### PR TITLE
fix(npm): lazily install package.json dependencies only when necessary

### LINKED ISSUE #17928: Deno 1.31.0 downloads Node modules without being asked to
Consider this situation:

```shell
$ ls
node_modules
package-lock.json
package.json
update-list.ts
...

$ cat package.json
{
  "dependencies": {
    "typescript": "^4.9.5"
  }
}

$ cat update-list.ts
console.log("test");

$ deno run update-list.ts
# downloads typescript from package.json dependencies
```

Deno has no need to look into Node modules here, since `update-list.ts` is its own standalone Deno script. However in this case, it still installs `typescript` first. This is unnecessary. Is this intentional? Is there going to be no way to have Deno scripts in an otherwise Node project?

### PR DESCRIPTION
**Pull request by dsherret**
This lazily does an "npm install" when any package name matches what's found in the package.json or when running a script from package.json with deno task.

Part of #17916

Closes #17928

### CODE REVIEW

File: test_util/src/lib.rs [hunk 1]
```diff
@@ -1948,17 +1948,60 @@ pub struct CheckOutputIntegrationTest<'a> {
 }
 
 impl<'a> CheckOutputIntegrationTest<'a> {
-  pub fn run(&self) {
+  pub fn run(self) {
```
Comment (dsherret) [inline test_util/src/lib.rs:1951]: Actually, I'm going to revert these test_util changes. I ended up not needing them, but I will land them in a separate PR.

File: cli/node/mod.rs [hunk 2]
```diff
@@ -285,6 +286,25 @@ pub fn node_resolve_npm_reference(
...
 
+/// Resolves a specifier that is pointing into a node_modules folder.
+///
+/// Note: This should be called whenever getting the specifier from
+/// a Module::External(module) reference because that module might
+/// not be fully resolved at the time deno_graph is analyzing it
+/// because the node_modules folder might not exist at that time.
+pub fn resolve_specifier_into_node_modules(
+  specifier: &ModuleSpecifier,
+) -> ModuleSpecifier {
```
Comment (bartlomieju) [inline cli/node/mod.rs:297]: Very handy 👍

File: cli/npm/installer.rs [hunk 3]
```diff
@@ -0,0 +1,88 @@
...
+struct PackageJsonDepsInstallerInner {
+  has_installed: AtomicBool,
+  npm_registry_api: NpmRegistryApi,
+  npm_resolution: NpmResolution,
+  package_deps: BTreeMap<String, NpmPackageReq>,
+}
+
+/// Holds and controls installing dependencies from package.json.
+#[derive(Debug, Clone, Default)]
+pub struct PackageJsonDepsInstaller(Option<Arc<PackageJsonDepsInstallerInner>>);
```
Comment (bartlomieju) [inline cli/npm/installer.rs:23]: Nice abstraction

File: cli/tests/integration/mod.rs [hunk 4]
```diff
@@ -30,6 +30,33 @@ macro_rules! itest_flaky(
...
+macro_rules! command_step(
+({$( $key:ident: $value:expr,)*})  => {
+  test_util::CheckOutputIntegrationTestCommandStep {
+    $(
+      $key: $value,
+      )*
+    .. Default::default()
+  }
+}
+);
```
Comment (bartlomieju) [inline cli/tests/integration/mod.rs:58]: Are these supposed to be included in this PR?

File: cli/tools/task.rs [hunk 5]
```diff
@@ -60,6 +60,11 @@ pub async fn execute_script(
         .await;
     Ok(exit_code)
   } else if let Some(script) = package_json_scripts.get(task_name) {
+    ps.package_json_deps_installer
+      .ensure_top_level_install()
+      .await?;
+    ps.npm_resolver.resolve_pending().await?;
```
Comment (bartlomieju) [inline cli/tools/task.rs:66]: Wouldn't it make sense for `ensure_top_level_install` to call `npm_resolver.resolve_pending` internally?

File: cli/tests/integration/mod.rs (hunk 4 above)
Comment (dsherret) [reply cli/tests/integration/mod.rs:58]: Nope, forgot to remove

File: cli/tools/task.rs (hunk 5 above)
Comment (dsherret) [reply cli/tools/task.rs:66]: No because when resolving with deno_graph we may call `ensure_top_level_install`, then wait for the full graph to be resolved, then finally call `resolve_pending()`. This is the only place they're done together so maybe in the future we could consider a helper method, but a helper method does make it more likely to accidentally call both. Also, the way the structs are right now with the lsp would require a bit of a big refactor to make this work. The code isn't great at the moment and more refactoring in the future would be nice.

Comment (bartlomieju) [reply cli/tools/task.rs:66]: Thanks for the explanation

**Review by bartlomieju — APPROVED** [review]
LGTM
