### PR TITLE
fix: make self and window getters only & make getterOnly ignore setting

### LINKED ISSUE #15765: `self` should be a getter
But now it's a usual property.

https://html.spec.whatwg.org/multipage/window-object.html#dom-self

image

Chromium:
image

Safari:
image

FF:
image

Deno:
image

### PR DESCRIPTION
**Pull request by crowlKats**
Closes #15765

### CODE REVIEW

File: runtime/js/98_global_scope.js [hunk 1]
```diff
@@ -296,31 +296,15 @@
...
     alert: util.writable(prompt.alert),
     confirm: util.writable(prompt.confirm),
     prompt: util.writable(prompt.prompt),
-    localStorage: {
-      configurable: true,
-      enumerable: true,
-      get: webStorage.localStorage,
-      // Makes this reassignable to make astro work
-      set: () => {},
-    },
```
Comment (bartlomieju) [inline runtime/js/98_global_scope.js:316]: I don't like this change, it will break Astro again

Comment (crowlKats) [reply runtime/js/98_global_scope.js:316]: @bartlomieju it doesnt. its changed to `getterOnly` with does this.

**Review by bartlomieju — APPROVED** [review]
