### PR TITLE
fix fromFileUrl use cases

### LINKED ISSUE #4108: CI fails on Windows
```
test result:  FAIL  704 passed; 2 failed; 0 ignored; 0 measured; 0 filtered out (30788.36ms)

There were 2 test failures.
 FAIL  GET / should serve html
Http: error sending request for url (http://127.0.0.1:8080/): connection error: An existing connection was forcibly closed by the remote host. (os error 10054)
    at Object.constructError ($deno$/errors.ts:69:13)
    at unwrapResponse ($deno$/dispatch_json.ts:40:12)
    at Object.sendAsync ($deno$/dispatch_json.ts:91:10)
    at async sendFetchReq ($deno$/fetch.ts:472:11)
    at async fetch ($deno$/fetch.ts:540:27)
    at async Object.fn (server_test.ts:31:16)
    at async Object.runTests ($deno$/testing.ts:157:7)
    at async runTestModules (runner.ts:234:3)
    at async main (runner.ts:276:5)
 FAIL  GET /ws should upgrade conn to ws
ConnectionRefused: No connection could be made because the target machine actively refused it. (os error 10061)
    at Object.constructError ($deno$/errors.ts:41:13)
    at unwrapResponse ($deno$/dispatch_json.ts:40:12)
    at Object.sendAsync ($deno$/dispatch_json.ts:91:10)
    at async Object.connect ($deno$/net.ts:292:15)
    at async connectWebSocket (file:///D:/a/deno/deno/std/ws/mod.ts:539:12)
    at async Object.fn (server_test.ts:40:8)
    at async Object.runTests ($deno$/testing.ts:157:7)
```

[/std/examples/chat/server_test.ts](https://github.com/denoland/deno/blob/master/std/examples/chat/server_test.ts) fails on Windows.

I don't have Windows PC, so it is difficult for me to test at hand...

Does anyone know the cause or solution for this?

Thanks.

### LINKED ISSUE #4647: websocket example broken on windows
https://github.com/denoland/deno/blob/6720a0dc02dc5a93472520e6d23ca033d7ec9d88/std/examples/chat/server.ts#L49

this line have some problems in windows while running locally , error text : 

```
error: Uncaught NotFound: The system cannot find the path specified. (os error 3)
► $deno$/ops/dispatch_json.ts:43:11
    at NotFound ($deno$/errors.ts:75:5)
    at unwrapResponse ($deno$/ops/dispatch_json.ts:43:11)
    at sendAsync ($deno$/ops/dispatch_json.ts:98:10)
```

deno version : 0.39.0
windows : 10 x64

i will make a PR for this

### PR DESCRIPTION
**Pull request by disizali**
after #4993 landed,
closes #4647,closes #4108

> a cleaner version of #4648 ( was my mistake to merge request from master branch )

### CODE REVIEW

**Comment by nayeemrmn** [comment]
@disizali Can you try re-enabling the chat server tests? They work for me locally now.

**Comment by disizali** [comment]
@nayeemrmn yeah works for me and on the ci too, re-enabled.

File: std/examples/chat/server_test.ts [hunk 1]
```diff
@@ -26,12 +26,8 @@ async function startServer(): Promise<Deno.Process> {
   return server;
 }
 
-// TODO: https://github.com/denoland/deno/issues/4108
-const ignore = build.os == "windows";
-
 test({
-  ignore,
-  name: "GET / should serve html",
+  name: "[examples/chat] GET / should serve html",
```
Comment (nayeemrmn) [inline std/examples/chat/server_test.ts:30]: 👍
