### PR TITLE
fix(ext/node): support numbered positional parameters in node:sqlite

### LINKED ISSUE #31719: `node:sqlite`: Numbered positional parameters (?1, ?2) cause "column index out of range" error
## Description

Deno's `node:sqlite` does not support numbered positional parameters (`?1`, `?2`), causing a "column index out of range" error. Node.js v24.7.0+ and standard SQLite support this syntax.

## Environment

- Deno: 2.6.3
- Platform: Linux (x86_64-unknown-linux-gnu)
- Node.js (for comparison): v24.10.0+

## Reproduction
```javascript
import { DatabaseSync } from 'node:sqlite';

const db = new DatabaseSync(':memory:');
db.exec(`
  CREATE TABLE users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    email TEXT NOT NULL
  )
`);

// ❌ Fails in Deno with "column index out of range"
const stmt = db.prepare('INSERT INTO users (name, email) VALUES (?1, ?2)');
stmt.run('Alice', 'alice@example.com');
```

**Result in Deno 2.6.3:** Error: column index out of range  
**Result in Node.js v24.10.0:** ✓ Works correctly

## Workarounds
```javascript
// Option 1: Implicit positional (recommended for Deno)
db.prepare('INSERT INTO users (name, email) VALUES (?, ?)');

// Option 2: Named parameters
db.prepare('INSERT INTO users (name, email) VALUES (:name, :email)');
stmt.run({ name: 'Alice', email: 'alice@example.com' });
```

## Expected Behavior

Numbered positional parameters should work like in Node.js v24.7.0+ (fixed in nodejs/node#59350):
```javascript
stmt.run(value1, value2); // Should bind to ?1, ?2 respectively
```

### Important use case: Parameter reuse
```sql
SELECT * FROM users WHERE id = ?1 OR parent_id = ?1
```

This pattern is common in SQLite but currently requires workarounds in Deno.

## References

- [SQLite parameter syntax documentation](https://www.sqlite.org/lang_expr.html#varparam)
- Node.js #59340, #59350: Same issue and fix
- Deno #28134, #28154: Named parameters support

### PR DESCRIPTION
**Pull request by magurotuna**
SQLite numbered positional parameters (?1, ?2, ?NNN) were incorrectly
treated as named parameters and skipped during binding, causing a
"column index out of range" error. This fix updates the parameter
binding logic to recognize that parameters whose names start with '?'
are positional and should be bound in order, just like anonymous
parameters (?).

Fixes #31719

### CODE REVIEW

File: ext/node/ops/sqlite/statement.rs [hunk 1]
```diff
@@ -543,20 +543,38 @@ impl StatementSync {
...
+            // Anonymous parameter - use this slot
+            break;
+          }
+          // Check if it's a numbered parameter (starts with '?')
+          // SAFETY: name_ptr is not null, checked above.
+          let first_byte = unsafe { *name_ptr as u8 };
+          if first_byte == b'?' {
+            // Numbered parameter like ?1, ?2 - use this slot
+            break;
+          }
```
Comment (littledivy) [inline ext/node/ops/sqlite/statement.rs]: nit, can be single if:
```suggestion
          if name_ptr.is_null()
              // SAFETY: short-circuiting guarantees name_ptr is non-null here
              || unsafe { *name_ptr as u8 == b'?' }
          {
              break;
          }
```

**Review by littledivy — APPROVED** [review]
LGTM!
