### PR TITLE
fix(init): use bare specifier for `jsr:@std/assert`

### LINKED ISSUE #24580: `deno init` should have `@std/assert` as bare specifier
```ts
import { assertEquals } from "jsr:@std/assert";
import { add } from "./mod.ts";

Deno.test(function addTest() {
  assertEquals(add(2, 3), 5);
});
```

Would be better to be:

```ts
import { assertEquals } from "@std/assert";
import { add } from "./mod.ts";

Deno.test(function addTest() {
  assertEquals(add(2, 3), 5);
});
```

Using a proper version constraint in the deno.json. If the version can't be determined then it should fallback to `@1`

### PR DESCRIPTION
**Pull request by dsherret**
Closes #24580

### CODE REVIEW

File: cli/tools/init/mod.rs [hunk 1]
```diff
@@ -53,10 +53,13 @@ Deno.test(function addTest() {
       "deno.json",
       &json!({
         "name": project_name,
-        "version": "1.0.0",
+        "version": "0.1.0",
```
Comment (dsherret) [inline cli/tools/init/mod.rs:56]: This is a better starting version IMO because you rarely release a `1.0.0` version the first time.

**Review by ry — APPROVED** [review]
