### PR TITLE
fix(task): match workspace directory name in --filter

### LINKED ISSUE #28620: deno task --filter fails to find tasks when workspace subproject's deno.json name doesn't match directory name
Version: Deno 2.2.5

When working with Deno workspaces, if a subproject's deno.json contains a name field that doesn't match its directory name, `deno task --filter` is unable to find tasks defined in that subproject.

#### 1. Create a workspace with the following structure:
```
my-workspace/
├── deno.json (workspace root)
└── client-a/
    └── deno.json (subproject)
└── server-b/
    └── deno.json (subproject)
```

#### 2. deno.json content:

In the root's `deno.json`, set:
```json
{
  "workspace": [
    "client-a",
    "server-b"
  ]
}
```

In the `client-a` `deno.json`, set:
```json
{
  "name": "@scope/client",
  "version": "0.1.0",
  "exports": "./mod.ts",
  "tasks": {
    "dev": "deno run -A mod.ts",
    "xx": "deno run -A mod.ts",
    "sd": "deno run -A mod.ts",
    "xd": "deno run -A mod.ts"
  },
  "license": "MIT",
  "imports": {
    "@std/assert": "jsr:@std/assert@1"
  }
}
```

In the `server-b` `deno.json`, set:
```json
{
  "name": "@scope/server-b",
  "version": "0.1.0",
  "exports": "./mod.ts",
  "tasks": {
    "dev": "deno run -A mod.ts",
    "xx": "deno run -A mod.ts",
    "sd": "deno run -A mod.ts",
    "xd": "deno run -A mod.ts"
  },
  "license": "MIT",
  "imports": {
    "@std/assert": "jsr:@std/assert@1"
  }
}
```
#### 3. Run
(1) run `deno task --filter "client-a" xd` 

Image

run `deno task --filter "client" xd` success

(2) run `deno task --filter "server-b" xd` success
run `deno task --filter "server" xd` success

(4) modify `client-a` `deno.json`, set:
```json
{
+  "name": "@scope/client-a",
  "version": "0.1.0",
  "exports": "./mod.ts",
  "tasks": {
    "dev": "deno run -A mod.ts",
    "xx": "deno run -A mod.ts",
    "sd": "deno run -A mod.ts",
    "xd": "deno run -A mod.ts"
  },
  "license": "MIT",
  "imports": {
    "@std/assert": "jsr:@std/assert@1"
  }
}
```
then run `deno task --filter "client-a" xd` success

[reproduce repository](https://github.com/kingsword09/deno-workspace-bug)

### PR DESCRIPTION
**Pull request by fibibot**
## Summary

\`deno task --filter <name>\` previously only matched the package's \`name\` field in \`deno.json\` / \`package.json\`. When a workspace member's directory name diverged from its package name, e.g. directory \`client-a/\` containing \`{ \"name\": \"@scope/client\" }\`, the matching directory-form got rejected:

\`\`\`
$ deno task --filter client-a xd
No matching task or script 'xd' found in selected packages.

$ deno task --filter client xd     # works
Task xd (@scope/client) deno eval 'console.log(\"client xd ran\")'
client xd ran
\`\`\`

Most other workspace tools (pnpm, yarn) accept either form, and the directory name is what shows up in error messages and \`deno task --filter '*'\` output, so users reasonably expect it to work.

Add a directory-name fallback to \`matches_package\` after the existing \`name\`-field checks. The fallback only kicks in when the folder declares a \`name\` so the workspace root (which is intentionally excluded from \`--filter '*'\` — every existing \`_filter_no_task\` snapshot relies on that) keeps its current behaviour.

Fixes #28620.

## Test plan

- [x] New spec test \`tests/specs/task/filter/deno_dir_name_match\` — workspace where \`./foo-dir\` has \`name: '@scope/totally-different-foo'\`; \`deno task --filter foo-dir dev\` finds and runs the task. Pre-fix this same setup printed the \"No matching task...\" message.
- [x] All 22 existing \`tests/specs/task/filter\` cases still pass, including \`deno_filter_no_task\` and \`npm_filter_no_task\` (which exercise the workspace-root-excluded behaviour).
- [x] Manual repro from the issue now succeeds.
- [x] \`./tools/format.js\`, \`cargo clippy --bin deno -- -D warnings\`.

### CODE REVIEW

File: cli/tools/task.rs [hunk 1]
```diff
@@ -725,9 +731,35 @@ fn matches_package(
     return true;
   }
 
+  // Fall back to the workspace member's directory name when neither
+  // deno.json nor package.json carry a `name`. Without this fallback,
+  // `deno task --filter <dir>` silently failed for members whose
+  // package name didn't happen to match the directory (#28620). The
+  // fallback is gated on the folder having no name so it never
+  // accidentally selects the workspace root (which doesn't carry a
+  // name and is intentionally excluded by `--filter *`).
```
Comment (lunadogbot) [inline cli/tools/task.rs]: The comment says "The fallback is gated on the folder having **no name** so it never accidentally selects the workspace root (which doesn't carry a name)", but the code reads `if has_name && ...` — i.e. it only fires when the folder *has* a name. The code is correct (workspace root has no name and must be excluded; members have names). The comment should read something like:

```
// Gated on the folder having a name so we never accidentally select the
// workspace root (which doesn't carry one and is intentionally excluded
// from `--filter *`).
```

**Review by lunadogbot — APPROVED** [review]
LGTM on the fix itself. Walked the cases against the test workspace:

- Root (no `name`) -> `has_name=false` -> fallback skipped -> falls through to `false`. Workspace-root exclusion preserved. ✓
- `foo-dir` (`name=@scope/totally-different-foo`) -> name regex misses, then `has_name=true`, `dir_name="foo-dir"`, regex matches. ✓
- `bar-dir` -> name regex misses, then `has_name=true`, `dir_name="bar-dir"`, regex doesn't match. ✓

`workspace_folder_dir_name` correctly tolerates trailing slash and rejects empty trailing segment. Spec test exercises both "matches by dir" and "doesn't match by dir".

One inline note below -- the comment on the fallback gate says the opposite of what the code does.

File: cli/tools/task.rs [hunk 2]
```diff
@@ -725,9 +731,35 @@ fn matches_package(
     return true;
   }
 
+  // Fall back to the workspace member's directory name when neither
+  // deno.json nor package.json carry a `name`. Without this fallback,
```
Comment (dsherret) [inline cli/tools/task.rs:735]: Comment seems wrong?

File: cli/tools/task.rs [hunk 3]
```diff
@@ -725,9 +731,35 @@ fn matches_package(
...
+  // package name didn't happen to match the directory (#28620).
+  // Gated on the folder having a name so we never accidentally select
+  // the workspace root (which doesn't carry one and is intentionally
+  // excluded from `--filter *`).
+  let has_name = config
+    .deno_json
+    .as_ref()
+    .and_then(|deno| deno.json.name.as_ref())
+    .or(config.pkg_json.as_ref().and_then(|pkg| pkg.name.as_ref()))
+    .is_some();
```
Comment (dsherret) [inline cli/tools/task.rs:746]: Why does this require a name?

Comment (bartlomieju) [reply cli/tools/task.rs:746]: The guard keeps the workspace root out of `--filter '*'` results. The root typically has no `name` field in its deno.json, so `has_name` is false and the directory-name fallback is skipped — which is the desired behavior (existing `_filter_no_task` snapshot tests depend on the root being excluded).

Workspace members do carry a `name`, so the fallback kicks in for them, letting `--filter foo-dir` match by directory when the package name diverges.

The comment above is just wrong though — it says "when neither … carry a `name`" but the code does `if has_name`. I'll send a fix.

File: cli/tools/task.rs (hunk 2 above)
Comment (bartlomieju) [reply cli/tools/task.rs:735]: Opened https://github.com/denoland/deno/pull/33540 to fix it

File: cli/tools/task.rs (hunk 3 above)
Comment (dsherret) [reply cli/tools/task.rs:746]: What if the workspace root has a name? What if a member doesn't have a name—should it match that?

If the code is trying to avoid the root, then shouldn't it be more explicit and check the directory path?

Comment (bartlomieju) [reply cli/tools/task.rs:746]: Yeah, that's a good point. I'll open a fix PR
