### PR TITLE
fix(npm): NPM_CONFIG_REGISTRY now correctly overrides .npmrc registry

### LINKED ISSUE #31392: The priority of npm_config_registry is lower than .npmrc.
Version: Deno 2.5.6

[deno-npmrc-test-log.txt](https://github.com/user-attachments/files/23723842/deno-npmrc-test.txt)

### PR DESCRIPTION
**Pull request by kajukitli**
Fixes #31392. Previously .npmrc registry had higher priority than NPM_CONFIG_REGISTRY env var, which contradicts npm behavior.

### CODE REVIEW

File: libs/npm/npm_rc/mod.rs [hunk 1]
```diff
@@ -162,9 +175,14 @@ impl NpmRc {
     &self,
     maybe_scope_name: Option<&str>,
     env_registry_url: &str,
+    get_env_var: &impl Fn(&str) -> Option<String>,
   ) -> (String, Arc<RegistryConfig>) {
+    // Check NPM_CONFIG_REGISTRY first (higher priority than .npmrc)
+    let env_override = get_env_var("NPM_CONFIG_REGISTRY");
```
Comment (dsherret) [inline libs/npm/npm_rc/mod.rs]: This doesn't make sense. The `env_registry_url` is already the NPM_CONFIG_REGISTRY value.

**Comment by kajukitli** [comment]
You're absolutely right that `env_registry_url` already contains the `NPM_CONFIG_REGISTRY` value if it was set.

The issue is that we need to distinguish between:
1. `NPM_CONFIG_REGISTRY` was explicitly set → use that value (via `env_registry_url`)
2. `NPM_CONFIG_REGISTRY` was not set → `env_registry_url` is just the default fallback, so use .npmrc registry if available

The original logic was:
```rust
.or(self.registry.as_deref())  // .npmrc registry
.unwrap_or(env_registry_url);  // NPM_CONFIG_REGISTRY or default
```

This meant if .npmrc had a registry, it would use that and never check if NPM_CONFIG_REGISTRY was set.

The fix checks `get_env_var("NPM_CONFIG_REGISTRY")` to determine if the environment variable was actually set, and if so, uses `env_registry_url` (which contains that value) instead of the .npmrc registry.

I've added comments to clarify this logic. Does this approach make sense?

**Comment by dsherret** [comment]
@kajukitli I don't like that we're reading from the env multiple times. Also, this will cause problems if `NPM_CONFIG_REGISTRY` fails to parse to a URL.

Can you update `npm_registry_url` to store an object that says whether it read the value from the env var? Then we can use that here.
