### PR TITLE
fix: type directives import

### LINKED ISSUE #2909: bug: Type definitions not working with import "./a.d.ts" syntax
Trying to provide definitions to `prettier` I hit this bug.

Given following script:
```
// @deno-types="./vendor/standalone.d.ts"
import "./vendor/standalone.js";
// @deno-types="./vendor/parser_typescript.d.ts"
import "./vendor/parser_typescript.js";
// @deno-types="./vendor/parser_babylon.d.ts"
import "./vendor/parser_babylon.js";
// @deno-types="./vendor/parser_markdown.d.ts"
import "./vendor/parser_markdown.js";
```
Type definitions are not loaded. It is because of `importExportRegEx` in `//js/type_directives.ts` - it can't match `import "./foo.d.ts"` syntax.

I added second regex to match above syntax and it seems to work fine. I'll post a PR shortly.

CC @kitsonk

### PR DESCRIPTION
**Pull request by bartlomieju**
Fixes #2909

I'm not sure about the test though

CC @kitsonk

### CODE REVIEW

File: js/type_directives.ts [hunk 1]
```diff
@@ -19,6 +18,12 @@ export function getMappedModuleName(
     return moduleName;
   }
   if (moduleName in typeDirectives) {
+    // @ts-ignore
```
Comment (kitsonk) [inline js/type_directives.ts]: What is the typescript error hear we are ignoring... I hate to ignore anything.

File: js/type_directives.ts [hunk 2]
```diff
@@ -33,15 +38,24 @@ export function getMappedModuleName(
...
 
-/** Matches `import` or `export from` statements and parses out the value of the
+/** Matches `import` statements and parses out the value of the
+ * module specifier in the second capture group:
+ *
+ *      import "./foo.js"
+ *
+ * [See Diagram](https://bit.ly/2maRCm8)
+ */
+const importRegEx = /(?:import|export)\s+(["'])((?:(?=(\\?))\3.)*?)\1/;
```
Comment (kitsonk) [inline js/type_directives.ts]: I think it would be better as a single RegEx.  The following keeps the same capture groups but makes the `from` optional.  While `export "foo";` isn't valid, it is unlikely to ever cause an issue.

```js
const importExportRegEx = /(?:import|export)\s+(?:[\s\S]*?from\s+)?(["'])((?:(?=(\\?))\3.)*?)\1/;
```

File: js/type_directives.ts (hunk 1 above)
Comment (kitsonk) [reply js/type_directives.ts]: Also, not sure why we need to log an error out here...  Seems like debug stuff that should be removed.

File: tests/type_definitions.ts [hunk 3]
```diff
@@ -1,4 +1,6 @@
 // @deno-types="./type_definitions/foo.d.ts"
 import { foo } from "./type_definitions/foo.js";
+// @deno-types="./type_definitions/fizz.d.ts"
+import "./type_definitions/fizz.js";
```
Comment (kitsonk) [inline tests/type_definitions.ts]: This seems valid to me.

File: js/type_directives.ts (hunk 1 above)
Comment (bartlomieju) [reply js/type_directives.ts]: Doh, yes, sorry...

**Comment by axetroy** [comment]
Should we add test cases to ensure that the parsing of the directives is correct?

eg.

```typescript
interface TestCase {
  input: string;
  output?: DirectiveInfo;
  error?: string;
}

test(() => {
  // defined testcase
  const testcases = [
    {
      input: "// some typescript code",
      output: undefined
    },
    {
      input: `// @deno-types="./foo.d.ts"`,
      output: {
        path: "...",
        start: 0,
        end: 0
      }
    }
  ];

  for (const testcase of testcases) {
    // run parser function
  }
});

```

**Comment by kitsonk** [comment]
@axetroy at the moment we don't have unit tests for the compiler and related modules, mostly because they have no run-time presence to access via the unit tests... we are getting to the point though where that will become possible to load the modules in the runtime and unit test them, but I see adding (actually restoring) that functionality to be seperate from this PR.
