### PR TITLE
URL support for Deno filesystem methods

### LINKED ISSUE #5916: URL support for Deno FS methods
I would like to be able to do something like that:

```ts
await Deno.open(new URL('../relative/path.txt', import.meta.url));
```

Currently this fails the TypeScript type checking, and even when bypassing it, it throws a `NotFound: No such file or directory (os error 2)` error.

FWIW Node.js `fs` module methods support it, and IMO it would be a neat addition to Deno.

### PR DESCRIPTION
**Pull request by actual-size**
This is my first contribution to any large open source project so let me know if I've done anything weird.

~~Also interesting in hearing if there's any call for any related methods to take URLs as well (particularly read/writeTextFile)~~

Decided to add as many as possible

closes #5916

### CODE REVIEW

File: cli/tests/unit/write_file_test.ts [hunk 1]
```diff
@@ -125,6 +139,20 @@ unitTest(
   }
 );
 
+unitTest(
+  { perms: { read: true, write: true } },
+  async function writeFileUrl(): Promise<void> {
+    const enc = new TextEncoder();
+    const data = enc.encode("Hello");
+    const fileUrl = new URL(`file://${Deno.makeTempDirSync()}/test.txt`);
+    await Deno.writeFile(fileUrl, data);
```
Comment (disizali) [inline cli/tests/unit/write_file_test.ts:148]: It will be great if you remove redundant files after testing.

Comment (actual-size) [reply cli/tests/unit/write_file_test.ts:148]: Sure thing, should I add that to the existing unit tests in this file as well, or just with the new tests?

Comment (disizali) [reply cli/tests/unit/write_file_test.ts:148]: for more clear PRs and commits, you can interact with other tests in another PR.
for now just care about new cases.

File: cli/js/util.ts [hunk 2]
```diff
@@ -78,3 +79,12 @@ export function immutableDefine(
     writable: false,
   });
 }
+
+// @internal
```
Comment (ry) [inline cli/js/util.ts:83]: This has no effect, please remove.

File: cli/js/util.ts [hunk 3]
```diff
@@ -78,3 +79,12 @@ export function immutableDefine(
...
+export function pathFromURL(url: URL): string {
+  return build.os == "windows"
+    ? new URL(url).pathname
+        .replace(/^\/*([A-Za-z]:)(\/|$)/, "$1/")
+        .replace(/\//g, "\\")
+    : new URL(url).pathname;
+}
```
Comment (ry) [inline cli/js/util.ts:90]: I would have expected something like 

```ts
if (url.schema == "file") {
  return url.pathname
} else {
  throw TypeError("Not a file URL");
}
```
This seems to be an important function - we need to figure out a way to have unit tests for it. Unfortunately, we only have a testing mechanism for public exposed methods. I think we should make use of "internalSymbol" to try to export this secretly from the Deno namespace for testing...

File: cli/tests/unit/write_text_file_test.ts [hunk 4]
```diff
@@ -1,4 +1,12 @@
 import { unitTest, assert, assertEquals } from "./test_util.ts";
+import { resolve, join } from "../../../std/path/mod.ts";
+
+const getResolvedUrl = (path: string): URL =>
+  new URL(
+    Deno.build.os === "windows"
+      ? "file:///" + resolve(path).replace(/\\/g, "/")
+      : "file://" + resolve(path)
```
Comment (ry) [inline cli/tests/unit/write_text_file_test.ts:8]: This bit of code which changes the backslashes to forward slashes is repeated a lot throughout the tests. It would be good to have a utility function for this.

File: cli/js/util.ts (hunk 3 above)
Comment (nayeemrmn) [reply cli/js/util.ts:90]: @ry https://github.com/denoland/deno/blob/f0ba814a79fe4f0791c4b0ef496a704356597467/cli/js/internals.ts#L8-L16

Comment (nayeemrmn) [reply cli/js/util.ts:90]: @ry Also, this function is pieced together from `std`: https://github.com/denoland/deno/blob/f0ba814a79fe4f0791c4b0ef496a704356597467/std/path/posix.ts#L437-L439 https://github.com/denoland/deno/blob/f0ba814a79fe4f0791c4b0ef496a704356597467/std/path/win32.ts#L916-L920 so as long as _they're_ tested and this one is kept in sync... 🤷‍♂️

File: cli/tests/unit/write_text_file_test.ts [hunk 5]
```diff
@@ -1,4 +1,12 @@
...
+  );
```
Comment (nayeemrmn) [inline cli/tests/unit/write_text_file_test.ts:9]: @actual-size The URL constructor does the backslash replacement for you, doesn't it?

```suggestion
function getResolvedUrl(path: string): URL {
  const url = new URL("file:///");
  url.pathname = resolve(path);
  return url;
}
```
This should handle every case correctly. Also see https://deno.land/manual/contributing/style_guide#top-level-functions-should-not-use-arrow-syntax.

Comment (guybedford) [reply cli/tests/unit/write_text_file_test.ts:9]: Note that you do need to manually handle percent decoding as well in the conversion to paths.

For reference the Node.js implementations can be seen here - https://github.com/nodejs/node/blob/master/lib/internal/url.js#L1290.

Node.js also specifically includes a check that no percent-encoded `/` is present to provide some vague security.

Comment (actual-size) [reply cli/tests/unit/write_text_file_test.ts:9]: @nayeemrmn Thanks for that, never thought to check if the constructor would do it for me. 
The exact snippet you've got there doesn't work, because the replacement only happens in the constructor, but I'll change my method to use the automatic replacement.

Comment (actual-size) [reply cli/tests/unit/write_text_file_test.ts:9]: @guybedford I think you've commmented on the wrong method here, but thanks for the link/advice about percent decoding! I'll start on working it into my implementation

File: cli/tests/unit/write_text_file_test.ts (hunk 4 above)
Comment (actual-size) [reply cli/tests/unit/write_text_file_test.ts:8]: I've moved it to cli/tests/unit/test_util.ts, if there's a better place to put it please let me know

Comment (actual-size) [reply cli/tests/unit/write_text_file_test.ts:8]: Judging by a few of these PR comments, it seems like the most important piece of this function was being masked by the way it's written. The important bit is the three slashes for windows and two slashes for *nix (actually it turns out the backslash replacement isn't even necessary).

I've removed this piece of logic entirely now, and I think all the tests are more readable for it, please let me know what you think.

File: cli/js/ops/fs/chmod.ts [hunk 6]
```diff
@@ -1,10 +1,17 @@
 // Copyright 2018-2020 the Deno authors. All rights reserved. MIT license.
 import { sendSync, sendAsync } from "../dispatch_json.ts";
+import { pathFromURL } from "../../util.ts";
 
-export function chmodSync(path: string, mode: number): void {
+export function chmodSync(path: string | URL, mode: number): void {
+  if (path instanceof URL) {
+    path = pathFromURL(path);
+  }
```
Comment (nayeemrmn) [inline cli/js/ops/fs/chmod.ts:8]: You could move the condition inside the function to have
```suggestion
  path = pathFromMaybeURL(path);
```
(no actual need to change the function name, though).

File: cli/tests/unit/chmod_test.ts [hunk 7]
```diff
@@ -18,6 +18,25 @@ unitTest(
   }
 );
 
+unitTest(
+  { ignore: Deno.build.os === "windows", perms: { read: true, write: true } },
+  function chmodSyncUrl(): void {
+    const enc = new TextEncoder();
+    const data = enc.encode("Hello");
+    const tempDir = Deno.makeTempDirSync();
+    const fileUrl = new URL(`file://${tempDir}/test.txt`);
```
Comment (piscisaureus) [inline cli/tests/unit/chmod_test.ts:27]: This is not a correct file URL. Correct file URLs always start with "file:///" except maybe when you're dealing with a network path (`\\server\share\dir\file`) which is a windows only thing that we don't need to support very urgently.

Comment (piscisaureus) [reply cli/tests/unit/chmod_test.ts:27]: nvm - missed that this is a posix-only test

File: cli/tests/unit/read_dir_test.ts [hunk 8]
```diff
@@ -19,6 +19,11 @@ unitTest({ perms: { read: true } }, function readDirSyncSuccess(): void {
   assertSameContent(files);
 });
 
+unitTest({ perms: { read: true } }, function readDirSyncWithUrl(): void {
+  const files = [...Deno.readDirSync(new URL("file:./cli/tests"))];
```
Comment (piscisaureus) [inline cli/tests/unit/read_dir_test.ts:23]: Although annoying, I don't think you can create cwd-relative file URLs like that.

Other platforms don't agree but none of them produces this outcome.

Chrome:
```
> new URL("file:./cli/tests")
URL {href: "file://./cli/tests", origin: "file://", protocol: "file:", username: "", password: "", …}
```

Node:
```
D:\deno>node
Welcome to Node.js v14.2.0.
Type ".help" for more information.
> new URL("file:./cli/tests")
URL {
  href: 'file:///cli/tests',
  origin: 'null',
  protocol: 'file:',
  username: '',
  password: '',
  host: '',
  hostname: '',
  port: '',
  pathname: '/cli/tests',
  search: '',
  searchParams: URLSearchParams {},
  hash: ''
}
```

Firefox:
```
> new URL("file:./cli/tests")
URL { href: "file:///cli/tests", origin: "null", protocol: "file:", username: "", password: "", host: "", hostname: "", port: "", pathname: "/cli/tests", search: "" }
```

Comment (actual-size) [reply cli/tests/unit/read_dir_test.ts:23]: @piscisaureus You're right, I looked back at RFC 8089 (which I know isn't quite accepted yet but it's the most complete description of the syntax I can find) and I have no idea where I got the syntax I'm using there. I'll revert back to absolute paths sometime this weekend.

Speaking of, based on whatwg+RFC 8089 it seems like the only way to do a relative URL of any kind is "scheme-less" but no `URL` object on any browser actually accepts it. Not sure what that's about, but I guess it doesn't affect this PR much anyway.

File: cli/tests/unit/stat_test.ts [hunk 9]
```diff
@@ -100,23 +147,56 @@ unitTest(
...
+    assert(
+      tempInfoByUrl.mtime !== null && now - tempInfoByUrl.mtime.valueOf() < 1000
+    );
+    assert(
+      tempInfoByUrl.birthtime === null ||
+        now - tempInfoByUrl.birthtime.valueOf() < 1000
+    );
+
+    Deno.removeSync(tempFile, { recursive: true });
+    Deno.removeSync(tempFileForUrl, { recursive: true });
```
Comment (ry) [inline cli/tests/unit/stat_test.ts:199]: It would be better if these additions were put into a new unit test

File: cli/tests/unit/stat_test.ts [hunk 10]
```diff
@@ -18,12 +18,45 @@ unitTest(
...
```
Comment (ry) [inline cli/tests/unit/stat_test.ts:59]: It would be better if these additions were put into a new unit test

**Comment by ry** [comment]
@nayeemrmn 

> Deno.remove("file:///path/to/file");
> Should we? It seems conventional to support this whenever a string | URL input type is seen.

If there's essentially zero cost to supporting it (which seems to be the case), then we should.

**Comment by actual-size** [comment]
@ry That's plenty of time for me to get this in. I'll make the requested changes + build in the same checks that node has, hopefully that should be fine.

I'll also add support for strings of file URLs, as @nayeemrmn mentioned.

**Comment by actual-size** [comment]
Almost everything is now done (it's 1:30 down under, so I'll complete the rest tomorrow), with the exceptions of:
- splitting the file URL stat/lstat tests out of the *Success tests
- implementing the percent encoded forward slash/backslash check [that Node does](https://github.com/nodejs/node/blob/master/lib/internal/url.js#L1292). I'd be interested to hear anyone's thoughts on if it should be included in Deno as well, since it will prevent some perfectly valid file names from being referenced by `file:` URL and is outside any specifications for the schema that I could find.
- exposing the internal pathFromURL function for testing

**Comment by piscisaureus** [comment]
I'm much in favor of adding URL support to our filesystem APIs.
However, I'd like to see some tests to confirm that special and non-ascii characters are getting encoded and decoded correctly. I'm not seeing any escaping/unescaping logic in the patch so this may have been overlooked. 

To get going, here are some files that I actually created on my (windows) filesystem and the URL chrome generated for them:

```
ampersand_&.txt                 file:///D:/weird_names/ampersand_&.txt
at_@.txt                        file:///D:/weird_names/at_@.txt
emoji_🙃.txt                    file:///D:/weird_names/emoji_%F0%9F%99%83.txt
percent_%.txt                   file:///D:/weird_names/percent_%25.txt
pound_#.txt                     file:///D:/weird_names/pound_%23.txt
space_ .txt                     file:///D:/weird_names/space_%20.txt
swapped_surrogate_pair_��.txt  file:///D:/weird_names/swapped_surrogate_pair_%EF%BF%BD%EF%BF%BD.txt    [does not work]
```

**Comment by piscisaureus** [comment]
> @nayeemrmn
> 
> > Deno.remove("file:///path/to/file");
> > Should we? It seems conventional to support this whenever a string | URL input type is seen.
> 
> If there's essentially zero cost to supporting it (which seems to be the case), then we should.

I don't agree, because I don't think that "os paths" can be reliably distinguished from URLs in some cases. E.g. I can just do this in my bash terminal:

```
piscisaureus@guru:~$ mkdir -p 'file:///path/to/file'
piscisaureus@guru:~$ find file\:/
file:/
file:/path
file:/path/to
file:/path/to/file
```

**Comment by actual-size** [comment]
@piscisaureus URI decoding is done just before returning a path from `pathFromURL`, but `URL` is responsible for encoding as you'd expect. The URL constructor in deno currently encodes spaces, and as far as I can see, nothing else.

I'm not sure the `URL` behaviour is particularly in scope for this PR though, since it does behave significantly differently from the browsers I've tested it in.

You're right about the impossibility of distinguishing file URLs from paths when a string is passed though, removing it is an easy enough change.

**Comment by ry** [comment]
@actual-size If you could add the test cases @piscisaureus provided and comment out the ones that don't work, we can land this and fix those later.

**Comment by ry** [comment]
I've added the test cases to the file in a TODO comment.

Issues with our URL encoding is important but orthogonal to this patch.
