### PR TITLE
fix(outdated): ensure "Latest" version is greater than "Update" version

### LINKED ISSUE #27038: `deno outdated` doesn't support pre-releases
Version: Deno 2.1.1

## Current behaviour

Currently, there's no indication that a new prerelease version is available. Running the `--update` command updates to the new version without any prior notice.

## Expected behaviour

The `outdated` command should also show prerelease versions.

## Example using `@fresh/core`

```
❯ deno outdated
┌─────────────────┬─────────┬─────────┬─────────┐
│ Package         │ Current │ Update  │ Latest  │
├─────────────────┼─────────┼─────────┼─────────┤
│ jsr:@deno/gfm   │ 0.9.0   │ 0.9.0   │ 0.10.0  │
├─────────────────┼─────────┼─────────┼─────────┤
│ jsr:@std/http   │ 1.0.9   │ 1.0.11  │ 1.0.11  │
├─────────────────┼─────────┼─────────┼─────────┤
│ jsr:@std/path   │ 1.0.7   │ 1.0.8   │ 1.0.8   │
├─────────────────┼─────────┼─────────┼─────────┤
│ npm:preact      │ 10.24.3 │ 10.25.0 │ 10.25.0 │
├─────────────────┼─────────┼─────────┼─────────┤
│ npm:tailwindcss │ 3.4.11  │ 3.4.11  │ 3.4.15  │
└─────────────────┴─────────┴─────────┴─────────┘
```

```
❯ deno outdated --update
Updated 4 dependencies:
 - jsr:@fresh/core 2.0.0-alpha.23 -> 2.0.0-alpha.25
 - jsr:@std/http            1.0.9 ->         1.0.11
 - jsr:@std/path            1.0.7 ->          1.0.8
 - npm:preact             10.24.3 ->        10.25.0
```

### PR DESCRIPTION
**Pull request by nathanwhit**
Fixes #27038.

Previously, for NPM packages the latest version was the version with the "latest" tag. For JSR packages, the latest version was the greatest version that matched a `*` version requirement. Unfortunately, that doesn't work well with pre-release versions.

This PR changes it so that the latest version is always > the currently requested version.
For NPM: if "latest" tag > current then "latest" tag; otherwise the greatest version that is >= current
For JSR: greatest version >= current

This is the most reasonable behavior I could come up with. For example,

```
versions:
2.0.0-beta.2
2.0.0-beta.1
1.0.0 => "latest" tag

with a version req `^2.0.0-beta.1`

previously:
"Update" column => 2.0.0-beta.2
"Latest" column => 1.0.0

now:
"Update" column => 2.0.0-beta.2
"Latest" column => 2.0.0-beta.2
```

### CODE REVIEW

File: cli/tools/registry/pm/deps.rs [hunk 1]
```diff
@@ -613,6 +614,9 @@ impl DepManager {
       )
       .await?;
 
+    self
+      .dependencies_resolved
+      .store(true, std::sync::atomic::Ordering::Relaxed);
```
Comment (dsherret) [inline cli/tools/registry/pm/deps.rs:619]: We should change this to use `SyncFlag` sometime in the future as the api is slightly nicer.

File: cli/tools/registry/pm/deps.rs [hunk 2]
```diff
@@ -670,14 +670,26 @@ impl DepManager {
...
             let semver_compatible =
               self.npm_fetch_resolver.req_to_nv(semver_req).await;
-            let latest = self.npm_fetch_resolver.req_to_nv(&latest_req).await;
+            let info =
+              self.npm_fetch_resolver.package_info(&semver_req.name).await;
+            let latest = info
+              .and_then(|info| {
+                let latest_tag = info.dist_tags.get("latest")?;
+                let lower_bound =
+                  semver_compatible.as_ref().map(|nv| &nv.version)?;
```
Comment (dsherret) [inline cli/tools/registry/pm/deps.rs:682]:
```suggestion
                  semver_compatible.as_ref()?.version;
```

File: cli/tools/registry/pm/deps.rs [hunk 3]
```diff
@@ -670,14 +670,26 @@ impl DepManager {
...
+                if latest_tag > lower_bound {
+                  Some(latest_tag.clone())
+                } else {
+                  latest_version(Some(latest_tag), info.versions.keys())
+                }
+              })
+              .map(|version| PackageNv {
+                name: semver_req.name.clone(),
+                version: version.clone(),
```
Comment (dsherret) [inline cli/tools/registry/pm/deps.rs:691]:
```suggestion
                version,
```

I think.

**Review by dsherret — APPROVED** [review]
Looks good!
