### PR TITLE
fix(ext/node/net): emit `error` before `close` when connection is refused

### LINKED ISSUE #19078: error: Uncaught Error: read ECONNRESET
Despite access npm:mongodb in try/catch, runtime is throwing Uncaught error, whenever db drops the connection.

```
error: Uncaught Error: read ECONNRESET
    at node_internal_captureLargerStackTrace (ext:deno_node/internal/errors.ts:89:11)
    at node_internal_errnoException (ext:deno_node/internal/errors.ts:137:12)
    at TCP.onStreamRead [as onread] (ext:deno_node/internal/stream_base_commons.ts:205:24)
    at TCP.#read (ext:deno_node/internal_binding/stream_wrap.ts:223:18)
    at eventLoopTick (ext:core/01_core.js:166:11)
```

### LINKED ISSUE #21951: Incorrect order of close vs error event with Node.js `net` polyfill on ECONNREFUSED
Version: Deno v1.39.4.

Consider the following script, assuming that you don't have anything running on port 27025 you should get an ENOENT error.

```
import net from 'node:net';
const socket = net.createConnection('mongodb://127.0.0.1:27025/test');
socket.on('close', () => console.log('close'));
socket.on('error', err => console.log('Error', err));
```

In Deno v1.39.4, this script outputs the following. Notice that `close` comes _before_ `error`. I believe this event order is incorrect: [the Node.js docs indicate the `close` event means that no further events should be emitted](https://nodejs.org/api/stream.html#event-close).

```
$ deno run --unstable --node-modules-dir --allow-net --allow-read --allow-sys --allow-env gh-14237.js
:white_check_mark: Granted write access to "mongodb://127.0.0.1:27025/test".
close
Error Error: connect ENOENT mongodb://127.0.0.1:27025/test
  at __node_internal_captureLargerStackTrace (ext:deno_node/internal/errors.ts:91:9)
  at __node_internal_exceptionWithHostPort (ext:deno_node/internal/errors.ts:215:10)
  at PipeConnectWrap._afterConnect [as oncomplete] (node:net:170:16)
  at Pipe.afterConnect (ext:deno_node/internal_binding/connection_wrap.ts:43:11)
  at ext:deno_node/internal_binding/pipe_wrap.ts:138:14 {
 errno: -2,
 code: "ENOENT",
 syscall: "connect",
 address: "mongodb://127.0.0.1:27025/test"
}
```

In Node v21.4.0, consider the following slightly modified but equivalent script.

```javascript
const net = require('net');
const socket = net.createConnection('mongodb://127.0.0.1:27025/test');
socket.on('close', () => console.log('close'));
socket.on('error', err => console.log('Error', err));
```

In the output, the event order is reversed: `close` comes _after_ `error`:

```
$ node gh-14237-2.js
Error Error: connect ENOENT mongodb://127.0.0.1:27025/test
  at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1595:16) {
 errno: -2,
 code: 'ENOENT',
 syscall: 'connect',
 address: 'mongodb://127.0.0.1:27025/test'
}
close
```

I think this issue is the root cause of #19078 and https://github.com/Automattic/mongoose/issues/14237.

### LINKED ISSUE #23665: Test fails in v1.43
the following test passes in `v1.42.0` but fails in `v1.43.1`

```ts
import {
  afterEach,
  beforeEach,
  describe,
  it,
} from 'https://deno.land/std@0.224.0/testing/bdd.ts';
import { MongoMemoryServer } from 'npm:mongodb-memory-server-core';
import { MongoClient, ObjectId } from 'npm:mongodb';
import { assert } from 'https://deno.land/std@0.224.0/assert/assert.ts';

let mongod: MongoMemoryServer;
let client: MongoClient;

describe({
  name: 'deno',
  fn: () => {
    beforeEach(async () => {
      mongod = await MongoMemoryServer.create();
      client = new MongoClient(mongod.getUri());
      await client.connect();
    });

    afterEach(async () => {
      await client.close();
      await mongod.stop();
    });

    it('test', async () => {
      const _id = new ObjectId();

      const { insertedId } = await client.db().collection('test').insertOne({
        _id,
      });

      assert(insertedId.equals(_id));
    });
  },
});


```

```
error: Error: connect ECONNREFUSED 127.0.0.1:59453 - Local (undefined:undefined)
    at __node_internal_captureLargerStackTrace (ext:deno_node/internal/errors.ts:62:9)
    at __node_internal_exceptionWithHostPort (ext:deno_node/internal/errors.ts:148:10)
    at TCPConnectWrap._afterConnect [as oncomplete] (node:net:130:16)
This error was not caught from a test and caused the test runner to fail on the referenced module.
It most likely originated from a dangling promise, event/timeout handler or top-level code.

 FAILURES 

./db/deno.test.ts (uncaught error)

FAILED | 0 passed | 2 failed (608ms)

error: Test failed
```

### LINKED ISSUE #24376: A node.js stream polyfill issue: the error thrown within the process.nextTick callback cannot be caught, leading to unexpected exit when connection closed
**Description**: I'm encountering a problem while running a script which makes a connection to MongoDB v6.8.0. Initially, everything works fine, but after a network connection break, any further query to the database will cause the proces to exit abruptly, alongside an uncatchable uncaught error (connect ECONNREFUSED).

**Deno**: Version 1.44.4
**MongoDB**: MongoDB driver for Node.js, `mongodb@6.8.0`

**Relevant Error Output**:
```sh
error: Uncaught Error: connect ECONNREFUSED 127.0.0.1:27017 - Local (undefined:undefined)
    at __node_internal_captureLargerStackTrace (ext:deno_node/internal/errors.ts:93:9)
    at __node_internal_exceptionWithHostPort (ext:deno_node/internal/errors.ts:217:10)
    at TCPConnectWrap._afterConnect [as oncomplete] (node:net:171:16)
    at TCP.afterConnect (ext:deno_node/internal_binding/connection_wrap.ts:43:11)
    at ext:deno_node/internal_binding/tcp_wrap.ts:302:14
    at eventLoopTick (ext:core/01_core.js:168:7)
```

Here is the program code:
```js
// main.js
import { MongoClient }  from 'npm:mongodb';

async function main(){
  const uri = "mongodb://127.0.0.1:27017";

  const client = new MongoClient(uri);

  try {
      // Connect to the MongoDB cluster
      await client.connect();

      setInterval(async () => {
        await listDatabases(client);
      }, 2000);

  } catch (e) {
      console.error('main error', e);
      // await client.close();
  }
}

main();

async function listDatabases(client){
  try {
    const databasesList = await client.db().admin().listDatabases();

    console.log("Databases:", databasesList.databases.map(db => `${db.name}`).join(', '));
  } catch (e) {
    console.error('listDatabases error', e);
  }
};
```

In this code, I'd like to keep the process running even a network disconnection happens. However, the outcome is not expected.

**Digging-in**: It seems like the error stems from Deno's `_stream.mjs`, which is a Node.js polyfill. Specifically, an error thrown within a `process.nextTick` callback in the stream's destroy logic isn't being caught, and cannot be caught in the main process.

```js
// function _destroy(self2, err, cb) {
// ...
process.nextTick(emitErrorCloseNT, self2, err2); // error in the nextTick is uncaught
// ...

// ...
function emitErrorCloseNT(self2, err) {
      emitErrorNT(self2, err);
      emitCloseNT(self2);
}
// ...

// ...
function emitErrorNT(self2, err) {
      const r = self2._readableState;
      const w = self2._writableState;
      if (w && w.errorEmitted || r && r.errorEmitted) {
        return;
      }
      if (w) {
        w.errorEmitted = true;
      }
      if (r) {
        r.errorEmitted = true;
      }
      self2.emit("error", err); // error in the nextTick is uncaught
}
// ...

// EventEmitter.prototype.emit = function emit(type) {
// ...
if (er instanceof Error) {
      throw er; // throw an error
}
// ...
```

**Comparison with Node.js**: When the same script is executed using Node.js v22.1.0 (with the MongoDB import adjusted to `import { MongoClient } from 'mongodb';`), the error `MongoNetworkError: connect EHOSTUNREACH` is caught, and the main process does not exit unexpectedly.

This is where as far as I can take it for now.

**Possibly related issues**
#21951
#16633
#19078
#23665
https://github.com/Automattic/mongoose/issues/14237

**Request for Help**: I'm looking for assistance to understand why this discrepancy exists between Deno and Node.js, and how to correctly handle MongoDB disconnection errors in Deno to prevent the program from crashing. Any insights or solutions for this issue would be greatly appreciated.

### PR DESCRIPTION
**Pull request by kt3k**
This PR delays the timing of callback called in `socket._handle.close(cb)` call, and causes `error` event happens before `close` event when `socket.destroy()` is called.

- This prevents uncaught error with `npm:mongodb` package (#24376, #19078).

closes #24376
closes #23665
closes #21951
closes #19078

Note: The changes in `unit_node/tls_test.ts`, `unit_node/http_test.ts`, and `polyfills/dgram.ts` were needed for avoiding op leak error in testing. They are not directly related to the fix.

TODO:
- [x] ~~enable test cases~~ Write test cases (I couldn't find the exact test case which exercise this behavior of `net.createConnection` in node.js native test cases)

### CODE REVIEW

**Comment by kt3k** [comment]
@bartlomieju PTAL

File: ext/node/polyfills/internal_binding/handle_wrap.ts [hunk 1]
```diff
@@ -40,7 +38,7 @@ export class HandleWrap extends AsyncWrap {
 
   close(cb: () => void = () => {}) {
     this._onClose();
-    queueMicrotask(cb);
+    setTimeout(cb, 0);
```
Comment (bartlomieju) [inline ext/node/polyfills/internal_binding/handle_wrap.ts:41]: Have you tried using `nextTick` instead?

**Review by bartlomieju — APPROVED** [review]
LGTM, thanks for looking into this one!

File: ext/node/polyfills/internal_binding/handle_wrap.ts (hunk 1 above)
Comment (kt3k) [reply ext/node/polyfills/internal_binding/handle_wrap.ts:41]: `nextTick` doesn't delay enough because `emitErrorNT` callback is called at next tick (and that's registered after `_handle.close` callback.

https://github.com/denoland/deno/blob/29934d558c188fdc3406706da19921ca5a389383/ext/node/polyfills/net.ts#L1418-L1426

In the above code, the callback for `this._handle.close` is the one delayed in this PR (that emits `close`). `cb` in the above is `onDestroy` in `_stream.mjs`, which calls `process.nextTick(() => stream.emit("error"))`.

So we need to delay the close callback at least 2 ticks.
