### PR TITLE
fix(ext/node): add tls.getCaCertificates()

### LINKED ISSUE #31207: `node:tls` does not implement `getCACertificates`
## Version

deno 2.5.6 (stable, release, x86_64-unknown-linux-gnu)

v8 14.0.365.5-rusty

typescript 5.9.2

## Steps to reproduce

1. Create file `test.mjs` with the following content:
```js
import tls from 'node:tls';

console.log(tls.getCACertificates('system'));
```
2. Run the file like `deno test.mjs`.

## Expected Behaviour
The list of all CA certificates installed in the system should be output.

## Actual Behaviour
`error: Uncaught (in promise) TypeError: tls.getCACertificates is not a function`

### PR DESCRIPTION
**Pull request by littledivy**
Closes https://github.com/denoland/deno/issues/31207

Adds `tls.getCACertificates(type)` which returns CA certificates by type:
- `"bundled"` — built-in webpki root certificates
- `"system"` — OS-level native CA certificates
- `"extra"` — certificates from `NODE_EXTRA_CA_CERTS` env var
- `"default"` — bundled + extra combined

Also:
- Adds JS-level validation (`validateString`/`validateOneOf`) with proper `ERR_INVALID_ARG_TYPE`/`ERR_INVALID_ARG_VALUE` errors
- Caches results per type with `Object.freeze()`
- Requires `--allow-sys=ca` permission for both `tls.rootCertificates` and `tls.getCACertificates()`
- Adds `"ca"` as a new `--allow-sys` variant
- Normalizes PEM format (strips trailing newline from `der_to_pem`)

### CODE REVIEW

**Review by bartlomieju — COMMENTED** [review]
@littledivy do you need any help with this PR?

**Comment by bartlomieju** [comment]
I think we might want to require `--allow-sys=ca` for this

**Review by fibibot — COMMENTED** [review]
Substance is clean. The four `cert_type` branches in `op_get_ca_certificates` are reasonable Node-compat plumbing — bundled / system / extra / default, with `parse_extra_ca_certs` reading `NODE_EXTRA_CA_CERTS` at runtime and splitting on `-----END CERTIFICATE-----` (the simple split is fine here because the only multi-cert delimiter the spec allows is the END marker). `validateString`/`validateOneOf` on the JS side mirrors Node's input validation. The `cachedCACertificates` per-type cache plus `Object.freeze()` on the array matches Node's caching behavior in `lib/tls.js`.

CI fully green: 135 SUCCESS, 0 FAILURE.

The trailing-newline normalization in `der_to_pem` (dropping `\n` so the format matches Node's per-cert string) is a nice cleanup that also eliminates the `StringPrototypeReplace(v, /\n$/, "")` workaround in `ensureLazyRootCertificates`. ✓

## Three escalation triggers — needs @bartlomieju's deliberate sign-off

This is well outside fibibot's autonomous-APPROVE scope:

1. **New public API on `node:tls`**: `tls.getCACertificates(type)` is a new module-level function — not just plumbing for an existing Node export. Once it ships, removing or renaming it is a breaking change.

2. **New permission descriptor**: `"ca"` added to `SysDescriptor::parse`'s allowlist (`runtime/permissions/lib.rs:2885`) and to the public `Deno.SysPermissionDescriptor.kind` type union (`cli/tsc/dts/lib.deno.ns.d.ts:4366`). Both are durable additions to the permission-system surface.

3. **Breaking change to `tls.rootCertificates`**: previously had no permission gate. After this PR, reading it throws `NotCapable` unless `--allow-sys=ca` is granted. Existing code that reads `tls.rootCertificates` (a stable Node API) without that flag will break. Worth a release-note callout.

## Coordination heads-up

The `op_get_root_certificates` permission gate change here is *also* in @bartlomieju's open PR #33641 (commit `b448cd98` "require --allow-sys=ca for tls.rootCertificates") — bundled there alongside the unrelated TLS Happy Eyeballs fix. Whichever lands second will hit a real merge conflict on `ext/node/ops/tls.rs:55` and `runtime/permissions/lib.rs:2885`. Easiest path is to drop the permission commit from #33641 and let this PR land it cleanly.

Pinging the original review thread: @littledivy, the PR has been open since February — is this still on your queue, or should the substance get rolled into #33641? Either way, @bartlomieju to weigh in on the API/permission shape.

File: ext/node/ops/tls.rs [hunk 1]
```diff
@@ -52,34 +54,109 @@ pub(crate) struct NodeTlsState {
...
+
+#[allow(
+  clippy::disallowed_methods,
+  reason = "NODE_EXTRA_CA_CERTS is read from env at runtime"
+)]
+fn parse_extra_ca_certs() -> Vec<String> {
+  let Ok(extra_ca_certs_file) = std::env::var("NODE_EXTRA_CA_CERTS") else {
+    return vec![];
+  };
+  let Ok(contents) = std::fs::read_to_string(&extra_ca_certs_file) else {
```
Comment (bartlomieju) [inline ext/node/ops/tls.rs]: This one should use `sys_traits` crate and not require supressing clippy lint
