### PR TITLE
fix(ext/node): `util.parseEnv` and `process.loadEnvFile` compatibility

### LINKED ISSUE #30952: `parseEnv` from `node:util` not supported in Deno
Version: Deno 2.5.3

Hi,

I would like to report a behavior I observed when running the following code snippet:

```javascript
import { parseEnv } from 'node:util'
```

Running this gives the following error:

```
PS C:\Users\Kevin\Downloads\a\29_09_2025> deno run 56775_toreport.js
error: Uncaught SyntaxError: The requested module 'node:util' does not provide an export named 'parseEnv'
import { parseEnv } from 'node:util'
         ^
    at <anonymous> (file:///C:/Users/Kevin/Downloads/a/29_09_2025/56775_toreport.js:6:10)
```

This module works in NodeJS. The Deno compatibility documentation also mentions that it supports `node:util` (https://docs.deno.com/api/node/#utilities)

### PR DESCRIPTION
**Pull request by Tango992**
Continues the work from #31856. Closes #30952.

Ported the node's env parser instead of using dotenvy, since there are some differences that makes the node compat test won't pass if dotenvy was used.

Allows https://github.com/nodejs/node/blob/v24.12.0/test/parallel/test-util-parse-env.js to pass

### CODE REVIEW

File: ext/node/lib.rs
Comment (Hajime-san) [inline ext/node/lib.rs]: Oh, when I tried to update Fresh's Vite to version 8, I got an error saying that `parseEnv` was not implemented, so I just implemented it just now.😄

FYI:
Yeah, the implementation of `dotenvy` is not compatible to Node.js. Should use own implementation.

```bash
% target/release/deno --version
deno 2.6.9 (stable, release, aarch64-apple-darwin)
v8 14.5.201.2-rusty
typescript 5.9.2
% target/release/deno eval "import * as process from 'node:process'; process.loadEnvFile('valid.env');"
error: Uncaught (in promise) Error: Error parsing line: '`    backticks    `', error at line index: 5
    at Module.loadEnvFile (node:process:580:10)
    at file:///Users/hajime_masutani/repository/deno/$deno$eval.mts:1:50

# ref:
# https://github.com/denoland/node_test/blob/170b25ab9080b9d58d21b582fbf28ee5676b8387/test/fixtures/dotenv/valid.env
```

File: ext/node/ops/util.rs [hunk 1]
```diff
@@ -258,3 +258,194 @@ pub fn op_node_get_own_non_index_properties<'s>(
...
+
+#[op2]
+pub fn op_node_parse_env<'a>(
+  scope: &mut v8::PinScope<'a, '_>,
+  #[string] input: &str,
+) -> v8::Local<'a, v8::Object> {
+  let vars = v8::Object::new(scope);
+
+  // Ported from https://github.com/nodejs/node/blob/70f6b58ac655234435a99d72b857dd7b316d34bf/src/node_dotenv.cc#L127-L303
+  {
```
Comment (Hajime-san) [inline ext/node/ops/util.rs]: I recommend you to pass the parsed string result through a closure instead of directly converting it to a V8 value, so that `parse_env_content_hook` can be shared between `util.parseEnv` and `process.loadEnv`.

Context of `process.loadEnv`:
https://github.com/denoland/deno/pull/32183#discussion_r2809477954

Implementation:
https://github.com/nodejs/node/blob/9cc7fcc26dece769d9ffa06c453f0171311b01f8/src/node_process_methods.cc#L617
https://github.com/nodejs/node/blob/9cc7fcc26dece769d9ffa06c453f0171311b01f8/src/node_dotenv.cc#L351

Feel free to use my implementation.
https://github.com/denoland/deno/compare/main...Hajime-san:deno:parse_env

Comment (Tango992) [reply ext/node/ops/util.rs]: Great, thanks!

File: ext/node/lib.rs [hunk 2]
```diff
@@ -123,11 +125,312 @@ fn op_node_load_env_file(
     )
     .map_err(DotEnvLoadErr::Permission)?;
 
-  dotenvy::from_filename(path).map_err(DotEnvLoadErr::DotEnv)?;
+  #[allow(clippy::disallowed_methods)]
+  let contents = fs::read_to_string(path)?;
```
Comment (Hajime-san) [inline ext/node/lib.rs:130]: Sorry for my code is written carelessly. If we need to implement it strictly, it seems best to separate errors into file open and invalid content.

https://github.com/nodejs/node/blob/a57893b7993daa111849b161e62a926848e40da3/src/node_process_methods.cc#L603-L634
https://github.com/nodejs/node/blob/1523d66a695ad1d1743e84966ff11859cc3dfd54/src/node_dotenv.cc#L321-L349

Comment (Tango992) [reply ext/node/lib.rs:130]: Ah noted, no problem I'll adjust to it

File: ext/node/lib.rs [hunk 3]
```diff
@@ -123,7 +126,32 @@ fn op_node_load_env_file(
...
+
+  parse_env_content_hook(&contents, |key, value| {
+    // Follows Node.js behavior where null bytes are stripped from env keys and values
```
Comment (Hajime-san) [inline ext/node/lib.rs:133]: Good catch!

probably related:
- https://github.com/nodejs/node/issues/54781#issuecomment-2332633069

File: ext/node/ops/dotenv.rs
Comment (bartlomieju) [inline ext/node/ops/dotenv.rs:1]: Please add some more unit tests here

Comment (bartlomieju) [reply ext/node/ops/dotenv.rs:1]: And ideally we could move this code to `libs/` into a new crate, that way we can later reuse it to get rid of `dotenvy` completely.

**Comment by bartlomieju** [comment]
LGTM, I'll let David take another look before approving
