### PR TITLE
fix(lsp): better handling of `data:` urls

### LINKED ISSUE #18524: LSP errors very agressively on files containing `data:` url imports
```
import {} from "data:application/typescript,42";
import "data:application/javascript,export%20const%20value%20%3D%2069%3B";
import _a from "data:application/typescript,export default { 0: 1 };";
import _b from "data:application/typescript;base64,ZXhwb3J0IGRlZmF1bHQgMHhERUFEQkVFRg==";
import { Nani } from "data:application/javascript,export const Nani = '何'";
```

image

The errors are emitted any time any file is changed in the project, after this source is loaded into tsc.

### PR DESCRIPTION
**Pull request by dsherret**
1. Log instead of error when the referrer can't be found
2. Fixes typescript to resolve data urls correctly. Properly documented here: https://github.com/denoland/TypeScript/pull/4/files#diff-180da7c288743d11d8590d30f0c07c48e5dcf291aa671bbea0dd520a9a1359d2

Closes #18524

### CODE REVIEW

File: cli/tsc/00_typescript.js [hunk 1]
```diff
@@ -6712,6 +6712,9 @@ ${lanes.join("\n")}
       }
       return ~path.length;
     }
+    if (path.startsWith("data:")) {
+      return ~path.length;
+    }
```
Comment (dsherret) [inline cli/tsc/00_typescript.js:6717]: https://github.com/denoland/TypeScript/pull/4/files#diff-180da7c288743d11d8590d30f0c07c48e5dcf291aa671bbea0dd520a9a1359d2

**Review by mmastrac — APPROVED** [review]
LGTM
