### PR TITLE
fix: hide progress bars when showing permission prompt

### LINKED ISSUE #16860: Progress bar conflicts with permission prompt
Given the following script and a clean $DENO_CACHE/deps folder:

```ts
// main.ts
const url = "https://deno.land/x/ts_morph/mod.ts"
const test = await import(url);
```

```
> deno run main.ts
✅ Granted net access to "deno.land".
Download ⠹ https://deno.land/x/ts_morph/mod.ts
Warning Implicitly using latest version (17.0.1) for https://deno.land/x/ts_morph/mod.ts
Download ⠹ https://deno.land/x/ts_morph@17.0.1/mod.ts
⚠️  ┌ Deno requests net access to "deno.land".
   ├ Run again with --allow-net to bypass this prompt.
Download ⠸ https://deno.land/x/ts_morph@17.0.1/mod.ts
```

The permission prompt should disable any progress bars.

### PR DESCRIPTION
**Pull request by dsherret**
Also adds download bytes progress when downloading remote specifiers.

Closes #16860

https://user-images.githubusercontent.com/1609021/208489297-2bafafb5-1684-4a8f-93cf-d03cb38ddcb5.mp4

### CODE REVIEW

File: cli/util/draw_thread.rs [hunk 1]
```diff
@@ -30,7 +30,6 @@ impl Drop for DrawThreadGuard {
 
 #[derive(Debug, Clone)]
 struct InternalEntry {
-  priority: u8,
```
Comment (dsherret) [inline cli/util/draw_thread.rs:33]: Removed because we're not using this functionality. I investigated a bit at making progress bars show while displaying the permission prompt and it would be too complicated.

File: runtime/permissions/prompter.rs [hunk 2]
```diff
@@ -38,11 +38,11 @@ pub fn permission_prompt(
 }
 
 pub fn set_prompt_callbacks(
-  before_callback: Option<PromptCallback>,
-  after_callback: Option<PromptCallback>,
+  before_callback: PromptCallback,
+  after_callback: PromptCallback,
```
Comment (bartlomieju) [inline runtime/permissions/prompter.rs:42]: I guess there won't be a situation where we disable this callbacks so I guess it's fine to change the signature here

**Review by bartlomieju — APPROVED** [review]
LGTM, tested locally, works great 👍

File: runtime/permissions/prompter.rs (hunk 2 above)
Comment (dsherret) [reply runtime/permissions/prompter.rs:42]: Yeah, we can add it back if we need it.
