### PR TITLE
fix(deno info): Never type check

### LINKED ISSUE #6935: Deno info should not type check

### PR DESCRIPTION
**Pull request by nayeemrmn**
Closes #6935.

### CODE REVIEW

File: cli/flags.rs [hunk 1]
```diff
@@ -849,7 +849,10 @@ TypeScript compiler cache: Subdirectory containing TS compiler output.",
     )
     .arg(Arg::with_name("file").takes_value(true).required(false))
     .arg(ca_file_arg())
-    .arg(no_check_arg())
+    // TODO(nayeemrmn): `--no-check` has been removed for `deno info`, but it
+    // shouldn't cause flag parsing to fail for backward-compatibility. Remove
+    // this line for v2.0.0.
+    .arg(no_check_arg().hidden(true))
```
Comment (ry) [inline cli/flags.rs:855]: 👍
