### PR TITLE
fix(task): show package name of task when --recursive

### LINKED ISSUE #29376: Hard to tell what folder is being run with `deno task -r <task>`
Image

Version: Deno 2.3.3

### PR DESCRIPTION
**Pull request by dsherret**
image

Closes #29376

### CODE REVIEW

File: libs/config/workspace/mod.rs [hunk 1]
```diff
@@ -2110,13 +2112,33 @@ impl WorkspaceDirectory {
 
 pub enum TaskOrScript<'a> {
   /// A task from a deno.json.
-  Task(&'a IndexMap<String, TaskDefinition>, &'a TaskDefinition),
+  Task(
+    &'a WorkspaceMemberTasksConfigFile<TaskDefinition>,
```
Comment (bartlomieju) [inline libs/config/workspace/mod.rs]: Maybe use a struct variant here?

Comment (dsherret) [reply libs/config/workspace/mod.rs]: Done.
