### PR TITLE
fix(ext/node): use Zlib base for brotli handles

### LINKED ISSUE #28507: brotli decompress stream fails in `pnpm`
```
TypeError: Failed to decompress
    at BrotliDecompress.transform [as _transform] (ext:deno_node/_brotli.js:80:23)
    at BrotliDecompress.Transform._write (ext:deno_node/_stream.mjs:4563:12)
    at writeOrBuffer (ext:deno_node/_stream.mjs:3520:16)
    at _write (ext:deno_node/_stream.mjs:3465:14)
    at BrotliDecompress.Writable.write (ext:deno_node/_stream.mjs:3468:14)
    at PassThrough.ondata (ext:deno_node/_stream.mjs:2744:26)
    at PassThrough.emit (ext:deno_node/_events.mjs:393:28)
    at addChunk (ext:deno_node/_stream.mjs:2438:16)
    at readableAddChunk (ext:deno_node/_stream.mjs:2417:13)
    at PassThrough.Readable.push (ext:deno_node/_stream.mjs:2356:14)
```

```
git clone https://github.com/lucacasonato/astro-demo && cd astro-demo

npx pnpm i

deno run -A npm:pnpm i --save yargs
```

### PR DESCRIPTION
**Pull request by littledivy**
Fixes #28507 
Closes https://github.com/denoland/deno/issues/28836

```
$ ../deno/target/debug/deno run -A npm:pnpm i --save yargs
Packages: +297
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Progress: resolved 381, reused 257, downloaded 41, added 297, done

dependencies:
+ @deno/astro-adapter 0.2.1 (0.3.1 is available)
+ astro 5.12.0
+ yargs 18.0.0
```

### CODE REVIEW

File: ext/node/polyfills/http.ts [hunk 1]
```diff
@@ -1033,7 +1033,10 @@ export class IncomingMessageForClient extends NodeReadable {
     this._dumped = false;
 
     this.on("close", () => {
-      this.socket.emit("close");
+      // Let the final data flush before closing the socket.
+      this.socket.once("drain", () => {
```
Comment (bartlomieju) [inline ext/node/polyfills/http.ts:1037]: Good catch, is this exercised any any tests?

**Review by bartlomieju — APPROVED** [review]
Overall LGTM, let's try to fix setImmediate soon to enable more tests

File: ext/node/polyfills/http.ts (hunk 1 above)
Comment (littledivy) [reply ext/node/polyfills/http.ts:1037]: Existing tests in `tests/unit_node/http_test.ts`
