### PR TITLE
fix: panic when $DENO_DIR is a relative path

### LINKED ISSUE #5293: Compile fails when deno_dir is relative
```ts
// hello.ts
console.log('Hello World');
```

```shell
$ env DENO_DIR=denodir deno cache hello.ts
Compile file:///xyz/test.ts
thread 'main' panicked at 'Bad file URL for file: ()', cli/tsc.rs:722:7
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

This is caused by `Url::from_file_path` not being able to handle relative paths.

This also occurs at `cli/tsc.rs:633:35` with a slightly different input.

### PR DESCRIPTION
**Pull request by bartlomieju**
This commit fixes panic occuring when $DENO_DIR is set to a relative
path, eg. "DENO_DIR=denodir deno run main.ts".

Before creating DenoDir instance given path is checked and if necessary
resolved against current working directory.

Additional sanity checks were put in place to ensure all caches
receive absolute path for the location.

Fixes #5293

### CODE REVIEW

**Comment by ry** [comment]
Can you add a test?

**Comment by bartlomieju** [comment]
> Can you add a test please?

I already added `assert!` in a few places it won't happen again.

File: cli/disk_cache.rs [hunk 1]
```diff
@@ -22,7 +22,9 @@ fn with_io_context<T: AsRef<str>>(
 }
 
 impl DiskCache {
+  /// `location` must be an absolute path.
   pub fn new(location: &Path) -> Self {
+    assert!(location.is_absolute());
```
Comment (ry) [inline cli/disk_cache.rs:27]: 👍
