### PR TITLE
fix(lsp): retain module dependencies when parse is invalid

### LINKED ISSUE #12753: lsp: Broken auto completion / suggestions
**Describe the bug**
It's a bit hard to describe the issue so I will append a video for better understanding.
I just moved from deno 1.15.3 to 1.16.1 and auto-completion is kinda broken. On code that I've written like a week ago, it shows auto-completion, but on code, I write today it doesn't come up with suggestions, they first appear when I explicitly start writing some method name or variable name. I use the same class to test, on old variables it shows completion on new instances of this class (new variables also) it doesn't suggest any methods (see the video appended).

**To Reproduce**

1. Install deno 1.16.1
2. Check auto completion on code that was already written
3. Create a new instance of a class or something
4. write `yourInstanceVariable.` and press the shortcut to show suggestions

**Expected behavior**

It should show class methods and variables in the suggestions.

**Screenshots**

https://user-images.githubusercontent.com/20863419/141652487-9b9a076f-4eab-4411-a9d9-1ab07ffc4ff1.mp4

**Versions**

vscode: 1.62.2 deno: 1.16.1 extension: 3.9.2

### PR DESCRIPTION
**Pull request by kitsonk**
Fixes #12753

### CODE REVIEW

File: cli/lsp/language_server.rs [hunk 1]
```diff
@@ -987,17 +987,16 @@ impl Inner {
...
 
-    let req = tsc::RequestMethod::GetNavigationTree(specifier);
-    let navigation_tree: tsc::NavigationTree = self
-      .ts_server
-      .request(self.snapshot()?, req)
-      .await
-      .map_err(|err| {
-        error!("Failed to request to tsserver {}", err);
-        LspError::invalid_request()
+    let navigation_tree =
```
Comment (kitsonk) [inline cli/lsp/language_server.rs:990]: Not directly related to fixing the issue, discovered that we were not using the potentially cached version of the navtree here, which is not good.

File: cli/lsp/language_server.rs [hunk 2]
```diff
@@ -1563,9 +1562,14 @@ impl Inner {
         }
         let reference_specifier =
           resolve_url(&reference.document_span.file_name).unwrap();
-        let asset_or_doc =
-          self.get_asset_or_document(&reference_specifier).await?;
-        results.push(reference.to_location(asset_or_doc.line_index(), self));
+        let reference_line_index = if reference_specifier == specifier {
```
Comment (kitsonk) [inline cli/lsp/language_server.rs:1565]: This also fixes a potential race condition where we re-use the line_index we first retrieved if the specifier is the same (which it is a lot of the time with this) instead of grabbing a new line_index.

File: cli/lsp/tsc.rs [hunk 3]
```diff
@@ -1141,14 +1141,23 @@ impl Classifications {
...
 
-      // start_pos.line == end_pos.line is always true as there are no multiline tokens
-      builder.push(
-        start_pos.line,
-        start_pos.character,
-        end_pos.character - start_pos.character,
-        token_type,
-        token_modifiers,
-      );
+      if start_pos.line == end_pos.line
```
Comment (kitsonk) [inline cli/lsp/tsc.rs:1144]: This directly deals with eliminating a panic that shouldn't occur, but did for me.  I haven't been able to reproduce it, but at least we will get a more useful error logged to the debug output versus a panic and a crash of the language server.

File: cli/lsp/documents.rs [hunk 4]
```diff
@@ -379,14 +393,20 @@ impl Document {
     } else {
       None
     };
-    let source = SourceTextInfo::new(content);
+    let dependencies = if let Some(Ok(module)) = &maybe_module {
+      Arc::new(module.dependencies.clone())
+    } else {
+      self.0.dependencies.clone()
```
Comment (kitsonk) [inline cli/lsp/documents.rs:399]: This is what fixes the issue, we carry over the dependencies when there is an invalid parse.  This allows completions/suggestions/etc to still be processed by tsc when the module contains an unparsable syntax error.

File: cli/lsp/tsc.rs (hunk 3 above)
Comment (dsherret) [reply cli/lsp/tsc.rs:1144]: Seems risky to just log here because maybe it could cause some indirect bugs. It might be better if we panic, but with the information you've added because then we'll get bug reports to fix the issue and we'll know this is occurring.

File: cli/lsp/documents.rs [hunk 5]
```diff
@@ -911,35 +929,32 @@ impl DocumentsInner {
     specifiers: Vec<String>,
     referrer: &ModuleSpecifier,
   ) -> Option<Vec<Option<(ModuleSpecifier, MediaType)>>> {
-    let doc = self.get(referrer)?;
+    let dependencies = self.get(referrer)?.0.dependencies.clone();
```
Comment (dsherret) [inline cli/lsp/documents.rs:932]: Nitpick: Can `doc` still be stored then `doc.0.dependencies` be used below instead to not clone? I think it should be ok because `Document` is immutable in an `Arc` (so should also be no borrow checker trouble). I see previously it was cloning and I think it's just something I missed in my refactor putting `Document` (`DocumentInner`) into an `Arc`.

**Review by dsherret — APPROVED** [review]
LGTM! I think we should still panic in `to_semantic_tokens` though (improve the panic message instead)

File: cli/lsp/documents.rs (hunk 5 above)
Comment (kitsonk) [reply cli/lsp/documents.rs:932]: No, because it is a double borrow of self.

Comment (dsherret) [reply cli/lsp/documents.rs:932]: Oh yeah, I forgot the return type is `&Document`. Could do `let doc = self.get(referrer)?.clone()` which is very cheap then.

Anyway, not a big deal.

Comment (kitsonk) [reply cli/lsp/documents.rs:932]: Dependencies in the document is an Arc now too.

File: cli/lsp/tsc.rs (hunk 3 above)
Comment (kitsonk) [reply cli/lsp/tsc.rs:1144]: I don't think it can cause indirect bugs.  What is occurring here is a returned value from tsc is being "remapped" to something that can be used by a language server client.  If it errors, a "bad" re-map is simply elided, which means a highlighted semantic symbol doesn't get returned to the client.  That is all.

Panicing here causes the language server to terminate, and be restarted which is far more "destructive".  Generally we should avoid panicing in the language server, as no good comes from it.

An improvement is I can return a result here as an internal error.

File: cli/lsp/language_server.rs (hunk 2 above)
Comment (kitsonk) [reply cli/lsp/language_server.rs:1565]: I think either way, there is no harm in re-using an already available value versus grabbing a new one.
