### PR TITLE
fix(ext/node): implement `dns.lookupService`

### LINKED ISSUE #26300: Bug: `dns.lookupService` is not a function
The `node:dns` module exports a `.lookupService()` function that we seem to be missing. See https://nodejs.org/api/dns.html#dnslookupserviceaddress-port-callback

## Steps to reproduce:

Run this snippet:

```ts
import dns from "node:dns";
dns.lookupService("127.0.0.1", 22, (err, hostname, service) => {
  console.log(hostname, service);
  // Prints: localhost ssh
});
```

Version: Deno 2.0.0

### PR DESCRIPTION
**Pull request by Tango992**
Closes #26300

Allows the following node compatibility tests to pass:
- https://github.com/nodejs/node/blob/v24.2.0/test/parallel/test-dns-lookupService-promises.js
- https://github.com/nodejs/node/blob/v24.2.0/test/parallel/test-dns-lookupService.js

### CODE REVIEW

**Comment by bartlomieju** [comment]
@coderabbitai review

File: ext/node/polyfills/internal/dns/promises.ts [hunk 1]
```diff
@@ -230,6 +234,52 @@ function onresolve(
...
+    req.port = port;
+    req.oncomplete = onlookupservice;
+    req.resolve = resolve;
+    req.reject = reject;
+
+    const errCode = cares.getnameinfo(req, address, port);
+
+    if (errCode) {
+      reject(dnsException(errCode, "getnameinfo", address));
+    }
```
Comment (Tango992) [inline ext/node/polyfills/internal/dns/promises.ts:265]: Our `cares.getnameinfo` will always return 0, but I use this approach because a test on `parallel/test-dns-lookupService.js` stubs the return value of this function: https://github.com/nodejs/node/blob/591ba692bfe30408e6a67397e7d18bfa1b9c3561/test/parallel/test-dns-lookupService.js#L9-L10

File: tests/node_compat/config.toml [hunk 2]
```diff
@@ -333,6 +333,8 @@
 "parallel/test-diagnostics-channel-udp.js" = {}
 "parallel/test-disable-sigusr1.js" = {}
 "parallel/test-dns-default-order-ipv4.js" = {}
+"parallel/test-dns-lookupService.js" = {}
+"parallel/test-dns-lookupService-promises.js" = {}
```
Comment (bartlomieju) [inline tests/node_compat/config.toml:337]: Nice work 👍 I just hope they won't be flaky 💀

**Review by bartlomieju — APPROVED** [review]
LGTM, nice fix
