### PR TITLE
Remap stack traces of unthrown errors.

### LINKED ISSUE #1717: Source map not applied to caught errors (and peculiarities with uncaught errors)
Example:
`caught_error.ts`:
```ts
interface A {
  a: number;
}

try {
  throw new Error("HELLO")
} catch (e) {
  console.log(e);
}
```
compiled code:
```js
try {
    throw new Error("HELLO");
}
catch (e) {
    console.log(e);
}
//# sourceMappingURL=caught_error.js.map
//# sourceURL=/Users/kevinqian/Desktop/Programming/Deno/test/caught_error.ts
```
Output:
```
Error: HELLO
    at /Users/kevinqian/Desktop/Programming/Deno/test/caught_error.ts:2:11
```
Notice the error message follows the location of compiled JS code, instead of the TS source.

In comparison,
`uncaught_error.ts`:
```ts
interface A {
  a: number;
}

throw new Error("HELLO")
```
compiled code:
```js
throw new Error("HELLO");
//# sourceMappingURL=uncaught_error.js.map
//# sourceURL=/Users/kevinqian/Desktop/Programming/Deno/test/uncaught_error.ts
```
output:
```
/Users/kevinqian/Desktop/Programming/Deno/test/uncaught_error.ts:1:6
throw new Error("HELLO");

Uncaught Error: HELLO
    at file:///Users/kevinqian/Desktop/Programming/Deno/test/uncaught_error.ts:5:7
```
Notice that the first line points to compiled JS code, yet the error string points to the source TS code.

### PR DESCRIPTION
**Pull request by kitsonk**
This is a redone PR of a previous one that works with current Deno.  In the previous PR I had hoped to move the cache of the parsed source maps into Deno cache, but I think it is just better to iterate on that eventually when deno_dir settles down.

Fixes #1717

### CODE REVIEW

File: js/error_stack_test.ts [hunk 1]
```diff
@@ -0,0 +1,111 @@
...
+
+test(function applySourceMap(): void {
+  const result = Deno.applySourceMap({
+    filename: "gen/cli/bundle/main.js",
+    line: 23,
+    column: 0
+  });
+  assert(result.filename.startsWith("js/"));
+  assert(result.line != null);
+  assert(result.column != null);
```
Comment (ry) [inline js/error_stack_test.ts]: 👍

File: js/error_stack.ts [hunk 2]
```diff
@@ -0,0 +1,298 @@
...
+ * An example:
+ *
+ *       const orig = Deno.applySourceMap({
+ *         location: "file://my/module.ts",
+ *         line: 5,
+ *         column: 15
+ *       });
+ *       console.log(`${orig.filename}:${orig.line}:${orig.column}`);
+ *
+ */
```
Comment (ry) [inline js/error_stack.ts]: 👍

File: tests/error_stack.ts.out [hunk 3]
```diff
@@ -0,0 +1,6 @@
+[WILDCARD]Error: foo
+    at foo ([WILDCARD]tests/error_stack.ts:2:9)
+    at [WILDCARD]tests/error_stack.ts:6:3
+error: Uncaught Error: foo
+    at foo ([WILDCARD]tests/error_stack.ts:2:9)
+    at [WILDCARD]tests/error_stack.ts:6:3
```
Comment (ry) [inline tests/error_stack.ts.out]: 👍
