### PR TITLE
fix(ext/node): add basic support of suite/describe in node:test

### LINKED ISSUE #27406: test.describe not implemented
Version: Deno 2.1.4

I attempted to run one of Astro's tests with Deno and hit this:

```
error: Uncaught (in promise) Error: Not implemented: test.describe
    at notImplemented (ext:deno_node/_utils.ts:9:9)
    at describe (node:test:145:3)
    at file:///Users/matthew/dev/astro/packages/astro/test/astro-basic.test.js:6:1
```

Test file: https://github.com/withastro/astro/blob/main/packages/astro/test/astro-basic.test.js

### PR DESCRIPTION
**Pull request by kt3k**
This PR adds basic support of suite/describe in `node:test`

closes #27406

towards #28837

### CODE REVIEW

**Review by marvinhagemeister — APPROVED** [review]
LGTM

File: ext/node/polyfills/testing.ts [hunk 1]
```diff
@@ -147,30 +195,104 @@ function prepareDenoTest(name, options, fn, overrides) {
...
+};
+
+it.todo = function todo(name, options, fn) {
+  return test.todo(name, options, fn);
+};
+
+it.only = function only(name, options, fn) {
+  return test.only(name, options, fn);
+};
+
```
Comment (bartlomieju) [inline ext/node/polyfills/testing.ts:295]: Can you add these lines?

```
test.test = test;
test.describe = describe;
test.it = it;
```
This will make this module more in-line with Node's implementation

File: tests/specs/node/node_test_module/test.js [hunk 2]
```diff
@@ -79,6 +79,36 @@ test("reject fail", () => {
...
+  it("test 1", () => {});
+  it("test 2", () => {});
+
+  describe("sub describe 1", () => {
+    it("nested test 1", () => {});
+    it("nested test 2", () => {});
+  });
+
+  describe("sub describe 2", () => {
+    it("nested test 1", () => {});
```
Comment (bartlomieju) [inline tests/specs/node/node_test_module/test.js:107]: Would be nice to have failing test cases here to ensure errors are properly caught and reported
