### PR TITLE
feat(urlpattern): add ignoreCase option & hasRegExpGroups property, and fix spec discrepancies

### LINKED ISSUE #20906: Panic when parsing URLPattern
```
james@DESKTOP-38UI0E9:~$ deno
Deno 1.37.2
exit using ctrl+d, ctrl+c, or close()
REPL is running with all permissions allowed.
To specify permissions, run `deno repl` with allow flags.
> let u = new URLPattern(":cafe://:foo")
undefined
> let u = new URLPattern(":café://:foo")

============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: linux x86_64
Version: 1.37.2
Args: ["deno"]

thread 'main' panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/urlpattern-0.2.0/src/constructor_parser.rs:173:8:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
james@DESKTOP-38UI0E9:~$
```

### LINKED ISSUE #21073: URLPattern: Implement whatwg/urlpattern#198.
A non-trivial update to URLPattern constructor string syntax is proposed in whatwg/urlpattern#198. If/when it is merged, you may wish to apply these changes to your implementation of the same.

### LINKED ISSUE #24266: URLPattern with search parameters and base url doesn't work
Version: Deno 1.41, 1.44

```
deno repl   
Deno 1.44.2

> const p = new URLPattern("/api/data/", "http://localhost:8000")
p.exec("http://localhost:8000/api/data/?w=1&g=2")

null
```

```
// Chrome 126.0.6478.62

const p = new URLPattern("/api/data/", "http://localhost:8000")
p.exec("http://localhost:8000/api/data/?w=1&g=2")

{Object}
```

-----

```
Deno 1.44.2
exit using ctrl+d, ctrl+c, or close()
> const pattern = new URLPattern("/books/:id(\\d+)", "https://example.com");
console.log(pattern.test("https://example.com/books/123"))
true
console.log(pattern.test("https://example.com/books/123?d=1"))
false

```

```
// Chrome 126.0.6478.62

const pattern = new URLPattern("/books/:id(\\d+)", "https://example.com");
console.log(pattern.test("https://example.com/books/123"))
true
console.log(pattern.test("https://example.com/books/123?d=1"))
true
```

### PR DESCRIPTION
**Pull request by crowlKats**
Fixes #20906
Fixes #24266
Closes #21073

### CODE REVIEW

**Review by lucacasonato — COMMENTED** [review]
The ignore case option also needs to be handled during regexp construction (like 182)

File: ext/url/01_urlpattern.js [hunk 1]
```diff
@@ -137,33 +137,61 @@ class SampledLRUCache {
...
+    if (webidl.type(baseURLOrOptions) === "String") {
+      webidl.requiredArguments(arguments.length, 1, prefix);
+      input = webidl.converters.URLPatternInput(input, prefix, "Argument 1");
+      baseURL = webidl.converters.USVString(
+        baseURLOrOptions,
+        prefix,
+        "Argument 2",
+      );
+      options = webidl.converters.URLPatternOptions(
+        maybeOptions,
```
Comment (lucacasonato) [inline ext/url/01_urlpattern.js:169]:
```suggestion
        maybeOptions ?? { __proto__: null },
```

File: ext/url/01_urlpattern.js [hunk 2]
```diff
@@ -137,33 +137,61 @@ class SampledLRUCache {
...
+        prefix,
+        "Argument 3",
+      );
+    } else {
+      if (input !== undefined) {
+        input = webidl.converters.URLPatternInput(input, prefix, "Argument 1");
+      } else {
+        input = {};
```
Comment (lucacasonato) [inline ext/url/01_urlpattern.js:177]:
```suggestion
        input = { __proto__: null };
```

File: ext/url/01_urlpattern.js [hunk 3]
```diff
@@ -137,33 +137,61 @@ class SampledLRUCache {
...
+      baseURL = webidl.converters.USVString(
+        baseURLOrOptions,
+        prefix,
+        "Argument 2",
+      );
+      options = webidl.converters.URLPatternOptions(
+        maybeOptions,
+        prefix,
+        "Argument 3",
+      );
```
Comment (lucacasonato) [inline ext/url/01_urlpattern.js:172]:
```suggestion
      if (options !== undefined) {
        options = webidl.converters.URLPatternOptions(
          maybeOptions,
          prefix,
          "Argument 3",
        );
      } else {
        options = { __proto: null };
      }
```

File: ext/url/01_urlpattern.js [hunk 4]
```diff
@@ -137,33 +137,65 @@ class SampledLRUCache {
...
   /**
    * @param {URLPatternInput} input
-   * @param {string} [baseURL]
+   * @param {string} [baseURLOrOptions]
+   * @param {string} [maybeOptions]
    */
-  constructor(input, baseURL = undefined) {
+  constructor(
+    input,
+    baseURLOrOptions = { __proto__: null },
```
Comment (lucacasonato) [inline ext/url/01_urlpattern.js:156]: I mean this is wrong. Please apply the suggestions I made on slack where you default to undefined.

**Review by lucacasonato — APPROVED** [review]
LGTM
