### PR TITLE
fix(lsp): exclude unmapped npm cache paths from auto-imports

### LINKED ISSUE #28777: Duplicate npm package imports with relative paths
Best explained with a picture:

Image

## Steps to reproduce

1. Run `deno init`
2. Run `deno install npm:@preact/signals`
3. Paste these contents into a js/ts file:
  ```ts
  import { useSignal } from "@preact/signals";
  useSignal(2);
  
  // Type: "effect" here to trigger completion
  ```

Version: Deno 2.2.8 (also in canary `ec8e4af85b66e23eca6108793c481fef0c1f70c0`)

### PR DESCRIPTION
**Pull request by nayeemrmn**
Fixes #28777.

### CODE REVIEW

File: tests/integration/lsp_tests.rs [hunk 1]
```diff
@@ -8837,6 +8837,61 @@ fn lsp_npm_types_nested_js_dts() {
...
+    .collect::<Vec<_>>();
+  assert_eq!(
+    json!(items
+      .iter()
+      .map(|i| i
+        .label_details
+        .as_ref()
+        .and_then(|d| d.description.as_ref()))
+      .collect::<Vec<_>>()),
+    json!(["npm:@denotest/reexport-from-non-export"]),
```
Comment (nayeemrmn) [inline tests/integration/lsp_tests.rs:8890]: ✅ Test fails on main:

image

**Review by dsherret — APPROVED** [review]
LGTM
