### PR TITLE
fix(ext/node): return first created path from recursive "node:fs" mkdir call

### LINKED ISSUE #24165: `mkdir()` incorrectly returns `undefined` and produces unexpected subsequent results
## Description

The way `mkdir()` works in Deno seems to differ from Node.js, despite having the same documentation. Using subsequent methods produces unexpected behaviour.

## Steps to Reproduce

Set up a project like so:

```
├── template
│   ├── 1
│   │   └── 1.txt
│   └── 2
│       └── 2.txt
└── test
    ├── index.js
    └── package.json
```

index.js has this:

```TypeScript
import path from "node:path";
import { mkdir, cp } from "node:fs/promises";

const root = path.resolve("./output/here/");

const dir = await mkdir(root, { recursive: true });
console.log(dir);

await cp(new URL("../template/1", import.meta.url), root, { recursive: true });
```

package.json has this:

```JSON
{
	"type": "module"
}
```

Run `deno run -A test/index.js` and the output will be `undefined`, even though `recursive` was `true`.

Remove the resulting directory and run `node test/index.js`. The output is the first directory created as documented.

<hr>

In addition, Deno seems to create a folder containing the files, which is unexpected behaviour (output/here/1). Node.js does not do this (output/here). This is likely due to `mkdir()` being improperly implemented in Deno?

## Versions

- Deno 1.44.1
- Node.js v20.12.2

### PR DESCRIPTION
**Pull request by bartlomieju**
## Summary

- Fix `fs.mkdir()`, `fs.mkdirSync()`, and `fs/promises.mkdir()` with `{ recursive: true }` to return the first directory path created, matching Node.js behavior
- When all directories already exist, correctly returns `undefined`
- Enables `test-fs-mkdir.js` Node compat test

Closes #24165

### CODE REVIEW

**Comment by Tango992** [comment]
I think based on the changes we could try to enable this test:
https://github.com/nodejs/node/blob/v24.12.0/test/parallel/test-fs-mkdir.js

**Comment by bartlomieju** [comment]
Good call, sadly still fails:
```
error: Uncaught (in promise) AssertionError: Expected values to be strictly deep-equal:
+ actual - expected

  Comparison {
    code: 'ENOENT',
+   message: 'No such file or directory (os error 2)',
+   name: 'NotFound'
-   message: /ENOENT: .*mkdir/,
-   name: 'Error',
-   syscall: 'mkdir'
  }

  assert.throws(
         ^
    at file:///Users/ib/dev/deno/tests/node_compat/runner/suite/test/parallel/test-fs-mkdir.js:226:10
    at Object.<anonymous> (file:///Users/ib/dev/deno/tests/node_compat/runner/suite/test/parallel/test-fs-mkdir.js:366:3)
    at Module._compile (node:module:1045:34)
    at loadMaybeCjs (node:module:1085:10)
    at Object.Module._extensions..js (node:module:1068:12)
    at Module.load (node:module:932:32)
    at Module._load (node:module:734:12)
    at file:///Users/ib/dev/deno/tests/node_compat/runner/suite/test/parallel/test-fs-mkdir.js:5:26

```

File: ext/node/polyfills/_fs/_fs_mkdir.ts [hunk 1]
```diff
@@ -80,9 +117,13 @@ export function mkdirSync(path: string | URL, options?: MkdirOptions) {
   }
   validateBoolean(recursive, "options.recursive");
 
+  const firstNonExistent = recursive ? findFirstNonExistent(path) : undefined;
+
   try {
     Deno.mkdirSync(path, { recursive, mode });
```
Comment (Tango992) [inline ext/node/polyfills/_fs/_fs_mkdir.ts]:
```suggestion
  let firstNonExistent: string | undefined;
  try {
    firstNonExistent = recursive ? findFirstNonExistent(path) : undefined;
    Deno.mkdirSync(path, { recursive, mode });
```

File: ext/node/polyfills/_fs/_fs_mkdir.ts [hunk 2]
```diff
@@ -45,10 +77,12 @@ export function mkdir(
   }
   validateBoolean(recursive, "options.recursive");
 
+  const firstNonExistent = recursive ? findFirstNonExistent(path) : undefined;
```
Comment (Tango992) [inline ext/node/polyfills/_fs/_fs_mkdir.ts]:
```suggestion
  let firstNonExistent: string | undefined;
  try {
    firstNonExistent = recursive ? findFirstNonExistent(path) : undefined;
  } catch (err) {
    if (typeof callback === "function") {
      callback(
        denoErrorToNodeError(err as Error, { syscall: "mkdir", path }),
      );
    }
    return;
  }
```

File: ext/node/polyfills/_fs/_fs_mkdir.ts
Comment (Tango992) [inline ext/node/polyfills/_fs/_fs_mkdir.ts]:
```suggestion
        callback(
          denoErrorToNodeError(err as Error, { syscall: "mkdir", path }),
        );
```

**Comment by Tango992** [comment]
Edited the node compat test config to ignore `test-fs-mkdir.js` on windows

**Comment by bartlomieju** [comment]
I want to give it one more try on Windows before ignoring

**Comment by bartlomieju** [comment]
@Tango992 cheers, it appears to work now
