### PR TITLE
feat(lsp): cache all dependencies quick fix

### LINKED ISSUE #16082: lsp: quickfix: cache all
### Current
current `quickfix: cache` is only cache one import within current file

### Request
`quickfix: cache all` cache all import within current file

### Scenario
Devcontainer

### LINKED ISSUE #20658: lsp - Do not pass around RwLock in DiagnosticsServer
This makes the code more prone to deadlocks:

https://github.com/denoland/deno/pull/20632/files/440121697557bcdda0ef5f7799471a55470f1ef5#r1335218921

### PR DESCRIPTION
**Pull request by nayeemrmn**
Closes #16082.
Closes #20658.

Does some refactors suggested by @dsherret in #20632:
- Extract `DiagnosticsServer::state` to a `language_server::Inner::state`, which is passed to `DiagnosticsServer::new()`.
- Internalize `DiagnosticsState`'s locking and mutability.

I haven't done https://github.com/denoland/deno/pull/20632#discussion_r1335221178. Not sure what design to go for and I don't want to mess with the publishing logic in the same PR.

### CODE REVIEW

File: cli/lsp/diagnostics.rs [hunk 1]
```diff
@@ -296,57 +301,72 @@ struct ChannelUpdateMessage {
...
 struct SpecifierState {
-  has_no_cache_diagnostic: bool,
+  version: Option<i32>,
+  no_cache_diagnostics: Vec<lsp::Diagnostic>,
 }
 
 #[derive(Clone, Debug, Default)]
 pub struct DiagnosticsState {
-  specifiers: HashMap<ModuleSpecifier, (Option<i32>, SpecifierState)>,
+  specifiers: Arc<RwLock<HashMap<ModuleSpecifier, SpecifierState>>>,
```
Comment (dsherret) [inline cli/lsp/diagnostics.rs:312]: I think we can just make this a parking_lot::rwlock since these method calls will be very short lived? Then we could get rid of the `async` on all the methods.

File: cli/lsp/diagnostics.rs [hunk 2]
```diff
@@ -358,14 +378,15 @@ pub struct DiagnosticsServer {
...
-  state: Arc<RwLock<DiagnosticsState>>,
+  state: DiagnosticsState,
 }
 
 impl DiagnosticsServer {
   pub fn new(
     client: Client,
     performance: Arc<Performance>,
     ts_server: Arc<TsServer>,
+    state: DiagnosticsState,
```
Comment (dsherret) [inline cli/lsp/diagnostics.rs:389]: Nitpick and something for debate: I've been slowly changing things to move the `Arc` to a higher level (so, `Arc<DiagnosticsState>` similar to `Arc<Performance>` and `Arc<TsServer>`) because then it's very clear that cloning will clone a reference to the struct and it's clear that it's shared amongst other code (I think it being in an `Arc` is a higher level concern).

File: cli/lsp/language_server.rs [hunk 3]
```diff
@@ -1443,11 +1449,9 @@ impl Inner {
...
     let mark = self.performance.mark("did_close", Some(&params));
     self
-      .diagnostics_server
-      .state()
-      .write()
-      .await
-      .clear(&params.text_document.uri);
+      .diagnostics_state
+      .clear(&params.text_document.uri)
+      .await;
```
Comment (dsherret) [inline cli/lsp/language_server.rs:1454]: Great! It will be better in the long term.

**Review by dsherret — COMMENTED** [review]
Nice work on everything and thanks for making the lsp much better!

I think we can change `DiagnosticsState` to use a non-async rwlock.

**Review by dsherret — APPROVED** [review]
LGTM!

File: cli/lsp/diagnostics.rs [hunk 4]
```diff
@@ -296,57 +297,70 @@ struct ChannelUpdateMessage {
...
 
-#[derive(Clone, Debug)]
+#[derive(Debug)]
 struct SpecifierState {
-  has_no_cache_diagnostic: bool,
+  version: Option<i32>,
+  no_cache_diagnostics: Vec<lsp::Diagnostic>,
 }
 
-#[derive(Clone, Debug, Default)]
```
Comment (dsherret) [inline cli/lsp/diagnostics.rs:304]: 👍

File: cli/lsp/language_server.rs [hunk 5]
```diff
@@ -3284,9 +3313,10 @@ impl tower_lsp::LanguageServer for LanguageServer {
       {
         return;
       }
-      inner.diagnostics_server.state()
+      inner.diagnostics_state.clone()
     };
-    if !diagnostics_state.read().await.has_no_cache_diagnostic(uri) {
+    // Call this outside of the language server lock, it sync locks internally.
+    if !diagnostics_state.has_no_cache_diagnostics(uri) {
```
Comment (nayeemrmn) [inline cli/lsp/language_server.rs:3319]: This probably isn't necessary

File: cli/lsp/language_server.rs [hunk 6]
```diff
@@ -3284,9 +3313,10 @@ impl tower_lsp::LanguageServer for LanguageServer {
       {
         return;
       }
-      inner.diagnostics_server.state()
+      inner.diagnostics_state.clone()
     };
-    if !diagnostics_state.read().await.has_no_cache_diagnostic(uri) {
+    // Call this outside of the language server lock, it sync locks internally.
```
Comment (dsherret) [inline cli/lsp/language_server.rs:3318]: Oh, I just realized this comment. We can remove it because what it's doing doesn't have the chance to deadlock since it's contained within DiagnosticsState and the lock will be acquired and released really quickly. So it can be called within the language server lock.

File: cli/lsp/language_server.rs (hunk 5 above)
Comment (nayeemrmn) [reply cli/lsp/language_server.rs:3319]: Okay for some reason when I remove it the `lsp_cache_on_save()` test freezes. Might have to do with the lock queueing?

File: cli/lsp/language_server.rs (hunk 6 above)
Comment (nayeemrmn) [reply cli/lsp/language_server.rs:3318]: https://github.com/denoland/deno/pull/20665#discussion_r1335245282

File: cli/lsp/diagnostics.rs [hunk 7]
```diff
@@ -296,57 +297,70 @@ struct ChannelUpdateMessage {
...
   }
 
-  pub fn has_no_cache_diagnostic(&self, specifier: &ModuleSpecifier) -> bool {
+  pub fn has_no_cache_diagnostics(&self, specifier: &ModuleSpecifier) -> bool {
     self
       .specifiers
+      .read()
       .get(specifier)
-      .map_or(false, |s| s.1.has_no_cache_diagnostic)
+      .map_or(false, |s| !s.no_cache_diagnostics.is_empty())
```
Comment (dsherret) [inline cli/lsp/diagnostics.rs:352]: Just a side note: `map_or`s are hard to understand because the arguments are backwards. I previously opened https://github.com/denoland/deno/pull/18212

File: cli/lsp/language_server.rs (hunk 5 above)
Comment (dsherret) [reply cli/lsp/language_server.rs:3319]: I'll take a look. I have to head out in 15 mins though.

Comment (nayeemrmn) [reply cli/lsp/language_server.rs:3319]: False alarm! I removed the `!` when I moved it and of course it freezes when reading diagnostics since none are published.

Comment (dsherret) [reply cli/lsp/language_server.rs:3319]: Ah, ok good!
