### PR TITLE
fix(npm): store npm binary command resolution in lockfile

### LINKED ISSUE #19034: [node] slow npm resolution with npm binary command
Continuing to use deno everywhere, I came across one repository on my disk where running the tests is significantly slower with deno compared to node. The repository uses `mocha` as the testing framework.

node-deno-test

The difference is more obvious in video form:

https://user-images.githubusercontent.com/1062408/236691718-cddd7f44-8b01-49e7-8be1-a48d4b4d1ee2.mp4

My native profiling skills are a bit basic, but from what I can tell with Mac's Instrument app is that most of the time is spent resolving and fetching npm modules.

Screenshot 2023-05-07 at 18 20 29

If I'm reading the trace correctly it seems like `serde` deserialization is very prominent.

## Steps to reproduce

1. Clone https://github.com/Rich-Harris/sourcemap-codec (yes that one, not the newer one, e.g. ignore the archived message)
2. Run `deno task test`

### PR DESCRIPTION
**Pull request by dsherret**
Part of #19038

Closes #19034 (eliminates the time spent re-resolving)

### CODE REVIEW

File: cli/npm/installer.rs [hunk 1]
```diff
@@ -77,7 +76,24 @@ impl PackageJsonDepsInstaller {
...
+      inner
+        .npm_resolution
+        .resolve_pkg_id_from_pkg_req(req)
+        .is_ok()
+    }) {
+      log::debug!(
+        "All package.json deps resolvable. Skipping top level install."
+      );
+      return Ok(()); // everything is already resolvable
+    }
```
Comment (bartlomieju) [inline cli/npm/installer.rs:93]: I assume this is the "meat" of this PR. Very elegant

**Review by bartlomieju — APPROVED** [review]
LGTM!

File: cli/npm/installer.rs (hunk 1 above)
Comment (dsherret) [reply cli/npm/installer.rs:93]: Yeah, it's actually two fixes.
