### PR TITLE
fix(lsp): update tsconfig after refreshing settings on init

### LINKED ISSUE #21167: lsp doesn't respect deno.unstable (on startup)
While investigating (https://github.com/denoland/deno/issues/21159) is seems there is another case where the LSP doesn't respect the unstable flag. This is unrelated to the `/// <reference no-default-lib="true" />` directive.

Steps to reproduce:
1. Start a new instance of VSCode
2. Initialize a Deno workspace (with unstable API)
3. Create a file with the following `Deno.dlopen` and save it
4. It will complain that `dlopen` is an unstable API.

If you restart the LSP, the setting sticks. Seems like a timing issue on startup.

I've attached a screengrab.
 
unstable

### PR DESCRIPTION
**Pull request by nayeemrmn**
Fixes #21167.

### CODE REVIEW

**Comment by irbull** [comment]
I pulled down the change-set and calling `ls.update_tsconfig` does this fix the problem. Thanks!

I'm not sure I understand how the changes to the tests are related to this issue and the commit message didn't provide any hints.

File: cli/tests/integration/lsp_tests.rs [hunk 1]
```diff
@@ -1933,12 +1935,13 @@ fn lsp_hover_unstable_disabled() {
       "contents": [
         {
           "language": "typescript",
-          "value": "any"
-        }
+          "value": "type Deno.ForeignLibraryInterface = /*unresolved*/ any",
```
Comment (bartlomieju) [inline cli/tests/integration/lsp_tests.rs:1938]: Ugh, so this test basically just stopped testing what's important here due to `Deno.ppid` stabilization?

Comment (nayeemrmn) [reply cli/tests/integration/lsp_tests.rs:1938]: Yeah, though the test above it will fail so for next time I left a comment there pointing to this one.

**Review by bartlomieju — APPROVED** [review]
