### PR TITLE
fix(ext/node): fix global in node env

### LINKED ISSUE #15617: `npm:node-fetch@2` doesn't work because of missing `global.Promise`
The following script fails with `Uncaught Error: native promise missing, set fetch.Promise to your favorite alternative`

```ts
import fetch from "npm:node-fetch@2.6.7";
await fetch("https://example.com");
```

It seems caused by missing `global.Promise` object. If I modify the line below (in downloaded node-fetch source):

```js
fetch.Promise = global.Promise;
```
to
```js
fetch.Promise = globalThis.Promise;
```
then it works.

### PR DESCRIPTION
**Pull request by kt3k**
closes #15617

### CODE REVIEW

File: ext/node/01_node.js [hunk 1]
```diff
@@ -93,7 +93,7 @@
     nodeGlobals.clearImmediate = nativeModuleExports["timers"].clearImmediate;
     nodeGlobals.clearInterval = nativeModuleExports["timers"].clearInterval;
     nodeGlobals.clearTimeout = nativeModuleExports["timers"].clearTimeout;
-    nodeGlobals.global = nodeGlobals;
+    nodeGlobals.global = nodeGlobalThis;
```
Comment (dsherret) [inline ext/node/01_node.js:96]: Oops! Thanks! :)

**Review by dsherret — APPROVED** [review]
LGTM!
