### PR TITLE
fix(lint): Support linting tsx/jsx from stdin

### LINKED ISSUE #24854: Lint tsx and jsx from stdin
Today is not possible lint a tsx or jsx file from stdin. Example:

```jsx
// test.jsx
function render() {
  return <View />;
}
```

```bash
deno lint test.jsx

# Result:
# error[no-unused-vars]: `render` is never used
```

With stdin:

```bash
cat test.jsx | deno lint -

# Error linting: /Users/dayangaliazzi/Projects/yanda/$deno$stdin.ts
#  Expression expected at file:///Users/dayangaliazzi/Projects/yanda/$deno$stdin.ts:2:17
#
#    return <View />;
#                  ~
# Checked 1 file
```

One suggestion is add a `--ext` argument like `fmt` to `lint`:

```
cat test.jsx | deno lint - --ext=jsx
```

### PR DESCRIPTION
**Pull request by yazan-abdalrahman**
Add --ext flag to deno lint to support linting TSX/JSX from stdin
fix #24854

### CODE REVIEW

**Comment by yazan-abdalrahman** [comment]
@lucacasonato @bartlomieju

File: cli/args/flags.rs [hunk 1]
```diff
@@ -2547,7 +2548,18 @@ Ignore linting a file by adding an ignore comment at the top of the file:
...
+          .arg(
+            Arg::new("ext")
+                .long("ext")
+                .require_equals(true)
+                .value_name("EXT")
+                .help("Specify the file extension(s) to lint when reading from stdin.\
+                 For example, use `jsx` to lint JSX files or `tsx` for TSX files. \
+                 This argument is necessary because stdin input does not automatically infer the file type and thus requires explicit extension specification. \
+                 Example usage: `cat file.jsx | deno lint - --ext=jsx`. \
+                 Multiple extensions can be provided, separated by commas, like `jsx,tsx`."),
```
Comment (dsherret) [inline cli/args/flags.rs:2560]: Why would someone provide multiple file extensions? It looks like this should only allow one extension to be provided since it's an `Option<String>`?

**Review by dsherret — CHANGES_REQUESTED** [review]

**Comment by yazan-abdalrahman** [comment]
I used the FileCollector with the same lint and fmt, but it did not apply the requirement, support
`$ deno lint "./src/**/*.ts"
$ deno check "./src/**/*.ts"`

image
image
image


I think the previous method is better than using FileCollector with the same as format and lint.

@dsherret

File: cli/args/flags.rs (hunk 1 above)
Comment (yazan-abdalrahman) [reply cli/args/flags.rs:2560]: @dsherret 
Oh, it's just a typo in message; actually, it supports one extension.

done, I changed it and I changed  ` let ext = matches.remove_many::<String>("ext").map(|f| f.collect());`
to `let ext = matches.remove_one::<String>("ext");`

**Review by dsherret — APPROVED** [review]
LGTM

In the future, I'd recommend writing a test to exercise the change (I just added one). For example, in this case the displayed file path was showing as ".ts" instead of ".jsx"
