### PR TITLE
fix(cache): don't try to set up node_modules with node_modules_dir manual in deno cache

### LINKED ISSUE #30938: deno install panic
Version: Deno 2.5.2

- git clone github.com/google-gemini/gemini-cli
- DENO_COMPAT=1 deno i

```
thread 'main' panicked at cli/tools/installer/mod.rs:528:60:
not yet implemented
```

https://github.com/denoland/deno/blob/9b4c141595466caa925b77f9742c8478498bf26b/cli/tools/installer/mod.rs#L528

### LINKED ISSUE #30949: JSR entrypoint in package JSON should not prevent run when using manual node modules dir
Take the following project:

```json
{
  "dependencies": {
    "@bigmoves/atproto-oauth-client": "jsr:^0.2.0"
  }
}
```

```ts
import {} from "@bigmoves/atproto-oauth-client";
```

If you run `pnpm install` to generate a `node_modules` folder, and then `deno cache main.ts`, the latter will fail like this:

```
~/D/test ❯❯❯ deno cache main.ts
JSR specifiers are not yet supported in package.json: @bigmoves/atproto-oauth-client@^0.2.0
error: JSR specifiers are not yet supported in package.json
    at file:///Users/lucacasonato/Downloads/test/main.ts:1:16
```

This makes no sense - Deno does not have to interpret `package.json` dependencies at all when using manual `node_modules`, as is the default when a `package.json` is present.

Version: Deno 2.5.3

### PR DESCRIPTION
**Pull request by nathanwhit**
Fixes #30949. Fixes #30938

### CODE REVIEW

File: cli/tools/installer/mod.rs [hunk 1]
```diff
@@ -525,7 +533,10 @@ pub fn print_install_report(
         continue;
       };
       match s {
-        deno_package_json::PackageJsonDepValue::File(_) => todo!(),
+        deno_package_json::PackageJsonDepValue::File(_) => {
+          // TODO(nathanwhit)
+          // TODO(bartlomieju)
```
Comment (dsherret) [inline cli/tools/installer/mod.rs:538]: Lol

File: cli/tools/installer/mod.rs [hunk 2]
```diff
@@ -525,7 +533,10 @@ pub fn print_install_report(
         continue;
       };
       match s {
-        deno_package_json::PackageJsonDepValue::File(_) => todo!(),
```
Comment (dsherret) [inline cli/tools/installer/mod.rs:528]: Should fix: https://github.com/denoland/deno/issues/30938

File: tests/specs/cache/nmd_manual/node_modules/@denotest/add/index.js [hunk 3]
```diff
@@ -0,0 +1,3 @@
+module.exports = {
+  add: (a, b) => a + b,
```
Comment (dsherret) [inline tests/specs/cache/nmd_manual/node_modules/@denotest/add/index.js]: Maybe make this subtract and then do a `deno run main.ts` and ensure it subtracts instead of adds? (that would indicate it didn't re-setup the node_modules directory)
