### PR TITLE
fix(ext/node): respects `flag` option on `fs.readfile` and `fs.readfilesync`

### LINKED ISSUE #31099: `fs.readFileSync` does not create new file if file does not exist when using `w+` flag
Version: Deno 2.5.4

Hi,

I would like to report a behavior I observed when running the following code snippet:

```javascript
// sample.mjs
import fs from "node:fs";
fs.readFileSync("data.txt", { encoding: "utf8", flag: "w+" })
```
Make sure that the file `data.txt` does not exist.

Node creates a `data.txt` file automatically and exits without error.
Deno gives the following error message:

```
PS D:\HIWI\RESULTS\25_10_2025> deno run -A .\sample.mjs
error: Uncaught (in promise) Error: ENOENT: no such file or directory, open 'data.txt'
fs.readFileSync("data.txt", { encoding: "utf8", flag: "w+" })
   ^
    at __node_internal_captureLargerStackTrace (ext:deno_node/internal/errors.ts:90:3)
    at __node_internal_uvException (ext:deno_node/internal/errors.ts:183:10)
    at denoErrorToNodeError (ext:deno_node/internal/errors.ts:1927:14)
    at Object.readFileSync (ext:deno_node/_fs/_fs_readFile.ts:66:13)
    at file:///D:/HIWI/RESULTS/25_10_2025/sample.mjs:2:4
```

The documentation (https://docs.deno.com/api/node/fs/~/readFileSync) shows that `fs.readFileSync` is supported by Deno.

### PR DESCRIPTION
**Pull request by Tango992**
Closes #31099

### CODE REVIEW

File: ext/node/ops/fs.rs [hunk 1]
```diff
@@ -206,6 +209,78 @@ where
   Ok(rid)
 }
 
+#[op2(stack_trace)]
+#[serde]
+pub fn op_node_read_file_sync<P>(
```
Comment (bartlomieju) [inline ext/node/ops/fs.rs]: Do we need new ops for this? Could we maybe change the existing ops to accept necessary params and call them directly in `ext/node`?

Comment (Tango992) [reply ext/node/ops/fs.rs]: That also works. So does this mean that we're also exposing the `flag` options to the `Deno.readFile` and `Deno.readFileSync`? And if that's the case, should the PR refers the changes as `fix(ext/node)` or `feat(fs)` instead?

Comment (bartlomieju) [reply ext/node/ops/fs.rs]: Let's adjust the ops in this PR so we get the Node part working and follow up with another PR that updates `Deno.readFile` API with the option?

**Comment by bartlomieju** [comment]
@Tango992 FYI the `ci-node-test` label is not needed anymore since https://github.com/denoland/deno/pull/31120

File: ext/node/ops/fs.rs (hunk 1 above)
Comment (Tango992) [reply ext/node/ops/fs.rs]: sure!

**Review by bartlomieju — APPROVED** [review]
Nice work, LGTM!
