### PR TITLE
Fix loading circular dependencies

### LINKED ISSUE #653: Better circular-dependencies handling
> deno -v

> deno: 0.1.2
> v8: 7.0.247-deno
> 

Assuming that I have two files, `a.ts`:

```
import { B } from './b.ts';

export class A {
    myB = new B();
}
```

and `b.ts`:
```
import { A } from './a.ts';

export class B {
    myA = new A();
}
```

then if I try:

> deno ./a.ts

I get:

> RangeError: Maximum call stack size exceeded
>     at eval (/path/to/b.ts, <anonymous>)
>     at DenoCompiler.eval [as _globalEval] (<anonymous>)
>     at DenoCompiler._gatherDependencies (deno/js/compiler.ts:228:10)
>     at moduleMetaData.deps.deps.map.dep (deno/js/compiler.ts:452:14)
>     at Array.map (<anonymous>)
>     at localDefine (deno/js/compiler.ts:440:34)
>     at eval (/path/to/a.ts, <anonymous>)
>     at DenoCompiler.eval [as _globalEval] (<anonymous>)
>     at DenoCompiler._gatherDependencies (deno/js/compiler.ts:228:10)
>     at moduleMetaData.deps.deps.map.dep (deno/js/compiler.ts:452:14)+

If I run the same using node (`ts-node ./a.ts`) it will not fail and it will execute everything correctly.

Now the question is:

### Do we want deno to fail on purpose whenever there is a circular dependency?

- If no, then this is just a bug that needs to be fixed. Just ignore the text below.

- If yes, then I guess:

1) we should output an error explicitly saying that there is a circular dependency so the code cannot be executed. Otherwise it might be not that obvious for the programmer that the issue is about a circular dependency in the code.

2) we should consistently fail in all scenarios where there is a circular dependency.

For example, if I remove the `new A()` and `new B()` calls from the code, so having:

a.ts
```
import { B } from './b.ts';

export class A {
    myB: B;
}
```

b.ts
```
import { A } from './a.ts';

export class B {
    myA: A;
}
```
there is still a circular dependency, however this latter code will **NOT** fail to execute.

### PR DESCRIPTION
**Pull request by kitsonk**
Fixes #653

### CODE REVIEW

File: js/compiler.ts [hunk 1]
```diff
@@ -250,10 +251,6 @@ export class DenoCompiler implements ts.LanguageServiceHost {
       }
       const dependencyMetaData = this._getModuleMetaData(dep);
       assert(dependencyMetaData != null, `Missing dependency "${dep}".`);
-      assert(
```
Comment (kitsonk) [inline js/compiler.ts]: This was, in the end, a _bad_ assertion, because with circular dependencies, you will have some modules that are not yet run, but we will be returning the reference to their `.exports` object to a module.

**Comment by kitsonk** [comment]
Yes, I can do that instead!

**Comment by kitsonk** [comment]
@ry good to go now.
