### PR TITLE
fix(dx): always spawn subprocess for dx

### LINKED ISSUE #31692: dx playwright install does not work, but deno run does
Version: Deno 2.6.3

Inside of a folder with the following `deno.json`:

```
{
  "imports":{
    "playwright": "npm:playwright@^1.57.0"
  }
}
```

```
# does not work
➜ dx playwright install
Downloading Chromium 143.0.7499.4 (playwright build v1200) from https://cdn.playwright.dev/dbazure/download/playwright/builds/chromium/1200/chromium-mac-arm64.zip
error: Could not find constraint 'run' in the list of packages.
Downloading Chromium 143.0.7499.4 (playwright build v1200) from https://playwright.download.prss.microsoft.com/dbazure/download/playwright/builds/chromium/1200/chromium-mac-arm64.zip
error: Could not find constraint 'run' in the list of packages.
Downloading Chromium 143.0.7499.4 (playwright build v1200) from https://cdn.playwright.dev/builds/chromium/1200/chromium-mac-arm64.zip
error: Could not find constraint 'run' in the list of packages.
Downloading Chromium 143.0.7499.4 (playwright build v1200) from https://cdn.playwright.dev/dbazure/download/playwright/builds/chromium/1200/chromium-mac-arm64.zip
error: Could not find constraint 'run' in the list of packages.
Downloading Chromium 143.0.7499.4 (playwright build v1200) from https://playwright.download.prss.microsoft.com/dbazure/download/playwright/builds/chromium/1200/chromium-mac-arm64.zip
error: Could not find constraint 'run' in the list of packages.
Failed to install browsers
Error: Failed to download Chromium 143.0.7499.4 (playwright build v1200), caused by
Error: Download failure, code=1
    at ChildProcess.<anonymous> (file:///Users/nic/Library/Caches/deno/npm/registry.npmjs.org/playwright-core/1.57.0/lib/server/registry/browserFetcher.js:94:32)
    at ChildProcess.emit (ext:deno_node/_events.mjs:436:20)
    at ext:deno_node/internal/child_process.ts:281:16
    at eventLoopTick (ext:core/01_core.js:187:7)
```

```
# works
➜ deno run -A npm:playwright install
Downloading Chromium 143.0.7499.4 (playwright build v1200) from https://cdn.playwright.dev/dbazure/download/playwright/builds/chromium/1200/chromium-mac-arm64.zip
159.6 MiB [==                  ] 9% 19.2s^C
```

### LINKED ISSUE #31874: `dx npm:tsx` causes panic
Version: Deno 2.6.5

steps
- `dx npm:tsx`

```sh
❯ dx npm:tsx         

============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: macos aarch64
Version: 2.6.5
Args: ["/Users/admin/.deno/bin/dx", "run", "-A", "--require", "/Users/admin/Library/Caches/deno/deno_x_cache/npm-tsx/node_modules/.deno/tsx@4.21.0/node_modules/tsx/dist/preflight.cjs", "--require", "/Users/admin/Library/Caches/deno/deno_x_cache/npm-tsx/node_modules/.deno/tsx@4.21.0/node_modules/tsx/dist/patch-repl.cjs", "--import", "file:///Users/admin/Library/Caches/deno/deno_x_cache/npm-tsx/node_modules/.deno/tsx@4.21.0/node_modules/tsx/dist/loader.mjs"]

View stack trace at:
https://panic.deno.com/v2.6.5/aarch64-apple-darwin/o4m_DgptjtBg9srtBw2srtB41srtBg1hqLo4hqL4_gqLw4piE420yHwsyvFom-mCwq9kK

thread 'main' (89726802) panicked at cli/tools/x.rs:405:62:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

```

### PR DESCRIPTION
**Pull request by nathanwhit**
Fixes #31692. Fixes #31874.

previously I tried to avoid this, but it messes up the argv0. So just spawn a process. Since we're going through native code (as opposed to a bash wrapper) it doesn't add too much time (I measured) though it does hurt perf a bit.

### CODE REVIEW

File: cli/tools/x.rs [hunk 1]
```diff
@@ -73,49 +71,55 @@ async fn resolve_local_bins(
...
+  let deno_exe = std::env::current_exe()
+    .and_then(|p| p.canonicalize())
+    .context("Failed to get current executable path")?;
+
+  let mut args: Vec<std::ffi::OsString> =
+    vec!["run".into(), "-A".into(), main_module.as_str().into()];
+  args.extend(argv.iter().map(|s| s.into()));
+
+  let mut command = std::process::Command::new(deno_exe);
+  command.args(&args);
```
Comment (bartlomieju) [inline cli/tools/x.rs]: Is it on purpose using `-A` here? What is someone passes different arg set? If I'm misunderstanding a comment here would be helpful

File: cli/tools/x.rs [hunk 2]
```diff
@@ -73,49 +71,55 @@ async fn resolve_local_bins(
...
+    Some(unsafe { std::fs::File::from_raw_io_handle(fd) })
+  } else {
+    None
+  };
 
   if npm {
     crate::tools::run::set_npm_user_agent();
+    if let Some(agent) = std::env::var_os("NPM_CONFIG_USER_AGENT") {
+      command.env("NPM_CONFIG_USER_AGENT", agent);
+    }
```
Comment (dsherret) [inline cli/tools/x.rs]: Why does it need to do this if not using clear_env?

File: cli/tools/x.rs [hunk 3]
```diff
@@ -73,49 +71,55 @@ async fn resolve_local_bins(
...
-    )
-    .await
-    .inspect_err(|e| deno_telemetry::report_event("boot_failure", e))?;
-
-  let exit_code = worker
-    .run()
-    .await
-    .inspect_err(|e| deno_telemetry::report_event("uncaught_exception", e))?;
-  Ok(exit_code)
+  let mut child = command.spawn().context("Failed to spawn deno subprocess")?;
```
Comment (dsherret) [inline cli/tools/x.rs]: Maybe prefer exec over spawn for unix?

File: cli/tools/x.rs (hunk 1 above)
Comment (nathanwhit) [reply cli/tools/x.rs]: Ah meant to go back and replace this
