### PR TITLE
fix(compile): inline symlinks as files outside node_modules dir and warn for directories

### LINKED ISSUE #19251: 1.34 npm:specifiers, Deno has panicked Error.
Deno 1.34 has been released and deno compile now supports npm packages.

[Deno 1.34 Updates](https://deno.com/blog/v1.34) I am doing the following based on the example in this document.

```
$ cat main.ts
import { say } from "npm:cowsay@1.5.0";
console.log(say({ text: "Hello from Deno!" }));

$ deno compile --allow-read main.ts
$ ./main.ts
```
But I am getting an error as below.

```
============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: macos x86_64
Version: 1.34.0
Args: ["deno", "compile", "--allow-read", "main.ts"]

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: StripPrefixError(())', cli/standalone/virtual_fs.rs:154:53
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

What is the reason of this ? What should we do ?

### PR DESCRIPTION
**Pull request by dsherret**
If a symlink within the `node_modules` directory lies outside that directory, it will now warn and inline the file. For directories, it will just warn for now.

Probably fixes #19251 (I'm still unable to reproduce).

### CODE REVIEW

File: cli/standalone/virtual_fs.rs [hunk 1]
```diff
@@ -72,19 +83,44 @@ impl VfsBuilder {
...
+            let file_bytes = std::fs::read(&target)
+              .with_context(|| format!("Reading {}", path.display()))?;
+            self.add_file(&path, file_bytes)?;
+          } else {
+            log::warn!(
+              "Symlink target is outside '{}'. Excluding symlink at '{}' with target '{}'.",
+              self.root_path.display(),
+              path.display(),
+              target.display(),
+            );
```
Comment (dsherret) [inline cli/standalone/virtual_fs.rs:109]: I made this just warn for now, but in the future we could see about inlining this as well maybe.

**Review by bartlomieju — APPROVED** [review]
LGTM
