### PR TITLE
fix(add): Handle packages without root exports

### LINKED ISSUE #24607: Bug: Command `deno add` logs error for JSR package without default export
When using `deno add`, I get errors if there is any JSR package that has no default export (`.`). For instance, installing `@std/testing` will make it so errors are printed every time I run `deno add` command. The command itself seems to succeed anyway, but the CLI command fails with a non-zero exit code, and a pretty verbose error message is printed. Is it mandatory to have a default export? If so, perhaps `@std/testing` should be updated, since it currently only has named subpath exports.

## Reproduction steps

1. Create a new folder
2. Add JSR package via `deno add` with no `.` export (e.g. `@std/testing@0.225.3`)
   - ` deno add @std/testing@0.225.3`
3. Install any other JSR package (e.g. `@std/json`)

### Actual results

When installing `@std/testing@0.225.3` the following errors is printed:
```
Created deno.json configuration file.
Add @std/testing - jsr:@std/testing@^0.225.3
error: Unknown export '.' for '@std/testing@0.225.3'.
  Package exports:
 * ./asserts
 * ./bdd
 * ./mock
 * ./snapshot
 * ./time
 * ./types
```

Installing another package via `deno add` (e.g. `@std/json`) will print the same error again.
```
Add @std/json - jsr:@std/json@^0.224.1
error: Unknown export '.' for '@std/testing@0.225.3'.
  Package exports:
 * ./asserts
 * ./bdd
 * ./mock
 * ./snapshot
 * ./time
 * ./types
```

### Expected results

No errors

## Environment

OS: Windows 11
deno 1.45.2 (release, x86_64-pc-windows-msvc)
v8 12.7.224.12
typescript 5.5.2

### PR DESCRIPTION
**Pull request by nathanwhit**
Fixes #24607.

This PR makes the logic that caches top level dependencies (things present in import map) smarter, so we handle JSR dependencies without root exports.

### CODE REVIEW

File: cli/graph_util.rs [hunk 1]
```diff
@@ -97,6 +100,25 @@ pub fn graph_valid(
...
+            ModuleLoadError::Jsr(JsrLoadError::UnknownExport {
+              export_name,
+              ..
+            }),
+          )) if export_name == "."
+        )
+      {
+        log::debug!("Ignoring: {}", error);
+        return None;
+      }
```
Comment (dsherret) [inline cli/graph_util.rs:120]: > This error arises when we attempt to cache packages listed in the import map after running deno add. The way we do this isn't particularly smart, we just attempt to cache everything that looks like a complete package path (no trailing slash).

Can't we instead get the exports for the package in pm/add.rs and only cache those?

**Review by dsherret — APPROVED** [review]
LGTM!
