### PR TITLE
reduce redundancies in the fetch code

### LINKED ISSUE #2923: bug: Request body is never discarded
There are actually two bugs here:
1. If I don't use `response.body` then program never exits:
```ts
// js/fetch_test.ts

...

testPerm({ net: true }, async function fetchUserAgent(): Promise<void> {
  const data = "Hello World";
  const response = await fetch("http://localhost:4545/echo_server", {
    method: "POST",
    body: new TextEncoder().encode(data)
  });
  assertEquals(response.headers.get("user-agent"), `Deno/${Deno.version.deno}`);

  setInterval(() => {
    console.table(Deno.resources());
  }, 5000);
});

runIfMain(import.meta);
```
```
$ target/debug/deno --allow-net js/fetch_test.ts
Compile file:///Users/biwanczuk/dev/deno/js/fetch_test.ts
running 18 tests
OK     fetchJsonSuccess (24.00ms)
OK     fetchUrl (10.00ms)
OK     fetchHeaders (10.00ms)
OK     fetchBlob (10.00ms)
OK     fetchBodyUsed (8.00ms)
OK     fetchAsyncIterator (8.00ms)
OK     responseClone (10.00ms)
OK     fetchEmptyInvalid (2.00ms)
OK     fetchMultipartFormDataSuccess (12.00ms)
OK     fetchURLEncodedFormDataSuccess (8.00ms)
OK     fetchWithRedirection (26.00ms)
OK     fetchWithRelativeRedirection (48.00ms)
OK     fetchInitStringBody (8.00ms)
OK     fetchRequestInitStringBody (6.00ms)
OK     fetchInitTypedArrayBody (6.00ms)
OK     fetchInitURLSearchParamsBody (8.00ms)
OK     fetchInitBlobBody (8.00ms)
OK     fetchUserAgent (6.00ms)

test result: OK. 18 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out (238.00ms)

┌─────────┬────────────┐
│ (index) │   Values   │
├─────────┼────────────┤
│    0    │  "stdin"   │
│    1    │  "stdout"  │
│    2    │  "stderr"  │
│    3    │  "worker"  │
│    5    │ "httpBody" │
│    6    │ "httpBody" │
│    9    │ "httpBody" │
│   13    │ "httpBody" │
│   15    │ "httpBody" │
│   22    │ "httpBody" │
└─────────┴────────────┘
┌─────────┬────────────┐
│ (index) │   Values   │
├─────────┼────────────┤
│    0    │  "stdin"   │
│    1    │  "stdout"  │
│    2    │  "stderr"  │
│    3    │  "worker"  │
│    5    │ "httpBody" │
│    6    │ "httpBody" │
│    9    │ "httpBody" │
│   13    │ "httpBody" │
│   15    │ "httpBody" │
│   22    │ "httpBody" │
└─────────┴────────────┘
....
```

2. Even if you consume the body using `.text()` method its resource is never closed. 

All but one of the "httpBody" resources you see above are from previous test cases in this file.

### PR DESCRIPTION
**Pull request by nstott**
This reduces the amount of duplicated and almost duplicate code in body.ts and fetch.ts.
I found myself having to make changes in both places when doing some more ReadableStream stuff.  

the implementation of `domTypes.Body` is done in body.ts.  this doesn't address the TODO's surrounding https://fetch.spec.whatwg.org/#body-mixin, but it aligns things a little bit more

This fixes #2923

### CODE REVIEW

File: cli/js/body.ts [hunk 1]
```diff
@@ -131,6 +134,7 @@ export const BodyUsedError =
 
 export class Body implements domTypes.Body {
   protected _stream: domTypes.ReadableStream | null;
+  protected _bodyUsed = false;
```
Comment (nstott) [inline cli/js/body.ts]: this uses a similar strategy to what was happening in fetch.ts before

https://github.com/denoland/deno/blob/master/cli/js/fetch.ts#L38

in that implementation we flip the switch when we issue our first read
https://github.com/denoland/deno/blob/master/cli/js/fetch.ts#L226

here, we flip the switch in the call to `arrayBuffer()`,

File: cli/js/body.ts [hunk 2]
```diff
@@ -160,14 +164,14 @@ export class Body implements domTypes.Body {
...
-    if (this.body && this.body.locked) {
+    if (this.body && this._bodyUsed) {
       return true;
     }
     return false;
   }
 
   public async blob(): Promise<domTypes.Blob> {
-    return new Blob([await this.arrayBuffer()]);
+    return new Blob([await this.arrayBuffer()], { type: this.contentType });
```
Comment (nstott) [inline cli/js/body.ts]: this was missing, and failing the `fetchBlob` tests in fetch.ts

File: cli/js/body.ts [hunk 3]
```diff
@@ -314,6 +318,7 @@ export class Body implements domTypes.Body {
   }
 
   public async arrayBuffer(): Promise<ArrayBuffer> {
+    this._bodyUsed = true;
```
Comment (nstott) [inline cli/js/body.ts]: I'm not sure whether this is accurate

File: cli/js/fetch.ts [hunk 4]
```diff
@@ -1,254 +1,68 @@
...
-class Body implements domTypes.Body, domTypes.ReadableStream, io.ReadCloser {
-  private _bodyUsed = false;
-  private _bodyPromise: null | Promise<ArrayBuffer> = null;
-  private _data: ArrayBuffer | null = null;
-  readonly locked: boolean = false; // TODO
-  readonly body: null | Body = this;
-
-  constructor(private rid: number, readonly contentType: string) {}
-
-  private async _bodyBuffer(): Promise<ArrayBuffer> {
```
Comment (nstott) [inline cli/js/fetch.ts]: replaced with https://github.com/nstott/deno/blob/fetch/cli/js/body.ts#L74

File: cli/js/fetch.ts [hunk 5]
```diff
@@ -1,254 +1,68 @@
...
-  }
-
-  getReader(): domTypes.ReadableStreamReader {
-    return notImplemented();
+    throw new Error("no stream present");
   }
 
   tee(): [domTypes.ReadableStream, domTypes.ReadableStream] {
-    return notImplemented();
+    if (this._stream) {
```
Comment (nstott) [inline cli/js/fetch.ts]: we no longer implement a ReadCloser, so we need to create this thing here

File: cli/js/fetch.ts [hunk 6]
```diff
@@ -266,48 +80,73 @@ export class Response implements domTypes.Response {
...
-    body_: null | Body = null
+    readableStream_: domTypes.ReadableStream | null = null
   ) {
     this.trailer = createResolvable();
     this.headers = new Headers(headersList);
     const contentType = this.headers.get("content-type") || "";
 
-    if (body_ == null) {
-      this.body = new Body(rid, contentType);
+    if (readableStream_ == null) {
```
Comment (nstott) [inline cli/js/fetch.ts]: there's an implicit capture of our `rid` here.
we pump the read date from that rid into the readable stream that we use to create the body

File: cli/js/fetch.ts [hunk 7]
```diff
@@ -1,254 +1,68 @@
...
 
   [Symbol.asyncIterator](): AsyncIterableIterator<Uint8Array> {
-    return io.toAsyncIterator(this);
-  }
+    //@ts-ignore
+    const reader = this.body.getReader();
 
-  get bodyUsed(): boolean {
-    return this._bodyUsed;
+    return {
```
Comment (nstott) [inline cli/js/fetch.ts]: we no longer implement a ReadCloser, so we need to create this iterable here

File: cli/js/fetch.ts [hunk 8]
```diff
@@ -266,48 +80,73 @@ export class Response implements domTypes.Response {
...
     const contentType = this.headers.get("content-type") || "";
 
-    if (body_ == null) {
-      this.body = new Body(rid, contentType);
+    if (readableStream_ == null) {
+      const rs = new ReadableStream({
+        start(controller: ReadableStreamController): Promise<void> {
+          return pump();
+          function pump(): Promise<void> {
+            const bytes: Uint8Array = new Uint8Array(2048);
```
Comment (nstott) [inline cli/js/fetch.ts]: magic buffer size

**Comment by nstott** [comment]
I think this also fixes #3105, 
or, at least I can't replicate that issue on this branch

File: cli/js/fetch.ts (hunk 4 above)
Comment (ry) [reply cli/js/fetch.ts]: thank you!

File: cli/js/body.ts (hunk 3 above)
Comment (ry) [reply cli/js/body.ts]: Yes I think so
