### PR TITLE
fix(compile): relative permissions should be retained as relative

### LINKED ISSUE #23715: Permission regression with `deno compile`
Executing a compiled binary from any path that is not the same as the current working directory when invoking `deno compile`  returns a permission error even when the permission flags have been set. This started to happen since Deno 1.42.

Minimal reproducible example:

```bash
$ cat main.ts
try { Deno.readTextFileSync('a.txt') }
catch (err) { console.log(err.message); }

$ deno compile --output=bin/a.out --no-prompt --allow-read=a.txt main.ts
```

Expected output:

```bash
$ ./bin/a.out
No such file or directory (os error 2): readfile 'a.txt'

$ cd bin && ./a.out
No such file or directory (os error 2): readfile 'a.txt'
```

Actual output:

```bash
$ ./bin/a.out
No such file or directory (os error 2): readfile 'a.txt'

$ cd bin && ./a.out
Requires read access to "a.txt", run again with the --allow-read flag
```

### PR DESCRIPTION
**Pull request by dsherret**
Closes #23715

### CODE REVIEW

File: cli/standalone/binary.rs [hunk 1]
```diff
@@ -134,7 +134,7 @@ pub enum NodeModules {
 pub struct Metadata {
   pub argv: Vec<String>,
   pub seed: Option<u64>,
-  pub permissions: PermissionsOptions,
+  pub permissions: PermissionFlags,
```
Comment (dsherret) [inline cli/standalone/binary.rs:137]: Fix is here. Instead of storing the resolved `PermissionsOptions` we store the raw flags.

File: cli/args/flags.rs [hunk 2]
```diff
@@ -532,14 +520,118 @@ pub struct Flags {
...
   pub no_npm: bool,
-  pub no_prompt: bool,
   pub reload: bool,
   pub seed: Option<u64>,
   pub strace_ops: Option<Vec<String>>,
   pub unstable_config: UnstableConfig,
   pub unsafely_ignore_certificate_errors: Option<Vec<String>>,
   pub v8_flags: Vec<String>,
   pub code_cache_enabled: bool,
+  pub permissions: PermissionFlags,
```
Comment (bartlomieju) [inline cli/args/flags.rs:530]: That's a nice cleanup but I wish it was done in a separate PR, makes reviewing this one a lot harder.

File: tests/specs/compile/relative_permissions/__test__.jsonc [hunk 3]
```diff
@@ -0,0 +1,26 @@
...
+      "Deno.mkdirSync('sub_dir');"
+    ],
+    "output": "[WILDCARD]"
+  }, {
+    "if": "unix",
+    "commandName": "../main",
+    "cwd": "sub_dir",
+    "args": [],
+    "output": "No such file[WILDCARD]"
+  }]
```
Comment (bartlomieju) [inline tests/specs/compile/relative_permissions/__test__.jsonc:25]: Nice flex on what spec tests can do now :)

**Review by bartlomieju — APPROVED** [review]
LGTM
