### PR TITLE
fix: removed unstable-htttp from deno help

### LINKED ISSUE #25210: Hide `--unstable-http` from `--help` output
It is currently unused.

### PR DESCRIPTION
**Pull request by HasanAlrimawi**
Closes #25210 .

Removed --unstable-http from being displayed on deno run --help=unstable

### CODE REVIEW

File: runtime/lib.rs [hunk 1]
```diff
@@ -76,11 +76,6 @@ pub static UNSTABLE_GRANULAR_FLAGS: &[(
     "Enable unstable file system APIs",
     4,
   ),
-  (
-    ops::http::UNSTABLE_FEATURE_NAME,
-    "Enable unstable HTTP APIs",
-    5,
-  ),
```
Comment (bartlomieju) [inline runtime/lib.rs:83]: This will not work. We still want this flag to exist, but not show in the help output. You'll need to add another field here (a boolean) that marks if this flag is supposed to show in the help output.

**Comment by bartlomieju** [comment]
@HasanAlrimawi thanks for the PR, FYI I updated the PR to use more structured data.

Waiting on @crowlKats's review.

**Review by crowlKats — APPROVED** [review]
LGTM
