### PR TITLE
fix(typescript): allow synthetic default imports when using `ModuleKind.ESNext`

### LINKED ISSUE #16437: Type checking broken in canary with synthetic default imports
Fresh website type checks on 1.26.2, broken in canary

https://github.com/denoland/fresh/actions/runs/3332841966/jobs/5515054222

### PR DESCRIPTION
**Pull request by dsherret**
Closes #16437

### CODE REVIEW

File: cli/tsc/00_typescript.js [hunk 1]
```diff
@@ -51163,7 +51163,7 @@ var ts;
             var usageMode = file && getUsageModeForExpression(usage);
             if (file && usageMode !== undefined) {
                 var result = isESMFormatImportImportingCommonjsFormatFile(usageMode, file.impliedNodeFormat);
-                if (usageMode === ts.ModuleKind.ESNext || result) {
+                if (result) {
```
Comment (dsherret) [inline cli/tsc/00_typescript.js:51166]: This is unfortunate. Essentially typescript doesn't allow synthetic default imports when using `ModuleKind.ESNext`, which we need to do because deno now supports importing cjs. I'll open an issue in TypeScript tomorrow.

**Review by bartlomieju — APPROVED** [review]
