### PR TITLE
fix(ext/node): support O_RDONLY | O_CREAT in fs.openSync

### LINKED ISSUE #32107: fs.openSync fails with O_RDONLY + O_CREAT
The following program works find under node and bun:

```
import { openSync, closeSync, constants } from "node:fs";

// Create or open a file for writing, creates if it doesn't exist
const fd = openSync("./log.txt", constants.O_WRONLY | constants.O_CREAT);
// ... operations
closeSync(fd);
```

But not under deno:

```
$ ~/.deno/bin/deno -A test.mjs
error: Uncaught (in promise) TypeError: creating or truncating a file requires write or append access
const fd = openSync("missing.txt", constants.O_RDONLY | constants.O_CREAT);
           ^
    at openSync (ext:deno_node/_fs/_fs_open.ts:43:12)
    at file:///usr/local/google/home/sbc/dev/wasm/emscripten/test.mjs:3:12
```

The C equivalent also seem to work fine, so I think maybe deno is wrong here?

```
#include <stdio.h>
#include <fcntl.h>
#include <sys/stat.h>

int main() {
  int fd = open("missing.txt", O_RDONLY|O_CREAT, 0x777);
  printf("%d\n", fd);
  return 0;
}
```

I ran into this issue while porting the emscriptn test suite to Deno: https://github.com/emscripten-core/emscripten/issues/26235

### PR DESCRIPTION
**Pull request by shtse8**
## Description

POSIX allows `O_RDONLY | O_CREAT` to create a file if it doesn't exist and then open it for reading only. Node.js and other runtimes support this combination. However, Rust's `std::fs::OpenOptions` requires write or append access when `create` is set, causing Deno to throw:

```
error: Uncaught (in promise) TypeError: creating or truncating a file requires write or append access
```

## Changes

- **`ext/fs/std_fs.rs`**: Handle the `create && !write && !append` case in `open_with_checked_path` by first creating the file (if it doesn't exist) via a temporary write-mode open, then reopening for read-only access.
- **`ext/node/ops/fs.rs`**: Update `open_options_to_access_kind` to include `create` flag in the write access check, ensuring proper permissions are requested.
- **`tests/unit_node/_fs/_fs_open_test.ts`**: Add tests for `O_RDONLY | O_CREAT` with both new and existing files.

## Reproduction

```js
import { openSync, closeSync, constants } from "node:fs";
const fd = openSync("./new_file.txt", constants.O_RDONLY | constants.O_CREAT);
closeSync(fd);
```

This works in Node.js and Bun but throws in Deno.

Fixes #32107

### CODE REVIEW

File: ext/fs/std_fs.rs [hunk 1]
```diff
@@ -1029,13 +1029,49 @@ fn open_options(options: OpenOptions) -> fs::OpenOptions {
...
+    let read_opts = open_options_for_checked_path(
+      OpenOptions {
+        read: true,
+        write: false,
+        create: false,
+        truncate: false,
+        append: false,
+        create_new: false,
+        custom_flags: opts.custom_flags,
+        mode: None,
```
Comment (Tango992) [inline ext/fs/std_fs.rs:1067]:
```suggestion
        read: true,
        write: false,
        create: false,
        truncate: opts.truncate,
        append: false,
        create_new: false,
        custom_flags: opts.custom_flags,
        mode: opts.mode,
```

Should it be like this?

Comment (shtse8) [reply ext/fs/std_fs.rs:1067]: Thanks for the review!

The current values are intentional:

- `truncate: false` — Truncating a read-only fd doesn't make sense (and POSIX defines `O_RDONLY | O_TRUNC` as undefined behavior). The truncate flag is already handled in the creation step if it were combined with write.
- `mode: None` — The file permission mode is already applied during the creation step above (line 1048). When re-opening for read-only, mode has no effect so we skip it.

The `custom_flags` and other options that do affect reading behavior are passed through correctly.

Let me know if I'm missing a case you had in mind!

Comment (Tango992) [reply ext/fs/std_fs.rs:1067]: Ah right
