### PR TITLE
fix(lsp): update diagnostics on npm install

### LINKED ISSUE #21042: BYONM requires restart of lsp after running `npm install`
If you run `npm install` then an LSP restart is required for the new deps to be picked up. Ideally the lsp would watch the file system and react to any changes to the node_modules directory.

### PR DESCRIPTION
**Pull request by nayeemrmn**
Fixes #21042.

### CODE REVIEW

File: cli/lsp/config.rs [hunk 1]
```diff
@@ -1700,6 +1700,7 @@ impl ConfigTree {
     if specifier.path().ends_with("/deno.json")
       || specifier.path().ends_with("/deno.jsonc")
       || specifier.path().ends_with("/package.json")
+      || specifier.path().ends_with("/.package-lock.json")
```
Comment (marvinhagemeister) [inline cli/lsp/config.rs:1703]: The lockfile name is `package-lock.json` without the leading dot.

```suggestion
      || specifier.path().ends_with("/package-lock.json")
```

Should we watch the other package manager's lockfiles too like `yarn.lock`, `pnpm-lock.yaml` or `bun.lockb`?

File: tests/integration/lsp_tests.rs [hunk 2]
```diff
@@ -14647,6 +14646,51 @@ fn lsp_byonm() {
...
+        "code": "resolver-error",
+        "source": "deno",
+        "message": "Could not resolve \"@denotest/esm-basic\", but found it in a package.json. Deno expects the node_modules/ directory to be up to date. Did you forget to run `deno install`?",
+      },
+    ])
+  );
+  context.run_npm("install");
+  client.did_change_watched_files(json!({
+    "changes": [{
+      "uri": temp_dir.url().join("node_modules/.package-lock.json").unwrap(),
```
Comment (marvinhagemeister) [inline tests/integration/lsp_tests.rs:14689]:
```suggestion
      "uri": temp_dir.url().join("node_modules/package-lock.json").unwrap(),
```

File: cli/lsp/config.rs (hunk 1 above)
Comment (nayeemrmn) [reply cli/lsp/config.rs:1703]: There is this `node_modules/.package-lock.json` that this is supposed to watch, since it tracks population of `node_modules`. Both might work? But this one seems more apt.

File: tests/integration/lsp_tests.rs (hunk 2 above)
Comment (nayeemrmn) [reply tests/integration/lsp_tests.rs:14689]: See https://github.com/denoland/deno/pull/25352#discussion_r1741080948

File: cli/lsp/config.rs (hunk 1 above)
Comment (lucacasonato) [reply cli/lsp/config.rs:1703]: @nayeemrmn Maybe expliclty check for `node_modules/.package-lock.json`? Also `node_modules/.yarn-integrity`, `.modules.yaml` (pnpm), and `node_modules/.deno/.setup-cache.bin`.
