### PR TITLE
fix(cli): update permission prompt message for compiled binaries

### LINKED ISSUE #23250: Misleading recommendation for permissions when using compiled binary
see https://github.com/denoland/deno/discussions/18728

When I compile a program like the below

```
const file = await Deno.open("C:\\dev\\misc\\candel\\a.ts");
await file.readable.pipeTo(Deno.stdout.writable, { preventClose: true });
```

and run it (./cat.exe) I get the following:
```
┌ ⚠️  Deno requests read access to "C:\dev\misc\candel\a.ts".
├ Requested by `Deno.open()` API.
├ Run again with --allow-read to bypass this prompt.
└ Allow? [y/n/A] (y = yes, allow; n = no, deny; A = allow all read permissions) >
```
However, specifying ./cat.exe --allow-read results in the same prompt.

@mmastrac says the message should be changed

### PR DESCRIPTION
**Pull request by yazan-abdalrahman**
When running a compiled Deno program that requires permissions, the prompt message previously instructed users to rerun with `--allow-*` flags, which is incorrect for binaries.

Changes:
- Updated the permission prompt message to instruct users to specify required permissions during the compilation step using `deno compile --allow-*`.
- Adjusted `PermissionDenied` error messages to reflect the correct instructions for binaries.

This fix ensures that users are correctly informed about how to handle permissions for compiled Deno binaries.

Resolves #23250

### CODE REVIEW

**Comment by lucacasonato** [comment]
Did you write this PR yourself, or is it AI generated? The addition of `global_flags` crate seems somewhat unnecessary?

**Comment by yazan-abdalrahman** [comment]
> Did you write this PR yourself, or is it AI generated? The addition of `global_flags` crate seems somewhat unnecessary?

Hi @lucacasonato 

I wrote it,
I searched about dependencies to help me pass a flag to indicate that I am running from binary and not uniray. I found this is_unary param in the prompt method; it was hardcoded with a value of true; it was not passed along with the flow, so it is difficult to update the flow to pass it, so we need a flag to indicate we are running from binary standalone by passing the flag. I believe this idea is better. 

Do you have a better way?

File: runtime/permissions/lib.rs [hunk 1]
```diff
@@ -131,14 +132,20 @@ impl PermissionState {
   }
 
   fn error(name: &str, info: impl FnOnce() -> Option<String>) -> AnyError {
-    custom_error(
-      "PermissionDenied",
+    let msg = if is_running_from_binary() {
```
Comment (bartlomieju) [inline runtime/permissions/lib.rs:135]: It should be `!is_running_from_binary()`

File: runtime/permissions/prompter.rs [hunk 2]
```diff
@@ -274,8 +275,9 @@ impl PermissionPrompter for TtyPrompter {
     message: &str,
     name: &str,
     api_name: Option<&str>,
-    is_unary: bool,
+    mut is_unary: bool,
   ) -> PromptResponse {
+    is_unary = is_unary && !is_running_from_binary();
```
Comment (bartlomieju) [inline runtime/permissions/prompter.rs:280]: Can you explain why this is changing unary permission depending on the fact if it's self-compiled binary? I don't understand this part

File: global_flags/global_flags.rs [hunk 3]
```diff
@@ -0,0 +1,15 @@
...
+  pub static ref RUNNING_FROM_BINARY: AtomicBool = AtomicBool::new(false);
+}
+
+pub fn set_running_from_binary(value: bool) {
+  RUNNING_FROM_BINARY.store(value, Ordering::SeqCst);
+}
+
+pub fn is_running_from_binary() -> bool {
+  RUNNING_FROM_BINARY.load(Ordering::SeqCst)
+}
```
Comment (bartlomieju) [inline global_flags/global_flags.rs:15]: I'm really not a fan of adding a separate crate just to share a single boolean. I think we can leverage other approaches here. 

I think we should use `OpState` here and add two "wrapper" structs: one in `ext/fs` and other in `runtime`. These struct should looks something like this:
```
struct IsStandaloneBinary(bool)
```
The we should accept these struct in `options` bag in `deno_fs` and `deno_runtime` extensions and look them up when deciding which message to print.

@yazan-abdalrahman let me know if this is enough info to get you started

Comment (yazan-abdalrahman) [reply global_flags/global_flags.rs:15]: Hi @bartlomieju , Okay, I think it's enough. I'll edit it and include your notes.

File: runtime/permissions/prompter.rs (hunk 2 above)
Comment (yazan-abdalrahman) [reply runtime/permissions/prompter.rs:280]: I noticed that is_unary is set to true 'hardcoded'. For future use, I checked if is_unary was set to true or false. If true, I need to verify if it is running from binary by flag. If it's set to false, there's no need to check.

But I can unuse is _unary and depends on the flag, What do you want?

File: global_flags/global_flags.rs (hunk 3 above)
Comment (yazan-abdalrahman) [reply global_flags/global_flags.rs:15]: @bartlomieju 
I believe we can't use OpState because it is intended to maintain the resources and operations within a JS runtime.    and we need to provide a Boolean value to use it in chose prompt message and we don't know which code flow it will take.
So, we need it to be global, and I assumed in the future we would need something else in the same way, so I utilized crate.

and what is bag in **options bag in deno_fs and deno_runtime**?

Comment (bartlomieju) [reply global_flags/global_flags.rs:15]: > I believe we can't use OpState because it is intended to maintain the resources and operations within a JS runtime.

You can use it for whatever purpose you need, `OpState` will work here perfectly fine.

> and we need to provide a Boolean value to use it in chose prompt message and we don't know which code flow it will follow.

I'm not sure what you mean, can you explain?

> So, we need it to be global, and I assumed in the future we would need something else in the same way, so I utilized crate.

It doesn't need to be global, it just needs to be available to permission crate. We didn't have a need to any global prior so I don't think this assumption is necessarily correct.

> and what is bag in options bag in deno_fs and deno_runtime?

These options:
https://github.com/denoland/deno/blob/3be0a1e8b44782b2d3c3970e0e6fa7fb11be8131/ext/fs/lib.rs#L253-L258
https://github.com/denoland/deno/blob/3be0a1e8b44782b2d3c3970e0e6fa7fb11be8131/runtime/worker.rs#L329-L337

**Review by dsherret — APPROVED** [review]
LGTM
