### PR TITLE
fix(ext/web/streams): fix ReadableStream asyncIterator

### LINKED ISSUE #11253: ReadableStream async iterator behaviour is not spec compliant
We have many WPT failures for this: https://wpt.fyi/results/streams/readable-streams/async-iterator.any.html?label=master&label=experimental&product=chrome&product=deno&product=firefox&product=safari&aligned&q=streams

### PR DESCRIPTION
**Pull request by marcosc90**
This PR fixes `ReadableStream` asyncIterator:

- WPT is currently crashing on main for async iterator tests: https://wpt.fyi/results/streams/readable-streams/async-iterator.any.html?label=master&label=experimental&product=deno&aligned&view=subtest (37/39 tests with this patch)

Fixes #11253

### CODE REVIEW

File: ext/web/06_streams.js [hunk 1]
```diff
@@ -4379,7 +4380,7 @@
    * @returns {IteratorResult<T>}
    */
   function createIteratorResult(value, done) {
-    const result = ObjectCreate(null);
+    const result = ObjectCreate(ObjectPrototype);
```
Comment (marcosc90) [inline ext/web/06_streams.js:4383]: See: https://github.com/web-platform-tests/wpt/blob/0d21c20b40df4f3f1cb6418a2eedd494257543bb/streams/readable-streams/async-iterator.any.js#L12

Comment (aapoalas) [reply ext/web/06_streams.js:4383]: Is it thus necessary to create this with `ObjectCreate(ObjectPrototype)` or would the simple `{}` be enough? Or does that risk prototype pollution as well?

File: ext/webidl/00_webidl.js [hunk 2]
```diff
@@ -834,8 +834,7 @@
   }
 
   function createPromiseConverter(converter) {
-    return (V, opts) =>
-      PromisePrototypeThen(PromiseResolve(V), (V) => converter(V, opts));
+    return (V, opts) => PromiseResolve(converter(V, opts));
```
Comment (marcosc90) [inline ext/webidl/00_webidl.js:837]: This change is needed for:

- https://github.com/web-platform-tests/wpt/blob/0d21c20b40df4f3f1cb6418a2eedd494257543bb/streams/readable-streams/async-iterator.any.js#L439
- https://github.com/web-platform-tests/wpt/blob/0d21c20b40df4f3f1cb6418a2eedd494257543bb/streams/readable-streams/async-iterator.any.js#L460

`createPromiseConverter` is only used in `06_streams.js`, no side effect detected so far.

File: ext/web/06_streams.js (hunk 1 above)
Comment (marcosc90) [reply ext/web/06_streams.js:4383]: It is needed, after `Object.defineProperties` is called `Object.getPrototypeOf(result) === Object.prototype;` is no longer true, and that assertion fails.

https://github.com/denoland/deno/blob/1e7c3c94c4fa3d38232ee9737b1b281370e30909/ext/web/06_streams.js#L4382-L4394

**Comment by marcosc90** [comment]
I found several other bugs in the internal usage of streams, I'll remove the change to [ext/webidl/00_webidl.js](https://github.com/denoland/deno/pull/16276/files/1e7c3c94c4fa3d38232ee9737b1b281370e30909#diff-9f6f9450a19221ebe43958b01a818135a3f52715e2d59bd89dc32d339616e7b2) in this PR:

```
function createPromiseConverter(converter) {
    return (V, opts) => PromiseResolve(converter(V, opts));
}
```

And open a follow-up PR to fix those, since it's out of scope of this PR.

File: ext/web/06_streams.js (hunk 1 above)
Comment (aduh95) [reply ext/web/06_streams.js:4383]: What about `return { value, done }`?

Comment (marcosc90) [reply ext/web/06_streams.js:4383]: @aduh95 that was my first thought, but I wanted to make minimal changes only to fix the tests, both yield the same results. TBH I would remove `createIteratorResult` to avoid the extra overhead.

Comment (aduh95) [reply ext/web/06_streams.js:4383]: > TBH I would remove createIteratorResult to avoid the extra overhead.

+1, it's only used 5 times in the whole codebase, so it wouldn't be a lot of work indeed.

Comment (lucacasonato) [reply ext/web/06_streams.js:4383]: This is correct as per. https://tc39.es/ecma262/#sec-createiterresultobject

**Review by crowlKats — APPROVED** [review]
LGTM

**Comment by crowlKats** [comment]
@marcosc90 do you have any idea about the remaining 2 failing tests?

**Comment by marcosc90** [comment]
> @marcosc90 do you have any idea about the remaining 2 failing tests?

Yes, those are fixed by this PR https://github.com/denoland/deno/pull/16367
