### PR TITLE
fix(core/modules): Prepare modules only once per runtime

### LINKED ISSUE #9802: Module graph is too eager to re-check
The module graph is a bit too eager to reload and re-check and this doesn't work that great in certain scenarios.

For example with reload set to true, it'll always re-check for each dynamic import and worker instantiation:

```js
for (let i = 0; i < 1000; i++) {
  const worker = new Worker(new URL("./worker.ts", import.meta.url).href, { type: 'module' });
}
```

Depending on the complexity of the graph, the above code can forever to execute with `deno run --reload`.

We want to check against something like `needs_reload(specifier)` rather than just `flags.reload` in `module_graph.check`.

### LINKED ISSUE #11014: Redundant re-checking of dynamic imports
image

You can cause the module to be type-checked again by changing the file between repeated dynamic imports, but the module is already loaded so this should not happen.

_Fully_ short-circuiting a repeated dynamic import is quite hard, but we can easily skip the `load_prepare()` step under certain conditions. Fix coming.

This is unrelated to #9802.

### PR DESCRIPTION
**Pull request by nayeemrmn**
Fixes #9802.
Fixes #11014.

### CODE REVIEW

**Comment by nayeemrmn** [comment]
@bartlomieju Please review.

File: core/modules.rs [hunk 1]
```diff
@@ -648,17 +603,32 @@ impl ModuleMap {
...
     specifier: &str,
     code: Option<String>,
-  ) -> RecursiveModuleLoad {
-    RecursiveModuleLoad::main(
+  ) -> Result<RecursiveModuleLoad, AnyError> {
+    let module_specifier =
+      self
+        .loader
+        .resolve(self.op_state.clone(), specifier, ".", true)?;
+    let load = RecursiveModuleLoad::main(
```
Comment (bartlomieju) [inline core/modules.rs:615]: I don't really understand changes in this file. Please explain.

Comment (nayeemrmn) [reply core/modules.rs:615]: Other than adding [this code path](https://github.com/denoland/deno/pull/11015/files#diff-aa01489135c068a2056422f99878ba91861c585baed075470c08c1ac439ab3b2R654-R655) to short-circuit preparing dynamic imported modules already in the module map, there are two refactors:
1. Move [this code](https://github.com/denoland/deno/pull/11015/files#diff-5b779288098bb6449725245ce7fdb1ec3190563b5dd255e747cfc35e639407aeL1258) (after the singular call site of `ModuleMap::load_main()`) inside of `ModuleMap::load_main()` to make its functionality more similar to `ModuleMap::load_dynamic_import()`.
2. Remove and inline `RecursiveModuleLoad::prepare()` at its two call sites in `ModuleMap::load_main()` and `ModuleMap::load_dynamic_import()`. Something like `RecursiveModuleLoad::prepare()` should probably still exist, but that would lead to a duplicate resolve in `ModuleMap::load_dynamic_import()`.

Comment (bartlomieju) [reply core/modules.rs:615]: > Other than adding this code path to short-circuit preparing dynamic imported modules already in the module map, there are two refactors:


I'm a bit weary about it. This function is one of problems in #8421 and I'm making strides to rewrite it into a future instead.

> - Move this code (after the singular call site of ModuleMap::load_main()) inside of ModuleMap::load_main() to make its functionality more similar to ModuleMap::load_dynamic_import(). 
> - Remove and inline RecursiveModuleLoad::prepare() at its two call sites in ModuleMap::load_main() and ModuleMap::load_dynamic_import(). Something like RecursiveModuleLoad::prepare() should probably still exist, but that would lead to a duplicate resolve in ModuleMap::load_dynamic_import().

So these two are just cleanups to make more of the APIs internal to `ModuleMap`. Can't `RecursiveModuleLoad::prepare()` be left as is and called by those two related methods? I'm worried they might diverge at some point.

Anyway, the tests look good and are passing so I think I'll land it and worry about potential troubles with `is_registered` later

Comment (bartlomieju) [reply core/modules.rs:615]: Though I'd like to get @kitsonk's review as well as this PR touches the module graph.

Comment (nayeemrmn) [reply core/modules.rs:615]: > Can't `RecursiveModuleLoad::prepare()` be left as is and called by those two related methods? I'm worried they might diverge at some point.

Diverging isn't a problem, the two call sites after still share nothing except for a `prepare_load()` call. You'll notice `RecursiveModuleLoad::prepare()` had two separate code paths for if it was called from `load_main()` or `load_dynamic_import()`, which is why I thought to inline it. The amount of shared code is the same as it was before.

It's awkward because `RecursiveModuleLoad` would ideally keep a method for preparing itself, but as I mentioned that creates complications as to where and how many times `resolve()` is called in `load_dynamic_import()`.

Comment (bartlomieju) [reply core/modules.rs:615]: > Diverging isn't a problem, the two call sites after still share nothing except for a prepare_load() call. You'll notice RecursiveModuleLoad::prepare() had two separate code paths for if it was called from load_main() or load_dynamic_import(), which is why I thought to inline it. The amount of shared code is the same as it was before.

Of course 🤦‍♂️ that makes perfect sense

It's awkward because RecursiveModuleLoad would ideally keep a method for preparing itself, but as I mentioned that creates complications as to where and how many times resolve() is called in load_dynamic_import().

Is it a problem that resolve is called multiple times? It should be idempotent after all.

Comment (nayeemrmn) [reply core/modules.rs]: Okay, I've brought back `RecursiveModuleLoad::prepare()`. I think `resolve()` has duped calls in other places anyway. On another note I want to see if I can make simplifications to `RecursiveModuleLoad::state`/`LoadState`.

Comment (bartlomieju) [reply core/modules.rs]: @nayeemrmn just a heads up that I'm also working on `core/modules.rs` in #10809

Comment (nayeemrmn) [reply core/modules.rs]: I've replaced the following structure:
```rust
struct RecursiveModuleLoad {
  state: LoadState,
  // ...
}

enum LoadState {
  ResolveMain(String, Option<String>),
  ResolveImport(String, String),
  LoadingRoot,
  LoadingImports,
  Done,
}
```
with:
```rust
struct RecursiveModuleLoad {
  init: LoadInit,
  state: LoadState,
  // ...
}

enum LoadInit {
  Main(String), // specifier
  MainWithCode(String, String), // specifier, code
  DynamicImport(String, String), // specifier, referrer
}

enum LoadState {
  Init,
  LoadingRoot,
  LoadingImports,
  Done,
}
```
It's a lot more intuitive and usable. Reading `impl Stream for RecursiveModuleLoad {}` is a lot easier.

Comment (bartlomieju) [reply core/modules.rs]: @nayeemrmn just to be clear, nothing changed in the actual behavior of `RecursiveModuleLoad`?

Comment (nayeemrmn) [reply core/modules.rs]: > nothing changed in the actual behavior of `RecursiveModuleLoad`?

Correct, it's a refactor.

File: cli/module_graph.rs [hunk 2]
```diff
@@ -610,7 +611,7 @@ pub struct BundleOptions {
 }
 
 #[derive(Debug, Default)]
-pub struct CheckOptions {
+pub struct CheckOptions<'a> {
```
Comment (kitsonk) [inline cli/module_graph.rs:614]: It seems like we are really going out of our way to avoid some cloning, which makes for some really ugly code.  I would much rather prefer we not throw pointer lifetimes everywhere and have to call stuff with `Cow::borrow`.

Comment (nayeemrmn) [reply cli/module_graph.rs]: `Cow` was the least obtrusive way I knew of to get it to satisfy `Default`, which was the only problem with a simple reference. I've changed it to just clone the the sets instead.

**Review by bartlomieju — APPROVED** [review]
LGTM, thank you Nayeem, this is a good fix and gave me an idea how to fix problems in concurrent module loading.

File: cli/module_graph.rs (hunk 2 above)
Comment (nayeemrmn) [reply cli/module_graph.rs]: 😅 Turns out no cloning is necessary anyway, there's only one consumption per branch. My mistake.
