### PR TITLE
fix(fmt): delegate component expression formatting to markup_fmt

### LINKED ISSUE #26999: fmt(svelte): formatter error on dynamic style in svelte
Version: Deno 2.1.1

```svelte
<script lang="ts">
  const { color }: { color: string | null } = $props();
</script>

<div
  style="background-color: {color || 'blueviolet'};"
>
</div>
```
```txt
deno fmt --unstable-component
Error formatting: C:\temp\deno-init\test.svelte
   syntax error at line 6, col 28: expect token `<ident>`, but found `{`
Checked 4 files
```

### PR DESCRIPTION
**Pull request by janosh**
closes #26999

This PR now solves component expression formatting by delegating parsing/formatting to `markup_fmt` instead of using Deno-side regex placeholder preprocessing.

## What changed
- upgraded `markup_fmt` and aligned Deno formatter config with the newer API
- removed local `format_expressions_in_text(...)` preprocessing/restore pipeline
- routed component formatting through `markup_fmt` as the single parser/formatter source of truth
- updated Svelte/Vue fixtures and related fmt expectations to current formatter output
- preserved Jinja/Nunjucks pseudo-block text in callback handling to avoid invalid JS formatting attempts

## Why this approach
Earlier review feedback called out regex preprocessing as fragile (for example formatting inside comments). This version avoids that class of issues by relying on `markup_fmt`'s native parse tree and language-aware formatting behavior.

### CODE REVIEW

File: cli/tools/fmt.rs [hunk 1]
```diff
@@ -404,14 +404,105 @@ fn format_yaml(
...
   file_text: &str,
   fmt_options: &FmtOptionsConfig,
   unstable_options: &UnstableFmtOptions,
 ) -> Result<Option<String>, AnyError> {
+  // Pre-format expressions in component files before markup parsing
+  let (preprocessed_text, expressions) =
+    if let Some(ext) = file_path.extension().and_then(|e| e.to_str()) {
+      let (pattern, open, close) = match ext.to_ascii_lowercase().as_str() {
+        "svelte" | "astro" => (r"\{([^{}]+)\}", "{", "}"),
+        "vue" => (r"\{\{([^{}]+)\}\}", "{{", "}}"),
```
Comment (dsherret) [inline cli/tools/fmt.rs]: This seems very error prone to do (ex. it would format within comments). Probably it should be handled by markup_fmt instead and it can call out to format these expressions with the appropriate formatter.

Comment (janosh) [reply cli/tools/fmt.rs]: @dsherret thanks for the earlier feedback! sorry for the long radio silence, just remembered i've been meaning to finish this 😅 

i reworked this PR to address your concern about the regex-based preprocessing:

- dropped local expression placeholder pipeline in `cli/tools/fmt.rs`:
  - deleted `format_expressions_in_text(...)`
  - removed preprocess/restore logic around `format_html(...)`
- `format_html(...)` now passes the original text directly to `markup_fmt` (single source of truth for parsing/formatting), instead of trying to rewrite expressions in Deno first
- Upgraded `markup_fmt` from `0.19.1` to `0.22.0`

ready for another review

**Comment by janosh** [comment]
@bartlomieju the "ensure CI success" error looks like a false positive. anything i need to do here?

**Comment by bartlomieju** [comment]
Review from Claude. No 2 and 4 look concerning :( 

### 1. PR title/description is misleading

The title says "Add expression formatting in CSS strings for components" and the description mentions a `format_expressions_in_text` function — but the diff contains neither. The actual change is a `markup_fmt` version bump plus config field additions. The expression formatting likely comes from the library upgrade itself, not from code in this PR.

### 2. Svelte test file loses trailing newline

```diff
-</style>
+</style>
\ No newline at end of file
```

`badly_formatted.svelte` now lacks a trailing newline. The fixed counterpart (`badly_formatted_fixed.svelte`) already ends with a newline, so after formatting, the file gains a newline it didn't have. This is fine functionally but the input file should probably retain the trailing newline for consistency — removing it seems unintentional.

### 3. New config fields use hardcoded defaults without documentation

```rust
vue_component_case: config::VueComponentCase::Ignore,
angular_next_control_flow_same_line: true,
```

These are set in two places (`format_embedded_html` and `get_resolved_markup_fmt_config`) with no user-facing configuration. If `markup_fmt` 0.26.0 changes behavior based on these, users can't control it. Are these the correct defaults? `VueComponentCase::Ignore` seems safe, but `angular_next_control_flow_same_line: true` is an opinionated choice with no way to override.

### 4. Vue formatted output swaps quote styles

The formatted Vue output changes `"` to `'` for attribute values containing JS strings:

```html
<!-- input -->
:style="{ width: a + b + 'px' }"
<!-- output -->
:style='{ width: a + b + "px" }'
```

This is technically valid HTML but may surprise users who consistently use double quotes for attributes. This behavior comes from `markup_fmt` and may not be configurable — worth confirming it's intentional and won't break tools that parse HTML expecting double-quoted attributes.

### 5. Jinja handler matches on string prefix — fragile

```rust
ext if ext.starts_with("markup-fmt-jinja-") => {
    Ok(Cow::from(text))
}
```

This relies on `markup_fmt` 0.26.0 passing extensions with exactly this prefix. If the library changes the prefix convention in a future version, this silently breaks. A comment referencing where this convention is documented in `markup_fmt` would help.

**Comment by janosh** [comment]
@bartlomieju thanks a lot for the thorough review, all good points!

- retitled and rewrote the PR description to reflect the real scope (markup_fmt-driven behavior) since the initial attempt at closing https://github.com/denoland/deno/issues/26999 was very different
- restored the trailing newline in `badly_formatted.svelte` for fixture consistency.
- added user-facing fmt config support for `vueComponentCase` and `angularNextControlFlowSameLine`
   - wired these through config resolution and formatter code paths (including workspace config merge behavior).
- kept expected fixture output aligned with current formatter behavior and clarified this behavior is owned by `markup_fmt`.
- kept the jinja passthrough behavior but added an upstream source reference in code for the `markup-fmt-jinja-*` extension naming convention.

**Comment by janosh** [comment]
would be great to get this merged! i'm currently blocked from upgrading beyond `deno` 2.3.7 by this. let me know if anything left to address

**Comment by bartlomieju** [comment]
I will land https://github.com/denoland/deno/pull/32949 first, to not confuse crate upgrade with additional changes
