### PR TITLE
fix(ext/node): `fs.exists` and `fs.existsSync` compatibility

### LINKED ISSUE #30506: `node:fs` `exists` returns true on invalid symlink on windows
Version: Deno 2.4.5

Given this code:
```ts
import { existsSync, symlinkSync } from "node:fs";

symlinkSync('./noop.txt', './noop.link')
const result = existsSync('./noop.link')
console.log(result)
```

Result:
```
PS F:\foo> node .\test-exists.js
false
PS F:\foo> deno -A .\test-exists.js
true
```

### PR DESCRIPTION
**Pull request by Tango992**
Closes #30506

Other changes:
- Emit deprecation warning.
- Allows [parallel/test-fs-exists.js](https://github.com/nodejs/node/blob/v24.2.0/test/parallel/test-fs-exists.js) to pass.
- Allows [test-fs-symlink-dir-junction.js](https://github.com/nodejs/node/blob/v24.2.0/test/parallel/test-fs-symlink-dir-junction.js) to pass. Previously it always fail due to invalid assertion using `existsSync`.

### CODE REVIEW

File: ext/fs/std_fs.rs [hunk 1]
```diff
@@ -1021,20 +1021,7 @@ fn exists(path: &Path) -> bool {
...
-
-    let path = path
-      .as_os_str()
-      .encode_wide()
-      .chain(std::iter::once(0))
-      .collect::<Vec<_>>();
-    // Safety: `path` is a null-terminated string
-    let attrs = unsafe { GetFileAttributesW(path.as_ptr()) };
-
-    attrs != INVALID_FILE_ATTRIBUTES
```
Comment (bartlomieju) [inline ext/fs/std_fs.rs:1037]: This is fishy 👀 can you explain why you opted to remove this low-level API call?

Comment (Tango992) [reply ext/fs/std_fs.rs:1037]: `GetFileAttributesW` doesn't actually follow symlinks, so invalid symlinks will return `true`.

Referencing https://learn.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-getfileattributesw :
> Symbolic link behavior—If the path points to a symbolic link, the function returns attributes for the symbolic link.

I thought it's better to use the stdlib's `exists` instead (https://doc.rust-lang.org/std/fs/fn.exists.html). What do you think?

Comment (bartlomieju) [reply ext/fs/std_fs.rs:1037]: I'm gonna defer to @dsherret who knows Windows better

Comment (dsherret) [reply ext/fs/std_fs.rs:1037]: Looks like this was done for perf: https://github.com/denoland/deno/pull/24613 -- but also before we were doing way too much work in our stat calls.

Overall this seems fine.

File: cli/rt/file_system.rs [hunk 2]
```diff
@@ -207,6 +207,17 @@ impl FileSystem for DenoRtSys {
     RealFs.chown_async(path, uid, gid).await
   }
 
+  fn exists_sync(&self, path: &CheckedPath) -> bool {
+    if self.error_if_in_vfs(path).is_err() {
```
Comment (dsherret) [inline cli/rt/file_system.rs]: This is wrong. It should only call this function for write operations. Look at `stat_sync` for an example.

**Review by dsherret — APPROVED** [review]
LGTM!
