### PR TITLE
fix(runtime/windows): ensure `Deno.stdin.setRaw(false)` properly disables raw mode

### LINKED ISSUE #17866: 🐛`Deno.stdin.setRaw(false)` does not disable ENABLE_VIRTUAL_TERMINAL_INPUT
@dsherret , @bartlomieju (I saw that you both collaborated on the last change to the ops code.)

`Deno.stdin.setRaw(false)` does not disable ENABLE_VIRTUAL_TERMINAL_INPUT. Consequently, using `Deno.stdin.setRaw(true)` in a script always leaves the terminal in "virtual terminal input" mode back at the command line, disabling arrow usage.

```shell
C> ver
Microsoft Windows [Version 10.0.19044.2604]
C>deno -V
deno 1.30.3
```

To show the bug, execute this script:

```typescript
// `deno run -A --unstable $0`

// Deno.stdin.setRaw(false) *does not* turn off ENABLE_VIRTUAL_TERMINAL_INPUT (DWORD = 0x0200) for STDIN
// ... causes incorrect/odd input for arrow keys at CMD line after use

// ref: rust ops code @ <https://github.com/denoland/deno/blob/d5634164cb86771fc279468cbb93e311c1ad3089/runtime/ops/tty.rs#L46-L102>
// ref: commit @ <https://github.com/denoland/deno/commit/715f35d635bf5a4e972238e6ac8d290c0e096083>
// ref: test(s) @ <https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=d126c95579fdc2dca91b14684ffe6f68>

// spell-checker: ignore (winos) getch kbhit

console.log(`stdin: isatty()=${Deno.isatty(Deno.stdin.rid)}`);

const dllKernel = (() => {
  try {
    return (Deno as any).dlopen?.("kernel32.dll", {
      "GetConsoleMode":
        /* https://learn.microsoft.com/en-us/windows/console/getconsolemode */ {
          parameters: ["pointer", "buffer"],
          result: "u32",
        },
      "GetStdHandle":
        /* https://learn.microsoft.com/en-us/windows/console/getstdhandle */ {
          parameters: ["u32"],
          result: "pointer",
        },
      "SetConsoleMode":
        /* https://learn.microsoft.com/en-us/windows/console/setconsolemode */ {
          parameters: ["pointer", "u32"],
          result: "u32",
        },
    });
  } catch {
    return undefined;
  }
})();

console.log({ dllKernel });
if (dllKernel == null) {
  console.warn(
    `Unable to load DLLs; use \`deno run -A --unstable "${Deno.mainModule}"\``,
  );
}

const ENABLE_VIRTUAL_TERMINAL_INPUT = 0x0200;
const stdinID = 4294967286; /* stdin == (DWORD(-10)) */
const stdinHandle = dllKernel.symbols.GetStdHandle(stdinID);

{
  const buffer = new Uint32Array(1).fill(0);
  const _ = dllKernel.symbols.GetConsoleMode(stdinHandle, buffer);
  const consoleMode = buffer[0];
  console.log("initial ::", {
    stdinHandle,
    buffer,
    consoleMode: "0x" + consoleMode.toString(16),
  });
}

Deno.stdin.setRaw(true);

{
  const buffer = new Uint32Array(1).fill(0);
  const _ = dllKernel.symbols.GetConsoleMode(stdinHandle, buffer);
  const consoleMode = buffer[0];
  console.log("setRaw(true)", {
    stdinHandle,
    buffer,
    consoleMode: "0x" + consoleMode.toString(16),
  });
}

Deno.stdin.setRaw(false);

{
  const buffer = new Uint32Array(1).fill(0);
  const _ = dllKernel.symbols.GetConsoleMode(stdinHandle, buffer);
  const consoleMode = buffer[0];
  console.log("setRaw(false)", {
    stdinHandle,
    buffer,
    consoleMode: "0x" + consoleMode.toString(16),
  });
}

//=== cut here

{
  // * disable ENABLE_VIRTUAL_TERMINAL_INPUT manually with FFI `SetConsoleMode()`
  const buffer = new Uint32Array(1).fill(0);
  const _0 = dllKernel.symbols.GetConsoleMode(stdinHandle, buffer);
  let consoleMode = buffer[0];
  consoleMode = consoleMode & ~ENABLE_VIRTUAL_TERMINAL_INPUT;
  const _1 = dllKernel.symbols.SetConsoleMode(stdinHandle, consoleMode);
}

{
  const buffer = new Uint32Array(1).fill(0);
  const _ = dllKernel.symbols.GetConsoleMode(stdinHandle, buffer);
  const consoleMode = buffer[0];
  console.log("after SetConsoleMode()", {
    stdinHandle,
    buffer,
    consoleMode: "0x" + consoleMode.toString(16),
  });
}
```

For the usual CMD shell terminal, the output is ...

```text
stdin: isatty()=true
{
  dllKernel: DynamicLibrary {
    symbols: {
      SetConsoleMode: [Function],
      GetConsoleMode: [Function],
      GetStdHandle: [Function]
    }
  }
}
initial :: { stdinHandle: 88, buffer: Uint32Array(1) [ 247 ], consoleMode: "0xf7" }
setRaw(true) { stdinHandle: 88, buffer: Uint32Array(1) [ 752 ], consoleMode: "0x2f0" }
setRaw(false) { stdinHandle: 88, buffer: Uint32Array(1) [ 759 ], consoleMode: "0x2f7" }
after SetConsoleMode() { stdinHandle: 88, buffer: Uint32Array(1) [ 247 ], consoleMode: "0xf7" }
```

For Windows Terminal, the output is ...

``` text
stdin: isatty()=true
{
  dllKernel: DynamicLibrary {
    symbols: {
      SetConsoleMode: [Function],
      GetConsoleMode: [Function],
      GetStdHandle: [Function]
    }
  }
}
initial :: { stdinHandle: 76, buffer: Uint32Array(1) [ 503 ], consoleMode: "0x1f7" }
setRaw(true) { stdinHandle: 76, buffer: Uint32Array(1) [ 1008 ], consoleMode: "0x3f0" }
setRaw(false) { stdinHandle: 76, buffer: Uint32Array(1) [ 1015 ], consoleMode: "0x3f7" }
after SetConsoleMode() { stdinHandle: 76, buffer: Uint32Array(1) [ 503 ], consoleMode: "0x1f7" }
```

Disabling the code below `//=== cut here` will leave the command line with disabled arrow keys (displaying character sequences instead of interpreting the arrows).

EDIT: ~I'm not sure where the bug is occurring; the deno ops code looks correct.~ On second look, the problem is in the ops code...

https://github.com/denoland/deno/blob/d5634164cb86771fc279468cbb93e311c1ad3089/runtime/ops/tty.rs#L89-L93

The precedence of `&` is higher than `|`, so parentheses are needed and this code should be...

```rust
      let new_mode = if is_raw {
        original_mode & !RAW_MODE_MASK | wincon::ENABLE_VIRTUAL_TERMINAL_INPUT
      } else {
        ( original_mode | RAW_MODE_MASK ) & !wincon::ENABLE_VIRTUAL_TERMINAL_INPUT
      };
```

### PR DESCRIPTION
**Pull request by rivy**
Compilation and tests are passing in local CI.
Ready for feedback.

Fixes #17866.

### CODE REVIEW

File: runtime/ops/tty.rs [hunk 1]
```diff
@@ -43,6 +43,27 @@ pub fn init() -> Extension {
...
+    & ! COOKED_MODE // disable line-by-line input, character echo, and system control key handling
+    | wincon::ENABLE_VIRTUAL_TERMINAL_INPUT // enable console/system handling of virtual terminal sequences
+}
+
+#[cfg(windows)]
+fn mode_raw_input_off(original_mode: DWORD) -> DWORD {
+  original_mode // disable, then enable (`&` has higher precedence than `|`)
+    & ! wincon::ENABLE_VIRTUAL_TERMINAL_INPUT // disable console/system handling of virtual terminal sequences
+    | COOKED_MODE // enable line-by-line input, character echo, and system control key handling
+}
```
Comment (dsherret) [inline runtime/ops/tty.rs:65]: Less verbose. Also, don't think we need an archive link because that can always be found via the original url.

```suggestion
// ref: https://learn.microsoft.com/en-us/windows/console/setconsolemode
#[cfg(windows)]
const COOKED_MODE: DWORD =
  // line-by-line input (returns input only after CR is read)
  wincon::ENABLE_LINE_INPUT
  // real-time character echo to console display (requires ENABLE_LINE_INPUT)
  | wincon::ENABLE_ECHO_INPUT
  // system handles CTRL-C (with ENABLE_LINE_INPUT, also handles BS, CR, and LF)
  // and other control keys (when using `ReadFile` or `ReadConsole`)
  | wincon::ENABLE_PROCESSED_INPUT;

#[cfg(windows)]
fn mode_raw_input_on(original_mode: DWORD) -> DWORD {
  original_mode & !COOKED_MODE | wincon::ENABLE_VIRTUAL_TERMINAL_INPUT
}

#[cfg(windows)]
fn mode_raw_input_off(original_mode: DWORD) -> DWORD {
  original_mode & !wincon::ENABLE_VIRTUAL_TERMINAL_INPUT | COOKED_MODE
}
```

File: runtime/ops/tty.rs [hunk 2]
```diff
@@ -271,3 +289,32 @@ pub fn console_size(
     }
   }
 }
+
+#[cfg(all(test, windows))]
+mod tests {
+  #[cfg(windows)]
+  #[test]
```
Comment (dsherret) [inline runtime/ops/tty.rs:296]:
```suggestion
  #[test]
```

**Review by dsherret — APPROVED** [review]
LGTM. Thanks @rivy!

**Comment by dsherret** [comment]
@rivy could you enable pushes from maintainers? I was going to merge this now, but then couldn't push the changes.

**Comment by rivy** [comment]
The permission checkbox is missing... ?
I'll merge your feedback changes and re-push the PR.

**Comment by rivy** [comment]
@dsherret , I force pushed to requested changes.
Did you want me to rebase it onto `main`?

**Comment by dsherret** [comment]
@rivy no, it's good. We squash merge everything so the commits in the PR don't matter. Thanks! Going to merge this now.
