### PR TITLE
fix: std/testing/runner.ts and deno test

### LINKED ISSUE #4413: `deno test` always returns 0 exit code
In v0.36.0 `deno test` always returns a 0 exit code, even on failed tests.

Example:
```typescript
Deno.test(function example() {
  throw new Error("hello world");
});
```

### PR DESCRIPTION
**Pull request by bartlomieju**
After splitting `failFast` and `exitOnFail` arguments, there was a situation where failing tests did not exit with code 1. 

Fixed:
* argument value passed to `Deno.runTests()` in `deno test`
* argument value passed to `Deno.runTests()` in `std/testing/runner.ts`
* added integration tests for `deno test` to ensure `failFast` and `exitOnFail` work as expected
* doesn't write test file to FS, but keeps it in memory

Closes #4413

### CODE REVIEW

**Comment by nayeemrmn** [comment]
Failures in https://github.com/denoland/deno/runs/509330266 will have to be fixed as well. Or reverted, but I think tests just need changes to some directory references.

File: cli/lib.rs [hunk 1]
```diff
@@ -393,7 +393,10 @@ async fn test_command(
   }
 
   let test_file = test_runner::render_test_file(test_modules, fail_fast);
-  let test_file_path = cwd.join(".deno.test.ts");
+  // Interpolated with pid, because multiple deno process may be run in current
+  // directory to run tests.
+  let filename = format!(".deno.{}.test.ts", std::process::id());
+  let test_file_path = cwd.join(filename);
```
Comment (ry) [inline cli/lib.rs]: Is there a good reason to place this in the cwd? Why not a temp file?

Comment (nayeemrmn) [reply cli/lib.rs]: Yeah, I think it was to avoid recompilation for repeat `deno test` in the same conditions but if the name is different each time that doesn't apply anymore.

Comment (bartlomieju) [reply cli/lib.rs]: @nayeemrmn good point, now I forgot about it :/ I hit issue of name collision when I added two integration tests for runner - both of them create file almost simultaneously and one of the test is failing.

Comment (bartlomieju) [reply cli/lib.rs]: Removed writing to fs completely, used the same logic as for `deno eval` and `deno` (repl). Let's see how this works out
