### PR TITLE
fix(cli): avoid `deno add` and `deno vendor` errors when deno.json is empty

### LINKED ISSUE #23215: `deno add` - Failed updating config file due to no object
No need to error. Just create the config object for me when the deno.json is blank.

```
> deno add @std/csv
error: Failed updating config file due to no object.
```

Version: Deno 1.42.1

### PR DESCRIPTION
**Pull request by nokazn**
Avoid "Failed updating config file due to no object" errors for the below commands when existing `deno.json` is empty. Added a test case for each.

- `deno add` (c0f410d50652acf9316fdca52e5cc919770ff419)
  - fix #23215
- `deno vendor` (46fdc7f9f46788c0cb384f8dccd50d30b90ecddf)
  - not listed in the issue, but errors occur in the same way

### CODE REVIEW

File: cli/tools/registry/pm.rs [hunk 1]
```diff
@@ -109,8 +109,14 @@ pub async fn add(flags: Flags, add_flags: AddFlags) -> Result<(), AnyError> {
...
-  let config_file_contents =
-    tokio::fs::read_to_string(&config_file_path).await.unwrap();
+  let config_file_contents = {
+    let contents = tokio::fs::read_to_string(&config_file_path).await.unwrap();
+    if contents.trim().is_empty() {
+      "{}\n".into()
+    } else {
+      contents
+    }
+  };
```
Comment (dsherret) [inline cli/tools/registry/pm.rs:119]: Does it work instead if we check below for `Value::Null`?

```rs
let obj = match ast.value {
    Some(Value::Object(obj)) => obj,
    Some(Value::Null) => Default::default(),
    _ => bail!("Failed updating config file due to no object."),
  };
```

Comment (dsherret) [reply cli/tools/registry/pm.rs:119]: Oh, my guess is no. Nevermind.

**Review by dsherret — APPROVED** [review]
LGTM. Thanks!
