### PR TITLE
fix(npm): only include top level packages in top level node_modules directory

### LINKED ISSUE #18822: npm:mongodb URLSearchParams problem with whatwg-url
Hi,

I am trying to use the npm:mongodb module. When I run my code, sometimes it runs correctly, but sometimes it throws an error like this;

```js
Error connecting to MongoDB:  TypeError: Cannot read properties of undefined (reading 'constructor')
    at new ConnectionString (file:///D:/deno.land/deno-gps-server-with-mqtt/node_modules/.deno/mongodb@5.3.0/node_modules/mongodb-connection-string-url/lib/index.js:153:98)
    at parseOptions (file:///D:/deno.land/deno-gps-server-with-mqtt/node_modules/.deno/mongodb@5.3.0/node_modules/mongodb/lib/connection_string.js:191:17)
    at new MongoClient (file:///D:/deno.land/deno-gps-server-with-mqtt/node_modules/.deno/mongodb@5.3.0/node_modules/mongodb/lib/mongo_client.js:46:63)
    at MongoDBDatabase.connect (file:///D:/deno.land/deno-gps-server-with-mqtt/src/db/Mongo.ts:156:27)
    at DBWorker.connectToDbAndPrepare (file:///D:/deno.land/deno-gps-server-with-mqtt/src/DBWorker.ts:45:28)
    at default.runServer (file:///D:/deno.land/deno-gps-server-with-mqtt/src/gps_server.ts:111:27)
    at file:///D:/deno.land/deno-gps-server-with-mqtt/src/main.ts:104:10
```

When I investigated the reason for this, I saw that searchParams was undefined on this.searchParams.constructor in the file:///D:/deno.land/deno-gps-server-with-mqtt/node_modules/.deno/mongodb@5.3.0/node_modules/mongodb-connection-string-url/lib/index.js:153:98 line.

I thought this might be related to the whatwg-url package and when I looked at the version in node_modules, I saw that it was 5.0.0. When I ran my code while keeping the package.json file of this module open, I noticed something. 
If my code is executed properly, the whatwg-url files change and the version becomes 11.0.0. But if my code gives the undefined error above, the whatwg-url package.json file changes and the version becomes 5.0.0.0. I don't understand the reason for this. 

You can see a video about this.

[Screen record](https://youtu.be/4BmXW0otpQs)

### PR DESCRIPTION
**Pull request by dsherret**
We were indeterministically including packages in the top level `node_modules/` folder when using a local node_modules directory. This change aligns with pnpm and only includes top level packages in this folder. This should be faster for initializing the folder, but may expose issues in packages that reference other packages not defined in their dependencies. That said, the behaviour previously was previously broken.

This has exposed a bug in the require implementation where it doesn't find a package (which is the main underlying issue here). There is a failing test already for this in the test suite after this change.

Closes #18822

### CODE REVIEW

**Review by bartlomieju — APPROVED** [review]
LGTM

File: cli/npm/resolvers/local.rs [hunk 1]
```diff
@@ -365,18 +364,16 @@ async fn sync_resolution_with_fs(
...
-  let mut pending_packages = VecDeque::new();
-  pending_packages.extend(snapshot.top_level_packages().map(|id| (id, true)));
-  while let Some((id, is_top_level)) = pending_packages.pop_front() {
+  let mut ids = snapshot.top_level_packages().collect::<Vec<_>>();
+  ids.sort_by(|a, b| b.cmp(a)); // create determinism and only include the latest version
+  for id in ids {
     let root_folder_name = if found_names.insert(id.nv.name.clone()) {
       id.nv.name.clone()
-    } else if is_top_level {
-      id.nv.to_string()
```
Comment (dsherret) [inline cli/npm/resolvers/local.rs:379]: This was previously useless because it would create this non-deterministically. I don't think there's any use for this so I removed it.
