### PR TITLE
fix(inspect): fix inspecting event classes

### LINKED ISSUE #9880: `Object.defineProperty` on `Event` prototype panics in repl
running `Object.defineProperty(Event.prototype, 0, {})` in repl will panic with `thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', cli/tools/repl.rs:564:49`

### PR DESCRIPTION
**Pull request by dsherret**
Before in REPL:

```
> new Event("")
Event {
  bubbles: false,
  cancelable: false,
  composed: false,
  currentTarget: null,
  defaultPrevented: false,
  eventPhase: 0,
  srcElement: null,
  target: null,
  returnValue: true,
  timeStamp: 1623786515074,
  type: ""
}
> Event.prototype
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', cli\tools\repl.rs:550:49
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

After:

```
exit using ctrl+d or close()
> new Event("")
Event {
  bubbles: false,
  cancelable: false,
  composed: false,
  currentTarget: null,
  defaultPrevented: false,
  eventPhase: 0,
  srcElement: null,
  target: null,
  returnValue: true,
  timeStamp: 1623786578618,
  type: ""
}
> Event.prototype
Event {
  bubbles: [Getter/Setter],
  cancelable: [Getter/Setter],
  composed: [Getter/Setter],
  currentTarget: [Getter/Setter],
  defaultPrevented: [Getter/Setter],
  eventPhase: [Getter/Setter],
  srcElement: [Getter/Setter],
  target: [Getter/Setter],
  returnValue: [Getter/Setter],
  timeStamp: [Getter/Setter],
  type: [Getter/Setter]
}
>
```

Closes #9880

### CODE REVIEW

File: cli/tests/unit/event_test.ts [hunk 1]
```diff
@@ -127,3 +132,30 @@ unitTest(function eventInspectOutput(): void {
     assertEquals(Deno.inspect(event), outputProvider(event));
   }
 });
+
+unitTest(function inspectEvent(): void {
+  // has a customInspect implementation that previously would throw on a getter
+  assertEquals(
+    Deno.inspect(Event.prototype),
+    `Event {
+  bubbles: [Getter/Setter],
```
Comment (dsherret) [inline cli/tests/unit/event_test.ts:141]: I'm not sure why these have empty setters defined... couldn't those be omitted?

Comment (lucacasonato) [reply cli/tests/unit/event_test.ts:141]: Yeah, those should be removed. Some legacy from when we understood how webidl works even less.

Comment (dsherret) [reply cli/tests/unit/event_test.ts]: Done in b2a8f21d848bfd598207bd991546f4a464173beb

Comment (dsherret) [reply cli/tests/unit/event_test.ts]: Nevermind. We need these because it causes an error to not have it when doing `e.target = something`, which doesn't error in chrome. I'm going to revert.

Comment (lucacasonato) [reply cli/tests/unit/event_test.ts:141]: Tested in the Chrome Dev Tools? That is non strict mode. It does error in Chrome too in ES modules or "use strict" scripts. That is how this snuck in in the first place :-)

Comment (dsherret) [reply cli/tests/unit/event_test.ts:141]: Oh, I didn’t think about that! Ok, yeah I’ll look into it on Thursday. There is a tests that assigns to target for some reason.

Comment (dsherret) [reply cli/tests/unit/event_test.ts:141]: @lucacasonato I was thinking about this. Maybe we should do it in a separate PR and minor release? It could possibly break some people's code. Thoughts?

Comment (lucacasonato) [reply cli/tests/unit/event_test.ts:141]: If you want, sure - but its a bug fix so I'd be happy to land it in a patch.

Comment (dsherret) [reply cli/tests/unit/event_test.ts:141]: Ok, lets merge this one and then I'll do a separate specific PR for that change so that it's not hidden under this one's title.

**Review by lucacasonato — APPROVED** [review]
