### PR TITLE
fix(lsp): apply import fix to missing declaration code action

### LINKED ISSUE #23916: LSP: accepting quick fix inserts import from https://jsr.io URL
```ts
import { doc, type FunctionDef } from "jsr:@deno/doc";

function assertFunctionDocs(method: FunctionDef) {
  if (method.returnType !== undefined) {
    assertReturnType(method.returnType);
  }
}

if (false) {
  await doc("123");
}
```

Accepting the quick fix on line 5 (`Add missing function declaration 'assertReturnType'`) adds an import for `TsTypeDef` from a `https://jsr.io/` URL:

```ts
import { TsTypeDef } from "https://jsr.io/@deno/doc/0.134.0/types.js";
import { doc, type FunctionDef } from "jsr:@deno/doc";

function assertFunctionDocs(method: FunctionDef) {
  if (method.returnType !== undefined) {
    assertReturnType(method.returnType);
  }
}

if (false) {
  await doc("123");
}

function assertReturnType(returnType: TsTypeDef) {
  throw new Error("Function not implemented.");
}
```

### PR DESCRIPTION
**Pull request by nayeemrmn**
Fixes #23916.

### CODE REVIEW

**Review by dsherret — APPROVED** [review]
LGTM :(

File: cli/jsr.rs [hunk 1]
```diff
@@ -111,12 +111,32 @@ impl JsrCacheResolver {
...
+          .or_else(|| path.strip_suffix(".cjs"))
+          .unwrap_or(path);
+        let path_ = path_
+          .strip_suffix(".d.ts")
+          .or_else(|| path_.strip_suffix(".d.mts"))
+          .or_else(|| path_.strip_suffix(".d.cts"))
+          .unwrap_or(path_);
+        if path_ == path {
+          sloppy_fallback =
+            Some(export.strip_prefix("./").unwrap_or(export).to_string());
```
Comment (nathanwhit) [inline cli/jsr.rs:135]: Could we just return here?
