### PR TITLE
fix: lockfile was sometimes getting corrupt when changing config deps

### LINKED ISSUE #22250: Lockfile becomes corrupt removing tailwind from deno.json in a new fresh template project
Given the following deno.json:

<details>

<summary>deno.json</summary>

```json
{
  "tasks": {
    "check": "deno fmt --check && deno lint && deno check **/*.ts && deno check **/*.tsx",
    "cli": "echo \"import '\\$fresh/src/dev/cli.ts'\" | deno run --unstable -A -",
    "manifest": "deno task cli manifest $(pwd)",
    "start": "deno run -A --watch=static/,routes/ dev.ts",
    "build": "deno run -A dev.ts build",
    "preview": "deno run -A main.ts",
    "update": "deno run -A -r https://fresh.deno.dev/update ."
  },
  "lint": {
    "rules": {
      "tags": [
        "fresh",
        "recommended"
      ]
    }
  },
  "exclude": [
    "**/_fresh/*"
  ],
  "imports": {
    "$fresh/": "https://deno.land/x/fresh@1.6.3/",
    "preact": "https://esm.sh/preact@10.19.2",
    "preact/": "https://esm.sh/preact@10.19.2/",
    "@preact/signals": "https://esm.sh/*@preact/signals@1.2.1",
    "@preact/signals-core": "https://esm.sh/*@preact/signals-core@1.5.0",
    "spotify": "npm:@spotify/web-api-ts-sdk",
    "tailwindcss": "npm:tailwindcss@3.3.5",
    "tailwindcss/": "npm:/tailwindcss@3.3.5/",
    "tailwindcss/plugin": "npm:/tailwindcss@3.3.5/plugin.js",
    "$std/": "https://deno.land/std@0.211.0/"
  },
  "compilerOptions": {
    "jsx": "react-jsx",
    "jsxImportSource": "preact"
  },
  "nodeModulesDir": true
}
```
</details>

And deno.lock file (I omitted the remote section because my GH comment was too long):

<details>
<summary>deno.lock</summary>
```
{
  "version": "3",
  "packages": {
    "specifiers": {
      "npm:@spotify/web-api-ts-sdk": "npm:@spotify/web-api-ts-sdk@1.2.0",
      "npm:autoprefixer@10.4.16": "npm:autoprefixer@10.4.16_postcss@8.4.31",
      "npm:cssnano@6.0.1": "npm:cssnano@6.0.1_postcss@8.4.31",
      "npm:postcss@8.4.31": "npm:postcss@8.4.31",
      "npm:tailwindcss@3.3.5": "npm:tailwindcss@3.3.5_postcss@8.4.31"
    },
    "npm": {
      "@alloc/quick-lru@5.2.0": {
        "integrity": "sha512-UrcABB+4bUrFABwbluTIBErXwvbsU/V7TZWfmbgJfbkwiBuziS9gxdODUyuiecfdGQ85jglMW6juS3+z5TsKLw==",
        "dependencies": {}
      },
      "@jridgewell/gen-mapping@0.3.3": {
        "integrity": "sha512-HLhSWOLRi875zjjMG/r+Nv0oCW8umGb0BgEhyX3dDX3egwZtB8PqLnjz3yedt8R5StBrzcg4aBpnh8UA9D1BoQ==",
        "dependencies": {
          "@jridgewell/set-array": "@jridgewell/set-array@1.1.2",
          "@jridgewell/sourcemap-codec": "@jridgewell/sourcemap-codec@1.4.15",
          "@jridgewell/trace-mapping": "@jridgewell/trace-mapping@0.3.20"
        }
      },
      "@jridgewell/resolve-uri@3.1.1": {
        "integrity": "sha512-dSYZh7HhCDtCKm4QakX0xFpsRDqjjtZf/kjI/v3T3Nwt5r8/qz/M19F9ySyOqU94SXBmeG9ttTul+YnR4LOxFA==",
        "dependencies": {}
      },
      "@jridgewell/set-array@1.1.2": {
        "integrity": "sha512-xnkseuNADM0gt2bs+BvhO0p78Mk762YnZdsuzFV018NoG1Sj1SCQvpSqa7XUaTam5vAGasABV9qXASMKnFMwMw==",
        "dependencies": {}
      },
      "@jridgewell/sourcemap-codec@1.4.15": {
        "integrity": "sha512-eF2rxCRulEKXHTRiDrDy6erMYWqNw4LPdQ8UQA4huuxaQsVeRPFl2oM8oDGxMFhJUWZf9McpLtJasDDZb/Bpeg==",
        "dependencies": {}
      },
      "@jridgewell/trace-mapping@0.3.20": {
        "integrity": "sha512-R8LcPeWZol2zR8mmH3JeKQ6QRCFb7XgUhV9ZlGhHLGyg4wpPiPZNQOOWhFZhxKw8u//yTbNGI42Bx/3paXEQ+Q==",
        "dependencies": {
          "@jridgewell/resolve-uri": "@jridgewell/resolve-uri@3.1.1",
          "@jridgewell/sourcemap-codec": "@jridgewell/sourcemap-codec@1.4.15"
        }
      },
      "@nodelib/fs.scandir@2.1.5": {
        "integrity": "sha512-vq24Bq3ym5HEQm2NKCr3yXDwjc7vTsEThRDnkp2DK9p1uqLR+DHurm/NOTo0KG7HYHU7eppKZj3MyqYuMBf62g==",
        "dependencies": {
          "@nodelib/fs.stat": "@nodelib/fs.stat@2.0.5",
          "run-parallel": "run-parallel@1.2.0"
        }
      },
      "@nodelib/fs.stat@2.0.5": {
        "integrity": "sha512-RkhPPp2zrqDAQA/2jNhnztcPAlv64XdhIp7a7454A5ovI7Bukxgt7MX7udwAu3zg1DcpPU0rz3VV1SeaqvY4+A==",
        "dependencies": {}
      },
      "@nodelib/fs.walk@1.2.8": {
        "integrity": "sha512-oGB+UxlgWcgQkgwo8GcEGwemoTFt3FIO9ababBmaGwXIoBKZ+GTy0pP185beGg7Llih/NSHSV2XAs1lnznocSg==",
        "dependencies": {
          "@nodelib/fs.scandir": "@nodelib/fs.scandir@2.1.5",
          "fastq": "fastq@1.16.0"
        }
      },
      "@spotify/web-api-ts-sdk@1.2.0": {
        "integrity": "sha512-JUaebva3Ohwo5I5tuTqyW/FKGOMbb40YevJMySAOINRxP7qQ/AMjBzfJx0zeO6yS+wAPfQSoGNsZaUggHw8vsA==",
        "dependencies": {}
      },
      "@trysound/sax@0.2.0": {
        "integrity": "sha512-L7z9BgrNEcYyUYtF+HaEfiS5ebkh9jXqbszz7pC0hRBPaatV0XjSD3+eHrpqFemQfgwiFF0QPIarnIihIDn7OA==",
        "dependencies": {}
      },
      "any-promise@1.3.0": {
        "integrity": "sha512-7UvmKalWRt1wgjL1RrGxoSJW/0QZFIegpeGvZG9kjp8vrRu55XTHbwnqq2GpXm9uLbcuhxm3IqX9OB4MZR1b2A==",
        "dependencies": {}
      },
      "anymatch@3.1.3": {
        "integrity": "sha512-KMReFUr0B4t+D+OBkjR3KYqvocp2XaSzO55UcB6mgQMd3KbcE+mWTyvVV7D/zsdEbNnV6acZUutkiHQXvTr1Rw==",
        "dependencies": {
          "normalize-path": "normalize-path@3.0.0",
          "picomatch": "picomatch@2.3.1"
        }
      },
      "arg@5.0.2": {
        "integrity": "sha512-PYjyFOLKQ9y57JvQ6QLo8dAgNqswh8M1RMJYdQduT6xbWSgK36P/Z/v+p888pM69jMMfS8Xd8F6I1kQ/I9HUGg==",
        "dependencies": {}
      },
      "autoprefixer@10.4.16_postcss@8.4.31": {
        "integrity": "sha512-7vd3UC6xKp0HLfua5IjZlcXvGAGy7cBAXTg2lyQ/8WpNhd6SiZ8Be+xm3FyBSYJx5GKcpRCzBh7RH4/0dnY+uQ==",
        "dependencies": {
          "browserslist": "browserslist@4.22.1",
          "caniuse-lite": "caniuse-lite@1.0.30001565",
          "fraction.js": "fraction.js@4.3.7",
          "normalize-range": "normalize-range@0.1.2",
          "picocolors": "picocolors@1.0.0",
          "postcss": "postcss@8.4.31",
          "postcss-value-parser": "postcss-value-parser@4.2.0"
        }
      },
      "balanced-match@1.0.2": {
        "integrity": "sha512-3oSeUO0TMV67hN1AmbXsK4yaqU7tjiHlbxRDZOpH0KW9+CeX4bRAaX0Anxt0tx2MrpRpWwQaPwIlISEJhYU5Pw==",
        "dependencies": {}
      },
      "binary-extensions@2.2.0": {
        "integrity": "sha512-jDctJ/IVQbZoJykoeHbhXpOlNBqGNcwXJKJog42E5HDPUwQTSdjCHdihjj0DlnheQ7blbT6dHOafNAiS8ooQKA==",
        "dependencies": {}
      },
      "boolbase@1.0.0": {
        "integrity": "sha512-JZOSA7Mo9sNGB8+UjSgzdLtokWAky1zbztM3WRLCbZ70/3cTANmQmOdR7y2g+J0e2WXywy1yS468tY+IruqEww==",
        "dependencies": {}
      },
      "brace-expansion@1.1.11": {
        "integrity": "sha512-iCuPHDFgrHX7H2vEI/5xpz07zSHB00TpugqhmYtVmMO6518mCuRMoOYFldEBl0g187ufozdaHgWKcYFb61qGiA==",
        "dependencies": {
          "balanced-match": "balanced-match@1.0.2",
          "concat-map": "concat-map@0.0.1"
        }
      },
      "braces@3.0.2": {
        "integrity": "sha512-b8um+L1RzM3WDSzvhm6gIz1yfTbBt6YTlcEKAvsmqCZZFw46z626lVj9j1yEPW33H5H+lBQpZMP1k8l+78Ha0A==",
        "dependencies": {
          "fill-range": "fill-range@7.0.1"
        }
      },
      "browserslist@4.22.1": {
        "integrity": "sha512-FEVc202+2iuClEhZhrWy6ZiAcRLvNMyYcxZ8raemul1DYVOVdFsbqckWLdsixQZCpJlwe77Z3UTalE7jsjnKfQ==",
        "dependencies": {
          "caniuse-lite": "caniuse-lite@1.0.30001565",
          "electron-to-chromium": "electron-to-chromium@1.4.577",
          "node-releases": "node-releases@2.0.13",
          "update-browserslist-db": "update-browserslist-db@1.0.13_browserslist@4.22.1"
        }
      },
      "camelcase-css@2.0.1": {
        "integrity": "sha512-QOSvevhslijgYwRx6Rv7zKdMF8lbRmx+uQGx2+vDc+KI/eBnsy9kit5aj23AgGu3pa4t9AgwbnXWqS+iOY+2aA==",
        "dependencies": {}
      },
      "caniuse-api@3.0.0": {
        "integrity": "sha512-bsTwuIg/BZZK/vreVTYYbSWoe2F+71P7K5QGEX+pT250DZbfU1MQ5prOKpPR+LL6uWKK3KMwMCAS74QB3Um1uw==",
        "dependencies": {
          "browserslist": "browserslist@4.22.1",
          "caniuse-lite": "caniuse-lite@1.0.30001565",
          "lodash.memoize": "lodash.memoize@4.1.2",
          "lodash.uniq": "lodash.uniq@4.5.0"
        }
      },
      "caniuse-lite@1.0.30001565": {
        "integrity": "sha512-xrE//a3O7TP0vaJ8ikzkD2c2NgcVUvsEe2IvFTntV4Yd1Z9FVzh+gW+enX96L0psrbaFMcVcH2l90xNuGDWc8w==",
        "dependencies": {}
      },
      "chokidar@3.5.3": {
        "integrity": "sha512-Dr3sfKRP6oTcjf2JmUmFJfeVMvXBdegxB0iVQ5eb2V10uFJUCAS8OByZdVAyVb8xXNz3GjjTgj9kLWsZTqE6kw==",
        "dependencies": {
          "anymatch": "anymatch@3.1.3",
          "braces": "braces@3.0.2",
          "fsevents": "fsevents@2.3.3",
          "glob-parent": "glob-parent@5.1.2",
          "is-binary-path": "is-binary-path@2.1.0",
          "is-glob": "is-glob@4.0.3",
          "normalize-path": "normalize-path@3.0.0",
          "readdirp": "readdirp@3.6.0"
        }
      },
      "colord@2.9.3": {
        "integrity": "sha512-jeC1axXpnb0/2nn/Y1LPuLdgXBLH7aDcHu4KEKfqw3CUhX7ZpfBSlPKyqXE6btIgEzfWtrX3/tyBCaCvXvMkOw==",
        "dependencies": {}
      },
      "commander@4.1.1": {
        "integrity": "sha512-NOKm8xhkzAjzFx8B2v5OAHT+u5pRQc2UCa2Vq9jYL/31o2wi9mxBA7LIFs3sV5VSC49z6pEhfbMULvShKj26WA==",
        "dependencies": {}
      },
      "commander@7.2.0": {
        "integrity": "sha512-QrWXB+ZQSVPmIWIhtEO9H+gwHaMGYiF5ChvoJ+K9ZGHG/sVsa6yiesAD1GC/x46sET00Xlwo1u49RVVVzvcSkw==",
        "dependencies": {}
      },
      "concat-map@0.0.1": {
        "integrity": "sha512-/Srv4dswyQNBfohGpz9o6Yb3Gz3SrUDqBH5rTuhGR7ahtlbYKnVxw2bCFMRljaA7EXHaXZ8wsHdodFvbkhKmqg==",
        "dependencies": {}
      },
      "css-declaration-sorter@6.4.1_postcss@8.4.31": {
        "integrity": "sha512-rtdthzxKuyq6IzqX6jEcIzQF/YqccluefyCYheovBOLhFT/drQA9zj/UbRAa9J7C0o6EG6u3E6g+vKkay7/k3g==",
        "dependencies": {
          "postcss": "postcss@8.4.31"
        }
      },
      "css-select@5.1.0": {
        "integrity": "sha512-nwoRF1rvRRnnCqqY7updORDsuqKzqYJ28+oSMaJMMgOauh3fvwHqMS7EZpIPqK8GL+g9mKxF1vP/ZjSeNjEVHg==",
        "dependencies": {
          "boolbase": "boolbase@1.0.0",
          "css-what": "css-what@6.1.0",
          "domhandler": "domhandler@5.0.3",
          "domutils": "domutils@3.1.0",
          "nth-check": "nth-check@2.1.1"
        }
      },
      "css-tree@2.2.1": {
        "integrity": "sha512-OA0mILzGc1kCOCSJerOeqDxDQ4HOh+G8NbOJFOTgOCzpw7fCBubk0fEyxp8AgOL/jvLgYA/uV0cMbe43ElF1JA==",
        "dependencies": {
          "mdn-data": "mdn-data@2.0.28",
          "source-map-js": "source-map-js@1.0.2"
        }
      },
      "css-tree@2.3.1": {
        "integrity": "sha512-6Fv1DV/TYw//QF5IzQdqsNDjx/wc8TrMBZsqjL9eW01tWb7R7k/mq+/VXfJCl7SoD5emsJop9cOByJZfs8hYIw==",
        "dependencies": {
          "mdn-data": "mdn-data@2.0.30",
          "source-map-js": "source-map-js@1.0.2"
        }
      },
      "css-what@6.1.0": {
        "integrity": "sha512-HTUrgRJ7r4dsZKU6GjmpfRK1O76h97Z8MfS1G0FozR+oF2kG6Vfe8JE6zwrkbxigziPHinCJ+gCPjA9EaBDtRw==",
        "dependencies": {}
      },
      "cssesc@3.0.0": {
        "integrity": "sha512-/Tb/JcjK111nNScGob5MNtsntNM1aCNUDipB/TkwZFhyDrrE47SOx/18wF2bbjgc3ZzCSKW1T5nt5EbFoAz/Vg==",
        "dependencies": {}
      },
      "cssnano-preset-default@6.0.1_postcss@8.4.31": {
        "integrity": "sha512-7VzyFZ5zEB1+l1nToKyrRkuaJIx0zi/1npjvZfbBwbtNTzhLtlvYraK/7/uqmX2Wb2aQtd983uuGw79jAjLSuQ==",
        "dependencies": {
          "css-declaration-sorter": "css-declaration-sorter@6.4.1_postcss@8.4.31",
          "cssnano-utils": "cssnano-utils@4.0.0_postcss@8.4.31",
          "postcss": "postcss@8.4.31",
          "postcss-calc": "postcss-calc@9.0.1_postcss@8.4.31",
          "postcss-colormin": "postcss-colormin@6.0.0_postcss@8.4.31",
          "postcss-convert-values": "postcss-convert-values@6.0.0_postcss@8.4.31",
          "postcss-discard-comments": "postcss-discard-comments@6.0.0_postcss@8.4.31",
          "postcss-discard-duplicates": "postcss-discard-duplicates@6.0.0_postcss@8.4.31",
          "postcss-discard-empty": "postcss-discard-empty@6.0.0_postcss@8.4.31",
          "postcss-discard-overridden": "postcss-discard-overridden@6.0.0_postcss@8.4.31",
          "postcss-merge-longhand": "postcss-merge-longhand@6.0.0_postcss@8.4.31",
          "postcss-merge-rules": "postcss-merge-rules@6.0.1_postcss@8.4.31",
          "postcss-minify-font-values": "postcss-minify-font-values@6.0.0_postcss@8.4.31",
          "postcss-minify-gradients": "postcss-minify-gradients@6.0.0_postcss@8.4.31",
          "postcss-minify-params": "postcss-minify-params@6.0.0_postcss@8.4.31",
          "postcss-minify-selectors": "postcss-minify-selectors@6.0.0_postcss@8.4.31",
          "postcss-normalize-charset": "postcss-normalize-charset@6.0.0_postcss@8.4.31",
          "postcss-normalize-display-values": "postcss-normalize-display-values@6.0.0_postcss@8.4.31",
          "postcss-normalize-positions": "postcss-normalize-positions@6.0.0_postcss@8.4.31",
          "postcss-normalize-repeat-style": "postcss-normalize-repeat-style@6.0.0_postcss@8.4.31",
          "postcss-normalize-string": "postcss-normalize-string@6.0.0_postcss@8.4.31",
          "postcss-normalize-timing-functions": "postcss-normalize-timing-functions@6.0.0_postcss@8.4.31",
          "postcss-normalize-unicode": "postcss-normalize-unicode@6.0.0_postcss@8.4.31",
          "postcss-normalize-url": "postcss-normalize-url@6.0.0_postcss@8.4.31",
          "postcss-normalize-whitespace": "postcss-normalize-whitespace@6.0.0_postcss@8.4.31",
          "postcss-ordered-values": "postcss-ordered-values@6.0.0_postcss@8.4.31",
          "postcss-reduce-initial": "postcss-reduce-initial@6.0.0_postcss@8.4.31",
          "postcss-reduce-transforms": "postcss-reduce-transforms@6.0.0_postcss@8.4.31",
          "postcss-svgo": "postcss-svgo@6.0.0_postcss@8.4.31",
          "postcss-unique-selectors": "postcss-unique-selectors@6.0.0_postcss@8.4.31"
        }
      },
      "cssnano-utils@4.0.0_postcss@8.4.31": {
        "integrity": "sha512-Z39TLP+1E0KUcd7LGyF4qMfu8ZufI0rDzhdyAMsa/8UyNUU8wpS0fhdBxbQbv32r64ea00h4878gommRVg2BHw==",
        "dependencies": {
          "postcss": "postcss@8.4.31"
        }
      },
      "cssnano@6.0.1_postcss@8.4.31": {
        "integrity": "sha512-fVO1JdJ0LSdIGJq68eIxOqFpIJrZqXUsBt8fkrBcztCQqAjQD51OhZp7tc0ImcbwXD4k7ny84QTV90nZhmqbkg==",
        "dependencies": {
          "cssnano-preset-default": "cssnano-preset-default@6.0.1_postcss@8.4.31",
          "lilconfig": "lilconfig@2.1.0",
          "postcss": "postcss@8.4.31"
        }
      },
      "csso@5.0.5": {
        "integrity": "sha512-0LrrStPOdJj+SPCCrGhzryycLjwcgUSHBtxNA8aIDxf0GLsRh1cKYhB00Gd1lDOS4yGH69+SNn13+TWbVHETFQ==",
        "dependencies": {
          "css-tree": "css-tree@2.2.1"
        }
      },
      "didyoumean@1.2.2": {
        "integrity": "sha512-gxtyfqMg7GKyhQmb056K7M3xszy/myH8w+B4RT+QXBQsvAOdc3XymqDDPHx1BgPgsdAA5SIifona89YtRATDzw==",
        "dependencies": {}
      },
      "dlv@1.1.3": {
        "integrity": "sha512-+HlytyjlPKnIG8XuRG8WvmBP8xs8P71y+SKKS6ZXWoEgLuePxtDoUEiH7WkdePWrQ5JBpE6aoVqfZfJUQkjXwA==",
        "dependencies": {}
      },
      "dom-serializer@2.0.0": {
        "integrity": "sha512-wIkAryiqt/nV5EQKqQpo3SToSOV9J0DnbJqwK7Wv/Trc92zIAYZ4FlMu+JPFW1DfGFt81ZTCGgDEabffXeLyJg==",
        "dependencies": {
          "domelementtype": "domelementtype@2.3.0",
          "domhandler": "domhandler@5.0.3",
          "entities": "entities@4.5.0"
        }
      },
      "domelementtype@2.3.0": {
        "integrity": "sha512-OLETBj6w0OsagBwdXnPdN0cnMfF9opN69co+7ZrbfPGrdpPVNBUj02spi6B1N7wChLQiPn4CSH/zJvXw56gmHw==",
        "dependencies": {}
      },
      "domhandler@5.0.3": {
        "integrity": "sha512-cgwlv/1iFQiFnU96XXgROh8xTeetsnJiDsTc7TYCLFd9+/WNkIqPTxiM/8pSd8VIrhXGTf1Ny1q1hquVqDJB5w==",
        "dependencies": {
          "domelementtype": "domelementtype@2.3.0"
        }
      },
      "domutils@3.1.0": {
        "integrity": "sha512-H78uMmQtI2AhgDJjWeQmHwJJ2bLPD3GMmO7Zja/ZZh84wkm+4ut+IUnUdRa8uCGX88DiVx1j6FRe1XfxEgjEZA==",
        "dependencies": {
          "dom-serializer": "dom-serializer@2.0.0",
          "domelementtype": "domelementtype@2.3.0",
          "domhandler": "domhandler@5.0.3"
        }
      },
      "electron-to-chromium@1.4.577": {
        "integrity": "sha512-/5xHPH6f00SxhHw6052r+5S1xO7gHNc89hV7tqlvnStvKbSrDqc/u6AlwPvVWWNj+s4/KL6T6y8ih+nOY0qYNA==",
        "dependencies": {}
      },
      "entities@4.5.0": {
        "integrity": "sha512-V0hjH4dGPh9Ao5p0MoRY6BVqtwCjhz6vI5LT8AJ55H+4g9/4vbHx1I54fS0XuclLhDHArPQCiMjDxjaL8fPxhw==",
        "dependencies": {}
      },
      "escalade@3.1.1": {
        "integrity": "sha512-k0er2gUkLf8O0zKJiAhmkTnJlTvINGv7ygDNPbeIsX/TJjGJZHuh9B2UxbsaEkmlEo9MfhrSzmhIlhRlI2GXnw==",
        "dependencies": {}
      },
      "fast-glob@3.3.2": {
        "integrity": "sha512-oX2ruAFQwf/Orj8m737Y5adxDQO0LAB7/S5MnxCdTNDd4p6BsyIVsv9JQsATbTSq8KHRpLwIHbVlUNatxd+1Ow==",
        "dependencies": {
          "@nodelib/fs.stat": "@nodelib/fs.stat@2.0.5",
          "@nodelib/fs.walk": "@nodelib/fs.walk@1.2.8",
          "glob-parent": "glob-parent@5.1.2",
          "merge2": "merge2@1.4.1",
          "micromatch": "micromatch@4.0.5"
        }
      },
      "fastq@1.16.0": {
        "integrity": "sha512-ifCoaXsDrsdkWTtiNJX5uzHDsrck5TzfKKDcuFFTIrrc/BS076qgEIfoIy1VeZqViznfKiysPYTh/QeHtnIsYA==",
        "dependencies": {
          "reusify": "reusify@1.0.4"
        }
      },
      "fill-range@7.0.1": {
        "integrity": "sha512-qOo9F+dMUmC2Lcb4BbVvnKJxTPjCm+RRpe4gDuGrzkL7mEVl/djYSu2OdQ2Pa302N4oqkSg9ir6jaLWJ2USVpQ==",
        "dependencies": {
          "to-regex-range": "to-regex-range@5.0.1"
        }
      },
      "fraction.js@4.3.7": {
        "integrity": "sha512-ZsDfxO51wGAXREY55a7la9LScWpwv9RxIrYABrlvOFBlH/ShPnrtsXeuUIfXKKOVicNxQ+o8JTbJvjS4M89yew==",
        "dependencies": {}
      },
      "fs.realpath@1.0.0": {
        "integrity": "sha512-OO0pH2lK6a0hZnAdau5ItzHPI6pUlvI7jMVnxUQRtw4owF2wk8lOSabtGDCTP4Ggrg2MbGnWO9X8K1t4+fGMDw==",
        "dependencies": {}
      },
      "fsevents@2.3.3": {
        "integrity": "sha512-5xoDfX+fL7faATnagmWPpbFtwh/R77WmMMqqHGS65C3vvB0YHrgF+B1YmZ3441tMj5n63k0212XNoJwzlhffQw==",
        "dependencies": {}
      },
      "function-bind@1.1.2": {
        "integrity": "sha512-7XHNxH7qX9xG5mIwxkhumTox/MIRNcOgDrxWsMt2pAr23WHp6MrRlN7FBSFpCpr+oVO0F744iUgR82nJMfG2SA==",
        "dependencies": {}
      },
      "glob-parent@5.1.2": {
        "integrity": "sha512-AOIgSQCepiJYwP3ARnGx+5VnTu2HBYdzbGP45eLw1vr3zB3vZLeyed1sC9hnbcOc9/SrMyM5RPQrkGz4aS9Zow==",
        "dependencies": {
          "is-glob": "is-glob@4.0.3"
        }
      },
      "glob-parent@6.0.2": {
        "integrity": "sha512-XxwI8EOhVQgWp6iDL+3b0r86f4d6AX6zSU55HfB4ydCEuXLXc5FcYeOu+nnGftS4TEju/11rt4KJPTMgbfmv4A==",
        "dependencies": {
          "is-glob": "is-glob@4.0.3"
        }
      },
      "glob@7.1.6": {
        "integrity": "sha512-LwaxwyZ72Lk7vZINtNNrywX0ZuLyStrdDtabefZKAY5ZGJhVtgdznluResxNmPitE0SAO+O26sWTHeKSI2wMBA==",
        "dependencies": {
          "fs.realpath": "fs.realpath@1.0.0",
          "inflight": "inflight@1.0.6",
          "inherits": "inherits@2.0.4",
          "minimatch": "minimatch@3.1.2",
          "once": "once@1.4.0",
          "path-is-absolute": "path-is-absolute@1.0.1"
        }
      },
      "hasown@2.0.0": {
        "integrity": "sha512-vUptKVTpIJhcczKBbgnS+RtcuYMB8+oNzPK2/Hp3hanz8JmpATdmmgLgSaadVREkDm+e2giHwY3ZRkyjSIDDFA==",
        "dependencies": {
          "function-bind": "function-bind@1.1.2"
        }
      },
      "inflight@1.0.6": {
        "integrity": "sha512-k92I/b08q4wvFscXCLvqfsHCrjrF7yiXsQuIVvVE7N82W3+aqpzuUdBbfhWcy/FZR3/4IgflMgKLOsvPDrGCJA==",
        "dependencies": {
          "once": "once@1.4.0",
          "wrappy": "wrappy@1.0.2"
        }
      },
      "inherits@2.0.4": {
        "integrity": "sha512-k/vGaX4/Yla3WzyMCvTQOXYeIHvqOKtnqBduzTHpzpQZzAskKMhZ2K+EnBiSM9zGSoIFeMpXKxa4dYeZIQqewQ==",
        "dependencies": {}
      },
      "is-binary-path@2.1.0": {
        "integrity": "sha512-ZMERYes6pDydyuGidse7OsHxtbI7WVeUEozgR/g7rd0xUimYNlvZRE/K2MgZTjWy725IfelLeVcEM97mmtRGXw==",
        "dependencies": {
          "binary-extensions": "binary-extensions@2.2.0"
        }
      },
      "is-core-module@2.13.1": {
        "integrity": "sha512-hHrIjvZsftOsvKSn2TRYl63zvxsgE0K+0mYMoH6gD4omR5IWB2KynivBQczo3+wF1cCkjzvptnI9Q0sPU66ilw==",
        "dependencies": {
          "hasown": "hasown@2.0.0"
        }
      },
      "is-extglob@2.1.1": {
        "integrity": "sha512-SbKbANkN603Vi4jEZv49LeVJMn4yGwsbzZworEoyEiutsN3nJYdbO36zfhGJ6QEDpOZIFkDtnq5JRxmvl3jsoQ==",
        "dependencies": {}
      },
      "is-glob@4.0.3": {
        "integrity": "sha512-xelSayHH36ZgE7ZWhli7pW34hNbNl8Ojv5KVmkJD4hBdD3th8Tfk9vYasLM+mXWOZhFkgZfxhLSnrwRr4elSSg==",
        "dependencies": {
          "is-extglob": "is-extglob@2.1.1"
        }
      },
      "is-number@7.0.0": {
        "integrity": "sha512-41Cifkg6e8TylSpdtTpeLVMqvSBEVzTttHvERD741+pnZ8ANv0004MRL43QKPDlK9cGvNp6NZWZUBlbGXYxxng==",
        "dependencies": {}
      },
      "jiti@1.21.0": {
        "integrity": "sha512-gFqAIbuKyyso/3G2qhiO2OM6shY6EPP/R0+mkDbyspxKazh8BXDC5FiFsUjlczgdNz/vfra0da2y+aHrusLG/Q==",
        "dependencies": {}
      },
      "lilconfig@2.1.0": {
        "integrity": "sha512-utWOt/GHzuUxnLKxB6dk81RoOeoNeHgbrXiuGk4yyF5qlRz+iIVWu56E2fqGHFrXz0QNUhLB/8nKqvRH66JKGQ==",
        "dependencies": {}
      },
      "lines-and-columns@1.2.4": {
        "integrity": "sha512-7ylylesZQ/PV29jhEDl3Ufjo6ZX7gCqJr5F7PKrqc93v7fzSymt1BpwEU8nAUXs8qzzvqhbjhK5QZg6Mt/HkBg==",
        "dependencies": {}
      },
      "lodash.memoize@4.1.2": {
        "integrity": "sha512-t7j+NzmgnQzTAYXcsHYLgimltOV1MXHtlOWf6GjL9Kj8GK5FInw5JotxvbOs+IvV1/Dzo04/fCGfLVs7aXb4Ag==",
        "dependencies": {}
      },
      "lodash.uniq@4.5.0": {
        "integrity": "sha512-xfBaXQd9ryd9dlSDvnvI0lvxfLJlYAZzXomUYzLKtUeOQvOP5piqAWuGtrhWeqaXK9hhoM/iyJc5AV+XfsX3HQ==",
        "dependencies": {}
      },
      "mdn-data@2.0.28": {
        "integrity": "sha512-aylIc7Z9y4yzHYAJNuESG3hfhC+0Ibp/MAMiaOZgNv4pmEdFyfZhhhny4MNiAfWdBQ1RQ2mfDWmM1x8SvGyp8g==",
        "dependencies": {}
      },
      "mdn-data@2.0.30": {
        "integrity": "sha512-GaqWWShW4kv/G9IEucWScBx9G1/vsFZZJUO+tD26M8J8z3Kw5RDQjaoZe03YAClgeS/SWPOcb4nkFBTEi5DUEA==",
        "dependencies": {}
      },
      "merge2@1.4.1": {
        "integrity": "sha512-8q7VEgMJW4J8tcfVPy8g09NcQwZdbwFEqhe/WZkoIzjn/3TGDwtOCYtXGxA3O8tPzpczCCDgv+P2P5y00ZJOOg==",
        "dependencies": {}
      },
      "micromatch@4.0.5": {
        "integrity": "sha512-DMy+ERcEW2q8Z2Po+WNXuw3c5YaUSFjAO5GsJqfEl7UjvtIuFKO6ZrKvcItdy98dwFI2N1tg3zNIdKaQT+aNdA==",
        "dependencies": {
          "braces": "braces@3.0.2",
          "picomatch": "picomatch@2.3.1"
        }
      },
      "minimatch@3.1.2": {
        "integrity": "sha512-J7p63hRiAjw1NDEww1W7i37+ByIrOWO5XQQAzZ3VOcL0PNybwpfmV/N05zFAzwQ9USyEcX6t3UO+K5aqBQOIHw==",
        "dependencies": {
          "brace-expansion": "brace-expansion@1.1.11"
        }
      },
      "mz@2.7.0": {
        "integrity": "sha512-z81GNO7nnYMEhrGh9LeymoE4+Yr0Wn5McHIZMK5cfQCl+NDX08sCZgUc9/6MHni9IWuFLm1Z3HTCXu2z9fN62Q==",
        "dependencies": {
          "any-promise": "any-promise@1.3.0",
          "object-assign": "object-assign@4.1.1",
          "thenify-all": "thenify-all@1.6.0"
        }
      },
      "nanoid@3.3.7": {
        "integrity": "sha512-eSRppjcPIatRIMC1U6UngP8XFcz8MQWGQdt1MTBQ7NaAmvXDfvNxbvWV3x2y6CdEUciCSsDHDQZbhYaB8QEo2g==",
        "dependencies": {}
      },
      "node-releases@2.0.13": {
        "integrity": "sha512-uYr7J37ae/ORWdZeQ1xxMJe3NtdmqMC/JZK+geofDrkLUApKRHPd18/TxtBOJ4A0/+uUIliorNrfYV6s1b02eQ==",
        "dependencies": {}
      },
      "normalize-path@3.0.0": {
        "integrity": "sha512-6eZs5Ls3WtCisHWp9S2GUy8dqkpGi4BVSz3GaqiE6ezub0512ESztXUwUB6C6IKbQkY2Pnb/mD4WYojCRwcwLA==",
        "dependencies": {}
      },
      "normalize-range@0.1.2": {
        "integrity": "sha512-bdok/XvKII3nUpklnV6P2hxtMNrCboOjAcyBuQnWEhO665FwrSNRxU+AqpsyvO6LgGYPspN+lu5CLtw4jPRKNA==",
        "dependencies": {}
      },
      "nth-check@2.1.1": {
        "integrity": "sha512-lqjrjmaOoAnWfMmBPL+XNnynZh2+swxiX3WUE0s4yEHI6m+AwrK2UZOimIRl3X/4QctVqS8AiZjFqyOGrMXb/w==",
        "dependencies": {
          "boolbase": "boolbase@1.0.0"
        }
      },
      "object-assign@4.1.1": {
        "integrity": "sha512-rJgTQnkUnH1sFw8yT6VSU3zD3sWmu6sZhIseY8VX+GRu3P6F7Fu+JNDoXfklElbLJSnc3FUQHVe4cU5hj+BcUg==",
        "dependencies": {}
      },
      "object-hash@3.0.0": {
        "integrity": "sha512-RSn9F68PjH9HqtltsSnqYC1XXoWe9Bju5+213R98cNGttag9q9yAOTzdbsqvIa7aNm5WffBZFpWYr2aWrklWAw==",
        "dependencies": {}
      },
      "once@1.4.0": {
        "integrity": "sha512-lNaJgI+2Q5URQBkccEKHTQOPaXdUxnZZElQTZY0MFUAuaEqe1E+Nyvgdz/aIyNi6Z9MzO5dv1H8n58/GELp3+w==",
        "dependencies": {
          "wrappy": "wrappy@1.0.2"
        }
      },
      "path-is-absolute@1.0.1": {
        "integrity": "sha512-AVbw3UJ2e9bq64vSaS9Am0fje1Pa8pbGqTTsmXfaIiMpnr5DlDhfJOuLj9Sf95ZPVDAUerDfEk88MPmPe7UCQg==",
        "dependencies": {}
      },
      "path-parse@1.0.7": {
        "integrity": "sha512-LDJzPVEEEPR+y48z93A0Ed0yXb8pAByGWo/k5YYdYgpY2/2EsOsksJrq7lOHxryrVOn1ejG6oAp8ahvOIQD8sw==",
        "dependencies": {}
      },
      "picocolors@1.0.0": {
        "integrity": "sha512-1fygroTLlHu66zi26VoTDv8yRgm0Fccecssto+MhsZ0D/DGW2sm8E8AjW7NU5VVTRt5GxbeZ5qBuJr+HyLYkjQ==",
        "dependencies": {}
      },
      "picomatch@2.3.1": {
        "integrity": "sha512-JU3teHTNjmE2VCGFzuY8EXzCDVwEqB2a8fsIvwaStHhAWJEeVd1o1QD80CU6+ZdEXXSLbSsuLwJjkCBWqRQUVA==",
        "dependencies": {}
      },
      "pify@2.3.0": {
        "integrity": "sha512-udgsAY+fTnvv7kI7aaxbqwWNb0AHiB0qBO89PZKPkoTmGOgdbrHDKD+0B2X4uTfJ/FT1R09r9gTsjUjNJotuog==",
        "dependencies": {}
      },
      "pirates@4.0.6": {
        "integrity": "sha512-saLsH7WeYYPiD25LDuLRRY/i+6HaPYr6G1OUlN39otzkSTxKnubR9RTxS3/Kk50s1g2JTgFwWQDQyplC5/SHZg==",
        "dependencies": {}
      },
      "postcss-calc@9.0.1_postcss@8.4.31": {
        "integrity": "sha512-TipgjGyzP5QzEhsOZUaIkeO5mKeMFpebWzRogWG/ysonUlnHcq5aJe0jOjpfzUU8PeSaBQnrE8ehR0QA5vs8PQ==",
        "dependencies": {
          "postcss": "postcss@8.4.31",
          "postcss-selector-parser": "postcss-selector-parser@6.0.13",
          "postcss-value-parser": "postcss-value-parser@4.2.0"
        }
      },
      "postcss-colormin@6.0.0_postcss@8.4.31": {
        "integrity": "sha512-EuO+bAUmutWoZYgHn2T1dG1pPqHU6L4TjzPlu4t1wZGXQ/fxV16xg2EJmYi0z+6r+MGV1yvpx1BHkUaRrPa2bw==",
        "dependencies": {
          "browserslist": "browserslist@4.22.1",
          "caniuse-api": "caniuse-api@3.0.0",
          "colord": "colord@2.9.3",
          "postcss": "postcss@8.4.31",
          "postcss-value-parser": "postcss-value-parser@4.2.0"
        }
      },
      "postcss-convert-values@6.0.0_postcss@8.4.31": {
        "integrity": "sha512-U5D8QhVwqT++ecmy8rnTb+RL9n/B806UVaS3m60lqle4YDFcpbS3ae5bTQIh3wOGUSDHSEtMYLs/38dNG7EYFw==",
        "dependencies": {
          "browserslist": "browserslist@4.22.1",
          "postcss": "postcss@8.4.31",
          "postcss-value-parser": "postcss-value-parser@4.2.0"
        }
      },
      "postcss-discard-comments@6.0.0_postcss@8.4.31": {
        "integrity": "sha512-p2skSGqzPMZkEQvJsgnkBhCn8gI7NzRH2683EEjrIkoMiwRELx68yoUJ3q3DGSGuQ8Ug9Gsn+OuDr46yfO+eFw==",
        "dependencies": {
          "postcss": "postcss@8.4.31"
        }
      },
      "postcss-discard-duplicates@6.0.0_postcss@8.4.31": {
        "integrity": "sha512-bU1SXIizMLtDW4oSsi5C/xHKbhLlhek/0/yCnoMQany9k3nPBq+Ctsv/9oMmyqbR96HYHxZcHyK2HR5P/mqoGA==",
        "dependencies": {
          "postcss": "postcss@8.4.31"
        }
      },
      "postcss-discard-empty@6.0.0_postcss@8.4.31": {
        "integrity": "sha512-b+h1S1VT6dNhpcg+LpyiUrdnEZfICF0my7HAKgJixJLW7BnNmpRH34+uw/etf5AhOlIhIAuXApSzzDzMI9K/gQ==",
        "dependencies": {
          "postcss": "postcss@8.4.31"
        }
      },
      "postcss-discard-overridden@6.0.0_postcss@8.4.31": {
        "integrity": "sha512-4VELwssYXDFigPYAZ8vL4yX4mUepF/oCBeeIT4OXsJPYOtvJumyz9WflmJWTfDwCUcpDR+z0zvCWBXgTx35SVw==",
        "dependencies": {
          "postcss": "postcss@8.4.31"
        }
      },
      "postcss-import@15.1.0_postcss@8.4.31": {
        "integrity": "sha512-hpr+J05B2FVYUAXHeK1YyI267J/dDDhMU6B6civm8hSY1jYJnBXxzKDKDswzJmtLHryrjhnDjqqp/49t8FALew==",
        "dependencies": {
          "postcss": "postcss@8.4.31",
          "postcss-value-parser": "postcss-value-parser@4.2.0",
          "read-cache": "read-cache@1.0.0",
          "resolve": "resolve@1.22.8"
        }
      },
      "postcss-js@4.0.1_postcss@8.4.31": {
        "integrity": "sha512-dDLF8pEO191hJMtlHFPRa8xsizHaM82MLfNkUHdUtVEV3tgTp5oj+8qbEqYM57SLfc74KSbw//4SeJma2LRVIw==",
        "dependencies": {
          "camelcase-css": "camelcase-css@2.0.1",
          "postcss": "postcss@8.4.31"
        }
      },
      "postcss-load-config@4.0.1_postcss@8.4.31": {
        "integrity": "sha512-vEJIc8RdiBRu3oRAI0ymerOn+7rPuMvRXslTvZUKZonDHFIczxztIyJ1urxM1x9JXEikvpWWTUUqal5j/8QgvA==",
        "dependencies": {
          "lilconfig": "lilconfig@2.1.0",
          "postcss": "postcss@8.4.31",
          "yaml": "yaml@2.3.4"
        }
      },
      "postcss-merge-longhand@6.0.0_postcss@8.4.31": {
        "integrity": "sha512-4VSfd1lvGkLTLYcxFuISDtWUfFS4zXe0FpF149AyziftPFQIWxjvFSKhA4MIxMe4XM3yTDgQMbSNgzIVxChbIg==",
        "dependencies": {
          "postcss": "postcss@8.4.31",
          "postcss-value-parser": "postcss-value-parser@4.2.0",
          "stylehacks": "stylehacks@6.0.0_postcss@8.4.31"
        }
      },
      "postcss-merge-rules@6.0.1_postcss@8.4.31": {
        "integrity": "sha512-a4tlmJIQo9SCjcfiCcCMg/ZCEe0XTkl/xK0XHBs955GWg9xDX3NwP9pwZ78QUOWB8/0XCjZeJn98Dae0zg6AAw==",
        "dependencies": {
          "browserslist": "browserslist@4.22.1",
          "caniuse-api": "caniuse-api@3.0.0",
          "cssnano-utils": "cssnano-utils@4.0.0_postcss@8.4.31",
          "postcss": "postcss@8.4.31",
          "postcss-selector-parser": "postcss-selector-parser@6.0.13"
        }
      },
      "postcss-minify-font-values@6.0.0_postcss@8.4.31": {
        "integrity": "sha512-zNRAVtyh5E8ndZEYXA4WS8ZYsAp798HiIQ1V2UF/C/munLp2r1UGHwf1+6JFu7hdEhJFN+W1WJQKBrtjhFgEnA==",
        "dependencies": {
          "postcss": "postcss@8.4.31",
          "postcss-value-parser": "postcss-value-parser@4.2.0"
        }
      },
      "postcss-minify-gradients@6.0.0_postcss@8.4.31": {
        "integrity": "sha512-wO0F6YfVAR+K1xVxF53ueZJza3L+R3E6cp0VwuXJQejnNUH0DjcAFe3JEBeTY1dLwGa0NlDWueCA1VlEfiKgAA==",
        "dependencies": {
          "colord": "colord@2.9.3",
          "cssnano-utils": "cssnano-utils@4.0.0_postcss@8.4.31",
          "postcss": "postcss@8.4.31",
          "postcss-value-parser": "postcss-value-parser@4.2.0"
        }
      },
      "postcss-minify-params@6.0.0_postcss@8.4.31": {
        "integrity": "sha512-Fz/wMQDveiS0n5JPcvsMeyNXOIMrwF88n7196puSuQSWSa+/Ofc1gDOSY2xi8+A4PqB5dlYCKk/WfqKqsI+ReQ==",
        "dependencies": {
          "browserslist": "browserslist@4.22.1",
          "cssnano-utils": "cssnano-utils@4.0.0_postcss@8.4.31",
          "postcss": "postcss@8.4.31",
          "postcss-value-parser": "postcss-value-parser@4.2.0"
        }
      },
      "postcss-minify-selectors@6.0.0_postcss@8.4.31": {
        "integrity": "sha512-ec/q9JNCOC2CRDNnypipGfOhbYPuUkewGwLnbv6omue/PSASbHSU7s6uSQ0tcFRVv731oMIx8k0SP4ZX6be/0g==",
        "dependencies": {
          "postcss": "postcss@8.4.31",
          "postcss-selector-parser": "postcss-selector-parser@6.0.13"
        }
      },
      "postcss-nested@6.0.1_postcss@8.4.31": {
        "integrity": "sha512-mEp4xPMi5bSWiMbsgoPfcP74lsWLHkQbZc3sY+jWYd65CUwXrUaTp0fmNpa01ZcETKlIgUdFN/MpS2xZtqL9dQ==",
        "dependencies": {
          "postcss": "postcss@8.4.31",
          "postcss-selector-parser": "postcss-selector-parser@6.0.13"
        }
      },
      "postcss-normalize-charset@6.0.0_postcss@8.4.31": {
        "integrity": "sha512-cqundwChbu8yO/gSWkuFDmKrCZ2vJzDAocheT2JTd0sFNA4HMGoKMfbk2B+J0OmO0t5GUkiAkSM5yF2rSLUjgQ==",
        "dependencies": {
          "postcss": "postcss@8.4.31"
        }
      },
      "postcss-normalize-display-values@6.0.0_postcss@8.4.31": {
        "integrity": "sha512-Qyt5kMrvy7dJRO3OjF7zkotGfuYALETZE+4lk66sziWSPzlBEt7FrUshV6VLECkI4EN8Z863O6Nci4NXQGNzYw==",
        "dependencies": {
          "postcss": "postcss@8.4.31",
          "postcss-value-parser": "postcss-value-parser@4.2.0"
        }
      },
      "postcss-normalize-positions@6.0.0_postcss@8.4.31": {
        "integrity": "sha512-mPCzhSV8+30FZyWhxi6UoVRYd3ZBJgTRly4hOkaSifo0H+pjDYcii/aVT4YE6QpOil15a5uiv6ftnY3rm0igPg==",
        "dependencies": {
          "postcss": "postcss@8.4.31",
          "postcss-value-parser": "postcss-value-parser@4.2.0"
        }
      },
      "postcss-normalize-repeat-style@6.0.0_postcss@8.4.31": {
        "integrity": "sha512-50W5JWEBiOOAez2AKBh4kRFm2uhrT3O1Uwdxz7k24aKtbD83vqmcVG7zoIwo6xI2FZ/HDlbrCopXhLeTpQib1A==",
        "dependencies": {
          "postcss": "postcss@8.4.31",
          "postcss-value-parser": "postcss-value-parser@4.2.0"
        }
      },
      "postcss-normalize-string@6.0.0_postcss@8.4.31": {
        "integrity": "sha512-KWkIB7TrPOiqb8ZZz6homet2KWKJwIlysF5ICPZrXAylGe2hzX/HSf4NTX2rRPJMAtlRsj/yfkrWGavFuB+c0w==",
        "dependencies": {
          "postcss": "postcss@8.4.31",
          "postcss-value-parser": "postcss-value-parser@4.2.0"
        }
      },
      "postcss-normalize-timing-functions@6.0.0_postcss@8.4.31": {
        "integrity": "sha512-tpIXWciXBp5CiFs8sem90IWlw76FV4oi6QEWfQwyeREVwUy39VSeSqjAT7X0Qw650yAimYW5gkl2Gd871N5SQg==",
        "dependencies": {
          "postcss": "postcss@8.4.31",
          "postcss-value-parser": "postcss-value-parser@4.2.0"
        }
      },
      "postcss-normalize-unicode@6.0.0_postcss@8.4.31": {
        "integrity": "sha512-ui5crYkb5ubEUDugDc786L/Me+DXp2dLg3fVJbqyAl0VPkAeALyAijF2zOsnZyaS1HyfPuMH0DwyY18VMFVNkg==",
        "dependencies": {
          "browserslist": "browserslist@4.22.1",
          "postcss": "postcss@8.4.31",
          "postcss-value-parser": "postcss-value-parser@4.2.0"
        }
      },
      "postcss-normalize-url@6.0.0_postcss@8.4.31": {
        "integrity": "sha512-98mvh2QzIPbb02YDIrYvAg4OUzGH7s1ZgHlD3fIdTHLgPLRpv1ZTKJDnSAKr4Rt21ZQFzwhGMXxpXlfrUBKFHw==",
        "dependencies": {
          "postcss": "postcss@8.4.31",
          "postcss-value-parser": "postcss-value-parser@4.2.0"
        }
      },
      "postcss-normalize-whitespace@6.0.0_postcss@8.4.31": {
        "integrity": "sha512-7cfE1AyLiK0+ZBG6FmLziJzqQCpTQY+8XjMhMAz8WSBSCsCNNUKujgIgjCAmDT3cJ+3zjTXFkoD15ZPsckArVw==",
        "dependencies": {
          "postcss": "postcss@8.4.31",
          "postcss-value-parser": "postcss-value-parser@4.2.0"
        }
      },
      "postcss-ordered-values@6.0.0_postcss@8.4.31": {
        "integrity": "sha512-K36XzUDpvfG/nWkjs6d1hRBydeIxGpKS2+n+ywlKPzx1nMYDYpoGbcjhj5AwVYJK1qV2/SDoDEnHzlPD6s3nMg==",
        "dependencies": {
          "cssnano-utils": "cssnano-utils@4.0.0_postcss@8.4.31",
          "postcss": "postcss@8.4.31",
          "postcss-value-parser": "postcss-value-parser@4.2.0"
        }
      },
      "postcss-reduce-initial@6.0.0_postcss@8.4.31": {
        "integrity": "sha512-s2UOnidpVuXu6JiiI5U+fV2jamAw5YNA9Fdi/GRK0zLDLCfXmSGqQtzpUPtfN66RtCbb9fFHoyZdQaxOB3WxVA==",
        "dependencies": {
          "browserslist": "browserslist@4.22.1",
          "caniuse-api": "caniuse-api@3.0.0",
          "postcss": "postcss@8.4.31"
        }
      },
      "postcss-reduce-transforms@6.0.0_postcss@8.4.31": {
        "integrity": "sha512-FQ9f6xM1homnuy1wLe9lP1wujzxnwt1EwiigtWwuyf8FsqqXUDUp2Ulxf9A5yjlUOTdCJO6lonYjg1mgqIIi2w==",
        "dependencies": {
          "postcss": "postcss@8.4.31",
          "postcss-value-parser": "postcss-value-parser@4.2.0"
        }
      },
      "postcss-selector-parser@6.0.13": {
        "integrity": "sha512-EaV1Gl4mUEV4ddhDnv/xtj7sxwrwxdetHdWUGnT4VJQf+4d05v6lHYZr8N573k5Z0BViss7BDhfWtKS3+sfAqQ==",
        "dependencies": {
          "cssesc": "cssesc@3.0.0",
          "util-deprecate": "util-deprecate@1.0.2"
        }
      },
      "postcss-svgo@6.0.0_postcss@8.4.31": {
        "integrity": "sha512-r9zvj/wGAoAIodn84dR/kFqwhINp5YsJkLoujybWG59grR/IHx+uQ2Zo+IcOwM0jskfYX3R0mo+1Kip1VSNcvw==",
        "dependencies": {
          "postcss": "postcss@8.4.31",
          "postcss-value-parser": "postcss-value-parser@4.2.0",
          "svgo": "svgo@3.0.2"
        }
      },
      "postcss-unique-selectors@6.0.0_postcss@8.4.31": {
        "integrity": "sha512-EPQzpZNxOxP7777t73RQpZE5e9TrnCrkvp7AH7a0l89JmZiPnS82y216JowHXwpBCQitfyxrof9TK3rYbi7/Yw==",
        "dependencies": {
          "postcss": "postcss@8.4.31",
          "postcss-selector-parser": "postcss-selector-parser@6.0.13"
        }
      },
      "postcss-value-parser@4.2.0": {
        "integrity": "sha512-1NNCs6uurfkVbeXG4S8JFT9t19m45ICnif8zWLd5oPSZ50QnwMfK+H3jv408d4jw/7Bttv5axS5IiHoLaVNHeQ==",
        "dependencies": {}
      },
      "postcss@8.4.31": {
        "integrity": "sha512-PS08Iboia9mts/2ygV3eLpY5ghnUcfLV/EXTOW1E2qYxJKGGBUtNjN76FYHnMs36RmARn41bC0AZmn+rR0OVpQ==",
        "dependencies": {
          "nanoid": "nanoid@3.3.7",
          "picocolors": "picocolors@1.0.0",
          "source-map-js": "source-map-js@1.0.2"
        }
      },
      "queue-microtask@1.2.3": {
        "integrity": "sha512-NuaNSa6flKT5JaSYQzJok04JzTL1CA6aGhv5rfLW3PgqA+M2ChpZQnAC8h8i4ZFkBS8X5RqkDBHA7r4hej3K9A==",
        "dependencies": {}
      },
      "read-cache@1.0.0": {
        "integrity": "sha512-Owdv/Ft7IjOgm/i0xvNDZ1LrRANRfew4b2prF3OWMQLxLfu3bS8FVhCsrSCMK4lR56Y9ya+AThoTpDCTxCmpRA==",
        "dependencies": {
          "pify": "pify@2.3.0"
        }
      },
      "readdirp@3.6.0": {
        "integrity": "sha512-hOS089on8RduqdbhvQ5Z37A0ESjsqz6qnRcffsMU3495FuTdqSm+7bhJ29JvIOsBDEEnan5DPu9t3To9VRlMzA==",
        "dependencies": {
          "picomatch": "picomatch@2.3.1"
        }
      },
      "resolve@1.22.8": {
        "integrity": "sha512-oKWePCxqpd6FlLvGV1VU0x7bkPmmCNolxzjMf4NczoDnQcIWrAF+cPtZn5i6n+RfD2d9i0tzpKnG6Yk168yIyw==",
        "dependencies": {
          "is-core-module": "is-core-module@2.13.1",
          "path-parse": "path-parse@1.0.7",
          "supports-preserve-symlinks-flag": "supports-preserve-symlinks-flag@1.0.0"
        }
      },
      "reusify@1.0.4": {
        "integrity": "sha512-U9nH88a3fc/ekCF1l0/UP1IosiuIjyTh7hBvXVMHYgVcfGvt897Xguj2UOLDeI5BG2m7/uwyaLVT6fbtCwTyzw==",
        "dependencies": {}
      },
      "run-parallel@1.2.0": {
        "integrity": "sha512-5l4VyZR86LZ/lDxZTR6jqL8AFE2S0IFLMP26AbjsLVADxHdhB/c0GUsH+y39UfCi3dzz8OlQuPmnaJOMoDHQBA==",
        "dependencies": {
          "queue-microtask": "queue-microtask@1.2.3"
        }
      },
      "source-map-js@1.0.2": {
        "integrity": "sha512-R0XvVJ9WusLiqTCEiGCmICCMplcCkIwwR11mOSD9CR5u+IXYdiseeEuXCVAjS54zqwkLcPNnmU4OeJ6tUrWhDw==",
        "dependencies": {}
      },
      "stylehacks@6.0.0_postcss@8.4.31": {
        "integrity": "sha512-+UT589qhHPwz6mTlCLSt/vMNTJx8dopeJlZAlBMJPWA3ORqu6wmQY7FBXf+qD+FsqoBJODyqNxOUP3jdntFRdw==",
        "dependencies": {
          "browserslist": "browserslist@4.22.1",
          "postcss": "postcss@8.4.31",
          "postcss-selector-parser": "postcss-selector-parser@6.0.13"
        }
      },
      "sucrase@3.34.0": {
        "integrity": "sha512-70/LQEZ07TEcxiU2dz51FKaE6hCTWC6vr7FOk3Gr0U60C3shtAN+H+BFr9XlYe5xqf3RA8nrc+VIwzCfnxuXJw==",
        "dependencies": {
          "@jridgewell/gen-mapping": "@jridgewell/gen-mapping@0.3.3",
          "commander": "commander@4.1.1",
          "glob": "glob@7.1.6",
          "lines-and-columns": "lines-and-columns@1.2.4",
          "mz": "mz@2.7.0",
          "pirates": "pirates@4.0.6",
          "ts-interface-checker": "ts-interface-checker@0.1.13"
        }
      },
      "supports-preserve-symlinks-flag@1.0.0": {
        "integrity": "sha512-ot0WnXS9fgdkgIcePe6RHNk1WA8+muPa6cSjeR3V8K27q9BB1rTE3R1p7Hv0z1ZyAc8s6Vvv8DIyWf681MAt0w==",
        "dependencies": {}
      },
      "svgo@3.0.2": {
        "integrity": "sha512-Z706C1U2pb1+JGP48fbazf3KxHrWOsLme6Rv7imFBn5EnuanDW1GPaA/P1/dvObE670JDePC3mnj0k0B7P0jjQ==",
        "dependencies": {
          "@trysound/sax": "@trysound/sax@0.2.0",
          "commander": "commander@7.2.0",
          "css-select": "css-select@5.1.0",
          "css-tree": "css-tree@2.3.1",
          "csso": "csso@5.0.5",
          "picocolors": "picocolors@1.0.0"
        }
      },
      "tailwindcss@3.3.5_postcss@8.4.31": {
        "integrity": "sha512-5SEZU4J7pxZgSkv7FP1zY8i2TIAOooNZ1e/OGtxIEv6GltpoiXUqWvLy89+a10qYTB1N5Ifkuw9lqQkN9sscvA==",
        "dependencies": {
          "@alloc/quick-lru": "@alloc/quick-lru@5.2.0",
          "arg": "arg@5.0.2",
          "chokidar": "chokidar@3.5.3",
          "didyoumean": "didyoumean@1.2.2",
          "dlv": "dlv@1.1.3",
          "fast-glob": "fast-glob@3.3.2",
          "glob-parent": "glob-parent@6.0.2",
          "is-glob": "is-glob@4.0.3",
          "jiti": "jiti@1.21.0",
          "lilconfig": "lilconfig@2.1.0",
          "micromatch": "micromatch@4.0.5",
          "normalize-path": "normalize-path@3.0.0",
          "object-hash": "object-hash@3.0.0",
          "picocolors": "picocolors@1.0.0",
          "postcss": "postcss@8.4.31",
          "postcss-import": "postcss-import@15.1.0_postcss@8.4.31",
          "postcss-js": "postcss-js@4.0.1_postcss@8.4.31",
          "postcss-load-config": "postcss-load-config@4.0.1_postcss@8.4.31",
          "postcss-nested": "postcss-nested@6.0.1_postcss@8.4.31",
          "postcss-selector-parser": "postcss-selector-parser@6.0.13",
          "resolve": "resolve@1.22.8",
          "sucrase": "sucrase@3.34.0"
        }
      },
      "thenify-all@1.6.0": {
        "integrity": "sha512-RNxQH/qI8/t3thXJDwcstUO4zeqo64+Uy/+sNVRBx4Xn2OX+OZ9oP+iJnNFqplFra2ZUVeKCSa2oVWi3T4uVmA==",
        "dependencies": {
          "thenify": "thenify@3.3.1"
        }
      },
      "thenify@3.3.1": {
        "integrity": "sha512-RVZSIV5IG10Hk3enotrhvz0T9em6cyHBLkH/YAZuKqd8hRkKhSfCGIcP2KUY0EPxndzANBmNllzWPwak+bheSw==",
        "dependencies": {
          "any-promise": "any-promise@1.3.0"
        }
      },
      "to-regex-range@5.0.1": {
        "integrity": "sha512-65P7iz6X5yEr1cwcgvQxbbIw7Uk3gOy5dIdtZ4rDveLqhrdJP+Li/Hx6tyK0NEb+2GCyneCMJiGqrADCSNk8sQ==",
        "dependencies": {
          "is-number": "is-number@7.0.0"
        }
      },
      "ts-interface-checker@0.1.13": {
        "integrity": "sha512-Y/arvbn+rrz3JCKl9C4kVNfTfSm2/mEp5FSz5EsZSANGPSlQrpRI5M4PKF+mJnE52jOO90PnPSc3Ur3bTQw0gA==",
        "dependencies": {}
      },
      "update-browserslist-db@1.0.13_browserslist@4.22.1": {
        "integrity": "sha512-xebP81SNcPuNpPP3uzeW1NYXxI3rxyJzF3pD6sH4jE7o/IX+WtSpwnVU+qIsDPyk0d3hmFQ7mjqc6AtV604hbg==",
        "dependencies": {
          "browserslist": "browserslist@4.22.1",
          "escalade": "escalade@3.1.1",
          "picocolors": "picocolors@1.0.0"
        }
      },
      "util-deprecate@1.0.2": {
        "integrity": "sha512-EPD5q1uXyFxJpCrLnCc1nHnq3gOa6DZBocAIiI2TaSCA7VCJ1UJDMagCzIkXNsUYfD1daK//LTEQ8xiIbrHtcw==",
        "dependencies": {}
      },
      "wrappy@1.0.2": {
        "integrity": "sha512-l4Sp/DRseor9wL6EvV2+TuQn63dMkPjZ/sp9XkghTEbV9KlPS1xUsZ3u7/IQO4wxtcFB4bgpQPRcR3QCvezPcQ==",
        "dependencies": {}
      },
      "yaml@2.3.4": {
        "integrity": "sha512-8aAvwVUSHpfEqTQ4w/KMlf3HcRdt50E5ODIQJBw1fQ5RL34xabzxtUlzTXVqc4rkZsPbvrXKWnABCD7kWSmocA==",
        "dependencies": {}
      }
    }
  },
  "remote": {
  },
  "workspace": {
    "dependencies": [
      "npm:@spotify/web-api-ts-sdk",
      "npm:tailwindcss@3.3.5"
    ]
  }
}
```
</details>

Removing tailwind results in the following:

```
error: failed reading lockfile 'deno.lock'

Caused by:
    0: The lockfile is corrupt. You can recreate it with --lock-write
    1: Could not find 'postcss-selector-parser@6.0.13' in the list of packages.
```

Version: Deno 1.40.3

### PR DESCRIPTION
**Pull request by dsherret**
Tests are in the deno_lockfile repo.

Closes #22250

### CODE REVIEW

File: cli/tests/integration/run_tests.rs [hunk 1]
```diff
@@ -1051,6 +1051,9 @@ fn lock_deno_json_package_json_deps() {
         "jsr:@denotest/module_graph@1.4": "jsr:@denotest/module_graph@1.4.0",
         "npm:@denotest/esm-basic": "npm:@denotest/esm-basic@1.0.0"
       },
+      "jsr": {
+        "@denotest/module_graph@1.4.0": {}
```
Comment (dsherret) [inline cli/tests/integration/run_tests.rs:1055]: We always insert these as part of the fix because in the future we'll have an integrity value here.

**Review by mmastrac — APPROVED** [review]
LGT
