### PR TITLE
fix(cli/tools): correct `deno init --serve` template behavior

### LINKED ISSUE #25305: `deno init --serve` is confusing
This route handler

```ts
{
  pattern: new URLPattern({ pathname: "/static/*" }),
  handler: (req) => serveDir(req, { urlRoot: "./" }),
},
```

paired with this test

```ts
Deno.test(async function serverFetchStatic() {
  const req = new Request("https://deno.land/static/main.ts");
  const res = await server.fetch(req);
  assertEquals(res.headers.get("content-type"), "text/plain;charset=UTF-8");
});
```

Makes it seem like the default template works and serves the main.ts file included in the template but that isn't the case and the response is a 404.

This makes it harder to get started IMO, and trying to figure out the correct folder path to place static files, the correct options to the file server, and wondering why the server doesn't work as expected after watching the tests pass

Possible improvements

- Comments in the files

- Remove the static server test

- Improve (less ambiguous) the static server test by asserting response status 404

- Rewrite the route and test to something like this that serves files from the root

```ts
// serves files from the root
{
  pattern: new URLPattern({ pathname: "/static/*" }),
  handler: (req: Request) => {
    return serveDir(req, { urlRoot: "static" });
  },
},
```

```ts
import denoJson from "./deno.json" with { type: "json" };

// ...

Deno.test(async function serverFetchStatic() {
  const req = new Request("https://deno.land/static/main.ts");
  const res = await server.fetch(req);
  assertEquals(await res.json(), denoJson);
});
```

versions:

```
deno 1.46.1 (stable, release, aarch64-apple-darwin)
v8 12.9.202.2-rusty
typescript 5.5.2
```

### PR DESCRIPTION
**Pull request by cotyhamilton**
fix #25305

- adds static folder and asset
- makes the static server test in the template more meaningful
- reorders args in help message
- fixes output to conform to default `deno fmt`

### CODE REVIEW

**Comment by cotyhamilton** [comment]
I would have liked to have used `fsRoot` along with `urlRoot` in the `ServeDirOptions` to show them off but the rust tests complained that `fsRoot` option didn't exist 🤷‍♀️ I think maybe the version of std lib isn't all the way up to date

```ts
{
  pattern: new URLPattern({ pathname: "/static/*" }),
  handler: (req) => serveDir(req, { fsRoot: "static", urlRoot: "static" }),
},
```

File: cli/tools/init/mod.rs [hunk 1]
```diff
@@ -203,7 +211,7 @@ Deno.test(function addTest() {
     info!("  deno task dev");
     info!("");
     info!("  {}", colors::gray("# Run the tests"));
-    info!("  deno -R test");
+    info!("  deno test -R");
```
Comment (bartlomieju) [inline cli/tools/init/mod.rs:214]: This is wrong, the allow read permission will not be applied in such a command

Comment (cotyhamilton) [reply cli/tools/init/mod.rs:214]: I'm not sure if I'm misunderstanding your comment, please let me know if I am

I will test some more, but I have deno 1.46 along with DENO_FUTURE=1 and this was the correct order of args.

I think the integration test would have failed also if this was wrong.

Comment (cotyhamilton) [reply cli/tools/init/mod.rs:214]: I was wrong about the integration tests, it appears the read permission flag doesn't have any effect on the child process running in these tests and read permission implicitly granted.

Testing manually again though `deno test -R` is needed for read permission

```
deno 1.46.2 (stable, release, aarch64-apple-darwin)
v8 12.9.202.5-rusty
typescript 5.5.2
```

```bash
deno init --serve demo
cd demo
```

Fix route handler

```diff
{
  pattern: new URLPattern({ pathname: "/static/*" }),
-   handler: (req) => serveDir(req, { urlRoot: "./" }),
+   handler: (req) => serveDir(req),
// or -- handler: (req) => serveDir(req, { fsRoot: "static", urlRoot: "static" }),
},
```

`deno -R test`

```
cotyhamilton dev/demo 
➜ deno -R test
Check file:///Users/cotyhamilton/dev/demo/main_test.ts
running 4 tests from ./main_test.ts
serverFetch ... ok (1ms)
serverFetchNotFound ... ok (0ms)
serverFetchUsers ... ok (0ms)
serverFetchStatic ...
------- output -------
Requires read access to "static/main.ts", run again with the --allow-read flag
[2024-09-01 03:54:26] [GET] /static/main.ts 500
----- output end -----
serverFetchStatic ... ok (6ms)

ok | 4 passed | 0 failed (10ms)
```

> Requires read access to "static/main.ts", run again with the --allow-read flag

---

`deno test -R`

```
cotyhamilton dev/demo 
➜ deno test -R
running 4 tests from ./main_test.ts
serverFetch ... ok (1ms)
serverFetchNotFound ... ok (0ms)
serverFetchUsers ... ok (0ms)
serverFetchStatic ...
------- output -------
No such file or directory (os error 2): stat 'static/main.ts'
[2024-09-01 03:54:32] [GET] /static/main.ts 404
----- output end -----
serverFetchStatic ... ok (2ms)
```

Comment (iuioiua) [reply cli/tools/init/mod.rs:215]: @bartlomieju, `deno test -R` is actually right. I think you're getting confused because there's no defined entry point. Imagine it was `deno test -R <entrypoint>`. [Reference](https://docs.deno.com/runtime/manual/tools/test/).

**Review by iuioiua — APPROVED** [review]
Great! Thank you.
