### PR TITLE
fix(watch): ignore unload errors on drop

### LINKED ISSUE #15428: `deno run --watch` panics when handling error
Pardon me for not able to provide a reproduce without dependencies, but I believe this is a Deno bug as it should be able to handle errors gracefully.

Given the following Telegram bot program:

```js
// test.ts
import {Bot} from 'https://deno.land/x/grammy@v1.8.3/mod.ts'
import {Octokit} from 'https://esm.sh/@octokit/rest@19.0.3'

new Octokit() // Without this there's no error, can't comprehend

const bot = new Bot(Deno.env.get('BOT_TOKEN'))

bot.command('test', (ctx) => {
	ctx.reply(does_not_exist) // This triggers an error
})

bot.start()
```

Run it, send a `/test` command to the bot, the program errored out:

```shellsession
$ deno run -A ./test.ts
Error in middleware while handling update 148195597 ReferenceError: does_not_exist is not defined
    at file:///workspaces/qvrelease-bot/test.ts:9:12
    at https://deno.land/x/grammy@v1.8.3/composer.ts:125:41
    at https://deno.land/x/grammy@v1.8.3/composer.ts:125:41
    at https://deno.land/x/grammy@v1.8.3/composer.ts:677:48
    at async https://deno.land/x/grammy@v1.8.3/composer.ts:136:13
    at async https://deno.land/x/grammy@v1.8.3/composer.ts:133:9
    at async https://deno.land/x/grammy@v1.8.3/composer.ts:677:13
    at async https://deno.land/x/grammy@v1.8.3/composer.ts:136:13
    at async https://deno.land/x/grammy@v1.8.3/composer.ts:133:9
    at async run (https://deno.land/x/grammy@v1.8.3/composer.ts:155:5)
No error handler was set!
Set your own error handler with `bot.catch = ...`
Stopping bot
error: Uncaught BotError: ReferenceError in middleware: does_not_exist is not defined
```

But when running it with `--watch`, Deno will panic when the error is triggerd:

```shellsession
$ deno run --watch -A ./test.ts
Watcher Process started.
Error in middleware while handling update 148195598 ReferenceError: does_not_exist is not defined
    at file:///workspaces/qvrelease-bot/test.ts:9:12
    at https://deno.land/x/grammy@v1.8.3/composer.ts:125:41
    at https://deno.land/x/grammy@v1.8.3/composer.ts:125:41
    at https://deno.land/x/grammy@v1.8.3/composer.ts:677:48
    at async https://deno.land/x/grammy@v1.8.3/composer.ts:136:13
    at async https://deno.land/x/grammy@v1.8.3/composer.ts:133:9
    at async https://deno.land/x/grammy@v1.8.3/composer.ts:677:13
    at async https://deno.land/x/grammy@v1.8.3/composer.ts:136:13
    at async https://deno.land/x/grammy@v1.8.3/composer.ts:133:9
    at async run (https://deno.land/x/grammy@v1.8.3/composer.ts:155:5)
No error handler was set!
Set your own error handler with `bot.catch = ...`
Stopping bot

============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: linux x86_64
Version: 1.24.2
Args: ["deno", "run", "--watch", "-A", "./test.ts"]

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Uncaught Error: execution terminated', cli/main.rs:983:12
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### PR DESCRIPTION
**Pull request by nayeemrmn**
Fixes #15428.

### CODE REVIEW

File: cli/worker.rs [hunk 1]
```diff
@@ -126,13 +126,18 @@ impl CliMainWorker {
...
+          match self
             .inner
             .worker
-            .dispatch_beforeunload_event(&located_script_name!())?
+            .dispatch_beforeunload_event(&located_script_name!())
           {
-            break result;
+            Ok(default_prevented) if default_prevented => {} // continue loop
+            Ok(_) => break Ok(()),
+            Err(error) => break Err(error),
```
Comment (nayeemrmn) [inline cli/worker.rs:140]: The unload on drop case is only meant to be hit when the watcher restarts on file changes mid-execution, but due to faulty circuiting here it could be hit on `"beforeunload"` handler errors or other error events (#15428). It's fixed with this

File: cli/tests/integration/watcher_tests.rs [hunk 2]
```diff
@@ -1038,6 +1038,40 @@ fn test_watch_module_graph_error_referrer() {
   check_alive_then_kill(child);
 }
 
+// Regression test for https://github.com/denoland/deno/issues/15428.
+#[test]
+fn test_watch_unload_handler_error_on_drop() {
```
Comment (bartlomieju) [inline cli/tests/integration/watcher_tests.rs:1043]: I verified that this test panics on `main`

**Review by bartlomieju — APPROVED** [review]
LGTM, nice fix. Thank you @nayeemrmn
