### PR TITLE
fix(ext/cache): illegal constructor

### LINKED ISSUE #16199: cache: `new Cache()` does not throw a `TypeError`
Given the code
```js
new Cache();
new Cache("test");
```
deno does not throw an error, while both Firefox and Chromium give
```js
Uncaught TypeError: Illegal constructor
```

Side note, TypeScirpt gives this error as well
```ts
error: TS2554 [ERROR]: Expected 1 arguments, but got 0.
```

### PR DESCRIPTION
**Pull request by marcosc90**
fixes #16199

There is no `constructor` in `interface Cache {}`
https://w3c.github.io/ServiceWorker/#cache-interface

### CODE REVIEW

**Review by crowlKats — COMMENTED** [review]
this should rather be using `webidl.createBranded` & also have brand assertions in all the methods

File: ext/cache/01_cache.js [hunk 1]
```diff
@@ -200,79 +205,80 @@
...
-      ) {
-        r = new Request(request);
+  /** See https://w3c.github.io/ServiceWorker/#cache-matchall
+   *
+   * Note: the function is private as we don't want to expose
+   * this API to the public yet.
+   *
+   * The function will return an array of responses.
+   */
+  async function matchAll(request, _options, cacheId) {
```
Comment (marcosc90) [inline ext/cache/01_cache.js:217]: Removed private method since it fails after branding with: 
```
TypeError: Receiver must be an instance of class Cache
```

Comment (crowlKats) [reply ext/cache/01_cache.js:217]: you could use a symbol then isntead like we do for websocket: https://github.com/denoland/deno/blob/a3432e54c7214dd37b7318ad03442b8415fb4f67/ext/websocket/01_websocket.js#L393

File: cli/tests/unit/cache_api_test.ts [hunk 2]
```diff
@@ -95,6 +96,13 @@ Deno.test(async function cacheApi() {
   assertFalse(await caches.has(cacheName));
 });
 
+Deno.test(function cacheIllegalConstructor() {
+  // @ts-ignore illegal constructor
+  assertThrows(() => new Cache(), TypeError, "Illegal constructor");
+  // @ts-ignore illegal constructor
```
Comment (axetroy) [inline cli/tests/unit/cache_api_test.ts:102]: // @ts-expect-error maybe better?

**Review by satyarohith — APPROVED** [review]
LGTM. Thanks!
