### PR TITLE
fix(ext/node): windows cancel stdin read in line mode

### LINKED ISSUE #21111: create-next-app prompts don't work on Windows
It's not possibe to change the selection from yes to no:

```
$ deno run -A npm:create-next-app@latest next-app
√ Would you like to use TypeScript? ... No / Yes
? Would you like to use ESLint? » No / Yes^[[D
√ Would you like to use ESLint? ... No / Yes
? Would you like to use Tailwind CSS? » No / Yes^[[D^[[B^[[A^[[C
√ Would you like to use Tailwind CSS? ... No / Yes
? Would you like to use `src/` directory? » No / Yes^[[C
√ Would you like to use `src/` directory? ... No / Yes
? Would you like to use App Router? (recommended) » No / Yes
√ Would you like to use App Router? (recommended) ... No / Yes
? Would you like to customize the default import alias (@/*)? » No / Yes
√ Would you like to customize the default import alias (@/*)? ... No / Yes
Creating a new Next.js app in V:\next-app.
```

### PR DESCRIPTION
**Pull request by littledivy**
This patch fixes stdin read hanging on user input when switching tty mode on Windows

Fixes #21111 

On Windows, when switching from line to raw mode:
- Cancel ongoing console read by writing a return keypress to its input buffer. This blocks the main thread until any ongoing read has been cancelled to prevent interference with the screen state.
- On the read thread, restore the cursor position to where it was before writing the enter, undoing its effect on the screen state.
- Restart reading and notify the main thread.

### CODE REVIEW

**Review by satyarohith — COMMENTED** [review]
I don't have a Windows machine to test the change. I'll let David review the PR.

**Review by bartlomieju — COMMENTED** [review]
Overall, looks good to me. Nice that there's a test. @dsherret can you try it out on your machine and see if it fixes the problem at hand?

File: ext/io/lib.rs [hunk 1]
```diff
@@ -736,19 +767,97 @@ impl crate::fs::File for StdFileResourceInner {
...
-        let nread = file.read(&mut buf)?;
-        Ok((nread, buf))
-      })
-      .await
+    match &self.kind {
+      /* On Windows, we need to handle special read cancellation logic for stdin */
+      #[cfg(windows)]
+      StdFileResourceKind::Stdin(state) => {
+        loop {
+          let state = state.clone();
```
Comment (bartlomieju) [inline ext/io/lib.rs:775]: Consider factoring out to separate functions that would be conditionally compiled to improve readability.

File: ext/io/lib.rs [hunk 2]
```diff
@@ -317,14 +333,29 @@ impl Resource for ChildStderrResource {
   }
 }
 
-#[derive(Clone, Copy)]
+#[cfg(windows)]
+use winapi::um::wincon::CONSOLE_SCREEN_BUFFER_INFO;
```
Comment (dsherret) [inline ext/io/lib.rs:337]: Nitpick: It's probably just better to inline these if there's only one used rather than using conditional compilation for them.

File: ext/io/lib.rs [hunk 3]
```diff
@@ -48,6 +48,13 @@ use winapi::um::processenv::GetStdHandle;
 #[cfg(windows)]
 use winapi::um::winbase;
 
+#[cfg(windows)]
+use std::sync::Arc;
+#[cfg(windows)]
+use std::sync::Condvar;
+#[cfg(windows)]
+use std::sync::Mutex;
```
Comment (dsherret) [inline ext/io/lib.rs:56]: Use parking_lot::Mutex and parking_lot::Condvar to avoid unwraps? Doesn't look like poisoning is done here.

File: ext/io/lib.rs [hunk 4]
```diff
@@ -736,19 +767,97 @@ impl crate::fs::File for StdFileResourceInner {
...
+    match &self.kind {
+      /* On Windows, we need to handle special read cancellation logic for stdin */
+      #[cfg(windows)]
+      StdFileResourceKind::Stdin(state) => {
+        loop {
+          let state = state.clone();
+
+          let fut = self.with_inner_blocking_task(move |file| {
+            /* Start reading, and set the reading flag to true */
+            state.lock().unwrap().reading = true;
```
Comment (dsherret) [inline ext/io/lib.rs:779]: Is a flag sufficient? Could multiple threads be in here at once?

File: ext/io/lib.rs [hunk 5]
```diff
@@ -736,19 +767,97 @@ impl crate::fs::File for StdFileResourceInner {
...
+              }
+
+              /* Reset the cancelled flag */
+              state.cancelled = false;
+
+              /* Unblock the main thread */
+              state.cvar.notify_one();
+
+              return Err((FsError::FileBusy, buf));
+            }
```
Comment (dsherret) [inline ext/io/lib.rs:831]: If the else condition happens `state.cancelled` won't be set to false and the conditional var not notified. Is that ok?

**Review by dsherret — APPROVED** [review]
LGTM

File: ext/io/lib.rs (hunk 4 above)
Comment (littledivy) [reply ext/io/lib.rs:777]: Yeah, there may be multiple threads in here at once. The reading flag tells tty mode changes to issue read cancellation before proceeding

**Comment by littledivy** [comment]
> Best you can do is try it in practice and see that it works OK most of the time. 

Node v Deno comparision for some packages:

`create-next-app`

https://github.com/denoland/deno/assets/34997667/6c5a6dea-b3ab-4f98-9d0d-b26a057ab13f

`crate-solid`

https://github.com/denoland/deno/assets/34997667/7d923367-537d-4990-8b43-c3f422c87bb4

`create-vite`:

https://github.com/denoland/deno/assets/34997667/891368d3-4376-4e17-b4c0-06824e96cb90

Seems to work most of the time :)

**Comment by littledivy** [comment]
> Best you can do is try it in practice and see that it works OK most of the time. 

Node v Deno comparision for some packages:

`create-next-app`

https://github.com/denoland/deno/assets/34997667/6c5a6dea-b3ab-4f98-9d0d-b26a057ab13f

`crate-solid`


https://github.com/denoland/deno/assets/34997667/5cf7722f-7cbf-4eba-bdc7-2cbc327f59af

`create-vite`:


https://github.com/denoland/deno/assets/34997667/1d51358a-2ef6-4ddb-900c-45dfb5860bab



Seems to work most of the time :)

**Review by dsherret — APPROVED** [review]
LGTM
