### PR TITLE
fix(npm): improved optional dependency support

### LINKED ISSUE #15544: npm: imports cause unnecessary download
```
../deno/target/debug/deno run -A --unstable --reload npm:vite build
Download https://registry.npmjs.org/vite
Download https://registry.npmjs.org/esbuild
Download https://registry.npmjs.org/fsevents
Download https://registry.npmjs.org/postcss
Download https://registry.npmjs.org/resolve
Download https://registry.npmjs.org/rollup
Download https://registry.npmjs.org/@esbuild/linux-loong64
Download https://registry.npmjs.org/esbuild-android-64
Download https://registry.npmjs.org/esbuild-android-arm64
Download https://registry.npmjs.org/esbuild-darwin-64
Download https://registry.npmjs.org/esbuild-darwin-arm64
Download https://registry.npmjs.org/esbuild-freebsd-64
Download https://registry.npmjs.org/esbuild-freebsd-arm64
Download https://registry.npmjs.org/esbuild-linux-32
Download https://registry.npmjs.org/esbuild-linux-64
Download https://registry.npmjs.org/esbuild-linux-arm
Download https://registry.npmjs.org/esbuild-linux-arm64
Download https://registry.npmjs.org/esbuild-linux-mips64le
Download https://registry.npmjs.org/esbuild-linux-ppc64le
Download https://registry.npmjs.org/esbuild-linux-riscv64
Download https://registry.npmjs.org/esbuild-linux-s390x
Download https://registry.npmjs.org/esbuild-netbsd-64
Download https://registry.npmjs.org/esbuild-openbsd-64
Download https://registry.npmjs.org/esbuild-sunos-64
Download https://registry.npmjs.org/esbuild-windows-32
Download https://registry.npmjs.org/esbuild-windows-64
Download https://registry.npmjs.org/esbuild-windows-arm64
Download https://registry.npmjs.org/nanoid
Download https://registry.npmjs.org/picocolors
Download https://registry.npmjs.org/source-map-js
Download https://registry.npmjs.org/is-core-module
Download https://registry.npmjs.org/path-parse
Download https://registry.npmjs.org/supports-preserve-symlinks-flag
Download https://registry.npmjs.org/has
Download https://registry.npmjs.org/function-bind
```
There's no reason to download binaries for all available platforms when `esbuild` is a dependency

### PR DESCRIPTION
**Pull request by dsherret**
Note: If the package information has already been cached, then this requires running with `--reload` or for the registry information to be fetched some other way (ex. the cache busting).

Closes #15544

### CODE REVIEW

File: cli/npm/resolvers/common.rs [hunk 1]
```diff
@@ -69,7 +69,6 @@ pub async fn cache_packages(
 
   let mut handles = Vec::with_capacity(packages.len());
   for package in packages {
-    assert_eq!(package.copy_index, 0); // the caller should not provide any of these
```
Comment (dsherret) [inline cli/npm/resolvers/common.rs:72]: This is not the case anymore, since a `copy_index > 1` might be the non-copy package now if the main `copy_index == 0` was not available for this system.

File: cli/args/mod.rs [hunk 2]
```diff
@@ -688,6 +689,42 @@ impl CliOptions {
...
+  pub fn npm_system_info(&self) -> NpmSystemInfo {
+    match self.sub_command() {
+      DenoSubcommand::Compile(CompileFlags {
+        target: Some(target),
+        ..
+      }) => {
+        // the values of NpmSystemInfo align with the possible values for the
+        // `arch` and `platform` fields of Node.js' `process` global:
+        // https://nodejs.org/api/process.html
+        match target.as_str() {
```
Comment (bartlomieju) [inline cli/args/mod.rs:701]: Very nice!

**Review by bartlomieju — APPROVED** [review]
LGTM! It's great to have this fixed, thank you David
