### PR TITLE
fix(ext/web): Prevent TextDecoderStream resource leak on stream cancellation

### LINKED ISSUE #13142: TextDecoderStream leaks a native decoder resource if its stream errors
I've come across what seems to be a bug in `TextDecoderStream` which allows it to leak the native decoder used by its `TextDecoder`.

I've made a test module to demonstrate the issue (repro code is at the bottom of that page, under the output): https://gist.github.com/h4l/0199ab7cc24dd13536e01c5ea98b3ae7
The 3 tests trigger the test runner's resource leak detection (a really nice feature!).

What seems to be happening is:
- `TextDecoderStream` uses a `TextDecoder` to decode its chunks
- `TextDecoder.decode()` creates a native decoder resource, which it holds open when used in streaming mode. It closes the resource when a non-streaming `decode()` call is made.
- `TextDecoderStream` makes streaming `decode()` calls in its `transform()` method, and makes a final non-streaming `decode()` call in its `flush()` method.
- When a stream pipeline is errored, the `flush()` method of any `Transformer` in a `TransformStream` is not called, so in the case of `TextDecoderStream` it has no way to know its no longer in use, and keeps open its decoder.

I was looking through the [streams spec](https://streams.spec.whatwg.org/) when I encountered the leak (before I worked out the cause) to try to work out if I was misusing the streams in some way. It seems to me like an oversight in the spec that `Transformer`s have no way to be told to close/clean up when a stream doesn't close cleanly. `flush()` is only called when the stream closes normally if I've not missed something, and there are no other lifecycle methods available for `Transformer`s.

I can't see any idiomatic way to tell the `Transformer` to close, but one approach could be to wrap the readable and writable streams of the `TransformerStream` to watch for `close`/`cancel`/`abort` calls.

I've not made any previous contributions, but I'd be happy to help with a PR to fix this if it'd be useful.

### PR DESCRIPTION
**Pull request by egfx-notifications**
This PR uses the new `cancel` method of `TransformStream` to properly clean up the internal `TextDecoder` used in `TextDecoderStream` if the stream is cancelled.

Fixes #13142

### CODE REVIEW

**Comment by mmastrac** [comment]
Could you add a test case for this?

This should be sufficient (it'll trigger the resource sanitizer for tests):

```
new TextDecoder('utf8').decode(new Uint8Array(), { stream: true });
```

**Comment by egfx-notifications** [comment]
> Could you add a test case for this?

I can, though I'm not satisfied with the fix yet as this recreates the internal decoder resource for every chunk of the stream. I'm going to look further into the root cause of this, hence the draft status of the PR. I will update this PR and add a test once I have (hopefully) come up with a better solution.

From what I've found out so far the problem is that the decoder from `encoding_rs` requires a final call of a `decode_*` function with the `last` argument set to `true`. The deno `TextDecoder` provides the `last` argument as the negated value of the `stream` option, so we have to call `TextDecoder.decode()` at least once without the `stream` option to free the resource. This is what `TextDecoderStream` does in its `flush` method, I'm yet to find the proper way of handling this for an aborted async iterator.

**Comment by crowlKats** [comment]
@egfx-notifications FYI as of recently, there is a `TransformStream` `cancel` option (#20741)

**Comment by egfx-notifications** [comment]
> @egfx-notifications FYI as of recently, there is a `TransformStream` `cancel` option (#20741)

Thank you! That saved me quite some time.

I just pushed a version using the `cancel` option and it works fine for my test case. Feel free to have a look, this is my first deep dive into deno code, so I may be missing something.

I'm going to test this properly and also add a minimal test case sometime next week. The test case suggested by @mmastrac is a bit too minimal as I consider the problem to be a cancelled stream not cleaning up its internal resources. Explicitly calling `TextDecoder.decode()` with the `stream` option without actually using it in a stream is not a case I want to solve, especially as the `deno test` output already mentions how to close the TextDecoder resource properly.

File: ext/web/08_text_encoding.js [hunk 1]
```diff
@@ -301,6 +301,14 @@ class TextDecoderStream {
...
         }
       },
+      cancel: (_reason) => {
+        try {
+          const _ = this.#decoder.decode();
+          return PromiseResolve();
+        } catch (err) {
+          return PromiseReject(err);
+        }
+      },
```
Comment (mmastrac) [inline ext/web/08_text_encoding.js:311]: I believe something like this can be used to simplify the construction:

```suggestion
      cancel: async (_reason) => {
        const _ = this.#decoder.decode();
      },
```

File: cli/tests/unit/text_encoding_test.ts [hunk 2]
```diff
@@ -319,3 +319,20 @@ Deno.test(function binaryEncode() {
...
 });
+
+Deno.test(
+  { permissions: { read: true } },
+  async function textDecoderStreamCleansUpOnCancel() {
+    const filename = "cli/tests/testdata/assets/hello.txt";
+    const file = await Deno.open(filename);
+    const readable = file.readable.pipeThrough(new TextDecoderStream());
+    const chunks = [];
+    for await (const chunk of readable) {
```
Comment (mmastrac) [inline cli/tests/unit/text_encoding_test.ts:330]: Great test, thanks

File: ext/web/08_text_encoding.js (hunk 1 above)
Comment (mmastrac) [reply ext/web/08_text_encoding.js:311]: I see that this entire class is using the other style -- I'm not sure why so let's leave as-is. This is probably a good follow-up issue. I'll merge it!

**Review by mmastrac — APPROVED** [review]

File: ext/web/08_text_encoding.js (hunk 1 above)
Comment (egfx-notifications) [reply ext/web/08_text_encoding.js:311]: Yes, I tried to follow the existing style. Not sure why it is preferred here, though.

**Comment by mmastrac** [comment]
This is causing a test flake:

```
[text_encoding_test 001.57] textDecoderStreamCleansUpOnCancel => ./cli/tests/unit/text_encoding_test.ts:323:6
[text_encoding_test 001.57] error: Leaking async ops:
[text_encoding_test 001.57]   - 1 async operation to op_read was started in this test, but never completed.
[text_encoding_test 001.57] To get more details where ops were leaked, run again with --trace-ops flag.
```

**Comment by egfx-notifications** [comment]
Yeah, just noticed this as well. Thanks for the fixed test. I was going to suggest deferring the sanitizers as suggested [here](https://github.com/denoland/deno/issues/15425#issuecomment-1368245954), but your fix seems cleaner.
