### PR TITLE
fix(cli): import maps handles data URLs

### LINKED ISSUE #9420: data url is not working with `--import-map` option
```ts
// main.ts

const a = await import("data:application/typescript;base64,ZXhwb3J0IGNvbnN0IGEgPSAiYSI7CgpleHBvcnQgZW51bSBBIHsKICBBLAogIEIsCiAgQywKfQo=")
console.log(a.a)
```

with an empty `import-map.json`

```json
{}
```

my **command** is `deno run --unstable --import-map=import-map.json main.ts`, then i got the an error:

> error: Uncaught (in promise) TypeError: Unmapped bare specifier "data:application/typescript;base64,ZXhwb3J0IGNvbnN0IGEgPSAiYSI7CgpleHBvcnQgZW51bSBBIHsKICBBLAogIEIsCiAgQywKfQo="

without import maps can work fine: `deno run main.ts`
> a

_

deno **1.7.2** (release, x86_64-apple-darwin)

### PR DESCRIPTION
**Pull request by kitsonk**
Fixes #9420

### CODE REVIEW

**Review by kt3k — APPROVED** [review]
LGTM

File: cli/import_map.rs [hunk 1]
```diff
@@ -36,7 +36,7 @@ impl Error for ImportMapError {}
 
 // NOTE: here is difference between deno and reference implementation - deno currently
 //  can't resolve URL with other schemes (eg. data:, about:, blob:)
```
Comment (bartlomieju) [inline cli/import_map.rs:38]: remove `data:` from parens

**Review by bartlomieju — APPROVED** [review]
LGTM
