### PR TITLE
fix(ext/node): parse fs open options correctly

### LINKED ISSUE #30299: `node:fs` `open` and `openSync` always enables read permission
The `O_RDONLY` constant has a value of 0, thus this operation will always enable the read permission, even though maybe the user only want a `O_WRONLY` (write only) permission:

https://github.com/denoland/deno/blob/c86e277fc1e0795f3602981e36c690e1abfbfe49/ext/node/polyfills/_fs/_fs_common.ts#L162-L165

This code works in Deno (both 2.4.3 and main branch) but fails in Node.js:
```js
import { constants, openSync, readSync,  writeSync } from "node:fs";
import { Buffer } from "node:buffer";
const { O_WRONLY } = constants;

const main = () => {
    const fd = openSync("test.txt", O_WRONLY);
    writeSync(fd, "Hello, world!");
    const buffer = Buffer.alloc(13);
    readSync(fd, buffer, 0, 13, 0); // Node.js will throw here
    console.log(buffer.toString());
}

main();
```

### PR DESCRIPTION
**Pull request by Tango992**
Fixes #30299 

I decided to build the `OpenOptions` on the Rust side, because it's cheaper to pass integers to the op function and we can enable the fast op call. Also the tests that I added to the `config.toml` were already passing before this PR.

### CODE REVIEW

File: ext/node/ops/fs.rs [hunk 1]
```diff
@@ -138,6 +138,55 @@ where
...
+  }
+  if (flags & libc::O_CREAT) == libc::O_CREAT {
+    options.create = true;
+    flags &= !libc::O_CREAT;
+  }
+  if (flags & libc::O_EXCL) == libc::O_EXCL {
+    options.create_new = true;
+    options.write = true;
+    flags &= !libc::O_EXCL;
+  }
```
Comment (Tango992) [inline ext/node/ops/fs.rs:159]: Here's the current logic from Deno 2.4.3: 
https://github.com/denoland/deno/blob/5612d2edc7262d7bfb3bcfb0f18649b01ec94b53/ext/node/polyfills/_fs/_fs_common.ts#L222-L226

I intentionally omitted the read permission as the Rust stdlib only requires write permission when chained with `create_new`:
https://doc.rust-lang.org/src/std/sys/fs/unix.rs.html#1118-1152
