### PR TITLE
fix: `Deno.Command` - improve error message when `cwd` is not a directory

### LINKED ISSUE #20351: `Deno.Command` error message for non-existent `cwd` is misleading
Deno 1.36.3

```
> new Deno.Command("/bin/sh", { cwd: "/nonexistent" }).spawn()
Uncaught NotFound: Failed to spawn: /bin/sh: No such file or directory (os error 2)
    at spawnChildInner (ext:runtime/40_process.js:162:17)
    at spawnChild (ext:runtime/40_process.js:182:10)
    at Command.spawn (ext:runtime/40_process.js:440:12)
    at <anonymous>:4:4
```

To a naive reading, the error message seems to imply that `/bin/sh` doesn't exist, and either way it has no indication that the `cwd` is the problem.

### PR DESCRIPTION
**Pull request by shreyass-ranganatha**
Fixes #20351 with checks for the path and its type.

Raises a `AnyError` if either the path doesn't exist OR if the path is NOT a directory

image

### CODE REVIEW

**Review by bartlomieju — COMMENTED** [review]
Thanks, can you add some tests to `cli/tests/unit/command_test.ts`?

File: runtime/ops/process.rs [hunk 1]
```diff
@@ -227,6 +227,20 @@ fn create_command(
...
+          "The runtime path '{}' is not a directory.",
+          cwd.clone()
+        )));
+      }
+    } else {
+      return Err::<std::process::Command, _>(AnyError::msg(format!(
+        "Unable to access the runtime path '{}'.",
+        cwd.clone()
+      )));
+    }
```
Comment (dsherret) [inline runtime/ops/process.rs:242]: This will increase the amount of time it takes to launch a command. Instead, perhaps we should check if the cwd exists on a `NotFound` error?

Comment (strawsnoceans) [reply runtime/ops/process.rs:242]: but wouldn't that be ambiguous regarding whether it's the command or the directory NotFound ?

Comment (dsherret) [reply runtime/ops/process.rs:242]: We could just always surface the cwd error when the cwd doesn't exist on a `NotFound` error. It would be almost essentially the same as this code.

File: runtime/ops/process.rs [hunk 2]
```diff
@@ -227,6 +227,20 @@ fn create_command(
   command.args(args.args);
 
   if let Some(cwd) = args.cwd {
+    if let Ok(cwd_metadata) = std::fs::metadata(cwd.clone()) {
+      if !cwd_metadata.is_dir() {
+        return Err::<std::process::Command, _>(AnyError::msg(format!(
```
Comment (dsherret) [inline runtime/ops/process.rs:232]: When adding a test, we should ensure that it still maintains the existing error class. I believe it's `Deno.errors.NotFound` (I think this could be maintained by instead just adding to the error message of the `std::io::Error`, but I'm not sure).

**Comment by strawsnoceans** [comment]
^I've incorporated all the changes including the required test cases

File: cli/tests/unit/command_test.ts [hunk 3]
```diff
@@ -424,6 +424,26 @@ Deno.test({ permissions: { run: true } }, function commandSyncNotFound() {
   );
 });
 
+Deno.test({ permissions: { run: true } }, function cwdNotFound() {
+  assertThrows(
+    () => new Deno.Command("ls", {
+      cwd: "/sadsa"
+    }).output(),
+    Deno.errors.NotFound,
+    "Can't find cwd path `/sadsa`: No such file or directory (os error 2)"
```
Comment (dsherret) [inline cli/tests/unit/command_test.ts:433]: I'm not sure the message will be the same on every operating system and it might be good to test a path that would work on windows. So for example, we could use use `Deno.cwd() + "/non-existent-path"` and then just check that the error message contains "non-existent-path".

File: cli/tests/unit/command_test.ts [hunk 4]
```diff
@@ -424,6 +424,26 @@ Deno.test({ permissions: { run: true } }, function commandSyncNotFound() {
   );
 });
 
+Deno.test({ permissions: { run: true } }, function cwdNotFound() {
+  assertThrows(
+    () => new Deno.Command("ls", {
```
Comment (dsherret) [inline cli/tests/unit/command_test.ts:429]: The `ls` command won't exist on windows. Might be better to use `curl`.

Comment (shreyass-ranganatha) [reply cli/tests/unit/command_test.ts:429]: How about using `Demo.execPath()` I've noticed most of the tests are using just that

File: cli/tests/unit/command_test.ts (hunk 3 above)
Comment (shreyass-ranganatha) [reply cli/tests/unit/command_test.ts:433]: Wouldn't it be better to do a check for only "Not a directory" or "No such file or directory" instead of the path name

Comment (dsherret) [reply cli/tests/unit/command_test.ts:433]: Each operating system has a slightly different message and Windows uses backslashes in paths. This is already checking for `Deno.errors.NotFound` so that's probably good enough in addition to just the filename

File: cli/tests/unit/command_test.ts (hunk 4 above)
Comment (dsherret) [reply cli/tests/unit/command_test.ts:429]: Sure.

File: cli/tests/unit/command_test.ts (hunk 3 above)
Comment (shreyass-ranganatha) [reply cli/tests/unit/command_test.ts:433]: Okay, I'll add the filename + this message

**Comment by shreyass-ranganatha** [comment]
been missing out on the basics, sorry

I've formatted the file, and I think the lint errors should stop now

File: runtime/ops/process.rs [hunk 5]
```diff
@@ -287,10 +287,22 @@ fn spawn_child(
...
   let mut child = command.spawn().with_context(|| {
-    format!(
-      "Failed to spawn: {}",
-      command.as_std().get_program().to_string_lossy()
-    )
+    let mut _cmd = command.as_std();
+
+    if let Some(cwd) = _cmd.get_current_dir() {
+      if !cwd.exists() {
+        return format!("Can't find cwd path `{}`", cwd.to_string_lossy());
```
Comment (dsherret) [inline runtime/ops/process.rs:294]:
```suggestion
        return format!("Can't find cwd path '{}'", cwd.to_string_lossy());
```

File: runtime/ops/process.rs [hunk 6]
```diff
@@ -287,10 +287,22 @@ fn spawn_child(
...
+      }
+
+      if !cwd.is_dir() {
+        return format!(
+          "cwd path is not a directory `{}`",
```
Comment (dsherret) [inline runtime/ops/process.rs:299]:
```suggestion
          "cwd path is not a directory '{}'",
```

File: cli/tests/unit/command_test.ts [hunk 7]
```diff
@@ -424,6 +424,28 @@ Deno.test({ permissions: { run: true } }, function commandSyncNotFound() {
...
+});
+
+Deno.test({ permissions: { run: true } }, function cwdNotDirectory() {
+  assertThrows(
+    () =>
+      new Deno.Command(Deno.execPath(), {
+        cwd: Deno.execPath(),
+      }).output(),
+    Deno.errors.NotFound,
+    `cwd path is not a directory \`${Deno.execPath()}\`: Not a directory`,
```
Comment (dsherret) [inline cli/tests/unit/command_test.ts:445]:
```suggestion
    `cwd path is not a directory '${Deno.execPath()}': Not a directory`,
```

File: cli/tests/unit/command_test.ts [hunk 8]
```diff
@@ -424,6 +424,28 @@ Deno.test({ permissions: { run: true } }, function commandSyncNotFound() {
...
 });
 
+Deno.test({ permissions: { run: true } }, function cwdNotFound() {
+  assertThrows(
+    () =>
+      new Deno.Command(Deno.execPath(), {
+        cwd: Deno.cwd() + "/non-existent-directory",
+      }).output(),
+    Deno.errors.NotFound,
+    "non-existent-directory\`: No such file or directory",
```
Comment (dsherret) [inline cli/tests/unit/command_test.ts:434]:
```suggestion
    "non-existent-directory': No such file or directory",
```

File: cli/tests/unit/command_test.ts [hunk 9]
```diff
@@ -424,6 +424,28 @@ Deno.test({ permissions: { run: true } }, function commandSyncNotFound() {
...
+});
+
+Deno.test({ permissions: { run: true } }, function cwdNotDirectory() {
+  assertThrows(
+    () =>
+      new Deno.Command(Deno.execPath(), {
+        cwd: Deno.execPath(),
+      }).output(),
+    Deno.errors.NotFound,
+    `cwd path is not a directory '${Deno.execPath()}': Not a directory`,
```
Comment (dsherret) [inline cli/tests/unit/command_test.ts:445]:
```suggestion
    `cwd path is not a directory '${Deno.execPath()}':`,
```

This will fail on windows.

**Review by dsherret — APPROVED** [review]
LGTM. Thanks!

**Comment by dsherret** [comment]
I'll fix the linting errors.

**Comment by shreyass-ranganatha** [comment]
Ah crap, I think I just undid a few changes, it lacked a permission read: true

**Comment by dsherret** [comment]
@shreyass-ranganatha the ci will fail again because the force pushing you did overwrote my fixes. I'm going to force push to add back the changes and then re-apply your latest commit.

**Comment by shreyass-ranganatha** [comment]
Thank you so much for helping through the screw ups @dsherret

**Comment by dsherret** [comment]
@shreyass-ranganatha that's ok! I think it will fail again for other reasons. I'm looking into it right now so we can get this merged.
