### PR TITLE
fix(node): implement libuv APIs needed to support `npm:sqlite3`

### LINKED ISSUE #24740: Bug: dyld[3532]: missing symbol called in `sqlite3`
## Steps to reproduce

1. Run `deno init`
2. Set `vendor: true` in `deno.json`
3. Run `deno install --allow-scripts npm:sqlite3`
4. Add `main.ts` with these contents:
  ```ts
  import sqlite3Init from "npm:sqlite3";
  
  const sqlite3 = sqlite3Init.verbose();
  const db = new sqlite3.Database(":memory:");
  
  db.serialize(() => {
    db.run("CREATE TABLE lorem (info TEXT)");
  
    const stmt = db.prepare("INSERT INTO lorem VALUES (?)");
    for (let i = 0; i < 10; i++) {
      stmt.run("Ipsum " + i);
    }
    stmt.finalize();
  
    db.each("SELECT rowid AS id, info FROM lorem", (err, row) => {
      console.log(row.id + ": " + row.info);
    });
  });
  
  db.close();
  ```
5. Run `DENO_FUTURE=1 deno run -A main.ts`

Output:

```sh
$ DENO_FUTURE=1 deno run -A main.ts
dyld[3532]: missing symbol called
[1]    3532 abort      DENO_FUTURE=1 deno run -A 
```

Version: Deno 1.45.3 (git https://github.com/denoland/deno/commit/7776636c2efc3db07b965166a9982fc3d5ef21ce 2024-07-26)

### PR DESCRIPTION
**Pull request by nathanwhit**
Fixes #24740.

Implements the `uv_mutex_*` and `uv_async_*` APIs.

The mutex API is implemented exactly as libuv, a thin wrapper over the OS's native mutex.

The async API is implemented in terms of napi_async_work. As documented in the napi docs, you really shouldn't call `napi_queue_async_work` multiple times (it is documented as undefined behavior). However, our implementation doesn't have any issue with this, so I believe it suits our purpose here.

### CODE REVIEW

File: cli/napi/uv.rs [hunk 1]
```diff
@@ -0,0 +1,237 @@
...
+      if libc::EDOM > 0 {
+        err
+      } else {
+        -err
+      }
+    }
+  }
+
+  #[no_mangle]
+  unsafe extern "C" fn uv_mutex_lock(lock: *mut uv_mutex_t) {
```
Comment (devsnek) [inline cli/napi/uv.rs:51]: these could be written in terms of `std::sync::Mutex` and gain safety and platform compat.

File: cli/napi/node_api.rs [hunk 2]
```diff
@@ -547,11 +547,16 @@ fn napi_delete_async_work(env: *mut Env, work: napi_async_work) -> napi_status {
...
+  uv_loop: *mut *mut (),
+) -> napi_status {
+  let env = check_env!(env_ptr);
   check_arg!(env, uv_loop);
-  // There is no uv_loop in Deno
-  napi_set_last_error(env, napi_generic_failure)
+  unsafe {
+    *uv_loop = env_ptr.cast();
+  }
+  0
```
Comment (devsnek) [inline cli/napi/node_api.rs:559]: i worry slightly that by allowing node-api modules to progress beyond calling this function, we may see an increase in reports of symbol resolution crashes that were previously just runtime errors.

File: cli/napi/uv.rs [hunk 3]
```diff
@@ -0,0 +1,237 @@
...
+  work: napi_async_work,
+  _padding: [MaybeUninit<u8>; const {
+    UV_ASYNC_SIZE
+      - size_of::<*mut c_void>()
+      - size_of::<*mut uv_loop_t>()
+      - size_of::<uv_handle_type>()
+      - size_of::<uv_async_cb>()
+      - size_of::<napi_async_work>()
+  }],
+}
```
Comment (devsnek) [inline cli/napi/uv.rs:172]: maybe add smth like this just to be sure.
```rs
const _: () = assert!(std::mem::size_of::<uv_async_t>() == UV_ASYNC_SIZE)
```
or maybe a test which compares it to the `uv_sys_lite` type?

File: cli/napi/uv.rs (hunk 1 above)
Comment (nathanwhit) [reply cli/napi/uv.rs]: Done, though I went with `parking_lot::Mutex` instead to avoid having to store the guard with a fake lifetime.

File: cli/napi/uv.rs (hunk 3 above)
Comment (nathanwhit) [reply cli/napi/uv.rs:144]: Done

File: cli/napi/uv.rs [hunk 4]
```diff
@@ -0,0 +1,231 @@
...
+      r#async.cast(),
+      addr_of_mut!((*r#async).work),
+    );
+    -res
+  }
+}
+
+#[no_mangle]
+unsafe extern "C" fn uv_async_send(handle: *mut uv_async_t) -> c_int {
+  unsafe { -napi_queue_async_work((*handle).r#loop, (*handle).work) }
```
Comment (littledivy) [inline cli/napi/uv.rs:182]: nit: second unsafe block is redundant. Ditto everywhere else.

Comment (nathanwhit) [reply cli/napi/uv.rs:182]: The `unsafe_op_in_unsafe_fn` lint is going to be [warn by default soon](https://doc.rust-lang.org/edition-guide/rust-2024/unsafe-op-in-unsafe-fn.html), and we actually deny that lint elsewhere in napi: https://github.com/denoland/deno/blob/05ca6994ca36a152b793654e7c631271b6280521/cli/napi/node_api.rs#L3

Comment (littledivy) [reply cli/napi/uv.rs:182]: ah interesting

**Review by littledivy — APPROVED** [review]
LGTM
