### PR TITLE
fix(upgrade): do not error if config in cwd invalid

### LINKED ISSUE #20729: `deno upgrade` fails if lockfile cannot be parsed
We shouldn't surface lockfile errors for `deno upgrade`. I'm not sure how difficult this is to fix though (probably we should resolve the lockfile lazily).

```
$ deno upgrade
 error: Unable to parse contents of lockfile: "/.../deno.lock"
```

### LINKED ISSUE #24517: `deno upgrade` fails in broken workspace setting in v1.45
Version: Deno v1.45.0

```
$ deno upgrade
error: Could not find package.json for workspace member in 'file:///Users/ib/dev/deno_workspace_examples/buzz/'.
```

Reproduction: https://github.com/bartlomieju/broken_deno_upgrade_in_workspace

### PR DESCRIPTION
**Pull request by dsherret**
```
> deno upgrade
error: Unsupported lockfile version 'invalid'. Try upgrading Deno or recreating the lockfile.
V:\scratch
> V:\deno\target\debug\deno upgrade
Looking up latest version
Local deno version 1.45.3 is the most recent release
```

Closes #24517
Closes #20729

### CODE REVIEW

File: cli/args/lockfile.rs [hunk 1]
```diff
@@ -93,6 +98,35 @@ impl CliLockfile {
     flags: &Flags,
     workspace: &Workspace,
   ) -> Result<Option<CliLockfile>, AnyError> {
+    fn pkg_json_deps(maybe_pkg_json: Option<&PackageJson>) -> BTreeSet<String> {
```
Comment (dsherret) [inline cli/args/lockfile.rs:101]: Moved from cli/factory.rs

**Review by bartlomieju — APPROVED** [review]
LGTM
