### PR TITLE
fix(lsp): allow formatting vendor files

### LINKED ISSUE #20308: Bug: Unable to format vendored files
Formatting a file that is vendored via `vendor: true` in the deno config file leads to an error.

Screenshot 2023-08-28 at 12 35 06

## Steps to reproduce

1. Clone https://github.com/marvinhagemeister/deno-format-vendor
2. Open `vendor/esm.sh/v124/@twind/core@1.1.3/deno/core.mjs`
3. Open command palette (CMD+Shift+P on macOS or CTRL+Shift+P on other OS'es) and select `Format document with...` -> `Deno`

Alternatively run `deno fmt ./vendor/esm.sh/v124/@twind/core@1.1.3/deno/core.mjs`.

## Output

```sh
Invalid file path.
  Specifier: https://esm.sh/v124/@twind/core@1.1.3/deno/core.mjs
```

### PR DESCRIPTION
**Pull request by nayeemrmn**
Fixes #20308.

### CODE REVIEW

File: cli/lsp/language_server.rs
Comment (dsherret) [inline cli/lsp/language_server.rs:1]: Does `deno fmt ./vendor/esm.sh/v124/@twind/core@1.1.3/deno/core.mjs` from the issue work? I think maybe this doesn't close the issue entirely?

File: cli/lsp/language_server.rs [hunk 1]
```diff
@@ -1632,23 +1632,30 @@ impl Inner {
     &self,
     params: DocumentFormattingParams,
   ) -> LspResult<Option<Vec<TextEdit>>> {
-    let specifier = self
+    let mut specifier = self
       .url_map
       .normalize_url(&params.text_document.uri, LspUrlKind::File);
+    // skip formatting any files ignored by the config file
+    if !self.fmt_options.files.matches_specifier(&specifier) {
```
Comment (dsherret) [inline cli/lsp/language_server.rs:1639]: If someone ignores something in the vendor folder, will this also skip those files? I think probably not. Maybe it should?

**Review by dsherret — APPROVED** [review]
LGTM with some caveats.

File: cli/lsp/language_server.rs (hunk 1 above)
Comment (nayeemrmn) [reply cli/lsp/language_server.rs:1639]: Currently `vendor` isn't applicable to config exclusion checks because it's excluded by default. We should remove https://github.com/denoland/deno_config/blob/0.4.0/src/lib.rs#L688-L690 for a start. It shouldn't be handled there.

**Comment by nayeemrmn** [comment]
We should change our fmt config exclusion check to only apply to automatic discovery such as `deno fmt <encompassing-dir>` and `formatOnSave` (though we can't detect that one unfortunately).

**Comment by nayeemrmn** [comment]
I'm gonna land this for now and open more targeted issues for the remainders
