### PR TITLE
fix(fetch): Fetch bad URL will not panic!

### LINKED ISSUE #8880: Rust panic after fetching invalid URLs
Just fetch a really incorrect URL, e.g. `fetch('http://<nil>/')`. That fetch should cause an error, but not panic.

Tested on Deno 1.6.1 and Deno 1.6.2.

When done with top level REPL await as shown below, it actually causes a double panic! But in the application that this error first happened in, it was just the first panic.

```
$ env RUST_BACKTRACE=full deno
Deno 1.6.1
exit using ctrl+d or close()
> await fetch('http://<nil>/')
thread 'main' panicked at 'a parsed Url should always be a valid Uri: InvalidUri(InvalidUriChar)', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/reqwest-0.10.8/src/into_url.rs:44:14
stack backtrace:
   0:     0x560dc98810b3 - std::backtrace_rs::backtrace::libunwind::trace::h72c2fb8038f1bbee
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/../../backtrace/src/backtrace/libunwind.rs:96
   1:     0x560dc98810b3 - std::backtrace_rs::backtrace::trace_unsynchronized::h1e3b084883f1e78c
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/../../backtrace/src/backtrace/mod.rs:66
   2:     0x560dc98810b3 - std::sys_common::backtrace::_print_fmt::h3bf6a7ebf7f0394a
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:79
   3:     0x560dc98810b3 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h2e8cb764b7fe02e7
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:58
   4:     0x560dc940972c - core::fmt::write::h7a1184eaee6a8644
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/fmt/mod.rs:1080
   5:     0x560dc98808a1 - std::io::Write::write_fmt::haeeb374d93a67eac
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/io/mod.rs:1516
   6:     0x560dc98801a5 - std::sys_common::backtrace::_print::h1d14a7f6ad632dc8
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:61
   7:     0x560dc98801a5 - std::sys_common::backtrace::print::h301abac8bb2e3e81
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:48
   8:     0x560dc98801a5 - std::panicking::default_hook::{{closure}}::hde0cb80358a6920a
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:208
   9:     0x560dc98801a5 - std::panicking::default_hook::h9b1a691049a0ec8f
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:227
  10:     0x560dc98801a5 - std::panicking::rust_panic_with_hook::h2bdec87b60580584
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:577
  11:     0x560dc989a2b8 - std::panicking::begin_panic_handler::{{closure}}::h101ca09d9df5db47
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:484
  12:     0x560dc989a284 - std::sys_common::backtrace::__rust_end_short_backtrace::h3bb85654c20113ca
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:153
  13:     0x560dc989a23d - rust_begin_unwind
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:483
  14:     0x560dc9406d20 - core::panicking::panic_fmt::h48c31e1e3d550146
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/panicking.rs:85
  15:     0x560dc940df32 - core::option::expect_none_failed::h6154dc750ae47ade
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/option.rs:1234
  16:     0x560dc98044c3 - reqwest::into_url::expect_uri::h2789eb03f670eb0c
  17:     0x560dc980719e - reqwest::async_impl::request::RequestBuilder::send::h3c4a9657df5af239
  18:     0x560dc95d2a21 - <futures_util::future::future::Map<Fut,F> as core::future::future::Future>::poll::hb78893f4584a0b97
  19:     0x560dc956c289 - <futures_util::future::future::Inspect<Fut,F> as core::future::future::Future>::poll::h8726eead4e0ea9e1
  20:     0x560dc941ddcd - <futures_util::future::future::Map<Fut,F> as core::future::future::Future>::poll::h651e62e8f57508f3
  21:     0x560dc9420565 - <futures_util::stream::futures_unordered::FuturesUnordered<Fut> as futures_core::stream::Stream>::poll_next::h15e0e148a7a6d27e
  22:     0x560dc9431617 - deno_core::runtime::JsRuntime::poll_event_loop::h509290194afb614f
  23:     0x560dc92fbe23 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hb4bbb59866504e6e
  24:     0x560dc92fbffb - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hbc3c429682d54bf0
  25:     0x560dc93930bf - deno::tools::repl::run::{{closure}}::h3d43c64dff0ca056
  26:     0x560dc92fe214 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hbff62ef71d245ce0
  27:     0x560dc957302f - tokio::runtime::Runtime::block_on::h66925486f068d4e2
  28:     0x560dc93b5e02 - deno::main::hab01604fd1310fda
  29:     0x560dc9260620 - std::sys_common::backtrace::__rust_begin_short_backtrace::h8d68729c9fd9492d
  30:     0x560dc93be1c6 - main
  31:     0x7f14056ec8e3 - __libc_start_main
  32:     0x560dc92079ba - _start
  33:                0x0 - <unknown>
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Object({"id": Number(2), "error": Object({"code": Number(-32000), "message": String("Execution context was destroyed.")})})', runtime/inspector.rs:890:8
stack backtrace:
   0:     0x560dc98810b3 - std::backtrace_rs::backtrace::libunwind::trace::h72c2fb8038f1bbee
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/../../backtrace/src/backtrace/libunwind.rs:96
   1:     0x560dc98810b3 - std::backtrace_rs::backtrace::trace_unsynchronized::h1e3b084883f1e78c
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/../../backtrace/src/backtrace/mod.rs:66
   2:     0x560dc98810b3 - std::sys_common::backtrace::_print_fmt::h3bf6a7ebf7f0394a
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:79
   3:     0x560dc98810b3 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h2e8cb764b7fe02e7
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:58
   4:     0x560dc940972c - core::fmt::write::h7a1184eaee6a8644
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/fmt/mod.rs:1080
   5:     0x560dc98808a1 - std::io::Write::write_fmt::haeeb374d93a67eac
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/io/mod.rs:1516
   6:     0x560dc98801a5 - std::sys_common::backtrace::_print::h1d14a7f6ad632dc8
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:61
   7:     0x560dc98801a5 - std::sys_common::backtrace::print::h301abac8bb2e3e81
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:48
   8:     0x560dc98801a5 - std::panicking::default_hook::{{closure}}::hde0cb80358a6920a
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:208
   9:     0x560dc98801a5 - std::panicking::default_hook::h9b1a691049a0ec8f
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:227
  10:     0x560dc98801a5 - std::panicking::rust_panic_with_hook::h2bdec87b60580584
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:577
  11:     0x560dc989a2b8 - std::panicking::begin_panic_handler::{{closure}}::h101ca09d9df5db47
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:484
  12:     0x560dc989a284 - std::sys_common::backtrace::__rust_end_short_backtrace::h3bb85654c20113ca
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:153
  13:     0x560dc989a23d - rust_begin_unwind
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:483
  14:     0x560dc9406d20 - core::panicking::panic_fmt::h48c31e1e3d550146
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/panicking.rs:85
  15:     0x560dc940df32 - core::option::expect_none_failed::h6154dc750ae47ade
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/option.rs:1234
  16:     0x560dc95c0da8 - <deno_runtime::inspector::InspectorSession as rusty_v8::inspector::ChannelImpl>::send_response::h5b91a0b8e08b44a6
  17:     0x560dc9e3a3c7 - _ZThn8_N12v8_inspector22V8InspectorSessionImpl20SendProtocolResponseEiNSt3__110unique_ptrIN8v8_crdtp12SerializableENS1_14default_deleteIS4_EEEE
  18:     0x560dc9e53941 - _ZN8v8_crdtp16DomainDispatcher12sendResponseEiRKNS_16DispatchResponseENSt3__110unique_ptrINS_12SerializableENS4_14default_deleteIS6_EEEE
  19:     0x560dc9e537b0 - _ZN8v8_crdtp16DomainDispatcher8Callback12sendIfActiveENSt3__110unique_ptrINS_12SerializableENS2_14default_deleteIS4_EEEERKNS_16DispatchResponseE
  20:     0x560dca2f7bc0 - _ZN12v8_inspector8protocol7Runtime20EvaluateCallbackImpl11sendFailureERKN8v8_crdtp16DispatchResponseE
  21:     0x560dca2f8cca - _ZN12v8_inspector14InjectedScript24discardEvaluateCallbacksEv
  22:     0x560dca2f8ac2 - _ZN12v8_inspector14InjectedScriptD1Ev
  23:     0x560dca308379 - _ZNSt3__113unordered_mapIiNS_10unique_ptrIN12v8_inspector14InjectedScriptENS_14default_deleteIS3_EEEENS_4hashIiEENS_8equal_toIiEENS_9allocatorINS_4pairIKiS6_EEEEE5eraseERSD_
  24:     0x560dca3081ab - _ZN12v8_inspector16InspectedContext21discardInjectedScriptEi
  25:     0x560dc9e33ac4 - _ZN12v8_inspector15V8InspectorImpl14forEachContextEiRKNSt3__18functionIFvPNS_16InspectedContextEEEE
  26:     0x560dc9e39ef9 - _ZN12v8_inspector22V8InspectorSessionImplD2Ev
  27:     0x560dc9e3a16e - _ZN12v8_inspector22V8InspectorSessionImplD0Ev
  28:     0x560dc927c633 - core::ptr::drop_in_place::hc8aa0deacea6146c
  29:     0x560dc9396cce - deno::tools::repl::run::{{closure}}::h3d43c64dff0ca056
  30:     0x560dc92fe214 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hbff62ef71d245ce0
  31:     0x560dc957302f - tokio::runtime::Runtime::block_on::h66925486f068d4e2
  32:     0x560dc93b5e02 - deno::main::hab01604fd1310fda
  33:     0x560dc9260620 - std::sys_common::backtrace::__rust_begin_short_backtrace::h8d68729c9fd9492d
  34:     0x560dc93be1c6 - main
  35:     0x7f14056ec8e3 - __libc_start_main
  36:     0x560dc92079ba - _start
  37:                0x0 - <unknown>
thread panicked while panicking. aborting.
fish: 'env RUST_BACKTRACE=full deno' terminated by signal SIGILL (Illegal instruction)
```

### PR DESCRIPTION
**Pull request by yos1p**
Fixes #8880

### CODE REVIEW

File: op_crates/fetch/lib.rs [hunk 1]
```diff
@@ -155,39 +156,44 @@ where
...
-
-  Ok(json!({
-    "bodyRid": rid,
-    "status": status.as_u16(),
-    "statusText": status.canonical_reason().unwrap_or(""),
-    "headers": res_headers
-  }))
+  return Err(custom_error(
+    "Http",
+    format!("error trying to connect ({})", url),
```
Comment (yos1p) [inline op_crates/fetch/lib.rs:195]: The error message defined here is according to that from `fetch_test.ts` line 31. I believe this can be improved for clarity. Any suggestions?

Comment (bnoordhuis) [reply op_crates/fetch/lib.rs:195]: I don't think you can get any more specific with reqwest than checking if `err.is_request()` (except maybe scanning the error message for a shibboleth), and that doesn't tell you in any detail what was wrong with the request, so this seems fine to me, it's a step up from the status quo.

Perhaps for troubleshooting purposes print the error with `eprintln!`?

**Review by bnoordhuis — APPROVED** [review]
LGTM and thanks for the quick fix!

File: op_crates/fetch/lib.rs (hunk 1 above)
Comment (yos1p) [reply op_crates/fetch/lib.rs:195]: It's possible, but I'm still not sure if additional error message would be necessary since this is just fetch API.

**Review by lucacasonato — CHANGES_REQUESTED** [review]
I think the error message from reqwest should not be swallowed. This makes debugging the error nearly impossible. Also this should return a web error like `TypeError` (check the spec), and there should be a test.

**Comment by yos1p** [comment]
I tried to make it simple by simply wrapping error message from reqwest in a `TypeError`. Added another test that check an invalid link caused by dns error (or bad URL) according to the issue.

Let me know what you think!

File: cli/tests/unit/fetch_test.ts [hunk 2]
```diff
@@ -27,7 +27,20 @@ unitTest(
...
+    );
+  },
+);
+
+unitTest(
+  { perms: { net: true } },
+  async function fetchConnectionError(): Promise<void> {
+    await assertThrowsAsync(
+      async (): Promise<void> => {
+        await fetch("http://nil/");
```
Comment (danopia) [inline cli/tests/unit/fetch_test.ts:41]: I think this URL is actually valid and doesn't cause a panic currently. Would be good to also test a really invalid URL like `http://<invalid>/`

Comment (yos1p) [reply cli/tests/unit/fetch_test.ts:41]: `http://nil/` cause panic from reqwest error, while `http://invalid/` cause panic because of Rust failing to parse invalid Uri. Thanks for adding another example. Will work on this too

Comment (yos1p) [reply cli/tests/unit/fetch_test.ts:41]: Apparently, deno_core::url doesn't throw error when parsing invalid Uri (neither did reqwest::Url). But error happen when reqwest trying to parse Url to http::Uri. 

This apparently can only be fixed by bumping up rust-url version to 2.2.

**Review by ry — APPROVED** [review]
Thanks @yos1p - LGTM
