### PR TITLE
fix(node): require of pkg json imports was broken

### LINKED ISSUE #21502: Can't use Clerk's Node SDK from NPM
Trying to use the Clerk Node SDK from NPM, like:
```ts
import { clerkClient } from 'npm:@clerk/clerk-sdk-node'
```
I get this error back:
```
Uncaught Error: Not a directory (os error 20)
    at Function.Module._resolveFilename (node:module:596:33)
    at Function.Module._load (node:module:502:27)
    at Module.require (node:module:677:19)
    at require (node:module:791:16)
    at Object.<anonymous> (file:///Users/deno/Library/Caches/deno/npm/registry.npmjs.org/@clerk/backend/0.34.3/dist/index.js:262:29)
    at Object.<anonymous> (file:///Users/deno/Library/Caches/deno/npm/registry.npmjs.org/@clerk/backend/0.34.3/dist/index.js:3100:4)
    at Module._compile (node:module:733:34)
    at Object.Module._extensions..js (node:module:747:10)
    at Module.load (node:module:658:32)
    at Function.Module._load (node:module:539:12)
```

deno 1.38.5 (release, aarch64-apple-darwin)
v8 12.0.267.1
typescript 5.2.2

### PR DESCRIPTION
**Pull request by dsherret**
We fixed pkg json imports for esm packages, but it looks like it was still broken in CJS.

Discovered in https://github.com/denoland/deno/issues/22811

Closes #21502

### CODE REVIEW

File: ext/node/ops/require.rs [hunk 1]
```diff
@@ -575,32 +568,35 @@ where
 #[string]
 pub fn op_require_package_imports_resolve<P>(
```
Comment (dsherret) [inline ext/node/ops/require.rs:569]: Needed to resolve the closest package.json (instead of the just one in the parent folder) and convert the URL to a path before returning.

**Review by marvinhagemeister — APPROVED** [review]
