### PR TITLE
fix(process,node): roll our own process spawning on windows

### LINKED ISSUE #16899: NPM: Playwright does not work
Hi,

I'm trying to use [Playwright](https://github.com/microsoft/playwright) via the new NPM compatibility layer, but it fails with:

`Uncaught TypeError: browserType.launch: Cannot read properties of undefined (reading 'on')`

The following snippet can be used to reproduce the error:

```typescript
import { chromium } from 'npm:playwright';

async function main() {
  const browser = await chromium.launch({
    headless: false,
  });
  const page = await browser.newPage();
  await page.goto('http://example.com');
  await browser.close();
};

if (import.meta.main) {
  main()
}
```

After running the above via `deno run --unstable --allow-all main.ts`, the following message is displayed:

```
error: Uncaught Error: browserType.launch: Executable doesn't exist at /home/user/.cache/ms-playwright/chromium-1033/chrome-linux/chrome
╔═════════════════════════════════════════════════════════════════════════╗
║ Looks like Playwright Test or Playwright was just installed or updated. ║
║ Please run the following command to download new browsers:              ║
║                                                                         ║
║     npx playwright install                                              ║
║                                                                         ║
║ <3 Playwright Team                                                      ║
╚═════════════════════════════════════════════════════════════════════════╝
```

Executing `deno run --unstable --allow-all npm:playwright install` downloads the required binaries.

Executing `deno run --unstable --allow-all main.ts` again, leads to the above-mentioned error:

```
error: Uncaught TypeError: browserType.launch: Cannot read properties of undefined (reading 'on')
=========================== logs ===========================
<launching> /home/user/.cache/ms-playwright/chromium-1033/chrome-linux/chrome --disable-field-trial-config --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-back-forward-cache --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-component-update --no-default-browser-check --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,DialMediaRouteProvider,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater,AvoidUnnecessaryBeforeUnloadCheckSync,Translate --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --no-sandbox --user-data-dir=/tmp/playwright_chromiumdev_profile-4e2wKK --remote-debugging-pipe --no-startup-window
<launched> pid=835204
============================================================
```

`Playwright`/`Deno` was already discussed in https://github.com/denoland/deno/issues/16298, but I thought it makes sense to open an issue that focuses only on `Playwright`. There was also some discussion in the `Playwright` repo: https://github.com/microsoft/playwright/issues/3146

### PR DESCRIPTION
**Pull request by nathanwhit**
Fixes #16899.
Fixes https://github.com/denoland/deno/issues/23524.
Fixes https://github.com/denoland/deno/issues/23938.
Fixes https://github.com/denoland/deno/issues/27869.

Unblocks #5501.

This PR adds support for additional stdio pipes to windows, as well as the detached option in `node:child_process`. I also ported over the `kill` implementation for windows, which means we now can support `kill(0)` as well as some other signals.

This means that playwright will now work on windows.

Now that we have a way to support detached processes on all platforms, we can also easily add a `detached` option to `Deno.Command`, similar to `child_process.spawn`.

---

The reason for moving away from `std::process::Command` is that the standard library doesn't expose what we need to control the file descriptor table of child processes on windows. The implementation here is based off of parts of `std` and parts of `libuv`, and allows us to support passing extra pipes in addition to detached processes on windows.

### CODE REVIEW

File: cli/lib/worker.rs [hunk 1]
```diff
@@ -600,14 +600,15 @@ impl<TSys: DenoLibSys> LibMainWorkerFactory<TSys> {
...
       .resolve_storage_key(&main_module);
-    let origin_storage_dir = maybe_storage_key.as_ref().map(|key| {
-      shared
-        .options
-        .origin_data_folder_path
-        .as_ref()
-        .unwrap() // must be set if storage key resolver returns a value
-        .join(checksum::gen(&[key.as_bytes()]))
-    });
+    let origin_storage_dir: Option<PathBuf> =
```
Comment (bartlomieju) [inline cli/lib/worker.rs:603]: Is this intentional? Seems like a totally unrelated change

File: ext/io/fs.rs [hunk 2]
```diff
@@ -3,6 +3,8 @@
 use std::borrow::Cow;
 use std::fmt::Formatter;
 use std::io;
+#[cfg(unix)]
+use std::process::Stdio as StdStdio;
```
Comment (bartlomieju) [inline ext/io/fs.rs:7]: `StdStdio` :D funny

File: ext/node/polyfills/process.ts [hunk 3]
```diff
@@ -325,7 +325,7 @@ memoryUsage.rss = function (): number {
 // Returns a negative error code than can be recognized by errnoException
 function _kill(pid: number, sig: number): number {
   const maybeMapErrno = (res: number) =>
-    res === 0 ? res : uv.mapSysErrnoToUvErrno(res);
+    res === 0 ? res : isWindows ? res : uv.mapSysErrnoToUvErrno(res);
```
Comment (bartlomieju) [inline ext/node/polyfills/process.ts:329]: A comment here would be useful - why we only need to map it for unix?

File: ext/process/lib.rs [hunk 4]
```diff
@@ -402,24 +411,18 @@ fn create_command(
...
+  let mut command = Command::new(cmd);
 
   #[cfg(windows)]
   {
     if args.detached {
-      // TODO(nathanwhit): Currently this causes the process to hang
-      // until the detached process exits (so never). It repros with just the
-      // rust std library, so it's either a bug or requires more control than we have.
-      // To be resolved at the same time as additional stdio support.
-      log::warn!("detached processes are not currently supported on Windows");
```
Comment (bartlomieju) [inline ext/process/lib.rs:414]: 🚀

File: ext/process/lib.rs [hunk 5]
```diff
@@ -529,6 +532,8 @@ fn create_command(
 
   #[cfg(windows)]
   {
+    let mut extra_pipe_rids = Vec::new();
```
Comment (bartlomieju) [inline ext/process/lib.rs]: Pre-allocate based on `args.extra_stdio.len()`

File: ext/process/lib.rs [hunk 6]
```diff
@@ -554,13 +559,35 @@ fn create_command(
...
+              extra_pipe_rids.push(None);
+              continue;
+            }
+          },
+        );
+        command.extra_handle(Some(fd2));
+        extra_pipe_rids.push(Some(rid));
+      } else {
+        command.extra_handle(None);
+        extra_pipe_rids.push(None);
```
Comment (bartlomieju) [inline ext/process/lib.rs:587]: Can you add a comment what it means? Pushing `None` is very non-descriptive

File: ext/process/lib.rs [hunk 7]
```diff
@@ -640,19 +671,46 @@ fn spawn_child(
 
   let pid = child.id().expect("Process ID should be set.");
 
+  #[cfg(not(windows))]
+  let stdin_rid = child
+    .stdin
+    .take()
+    .map(|stdin| state.resource_table.add(ChildStdinResource::from(stdin)));
```
Comment (bartlomieju) [inline ext/process/lib.rs:679]: Yikes, all these conditionals are horrible - I think it's fine for this first pass, but we should address it in a follow up - ideally we'd only have one block for windows and one block for unix

File: ext/process/lib.rs [hunk 8]
```diff
@@ -997,6 +1055,11 @@ fn op_spawn_kill(
 }
 
 mod deprecated {
+  #[cfg(windows)]
+  use deno_subprocess_windows::Child;
+  #[cfg(not(windows))]
+  use tokio::process::Child;
```
Comment (bartlomieju) [inline ext/process/lib.rs:1062]: I believe `Deno.run` (which this module implements) is not used in Node compat layer and doesn't necessarily needs to be updated to use the new crate - or is it just simpler for you to do so?

File: runtime/subprocess_windows/src/anon_pipe.rs [hunk 9]
```diff
@@ -0,0 +1,501 @@
+// Copyright 2018-2025 the Deno authors. MIT license.
+
+// Pulled from https://github.com/rust-lang/rust/blob/3e674b06b5c74adea662bd0b0b06450757994b16/library/std/src/sys/pal/windows/pipe.rs
```
Comment (bartlomieju) [inline runtime/subprocess_windows/src/anon_pipe.rs:29]: We should probably add a proper copyright here

File: runtime/subprocess_windows/src/env.rs [hunk 10]
```diff
@@ -0,0 +1,237 @@
+// Copyright 2018-2025 the Deno authors. MIT license.
+
+// https://github.com/rust-lang/rust/blob/2eef47813f25df637026ce3288880e5c587abd92/library/std/src/sys/process/env.rs
```
Comment (bartlomieju) [inline runtime/subprocess_windows/src/env.rs:29]: Ditto

File: runtime/subprocess_windows/src/lib.rs [hunk 11]
```diff
@@ -0,0 +1,467 @@
...
+
+impl<T: Kill> Drop for ChildDropGuard<T> {
+  fn drop(&mut self) {
+    if self.kill_on_drop {
+      drop(self.kill());
+    }
+  }
+}
+
+// copied from https://github.com/tokio-rs/tokio/blob/ab8d7b82a1252b41dc072f641befb6d2afcb3373/tokio/src/process/mod.rs
```
Comment (bartlomieju) [inline runtime/subprocess_windows/src/lib.rs:158]: Let's add tokio copyright to the top too

File: runtime/subprocess_windows/src/process.rs [hunk 12]
```diff
@@ -0,0 +1,1567 @@
+// Copyright 2018-2025 the Deno authors. MIT license.
+
+#![allow(nonstandard_style, dead_code)]
```
Comment (bartlomieju) [inline runtime/subprocess_windows/src/process.rs]: Do we have to keep `dead_code`?

File: runtime/subprocess_windows/src/tests.rs [hunk 13]
```diff
@@ -0,0 +1,3 @@
+// Copyright 2018-2025 the Deno authors. MIT license.
+
+// TODO
```
Comment (bartlomieju) [inline runtime/subprocess_windows/src/tests.rs:3]: Address before landing? Maybe ask Claude to write some tests?

File: tests/node_compat/config.jsonc [hunk 14]
```diff
@@ -1394,7 +1394,6 @@
   },
   "windowsIgnore": {
     "parallel": [
-      "test-child-process-detached.js",
```
Comment (bartlomieju) [inline tests/node_compat/config.jsonc:1397]: Fan-ta-stic!

File: tests/unit/command_test.ts [hunk 15]
```diff
@@ -705,6 +705,7 @@ Deno.test(
 Deno.test(
   { permissions: { run: true, read: true, env: true } },
   async function commandClearEnv() {
+    Deno.env.set("DENO_COMMAND_CLEAR_ENV_TESTING", "TESTING");
```
Comment (bartlomieju) [inline tests/unit/command_test.ts:708]: These should be done in `try/finally` block otherwise they will start leaking. Why are these needed anyway? Can't they be set in `env` option of the spawned subprocess?

File: cli/lib/worker.rs (hunk 1 above)
Comment (nathanwhit) [reply cli/lib/worker.rs:603]: Sometimes when I double click in vscode, rust-analyzer inserts the inferred type for the variable :(

File: tests/unit/command_test.ts (hunk 15 above)
Comment (nathanwhit) [reply tests/unit/command_test.ts:708]: Not needed anymore, forgot to revert. I originally ported the env var creation from libuv, which forcibly ensures that child processes always have a `PATH` var https://github.com/libuv/libuv/blob/b00c5d1a09c094020044e79e19f478a25b8e1431/src/win/process.c#L50-L62

I switched over to an impl from std instead, since it's a lot more maintainable and doesn't have that quirk

File: tests/specs/npm/playwright_compat/__test__.jsonc [hunk 16]
```diff
@@ -6,10 +6,6 @@
     "args": "run -A npm:playwright install chromium",
     "output": "[WILDCARD]"
   }, {
-    // stdio pipes beyond stdin/stdout/stderr are not currently supported on windows
-    // https://github.com/denoland/deno/issues/23524
-    // TODO(kt3k): enable this on windows when the issue is fixed
-    "if": "unix",
```
Comment (littledivy) [inline tests/specs/npm/playwright_compat/__test__.jsonc:12]: Nicee

File: runtime/subprocess_windows/src/widestr.rs [hunk 17]
```diff
@@ -0,0 +1,155 @@
...
+use std::ops::Index;
+use std::ops::Range;
+use std::ops::RangeFrom;
+use std::ops::RangeTo;
+use std::os::windows::ffi::OsStrExt;
+
+#[derive(Clone, PartialEq, Eq)]
+pub struct WCString {
+  buf: Box<[u16]>,
+}
```
Comment (littledivy) [inline runtime/subprocess_windows/src/widestr.rs:14]: Why is this needed and not something like `std::ffi::OsString`?

Comment (nathanwhit) [reply runtime/subprocess_windows/src/widestr.rs:14]: `OsString` is WTF-8 encoded on windows, so any time you want to call into a windows api you have to re-encode it to null-terminated utf16. This type just represents a null terminated utf16 string

File: runtime/subprocess_windows/src/tests.rs (hunk 13 above)
Comment (nathanwhit) [reply runtime/subprocess_windows/src/tests.rs:3]: Will do in a followup
