### PR TITLE
fix(signals): prevent panic when listening to forbidden signals

### LINKED ISSUE #12515: bug(signal): Registering SIGKILL causes panic
the following code will cause a panic in deno 1.15.2
```ts
for await (const sig of Deno.signal("SIGKILL")) {
  console.log(sig);
}
```
Ran with `deno run --unstable mod.ts`

Error
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: Other, error: "Refusing to register signal 9" }', runtime/ops/signal.rs:185:67
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

stacktrace
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: Other, error: "Refusing to register signal 9" }', runtime/ops/signal.rs:185:67
stack backtrace:
   0: rust_begin_unwind
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:515:5
   1: core::panicking::panic_fmt
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/panicking.rs:92:14
   2: core::result::unwrap_failed
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/result.rs:1599:5
   3: deno_core::ops_json::op_sync::{{closure}}
   4: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
   5: deno_core::ops::OpTable::route_op
   6: <extern "C" fn(A0) .> R as rusty_v8::support::CFnFrom<F>>::mapping::c_fn
   7: _ZN2v88internal25FunctionCallbackArguments4CallENS0_15CallHandlerInfoE
             at ./../../../../v8/src/api/api-arguments-inl.h:152:3
   8: _ZN2v88internal12_GLOBAL__N_119HandleApiCallHelperILb0EEENS0_11MaybeHandleINS0_6ObjectEEEPNS0_7IsolateENS0_6HandleINS0_10HeapObjectEEESA_NS8_INS0_20FunctionTemplateInfoEEENS8_IS4_EENS0_16BuiltinArgumentsE
             at ./../../../../v8/src/builtins/builtins-api.cc:112:36
   9: _ZN2v88internalL26Builtin_Impl_HandleApiCallENS0_16BuiltinArgumentsEPNS0_7IsolateE
             at ./../../../../v8/src/builtins/builtins-api.cc:142:5
  10: Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_BuiltinExit
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

### PR DESCRIPTION
**Pull request by crowlKats**
Closes #12515

### CODE REVIEW

**Review by lucacasonato — COMMENTED** [review]
Instead of adding this dependency, can we just filter out the 4 forbidden signals ourselves? The forbidden ones are:

- `SIGKILL`
- `SIGSTOP`
- `SIGILL`
- `SIGFPE`
- `SIGSEGV`

**Review by lucacasonato — COMMENTED** [review]
disregard my comment. this is not a new dep

File: cli/tests/unit/signal_test.ts [hunk 1]
```diff
@@ -203,3 +203,19 @@ Deno.test(
...
+
+Deno.test(
+  {
+    ignore: Deno.build.os === "windows",
+    permissions: { run: true },
+  },
+  function signalForbiddenSignalTest() {
+    assertThrows(
+      () => {
+        Deno.addSignalListener("SIGKILL", () => {});
```
Comment (bartlomieju) [inline cli/tests/unit/signal_test.ts:215]: Could you test all signals that should throw this error?

**Review by erfanium — APPROVED** [review]

**Review by piscisaureus — APPROVED** [review]
