### PR TITLE
fix(npm): retain authorization header on http->https redirect

### LINKED ISSUE #29869: Can't install private npm package with deno (but works with npm)
Version: Deno 2.3.3

When doing `deno install` with a correctly configured `.npmrc`, install fails with a 401.  With the same setup with npm the install succeeds.

Repro:

1. Unzip the repro project
2. Try deno install and see it fail
3. Try npm and see it installs

NOTE: The toke included with this project is set to expire in 90 days.

Actual:

It fails with Deno.

```
$ deno install
error: Failed loading http://npm.pkg.github.com/@superiorframework%2flogger for package "@superiorframework/logger"

Caused by:
    Bad response: 401

    {"error":"authentication token not provided"}
```

Image

```
$ npm install

added 5 packages, and audited 6 packages in 766ms

found 0 vulnerabilities
```

[private-repo-repoduction-deno.zip](https://github.com/user-attachments/files/20884348/private-repo-repoduction-deno.zip)

Expected:
It should install with Deno.

### PR DESCRIPTION
**Pull request by nathanwhit**
Fixes #29869.

## Summary

When an npm registry is configured with `http://` in `.npmrc` and the server
redirects to `https://`, the authorization header was being stripped. This
happened because the previous origin-based check (`url.origin() != new_url.origin()`)
treated scheme changes as cross-origin, since `url::Origin` includes the scheme.

This caused 401 errors for private registries like GitHub Packages when
configured with `http://` URLs.

## Changes

- Extract the redirect auth-stripping logic into a `should_strip_auth_on_redirect`
  helper function with clear semantics:
  - **Strip auth** when the host or port changes (true cross-origin redirect)
  - **Strip auth** on scheme downgrade (`https` -> `http`) to avoid leaking
    credentials over plaintext
  - **Retain auth** on same-host scheme upgrades (`http` -> `https`), which are
    safe redirects
- Add unit tests covering all cases (same-host upgrade, same origin, different
  host, different port, scheme downgrade)

### CODE REVIEW

File: cli/http_util.rs [hunk 1]
```diff
@@ -345,7 +345,7 @@ impl HttpClient {
 
         let mut headers = headers.clone();
         // SECURITY: Do NOT forward auth headers to a new origin
-        if new_url.origin() != url.origin() {
+        if new_url.origin() != url.origin() && url.host() != new_url.host() {
```
Comment (anonhostpi) [inline cli/http_util.rs]: This seems wrong.

Correct me if I'm wrong (I'm very sleepy), but this looks like it allows leaking of the authorization header not only when upgrading to HTTPS, _but also **downgrading**_.
- It would also allow leaking when switching ports. However, it is generally assumed that different ports on the same host are equally trustworthy.

Not familiar enough with the codebase (and equally too sleepy) to know if this is handled elsewhere (or externally)

Comment (anonhostpi) [reply cli/http_util.rs]: Not sure if a HTTPS to HTTP downgrade can even be expected though.

Comment (anonhostpi) [reply cli/http_util.rs]: Out of curiosity, is it possible to deprecate or block sending authorization headers over HTTP completely to begin with? Now that I think about it, that is a very insecure practice.

Maybe if its required, add a flag to allow insecure auth token transport?
