### PR TITLE
fix: release ReadeableStream in fetch

### LINKED ISSUE #16648: Unhandled rejection when aborting cloned request with a static body
The code below causes an unhandled rejection in Deno but not in browsers. This does not happen if `body` is a `ReadableStream`.

```js
// a.js
const req = new Request("http://example.com/", {
  body: "",
  method: "POST",
  signal: AbortSignal.timeout(0),
});
fetch(req.clone()).catch(() => {});
```

```shellsession
$ deno run --allow-net a.js
error: Uncaught (in promise) TypeError: Cannot cancel a locked ReadableStream.
    at ReadableStream.cancel (deno:ext/web/06_streams.js:4685:11)
    at InnerBody.cancel (deno:ext/fetch/22_body.js:165:29)
    at abortFetch (deno:ext/fetch/26_fetch.js:476:22)
    at onabort (deno:ext/fetch/26_fetch.js:409:11)
    at AbortSignal.[[[signalAbort]]] (deno:ext/web/03_abort_signal.js:80:11)
    at deno:ext/web/03_abort_signal.js:183:37
    at AbortSignal.[[[signalAbort]]] (deno:ext/web/03_abort_signal.js:80:11)
    at deno:ext/web/03_abort_signal.js:183:37
    at AbortSignal.[[[signalAbort]]] (deno:ext/web/03_abort_signal.js:80:11)
    at deno:ext/web/03_abort_signal.js:183:37
$ deno --version
deno 1.28.0+d6fd171 (canary, x86_64-apple-darwin)
v8 10.9.194.1
typescript 4.8.3
```

### PR DESCRIPTION
**Pull request by crowlKats**
Fixes #16648

### CODE REVIEW

**Review by bartlomieju — APPROVED** [review]
LGTM

File: cli/tests/unit/fetch_test.ts [hunk 1]
```diff
@@ -1887,3 +1887,27 @@ Deno.test(
     await server;
   },
 );
+
+Deno.test(
+  { permissions: { net: true } },
+  async function fetchRequestBodyEmptyStream() {
```
Comment (dsherret) [inline cli/tests/unit/fetch_test.ts:1893]:
```
fetchRequestBodyEmptyStream => ./cli/tests/unit/fetch_test.ts:1891:6
error: AssertionError: Expected function to reject.
    throw new AssertionError(
          ^
    at assertRejects (file:///home/runner/work/deno/deno/test_util/std/testing/asserts.ts:891:11)
    at async fetchRequestBodyEmptyStream (file:///home/runner/work/deno/deno/cli/tests/unit/fetch_test.ts:1901:5)
```

Seems flaky https://github.com/denoland/deno/actions/runs/3904649696/jobs/6670704695

Comment (crowlKats) [reply cli/tests/unit/fetch_test.ts:1893]: i tried this test so many times locally and never was... why ci...

Comment (dsherret) [reply cli/tests/unit/fetch_test.ts:1893]: I managed to reproduce it by running all the fetch tests together over and over again in two separate terminals. It didn't seem to occur with just one. `do { cargo run --bin deno -- test --allow-all --unstable --location=http://js-unit-tests/foo/bar .\cli\tests\unit\fetch_test.ts } until ($LastExitCode -ne 0)`

Comment (crowlKats) [reply cli/tests/unit/fetch_test.ts:1893]: hm, unsure what to do here

**Comment by aapoalas** [comment]
Marking as ready to review to get CI.

File: cli/tests/unit/fetch_test.ts (hunk 1 above)
Comment (aapoalas) [reply cli/tests/unit/fetch_test.ts:1911]: I pushed a change to use a synchronous AbortSignal triggering to avoid the flakiness. I think this should be good since now it's not possible for the fetch to get resolved before the abort happens.
