### PR TITLE
fix(types): Conform lib.deno_web.d.ts to lib.dom.d.ts and lib.webworker.d.ts

### LINKED ISSUE #21981: The `dom` lib is missing typings for `ReadableStream.from`
Version: Deno 1.39.4

Really just forwarding this comment since that issue is closed and therefore seems to not be on anyone's radar.
https://github.com/denoland/deno/issues/21733#issuecomment-1880315355 

## Example
This code runs successfully, but throws a typing error on `.from`
```ts
function* example() {
	yield 1
}

const stream = ReadableStream.from(example())

for await (const value of stream)
	console.log(value)
```
```json
{
	"compilerOptions": {
		"lib": [
			"dom",
			"deno.ns"
		]
	}
}

### LINKED ISSUE #24578: ReadableStream.from method fails type-checking in v1.45.0+ if you import openai package
```ts
import "npm:openai@^4.52.7";

const rs = ReadableStream.from([
  new Uint8Array([5, 6, 7]),
]);
```

```
> deno check .\main.ts
Check file:///E:/chris/Coding/deno-test/main.ts
error: TS2339 [ERROR]: Property 'from' does not exist on type '{ new (underlyingSource: UnderlyingByteSource, strategy?: { highWaterMark?: number | undefined; } | undefined): ReadableStream<Uint8Array>; new <R = any>(underlyingSource: UnderlyingDefaultSource<...>, strategy?: QueuingStrategy<...> | undefined): ReadableStream<...>; new <R = any>(underlyingSource?: UnderlyingSourc...'.
const rs = ReadableStream.from([
                          ~~~~
    at file:///E:/chris/Coding/deno-test/main.ts:3:27
```

This error does not happen if you remove the import.

This error does not happen in Deno 1.44.4. This error happens in 1.45.0 and above.

In VSCode, if I ctrl-click on `ReadableStream` in the code, I see that both lib.deno.web.d.ts and lib.dom.d.ts declare an interface and variable named `ReadableStream`, and `polyfill.d.ts` (from the "web-streams-polyfill" npm package, a dependency of the "openai" package) declares an interface named `ReadableStream`. If I comment out the import, then only the lib.deno.web.d.ts entry appears without the other two.

image

The [variable declared by lib.dom.d.ts](https://github.com/denoland/deno/blob/v1.45.2/cli/tsc/dts/lib.dom.d.ts#L18817) is missing the `from` method which is present in the variable declared by [lib.deno.web.d.ts](https://github.com/denoland/deno/blob/v1.45.2/ext/web/lib.deno_web.d.ts#L806) and there are some other inconsistencies in the `new` overloads. I think this problem would be fixed either by these two declarations being made consistent, or by the declaration in lib.dom.d.ts being removed entirely (as it's redundant, assuming it's the case that lib.deno.web.d.ts is always loaded).

### PR DESCRIPTION
**Pull request by petamoriken**
Fix #24578
Fix #21981

### CODE REVIEW

**Comment by Hajime-san** [comment]
Will this also fix?
https://github.com/denoland/deno/issues/21981

**Review by bartlomieju — COMMENTED** [review]
Thanks for working on this. Could you please add some tests like I did in https://github.com/denoland/deno/pull/24489 to ensure we don't regress again?

**Comment by bartlomieju** [comment]
@petamoriken do you need any help with this PR? I'd like to land it before v1.45.3 release that will happen on Monday, July 22nd.

**Comment by petamoriken** [comment]
@bartlomieju Finally, I am going to add type aliases for users who refer to old types. It shouldn't take that long.

File: ext/web/lib.deno_web.d.ts [hunk 1]
```diff
@@ -577,66 +592,62 @@ declare var File: {
...
-/** @category Streams */
-declare interface ReadableStreamBYOBReadValueResult<V extends ArrayBufferView> {
-  done: false;
-  value: V;
-}
-
-/** @category Streams */
-declare type ReadableStreamBYOBReadResult<V extends ArrayBufferView> =
-  | ReadableStreamBYOBReadDoneResult<V>
-  | ReadableStreamBYOBReadValueResult<V>;
```
Comment (petamoriken) [inline ext/web/lib.deno_web.d.ts:625]: It can be reland when supported by upstream (https://github.com/microsoft/TypeScript-DOM-lib-generator/pull/1676)

File: ext/web/lib.deno_web.d.ts [hunk 2]
```diff
@@ -339,16 +348,16 @@ declare var TextEncoder: {
...
-  /** Returns `true` if ignore BOM flag is set, and `false` otherwise. */
-  readonly ignoreBOM: boolean;
+}
+
+/** @category Encoding */
+declare interface TextDecoderStream
+  extends GenericTransformStream, TextDecoderCommon {
   readonly readable: ReadableStream<string>;
   readonly writable: WritableStream<BufferSource>;
-  readonly [Symbol.toStringTag]: string;
```
Comment (petamoriken) [inline ext/web/lib.deno_web.d.ts:351]: ditto (https://github.com/microsoft/TypeScript-DOM-lib-generator/pull/1699)

**Review by dsherret — APPROVED** [review]
LGTM. Thanks a lot!
