### PR TITLE
fix(ext/node): make `child_process` stdio streams Socket instances

### LINKED ISSUE #25602: `process.stdout` should be an instance of `node:tty` `WriteStream`
There's code that checks whether stdout is a tty by doing an instanceof check, e.g. in angular: https://github.com/angular/angular-cli/blob/d66aaa3ca458e05b535bec7c1dcb98b0e9c5202e/packages/angular/cli/src/utilities/color.ts#L14-L16

### LINKED ISSUE #31961: Child processes spawned with node:child_process and piped stdout have incorrect type data
When a child process is spawned with piped output streams, Deno treats them as a Readable. In Node, the TS typings agree that its a readable, but under the hood it is implemented as a socket.

This is important because you need to unref the streams in addition to the child_process for the process to shut down gracefully. 

This was discovered as a bug report in https://github.com/nrwl/nx where a PR was opened to remove an error check we had around this: https://github.com/nrwl/nx/pull/34224/

For context, in Nx we have "Plugin Workers" - these workers are started by either the main cli process or the daemon, if its enabled. The worker's lifetime is bound by the process that spawned them. They are detached and unrefed s.t. the presence of the worker doesn't keep the parent process alive. When the parent process exits, the workers see their ipc socket close, and shut themselves down quickly.

A similar issue appears to exist in bun, I'm planning to create the issue there next.

## Reproduction Steps

Compare the output of the below script between node + deno

```js
import { spawn } from 'node:child_process';
import { Socket } from 'node:net';

const cp = spawn('node', [], {
  stdio: 'pipe'
});

console.log('Stdout is socket:', cp.stdout instanceof Socket);
console.log('Stdout is unref\'able', 'unref' in cp.stdout && typeof cp.stdout.unref === 'function');
cp.kill();

```

For comparison, here is the output in each of node/deno/bun

```console
12:13 $ deno --allow-all tmp/test.mjs
Stdout prototype: Readable
Stdout is socket: false
Stdout is unref'able false
12:13 $ node tmp/test.mjs
Stdout prototype: Socket
Stdout is socket: true
Stdout is unref'able true
12:13 $ bun tmp/test.mjs
Stdout prototype: Readable
Stdout is socket: false
Stdout is unref'able true
```

## Environment Info
deno 2.6.6 (stable, release, aarch64-apple-darwin)
v8 14.2.231.17-rusty
typescript 5.9.2

## Other Info
The bun issue for a similar mismatch is here: https://github.com/oven-sh/bun/issues/26505

### PR DESCRIPTION
**Pull request by fraidev**
Closes #31961
Closes #25602

This PR fixes child process stdio streams (`stdin`, `stdout`, `stderr`) to be instances of `Socket` from `node:net`, matching Node.js behavior.

### CODE REVIEW

File: ext/node/polyfills/internal/child_process.ts [hunk 1]
```diff
@@ -164,18 +167,46 @@ class StreamResource implements StreamBase {
   }
   async read(p: Uint8Array): Promise<number | null> {
```
Comment (bartlomieju) [inline ext/node/polyfills/internal/child_process.ts:167]: What if this gets called multiple times? Is that possible? If so then you will overwrite pending promise

File: ext/node/polyfills/internal/child_process.ts [hunk 2]
```diff
@@ -164,18 +167,46 @@ class StreamResource implements StreamBase {
...
+    if (this.#pendingReadPromise) {
+      core.unrefOpPromise(this.#pendingReadPromise);
+    }
+    if (this.#pendingWritePromise) {
+      core.unrefOpPromise(this.#pendingWritePromise);
+    }
   }
-  write(p: Uint8Array): Promise<number> {
-    return core.write(this.#rid, p);
+  async write(p: Uint8Array): Promise<number> {
```
Comment (bartlomieju) [inline ext/node/polyfills/internal/child_process.ts:192]: Ditto

File: ext/node/polyfills/internal/child_process.ts (hunk 1 above)
Comment (fraidev) [reply ext/node/polyfills/internal/child_process.ts:167]: Good catch! I changed to use a Set of it instead

**Comment by AgentEnder** [comment]
Awesome! Thanks yall
