### PR TITLE
(std) refactor: remove testing dependencies from non-test code

### LINKED ISSUE #5762: Uuid std lib module > 0.41.0 does not work in browsers
Version 0.41.0 seems to be the last version supported in the browser.

I've created a small [reproduction repo](https://github.com/NathanKleekamp/deno-uuid-bug) to illustrate. If you clone the repo, and checkout each of the tagged versions, you'll see that it's only at 0.41.0 does it work in browsers.

In Chrome until 0.52.0, and Firefox between version 0.42.0 and 0.50.0, it complains `Uncaught ReferenceError: Deno is not defined`.

In Firefox, version 0.50.0 and greater, it complains `SyntaxError: private fields are not currently supported`.

### PR DESCRIPTION
**Pull request by cknight**
This PR removes dependencies on the `std/testing/asserts.ts` module in non-test code, achieved by moving `assert()` to  `std/_util` sub-folder.   All `std` non-test code has been updated to remove any imports from `std/testing`.

In addition to better separation of concerns, this change also has the benefit of removing the dependency on the Deno global which comes with importing `std/testing/asserts.ts` making these modules more likely to work in the browser.  ~~Specifically, `std/uuid` should now work in the browser, with this change resolving #5762.~~

EDIT: browser compatibility was tackled in #5847.  Therefore this PR is about removing test dependencies from production code.

### CODE REVIEW

File: std/testing/asserts.ts [hunk 1]
```diff
@@ -129,13 +124,6 @@ export function equal(c: unknown, d: unknown): boolean {
   })(c, d);
 }
 
-/** Make an assertion, if not `true`, then throw. */
-export function assert(expr: unknown, msg = ""): asserts expr {
-  if (!expr) {
-    throw new AssertionError(msg);
-  }
-}
-
```
Comment (nayeemrmn) [inline std/testing/asserts.ts:138]: This module needs to export something like this either way.

**Comment by cknight** [comment]
> How about putting the non-test `assert()` in `std/_util/assert.ts`, using that for all non-test code and leaving `std/testing` as is?

I've no strong objection to this and I did consider it at first, however I went with my approach for two reasons:
* `_util` is designated by convention as an internal package.  `assert` seems a useful function to expose externally and one which developers would want to use in building their own modules.  As no other existing module seemed to fit, I went with a new one.
* The re-export approach was meant to avoid code duplication.  

Thinking on this more, I think duplicating `assert()` may be better in the long run, as this leaves a dedicated `assert()` function in the test code which can be modified in the future for test specific concerns without adding complications to the non-test version.

**Comment by nayeemrmn** [comment]
> * `_util` is designated by convention as an internal package.  `assert` seems a useful function to expose externally and one which developers would want to use in building their own modules.

While I said that it makes sense to have both asserts, having both in the public API becomes confusing... due to the uncanny valley between their behaviours. Plus there's no way or reason to stop people from using the testing assertion library for runtime assertions. It should always "just work" for that purpose.

I also think projects should have their own mechanisms for this, rather than us providing a non-descriptive one that overlaps with the testing assertion:
```ts
export class RedisInternalError extends Error {
  constructor(message: string) {
    super(`${message}

Please submit a bug report to https://github.com/keroxp/deno-redis/issues if a
similar one has not been submitted already.`);
  }
}

export function assert(expr: unknown, msg = ""): asserts expr {
  if (!expr) {
    throw new RedisInternalError(msg);
  }
}
```

**Comment by ry** [comment]
I totally agree with the goal of this patch - to make some std modules more browser compatible. I disagree with adding `std/validation`.

Why doesn't `std/testing/asserts.ts` work in the browser? It ought to not be using `Deno`.

File: std/http/_io_test.ts [hunk 2]
```diff
@@ -164,7 +164,7 @@ test("writeTrailer should throw", async () => {
           new Headers({ [f]: "1" })
         );
       },
-      AssertionError,
+      AssertionFailedError,
```
Comment (nayeemrmn) [inline std/http/_io_test.ts:167]: I see we've been using assertion errors for validating input 🙃 We have `TypeError` and `InvalidData` for that, this should be fixed.

File: std/validation/assert.ts [hunk 3]
```diff
@@ -0,0 +1,15 @@
+// Copyright 2018-2020 the Deno authors. All rights reserved. MIT license.
+
+export class AssertionFailedError extends Error {
```
Comment (nayeemrmn) [inline std/validation/assert.ts:3]: Introducing a superficial difference to avoid a name clash is especially confusing. That's why I suggested `StdInternalError`... of course that name only works if it's being used for debugging and not for user input validation somewhere 😫

**Comment by nayeemrmn** [comment]
> Why doesn't `std/testing/asserts.ts` work in the browser? It ought to not be using `Deno`.

After a quick scan it should be easy to make compatible with some feature testing. Replace `Deno.inspect(v)` with `globalThis.Deno ? Deno.inspect(v) : v.toString()`, `const { noColor } = Deno` with `const noColor = globalThis.Deno?.noColor ?? true`.

**Comment by cknight** [comment]
> I totally agree with the goal of this patch - to make some std modules more browser compatible. I disagree with adding `std/validation`.
> 
> Why doesn't `std/testing/asserts.ts` work in the browser? It ought to not be using `Deno`.

@ry thanks for the feedback.  With @nayeemrmn's suggestion it looks like we can eliminate `Deno` from `std/testing/asserts.ts`, making it browser compatible.  And thanks @nayeemrmn for the explanation on your reasoning.  That makes sense.  I'll update this PR later with another go with an internal assert implementation in `std/_util`.

**Comment by bartlomieju** [comment]
@cknight is this PR still relevant with #5847 landed?

**Comment by cknight** [comment]
> @cknight is this PR still relevant with #5847 landed?

@bartlomieju This PR was ultimately focused on two intertwined outcomes.  The first was reducing dependency on the Deno global (as seen in `std/testing/asserts.ts`) to improve browser compatibility.  The second was on removing dependencies on `std/testing/asserts.ts` from non-test code for better separation of concerns.  #5847 resolves the first by making `std/testing/asserts.ts` browser compatible.  What's left in this re-worked PR is the separation of concerns.  Feel free to close without merge if you are OK with modules such as `std/uuid`, etc depending on `std/testing/asserts.ts`.

**Comment by bartlomieju** [comment]
> > @cknight is this PR still relevant with #5847 landed?
> 
> @bartlomieju This PR was ultimately focused on two intertwined outcomes. The first was reducing dependency on the Deno global (as seen in `std/testing/asserts.ts`) to improve browser compatibility. The second was on removing dependencies on `std/testing/asserts.ts` from non-test code for better separation of concerns. #5847 resolves the first by making `std/testing/asserts.ts` browser compatible. What's left in this re-worked PR is the separation of concerns. Feel free to close without merge if you are OK with modules such as `std/uuid`, etc depending on `std/testing/asserts.ts`.

@cknight @nayeemrmn with #5847 landed these modules should work with browsers; if that's the case I think it's fine to keep imports to `testing/asserts.ts`

**Comment by cknight** [comment]
Checked with @bartlomieju to see if this should be closed. He wishes to think more on this, but asked for a summary of our conversation to be added as a comment here.  Essentially, by having production modules such as `std/uuid` depending on `std/testing/asserts.ts`, this creates a dependency between test and production code. If in the future `assert()` behaviour is changed for a specific testing reason, this could unknowingly impact production code or break browser compatibility.  A final point was that if modules such as `std/uuid` are importing `std/testing/asserts.ts`, this may accidentally encourage use of non-appropriate functions from this module or other modules in the `std/testing` directory.

**Comment by nayeemrmn** [comment]
> If in the future `assert()` behaviour is changed for a specific testing reason, this could unknowingly impact production code or break browser compatibility.

I think @ry's point was that the `asserts` module _ought_ to stay simple enough to always work for both uses. Meaning we would actively avoid extensions like that to keep testing mechanisms simple. Besides, I think there is enough precedent to know we won't suddenly need it to do more later.

The fundamental behaviour of `assert()` is to throw an error if a condition doesn't hold. Rather than thinking of it as "testing code", just let it be used where this behaviour is desired. I'm in favour of moving it to `std/assert/mod.ts` to better represent this.
