### PR TITLE
Handle promise reject handler added later issue

### LINKED ISSUE #936: Unable to catch error thrown inside async function
```javascript
async function fn() {
	throw new Error("message");
}
async function call() {
	try {
		console.log("before await fn()");
		await fn();
		console.log("after await fn()");
	} catch (error) {
		console.log("catch");
	}
	console.log("after try-catch");
}
call().catch(error => console.log("outer catch"));
```

```
$ deno async-fn.ts
Compiling /.../async-fn.ts
before await fn()
Error: message
    at fn (file:///.../async-fn.ts:2:8)
    at call (file:///.../async-fn.ts:7:9)
    at eval (file:///.../async-fn.ts:14:1)
    at DenoCompiler.eval [as _globalEval] (<anonymous>)
    at DenoCompiler._gatherDependencies (deno/js/compiler.ts:214:10)
    at DenoCompiler.run (deno/js/compiler.ts:560:12)
    at denoMain (deno/js/main.ts:72:12)
    at deno_main.js:1:1
```

---

If `fn` is synchronous instead, it works fine:

```diff
- async function fn() {
+ function fn() {
```

```
$ deno sync-fn.ts
Compiling /.../sync-fn.ts
before await fn()
catch
after try-catch
```

I thought it might be related to #919, but this also happens with my own build of master after that was closed.

### PR DESCRIPTION
**Pull request by kevinkassimo**
Closes #936
Rationale see #936 comments (handler implementation moved to TS side).

v8 [emits `kPromiseHandlerAddedAfterReject`](https://v8.paulfryzel.com/docs/master/classv8_1_1_isolate.html#a702f0ba4e5dee8a98aeb92239d58784e) when a catch block is found in async function, that cancels a previous `kPromiseRejectWithNoHandler`. Postpone error handling and exit to the end of each event loop cycle. `tests/async_error.ts.out` actually now matches that running under Node. ("world" is printed first: error handling only happens after script running to its end)

An alternative C++ only implementation could be found [here](https://github.com/kevinkassimo/deno/commit/a60f3d45df162e3e1dd9481ff93af175c55aab29)

### CODE REVIEW

File: libdeno/deno.h [hunk 1]
```diff
@@ -59,6 +59,8 @@ int deno_execute(Deno* d, void* user_data, const char* js_filename,
 // libdeno.recv() callback. Check deno_last_exception() for exception text.
 int deno_respond(Deno* d, void* user_data, int32_t req_id, deno_buf buf);
 
+void deno_check_promise_reject_events(Deno* d);
```
Comment (ry) [inline libdeno/deno.h]: Please add tests to libdeno/libdeno_test.cc

File: libdeno/binding.cc [hunk 2]
```diff
@@ -490,6 +624,35 @@ int deno_respond(Deno* d, void* user_data, int32_t req_id, deno_buf buf) {
...
+      return;
+    }
+    v8::Local<v8::Value> args[0];
+    auto result = promise_error_examiner->Call(context->Global(), 0, args);
+    if (try_catch.HasCaught()) {
+      deno::HandleException(context, try_catch.Exception());
+    }
+    d->pending_promise_events = 0;  // reset
+    if (result->Uint32Value(context).FromJust() == 1) {
+      exit(1);
```
Comment (kevinkassimo) [inline libdeno/binding.cc]: Checking returned value and exit here is not quite ideal... However, if I were to use `os.exit(...)` from TS side in `promiseErrorExaminer` it would trigger segfault.

Not quite sure what I did wrong

File: libdeno/binding.cc [hunk 3]
```diff
@@ -322,6 +396,43 @@ bool Execute(v8::Local<v8::Context> context, const char* js_filename,
   return ExecuteV8StringSource(context, js_filename, source);
 }
 
+v8::Local<v8::Object> InitializeConstants(v8::Isolate* isolate,
+                                          v8::Local<v8::Context> context) {
+  auto constants_val = v8::Object::New(isolate);
```
Comment (ry) [inline libdeno/binding.cc]: Put these directly into the `libdeno` namespace, not `libdeno.constants`

File: libdeno/binding.cc [hunk 4]
```diff
@@ -322,6 +396,43 @@ bool Execute(v8::Local<v8::Context> context, const char* js_filename,
...
+
+  auto promise_reject_event_val = v8::Object::New(isolate);
+  CHECK(promise_reject_event_val
+            ->Set(context, deno::v8_str("kPromiseRejectWithNoHandler"),
```
Comment (ry) [inline libdeno/binding.cc]: put this directly into the libdeno namespace, not `libdeno.constants.promiseRejectEvents`

File: libdeno/libdeno_test.js [hunk 5]
```diff
@@ -133,3 +133,43 @@ global.DataBuf = () => {
...
+  }
+
+  (async () => {
+    try {
+      await fn();
+    } catch (e) {
+      assertOrSend(count === 2);
+    }
+  })();
+}
```
Comment (ry) [inline libdeno/libdeno_test.js]: nice work!

File: js/libdeno.ts [hunk 6]
```diff
@@ -20,6 +28,21 @@ interface Libdeno {
     ) => void
   ) => void;
 
+  setPromiseRejectHandler: (
+    handler: (
+      error: Error,
+      event: number,
```
Comment (ry) [inline js/libdeno.ts]: How about about 
```ts
event: "RejectWithNoHandler" | "HandlerAddedAfterReject" | "ResolveAfterResolved" | "RejectAfterResolved"
```

File: js/promise_util.ts [hunk 7]
```diff
@@ -0,0 +1,49 @@
+import { libdeno } from "./libdeno";
+
+const promiseRejectEvents = libdeno.constants.promiseRejectEvents;
+
+/* tslint:disable-next-line:no-any */
+const promiseRejectMap = new Map<Promise<any>, string>();
```
Comment (ry) [inline js/promise_util.ts]: :%s/promiseRejectMap/rejectMap/g

File: js/promise_util.ts [hunk 8]
```diff
@@ -0,0 +1,49 @@
...
+/* tslint:disable-next-line:no-any */
+const otherPromiseErrorMap = new Map<Promise<any>, string>();
```
Comment (ry) [inline js/promise_util.ts]: %s/otherPromiseErrorMap/otherErrorMap/g

File: js/promise_util.ts [hunk 9]
```diff
@@ -0,0 +1,49 @@
...
+    otherPromiseErrorMap.clear();
+  }
+  if (promiseRejectMap.size > 0) {
+    for (const msg of promiseRejectMap.values()) {
+      console.log(msg);
+    }
+    promiseRejectMap.clear();
+    return 1;
+  }
+  return 0;
```
Comment (ry) [inline js/promise_util.ts]: deno.exit() requires message passing - which probably doesn't work in this state of error.

maybe we should add libdeno.exit() as a way to quickly exit.. but i think your solution here is fine. maybe make the return value boolean.

File: js/libdeno.ts (hunk 6 above)
Comment (kevinkassimo) [reply js/libdeno.ts]: Event types from v8 here are integers. Not quite sure if we want to covert to string reprs

Comment (ry) [reply js/libdeno.ts]: The only concern would be about performance.. presumably numbers are faster.
Is this hot code?

Comment (kevinkassimo) [reply js/libdeno.ts]: The handler is invoked twice for each caught promise reject. Not quite sure if it is hot enough

Comment (ry) [reply js/libdeno.ts]: I think mapping the V8 numbers to strings in C++ isn't so bad. This will simply the libdeno JS interface quite a bit.

Comment (ry) [reply js/libdeno.ts]:
```c++
const char* PromiseRejectStr(enum v8::PromiseRejectEvent e) {
  switch (e) {
    case kPromiseRejectWithNoHandler:
      return "RejectWithNoHandler";
    case kPromiseHandlerAddedAfterReject:
      return "HandlerAddedAfterReject";
    case kPromiseResolveAfterResolved:
      return "ResolveAfterResolved";
    case kPromiseRejectAfterResolved:
      return "RejectAfterResolved";
  }
```

Comment (kevinkassimo) [reply js/libdeno.ts]: Thanks! Added the function.
