### PR TITLE
fix(lsp): store assigned compiler options for cache files

### LINKED ISSUE #31315: Goto Definiton doesn't work within NPM packages
if I'm using an npm package with the cache and not node_modules, I can use cmd click on a function to get its definition, but once I'm in that I can't continue to do that to look at related definitions in the package.

The same functionality works fine with JSR packages.

Version: Deno 2.5.6

### PR DESCRIPTION
**Pull request by nayeemrmn**
- Fixes #31315
- Fixes https://github.com/denoland/vscode_deno/issues/1335

### CODE REVIEW

File: cli/lsp/documents.rs [hunk 1]
```diff
@@ -1044,6 +1044,9 @@ pub struct DocumentModules {
   dep_info_by_scope: once_cell::sync::OnceCell<Arc<DepInfoByScope>>,
   modules_unscoped: Arc<WeakDocumentModuleMap>,
   modules_by_scope: Arc<BTreeMap<Arc<Url>, Arc<WeakDocumentModuleMap>>>,
+  #[allow(clippy::type_complexity)]
+  assigned_scopes:
+    Arc<DashMap<Arc<Uri>, (Option<Arc<Url>>, CompilerOptionsKey)>>,
```
Comment (bartlomieju) [inline cli/lsp/documents.rs]: I agree with `type_complexity` lint here - I don't understand what this is storing and a wrapper struct would be helpful here.

**Review by bartlomieju — DISMISSED** [review]
