### PR TITLE
chore: fix flaky lsp_testing_api test

### LINKED ISSUE #14568: test `lsp_testing_api` is flaky
This is essentially https://github.com/denoland/deno/pull/14562

```
---- integration::lsp::lsp_testing_api stdout ----
thread 'integration::lsp::lsp_testing_api' panicked at 'assertion failed: `(left == right)`

Diff < left / right > :
 Some(
     Object(***
         "id": Number(
             1,
         ),
         "message": Object(***
             "type": String(
                 "output",
             ),
             "value": String(
<                "test a\r\n\u***200b***",
>                "test a\r\n",
             ),
             "test": Object(***
                 "textDocument": Object(***
                     "uri": String(
                         "file:///tmp/deno-cli-test-1652249450976-343/test.ts",
                     ),
                 ***),
                 "id": String(
                     "891cf466cef92ef6ff7e7cf79ed6e74c8e04186342f795b73dad64226294e49e",
                 ),
             ***),
         ***),
     ***),
 )

', cli/tests/integration/lsp_tests.rs:5473:3
stack backtrace:
   0:     0x5578e3e7417c - std::backtrace_rs::backtrace::libunwind::trace::h91c465e73bf6c785
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x5578e3e7417c - std::backtrace_rs::backtrace::trace_unsynchronized::hae9da36f5d58b5f3
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x5578e3e7417c - std::sys_common::backtrace::_print_fmt::h7f499fa126a7effb
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x5578e3e7417c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h3e2b509ce2ce6007
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x5578e3e9ef5c - core::fmt::write::h753c7571fa063ecb
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/fmt/mod.rs:1168:17
   5:     0x5578e3e6af43 - std::io::Write::write_fmt::hb649ab67f71b6655
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/io/mod.rs:1660:15
   6:     0x5578e3e77192 - std::sys_common::backtrace::_print::h64941a6fc8b0ed9b
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x5578e3e77192 - std::sys_common::backtrace::print::hcf25e43e1a9b0766
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x5578e3e77192 - std::panicking::default_hook::***closure***::h78d3e6cf97fc623d
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:211:50
   9:     0x5578e3e76de1 - std::panicking::default_hook::hda898f8d3ad1a5ae
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:225:9
  10:     0x5578e3e778e3 - std::panicking::rust_panic_with_hook::h1a5ea2d6c23051aa
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:606:17
  11:     0x5578e3e77600 - std::panicking::begin_panic_handler::***closure***::h07f549390938b73f
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:502:13
  12:     0x5578e3e74624 - std::sys_common::backtrace::__rust_end_short_backtrace::h5ec3758a92cfb00d
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/sys_common/backtrace.rs:139:18
error: test failed, to rerun pass '-p deno --test integration_tests'
  13:     0x5578e3e77339 - rust_begin_unwind
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:498:5
  14:     0x5578e3e9cde1 - core::panicking::panic_fmt::h3a79a6a99affe1d5
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panicking.rs:116:14
  15:     0x5578e3fa7f6a - integration_tests::integration::lsp::lsp_testing_api::h2004bbfdee7936bd
  16:     0x5578e3e00f63 - core::ops::function::FnOnce::call_once::h1845a80638abc06e
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/ops/function.rs:227:5
  17:     0x5578e3e00f63 - test::__rust_begin_short_backtrace::h4f56ccea01b9889f
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/test/src/lib.rs:574:5
  18:     0x5578e3dffc4f - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h5afedf14a39ffa74
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/alloc/src/boxed.rs:1854:9
  19:     0x5578e3dffc4f - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::hd5aaa1b551e9ce71
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panic/unwind_safe.rs:271:9
  20:     0x5578e3dffc4f - std::panicking::try::do_call::h316eebee63f96d32
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:406:40
  21:     0x5578e3dffc4f - std::panicking::try::h662e31e84dd7ce52
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:370:19
  22:     0x5578e3dffc4f - std::panic::catch_unwind::h129c1b23f076663f
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panic.rs:133:14
  23:     0x5578e3dffc4f - test::run_test_in_process::h51d800d572f878ef
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/test/src/lib.rs:597:18
  24:     0x5578e3dffc4f - test::run_test::run_test_inner::***closure***::h71a47db4[3026](https://github.com/denoland/deno/runs/6382615880?check_suite_focus=true#step:34:3026)0854
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/test/src/lib.rs:491:39
  25:     0x5578e3e090b1 - test::run_test::run_test_inner::***closure***::h02edd5b3e2dab52a
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/test/src/lib.rs:518:37
  26:     0x5578e3e090b1 - std::sys_common::backtrace::__rust_begin_short_backtrace::h0838cfc8b0e995ec
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/sys_common/backtrace.rs:123:18
  27:     0x5578e3dd34af - std::thread::Builder::spawn_unchecked::***closure***::***closure***::h4c2725d7078043cd
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/thread/mod.rs:477:17
  28:     0x5578e3dd34af - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::hdf1aa612eed87270
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panic/unwind_safe.rs:271:9
  29:     0x5578e3dd34af - std::panicking::try::do_call::hc72f8de3706d18d6
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:406:40
  30:     0x5578e3dd34af - std::panicking::try::h63f01f54dbd0fb87
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:370:19
  31:     0x5578e3dd34af - std::panic::catch_unwind::h58bc464ae9b26453
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panic.rs:133:14
  32:     0x5578e3dd34af - std::thread::Builder::spawn_unchecked::***closure***::h6c065e19513e33e3
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/thread/mod.rs:476:30
  33:     0x5578e3dd34af - core::ops::function::FnOnce::call_once***vtable.shim***::hd143450c74f35c32
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/ops/function.rs:227:5
  34:     0x5578e3e7f793 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h49b6c7c5155a2296
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/alloc/src/boxed.rs:1854:9
  35:     0x5578e3e7f793 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::ha8b5234bfeb15105
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/alloc/src/boxed.rs:1854:9
  36:     0x5578e3e7f793 - std::sys::unix::thread::Thread::new::thread_start::h6f207dd842d64859
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/sys/unix/thread.rs:108:17
  37:     0x7fe579877609 - start_thread
  38:     0x7fe57964d163 - clone
  39:                0x0 - <unknown>


failures:
    integration::lsp::lsp_testing_api
```

https://github.com/denoland/deno/runs/6382615880?check_suite_focus=true

### PR DESCRIPTION
**Pull request by dsherret**
Closes #14568

### CODE REVIEW

File: cli/tests/integration/lsp_tests.rs [hunk 1]
```diff
@@ -5470,13 +5470,30 @@ Deno.test({
...
+    .as_object()
+    .unwrap()
+    .get("message")
+    .unwrap()
+    .as_object()
+    .unwrap()
+    .get("value")
+    .unwrap()
+    .as_str()
+    .unwrap();
```
Comment (dsherret) [inline cli/tests/integration/lsp_tests.rs:5485]: Brutal.

Comment (bartlomieju) [reply cli/tests/integration/lsp_tests.rs:5485]: Oooof

**Review by bartlomieju — APPROVED** [review]
