### PR TITLE
Fixed printing strings in arrays & objects without quotes

### LINKED ISSUE #607: Better console output
Currently when logging strings as members of objects to the console, it is a bit _ugly_.  For example:

```ts
console.log(["foo", "bar"]);
```

Will output:

```
[ foo, bar ]
```

Which is frustrating when trying to copy something out of the console.

### PR DESCRIPTION
**Pull request by Aaronepower**
fixes #607

### CODE REVIEW

File: tests/014_print_complex_objects.ts [hunk 1]
```diff
@@ -0,0 +1,2 @@
+console.log(["foo", "bar"]);
+console.log({"foo": "bar"});
```
Comment (ry) [inline tests/014_print_complex_objects.ts]: Could you use `js/unit_tests.ts` instead of `tests/`? ... these are relatively expensive to run.

Comment (Aaronepower) [reply tests/014_print_complex_objects.ts]: That's no problem. How would I capture `console.log`'s output in `js/unit_tests.ts`? I can't see a example that does that. Should I just call stringify directly?

Comment (ry) [reply tests/014_print_complex_objects.ts]: Yes, just do a unit test on stringify. I think the other console tests in unit_tests are not currently proper unit tests - they should be changed - but that'll be another commit.

**Comment by Aaronepower** [comment]
@ry Updated. Let me know if there's any more changes needed.

File: js/console.ts [hunk 2]
```diff
@@ -125,3 +136,5 @@ export class Console {
     }
   }
 }
+
+export { stringify };
```
Comment (ry) [inline js/console.ts]: Just put the export at the stringify's definition.

File: js/unit_tests.ts [hunk 3]
```diff
@@ -25,6 +26,14 @@ test(function tests_console_assert() {
   assertEqual(hasThrown, true);
 });
 
+test(function tests_console_stringify_complex_objects() {
+  // tslint:disable:no-any
+  assertEqual("foo", stringify(new Set<any>(), "foo"));
+  assertEqual(`[ "foo", "bar" ]`, stringify(new Set<any>(), ["foo", "bar"]));
+  assertEqual(`{ foo: "bar" }`, stringify(new Set<any>(), { foo: "bar" }));
+  // tslint:enable:no-any
+});
```
Comment (ry) [inline js/unit_tests.ts]: Cool - Thanks.

Comment (ry) [reply js/unit_tests.ts]: If you want to do a follow up PR - I would like to have these changes:
1. modifying tests_console_stringify_circular to call stringify instead that would be appreciated.
1. I would also like all the console tests to be moved to `js/console_test.ts` in a similiar way as `compiler_test.ts`
1. Use camel-case instead of snake-case for console test names. Follow `compiler_test.ts` as an example.

Comment (Aaronepower) [reply js/unit_tests.ts]: Alright, I've updated and I'll make another PR with those changes.
