### PR TITLE
fix(ext/node): session close during stream setup

### LINKED ISSUE #25168: HTTP2 request opened at same time Close is called throws
Version: Deno 1.46.0

```ts
const url = "http://127.0.0.1:4246";
const client = http2.connect(url)

// leave a request open to prevent immediate destroy
const req = client.request();
req.on("data", () => {});
req.on("error", (err) => console.error(err));
const reqClosePromise = Promise.withResolvers<void>();
req.on("close", () => { reqClosePromise.resolve() });

client.close();

await reqClosePromise.promise
```

Throws:

```
error: (in promise) BadResource: Bad resource ID
```

I will send a PR with a test and a fix

### PR DESCRIPTION
**Pull request by caleblloyd**
- Fixes #25168 
- Adds tests for #25143

### CODE REVIEW

File: ext/node/polyfills/http2.ts [hunk 1]
```diff
@@ -840,6 +840,11 @@ async function clientHttp2Request(
     reqHeaders,
   );
 
+  if (session.closed || session.destroyed) {
+    debugHttp2(">>> session closed during request promise");
+    throw new ERR_HTTP2_STREAM_CANCEL();
```
Comment (kt3k) [inline ext/node/polyfills/http2.ts:845]: I tried the below script with Node.js (v22.7) and it doesn't seem throwing in this situation (The below exits without showing an error):

```js
import http2 from "node:http2";
const url = "http://127.0.0.1:4246";
const connectPromise = Promise.withResolvers();
const client = http2.connect(url, {}, () => {
  connectPromise.resolve();
})

await connectPromise.promise

// leave a request open to prevent immediate destroy
const req = client.request();
req.on("data", () => {});
req.on("error", (err) => console.error(err));
const reqClosePromise = Promise.withResolvers();
req.on("close", () => { reqClosePromise.resolve() });

client.close();

await reqClosePromise.promise
```

Can you share the reasoning why throwing `ERR_HTTP2_STREAM_CANCEL` here?

Comment (caleblloyd) [reply ext/node/polyfills/http2.ts:845]: All open and pending streams are destroyed with `ERR_HTTP2_STREAM_CANCEL` here:

https://github.com/denoland/deno/blob/7e68cce8159d55fd597f0da3e00f794200b9928f/ext/node/polyfills/http2.ts#L410

I initially tried to just catch the error and wait for that logic to kick in, but I got errors running tests. State machine stopped but there are still outstanding promises.

Happy to change it, what would you recommend?

Comment (kt3k) [reply ext/node/polyfills/http2.ts:845]: Looked into this more, and it looked like the root cause of this is that we don't implement GOAWAY frame and streams can't be closed/destroyed normally.

https://github.com/denoland/deno/blob/97d1635343dc6e93c8dcf4b116922de5b9c57af3/ext/node/polyfills/http2.ts#L316-L317

I now think this implementation is a good compromise at this point.

**Review by kt3k — APPROVED** [review]
LGTM

@satyarohith Can you take another look at this?

**Comment by caleblloyd** [comment]
@satyarohith need me to make any other changes to this PR?

**Comment by caleblloyd** [comment]
The fix for stream closing was required to correctly implement the test, so that is why I put the fix and the test in the same PR as opposed to putting them in separate PRs

**Review by satyarohith — APPROVED** [review]
My concern with this script is that it doesn't match node's behaviour exactly but improves it by propagating the error via "error" event instead of throwing it.

Logs:
```
➜ deno run -A test.mjs 
Script started
Connect callback triggered
'connect' event triggered
Connection established
Request created
Closing client
error: Uncaught (in promise) BadResource: Bad resource ID
    at clientHttp2Request (node:http2:638:16)
    at Object.runMicrotasks (ext:core/01_core.js:690:26)
    at processTicksAndRejections (ext:deno_node/_next_tick.ts:53:10)
    at runNextTicks (ext:deno_node/_next_tick.ts:71:3)
    at eventLoopTick (ext:core/01_core.js:181:21)
    at async node:http2:670:37

➜ denod run -A test.mjs # this PR
Script started
Connect callback triggered
'connect' event triggered
Connection established
Request created
Closing client
'close' event triggered on client
'error' event triggered on request: The pending stream has been canceled
'close' event triggered on request
Script finished

➜ node test.mjs 
Script started
Connect callback triggered
'connect' event triggered
Connection established
Request created
Closing client
'response' event triggered on request
'data' event triggered on request
'end' event triggered on request
'close' event triggered on request
Script finished
'close' event triggered on client
```

<details>
<summary>script</summary>

```
import http2 from "node:http2";

const url = "http://127.0.0.1:4246";
const connectPromise = Promise.withResolvers();

console.log("Script started");

const client = http2.connect(url, {}, () => {
  console.log("Connect callback triggered");
  connectPromise.resolve();
});

client.on('connect', () => console.log("'connect' event triggered"));
client.on('error', (err) => console.log("'error' event triggered on client:", err.message));
client.on('close', () => console.log("'close' event triggered on client"));

await connectPromise.promise;
console.log("Connection established");

// leave a request open to prevent immediate destroy
const req = client.request();
console.log("Request created");

req.on("response", (headers) => console.log("'response' event triggered on request"));
req.on("data", (chunk) => console.log("'data' event triggered on request"));
req.on("end", () => console.log("'end' event triggered on request"));
req.on("error", (err) => console.log("'error' event triggered on request:", err.message));
req.on("close", () => {
  console.log("'close' event triggered on request");
  reqClosePromise.resolve();
});

const reqClosePromise = Promise.withResolvers();

console.log("Closing client");
client.close();

await reqClosePromise.promise;
console.log("Script finished");
```
</details>

LGTM - we should match node's behaviour in future iterations.

**Review by satyarohith — COMMENTED** [review]
Thanks for the contribution @caleblloyd!

**Comment by caleblloyd** [comment]
Thanks for the review!  I agree, once `session.close()` implements graceful connection closing the pending request should attempt to be completed, and there should be no error on the request with the test case you posted.
