### PR TITLE
fix(node): seperate worker module cache

### LINKED ISSUE #17248: Support for SvelteKit
Prompted by discussion on Discord I tried to get SvelteKit working in Deno.

After an hour of debugging I found the main blocker: by default SvelteKit installed Node adapter, which does a bit of setup that is not needed in Deno and makes the project crash, namely:
https://github.com/sveltejs/kit/blob/e7bc0be2b25aff5ac151e3d83b771ad80cac1ab8/packages/kit/src/exports/node/polyfills.js#L6-L28
which installs polyfills from `undici` for various Web APIs like `fetch` or `Response`. These objects work slightly differently in Deno and arguably installing them in Deno is not needed. 

I think the way forward would be to get a Deno dedicated adapter that would essentially be a noop as there's no need to change anything to make SvelteKit work.

Of course it would be very nice if `deno run -A npm:create-svelte@latest` would set up a project in a way that requires no changes (namely making specifiers use `npm:` prefixes).

### LINKED ISSUE #23461: node:worker_threads module cache is shared
The module cache is seperate in Node. 

```javascript
import fs from 'node:fs/promises';
import { Worker, isMainThread } from 'node:worker_threads';

await fs.writeFile('mod.mjs', 'export default ' + isMainThread);

const path = new URL('mod.mjs', import.meta.url);
const i = await import(path.href);
console.log(i);

if (isMainThread) {
  const worker = new Worker(new URL('main.mjs', import.meta.url));
  worker.on('message', (msg) => console.log(msg));
}
```

```
$ node main.mjs
[Module: null prototype] { default: true }
[Module: null prototype] { default: false }
$ deno run -A main.mjs
[Module: null prototype] { default: true }
[Module: null prototype] { default: true }
```

SvelteKit's build system (vite plugin) relies on this, it imports a manifest file, modifies it and imports from a worker thread. Ref https://github.com/denoland/deno/issues/17248

### PR DESCRIPTION
**Pull request by littledivy**
Construct a new module graph container for workers instead of sharing it with the main worker.

Fixes #17248
Fixes #23461

### CODE REVIEW

File: cli/module_loader.rs
Comment (dsherret) [inline cli/module_loader.rs:1]: How's the memory usage? Does it reuse the `Arc<str>` when it can? (ex. for remote modules)

Also, what happens with `--reload`?

File: tests/specs/node/worker_threads_cache/__test__.jsonc [hunk 1]
```diff
@@ -0,0 +1,4 @@
+{
```
Comment (satyarohith) [inline tests/specs/node/worker_threads_cache/__test__.jsonc:1]: nit: it would be nice to convert this test into a step under `worker_threads` folder instead of creating `worker_threads_cache` folder.

Comment (satyarohith) [reply tests/specs/node/worker_threads_cache/__test__.jsonc:1]: Hmm. I thought it would be clean to convert several tests of a module into steps but it will break reporting.

Comment (satyarohith) [reply tests/specs/node/worker_threads_cache/__test__.jsonc:1]: After https://github.com/denoland/deno/pull/23667, you can now declare serveral tests in `__test__.jsonc` itself.

File: cli/module_loader.rs [hunk 2]
```diff
@@ -221,13 +235,22 @@ impl ModuleLoadPreparer {
...
 
+#[derive(Clone)]
 struct PreparedModuleLoader {
   emitter: Arc<Emitter>,
   graph_container: Arc<ModuleGraphContainer>,
   parsed_source_cache: Arc<ParsedSourceCache>,
 }
 
 impl PreparedModuleLoader {
+  pub fn for_worker(&self, graph_container: Arc<ModuleGraphContainer>) -> Self {
```
Comment (dsherret) [inline cli/module_loader.rs:246]: @littledivy I'm going to do a commit to this PR because I was just looking at this code for making more stuff an `Rc`.

**Review by bartlomieju — COMMENTED** [review]
Drive-by: can we add tests for both Web and Node workers that verify this behavior?

**Comment by dsherret** [comment]
Looks like some wpt tests are failing now.

**Comment by littledivy** [comment]
> Looks like some wpt tests are failing now.

It's a new test thats passing now.

**Comment by bartlomieju** [comment]
Other issues that might potentially get fixed by this one:
- https://github.com/denoland/deno/issues/21035
- https://github.com/denoland/deno/issues/18414
- https://github.com/denoland/deno/issues/20104

File: cli/module_loader.rs
Comment (dsherret) [reply cli/module_loader.rs:1]: @littledivy do you think we could reduce memory usage by sharing the strings in memory when they're the same?

**Review by dsherret — COMMENTED** [review]
See https://github.com/denoland/deno/pull/23634#discussion_r1586510102

File: cli/module_loader.rs
Comment (littledivy) [reply cli/module_loader.rs:1]: yeah, maybe we could store specifier -> hash mapping in a shared container and compare that in the file fetcher. Doing this check without comparing specifiers first may be expensive but more effective in some cases.

**Review by dsherret — APPROVED** [review]
LGTM. Seems like there's some errors after merge though.
