### PR TITLE
fix(#6368): "deno test" should respect NO_COLOR=true

### LINKED ISSUE #6368: deno test does not completely respect NO_COLOR=true
`deno test` does not completely respect `NO_COLOR=true`. 

I like to run my scripts from within vim, whose command output buffer does not apply ANSI escape codes by default. `deno run` respects `NO_COLOR=true` by not producing ANSI escape codes, but `deno test` still produces some.

---

**`deno run`:**

Running the following file within vim:
```typescript
#!/usr/bin/env deno run

if (import.meta.main) {
  console.log('Hello world!');
}
```

Produces the following output with ANSI escape codes:
```
:!/Users/michaelwm/Development/test.ts
^[[0m^[[38;5;10mCompile^[[0m file:///Users/michaelwm/Development/test.ts
Hello world!
```

Adding `NO_COLOR=true`:
```typescript
#!/usr/bin/env NO_COLOR=true deno run

if (import.meta.main) {
  console.log('Hello world!');
}
```

Correctly produces:
```
:!/Users/michaelwm/Development/test.ts
Compile file:///Users/michaelwm/Development/test.ts
Hello world!
```

---

**`deno test`:**

Running the following file within vim:
```typescript
#!/usr/bin/env deno test

import { assertEquals } from 'https://deno.land/std/testing/asserts.ts';

Deno.test('1 + 1 = 2', () => assertEquals(1 + 1, 2));
```

Produces output with ANSI escape codes:
```
:!/Users/michaelwm/Development/test.ts
^[[0m^[[38;5;10mCompile^[[0m file:///Users/michaelwm/Development/test.ts
running 1 tests
test 1 + 1 = 2 ... ^[[32mok^[[39m ^[[90m^[[3m(3ms)^[[23m^[[39m

test result: ^[[32mok^[[39m. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out ^[[90m^[[3m(3ms)^[[23m^[[39m
```

Adding `NO_COLOR=true`:
```typescript
#!/usr/bin/env NO_COLOR=true deno test

import { assertEquals } from 'https://deno.land/std/testing/asserts.ts';

Deno.test('1 + 1 = 2', () => assertEquals(1 + 1, 2));
```

Incorrectly produces:
```
:!/Users/michaelwm/Development/test.ts
Compile file:///Users/michaelwm/Development/test.ts
running 1 tests
test 1 + 1 = 2 ... ^[[32mok^[[39m (10ms)

test result: ^[[32mok^[[39m. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out (11ms)
```

With the `ok` from test output still surrounded by ANSI escape codes, but all others, such as compilation colors, dropped.

### PR DESCRIPTION
**Pull request by uki00a**
Closes #6368.

### CODE REVIEW

File: cli/js/testing.ts [hunk 1]
```diff
@@ -9,9 +9,6 @@ import { metrics } from "./ops/runtime.ts";
 import { resources } from "./ops/resources.ts";
 import { assert } from "./util.ts";
```
Comment (uki00a) [inline cli/js/testing.ts:11]: At this point, `op_start` is not yet called.
So, `Deno.noColor` is set to `false` regardless of `NO_COLOR`.

File: cli/tests/integration_tests.rs [hunk 2]
```diff
@@ -1118,6 +1118,22 @@ fn repl_test_assign_underscore_error() {
...
+    None,
+    Some(vec![("NO_COLOR".to_owned(), "true".to_owned())]),
+    false,
+  );
+  // ANSI escape codes should be stripped.
+  assert!(out.contains("test success ... ok"));
+  assert!(out.contains("test fail ... FAILED"));
+  assert!(out.contains("test ignored ... ignored"));
+  assert!(out.contains("test result: FAILED. 1 passed; 1 failed; 1 ignored; 0 measured; 0 filtered out"));
+}
```
Comment (bartlomieju) [inline cli/tests/integration_tests.rs:1135]: 👍
