### PR TITLE
fix(npm): do not "npm install" when npm specifier happens to match package.json entry

### LINKED ISSUE #18605: "deno cache --reload <package_name>" reloads all dependencies in Node project
I created a new `next.js` project like so:
```
$ deno run -A npm:create-next-app@latest next-app
$ next-app
```

I tried `deno task dev` but got following error:
```
error: Could not find npm package '@types/node' matching 18.15.11. Try retrieving the latest npm package information by running with --reload
```

`deno cache --reload npm:@types/node` fixed the problem, but it reloaded all the dependencies specified in `package.json` in the current working directory.

### PR DESCRIPTION
**Pull request by dsherret**
I thought this would be more difficult than it was, but actually we can just keep track of this in the `CliGraphResolver`.

Closes #18605

### CODE REVIEW

File: cli/tests/integration/cache_tests.rs [hunk 1]
```diff
@@ -107,3 +108,22 @@ itest!(package_json_basic {
...
   exit_code: 0,
 });
+
+#[test]
+fn cache_matching_package_json_dep_should_not_reload() {
+  let context = TestContextBuilder::for_npm().use_temp_cwd().build();
+  let temp_dir = context.temp_dir();
+  temp_dir.write(
+    "package.json",
+    r#"{ "dependencies": { "@types/node": "18.8.2", "@denotest/esm-basic": "*" } }"#,
```
Comment (dsherret) [inline cli/tests/integration/cache_tests.rs:118]: On main, this also installs `@denotest/esm-basic`

**Review by bartlomieju — APPROVED** [review]
LGTM, nice abstraction!
