### PR TITLE
fix(lsp): correct `parameterNames.suppressWhenArgumentMatchesName` and `variableTypes.suppressWhenTypeMatchesName`

### LINKED ISSUE #16468: lsp: Inlay hints option `suppressWhenArgumentMatchesName` meaning flipped
Deno version: 1.27.0
OS: Windows 10

With this VS Code configuration:

```json
{
    "deno.enable": true,
    "deno.inlayHints.parameterNames.enabled": "all",
    "deno.inlayHints.parameterNames.suppressWhenArgumentMatchesName": true
}
```

VS Code displays:
image

But with the configuration:
```json
{
    "deno.enable": true,
    "deno.inlayHints.parameterNames.enabled": "all",
    "deno.inlayHints.parameterNames.suppressWhenArgumentMatchesName": false
}
```

It displays:
image

I expect that when `suppressWhenArgumentMatchesName` is true that inlay hints when names match are suppressed, not the other way around.

I can't tell if this is a `vscode_deno` issue or an LSP issue, but since the related commit in the VS Code extension doesn't seem to do much except add preset entries, I'm posting it here.

### PR DESCRIPTION
**Pull request by dsherret**
Closes #16468

### CODE REVIEW

File: cli/lsp/tsc.rs [hunk 1]
```diff
@@ -3020,7 +3020,7 @@ impl From<&config::WorkspaceSettings> for UserPreferences {
         inlay_hints.variable_types.enabled,
       ),
       include_inlay_variable_type_hints_when_type_matches_name: Some(
-        inlay_hints
+        !inlay_hints
           .variable_types
           .suppress_when_argument_matches_name,
```
Comment (dsherret) [inline cli/lsp/tsc.rs:3025]: This name seems wrong. Probably should be `suppress_when_type_matches_name`?

Comment (dsherret) [reply cli/lsp/tsc.rs:3025]: Yes, it is according to the blog post. I'll fix it.

**Review by bartlomieju — APPROVED** [review]
LGTM, good catch
