### PR TITLE
fix(lsp/format): language formatter used should be based on language id

### LINKED ISSUE #11897: lsp: formatting `json` syntax in a non `.json` file causes error
If you have the following in a `foo.importmap` file:

```json
{
  "imports": {}
}
```

And your editor (Nova in my case) is configured to use the `json` syntax for the `.importmap` file, using the Deno LSP to format the file results in an error:

```
Unable to format "file://[redacted]/foo.importmap". Likely due to unrecoverable syntax errors in the file.
```

The weird thing is, if you make the content this instead:

```
{
  }
```

The Deno LSP formats it just fine to this:

```
{
}
```

Also, if you keep the original contents but change the file extension to `.json` it formats fine.

There must be some sort of edge case LSP bug?

### PR DESCRIPTION
**Pull request by dsherret**
Closes #11897

### CODE REVIEW

File: cli/lsp/documents.rs [hunk 1]
```diff
@@ -93,6 +93,31 @@ pub enum LanguageId {
...
 impl LanguageId {
+  pub fn as_media_type(&self) -> MediaType {
+    match self {
+      LanguageId::JavaScript => MediaType::JavaScript,
+      LanguageId::Jsx => MediaType::Jsx,
+      LanguageId::TypeScript => MediaType::TypeScript,
+      LanguageId::Tsx => MediaType::Tsx,
+      LanguageId::Json => MediaType::Json,
+      LanguageId::JsonC => MediaType::Json,
+      LanguageId::Markdown | LanguageId::Unknown => MediaType::Unknown,
```
Comment (satyarohith) [inline cli/lsp/documents.rs:104]: Should `MediaType` be `MediaType::Markdown` for `LanguageId::Mardown`?

Comment (dsherret) [reply cli/lsp/documents.rs:104]: `MediaType::Markdown` doesn't exist. I'm not sure it's worth it to add one (maybe once we get a bug for something).

**Review by crowlKats — APPROVED** [review]
LGTM - no comments
