### PR TITLE
Fix behavior for extensionless files with .mime file

### LINKED ISSUE #1776: Problem with .mime files for modules imported without extension
`.mime` files have been used in some way to instruct TS compiler how to resolve a file.
For example, for a file `no_ext`:
```ts
console.log("NO_EXT");
```
Creating a file `no_ext.mime` with content type
```
application/javascript
```
allows `deno no_ext` to run the file as if it is a JavaScript file.

However, this does not work if `no_ext` is imported. Suppose we have a file `import_no_ext.ts`:
```ts
import "./no_ext";
```
Running `deno import_no_ext.ts` would instead crash with error:
```
Uncaught Error: Debug Failure. File /Users/kevinqian/Desktop/Programming/Deno/test/no_ext has unknown extension.
    at fail (deno/third_party/node_modules/typescript/lib/typescript.js:1462:23)
    at extensionFromPath (deno/third_party/node_modules/typescript/lib/typescript.js:15845:48)
    at deno/third_party/node_modules/typescript/lib/typescript.js:20696:30
    at resolveModuleNamesWorker (deno/third_party/node_modules/typescript/lib/typescript.js:20688:69)
    at resolveModuleNamesReusingOldState (deno/third_party/node_modules/typescript/lib/typescript.js:20909:20)
    at processImportedModules (deno/third_party/node_modules/typescript/lib/typescript.js:22242:29)
    at findSourceFile (deno/third_party/node_modules/typescript/lib/typescript.js:22050:47)
    at deno/third_party/node_modules/typescript/lib/typescript.js:21903:75
    at getSourceFileFromReferenceWorker (deno/third_party/node_modules/typescript/lib/typescript.js:21876:34)
    at processSourceFile (deno/third_party/node_modules/typescript/lib/typescript.js:21903:75)
```

One thing to note is that `codeFetch` does successfully grab `MediaType.JavaScript` correctly for `no_ext`. This error is emitted somewhere inside of the TS compiler that our current compiler instance code does not control.

/to @kitsonk

### PR DESCRIPTION
**Pull request by kevinkassimo**
Closes #1776

There are 2 separate issues addressed here that both contribute to the issue:

1. In rollup config file we failed to include `ts.Extension`, resulting in `ts.Extension` become `undefined` in the bundle.

2. In `js/compiler.ts` we did not specify that we allow files of non-TS extensions => This would result in the following lines to fail:
https://github.com/Microsoft/TypeScript/blob/ed8c81a5638c7d745cb8541137ad6990da045467/src/compiler/program.ts#L2151-L2161
```ts
function getSourceFileFromReferenceWorker(...) {
  // ...
  const sourceFileNoExtension = options.allowNonTsExtensions && getSourceFile(fileName);
  if (sourceFileNoExtension) return sourceFileNoExtension;
  // ...

  const sourceFileWithAddedExtension = forEach(supportedExtensions, extension => getSourceFile(fileName + extension)); // Trying with all possibly supported extensions
  // ...
}
```
Without `allowNonTsExtensions` set to true in options, the compiler would try out all possible file names with extensions but never check the original extensionless one. This causes the behavior in debug log as mentioned in https://github.com/denoland/deno/issues/1776#issuecomment-463812025

/cc @kitsonk

### CODE REVIEW

**Comment by kevinkassimo** [comment]
@ry AppVeyor is reporting something like `ninja explain: rust_crates/libwebpki_roots.rlib is dirty`. Could you check what is the problem?

File: js/compiler.ts [hunk 1]
```diff
@@ -169,7 +169,8 @@ class Compiler implements ts.LanguageServiceHost, ts.FormatDiagnosticsHost {
     resolveJsonModule: true,
     sourceMap: true,
     stripComments: true,
-    target: ts.ScriptTarget.ESNext
+    target: ts.ScriptTarget.ESNext,
+    allowNonTsExtensions: true
```
Comment (kitsonk) [inline js/compiler.ts]: should be in alphabetical order

File: rollup.config.js [hunk 2]
```diff
@@ -270,6 +270,7 @@ export default function makeConfig(commandOptions) {
             "ScriptKind",
             "ScriptSnapshot",
             "ScriptTarget",
+            "Extension",
```
Comment (kitsonk) [inline rollup.config.js]: Should be in alphabetical order
