### PR TITLE
fix(test): throw when Deno.test() is called during test execution

### LINKED ISSUE #30787: Nested tests not running, silently passing
I just discovered that not only do my tests not pass, but they havent even been running. 
That is not the issue here. This was my fault. I did my tests incorrectly, nesting them in a way that deno doesn't support:
```ts
Deno.test("category",
async () => {
    try {
        Deno.test("name", async () => {
            // test logic
        }
        // more tests
    } 
}
```
This was completely incorrect. You cannot nest a Deno.test in a Deno.test.

The problem I'm raising is that the entire time, my incorrect tests never errored or even showed any warnings in the linter. The tests would show as passing when I ran them even though none of these tests were actually being run.

Version: Deno 2.5.1

### PR DESCRIPTION
**Pull request by pmarchini**
Fixes #30787.

`Deno.test()` was being accepted even when called from inside a running test callback.  
That means nested registrations could silently be ignored and tests looked like they passed.

Now `Deno.test()` calls made from inside a running test are rejected immediately.  
Instead of silently registering too late, they fail with a clear error:

`Nested Deno.test() calls are not supported. Use t.step() for nested tests.`

This makes the misuse explicit and points users to `t.step()`.

### CODE REVIEW

File: cli/ops/testing.rs
Comment (dsherret) [inline cli/ops/testing.rs]: Maybe `register` should error instead? That way the borrow only needs to happen once.

Comment (pmarchini) [reply cli/ops/testing.rs]: sure! Sounds good to me!

thanks for the pointer!

**Comment by bartlomieju** [comment]
Nice fix!

**Comment by pmarchini** [comment]
I've noticed the failures in the CI, I'm going to put the PR in draft again until it’s fixed 🚀

File: tests/unit_node/_fs/_fs_open_test.ts [hunk 1]
```diff
@@ -397,15 +397,13 @@ Deno.test("[std/node/fs] open callback isn't called twice if error is thrown", a
       await Deno.remove(tempFile);
     },
   });
+});
 
-  Deno.test({
-    name: "SYNC: open file with flag set to 0 (readonly)",
```
Comment (bartlomieju) [inline tests/unit_node/_fs/_fs_open_test.ts:402]: Nice catch 👍
