### PR TITLE
fix: display "-0" for -0

### LINKED ISSUE #2276: Print weird behavior with negative zeros
I am writing a test case and found the weird behavior of printing `-0`.

It caused my test case to fail

### Test code

```typescript
console.log(-0);
```

### Print in the chrome

屏幕快照 2019-05-03 15 06 11

### Print in Node.js

屏幕快照 2019-05-03 15 07 01

### Print in Deno

屏幕快照 2019-05-03 15 04 41

### PR DESCRIPTION
**Pull request by kevinkassimo**
Closes #2276

Added special handling code in js/console.ts

### CODE REVIEW

**Comment by ry** [comment]
@kevinkassimo rebased your build so it will go thru ci faster

File: js/console.ts [hunk 1]
```diff
@@ -122,6 +122,8 @@ function stringify(
     case "string":
       return value;
     case "number":
+      // Special handling of -0
+      return Object.is(value, -0) ? "-0" : `${value}`;
```
Comment (ry) [inline js/console.ts]: Does node do this?

Comment (kevinkassimo) [reply js/console.ts]: Yes, https://github.com/nodejs/node/blob/8876ac5c358114f0f88424f6737ca4b89fc9e6c7/lib/internal/util/inspect.js#L1026-L1029
