### PR TITLE
fix(ext/node): support proxy http request

### LINKED ISSUE #27692: Wrong path when using HTTP proxy in Node API `http`
Version: Deno 2.1.5

TLDR: when `http.request`'s opinions include proxy settings and `options.path` is a full URL (e.g., `http://httpbin.org/200`), the website that proxy server accesses should be `http://httpbin.org/200`, but in Deno it is `http://httpbin.org/http://httpbin.org/200`.

POC:
```js
import axios from "axios";
const instance = axios.create({
  baseURL: "http://httpbin.org/",
  proxy: {
    protocol: "http",
    host: "127.0.0.1",
    port: 8892,
  },
});
try {
  const resp = await instance.get("/get");
  console.log("success", resp.config);
} catch (e) {
  console.log(e);
}
```

For convenience, I use Axios as demo, and related code is [here](https://github.com/axios/axios/blob/bad6d8b97b52c0c15311c92dd596fc0bff122651/lib/adapters/http.js#L464C11-L464C28). When I add a patch `options.path = new URL(options.path).pathname;`, it becomes correct.
This demo requires a http proxy running at port 8892 (such as Fiddler or mitmproxy).

In Node.JS, it can get `http://httpbin.org/get` correctly. In Deno, it gets a 404, while Fiddler shows it is requesting `http://httpbin.org/http://httpbin.org/get`

### PR DESCRIPTION
**Pull request by kt3k**
closes #27692

This PR add support of proxy http request to `node:http.request`.

Passing the full url in `path` seems causing proxy http request in Node.js (ref: https://stackoverflow.com/questions/3862813/how-can-i-use-an-http-proxy-with-node-js-http-client ), and `axios` seems using this feature as pointed in #27692 (strangely I couldn't find a native test case that tests this feature though..)

This PR enhances `op_node_http_request_with_conn` to accept extra `request_path`. If it's passed, it overwrites the default uri of `Request` struct and causes proxy request to the server.

### CODE REVIEW

File: ext/node/ops/http.rs [hunk 1]
```diff
@@ -247,11 +251,17 @@ where
...
-    .unwrap_or_else(|| path.to_string())
-    .parse()
-    .map_err(|_| ConnError::InvalidUrl(url_parsed.clone()))?;
+  if let Some(request_path) = request_path {
+    *request.uri_mut() = request_path
+      .parse()
+      .map_err(|_| ConnError::InvalidPath(request_path.clone()))?;
+  } else {
+    *request.uri_mut() = query
+      .map(|q| format!("{}?{}", path, q))
```
Comment (satyarohith) [inline ext/node/ops/http.rs:260]: Unfortunate that there is no method that returns both path and query.

**Review by satyarohith — APPROVED** [review]
LGTM
