### PR TITLE
Simplify src fetch logic AND Auto append suffix in cache search

### LINKED ISSUE #1202: Deno fails to find extension less imports in cache
ex:
```
➜  ~ deno https://deno.land/x/examples/example_test.ts
Downloading https://deno.land/x/examples/example_test.ts
Downloading https://deno.land/x/testing/testing.ts
Downloading https://deno.land/x/testing/util
Downloading https://deno.land/x/testing/util.ts
running 2 tests
test t1
... ok
test t2
... ok

test result: ok. 2 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

➜  ~ deno https://deno.land/x/examples/example_test.ts
Downloading https://deno.land/x/testing/util
running 2 tests
test t1
... ok
test t2
... ok

test result: ok. 2 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out
```

### PR DESCRIPTION
**Pull request by kevinkassimo**
Closes #1202 

This PR simplifies `get_source_code` logic and perform auto suffix appending attempts when searching local cache.

`fetch_remote_source` become only fetching remote sources
`fetch_local_source` is added for local/cached sources

Before:
```sh
# with NO cache
$ deno --allow-net https://deno.land/x/net/file_server.ts
Downloading https://deno.land/x/net/file_server.ts
Compiling https://deno.land/x/net/file_server.ts
Downloading https://deno.land/x/net/http
Downloading https://deno.land/x/net/http.ts
Downloading https://deno.land/x/net/bufio.ts
Downloading https://deno.land/x/net/textproto.ts
Downloading https://deno.land/x/net/http_status
Downloading https://deno.land/x/net/http_status.ts
Downloading https://deno.land/x/net/util
Downloading https://deno.land/x/net/util.ts
Compiling https://deno.land/x/net/http.ts
# ...
HTTP server listening on http://0.0.0.0:4500/

# with cached
$ deno --allow-net https://deno.land/x/net/file_server.ts
Downloading https://deno.land/x/net/http
Downloading https://deno.land/x/net/http_status
Downloading https://deno.land/x/net/util
HTTP server listening on http://0.0.0.0:4500/
```

After:
```sh
# with NO cache
$ deno --allow-net https://deno.land/x/net/file_server.ts
Downloading https://deno.land/x/net/file_server.ts...
Compiling https://deno.land/x/net/file_server.ts
Downloading https://deno.land/x/net/http... NOT FOUND
Downloading https://deno.land/x/net/http.ts...
Downloading https://deno.land/x/net/bufio.ts...
Downloading https://deno.land/x/net/textproto.ts...
Downloading https://deno.land/x/net/http_status... NOT FOUND
Downloading https://deno.land/x/net/http_status.ts...
Downloading https://deno.land/x/net/util... NOT FOUND
Downloading https://deno.land/x/net/util.ts...
Compiling https://deno.land/x/net/http.ts
# ...
HTTP server listening on http://0.0.0.0:4500/

# with cache
$ deno --allow-net https://deno.land/x/net/file_server.ts
HTTP server listening on http://0.0.0.0:4500/
```

### CODE REVIEW

File: src/deno_dir.rs [hunk 1]
```diff
@@ -136,38 +137,78 @@ impl DenoDir {
...
+    for ext in extensions.iter() {
+      let filename = format!("{}{}", filename, ext);
+      let module_name = format!("{}{}", module_name, ext);
+      let p = Path::new(&filename);
+      // We write a special ".mime" file into the `.deno/deps` directory along side the
+      // cached file, containing just the media type.
+      let mut media_type_filename = filename.to_string();
+      media_type_filename.push_str(".mime");
+      let mt = Path::new(&media_type_filename);
+      eprintln!("Try downloading {}...", &module_name);
```
Comment (ry) [inline src/deno_dir.rs]: Please keep it "Downloading"

Comment (kevinkassimo) [reply src/deno_dir.rs]: I have actually made some changes to this just now. Now it looks like
```sh
Downloading https://deno.land/x/net/file_server.ts... DONE
Compiling https://deno.land/x/net/file_server.ts
Downloading https://deno.land/x/net/http... NOT FOUND
Downloading https://deno.land/x/net/http.ts... DONE
Downloading https://deno.land/x/net/bufio.ts... DONE
Downloading https://deno.land/x/net/textproto.ts... DONE
Downloading https://deno.land/x/net/http_status... NOT FOUND
Downloading https://deno.land/x/net/http_status.ts... DONE
Downloading https://deno.land/x/net/util... NOT FOUND
Downloading https://deno.land/x/net/util.ts... DONE
Compiling https://deno.land/x/net/http.ts
...
HTTP server listening on http://0.0.0.0:4500/
```

Comment (ry) [reply src/deno_dir.rs]: I'd rather you keep it as a single line - in the case of an error it can be printed too. The reason is that I want to refactor this whole bit soon with progress bars - so I prefer if you keep it the same and as simple as possible for future refactors.

Comment (kevinkassimo) [reply src/deno_dir.rs]: Oh okay. Done.

File: src/deno_dir.rs [hunk 2]
```diff
@@ -136,38 +137,81 @@ impl DenoDir {
...
-      deno_fs::write_file(&p, source.as_bytes(), 0o666)?;
-      deno_fs::write_file(&mt, content_type.as_bytes(), 0o666)?;
-      (source, map_content_type(&p, Some(&content_type)))
-    } else {
-      let source = fs::read_to_string(&p)?;
-      // .mime file might not exists with bundled deps
+  ) -> DenoResult<Option<CodeFetchOutput>> {
+    let extensions = ["", ".ts", ".js"];
+    for ext in extensions.iter() {
+      let filename = format!("{}{}", filename, ext);
```
Comment (F001) [inline src/deno_dir.rs]: Do not use `format!` for concatenating strings. This is considered an [anti-pattern](https://github.com/rust-unofficial/patterns/blob/master/idioms/concat-format.md).

Comment (F001) [reply src/deno_dir.rs]: There are several ways to do this. Please refer to the benchmark result https://github.com/hoodie/concatenation_benchmarks-rs

Comment (kevinkassimo) [reply src/deno_dir.rs]: Thanks for pointing out. I'll go with `array_concat` as it seems simple enough and fast

File: src/deno_dir.rs [hunk 3]
```diff
@@ -136,38 +137,81 @@ impl DenoDir {
...
+      // this is okay for local source: maybe_content_type_str will be None
       let maybe_content_type_string = fs::read_to_string(&mt).ok();
       // Option<String> -> Option<&str>
       let maybe_content_type_str =
         maybe_content_type_string.as_ref().map(String::as_str);
-      (source, map_content_type(&p, maybe_content_type_str))
-    };
-    Ok(src)
+      return Ok(Some(CodeFetchOutput {
+        module_name: module_name.clone(),
```
Comment (F001) [inline src/deno_dir.rs]: The `clone()` seems unnecessary?

Comment (kevinkassimo) [reply src/deno_dir.rs]: Hmm `module_name.clone()` is unnecessary, but `filename.clone()` is still needed

Comment (kevinkassimo) [reply src/deno_dir.rs]: Also I'll make a final push after you complete review... (travis is jammed)

Comment (F001) [reply src/deno_dir.rs]: why? You have created a local `filename : String` which shadows `filename: &str` in the argument.

Comment (kevinkassimo) [reply src/deno_dir.rs]: `let mt = Path::new(&media_type_filename);`

Comment (F001) [reply src/deno_dir.rs]: `p` is inactive after its last usage. It should compile when NLL is enabled. Before that, we can only bypass this restriction (annoying):
```rust
let filename = ...
{
  let p = Path::new(&filename);
  ...
}
// move filename
```

Comment (ry) [reply src/deno_dir.rs]: Add a TODO ?

Comment (F001) [reply src/deno_dir.rs]: Err, `map_content_type(&p, Some(&content_type))` should also move to  another place... Yeah, it depends on you whether to choose this style.

Comment (kevinkassimo) [reply src/deno_dir.rs]: @F001 I'll drop it and add a TODO
