### PR TITLE
fix(repl): Complete declarations

### LINKED ISSUE #10962: REPL does not complete declarations
For example...

```
> const myVar = {};
undefined
> my<TAB>
```

...does nothing.

I'm not sure if this is a bug or a feature that just hasn't been done so please categorize accordingly.

### PR DESCRIPTION
**Pull request by dsherret**
Closes #10962

### CODE REVIEW

File: cli/tools/repl.rs [hunk 1]
```diff
@@ -50,56 +50,42 @@ impl EditorHelper {
...
-
-    let word = &line[start..end];
-    let word = word.strip_prefix(is_word_boundary).unwrap_or(word);
-    let word = word.strip_suffix(is_word_boundary).unwrap_or(word);
-
-    let fallback = format!(".{}", word);
+  fn get_global_lexical_scope_names(&self) -> Vec<String> {
+    let evaluate_response = self
+      .post_message(
+        "Runtime.globalLexicalScopeNames",
```
Comment (dsherret) [inline cli/tools/repl.rs:57]: .@caspervonb gave me the tip here: https://chromedevtools.github.io/devtools-protocol/v8/Runtime/#method-globalLexicalScopeNames

File: cli/tools/repl.rs [hunk 2]
```diff
@@ -113,32 +99,83 @@ impl Completer for EditorHelper {
...
+      let mut candidates = self
+        .get_expression_property_names("globalThis")
+        .into_iter()
+        .chain(self.get_global_lexical_scope_names())
+        .filter(|n| n.starts_with(expr))
+        .collect::<Vec<_>>();
+
+      // sort and remove duplicates
+      candidates.sort();
+      candidates.dedup(); // make sure to sort first
```
Comment (dsherret) [inline cli/tools/repl.rs:175]: I kind of dislike `dedup()` because it requires remembering that the data needs to be sorted (which I needed to do here anyway). Should I keep this or perhaps use a hash set above instead?

Comment (bartlomieju) [reply cli/tools/repl.rs:175]: I think it's fine, there are comments so it's all good

**Review by bartlomieju — APPROVED** [review]
LGTM, great fix 👍

File: cli/tests/integration_tests.rs [hunk 3]
```diff
@@ -2085,6 +2085,35 @@ mod integration {
...
+        assert!(output.contains("> myVar"));
+
+        fork.wait().unwrap();
+      } else {
+        std::env::set_var("NO_COLOR", "1");
+        let err = exec::Command::new(deno_exe).arg("repl").exec();
+        println!("err {}", err);
+        unreachable!()
+      }
+    }
```
Comment (ry) [inline cli/tests/integration_tests.rs:2115]: Nice test!

File: cli/tests/integration_tests.rs [hunk 4]
```diff
@@ -2085,6 +2085,35 @@ mod integration {
...
+        assert!(output.contains("> MyClass"));
+        assert!(output.contains("> myVar"));
+
+        fork.wait().unwrap();
+      } else {
+        std::env::set_var("NO_COLOR", "1");
+        let err = exec::Command::new(deno_exe).arg("repl").exec();
+        println!("err {}", err);
+        unreachable!()
+      }
```
Comment (bartlomieju) [inline cli/tests/integration_tests.rs:2114]: It seems this conditional is repeated in every repl test... 

I'm in favor of moving REPL tests to separate file as you suggested @dsherret , `integrations_tests.rs` became unwieldy at this point.

Comment (dsherret) [reply cli/tests/integration_tests.rs:2114]: Yeah, I just copied what was done before. It would be nice to extract all this out then clean it up... after all the repl changes/fixes I will confirm it should be done then do it.

**Review by caspervonb — APPROVED** [review]
LGTM.

**Review by bartlomieju — APPROVED** [review]
Let's land it for 1.11.1
