### PR TITLE
fix: panic when process stdio rid is 0 or invalid

### LINKED ISSUE #6400: setting stdout to 0 in Deno.run causes deno to panic
```ts
const p3 = Deno.run({
  cmd: ["tee",  "head_output.txt"],
  stdin: "piped",
  stdout: 0,
});

const p2 = Deno.run({
  cmd: ["head", "-2"],
  stdin: "piped",
  stdout: p3.rid
});

const p1 = Deno.run({
  cmd: ["ls"],
  stdin: 0,
  stdout: p2.rid
});
```
This code causes deno to panic: 
```
thread 'main' panicked at 'internal error: entered unreachable code', cli/ops/process.rs:41:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: failed to initiate panic, error 5
```
which I was relatively easily able to trace back to the fact that i had supplied a 0 as the stdout for p3. I would have expected deno to throw an error like a bad resource id rather than panicking

### PR DESCRIPTION
**Pull request by lucacasonato**
Fixes #6400

### CODE REVIEW

File: cli/ops/process.rs [hunk 1]
```diff
@@ -86,28 +86,37 @@ fn op_run(
...
   // TODO: make this work with other resources, eg. sockets
-  let stdin_rid = run_args.stdin_rid;
-  if stdin_rid > 0 {
-    let file = clone_file(stdin_rid, &mut resource_table)?;
-    c.stdin(file);
+  if run_args.stdin != "" {
+    if let Some(stdin) = subprocess_stdio_map(run_args.stdin.as_ref()) {
+      c.stdin(stdin);
+    } else {
+      return Err(OpError::other("Invalid resource for stdin".to_string()));
```
Comment (ry) [inline cli/ops/process.rs:93]: Maybe lift this error into the utility function subprocess_stdio_map, so it doesn't have to be repeated

File: cli/ops/process.rs [hunk 2]
```diff
@@ -33,12 +33,12 @@ fn clone_file(
...
   match s {
-    "inherit" => std::process::Stdio::inherit(),
-    "piped" => std::process::Stdio::piped(),
-    "null" => std::process::Stdio::null(),
-    _ => unreachable!(),
+    "inherit" => Some(std::process::Stdio::inherit()),
+    "piped" => Some(std::process::Stdio::piped()),
+    "null" => Some(std::process::Stdio::null()),
+    _ => None,
   }
```
Comment (ry) [inline cli/ops/process.rs:42]: Rather than returning `Option<Stdio>` here return `Result<Stdio, ErrBox>`, do reduce the amount of code below.

File: cli/tests/unit/process_test.ts [hunk 3]
```diff
@@ -30,6 +31,46 @@ unitTest({ perms: { run: true } }, async function runSuccess(): Promise<void> {
   p.stdout.close();
   p.close();
 });
+unitTest({ perms: { run: true } }, async function runStdinRid0(): Promise<
+  void
+> {
+  const p = Deno.run({
+    cmd: ["python", "-c", "print('hello world')"],
+    stdin: 0,
```
Comment (ry) [inline cli/tests/unit/process_test.ts:39]: I'm confused. Certainly Deno shouldn't panic when given 0 for stdin, but this is showing it be successful. Shouldn't this throw? What does `stdin: 0` mean?

Comment (lucacasonato) [reply cli/tests/unit/process_test.ts:39]: It means use `rid 0` as `stdin`. And `rid 0` maps to the current process stdin:

```
> Deno.resources()
{ 0: "stdin", 1: "stdout", 2: "stderr", 3: "repl" }
```

Comment (lucacasonato) [reply cli/tests/unit/process_test.ts:39]: It means use `rid 0` as `stdin`. And `rid 0` maps to the current process stdin:

```
> Deno.resources()
{ 0: "stdin", 1: "stdout", 2: "stderr", 3: "repl" }
```

Comment (ry) [reply cli/tests/unit/process_test.ts:39]: Ah cool. I forgot we had this feature.
