### PR TITLE
Fix REPL when it receives EOF

### LINKED ISSUE #2637: CTRL+D in the REPL causes panic
this was introduced in abe8a113ad8004f160eac5f3f115cb28c5072ba7
```
% ./target/debug/deno
> 1+2
3
> ^D
thread 'tokio-runtime-worker-1' panicked at 'Can't get ErrorKind for Eof', ../../cli/deno_error.rs:235:9
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
thread 'main' panicked at 'internal error: entered unreachable code', ../../third_party/rust_crates/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.21/src/runtime/threadpool/mod.rs:296:26
thread 'tokio-runtime-worker-0' panicked at 'unexpected state while aborting task: Complete', ../../third_party/rust_crates/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.14/src/task/mod.rs:216:21
```

### PR DESCRIPTION
**Pull request by ry**
Fixes #2637

### CODE REVIEW

File: cli/deno_error.rs [hunk 1]
```diff
@@ -185,6 +186,19 @@ impl GetErrorKind for hyper::Error {
...
 
+impl GetErrorKind for ReadlineError {
+  fn kind(&self) -> ErrorKind {
+    use ReadlineError::*;
+    match self {
+      Io(_err) => unimplemented!(),
+      Eof => ErrorKind::UnexpectedEof,
+      Interrupted => unimplemented!(),
+      Utf8Error => unimplemented!(),
+      Errno(_err) => unimplemented!(),
```
Comment (ry) [inline cli/deno_error.rs]: Not sure about how to handle these other errors. I would just wait until we hit them..

File: cli/deno_error.rs [hunk 2]
```diff
@@ -185,6 +186,19 @@ impl GetErrorKind for hyper::Error {
   }
 }
 
+impl GetErrorKind for ReadlineError {
+  fn kind(&self) -> ErrorKind {
+    use ReadlineError::*;
+    match self {
+      Io(_err) => unimplemented!(),
+      Eof => ErrorKind::UnexpectedEof,
```
Comment (piscisaureus) [inline cli/deno_error.rs]: So the type of `_err` here is probably io::Error. Which means you can just call kind() on it.
So: `Io(err) => err.kind()`

File: cli/deno_error.rs (hunk 1 above)
Comment (piscisaureus) [reply cli/deno_error.rs]: This variant exists only on unix (type is nix::Error), so this will probably cause a build error on windows.
We do implement GetErrorKind for nix::Error too, so on unix `Errno(err) => err.kind()` should work.

File: cli/deno_error.rs (hunk 2 above)
Comment (ry) [reply cli/deno_error.rs]: Ok - done

File: cli/deno_error.rs (hunk 1 above)
Comment (ry) [reply cli/deno_error.rs]: ok, i made it `#[cfg(unix)]`
