### PR TITLE
fix(diff): better handling of text with only line ending differences

### LINKED ISSUE #8118: deno fmt --check should not show entire file when only line endings differ
When running `deno fmt --check` it should only show relevant changes, or a radius of it, it shouldn't print simple line changes, or it could result in quite bad outputs in my opinion. 

Running it, basically printed my whole codebase because of some import reordering, and organizing.

<details>
<summary>Examples</summary>

image
image

</details>

### PR DESCRIPTION
**Pull request by dsherret**
Also fixed a few additional bugs like:

1. It not displaying a diff when one text had a trailing newline and the other didn't.
2. Edge case where the line number width could be incorrect if the original text had say `99` lines and the edit text had `100` lines.

I commented everywhere in the PR that actually changed other than the refactor to make the borrow checker happy without duplicating code.

Closes #8118

### CODE REVIEW

File: cli/diff.rs [hunk 1]
```diff
@@ -27,146 +165,60 @@ fn fmt_rem_text_highlight(x: &str) -> String {
...
-  orig.clear();
-  edit.clear();
-}
-
-/// Print diff of the same file_path, before and after formatting.
-///
-/// Diff format is loosely based on Github diff formatting.
-pub fn diff(orig_text: &str, edit_text: &str) -> String {
-  let lines = edit_text.split('\n').count();
-  let line_number_width = lines.to_string().chars().count();
```
Comment (dsherret) [inline cli/diff.rs:76]: Bug here fixed in new code. Should take into account the max of orig_text and edit_text line count.

File: cli/diff.rs [hunk 2]
```diff
@@ -27,146 +165,60 @@ fn fmt_rem_text_highlight(x: &str) -> String {
...
-
-  let mut text1 = orig_text.to_string();
-  let mut text2 = edit_text.to_string();
-
-  if !text1.ends_with('\n') {
-    text1.push('\n');
-  }
-  if !text2.ends_with('\n') {
-    text2.push('\n');
-  }
```
Comment (dsherret) [inline cli/diff.rs:88]: Bug here. Should not do this because it should display a diff for when one has a trailing newline and the other doesn't.

File: cli/diff.rs [hunk 3]
```diff
@@ -3,6 +3,144 @@
...
+
+struct DiffBuilder {
+  output: String,
+  line_number_width: usize,
+  orig_line: usize,
+  edit_line: usize,
+  orig: String,
+  edit: String,
+  has_changes: bool,
+}
```
Comment (dsherret) [inline cli/diff.rs:33]: Unfortunately I had to change the function to a struct in order to make the borrow checker happy and not duplicate a lot of code with the new `flush_changes` method.

File: cli/diff.rs [hunk 4]
```diff
@@ -3,6 +3,144 @@
...
+  if orig_text == edit_text {
+    return String::new();
+  }
+
+  // normalize newlines as it adds too much noise if they differ
+  let orig_text = orig_text.replace("\r\n", "\n");
+  let edit_text = edit_text.replace("\r\n", "\n");
+
+  if orig_text == edit_text {
+    return " | Text differed by line endings.\n".to_string();
```
Comment (dsherret) [inline cli/diff.rs:19]: Fix here. This is what I do in dprint. It prevents entire files from being spammed.

File: cli/diff.rs [hunk 5]
```diff
@@ -3,6 +3,142 @@
...
+      orig_line: 1,
+      edit_line: 1,
+      orig: String::new(),
+      edit: String::new(),
+      has_changes: false,
+      line_number_width: {
+        let line_count = std::cmp::max(
+          orig_text.split('\n').count(),
+          edit_text.split('\n').count(),
+        );
```
Comment (dsherret) [inline cli/diff.rs:48]: Fix here to use max.

File: cli/diff.rs [hunk 6]
```diff
@@ -3,6 +3,142 @@
...
+              self.flush_changes();
+            }
+            self.orig.push_str(&fmt_rem_text(s));
+            self.edit.push_str(&fmt_add_text(s));
+          }
+        }
+      }
+    }
+
+    self.flush_changes();
```
Comment (dsherret) [inline cli/diff.rs:94]: Fix here to flush the changes here as well.

File: cli/diff.rs [hunk 7]
```diff
@@ -3,6 +3,142 @@
 use crate::colors;
 use dissimilar::{diff as difference, Chunk};
 
+/// Print diff of the same file_path, before and after formatting.
+///
+/// Diff format is loosely based on Github diff formatting.
+pub fn diff(orig_text: &str, edit_text: &str) -> String {
```
Comment (dsherret) [inline cli/diff.rs:9]: Sorry, the diff here wasn't going to be pretty no matter what, so I took the liberty of reorganizing the file. For the most part it's largely the same other than a few fixes. I've commented everywhere that's changed.

File: cli/diff.rs [hunk 8]
```diff
@@ -27,146 +163,60 @@ fn fmt_rem_text_highlight(x: &str) -> String {
...
+        "6 | -'Hello World'\n",
+        "2 | +\"Hello World\"\n",
+        "7 | -)\n3 | +);\n",
+      ),
+    );
+  }
+
+  #[test]
+  fn test_eof_newline_missing() {
+    run_test(
```
Comment (bartlomieju) [inline cli/diff.rs:200]: Nice tests 👍

**Review by bartlomieju — APPROVED** [review]
LGTM
