### PR TITLE
fix(test): add process sigint handler for --watch

### LINKED ISSUE #18676: `deno test --watch` cannot be interrupted with `sigint` while waiting for restart
### problem
Deno's watcher does not respond to `sigint` when pending restart 

### expectations
One would expect to be able to stop deno's watcher using `sigint` usually sent using `ctrl-c` in a cli environment

### how to reproduce
Below is a sample code `sig.js` used in the command below.

It starts an async test so that interuption can be tested during test execution and after execution has completed when deno is pending restart.

```js
Deno.test('pending_test', async () => {
  await new Promise((resolve, reject) => {
    const t = setTimeout(() => {
      resolve(true);
    }, 1000);
  });
});
```
---
Running `deno test --watch sig.js` and waiting for the timeout to resolve *then* sending sigint (using control-c or the `kill` command) fails to stop deno's watcher, outputing:
```sh
$ deno test --watch sig.js
Watcher Test started.
running 1 test from ./sig.js
pending_test ... ok (1s)

ok | 1 passed | 0 failed (1s)

Watcher Test finished. Restarting on file change...
^C
```

Alternatively sending `sigint` during test execution works as expected and outputs:

```sh
$ deno test --watch sig.js
Watcher Test started.
running 1 test from ./sig.js
pending_test ...^C
SIGINT The following tests were pending:

pending_test => ./sig.js:5:6
$
```
This happens only with `deno test --watch`. `deno run --watch` can be interrupted unless a signal listener was attached during execution. Doing some research I stumbled upon this comment which seems relevant.
https://github.com/denoland/deno/pull/18246#pullrequestreview-1347577127

Is `deno test` attaching a sigint listener preventing the watcher to subsequently receive the signal?

### environment

deno config 
```
$ deno --version
deno 1.32.4 (release, aarch64-apple-darwin)
v8 11.2.214.9
typescript 5.0.
```
the problem happens on macos ventura 13.2.1 using the native macos terminal.
the same thing was tested on windows where deno's watcher can be interrupted as expected pending restart.

### PR DESCRIPTION
**Pull request by nayeemrmn**
Fixes #18676.

### CODE REVIEW

File: cli/tools/test.rs [hunk 1]
```diff
@@ -1736,6 +1742,19 @@ pub async fn run_tests_with_watch(
...
 
+  // On top of the sigint handlers which are added and unbound for each test
+  // run, a process-scoped basic exit handler is required due to a tokio
+  // limitation where it doesn't unbind its own handler for the entire process
+  // once a user adds one.
+  tokio::task::spawn(async move {
+    loop {
+      signal::ctrl_c().await.unwrap();
+      if !HAS_TEST_RUN_SIGINT_HANDLER.load(Ordering::Relaxed) {
+        std::process::exit(130);
```
Comment (bartlomieju) [inline cli/tools/test.rs:1753]: Why 130?

Comment (bartlomieju) [reply cli/tools/test.rs:1753]: Nvm, appears that was the case in 1.32.1

**Review by bartlomieju — APPROVED** [review]
Tested locally and it fixes the issue. LGTM, thanks for quick turnaround Nayeem.
