### PR TITLE
fix(compile): ensure import map is used when specified in deno config file

### LINKED ISSUE #14246: deno compile ignores import_map.json specified in deno.json
Hey! I have a smallish project that I'm working on, and when I compile the command to make a binary, it seems to ignore the `import_map.json`. I have an `"importMap"` key in my `deno.json`, but it doesn't pick it up. When I use `--import-map ./import_map.json` it works, but it then gives me a warning that the `"importMap"` key is being ignored. It also works completely fine when I run with `deno run`, and I don't have to use the `--import-map` option.

Here are the commands I used:

Compile: `deno compile --allow-env --allow-net --allow-read ./src/main.ts`
The compilation succeeds, but when I try to run the binary with `./main` I get this result: `error: Relative import path "dotenv/mod.ts" not prefixed with / or ./ or ../ from "file:///home/redxtech/Code/project/src/main.ts"`

Compile with args: `deno compile --allow-env --allow-net --allow-read --import-map ./import_map.json ./src/main.ts`
Warning: `Warning the configuration file "file:///home/redxtech/Code/project/deno.json" contains an entry for "importMap" that is being ignored.`

Run: `deno run --allow-env --allow-net --allow-read ./src/main.ts`
Result: works as expected.

Output of `deno --version`:
```
deno 1.20.5 (release, x86_64-unknown-linux-gnu)
v8 10.0.139.6
typescript 4.6.2
```

Here's my `./deno.json` (`lint` & `fmt` fields removed):
```json
{
  "compilerOptions": {
    "allowJs": false,
    "lib": ["deno.window", "es2021"],
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "strict": true
  },
  "importMap": "./import_map.json"
}
```
and my `./import_map.json`:
```json
{
   "imports": {
      "dotenv/": "https://deno.land/x/dotenv@v1.0.1/",
      "kall/": "https://denopkg.com/olaven/kall@v1.0.8/",
      "std/": "https://deno.land/std@0.133.0/"
   }
}

```

Here's the relevant part of `./src/main.ts` file where the imports are used:
```ts
import { config as dotEnvConfig } from 'dotenv/mod.ts';
```

If you need any more info I would be happy to provide it.

### PR DESCRIPTION
**Pull request by dsherret**
Closes #14246

### CODE REVIEW

File: cli/args/flags.rs [hunk 1]
```diff
@@ -2997,11 +2982,7 @@ fn permission_args_parse(flags: &mut Flags, matches: &clap::ArgMatches) {
     flags.allow_ffi = Some(vec![]);
     flags.allow_hrtime = true;
   }
-  #[cfg(not(test))]
-  let has_no_prompt_env = env::var("DENO_NO_PROMPT") == Ok("1".to_string());
```
Comment (dsherret) [inline cli/args/flags.rs:3001]: Env var is now resolved in `CliOptions` (multiple source resolution) to keep this file strictly about argument parsing.

File: cli/args/flags.rs [hunk 2]
```diff
@@ -482,20 +481,6 @@ impl Flags {
...
-      allow_hrtime: self.allow_hrtime,
-      allow_net: self.allow_net.clone(),
-      allow_ffi: self.allow_ffi.clone(),
-      allow_read: self.allow_read.clone(),
-      allow_run: self.allow_run.clone(),
-      allow_sys: self.allow_sys.clone(),
-      allow_write: self.allow_write.clone(),
-      prompt: !self.no_prompt,
-    }
-  }
```
Comment (dsherret) [inline cli/args/flags.rs:497]: Moved to `CliOptions` since `no_prompt` is resolved via multiple sources (environment and flags).

File: cli/args/mod.rs [hunk 3]
```diff
@@ -467,8 +475,8 @@ impl CliOptions {
       .unwrap_or(false)
   }
 
-  pub fn location_flag(&self) -> Option<&Url> {
-    self.flags.location.as_ref()
+  pub fn location_flag(&self) -> &Option<Url> {
+    &self.flags.location
```
Comment (dsherret) [inline cli/args/mod.rs:479]: I think for outputs `&Option<T>` makes sense if able and for inputs `Option<&T>` (I initially wrote this code here)

File: cli/main.rs [hunk 4]
```diff
@@ -88,60 +88,26 @@ use std::pin::Pin;
 use std::sync::Arc;
 use worker::create_main_worker;
 
-pub fn get_types(unstable: bool) -> String {
```
Comment (dsherret) [inline cli/main.rs:91]: Didn't want to open a separate PR for this. Moved it to the tsc folder.

File: cli/main.rs [hunk 5]
```diff
@@ -88,60 +88,26 @@ use std::pin::Pin;
...
-  }
-
-  types.join("\n")
-}
-
 async fn compile_command(
   flags: Flags,
   compile_flags: CompileFlags,
 ) -> Result<i32, AnyError> {
-  let debug = flags.log_level == Some(log::Level::Debug);
```
Comment (dsherret) [inline cli/main.rs:120]: This can be figured out further down, so no need to store this here.

File: cli/tools/standalone.rs [hunk 6]
```diff
@@ -233,67 +228,6 @@ pub async fn write_standalone_binary(
   Ok(())
 }
 
-/// Transform the flags passed to `deno compile` to flags that would be used at
-/// runtime, as if `deno run` were used.
-/// - Flags that affect module resolution, loading, type checking, etc. aren't
-///   applicable at runtime so are set to their defaults like `false`.
-/// - Other flags are inherited.
-pub fn compile_to_runtime_flags(
```
Comment (dsherret) [inline cli/tools/standalone.rs:241]: This was a huge distraction. We can just remove it.

Comment (bartlomieju) [reply cli/tools/standalone.rs:241]: I'm not sure, what are we passing now?

Comment (dsherret) [reply cli/tools/standalone.rs:241]: See https://github.com/denoland/deno/pull/16990/files#diff-388fb4e27905632c538ee418fcd8a62c38af40dc4321f402c795e6a08f9ca64fL130

**Review by bartlomieju — APPROVED** [review]
LGTM, thanks for fixing this David!
