### PR TITLE
fix(cli): Handle formatting UTF-8 w/ BOM files

### LINKED ISSUE #5850: deno fmt - Formatting a file saved as UTF-8 with BOM leads to badly formatted text
Input code (saved as UTF-8 w/ BOM):

```ts
/// <reference path='firebase.d.ts'/>

export declare class AngularFire {
    asArray(): FirebaseArray;
}

export interface FirebaseArray {
    getItem(recOrIndex: any): any;
    getChild(recOrIndex: any): any;
    add(newData: any): void;
    remove(recOrIndex: any): void;
    save(recOrIndex: any): void;
    keyify(snap: any): any;
    created(snap: any): void;
    moved(snap: any): void;
    updated(snap: any): void;
    removed(snap: any): void;
    bulkUpdate(items: Object): void;
    spliceOut(key: any): void;
    indexFor(key: any): number;
    getRecord(key: any): any;
    list: any[];
}
```

Output code:

```ts
/// <reference path='firebase.d.ts'/>

export declare class AngularFire {
  asArray(): FirebaseArray;
}

export interface FirebaseArray {
  getItem(recOrIndex: x: ): ): ;
  getChild(recOrIndex: x: ): ): ;
  add(newData: a: ): ): v;
  remove(recOrIndex: x: ): ): v;
  save(recOrIndex: x: ): ): v;
  keyify(snap: p: ): ): ;
  created(snap: p: ): ): v;
  moved(snap: p: ): ): v;
  updated(snap: p: ): ): v;
  removed(snap: p: ): ): v;
  bulkUpdate(items: Object): ): v;
  spliceOut(key: y: ): ): v;
  indexFor(key: y: ): ): num;
  getRecord(key: y: ): ): ;
  list: t: [];
}
```

I'm thinking deno fmt should strip the BOM before providing the string to dprint then save the file with BOM afterwards.

### PR DESCRIPTION
**Pull request by dsherret**
Closes #5850.

### CODE REVIEW

File: cli/fmt.rs [hunk 1]
```diff
@@ -112,12 +114,18 @@ async fn format_source_files(
...
-      let file_contents = fs::read_to_string(&file_path)?;
-      let r = formatter.format_text(&file_path, &file_contents);
+      let file_contents = read_file_contents(&file_path)?;
+      let r = formatter.format_text(&file_path, &file_contents.text);
       match r {
         Ok(formatted_text) => {
-          if formatted_text != file_contents {
-            fs::write(&file_path, formatted_text)?;
+          if formatted_text != file_contents.text {
+            write_file_contents(
```
Comment (dsherret) [inline cli/fmt.rs:122]: Should the BOM be stripped instead?
