### PR TITLE
fix(lsp): Remove client-facing format failure warning

### LINKED ISSUE #23163: LSP creates annoying pop up on syntax error
Version: Deno 1.42.1

In VSCode when I save a file with a syntax error I get this annoying pop up rather than just a red squiggly like I would in Rust.

Screenshot 2024-04-01 at 10 46 22 AM

This comes from 
https://github.com/denoland/deno/blob/240b362c002d17bc2b676673ed1b9406683ff0c2/cli/lsp/language_server.rs#L1592

Suggest to match Rust behavior - no pop up.

### PR DESCRIPTION
**Pull request by nathanwhit**
Fixes #23163.

The client-facing warning doesn't provide any value and is super annoying. We still emit a warning message on the server side for format errors, which should fulfill the same (less intrusive) purpose.

### CODE REVIEW

File: cli/lsp/language_server.rs [hunk 1]
```diff
@@ -1576,7 +1576,6 @@ impl Inner {
         Ok(Some(text_edits))
       }
     } else {
-      self.client.show_message(MessageType::WARNING, format!("Unable to format \"{specifier}\". Likely due to unrecoverable syntax errors in the file."));
```
Comment (nayeemrmn) [inline cli/lsp/language_server.rs:1579]: We should replace it with `lsp_warn!()` so it shows up in the output panel

Comment (nathanwhit) [reply cli/lsp/language_server.rs:1579]: It already logs a warning for the error on line 1562 (which includes the file path), so it seemed like another warning didn't really provide any value. For instance, after this PR you'll still get a warning like below in the lsp output.
Screenshot 2024-04-02 at 6 04 56 PM

**Review by nayeemrmn — APPROVED** [review]
LGTM!
