### PR TITLE
fix(cli/web/fetch): multipart/form-data request body support for binary files

### LINKED ISSUE #5884: fetch request.formData does not work for binary files
Similar to https://github.com/denoland/deno/issues/4877 but for `Request`.

Right now binary files posted using `fetch` are corrupted.

### PR DESCRIPTION
**Pull request by marcosc90**
fixes #5884 #5829

`Blob` is being converted to `utf8`, breaking binary files. Created a `MultipartBuilder` class that builds `multipart/form-data` body correctly.

~It's currently hard to write a test for binary files since `Response.formData` is also broken (#4877). So added a test for text files which are currently working on `master`~

Did multiple manual tests for binary files, and everything's working correctly.

### CODE REVIEW

File: cli/js/web/fetch/multipart.ts [hunk 1]
```diff
@@ -0,0 +1,86 @@
...
+  }
+
+  getBody(): Uint8Array {
+    for (const [fieldName, fieldValue] of this.formData.entries()) {
+      if (fieldValue instanceof DomFileImpl) {
+        this.#writeFile(fieldName, fieldValue);
+      } else this.#writeField(fieldName, fieldValue as string);
+    }
+
+    this.writer.writeSync(encoder.encode(`\r\n--${this.boundary}--`));
```
Comment (marcosc90) [inline cli/js/web/fetch/multipart.ts:31]: I used `writeSync` since in `master` we're building it synchronous too, and in any case, `Buffer.write` also uses `.writeSync` internally.

If someone prefers `.write` instead, I'll do the change, don't have strong opinions here.

**Comment by marcosc90** [comment]
Now that #4877 is merged, added couple of tests to make sure binary files are build and parsed correctly

File: cli/js/web/fetch/multipart.ts (hunk 1 above)
Comment (bartlomieju) [reply cli/js/web/fetch/multipart.ts:41]: That's fine 👍

File: cli/tests/unit/fetch_test.ts [hunk 2]
```diff
@@ -267,6 +267,60 @@ unitTest(
...
+      const resultFile = resultForm.get(file.name) as File;
+      assertEquals(inputFile.size, resultFile.size);
+      assertEquals(inputFile.name, resultFile.name);
+      assertEquals(file.expectedType || file.type, resultFile.type);
+      assertEquals(
+        new Uint8Array(await resultFile.arrayBuffer()),
+        file.content
+      );
+    }
+  }
```
Comment (bartlomieju) [inline cli/tests/unit/fetch_test.ts:321]: Nice test!
