### PR TITLE
fix(bundle): pass requested module type to load

### LINKED ISSUE #29663: deno bundle error
Version: deno 2.3.5+635e374 (canary, release, x86_64-unknown-linux-gnu)

```
deno bundle https://raw.githubusercontent.com/sigmaSd/Share/refs/heads/master/src/main.worker.ts
⚠️ deno bundle is experimental and subject to changes
bundler error: Unexpected end of file in JSON
  at deno:https://jsr.io/@std/http/1.0.16/deno.json 1:0
error: bundling failed
```

notes:
- initially deno bundle complained about esbuild, i run it with deno bundle -r to fix this
- is it possible in the future to bundle the worker automatically if its statically analyzable or thats out of scope for bundle?

### PR DESCRIPTION
**Pull request by nathanwhit**
Fixes #29663.

### CODE REVIEW

File: cli/tools/bundle/mod.rs [hunk 1]
```diff
@@ -562,18 +575,19 @@ impl DenoPluginHandler {
...
+      requested_type
     );
 
-    let resolve_dir = Path::new(&resolve_dir);
-    let specifier = deno_core::resolve_url_or_path(specifier, resolve_dir)?;
-
+    let specifier = deno_core::resolve_url_or_path(
+      specifier,
+      Path::new(""), // should be absolute already, feels kind of hacky though
+    )?;
```
Comment (dsherret) [inline cli/tools/bundle/mod.rs:590]: Won't specifier always be a url?

**Review by dsherret — APPROVED** [review]
LGTM

File: cli/tools/bundle/mod.rs (hunk 1 above)
Comment (nathanwhit) [reply cli/tools/bundle/mod.rs:590]: It can be a URL or a file path
