### PR TITLE
fix(ext/flash): don't block requests

### LINKED ISSUE #15758: [Bug 1.25.1] (Deno.serve) - Only handles one request at a time
### Description
The new Deno.serve method only appears to be allowing one request at a time.

### Example (Using Deno.serve)
deno-serve-example
**Command:** `RUST_BACKTRACE=full deno run -A --unstable serve-test.ts`

**Source:**
```typescript
let active = 0;
const sleep = (time: number) => new Promise(r => setTimeout(r, time));
const start = (pathname: string) => {
  active++;
  console.log(`⏰ Request received  ${pathname}  | Total Active: ${active}`)
};
const end = (pathname: string) => {
  active--;
  console.log(`✅ Request completed ${pathname}  | Total Active: ${active}`);
}

const handler: Deno.ServeHandler = async (event) => {
  const pathname = new URL(event.url).pathname;
  start(pathname);
  await sleep(2000);
  try {
    return new Response('done');
  } finally {
    end(pathname);
  }
};

Deno.serve(
  {
    handler,
    port: 9999,
    onListen({ hostname, port }) {
      console.log(`Server Started... http://${hostname}:${port}/`);
    }
  } 
)
```
### Example (Using std/http/server)
std-http-serve-example

**Command:** `RUST_BACKTRACE=full deno run -A serve-test.ts`

**Source:**
```typescript
import { serve } from "https://deno.land/std@0.154.0/http/server.ts";

let active = 0;
const sleep = (time: number) => new Promise(r => setTimeout(r, time));
const start = (pathname: string) => {
  active++;
  console.log(`⏰ Request received  ${pathname}  | Total Active: ${active}`)
};
const end = (pathname: string) => {
  active--;
  console.log(`✅ Request completed ${pathname}  | Total Active: ${active}`);
}

const handler: Deno.ServeHandler = async (event) => {
  const pathname = new URL(event.url).pathname;
  start(pathname);
  await sleep(2000);
  try {
    return new Response('done');
  } finally {
    end(pathname);
  }
};

serve(
  handler,
  {
    port: 9999,
    onListen({ hostname, port }) {
      console.log(`Server Started... http://${hostname}:${port}/`);
    }
  } 
)
```

### PR DESCRIPTION
**Pull request by littledivy**
Fixes #15758 

<details><summary>13% improvement in react-dom SSR</summary>

image

</details>

* slight ~3% decrease in Hono routing benchmark but there is a 14% overhead in `{ headers }` logic.
* no change in plaintext benchmark on OSX / Linux.

### CODE REVIEW

File: ext/flash/01_http.js [hunk 1]
```diff
@@ -227,6 +228,192 @@
...
+        ws[_eventLoop]();
+        if (ws[_idleTimeoutDuration]) {
+          ws.addEventListener(
+            "close",
+            () => clearTimeout(ws[_idleTimeoutTimeout]),
+          );
+        }
+        ws[_serverHandleIdleTimeout]();
+      }
+    })().catch(console.error);
```
Comment (sagea) [inline ext/flash/01_http.js:414]: Question:
In the original this async function would call the onError handler. It doesn't appear that the responseHandler function awaits or returns this whole async block so the `.catch(onError)` on line 557 doesn't handle this case.

Is this expected?

**Review by sagea — APPROVED** [review]
Approved, but I posted a comment with a question on a behavior change.

I tested this locally and it works as expected.

https://user-images.githubusercontent.com/12538959/189571857-7ef63b40-0ae6-4918-b4d1-39482ceb7b3f.mov

File: ext/flash/01_http.js (hunk 1 above)
Comment (littledivy) [reply ext/flash/01_http.js:414]: Oh that is an oversight

File: ext/flash/01_http.js [hunk 2]
```diff
@@ -353,183 +540,37 @@
...
-                }
-                ws[_serverHandleIdleTimeout]();
+                    respondChunked,
+                  )
+                ).catch(onError);
+                continue;
               }
-            })().catch(onError);
+            } catch (e) {
+              resp = await onError(e);
```
Comment (sagea) [inline ext/flash/01_http.js:561]: Found an edgecase: Because this line is not going through the same treatment a users custom onError method can block future requests.

This will only happen if the handler threw an error outside of a promise (example below).


```
const handler = (request) => {
  if (Math.random() > .5) throw new Error('blow up randomly');
  return (async() => {
    return new Response('handler can still return a promise');
  })();
}
```


Alternatively, something like this could be done. let me know what you think.
```typescript
Promise.resolve()
  .then(() => handle(req))
  .catch(error => onError(error))
  .then(resp => handleResponse(...));

```

**Review by sagea — CHANGES_REQUESTED** [review]

File: ext/flash/01_http.js [hunk 3]
```diff
@@ -353,183 +540,37 @@
...
-                    });
-                  } catch (error) {
-                    await reader.cancel(error);
-                    throw error;
-                  }
-                } else {
-                  const reader = respBody.getReader();
-                  writeFixedResponse(
+              resp = handler(req);
+              if (resp instanceof Promise || resp.then) {
```
Comment (ry) [inline ext/flash/01_http.js:544]: In what situation is something not a promise but has a `.then` method?

Comment (bartlomieju) [reply ext/flash/01_http.js:544]: It seems return value like this would trigger this conditional but it shouldn't:

```js
return {
   // ...
   then: 1
}
```
