### PR TITLE
core: gracefully handle bad op id

### LINKED ISSUE #3117: Harden Isolate ops API
New `Isolate::register_op` API (#3002) still needs some work, namely:
- `OpRegistry::call_op` will panic if you try to call op that doesn't exist - it should be handled gracefully by throwing error in JS (eg. `Deno.core.send called with unknown op id: 100`)
https://github.com/denoland/deno/blob/97d8498d46bbfb7bb16eeb3a69565d2aeda1e5aa/core/ops.rs#L66-L81
- No handling of malformed control buffer in either of dispatch mechanisms.
https://github.com/denoland/deno/blob/97d8498d46bbfb7bb16eeb3a69565d2aeda1e5aa/cli/ops/dispatch_minimal.rs#L74-L81
https://github.com/denoland/deno/blob/97d8498d46bbfb7bb16eeb3a69565d2aeda1e5aa/cli/ops/dispatch_json.rs#L46-L53
They would panic if you send bad data, eg. 
```
Deno.core.send(1, new Uint8Array([1])
thread 'tokio-runtime-worker-3' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:378:21
stack backtrace:
   0: std::panicking::default_hook::{{closure}}
   1: std::panicking::default_hook
   2: std::panicking::rust_panic_with_hook
   3: std::panicking::continue_panic_fmt
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::panicking::panic
   7: core::option::Option<T>::unwrap
   8: deno_cli::ops::dispatch_minimal::minimal_op::{{closure}}
   9: deno_cli::state::ThreadSafeState::cli_op::{{closure}}
  10: <alloc::boxed::Box<F> as core::ops::function::Fn<A>>::call
  11: deno::ops::OpRegistry::call
  12: deno::isolate::Isolate::pre_dispatch
  13: _ZN4deno4SendERKN2v820FunctionCallbackInfoINS0_5ValueEEE
  14: _ZN2v88internal25FunctionCallbackArguments4CallENS0_15CallHandlerInfoE
  15: _ZN2v88internal12_GLOBAL__N_119HandleApiCallHelperILb0EEENS0_11MaybeHandleINS0_6ObjectEEEPNS0_7IsolateENS0_6HandleINS0_10HeapObjectEEESA_NS8_INS0_20FunctionTemplateInfoEEENS8_IS4_EENS0_16BuiltinArgumentsE
  16: _ZN2v88internalL26Builtin_Impl_HandleApiCallENS0_16BuiltinArgumentsEPNS0_7IsolateE
  17: _ZN2v88internal21Builtin_HandleApiCallEiPmPNS0_7IsolateE
fatal runtime error: failed to initiate panic, error 5
Abort trap: 6
```
Again this should throw an error in JS. 

I say this is a prerequisite for native plugins.

Related issues:
- #2459
- #2987

### PR DESCRIPTION
**Pull request by bartlomieju**
Towards #3117

### CODE REVIEW

File: core/ops.rs [hunk 1]
```diff
@@ -68,16 +68,20 @@ impl OpRegistry {
...
-      return Op::Sync(self.json_map());
+      return Ok(Op::Sync(self.json_map()));
     }
 
-    let d = &*self.dispatchers.get(op_id as usize).expect("Op not found!");
-    d(control, zero_copy_buf)
+    let d = match self.dispatchers.get(op_id as usize) {
+      Some(handler) => &*handler,
+      None => return Err(format!("Unknown op id: {}", op_id)),
+    };
```
Comment (ry) [inline core/ops.rs]: It's a little odd for this low-level function to construct an error string like this. I think it might be better if this function returns `Result<CoreOp, ()>` or `Option<CoreOp>` and the caller creates the error message.

Comment (ry) [reply core/ops.rs]: Also it would be helpful if you add triple slash doc to this function describing when it fails (i.e. it only fails when op id is wrong).

**Comment by bartlomieju** [comment]
@ry I updated bit with calling ops. Handling of malformed control buffers is still a TODO and I must say I don't know how to handle it properly...

Example:
Let's say we call "read" op with some bad control buffer, please remember that `promise_id` is put inside the control buffer.
```
Deno.core.send(1, new Uint8Array([...some junk here]))
```
Once we send it we get into `dispatch_minimal`:

https://github.com/denoland/deno/blob/97d8498d46bbfb7bb16eeb3a69565d2aeda1e5aa/cli/ops/dispatch_minimal.rs#L74-L81

Surely `parse_min_record(control).unwrap()` can be handled gracefully without unwrapping, and we could construct `record` be hand to return error response. But here's the problem: we don't know what `promise_id` we should return because we couldn't get it from control buffer (because it was imported). That's still fine, we can create some "fake" record with error, return it to JS and then throw error there. But here's another problem; remember that `promise_id` we're missing? That means that underyling promise will still be in promise map would still pend resolution - but we don't know what was the promise id so effectively we can't remove promise from the map and `reject` it. 

Exactly the same scenario applies to JSON dispatch.

**Comment by bartlomieju** [comment]
@ry this PR should be landable
