### PR TITLE
fix(vendor): do not panic vendoring with jsxImportSource and no jsx files

### LINKED ISSUE #19833: Deno panics when vendoring JSX runtime and no JSX is in the module graph
I'm getting a panic in Deno `1.35.1` when vendoring a new fresh project.

## Steps to reproduce

1. Run `deno run -Ar https://fresh.deno.dev` (press enter to go through the wizard)
2. Run `cd fresh-project`
3. Run `deno vendor dev.ts`

Error:

```sh
$ deno vendor dev.ts

============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: macos aarch64
Version: 1.35.1
Args: ["deno", "vendor", "dev.ts"]

thread 'main' panicked at 'Could not find local path for https://esm.sh/preact@10.15.1/jsx-runtime', cli/tools/vendor/mappings.rs:142:28
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### PR DESCRIPTION
**Pull request by dsherret**
Closes #19833

### CODE REVIEW

File: cli/tools/vendor/import_map.rs [hunk 1]
```diff
@@ -205,7 +205,10 @@ pub fn build_import_map(
       if let Ok(resolved_url) =
         import_map.resolve(&specifier_text, import_map.base_url())
       {
-        builder.imports.add(specifier_text, &resolved_url);
+        // the graph might not have any jsx files
+        if graph.contains(&resolved_url) {
```
Comment (dsherret) [inline cli/tools/vendor/import_map.rs:209]: Actually, perhaps it should still vendor the jsx import source in this case? I will mark this PR back as draft.

Comment (dsherret) [reply cli/tools/vendor/import_map.rs]: Ok, this now always vendors the jsx import source.

**Review by marvinhagemeister — APPROVED** [review]
Can confirm that this resolves the issue 🎉
