### PR TITLE
fix(node/http): allow callback in first argument of end call

### LINKED ISSUE #19762: [Bug] `callback` in `https.request().end(callback)` from `node:https` is never fired
Hello,

Here's a fire-and-forget HTTP request method that works on Node :

```js
import https from 'node:https';

const fireAndForget = ({
    url,
    method = 'GET',
    headers = {},
    data
}) => new Promise((resolve, reject) => {
    const
        _data = JSON.stringify(data),
        request = https.request(url, {
            method,
            headers: _data ? {
                ...headers,
                'Content-Type': 'application/json',
                'Content-Length': Buffer.byteLength(_data)
            } : headers
        });
    request.on('error', reject);
    if(_data)
        request.write(_data);
    request.end(resolve);
});
```

When running on Deno, the request is successfully sent, but the callback from `request.end` is never fired.

Thanks

### PR DESCRIPTION
**Pull request by crowlKats**
Closes #19762

### CODE REVIEW

File: cli/tests/unit_node/http_test.ts [hunk 1]
```diff
@@ -706,3 +706,17 @@ Deno.test(
...
   },
 );
+
+Deno.test(
+  "[node/http] client end with callback",
+  { permissions: { net: true } },
+  async () => {
+    const promise = deferred();
+
+    const request = https.request("http://localhost:4545/http_version");
```
Comment (crowlKats) [inline cli/tests/unit_node/http_test.ts:716]:
```suggestion
    const request = http.request("http://localhost:4545/http_version");
```
