### PR TITLE
Fix read sync on stdin

### LINKED ISSUE #6121: Sync read is not allowed on stdin
This minimal example
```typescript
const data = new Uint8Array(32);
const nread = Deno.stdin.readSync(data);

console.log("read %d bytes", nread);
```

Results in the following error consistently across Ubuntu, MacOS and Windows:

```shell
Compile file:///Users/caspervonb/deno-sync-read-not-allowed-on-stdin/test.ts
error: Uncaught TypeError: sync read not allowed on this resource  
    at unwrapResponse ($deno$/ops/dispatch_minimal.ts:63:11)
    at Object.sendSyncMinimal ($deno$/ops/dispatch_minimal.ts:118:10)
    at Object.readSync ($deno$/ops/io.ts:19:17)
    at Stdin.readSync ($deno$/files.ts:110:12)
    at file:///Users/caspervonb/deno-sync-read-not-allowed-on-stdin/test.ts:4:26
```

### PR DESCRIPTION
**Pull request by caspervonb**
Currently sync operations on stdin are failing because tokio::Stdin cannot be converted to a std::File.

This replaces tokio::stdin with a raw file descriptor wrapped in a std::fs::File which can be converted to a tokio::File and back again making the synchronous version of op_read actually work.

This fixes #6121

### CODE REVIEW

File: cli/tests/unit/stdio_test.ts [hunk 1]
```diff
@@ -0,0 +1,38 @@
+// Copyright 2018-2020 the Deno authors. All rights reserved. MIT license.
+import { unitTest, assertEquals } from "./test_util.ts";
+
+unitTest(function stdioFileDescriptors(): void {
+  assertEquals(Deno.stdin.rid, 0);
+  assertEquals(Deno.stdout.rid, 1);
+  assertEquals(Deno.stderr.rid, 2);
+});
```
Comment (ry) [inline cli/tests/unit/stdio_test.ts:8]: this is a duplicate of another test: filesStdioFileDescriptors

File: cli/tests/unit/stdio_test.ts [hunk 2]
```diff
@@ -0,0 +1,32 @@
+// Copyright 2018-2020 the Deno authors. All rights reserved. MIT license.
+import { unitTest, assertEquals } from "./test_util.ts";
+
+unitTest(async function stdioStdinRead() {
+  const nread = await Deno.stdin.read(new Uint8Array(0));
+  assertEquals(nread, 0);
+});
```
Comment (ry) [inline cli/tests/unit/stdio_test.ts:7]: These tests don't seem to be running...

Try changing the 0 to 42 and seeing if "cargo run std_tests" fails?

Comment (caspervonb) [reply cli/tests/unit/stdio_test.ts:7]: [Seem to be running as far as I can tell](https://github.com/denoland/deno/pull/6126/checks?check_run_id=745481818#step:16:2289)?

But yes stdin tests do hang with a buffer bigger than 0 in byteLength.

Comment (caspervonb) [reply cli/tests/unit/stdio_test.ts:7]: I would like to add some integration tests however, but seems the runner is not currently capable of sending something to stdin of the integration test?

Comment (ry) [reply cli/tests/unit/stdio_test.ts:7]: I'm worried it's not actually running the tests. Try intentionally breaking one of the asserts - does CI fail? That would give me confidence. I can look into this tomorrow...

File: cli/tests/unit/stdio_test.ts [hunk 3]
```diff
@@ -2,13 +2,13 @@
...
-  assertEquals(nread, 0);
+  const nread = await Deno.stdin.read(new Uint8Array(42));
+  assertEquals(nread, 42);
 });
 
 unitTest(function stdioStdinReadSync() {
-  const nread = Deno.stdin.readSync(new Uint8Array(0));
-  assertEquals(nread, 0);
+  const nread = Deno.stdin.readSync(new Uint8Array(42));
+  assertEquals(nread, 42);
```
Comment (caspervonb) [inline cli/tests/unit/stdio_test.ts:11]: Hangs from a tty is true and yields EOF from CI

Comment (ry) [reply cli/tests/unit/stdio_test.ts]: Thanks

**Comment by caspervonb** [comment]
I've rebased for a green CI and popped of the two junk commits for a clean merge.
