### PR TITLE
fix(std/node): fix readFile types, add encoding types: fix #6450

### LINKED ISSUE #6450: bug(std/node): readFile needs generics for correct types
There is an incompatibility on https://deno.land/std/node/_fs/_fs_readFile.ts

## prep

```
echo 'hello' > 'world.txt'
```

## deno

```
deno eval "import { promises as fsPromises } from 'https://deno.land/std/node/fs.ts'; const str: string = await fsPromises.readFile('./world.txt', 'utf8'); console.log(str)"
```

```
Compile file:///Users/balupton/Projects/active/valid-module/__$deno$eval.ts
error: TS2322 [ERROR]: Type 'MaybeEmpty<string | Uint8Array>' is not assignable to type 'string'.
  Type 'undefined' is not assignable to type 'string'.
import { promises as fsPromises } from 'https://deno.land/std/node/fs.ts'; const str: string = await fsPromises.readFile('./package.json', 'utf8');
                                                                                 ~~~
    at file:///Users/balupton/Projects/active/valid-module/__$deno$eval.ts:1:82
```

## node

``` bash
node --input-type=module -e "import { promises as fsPromises } from 'fs'; (async () => { const str = await fsPromises.readFile('./world.txt', 'utf8'); console.log(str) })()"
```

## evaluation

Problem seems fixable by [overloading](https://www.typescriptlang.org/docs/handbook/functions.html#overloads) readFile where instead of `err`, and `data` being maybe empty, they are conditionally empty based on the non-presence of the other.

However, it may be simpler to just use the Node types:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/64ca7c2a2947369edda83b1e8e1235a116ab352a/types/node/fs/promises.d.ts#L67-L89
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/64ca7c2a2947369edda83b1e8e1235a116ab352a/types/node/fs.d.ts#L1450-L1467

Which it seems always provides a string or Buffer for `data` - however, the types could be wrong for Node.js, testing now.

Yeah, the types are wrong for Node.js:

```
> node --input-type=module -e "import { readFile } from 'fs'; readFile('aasdasdad', (...args) => console.log(args))"
[
  [Error: ENOENT: no such file or directory, open 'aasdasdad'] {
    errno: -2,
    code: 'ENOENT',
    syscall: 'open',
    path: 'aasdasdad'
  }
]
```

However, there is still a need to fix this for Deno. In short:

1. callback has error: node.js is wrong, deno is right; i.e. there should be no data argument provided to the callback
2. otherwise callback has data: error should be empty, node.js is right, deno is wrong

Deno is wrong on item 2, because it thinks there could be a 3rd case, where both error, and data are empty.

---

Ignoring the incorrect `readFile` for now, which seems to be too complicated to resolve, instead one can focus on the more simple [`promises/readFile`](https://deno.land/std/node/_fs/promises/_fs_readFile.ts)

I came up with:

``` typescript
// Copyright 2018-2020 the Deno authors. All rights reserved. MIT license.
import { FileOptions } from "../_fs_common.ts";
import { MaybeEmpty } from "../../_utils.ts";

import { readFile as readFileCallback } from "../_fs_readFile.ts";

export function readFile(
  path: string | URL,
  options?: FileOptions | string
): Promise<string | Uint8Array> {
  return new Promise((resolve, reject) => {
    readFileCallback(path, options, (err, data): void => {
      if (err) return reject(err);
      if (data == null)
        return reject(new Error("Invalid state: data missing, but no error"));
      resolve(data);
    });
  });
}
```

However it still fails with:

```
Compile file:///Users/balupton/Projects/active/valid-module/__$deno$eval.ts
error: TS2322 [ERROR]: Type 'string | Uint8Array' is not assignable to type 'string'.
  Type 'Uint8Array' is not assignable to type 'string'.
    at file:///Users/balupton/Projects/active/valid-module/__$deno$eval.ts:1:72
```

So there also needs to be type conditionals on the return type based on the input encoding.

### PR DESCRIPTION
**Pull request by balupton**
This PR corrects the node readFile types. See #6450 for the bug report. It is ready for review and at your discretion merging.

In short:

1. the promised readFile will either reject with an error, or resolve with the data - there will never be a case where they are both `null | undefined`
2. the promise, callback, and sync readFiles will return/resolve a string if a string encoding was provided, or a buffer if a binary encoding (or no encoding) was provided

This PR corrects these issues, and includes new type information for binary and text encodings such that methods can be overloaded accordingly to resolve the correct types depending on the inputs.

There was also another issue, where there was an encoding type `buffer` defined, however that does not exist in Node.js, and I couldn't find any usages of it within Deno either. It seemed it was meant to be `binary` (an encoding that returns a Buffer instance), so I changed it accordingly and added a comment.

# promises.readFile

## node

``` bash
echo 'hello' > ../world.txt
node --input-type=module -e "import { promises as fsPromises } from 'fs'; (async () => { const str = await fsPromises.readFile('../world.txt', 'utf8'); console.log(str) })()"
```

```
hello
```

## deno before

``` bash
echo 'hello' > ../world.txt
deno eval -T "import { promises as fsPromises } from 'https://deno.land/std/node/fs.ts'; const str: string = await fsPromises.readFile('../world.txt', 'utf8'); console.log(str)"
```

```
Compile file:///Users/balupton/Projects/active/deno/__$deno$eval.ts
error: TS2322 [ERROR]: Type 'MaybeEmpty<string | Uint8Array>' is not assignable to type 'string'.
  Type 'undefined' is not assignable to type 'string'.
    at file:///Users/balupton/Projects/active/deno/__$deno$eval.ts:1:82
```

## deno after

``` bash
echo 'hello' > ../world.txt
deno eval -T "import { promises as fsPromises } from './std/node/fs.ts'; const str: string = await fsPromises.readFile('../world.txt', 'utf8'); console.log(str)"
```

```
Compile file:///Users/balupton/Projects/active/deno/__$deno$eval.ts
hello
```

# readFile

## node

``` bash
echo 'hello' > ../world.txt
node --input-type=module -e "import { readFile } from 'fs'; readFile('../world.txt', 'utf8', (err, str) => console.log(err, str) )"
```

```
null hello
```

## deno before

``` bash
echo 'hello' > ../world.txt
deno eval -T "import { readFile } from 'https://deno.land/std/node/fs.ts'; readFile('../world.txt', 'utf8', (err, str: string) => console.log(err, str) )"
```

```
Compile file:///Users/balupton/Projects/active/deno/__$deno$eval.ts
error: TS2345 [ERROR]: Argument of type '(err: Error | null | undefined, str?: string | undefined) => void' is not assignable to parameter of type 'ReadFileCallback'.
  Types of parameters 'str' and 'data' are incompatible.
    Type 'MaybeEmpty<string | Buffer>' is not assignable to type 'string | undefined'.
      Type 'null' is not assignable to type 'string | undefined'.
import { readFile } from 'https://deno.land/std/node/fs.ts'; readFile('../world.txt', 'utf8', (err, str?: string) => console.log(err, str) )
                                                                                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at file:///Users/balupton/Projects/active/deno/__$deno$eval.ts:1:95
```

## deno after

``` bash
echo 'hello' > ../world.txt
deno eval -T "import { readFile } from './std/node/fs.ts'; readFile('../world.txt', 'utf8', (err, str?: string) => console.log(err, str) )"
```

```
Compile file:///Users/balupton/Projects/active/deno/__$deno$eval.ts
null hello
```

# readFileSync

## node

``` bash
echo 'hello' > ../world.txt
node --input-type=module -e "import { readFileSync } from 'fs'; const str = readFileSync('../world.txt', 'utf8'); console.log(str)"
```

```
hello
```

## deno before

``` bash
echo 'hello' > ../world.txt
deno eval -T "import { readFileSync } from 'https://deno.land/std/node/fs.ts'; const str: string = readFileSync('../world.txt', 'utf8'); console.log(str)"
```

```
Compile file:///Users/balupton/Projects/active/deno/__$deno$eval.ts
error: TS2322 [ERROR]: Type 'string | Buffer' is not assignable to type 'string'.
  Type 'Buffer' is not assignable to type 'string'.
import { readFileSync } from 'https://deno.land/std/node/fs.ts'; const str: string = readFileSync('../world.txt', 'utf8'); console.log(str)
                                                                       ~~~
    at file:///Users/balupton/Projects/active/deno/__$deno$eval.ts:1:72
```

## deno after

``` bash
echo 'hello' > ../world.txt
deno eval -T "import { readFileSync } from './std/node/fs.ts'; const str: string = readFileSync('../world.txt', 'utf8'); console.log(str)"
```

```
Compile file:///Users/balupton/Projects/active/deno/__$deno$eval.ts
hello
```

---

Tests have been updated accordingly. Static type checks in the tests capture this.

### CODE REVIEW

File: std/node/_fs/_fs_readFile.ts [hunk 1]
```diff
@@ -33,18 +61,39 @@ export function readFile(
...
+
+  if (cb) {
+    p.then((data: Uint8Array) => {
+      if (encoding && encoding !== "binary") {
+        const text = maybeDecode(data, encoding);
+        return (cb as TextCallback)(null, text);
+      }
+      const buffer = maybeDecode(data, encoding);
+      (cb as BinaryCallback)(null, buffer);
+    }).catch((err) => cb && cb(err));
```
Comment (balupton) [inline std/node/_fs/_fs_readFile.ts:74]: this could be changed from `}).catch((err) => cb && cb(err));` to `}).catch((err) => cb!(err));` as for some reason, the type checker is not considering the if statement
