### PR TITLE
fix(runtime/js/timers): Use (0, eval) instead of eval()

### LINKED ISSUE #10091: Use of eval in setTimeout/setInterval leaks internal scope
```ts
setTimeout("globalThis.console.log(timer)", 1000);
// {
//   id: 1,
//   callback: "globalThis.console.log(timer)",
//   args: [],
//   delay: 1000,
//   due: 1617982526862,
//   repeat: false,
//   scheduled: false
// }
```
https://github.com/denoland/deno/blob/cd0560210aa0ac9dc9772cdddcb1c5a59cef1815/runtime/js/11_timers.js#L445

### PR DESCRIPTION
**Pull request by nayeemrmn**
Fixes #10091.

### CODE REVIEW

File: runtime/js/11_timers.js [hunk 1]
```diff
@@ -442,7 +442,10 @@
     if ("function" === typeof callback) {
       callback();
     } else {
-      eval(callback);
+      const result = core.evalContext(callback);
+      if (result[1] != null) {
+        throw result[1].thrown;
```
Comment (bnoordhuis) [inline runtime/js/11_timers.js:447]: Would `(0, eval)(callback)` work? Rethrowing means this `throw` statement shows up as the exception's origin rather than the evaluated code.

Comment (nayeemrmn) [reply runtime/js/11_timers.js]: I didn't know about `globalThis.eval` vs `eval`. Fixed.

**Review by bnoordhuis — APPROVED** [review]
LGTM. One suggestion: maybe add a regression test?

**Review by bartlomieju — APPROVED** [review]
LGTM
