### PR TITLE
fix(compiler): JSX compilation and provide better error message

### LINKED ISSUE #6057: error: No such file or directory (os error 2)
Running a simple oak server to illustrate [deno-react-example](https://github.com/o2sevruk/deno-react-example) using deno 1.0.3 on Ubuntu results in: "error: No such file or directory (os error 2)"

Would anyone know how to debug this?
Thanks

### PR DESCRIPTION
**Pull request by bartlomieju**
Ref https://github.com/denoland/deno/issues/6057#issuecomment-643634290
Closes #6057 (again)

### CODE REVIEW

File: cli/tests/integration_tests.rs [hunk 1]
```diff
@@ -2015,6 +2015,12 @@ itest!(ts_import_from_js {
   http_server: true,
 });
 
+itest!(jsx_import_from_ts {
+  args: "run --quiet --reload jsx_import_from_ts.ts",
+  output: "jsx_import_from_ts.ts.out",
+  http_server: true,
+});
+
```
Comment (bartlomieju) [inline cli/tests/integration_tests.rs:2023]: Run this test case on master and it fails with: `error: No such file or directory (os error 2)`

File: cli/global_state.rs [hunk 2]
```diff
@@ -342,6 +356,43 @@ fn test_should_allow_js() {
...
+        resolved_type_directive: None,
+      }],
+      referenced_files: vec![],
+      lib_directives: vec![],
+      types_directives: vec![],
+      type_headers: vec![],
+      media_type: MediaType::TypeScript as i32,
+      source_code: "function foo() {}".to_string(),
+    },
+  ]));
```
Comment (ry) [inline cli/global_state.rs:394]: 👍

File: cli/global_state.rs [hunk 3]
```diff
@@ -203,7 +204,16 @@ impl GlobalState {
...
-      state1.ts_compiler.get_compiled_module(&out.url)?
+      state1
+        .ts_compiler
+        .get_compiled_module(&out.url)
+        .map_err(|e| {
+          let msg = e.to_string();
+          OpError::other(format!(
+            "Failed to get compiled source code of {}.\nReason: {}",
+            out.url, msg
+          ))
```
Comment (ry) [inline cli/global_state.rs:215]: If you start adding more messages like this elsewhere, maybe make this into a standalone utility in the future
