### PR TITLE
fix(bundle): reload html entrypoints with --watch

### LINKED ISSUE #30769: `deno bundle --watch` with HTML entrypoint does not fully reconstruct entry HTML
Version: Deno 2.5.0

When using `--watch` with `deno bundle` on an HTML entrypoint, file changes made to watched files trigger a re-bundle, but exclude the HTML entrypoint from being reconstructed fully. This occurs both when making changes to the HTML directly and when updating modules in the tree. When running bundle, the HTML file is correctly reconstructed the first time, both with and without `--watch`, but will not be updated outside of changed script and stylesheet paths .

To reproduce, run `deno bundle --watch` with any HTML file as an entrypoint - use an HTML file with an attached script module. Note that after first run, the output .html file correctly matches content with the entrypoint HTML. Then, edit the entrypoint HTML file with new content (meta tags, links, body content, etc.). The bundler will kick in when the file is saved, as expected, however the content of the output HTML file will not be updated to match the content of entrypoint file. Then, make changes to an imported module. Notice that the output file name of the script is correctly included in the output HTML, but the content of the output HTML still does not match the content of the entrypoint file.

HTML entrypoints are amazing for folks like me that just want to spin something up with minimal config. I hope we can get over some of these small speedbumps

### PR DESCRIPTION
**Pull request by nathanwhit**
Fixes #30769.

### CODE REVIEW

File: cli/tools/bundle/html.rs [hunk 1]
```diff
@@ -201,7 +204,8 @@ pub fn load_html_entrypoint(
   path: &Path,
 ) -> anyhow::Result<HtmlEntrypoint> {
   let contents = std::fs::read_to_string(path)?;
-  parse_html_entrypoint(cwd, path, contents)
+  let canonical_path = path.canonicalize()?;
```
Comment (dsherret) [inline cli/tools/bundle/html.rs]: maybe use `crate::util::fs::canonicalize_path`? It's slightly better.
