### PR TITLE
fix(ext/http): do not set localhost to hostname unnecessarily

### LINKED ISSUE #24776: http serve: pass the hostname as is to user-defined `onListen` handler
Currently we substitute 'localhost' to hostname if the platform is windows and the hostname is "0.0.0.0" to work around the issue of browsers in windows.

https://github.com/denoland/deno/blob/ad5cec27d3ba67c67e501f612d361254def78194/ext/http/00_serve.ts#L664

This makes sense for displaying something more convenient for users, but I think it's not appropriate if the user provide `onListen` callback to `serve` because the user might want to do more than just displaying it using the hostname string (One such idea is https://github.com/denoland/std/issues/5558 ).

I suggest we should move that 'localhost'-substitution logic inside the default `onListen` implementation, instead of the current place.

### PR DESCRIPTION
**Pull request by kt3k**
This PR changes when to cause the hostname substition of `0.0.0.0` -> `localhost`.

Currently we substitute `localhost` to the hostname on windows before calling `options.onListen`, which prevents the users to do more advanced thing using hostname string like https://github.com/denoland/std/issues/5558. This PR changes it not to substitute it when the user provide `onListen` callback.

closes #24776
unblocks https://github.com/denoland/std/issues/5558

### CODE REVIEW

**Review by iuioiua — APPROVED** [review]

**Review by iuioiua — APPROVED** [review]
LGTM again (once Windows test is fixed).

**Comment by kt3k** [comment]
@bartlomieju Does this change look reasonable?

File: ext/http/00_serve.ts [hunk 1]
```diff
@@ -581,6 +581,19 @@ type RawServeOptions = {
 
 const kLoadBalanced = Symbol("kLoadBalanced");
 
+function mapAnyAddrToLocalhostForWindows(hostname: string) {
+  // If the hostname is "0.0.0.0", we display "localhost" in console
+  // because browsers in Windows don't resolve "0.0.0.0".
+  // See the discussion in https://github.com/denoland/deno_std/issues/1165
+  if (
+    (hostname == "0.0.0.0" || hostname == "::") &&
+    (Deno.build.os === "windows")
```
Comment (jsejcksn) [inline ext/http/00_serve.ts:590]: The evaluation won't change by reordering the conditions, but because the platform is a precondition of the others, I think it makes sense to go first (it will short-circuit more quickly for other platforms and avoid the unnecessary comparisons):

```suggestion
    (Deno.build.os === "windows") &&
    (hostname == "0.0.0.0" || hostname == "::")
```
