### PR TITLE
fix(runtime): `ChildProcess::kill()` doesn't require additional perms

### LINKED ISSUE #15217: `Deno.Command` kill ability permission requirement
I ran a subprocess using Deno from within a process that had already been granted a specific run permission for Deno (`--allow-run=deno`), and then tried to kill the child process. I tried two ways: by providing an `AbortSignal` in the options, and by using [`Deno.Child#kill`](https://doc.deno.land/deno/unstable/~/Deno.Child#kill). I was met with this permission prompt both times:

```
⚠️  ️Deno requests run access to all. Run again with --allow-run to bypass this prompt.
   Allow? [y/n (y = yes allow, n = no deny)]
```

I denied it (because I don't want to run the script with unlimited run permissions — I already granted the process name in advance), and an exception was thrown:

```
⚠️  ️Deno requests run access to all. Run again with --allow-run to bypass this prompt.
   Allow? [y/n (y = yes allow, n = no deny)]  n
error: Uncaught (in promise) PermissionDenied: Requires run access to all, run again with the --allow-run flag
  ac.abort();
     ^
    at Object.opSync (deno:core/01_core.js:170:12)
    at Child.kill (deno:runtime/js/40_spawn.js:172:12)
    at onAbort (deno:runtime/js/40_spawn.js:128:34)
    at AbortSignal.[[[signalAbort]]] (deno:ext/web/03_abort_signal.js:80:11)
    at AbortController.abort (deno:ext/web/03_abort_signal.js:159:32)
    at file:///...
```

I haven't followed the stack trace into the built-ins and core yet, but I was quite surprised to see this. Is it a requirement to grant blanket run permission to **all** processes in order to kill **any** child process using the `spawn`/`spawnChild` API? If so, why? And can this be changed before stabilization?

### PR DESCRIPTION
**Pull request by nayeemrmn**
Fixes #15217.

### CODE REVIEW

File: runtime/ops/spawn.rs [hunk 1]
```diff
@@ -226,17 +233,18 @@ async fn op_spawn_wait(
...
-    .await?
-    .try_into()
+    .get::<ChildResource>(rid)?;
+  let result = resource.0.borrow_mut().wait().await?.try_into();
+  state
+    .borrow_mut()
+    .resource_table
+    .close(rid)
+    .expect("shouldn't have closed until now");
+  result
```
Comment (lucacasonato) [inline runtime/ops/spawn.rs:247]: The spawn code change looks good, but I don't like this refcell being hold across await points. Can you instead try to borrow, and if it fails return a `Deno.errors.Busy` error?

Comment (nayeemrmn) [reply runtime/ops/spawn.rs:247]: > Can you instead try to borrow, and if it fails return a `Deno.errors.Busy` error?

Could you clarify this suggestion? It seems like the content of the refcell is needed along the `.wait()` call so this is unavoidable. For context this is the only place it's borrowed, and the only reason I need a refcell is to wrestle with the other reference in the resource table (which didn't previously exist because it was taken out on wait start).

Comment (lucacasonato) [reply runtime/ops/spawn.rs:247]: Ok, ignore the first part of my first comment. The issue is that this code will panic if you call this op concurrenly.

To avoid this, you must switch the `borrow_mut()` on line 241 to a `try_borrow_mut()` and error when that returns `Err(BorrowMutError)`.

File: runtime/ops/spawn.rs [hunk 2]
```diff
@@ -262,3 +270,16 @@ fn op_spawn_sync(
...
+fn op_spawn_kill(
+  state: &mut OpState,
+  rid: ResourceId,
+  signal: String,
+) -> Result<(), AnyError> {
+  if let Ok(child_resource) = state.resource_table.get::<ChildResource>(rid) {
+    kill(child_resource.1 as i32, &signal)?;
+    return Ok(());
+  }
+  Err(type_error("Child process has already terminated."))
```
Comment (jsejcksn) [inline runtime/ops/spawn.rs:284]:
```suggestion
  Err(type_error("Child process is already terminated."))
```

Is _is_ a better verb here?

"has terminated" isn't grammatical in English (unless the meaning is "has terminated itself").

**Review by jsejcksn — CHANGES_REQUESTED** [review]

File: runtime/ops/spawn.rs (hunk 2 above)
Comment (jsejcksn) [reply runtime/ops/spawn.rs]: @nayeemrmn I noticed that you declined to accept this suggested change, but then later pushed a [commit](https://github.com/denoland/deno/pull/15339/commits/59738cad3520ed49afe8257a4b1c3379b11d97a4) which included it exactly as though it were your own contribution. Why is that?

Comment (nayeemrmn) [reply runtime/ops/spawn.rs]: > @nayeemrmn I noticed that you declined to accept this suggested change

?

> but then later pushed a [commit](https://github.com/denoland/deno/pull/15339/commits/59738cad3520ed49afe8257a4b1c3379b11d97a4) which included it exactly as though it were your own contribution. Why is that?

You mean not using the commit suggestion feature? Sometimes I skip past that because I have to search and replace anyway in case there are test expectations to update. Pretty common, didn't realise it was so suspicious 😅 Sounds like you want attribution though so I'll reconstruct the branch

Comment (nayeemrmn) [reply runtime/ops/spawn.rs:284]: Actually I've decided to leave the change out of this PR. This is a pre-existing error message which is unrelated to this change, please open your own PR to improve it. The changes here get squashed anyway.

Comment (jsejcksn) [reply runtime/ops/spawn.rs:284]: > This is a pre-existing error message which is unrelated to this change, please open your own PR to improve it.

Thanks — wilco.

**Comment by bartlomieju** [comment]
@piscisaureus could you take a look? I discussed this PR with Luca and we're mostly happy with it, the only question is if it's guaranteed on Windows that PIDs of subprocesses will not be recycled during the program run (ie. if you spawn a subprocess that has PID X and the subprocess finishes, can system recycle that PID and use it in other subprocess spawned by entirely different process). It appears this is true on Linux and Mac, but we're unsure about Windows.

**Comment by nayeemrmn** [comment]
> ie. if you spawn a subprocess that has PID X and the subprocess finishes, can system recycle that PID and use it in other subprocess spawned by entirely different process

I think this is an extreme edge case that affects the window between the subprocess finishing and the `.wait().await` in rust being resolved and continued after. If in that window the pid is already reallocated to some other process and `child.kill()` in JS is called, that other process will be killed instead.

**Comment by piscisaureus** [comment]
> @piscisaureus could you take a look? I discussed this PR with Luca and we're mostly happy with it, the only question is if it's guaranteed on Windows that PIDs of subprocesses will not be recycled during the program run (ie. if you spawn a subprocess that has PID X and the subprocess finishes, can system recycle that PID and use it in other subprocess spawned by entirely different process). It appears this is true on Linux and Mac, but we're unsure about Windows.

I don't think that guarantee exists on any platform.

**Comment by nayeemrmn** [comment]
For both platforms, the pid is freed up for reuse at the end of `tokio::process::Child::wait()` where implicitly the os handle to the subprocess is dropped/reaped. Ideally we could delay that until _we_ drop the tokio child from the resource table (currently there is a `.await` in between) but this is the best we can do with the API. It's better than the current code right?

**Comment by lucacasonato** [comment]
What if we try_wait on the child just prior to doing the actual killing? If that returns Ok() we don't perform the kill. Due to process zombies on Unix, this should be a non-racy fix (because the pid is only reaped after a successful wait/try_wait (and async wait can't complete in parallel with the killing).

**Comment by nayeemrmn** [comment]
> What if we try_wait on the child just prior to doing the actual killing? If that returns Ok() we don't perform the kill.

The `Child` refcell is already borrowed by `op_spawn_wait()` so we can't access it there. That's why I had to copy the pid out from the refcell.

**Comment by SINE** [comment]
@piscisaureus Would you care to take a glance? Sorry for tagging.

**Review by aapoalas — CHANGES_REQUESTED** [review]
Requires rebase.

**Review by aapoalas — APPROVED** [review]
Looks good to me!

File: runtime/js/40_process.js [hunk 3]
```diff
@@ -317,10 +316,7 @@ class ChildProcess {
   }
 
   kill(signo = "SIGTERM") {
-    if (this.#rid === null) {
-      throw new TypeError("Child process has already terminated.");
-    }
-    ops.op_kill(this.#pid, signo, "Deno.Child.kill()");
+    ops.op_spawn_kill(this.#rid, signo);
```
Comment (bartlomieju) [inline runtime/js/40_process.js:319]: @nayeemrmn could you add a check here that this functions throws once the process finishes running? Ie. make it impossible to call `kill()` on a process that did `new Command().output()`. Also please add a test for this scenario for all 3 APIs used to spawn processes.

**Review by bartlomieju — CHANGES_REQUESTED** [review]
One small blocker for landing. Other than that LGTM

File: runtime/js/40_process.js (hunk 3 above)
Comment (nayeemrmn) [reply runtime/js/40_process.js:324]: This method is only applicable to one of the ways `new Command().spawn()`, otherwise done.

**Review by bartlomieju — APPROVED** [review]
LGTM, thank you @nayeemrmn
