### PR TITLE
fix: ensure concurrent non-statically analyzable dynamic imports do not sometimes fail

### LINKED ISSUE #17918: Deno 1.31.0 sometimes fails importing non-statically analyzable dynamic imports concurrently
Hi.
I've starting to get this weird error on Deno 1.31.0:
https://github.com/lumeland/lume/actions/runs/4262008619/jobs/7417000682#step:7:1139

It works fine on 1.30.3. I've tried to replicate this error in a isolated environment without lucky.
Maybe you have some clue why it happens?

```
Caused by TypeError: Loading unprepared module: file:///home/runner/work/lume/lume/tests/assets/jsx_preact/with-function.jsx#1677238255917, imported from: file:///home/runner/work/lume/lume/core/loaders/module.ts
```

### PR DESCRIPTION
**Pull request by dsherret**
Closes #17918

### CODE REVIEW

File: cli/proc_state.rs [hunk 1]
```diff
@@ -340,15 +339,17 @@ impl ProcState {
     let analyzer = self.parsed_source_cache.as_analyzer();
 
     log::debug!("Creating module graph.");
-    let mut graph = self.graph_data.read().graph_inner_clone();
```
Comment (dsherret) [inline cli/proc_state.rs:343]: I was not thinking about this situation when I wrote this code. Essentially we would take the graph out of the graph data, modify it, then put it back, but multiple graph loads might have been occurring here. A downside is this change makes each dynamic import load sequentially since deno_graph currently does not have a way for multiple loads to update it at the same time.

Comment (bartlomieju) [reply cli/proc_state.rs:343]: I think that's fair in this situation

File: test_util/src/lib.rs [hunk 2]
```diff
@@ -1058,6 +1059,20 @@ async fn main_server(
...
         }
+      } else if let Some(suffix) = req.uri().path().strip_prefix("/deno_std/") {
+        let mut file_path = std_path();
+        file_path.push(suffix);
+        if let Ok(file) = tokio::fs::read(&file_path).await {
+          let file_resp = custom_headers(req.uri().path(), file);
+          return Ok(file_resp);
+        }
+      } else if let Some(suffix) = req.uri().path().strip_prefix("/sleep/") {
+        let duration = suffix.parse::<u64>().unwrap();
```
Comment (bartlomieju) [inline test_util/src/lib.rs:1070]: Can you add a comment here explaining why it's needed?

File: cli/proc_state.rs (hunk 1 above)
Comment (dsherret) [reply cli/proc_state.rs:343]: Yeah, it's only non-concurrent in this section of the loading. The rest is still concurrent.

**Review by bartlomieju — APPROVED** [review]
LGTM, just one nitpick as it's not immediately obvious

File: test_util/src/lib.rs (hunk 2 above)
Comment (dsherret) [reply test_util/src/lib.rs:1070]: There is one where it's used. Is that ok?

https://github.com/denoland/deno/pull/17923/files#diff-2bcd38df42ce86956ec90875b386428bc10044990c85580b2d7558927353d822R1-R3

Comment (dsherret) [reply test_util/src/lib.rs:1070]: I think the one on the usage only is ok and there might be multiple reasons in the future for this. Also, I want this in a canary build for anyone to try who encounters this error so I'm going to merge.
