### PR TITLE
fix(extensions/crypto): change Crypto to interface

### LINKED ISSUE #10850: `Crypto` should be an interface
See failing tests (the ones prefixed with `Crypto interface:`: https://wpt.deno.land/e8be116ab6d06bed764ad9b6cb253d8de36ae73d/WebCryptoAPI/idlharness.https.any.html

`window.crypto instanceof Crypto` should be true, but it is `Uncaught ReferenceError: Crypto is not defined` in Deno :-)

### PR DESCRIPTION
**Pull request by crowlKats**
Closes #10850

### CODE REVIEW

File: extensions/crypto/01_crypto.js [hunk 1]
```diff
@@ -3,54 +3,68 @@
...
+          "The provided ArrayBufferView is not an integer array type",
+          "TypeMismatchError",
+        );
+      }
+      if (arrayBufferView.byteLength > 65536) {
+        throw new DOMException(
+          `The ArrayBufferView's byte length (${arrayBufferView.byteLength}) exceeds the number of bytes of entropy available via this API (65536)`,
+          "QuotaExceededError",
+        );
+      }
```
Comment (lucacasonato) [inline extensions/crypto/01_crypto.js:42]: This should really be done in Rust...

**Review by lucacasonato — APPROVED** [review]
LGTM, thanks!
