### PR TITLE
fix(ext/node): fix unable to resolve fraction.js

### LINKED ISSUE #18535: Error loading `package.json` with `fraction.js`
Ran into an error with resolving the `fraction.js` module which is pulled in by `autoprefixer`. The problem is that `deno` looks for the `package.json` in the wrong path.

Expected: `node_modules/fraction.js/package.json`
Actual: `node_modules/fraction.js/fraction.js/package.json`

Steps to reproduce:

1. `mkdir foo && cd foo`
2. `echo '{ "name": "foo", "scripts": { "build": "microbundle" }, "dependencies": { "microbundle": "0.15.1"}}' >> package.json`
3. `deno task build`

Error:

```sh
error: Uncaught Error: Error loading package.json at /foo/node_modules/.deno/autoprefixer@10.4.14/node_modules/fraction.js/fraction.js/package.json. Not a directory (os error 20)
    at resolveExports (ext:deno_node/01_require.js:508:14)
    at Function.Module._findPath (ext:deno_node/01_require.js:547:31)
    at Function.Module._resolveFilename (ext:deno_node/01_require.js:808:27)
    at Function.Module._load (ext:deno_node/01_require.js:657:27)
    at Module.require (ext:deno_node/01_require.js:871:19)
    at require (ext:deno_node/01_require.js:1011:16)
    at Object.<anonymous> (file:///foo/node_modules/.deno/autoprefixer@10.4.14/node_modules/autoprefixer/lib/resolution.js:1:270)
    at Object.<anonymous> (file:///foo/node_modules/.deno/autoprefixer@10.4.14/node_modules/autoprefixer/lib/resolution.js:99:4)
    at Module._compile (ext:deno_node/01_require.js:938:34)
    at Object.Module._extensions..js (ext:deno_node/01_require.js:971:10)
```

### LINKED ISSUE #18600: Error loading package.json importing `@google-cloud/storage`
```js
import { Storage } from "npm:@google-cloud/storage";
```

```
divy@mini ~/gh> deno run -A --reload gcloud_storage.mjs
error: Uncaught Error: Error loading package.json at /Users/divy/gh/node_modules/.deno/json-bigint@1.0.0/node_modules/bignumber.js/bignumber.js/package.json. Not a directory (os error 20)
    at resolveExports (ext:deno_node/01_require.js:510:14)
    at Function.Module._findPath (ext:deno_node/01_require.js:549:31)
    at Function.Module._resolveFilename (ext:deno_node/01_require.js:809:27)
    at Function.Module._load (ext:deno_node/01_require.js:659:27)
    at Module.require (ext:deno_node/01_require.js:891:19)
    at require (ext:deno_node/01_require.js:1031:16)
    at Object.<anonymous> (file:///Users/divy/gh/node_modules/.deno/json-bigint@1.0.0/node_modules/json-bigint/lib/stringify.js:1:269)
    at Object.<anonymous> (file:///Users/divy/gh/node_modules/.deno/json-bigint@1.0.0/node_modules/json-bigint/lib/stringify.js:386:4)
    at Module._compile (ext:deno_node/01_require.js:958:34)
    at Object.Module._extensions..js (ext:deno_node/01_require.js:991:10)
```

### PR DESCRIPTION
**Pull request by marvinhagemeister**
Turns out `autoprefixer` is a better reproduction case then `microbundle`.

Fixes #18535 
Fixes #18600

### CODE REVIEW

File: ext/node/ops.rs [hunk 1]
```diff
@@ -470,7 +470,13 @@ where
...
     modules_path
   } else {
-    path_resolve(vec![modules_path, name])
+    let orignal = modules_path.clone();
+    let mod_dir = path_resolve(vec![modules_path, name]);
+    if Path::new(&mod_dir).is_dir() {
+      mod_dir
+    } else {
+      orignal
+    }
```
Comment (marvinhagemeister) [inline ext/node/ops.rs:479]: This is the fix here. I'm not too happy about it because it adds a file system check, but it does solve the issue.

The reason I'm not happy about it is that the resolution code expects node_module paths everywhere like `/my-project/node_modules`. But in this [branch here](https://github.com/denoland/deno/blob/c162647020c26de1d27064b488ca11525f1bc4bf/ext/node/polyfills/01_require.js#L618-L626) we ignore that assumption and push a module directory to the list of paths instead (`/my-project/node_modules/my-module`). Then we reach this section here where we'd incorrectly append the package name to the path again resulting in `/my-project/node_modules/my-module/my-module` which doesn't exist and therefore panics.

File: ext/node/ops.rs [hunk 2]
```diff
@@ -470,7 +470,13 @@ where
   {
     modules_path
   } else {
-    path_resolve(vec![modules_path, name])
+    let orignal = modules_path.clone();
+    let mod_dir = path_resolve(vec![modules_path, name]);
+    if Path::new(&mod_dir).is_dir() {
```
Comment (bartlomieju) [inline ext/node/ops.rs:475]: Could you please replace `is_dir()` call with `Env::Fs::metadata()`? We don't want to hardcode access to file-system here, because systems like Deno Deploy, will inject another implementation of file system (via the `Env::Fs` type)

File: ext/node/ops.rs (hunk 1 above)
Comment (bartlomieju) [reply ext/node/ops.rs:479]: Good catch. IIRC this was done to support CJS in situation where we use "global cache" (ie. not creating local `node_modules` directory), but appears that it's wrong. I'm happy to completely reorganize this bit of code so we don't have to do `is_dir()` check.

File: ext/node/ops.rs (hunk 2 above)
Comment (dsherret) [reply ext/node/ops.rs:475]: We should also add `is_dir()` and related methods to https://github.com/denoland/deno/blob/main/ext/node/clippy.toml

Comment (marvinhagemeister) [reply ext/node/ops.rs:475]: Might just be me being new to Rust. I don't have a good feel yet for which methods are preferred and which aren't 👀

Comment (dsherret) [reply ext/node/ops.rs:475]: I think we should add the following (all the methods on std::path::Path that interact with the file system https://doc.rust-lang.org/std/path/struct.Path.html):

```toml
{ path = "std::path::Path::canonicalize", reason = "File system operations should be done using NodeFs trait" },
{ path = "std::path::Path::is_dir", reason = "File system operations should be done using NodeFs trait" },
{ path = "std::path::Path::is_file", reason = "File system operations should be done using NodeFs trait" },
{ path = "std::path::Path::is_symlink", reason = "File system operations should be done using NodeFs trait" },
{ path = "std::path::Path::metadata", reason = "File system operations should be done using NodeFs trait" },
{ path = "std::path::Path::read_dir", reason = "File system operations should be done using NodeFs trait" },
{ path = "std::path::Path::read_link", reason = "File system operations should be done using NodeFs trait" },
{ path = "std::path::Path::symlink_metadata", reason = "File system operations should be done using NodeFs trait" },
{ path = "std::path::Path::try_exists", reason = "File system operations should be done using NodeFs trait" },
```

Comment (bartlomieju) [reply ext/node/ops.rs:475]: My bad here, I should have added these methods to `ext/node/clippy.toml` in a previous PR

Comment (bartlomieju) [reply ext/node/ops.rs]: Updated in #18604 and fixed it in this PR.

**Review by bartlomieju — APPROVED** [review]
LGTM, thank you Marvin! We can clean it up further down the line, but it immediately unblocks us on using a lot more packages, so I'm going to merge it.

**Comment by marvinhagemeister** [comment]
@bartlomieju Thanks for bringing this PR over the finish line 💯
