### PR TITLE
fix(ext/cache): cache.put overwrites previous call

### LINKED ISSUE #17299: Cache::put() behavior
I tested Cache API and noticed that behavior of the ```cache.put()``` changes with different launches of the program.
On the first run, the responses are successfully overwritten, but at the second run and beyond overwriting is not happening.

```js
// test.js - first run

const req = new Request( 'http://localhost/' );
const res1 = new Response( 'test1' );
const res2 = new Response( 'test2' );

let cache = await caches.open( 'test' );

await cache.put( req, res1 );
await cache.put( req, res2 );

let res = await cache.match( req ).then( res => res?.text() );

console.log( res ); // logs "test2"
```

```js
// test.js - second run

await cache.put( req, res2 ); // swap puts order
await cache.put( req, res1 );
// ...
console.log( res ); // also logs "test2"
```

It can be fixed by calling ```caches.delete( 'test' )``` or ```cache.delete( req )``` before puts

Is it right ```cache.put()``` behavior?

### PR DESCRIPTION
**Pull request by satyarohith**
Fixes #17299

### CODE REVIEW

File: ext/cache/sqlite.rs [hunk 1]
```diff
@@ -368,13 +350,24 @@ impl CachePutResource {
...
       self.put_request.clone(),
-      Some((self.response_body_key.clone(), self.start_time)),
+      Some(self.response_body_key.clone()),
     )
     .await?;
-    Ok(())
+    match maybe_body_key {
+      Some(key) => {
+        // Ensure the response body key is the same as the one we
+        // inserted into the database.
```
Comment (satyarohith) [inline ext/cache/sqlite.rs:362]:
```suggestion
```

File: ext/cache/sqlite.rs [hunk 2]
```diff
@@ -368,13 +350,24 @@ impl CachePutResource {
...
+        assert_eq!(key, self.response_body_key);
+        Ok(())
+      }
+      // This should never happen.
```
Comment (satyarohith) [inline ext/cache/sqlite.rs:366]:
```suggestion
      // This should never happen because we will always have
      // body key associated with CachePutResource
```

File: ext/cache/sqlite.rs [hunk 3]
```diff
@@ -285,29 +285,11 @@ impl Cache for SqliteBackedCache {
...
-        response_body_key = Some(body_key);
-          let last_inserted_at = db.query_row("
-          SELECT last_inserted_at FROM request_response_list
-          WHERE cache_id = ?1 AND request_url = ?2",
-          (put.cache_id, &put.request_url), |row| {
-            let last_inserted_at: i64 = row.get(0)?;
-            Ok(last_inserted_at)
-          }).optional()?;
-          if let Some(last_inserted) = last_inserted_at {
-            // Some other worker has already inserted this resource into the cache.
```
Comment (satyarohith) [inline ext/cache/sqlite.rs:304]: This assumption isn't true as the response body can be different for multiple put operations with the same request.

File: ext/cache/sqlite.rs [hunk 4]
```diff
@@ -368,13 +350,23 @@ impl CachePutResource {
...
       self.db.clone(),
       self.put_request.clone(),
-      Some((self.response_body_key.clone(), self.start_time)),
+      Some(self.response_body_key.clone()),
     )
     .await?;
-    Ok(())
+    match maybe_body_key {
+      Some(key) => {
+        assert_eq!(key, self.response_body_key);
```
Comment (satyarohith) [inline ext/cache/sqlite.rs:361]: The unit test fails at this assertion if the response isn't overwritten.

File: cli/tests/unit/cache_api_test.ts [hunk 5]
```diff
@@ -173,3 +173,20 @@ Deno.test(async function cachePutFailedBody() {
...
+  const res2 = new Response("res2");
+
+  await cache.put(request, res1);
+  const res = await cache.match(request);
+  assertEquals(await res?.text(), "res1");
+
+  await cache.put(request, res2);
+  const res_ = await cache.match(request);
+  assertEquals(await res_?.text(), "res2");
+});
```
Comment (ry) [inline cli/tests/unit/cache_api_test.ts:192]: The test passes on main

Comment (satyarohith) [reply cli/tests/unit/cache_api_test.ts:192]: Run it twice and it will fail.

Comment (ry) [reply cli/tests/unit/cache_api_test.ts:192]: It passes the second run too

Comment (satyarohith) [reply cli/tests/unit/cache_api_test.ts:192]: Unfortunately, we need to preserve sqlite metadata to reproduce the bug and it doesn't work for unit tests as every invocation gets new sqlite db file. I created integration tests that fail on main: https://github.com/denoland/deno/pull/18649/commits/515d599b4a71edaba793cf7f40959fd5a2093f5e

File: cli/tests/integration/cache_tests.rs [hunk 6]
```diff
@@ -107,3 +107,49 @@ itest!(package_json_basic {
   copy_temp_dir: Some("package_json/basic"),
   exit_code: 0,
 });
+
+// Cache API put() regression tests.
+// See https://github.com/denoland/deno/issues/17299
+// Note: It is important that part1 runs before part2.
```
Comment (dsherret) [inline cli/tests/integration/cache_tests.rs:113]: If it's important for part1 to run before part2 then maybe these should be a single test? We could rewrite it using the `TestContextBuilder`.

Also, I'm not sure how this tests it because doesn't the `itest` macro use a fresh deno_dir each time? Also, doesn't Rust execute tests in parallel?

Comment (bartlomieju) [reply cli/tests/integration/cache_tests.rs:113]: > Also, I'm not sure how this tests it because doesn't the itest macro use a fresh deno_dir each time? 

It does

> Also, doesn't Rust execute tests in parallel?

Yup

+1 for rewriting it using `TestContextBuilder`

Comment (satyarohith) [reply cli/tests/integration/cache_tests.rs]: TestContextBuilder is exactly what I wanted. Thanks!

**Review by bartlomieju — APPROVED** [review]
LGTM, verified that the test fails on `main`

File: cli/tests/integration/cache_tests.rs [hunk 7]
```diff
@@ -107,3 +108,57 @@ itest!(package_json_basic {
...
+  let run_command =
+    test_context.new_command().args_vec(["run", "cache_put.js"]);
+
+  let output = run_command.run();
+  output.assert_matches_text("res2\n");
+  output.assert_exit_code(0);
+
+  // The wait will surface the bug as we check last written time
+  // when we overwrite a response.
+  tokio::time::sleep(std::time::Duration::from_secs(1)).await;
```
Comment (ry) [inline cli/tests/integration/cache_tests.rs:158]: nit: you can use `std::time:sleep` here instead and avoid making this test async.
