### PR TITLE
fix(ext/web): Prevent (De-)CompressionStream resource leak on stream cancellation

### LINKED ISSUE #14212: Aborting a CompressionStream/DecompressionStream leaks a resource
If inside of a test you call abort() on the writable end of a CompressionStream or DecompressionStream instead of close(), then you get a Deno error about a resource being leaked.

```ts
Deno.test(
  "CompressionStream may be aborted",
  // { sanitizeResources: false },
  async () => {
    const compressionStream = new CompressionStream("gzip");

    async function write() {
      const writer = compressionStream.writable.getWriter();
      await writer.ready;
      await writer.write(new Uint8Array([1, 2, 3]));
      try {
        await writer.abort(new Error("aborting"));
      } catch {
        // abort rejects with the error we give it so ignore that
      }
    }

    async function read() {
      try {
        const reader = compressionStream.readable.getReader();
        console.log("bytes received:", (await reader.read()).value?.byteLength);
        console.log("bytes received:", (await reader.read()).value?.byteLength);
      } catch (err) {
        console.log(
          "got error in read() because of abort call in write()",
          err,
        );
      }
    }

    await Promise.all([
      write(),
      read(),
    ]);
  },
);
```

If `sanitizeResources: false` is set, then this gives the expected output:

```
$ deno test fail_test.ts
Check file:///Users/macil/Coding/streaming-zip/fail_test.ts
running 1 test from file:///Users/macil/Coding/streaming-zip/fail_test.ts
test CompressionStream may be aborted ...bytes received: 19

got error in read() because of abort call in write() Error: aborting
    at write (file:///Users/macil/Coding/streaming-zip/fail_test.ts:12:28)
    at async Promise.all (index 0)
    at async file:///Users/macil/Coding/streaming-zip/fail_test.ts:31:5
    at async testStepSanitizer (deno:runtime/js/40_testing.js:444:7)
    at async asyncOpSanitizer (deno:runtime/js/40_testing.js:145:9)
    at async Object.exitSanitizer [as fn] (deno:runtime/js/40_testing.js:427:9)
    at async runTest (deno:runtime/js/40_testing.js:788:7)
    at async Object.runTests (deno:runtime/js/40_testing.js:986:22)

 ok (4ms)

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out (10ms)
```

But when run normally, this output happens instead:

```
$ deno test fail_test.ts
Check file:///Users/macil/Coding/streaming-zip/fail_test.ts
running 1 test from file:///Users/macil/Coding/streaming-zip/fail_test.ts
test CompressionStream may be aborted ...bytes received: 19

got error in read() because of abort call in write() Error: aborting
    at write (file:///Users/macil/Coding/streaming-zip/fail_test.ts:12:28)
    at async Promise.all (index 0)
    at async file:///Users/macil/Coding/streaming-zip/fail_test.ts:31:5
    at async testStepSanitizer (deno:runtime/js/40_testing.js:444:7)
    at async asyncOpSanitizer (deno:runtime/js/40_testing.js:145:9)
    at async resourceSanitizer (deno:runtime/js/40_testing.js:370:7)
    at async Object.exitSanitizer [as fn] (deno:runtime/js/40_testing.js:427:9)
    at async runTest (deno:runtime/js/40_testing.js:788:7)
    at async Object.runTests (deno:runtime/js/40_testing.js:986:22)

 FAILED (5ms)

failures:

CompressionStream may be aborted
AssertionError: Test case is leaking 1 resource:

 - A CompressionStream (rid 3) was created during the test, but not closed during the test. Close the compression stream by calling `await stream.writable.close()`.

    at assert (deno:ext/web/00_infra.js:293:13)
    at resourceSanitizer (deno:runtime/js/40_testing.js:409:7)
    at async Object.exitSanitizer [as fn] (deno:runtime/js/40_testing.js:427:9)
    at async runTest (deno:runtime/js/40_testing.js:788:7)
    at async Object.runTests (deno:runtime/js/40_testing.js:986:22)

failures:

	CompressionStream may be aborted

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out (11ms)

error: Test failed
```

The same issue exists with DecompressionStream too.

The same issue also exists if the CompressionStream's readable end is canceled (instead of the writable end being aborted):

<details>
  <summary>Details about error in canceling</summary>

```ts
Deno.test(
  "CompressionStream may be aborted",
  // { sanitizeResources: false },
  async () => {
    const compressionStream = new CompressionStream("gzip");

    async function write() {
      const writer = compressionStream.writable.getWriter();
      await writer.ready;
      try {
        await writer.write(new Uint8Array([1, 2, 3]));
      } catch (err) {
        console.log(
          "got error in write() because of cancel call in read()",
          err,
        );
      }
    }

    async function read() {
      try {
        const reader = compressionStream.readable.getReader();
        await reader.cancel(new Error("canceling"));
      } catch {
        // ignore error rethrown by cancel call
      }
    }

    await Promise.all([
      write(),
      read(),
    ]);
  },
);
```

Expected output:

```
$ deno test fail_test.ts
Check file:///Users/macil/Coding/streaming-zip/fail_test.ts
running 1 test from file:///Users/macil/Coding/streaming-zip/fail_test.ts
test CompressionStream may be aborted ...got error in write() because of cancel call in read() Error: canceling
    at read (file:///Users/macil/Coding/streaming-zip/fail_test.ts:23:29)
    at file:///Users/macil/Coding/streaming-zip/fail_test.ts:31:7
    at testStepSanitizer (deno:runtime/js/40_testing.js:444:13)
    at asyncOpSanitizer (deno:runtime/js/40_testing.js:145:15)
    at Object.exitSanitizer [as fn] (deno:runtime/js/40_testing.js:427:15)
    at runTest (deno:runtime/js/40_testing.js:788:18)
    at Object.runTests (deno:runtime/js/40_testing.js:986:28)
    at [deno:cli/tools/test.rs:512:6]:1:21

 ok (4ms)

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out (10ms)
```

Actual output:

```
$ deno test fail_test.ts
Check file:///Users/macil/Coding/streaming-zip/fail_test.ts
running 1 test from file:///Users/macil/Coding/streaming-zip/fail_test.ts
test CompressionStream may be aborted ...got error in write() because of cancel call in read() Error: canceling
    at read (file:///Users/macil/Coding/streaming-zip/fail_test.ts:23:29)
    at file:///Users/macil/Coding/streaming-zip/fail_test.ts:31:7
    at testStepSanitizer (deno:runtime/js/40_testing.js:444:13)
    at asyncOpSanitizer (deno:runtime/js/40_testing.js:145:15)
    at resourceSanitizer (deno:runtime/js/40_testing.js:370:13)
    at Object.exitSanitizer [as fn] (deno:runtime/js/40_testing.js:427:15)
    at runTest (deno:runtime/js/40_testing.js:788:18)
    at Object.runTests (deno:runtime/js/40_testing.js:986:28)
    at [deno:cli/tools/test.rs:512:6]:1:21

 FAILED (5ms)

failures:

CompressionStream may be aborted
AssertionError: Test case is leaking 1 resource:

 - A CompressionStream (rid 3) was created during the test, but not closed during the test. Close the compression stream by calling `await stream.writable.close()`.

    at assert (deno:ext/web/00_infra.js:293:13)
    at resourceSanitizer (deno:runtime/js/40_testing.js:409:7)
    at async Object.exitSanitizer [as fn] (deno:runtime/js/40_testing.js:427:9)
    at async runTest (deno:runtime/js/40_testing.js:788:7)
    at async Object.runTests (deno:runtime/js/40_testing.js:986:22)

failures:

	CompressionStream may be aborted

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out (10ms)

error: Test failed
```

</details>

### PR DESCRIPTION
**Pull request by egfx-notifications**
Based on #21074 and #20741 I was looking for further potential use cases of `TransformStream` `cancel()` method, so here go `CompressionStream` and `DecompressionStream`.

Fixes #14212

### CODE REVIEW

File: cli/tests/unit/streams_test.ts [hunk 1]
```diff
@@ -468,3 +468,47 @@ Deno.test(async function readableStreamWithAggressiveResourceClose() {
...
+});
+
+Deno.test(async function decompressionStreamWritableMayBeAborted() {
+  await Promise.all([
+    assertRejects(
+      async () => {
+        await new DecompressionStream("gzip").writable.getWriter().abort();
+      },
+      TypeError,
+      "corrupt gzip stream does not have a matching checksum",
```
Comment (mmastrac) [inline cli/tests/unit/streams_test.ts:495]: I don't think we should throw on cancellation. This probably means we need a separate Rust op (or a second parameter) to just throw away the results.

File: ext/web/14_compression.js [hunk 2]
```diff
@@ -88,6 +91,9 @@ class DecompressionStream {
         const output = ops.op_compression_finish(rid);
         maybeEnqueue(controller, output);
       },
+      cancel: (_reason) => {
+        ops.op_compression_finish(rid);
```
Comment (mmastrac) [inline ext/web/14_compression.js:95]: This could be `ops.op_compression_finish(rid, false)`, and we could use `ops.op_compression_finish(rid, true)` for the success case right above.

File: cli/tests/unit/streams_test.ts (hunk 1 above)
Comment (egfx-notifications) [reply cli/tests/unit/streams_test.ts:495]: I actually started work on a separate Rust op, but then decided that we should probably give the user the chance to handle this case as they see fit. Thinking of intentional abortion on the user side where the user wants to continue work with the results received so far, it would be good to let the user know if they need to perform some manual cleanup on the last bytes received or can use the slice as is. This being said, I don't know the specifics of gzip, deflate and deflate-raw enough to say if a decompressed slice is even usable, this being implemented as a stream I suppose it is. If it is, I'd at least give the user the option to request error bubbling, maybe with an options object to the `CompressionStream` and `DecompressionStream` constructors.

Comment (mmastrac) [reply cli/tests/unit/streams_test.ts:495]: I'm not entirely sure here...  I might have to hand this one off to someone with a better intuition. 

Cancellation on a TextDecoderStream in Firefox appears to reject the read with the cancellation rather than throwing from the writer abort:

```
(async () => { let td = new TextDecoderStream(); td.writable.abort("hmm"); await td.readable.getReader().read() })()
Promise { <state>: "rejected", <reason>: "hmm" }
```

I wonder if this is the right way to do things here.

Comment (lucacasonato) [reply cli/tests/unit/streams_test.ts:495]: Yeah, we should follow browser behaviour here (`.cancel()` should not throw)

`cancel()` should just `close()` the underlying resource I think.

Comment (egfx-notifications) [reply cli/tests/unit/streams_test.ts]: Agreed, I pushed the necessary changes.

**Comment by egfx-notifications** [comment]
Just added two more tests to verify that my changes did not break `flush()` for both successful and erroneous `close()` of the stream.

**Review by mmastrac — APPROVED** [review]
LGTM! I rebased it on the latest main.
