### PR TITLE
fix(lsp): correct scope attribution for injected @types/node

### LINKED ISSUE #24401: No types for node builtin modules in LSP
Regressed in #24206.

On the previous commit: 
```
deno 1.44.2+3419133 (canary, aarch64-apple-darwin)
```
Screenshot 2024-07-02 at 2 48 08 PM

After PR merged:
```
deno 1.44.2+5dec3fd (canary, aarch64-apple-darwin)
```
Screenshot 2024-07-02 at 2 47 44 PM

### PR DESCRIPTION
**Pull request by nayeemrmn**
Fixes #24401.

### CODE REVIEW

File: cli/lsp/tsc.rs [hunk 1]
```diff
@@ -4514,29 +4507,41 @@ fn op_script_names(state: &mut OpState) -> ScriptNames {
   let scopes_with_node_specifier =
     state.state_snapshot.documents.scopes_with_node_specifier();
   if scopes_with_node_specifier.contains(&None) {
-    result
-      .unscoped
-      .insert("asset:///node_types.d.ts".to_string());
+    let req_ref =
+      deno_semver::npm::NpmPackageReqReference::from_str("npm:@types/node")
```
Comment (nathanwhit) [inline cli/lsp/tsc.rs:4511]: Why `npm:@types/node` instead of the asset file?

Comment (nayeemrmn) [reply cli/lsp/tsc.rs]: It was so it could be turned into a file URL here and have proper scope attribution, but I passed the scope to `Documents::resolve()` instead to use as a fallback (when resolving `npm:@types/node` from `asset:///node_types.d.ts`).

**Review by nathanwhit — APPROVED** [review]
LGTM
