### PR TITLE
fix(upgrade): ensure temp dir cleanup on failure

### LINKED ISSUE #17533: 🐛 POSIX: `deno upgrade` leaves temporary directory with large files in */tmp*
When upgrading from Deno v1.29.4 to v1.30.0, the upgrade failed because of tmpfs exhaustion. In tracking the issue, it was apparent that when using `deno upgrade`, Deno leaves a temporary directory in */tmp* with the downloaded zip file and its expansion. At least one prior version left the same residual files. As it didn't fail at the time, I can't determine which earlier versions are affected (maybe all of them).

```shell
$ ls -Al .tmpQ2GQJW
total 141460
-rwxr-x--x 1 root administrators 105538456 2023-01-16 16:42 deno
-rw-r----- 1 root administrators  39309948 2023-01-25 18:42 deno.zip
```
Obviously, these files are relatively large and this can exhaust the */tmp* storage quite quickly if not removed promptly. Please clean up after the upgrade is completed.

### PR DESCRIPTION
**Pull request by dsherret**
Closes #17533

### CODE REVIEW

File: cli/tools/upgrade.rs [hunk 1]
```diff
@@ -423,6 +424,7 @@ pub async fn upgrade(
     }
   }
 
+  drop(temp_dir); // delete the temp dir
```
Comment (littledivy) [inline cli/tools/upgrade.rs:427]: redundant?

**Review by littledivy — APPROVED** [review]
LGTM

File: cli/tools/upgrade.rs (hunk 1 above)
Comment (dsherret) [reply cli/tools/upgrade.rs:427]: Yes, but purposefully in order to ensure a compile error would occur if the scope of temp_dir accidentally changed
