### PR TITLE
fix(npm): support npmrc email authorization

### LINKED ISSUE #23952: .npmrc: support `email` auth configuration
https://docs.npmjs.com/cli/v10/configuring-npm/npmrc#auth-related-configuration

Needs to be addressed after https://github.com/denoland/deno/pull/23560 lands.

### PR DESCRIPTION
**Pull request by seroperson**
Small change to support `email` auth in `.npmrc`. 

https://docs.npmjs.com/cli/v10/configuring-npm/npmrc#auth-related-configuration

Closes #23952

### CODE REVIEW

File: libs/npm_cache/remote.rs [hunk 1]
```diff
@@ -26,17 +28,18 @@ pub fn maybe_auth_header_value_for_npm_registry(
...
-  );
-  if (username.is_some() && password.is_none())
-    || (username.is_none() && password.is_some())
+  let username_or_email = registry_config
+    .username
+    .as_ref()
+    .or(registry_config.email.as_ref());
+  let password = registry_config.password.as_ref();
+  if (username_or_email.is_some() && password.is_none())
+    || (username_or_email.is_none() && password.is_some())
```
Comment (dsherret) [inline libs/npm_cache/remote.rs]:
```suggestion
  if username_or_email.is_some() != password.is_some()
```

File: libs/npm_cache/remote.rs [hunk 2]
```diff
@@ -26,17 +28,17 @@ pub fn maybe_auth_header_value_for_npm_registry(
...
-  );
-  if (username.is_some() && password.is_none())
-    || (username.is_none() && password.is_some())
+  let username_or_email = registry_config
+    .username
+    .as_ref()
+    .or(registry_config.email.as_ref());
+  let password = registry_config.password.as_ref();
+  if username_or_email.is_some() != password.is_some()
   {
```
Comment (dsherret) [inline libs/npm_cache/remote.rs]:
```suggestion
  if username_or_email.is_some() != password.is_some() {
```
