### PR TITLE
fix: support typechecking docs with CRLF line endings

### LINKED ISSUE #12187: `deno test --doc` doesn't detect errors in Markdown files with CRLF line endings
When I make a new `.md` file with some code that should throw a type error:

\```ts
let str: string = 1;
\```

If the file has CRLF line endings, running `deno test --doc` will not detect any problems.

Switching to LF works properly and throws the expected error:
```
error: TS2322 [ERROR]: Type 'number' is not assignable to type 'string'.
```
Deno 1.14.0

### PR DESCRIPTION
**Pull request by GJZwiers**
This fixes #12187 and enables `deno test --doc` to typecheck docs that make use of `\r\n` line endings (CRLF). An additional integration test has been added that asserts that the doc typechecker has the same output as it did for the test which has LF. I updated  `.gitattributes` to keep CRLF in one  `.md` file in the `testdata/test` directory, and added some ignore/excludes for this file where needed.

### CODE REVIEW

File: cli/tests/integration/fmt_tests.rs [hunk 1]
```diff
@@ -129,7 +129,7 @@ fn fmt_ignore_unexplicit_files() {
 }
 
 itest!(fmt_check_tests_dir {
-  args: "fmt --check ./ --ignore=.test_coverage,fmt/fmt_with_config/",
+  args: "fmt --check ./ --ignore=.test_coverage,fmt/fmt_with_config/,test/markdown_windows.md",
```
Comment (bartlomieju) [inline cli/tests/integration/fmt_tests.rs:132]: This is unfortunate, I opened https://github.com/denoland/deno/issues/12758 to fix this situation

**Review by dsherret — APPROVED** [review]
LGTM. Thanks @GJZwiers!
