### PR TITLE
fix(std/io): BufWriter/StringWriter bug

### LINKED ISSUE #6220: std: BufWriter/StringWriter bug
The following fails, but should pass:

```ts
import { BufWriter } from "https://deno.land/std@0.56.0/io/bufio.ts";
import { StringWriter } from "https://deno.land/std@0.56.0/io/writers.ts";
import { assertEquals } from "https://deno.land/std@0.56.0/testing/asserts.ts";

const test = Deno.test;

test({
  name: "defect with writer",
  async fn() {
    const stringWriter = new StringWriter();
    const bufWriter = new BufWriter(stringWriter);
    const encoder = new TextEncoder();
    await bufWriter.write(encoder.encode("hello\nworld\nhow\nare\nyou?\n\n"));
    await bufWriter.flush();
    await bufWriter.write(encoder.encode("foobar\n\n"));
    await bufWriter.flush();
    const actual = stringWriter.toString();
    assertEquals(actual, "hello\nworld\nhow\nare\nyou?\n\nfoobar\n\n");
  },
});
```

The expected output should be:

```
hello
world
how
are
you?

foobar

```

The actual output is:

```
foobar

rld
how
are
you?

foobar

```

Somehow the second write is being written into both chunks within the `StringWriter`.

### PR DESCRIPTION
**Pull request by marcosc90**
Fixes #6220

The issue is that `StringWriter` buffers the `Uint8Array` in every `.write`, and that chunk is pointing to the buffer from `BufWriter`, so when a new chunk is written, is modifying the buffered chunk in `StringWriter`.

There are at least 3 possible solutions that I can think of:

- Using `.slice` instead of `.subarray` in `BufWriter.flush` (The one I used to show the issue)
- Resetting `this.buf` in `BufWriter.flush`: `this.buf = new Uint8Array(this.buf.length)`
- Using `p.slice` in `StringWriter.write`

### CODE REVIEW

**Comment by kitsonk** [comment]
It feels like `BufWriter` shouldn't be leaking its internal arrays, like it is doing with the use of `.subarray`.  While option 3 works for this use case, it puts the duty on every implementation of `Deno.write()` that it can't "own" the `Uint8Array` being passed to it on write.  That doesn't seem right.  Thoughts @ry?

File: std/io/bufio_test.ts [hunk 1]
```diff
@@ -469,3 +470,18 @@ Deno.test(
...
+    const bufWriter = new BufWriter(stringWriter);
+    const encoder = new TextEncoder();
+    await bufWriter.write(encoder.encode("hello\nworld\nhow\nare\nyou?\n\n"));
+    await bufWriter.flush();
+    await bufWriter.write(encoder.encode("foobar\n\n"));
+    await bufWriter.flush();
+    const actual = stringWriter.toString();
+    assertEquals(actual, "hello\nworld\nhow\nare\nyou?\n\nfoobar\n\n");
+  },
+});
```
Comment (ry) [inline std/io/bufio_test.ts:487]: I checked that this fails on master

File: std/io/bufio.ts [hunk 2]
```diff
@@ -571,7 +571,7 @@ export class BufWriterSync extends AbstractBufBase implements WriterSync {
     let numBytesWritten = 0;
     try {
       numBytesWritten = this.writer.writeSync(
-        this.buf.subarray(0, this.usedBufferBytes)
+        this.buf.slice(0, this.usedBufferBytes)
```
Comment (ry) [inline std/io/bufio.ts:574]: Test only demonstrates the async case... So this change is untested

**Comment by ry** [comment]
> Resetting this.buf in BufWriter.flush: this.buf = new Uint8Array(this.buf.length)

This seems the most reasonable to me....

File: std/io/bufio.ts (hunk 2 above)
Comment (marcosc90) [reply std/io/bufio.ts:574]: I'll submit a test, we don't have a `StringWriter.writeSync` method though. I can implement it in this PR too or submit a new one with that addition if we do want a synchronous method on `StringWriter`.

Otherwise I'll write a test without using `StringWriter`.

**Comment by marcosc90** [comment]
You're welcome and no worries!

**Comment by marcosc90** [comment]
@kitsonk @ry I know this has been merged, but want to point out that [`Writer.write`](https://doc.deno.land/https/github.com/denoland/deno/releases/latest/download/lib.deno.d.ts#Deno.Writer) documentation states the following

> Implementations should not retain a reference to `p`.
