### PR TITLE
fix(install): retry downloads of registry info / tarballs

### LINKED ISSUE #26085: Make `deno install` automatically retry network requests.
I have been porting a project to deno, and my current internet connection is slightly unstable. Because of this, `deno install` will randomly fail a network request. This is causing a lot of issues building my docker containers. The errors always look something like this:

```
0.094 Download https://registry.npmjs.org/yaml
0.094 Download https://registry.npmjs.org/word-wrap
0.094 Download https://registry.npmjs.org/esbuild
0.163 error: failed reading lockfile '/app/deno.lock'
0.163 
0.163 Caused by:
0.163     Error getting response at https://registry.npmjs.org/@alloc/quick-lru for package "@alloc/quick-lru": error sending request for url (https://registry.npmjs.org/@alloc/quick-lru): client error (Connect): tcp connect error: Network is unreachable (os error 101): Network is unreachable (os error 101)
------
Dockerfile:15
--------------------
  13 |     FROM base AS client
  14 |     COPY client/package.json client/deno.lock ./
  15 | >>> RUN deno install --allow-scripts --frozen=true
  16 |     COPY client/ ./
  17 |     RUN deno task build
--------------------
ERROR: failed to solve: process "/bin/sh -c deno install --allow-scripts --frozen=true" did not complete successfully: exit code: 1
```

It is always a different package that fails, which is why I suspect intermittent network issues. Currently I have to just run `docker build` over and over until it happens to be successful and docker can cache the layer. If deno were to automatically retry the requests a few times before failing, this issue would be mitigated.

### PR DESCRIPTION
**Pull request by nathanwhit**
Fixes #26085.

Adds a basic retry utility with some defaults, starts off with a 1ms wait, then 10x for each successive attempt, up to a max of 1 second and 5 attempts.

I've applied the retry in the http client, reusing an existing function, so this also applies to retrying downloads of deno binaries in `upgrade` and `compile`. I can make a separate function that doesn't retry so this doesn't affect `upgrade` and `compile`, but it seemed desirable to have retries there too, so I left it in.

### CODE REVIEW

File: cli/http_util.rs [hunk 1]
```diff
@@ -470,15 +470,20 @@ impl HttpClient {
...
-      .download_inner(url, maybe_header, Some(progress_guard))
-      .await
+    crate::util::retry::retry(|| {
+      self.download_inner(
+        url.clone(),
+        maybe_header.clone(),
+        Some(progress_guard),
+      )
+    })
+    .await
```
Comment (dsherret) [inline cli/http_util.rs:486]: Maybe we should only retry certain errors? For example, this seems to retry errors like "Too many redirects."

File: cli/util/retry.rs [hunk 2]
```diff
@@ -0,0 +1,29 @@
...
+    let mut attempt = 1;
+    loop {
+      let result = f().await;
+      if result.is_ok() {
+        return result;
+      }
+      if attempt >= ATTEMPTS {
+        return result;
+      }
+      tokio::time::sleep(wait).await;
```
Comment (dsherret) [inline cli/util/retry.rs:23]: The initial wait seems quite short and waiting a total of 2s (?) seems a bit long when there's a legitimate error. That said, maybe we should just retry once like what's done in file_fetcher.rs, but that's probably not good enough.

File: cli/util/retry.rs [hunk 3]
```diff
@@ -0,0 +1,29 @@
...
+  async move {
+    let mut wait = Duration::from_millis(1);
+    let mut attempt = 1;
+    loop {
+      let result = f().await;
+      if result.is_ok() {
+        return result;
+      }
+      if attempt >= ATTEMPTS {
+        return result;
```
Comment (dsherret) [inline cli/util/retry.rs:21]: Maybe we should surface the first error instead of last one? The last one might be a rate limit.

File: cli/util/retry.rs (hunk 2 above)
Comment (nathanwhit) [reply cli/util/retry.rs:23]: How about 10ms->50ms->250ms? So three retries, with a worst case of 310ms.

Comment (bartlomieju) [reply cli/util/retry.rs:23]: I suggest 100->250->500ms. If the service doesn't recover then it's probably down.

File: cli/http_util.rs (hunk 1 above)
Comment (nathanwhit) [reply cli/http_util.rs:489]: Changed to only retry on fetch and bad response errors

**Review by dsherret — APPROVED** [review]
LGTM!
