### PR TITLE
fix(ext/http): Deno.Server should not be thenable

### LINKED ISSUE #20446: Deno errors when an async function returns `Deno.Server`
Minimal reproducible code:

```js
async function serve() {
  return Deno.serve(() => new Response("hi"));
}

serve();
```

Result:

```
$ deno run -A --unstable main.ts
Listening on http://localhost:8000/
error: Uncaught (in promise) Error: Deno.serve no longer returns a promise. await server.finished instead of server.
    at Object.then (ext:deno_http/00_serve.js:645:13)
```

Deno version:

```
$ deno --version
deno 1.36.4 (release, x86_64-pc-windows-msvc)
v8 11.6.189.12
typescript 5.1.6
```

### PR DESCRIPTION
**Pull request by lucacasonato**
Otherwise you can not return `Deno.Server` from async functions.

Fixes #20446

### CODE REVIEW

File: cli/tests/unit/serve_test.ts [hunk 1]
```diff
@@ -3715,3 +3715,14 @@ async function curlRequestWithStdErr(args: string[]) {
   assert(success);
   return [new TextDecoder().decode(stdout), new TextDecoder().decode(stderr)];
 }
+
+Deno.test("Deno.Server is not thenable", async () => {
+  // deno-lint-ignore require-await
+  async function serveTest() {
+    const server = Deno.serve({ port: servePort });
```
Comment (kt3k) [inline cli/tests/unit/serve_test.ts:3722]:
```suggestion
    const server = Deno.serve({ port: servePort }, (_) => {});
```

**Comment by mmastrac** [comment]
Good catch. LGTM!

File: cli/tests/unit/serve_test.ts [hunk 2]
```diff
@@ -3715,3 +3715,14 @@ async function curlRequestWithStdErr(args: string[]) {
   assert(success);
   return [new TextDecoder().decode(stdout), new TextDecoder().decode(stderr)];
 }
+
+Deno.test("Deno.Server is not thenable", async () => {
+  // deno-lint-ignore require-await
+  async function serveTest() {
+    const server = Deno.serve({ port: servePort }, (_) => {});
```
Comment (kt3k) [inline cli/tests/unit/serve_test.ts:3722]:
```suggestion
    const server = Deno.serve({ port: servePort }, (_) => new Response(""));
```
