### PR TITLE
fix(cli): Prefer npm bin entries provided by packages closer to the root

### LINKED ISSUE #24012: Bug: `deno install` produces warnings for packages it installed itself
Running `deno install` produces a few warnings about packages already existing in the directory that the command itself did set up. The `node_modules` folder didn't exist before running this command.

## Steps to reproduce

1. Clone https://github.com/preactjs/preact
2. Run `cd preact`
3. Run `DENO_FUTURE=1 deno install`

## Output

```sh
DENO_FUTURE=1 deno-git i
⚠️ `deno install` behavior will change in Deno 2. To preserve the current behavior use the `-g` or `--global` flag.
Warning Trying to set up 'uuid' bin for "../.deno/uuid@8.3.2/node_modules/uuid/dist/bin/uuid", but an entry pointing to "/Users/marvinh/dev/oss/preact/node_modules/.deno/uuid@3.4.0/node_modules/uuid/./bin/uuid" already exists. Skipping...
Warning Trying to set up 'semver' bin for "../.deno/semver@6.3.1/node_modules/semver/bin/semver.js", but an entry pointing to "/Users/marvinh/dev/oss/preact/node_modules/.deno/semver@5.7.2/node_modules/semver/bin/semver" already exists. Skipping...
Warning Trying to set up 'jsesc' bin for "../.deno/jsesc@2.5.2/node_modules/jsesc/bin/jsesc", but an entry pointing to "/Users/marvinh/dev/oss/preact/node_modules/.deno/jsesc@0.5.0/node_modules/jsesc/bin/jsesc" already exists. Skipping...
Warning Trying to set up 'semver' bin for "../.deno/semver@6.3.1/node_modules/semver/bin/semver.js", but an entry pointing to "/Users/marvinh/dev/oss/preact/node_modules/.deno/semver@7.6.0/node_modules/semver/bin/semver.js" already exists. Skipping...
Warning Trying to set up 'js-yaml' bin for "../.deno/js-yaml@3.14.1/node_modules/js-yaml/bin/js-yaml.js", but an entry pointing to "/Users/marvinh/dev/oss/preact/node_modules/.deno/js-yaml@4.1.0/node_modules/js-yaml/bin/js-yaml.js" already exists. Skipping...
Warning Trying to set up 'nanoid' bin for "../.deno/nanoid@3.3.7/node_modules/nanoid/bin/nanoid.cjs", but an entry pointing to "/Users/marvinh/dev/oss/preact/node_modules/.deno/nanoid@3.1.20/node_modules/nanoid/bin/nanoid.cjs" already exists. Skipping...
Warning Trying to set up 'js-yaml' bin for "../.deno/js-yaml@3.14.1/node_modules/js-yaml/bin/js-yaml.js", but an entry pointing to "/Users/marvinh/dev/oss/preact/node_modules/.deno/js-yaml@4.0.0/node_modules/js-yaml/bin/js-yaml.js" already exists. Skipping...
Warning Trying to set up 'esbuild' bin for "../.deno/esbuild@0.14.54/node_modules/esbuild/bin/esbuild", but an entry pointing to "/Users/marvinh/dev/oss/preact/node_modules/.deno/esbuild@0.21.4/node_modules/esbuild/bin/esbuild" already exists. Skipping...
Warning Trying to set up 'semver' bin for "../.deno/semver@6.3.1/node_modules/semver/bin/semver.js", but an entry pointing to "/Users/marvinh/dev/oss/preact/node_modules/.deno/semver@7.6.2/node_modules/semver/bin/semver.js" already exists. Skipping...
```

Version: Deno 1.43.6

### PR DESCRIPTION
**Pull request by nathanwhit**
Fixes #24012.

In the case of multiple packages providing a binary with a same name, we were basically leaving the results undefined (since we set up things in parallel, and whichever got set up first won). In addition, we were warning about these cases, even though it's a situation that's expected to occur.

Instead, in the case of a collision in the binary names, we prefer the binary provided by the package with the least depth in the dependency tree.

While I was at it, I also took moved more code to `bin_entries.rs` since it was starting to get a bit cluttered.

### CODE REVIEW

**Review by marvinhagemeister — APPROVED** [review]
Tested and confirmed that warnings in the reproduction case aren't showing up anymore 👍

File: cli/npm/managed/resolvers/local/bin_entries.rs [hunk 1]
```diff
@@ -3,7 +3,201 @@
...
+          .map(Entry::Pkg),
+      );
+    }
+  }
+
+  bin_entries.sort_by(|(a, _), (b, _)| {
+    depths
+      .get(&a.id)
+      .unwrap_or_else(|| {
+        log::warn!("{} not found in dependency tree", a.id.nv);
```
Comment (dsherret) [inline cli/npm/managed/resolvers/local/bin_entries.rs:191]: We can probably just change this to a `debug_assert!`. It shouldn't ever happen.

File: cli/npm/managed/resolvers/local/bin_entries.rs [hunk 2]
```diff
@@ -3,7 +3,201 @@
...
+use std::collections::HashSet;
+use std::collections::VecDeque;
 use std::path::Path;
+use std::path::PathBuf;
+
+#[derive(Default)]
+pub(super) struct BinEntries {
+  /// Whether there's a collision in bin names
+  /// (i.e. two packages with the same bin name)
+  has_collision: bool,
```
Comment (dsherret) [inline cli/npm/managed/resolvers/local/bin_entries.rs:18]: Perhaps instead of a bool we should store a list of package names with collissions? That way we can search for only those packages in the graph and not all of them?

File: cli/npm/managed/resolvers/local/bin_entries.rs [hunk 3]
```diff
@@ -3,7 +3,201 @@
...
+    Pkg(&'a NpmPackageId),
+    IncreaseDepth,
+  }
+  let mut want = bin_entries
+    .iter()
+    .map(|(p, _)| p.id.clone())
+    .collect::<HashSet<_>>();
+  let mut seen = HashSet::new();
+  let mut depths: HashMap<NpmPackageId, u64> =
+    HashMap::with_capacity(want.len());
```
Comment (dsherret) [inline cli/npm/managed/resolvers/local/bin_entries.rs:149]: We can probably avoid cloning here and use a reference for `NpmPackageId` instead?

File: cli/npm/managed/resolvers/local/bin_entries.rs [hunk 4]
```diff
@@ -3,7 +3,201 @@
...
+        }
+        queue.push_back(Entry::IncreaseDepth);
+        continue;
+      }
+    };
+    if let Some(package) = snapshot.package_from_id(id) {
+      if want.remove(&package.id) {
+        depths.insert(package.id.clone(), current_depth);
+      }
+      seen.insert(package.id.clone());
```
Comment (dsherret) [inline cli/npm/managed/resolvers/local/bin_entries.rs:176]: I think we should change this (and above) to insert to `seen` when adding to the queue. Otherwise the same `id` could be added multiple times and we'd be doing more work.

```rs
for dep_id in package.dependencies.values() {
  if seen.insert(dep_id) {
    queue.push(Entry::Pkg(dep_id));
  }
}
```

(Also, we're unconditionally adding stuff to the queue on the next line even if the current dep might have been seen before)

File: cli/npm/managed/resolvers/local/bin_entries.rs [hunk 5]
```diff
@@ -68,6 +262,17 @@ fn symlink_bin_entry(
   let link = bin_node_modules_dir_path.join(bin_name);
   let original = package_path.join(bin_script);
 
+  if !original.exists() {
```
Comment (dsherret) [inline cli/npm/managed/resolvers/local/bin_entries.rs:265]: These checks take extra time. Is it worth doing? Maybe we should just set it up and if it errors then it errors?

By the way, I think maybe removing the next if statement and just setting it up each time might be faster than doing a read.

**Review by dsherret — APPROVED** [review]
LGTM

File: cli/npm/managed/resolvers/local/bin_entries.rs (hunk 5 above)
Comment (nathanwhit) [reply cli/npm/managed/resolvers/local/bin_entries.rs]: Makes sense, I moved these into the error handling instead of checking for ahead of time.
