### PR TITLE
fix(core): Make dynamic import async errors catchable

### LINKED ISSUE #6259: Errors in dynamic imports are not properly caught
Runtime
```
debian 10
deno 1.6.2
v8 8.8.278.2
typescript 4.1.3
```
------

```ts
//a.ts
import("./b.ts").catch(e=>{
  console.log("caught import b.ts error")
  console.error(e)
})

import("./c.ts").catch(e=>{
  console.log("caught import c.ts error")
  console.error(e)
})

setInterval(function () {
  import("./c.ts").catch((e) => {
    console.log("caught interval import c.ts error");
    console.error(e);
  });
}, 1e3);
```
```ts
//b.ts
// @ts-ignore
import "./b1.ts";
export default () => "error";
```
```ts
//c.ts
// @ts-ignore
await import("./c1.ts");
export default () => "error";
```

create those files and then run `deno run -A a.ts`, you will get log like below:
```
caught import b.ts error
TypeError: Cannot resolve module "file://yourdir/b1.ts" from "file://yourdir/b.ts".
    at file://yourdir/b.ts:3:0
caught import c.ts error
TypeError: Cannot resolve module "file://yourdir/c1.ts".
error: Uncaught TypeError: Cannot resolve module "file://yourdir/c1.ts".
```

`import('./c.ts')` first error is caught, but then second import is not caught and it make my program exit

### PR DESCRIPTION
**Pull request by nayeemrmn**
Fixes #6259.

### CODE REVIEW

File: core/runtime.rs [hunk 1]
```diff
@@ -104,6 +105,7 @@ pub(crate) struct JsRuntimeState {
   pub(crate) js_macrotask_cb: Option<v8::Global<v8::Function>>,
   pub(crate) pending_promise_exceptions:
     HashMap<v8::Global<v8::Promise>, v8::Global<v8::Value>>,
+  pub(crate) cancelled_promise_exceptions: HashSet<v8::Global<v8::Promise>>,
```
Comment (bartlomieju) [inline core/runtime.rs:108]: Please add a comment for these two fields describing distinction between them

File: cli/tests/delayed_error.ts [hunk 2]
```diff
@@ -0,0 +1,2 @@
+await new Promise((r) => setTimeout(r, 100));
```
Comment (bartlomieju) [inline cli/tests/delayed_error.ts:1]: Can this line be replaced with `await Promise.resolve();`? If so maybe you could rewrite it as a unit test in `core/runtime.rs`?

**Review by bartlomieju — COMMENTED** [review]
Great fix Nayeem!

File: cli/tests/delayed_error.ts (hunk 2 above)
Comment (nayeemrmn) [reply cli/tests/delayed_error.ts:1]: It must be delayed by a macrotask at least.

File: core/runtime.rs [hunk 3]
```diff
@@ -811,7 +816,10 @@ impl JsRuntime {
           .expect("Expected to get promise as module evaluation result");
         let promise_global = v8::Global::new(scope, promise);
         let mut state = state_rc.borrow_mut();
-        state.pending_promise_exceptions.remove(&promise_global);
+        let removed = state.pending_promise_exceptions.remove(&promise_global);
+        if removed.is_none() {
+          state.cancelled_promise_exceptions.insert(promise_global);
```
Comment (nayeemrmn) [inline core/runtime.rs:821]: Actually I think this is leaky, dynamic imports which don't eventually reject are also added to and never removed from this set. @bartlomieju Any ideas?

Comment (nayeemrmn) [reply core/runtime.rs:821]: Though it's not that big of a deal, as data associated with that module is also permanently kept in the module graph I think.

Comment (bartlomieju) [reply core/runtime.rs:821]: @nayeemrmn can you remove the promise handle from this hash map once dynamic import resolves?

Comment (nayeemrmn) [reply core/runtime.rs:821]: > @nayeemrmn can you remove the promise handle from this hash map once dynamic import resolves?

No, as far as the runtime infrastructure is concerned, the module is considered evaluated and done with once the pending promise is returned. Then it's just a promise in JS land. We pretty much need to do the equivalent of `.then()`ing it in rust land at this site.

Comment (bartlomieju) [reply core/runtime.rs:821]: > > @nayeemrmn can you remove the promise handle from this hash map once dynamic import resolves?
> 
> No, as far as the runtime infrastructure is concerned, the module is considered evaluated and done with once the pending promise is returned. Then it's just a promise in JS land. We pretty much need to do the equivalent of `.then()`ing it in rust land at this site.

Would https://docs.rs/rusty_v8/0.19.0/rusty_v8/struct.Promise.html#method.then work?

Comment (nayeemrmn) [reply core/runtime.rs]: Discussed on discord: https://discord.com/channels/684898665143206084/713035341736706089/810923927618060308.

**Comment by nayeemrmn** [comment]
@bartlomieju I've changed the approach to attach a JS object property to the promise to indicate that it shouldn't result in an exception.

**Comment by nayeemrmn** [comment]
Simplified further... we just had to add an empty `.catch()` handler to the promise 🤦‍♂️

**Review by kitsonk — APPROVED** [review]
LGTM

**Comment by ry** [comment]
Nice work @nayeemrmn - thanks!

**Comment by kitsonk** [comment]
Yes, meant to thank you in the approval.

File: core/runtime.rs [hunk 4]
```diff
@@ -822,6 +822,12 @@ impl JsRuntime {
...
           .expect("Expected to get promise as module evaluation result");
+        let empty_fn = |_scope: &mut v8::HandleScope,
+                        _args: v8::FunctionCallbackArguments,
+                        _rv: v8::ReturnValue| {};
+        let empty_fn = v8::FunctionTemplate::new(scope, empty_fn);
+        let empty_fn = empty_fn.get_function(scope).unwrap();
+        promise.catch(scope, empty_fn);
         let promise_global = v8::Global::new(scope, promise);
         let mut state = state_rc.borrow_mut();
         state.pending_promise_exceptions.remove(&promise_global);
```
Comment (bartlomieju) [inline core/runtime.rs:833]: Out of curiosity, does adding this handler still makes it so that promise ends up in `state.pending_promise_exceptions`? If not we could cut some complexity thanks to this fix

Comment (nayeemrmn) [reply core/runtime.rs:833]: It still gets put in there if there is an immediate rejection (the cases that worked correctly before this patch), the promise reject callback gets called before the handler is added. Actually... I think adding the handler here triggers https://github.com/denoland/deno/blob/555595e6d02d1fc1adb535df074d258389fab509/core/bindings.rs#L252-L254 so maybe the remove below is redundant. Will investigate.
