### PR TITLE
fix(cli): output file handling in deno upgrade

### LINKED ISSUE #18411: `deno upgrade` permission check should check cliOptionOutput
### Actual
```sh
$ deno upgrade --version 1.30.3 --output ./deno_1_30_3
error: You don't have write permission to /usr/bin/deno because it's owned by root.
Consider updating deno through your package manager if its installed from it.
Otherwise run `deno upgrade` as root.
```

Workaround
```shj
$ sudo deno upgrade --version 1.30.3 --output ./deno_1_30_3
Downloading https://github.com/denoland/deno/releases/download/v1.30.3/deno-x86_64-unknown-linux-gnu.zip
...
```

### Expected
deno upgrade should permission check `./deno_1_30_3` instead of `/usr/bin/deno`

### Related
https://github.com/denoland/deno/issues/18405
https://github.com/denoland/deno/issues/18406
https://github.com/denoland/deno/issues/18438
https://github.com/denoland/deno/issues/18440

### LINKED ISSUE #18466: `deno upgrade --output`: No such file or directory (os error 2)
deno 1.32.1+101abf3:
```
cd /tmp
mkdir foo
deno upgrade --version 1.11.5 --output foo/deno
error: No such file or directory (os error 2)
```

deno 1.32.1:
```
deno upgrade --version 1.11.5 --output foo/deno
Downloading https://github.com/denoland/deno/releases/download/v1.11.5/deno-x86_64-unknown-linux-gnu.zip
Deno is upgrading to version 1.11.5
Archive:  /tmp/.tmp2QmbJs/deno.zip
  inflating: deno                    
Upgraded successfully
Release notes: https://github.com/denoland/deno/releases/tag/v1.11.5
Blog post: https://deno.com/blog/v1.11
```
Issue seems to be that Deno is calling `std::fs::metadata` on the output exe instead of the current exe since https://github.com/denoland/deno/commit/0742ea1170239b7d010e219b3349b2f9edaaefe5, but that file has not been made yet at that point.

https://github.com/denoland/deno/blob/8c051dbd1a075ad3c228f78b29b13f0e455972a7/cli/tools/upgrade.rs#L270

### PR DESCRIPTION
**Pull request by solach**
Fixes #18411 without reopening #18466.
This reapplies commit 0742ea1 and then fixes #18466.
If the output file does not exist then it will have the permissions of the current running executable. I'm not sure if that is ideal or not.

### CODE REVIEW

File: cli/tools/upgrade.rs [hunk 1]
```diff
@@ -270,24 +270,32 @@ pub async fn upgrade(
...
+    if std::os::unix::fs::MetadataExt::uid(&metadata) == 0
+      && !nix::unistd::Uid::effective().is_root()
+    {
+      bail!(concat!(
+        "You don't have write permission to {} because it's owned by root.\n",
+        "Consider updating deno through your package manager if its installed from it.\n",
+        "Otherwise run `deno upgrade` as root.",
+      ), output_exe_path.display());
+    }
   }
```
Comment (dsherret) [inline cli/tools/upgrade.rs:299]:
```suggestion
  let permissions = if let Ok(metadata) = fs::metadata(output_exe_path) {
    let permissions = metadata.permissions();
    if permissions.readonly() {
      bail!(
        "You do not have write permission to {}",
        output_exe_path.display()
      );
    }
    #[cfg(unix)]
    if std::os::unix::fs::MetadataExt::uid(&metadata) == 0
      && !nix::unistd::Uid::effective().is_root()
    {
      bail!(concat!(
        "You don't have write permission to {} because it's owned by root.\n",
        "Consider updating deno through your package manager if its installed from it.\n",
        "Otherwise run `deno upgrade` as root.",
      ), output_exe_path.display());
    }
    permissions
  } else {
    fs::metadata(&current_exe_path)?.permissions()
  };
```

**Review by dsherret — APPROVED** [review]
LGTM. Thanks!

**Review by dsherret — COMMENTED** [review]
Oh wait, this seems slightly incorrect. I will push a change in order to get this PR merged because it's been a while.

**Review by dsherret — APPROVED** [review]
Oh no, it's correct. I just misread the code.
