### PR TITLE
fix: don't prompt when using `Deno.permissions.request` with `--no-prompt`

### LINKED ISSUE #14668: `Deno.permissions.request()` prompts even if `--no-prompt` set
Calling `Deno.permissions.request()` will prompt the user for the permission if not already granted even when `--no-prompt` or `NO_PROMPT` is set, which seems wrong.  In those cases, it should just deny un-granted permissions.

Ref: denoland/deno_emit#3 where deno_cache is using `Deno.permissions.request()` to ensure it has sufficient permissions to determine the `DENO_DIR`.

### PR DESCRIPTION
**Pull request by lowlighter**
Closes #14668

### CODE REVIEW

**Comment by bartlomieju** [comment]
Thanks for the PR, unfortunately I think this test is not correct - if you are in non-TTY environment (eg. in a CI) the prompting won't happen anyway. I believe we'll need to have this test use PTY - eg. check `permissions_cache()` test in `tests/integration/run_tests.rs`

**Comment by lowlighter** [comment]
I've updated the test to use a PTY environment like suggested

File: runtime/permissions/lib.rs [hunk 1]
```diff
@@ -3438,7 +3441,8 @@ mod tests {
   fn test_request() {
     set_prompter(Box::new(TestPrompter));
     let parser = TestPermissionDescriptorParser;
-    let mut perms: Permissions = Permissions::none_without_prompt();
```
Comment (lowlighter) [inline runtime/permissions/lib.rs:3441]: I've changed this to `none_with_prompt()` because it seemed like a mistake, since later in the test we manipulate the prompt value. I feel like this is why it has been overlooked in the first place, though I could be wrong

**Review by dsherret — APPROVED** [review]
LGTM. Thanks!
