### PR TITLE
Fix permission requirements for Deno.rename() and Deno.link()

### LINKED ISSUE #2736: Insufficient permission requirements for Deno.rename() and Deno.link()
`Deno.link()` should be as `Deno.copyFile()`, `Deno.rename()` as `Deno.copyFile()` + `Deno.remove()`.

### PR DESCRIPTION
**Pull request by nayeem-rahman**
Fixes #2736

### CODE REVIEW

File: js/link_test.ts [hunk 1]
```diff
@@ -63,7 +63,18 @@ testPerm({ read: true, write: true }, function linkSyncNotFound(): void {
   assertEquals(err.name, "NotFound");
 });
 
-test(function linkSyncPerm(): void {
+testPerm({ read: false, write: true }, function linkSyncReadPerm(): void {
```
Comment (bartlomieju) [inline js/link_test.ts]: Just to have full coverage, could you add test case with `{ read: true, write: false }`? That applies to `rename` tests as well

Comment (nayeem-rahman) [reply js/link_test.ts]: @bartlomieju It's at the bottom of this diff :) Unless you meant `{ read: false, write: false }`?

Comment (bartlomieju) [reply js/link_test.ts]: My bad! Then LGTM :+1:
