### PR TITLE
fix(compile): Support import maps

### LINKED ISSUE #13748: `deno compile` ignores ` --import-map` in 1.19.0
Using 1.18.2 I can run this:

```
deno compile -A --no-check --unstable --import-map ./modules.json --output test test.js
```

and it works.

In 1.19.0 the same thing doesn't work. Well, the compilation works, but running the executable will throw an error like this one, which is familiar to anyone who forgot using the `--import-map` flag once:

```
error: Relative import path "std/path" not prefixed with / or ./ or ../ from "file:///path/to/test.js"
```

This might be related to https://github.com/denoland/deno/pull/13563. Seems like import map support was forgotten in the change. Also, `deno bundle` seems unaffected by this, but it's obviously not the same feature.

### PR DESCRIPTION
**Pull request by littledivy**
Fixes #13748

### CODE REVIEW

**Review by bartlomieju — APPROVED** [review]
LGTM, good fix

File: cli/main.rs [hunk 1]
```diff
@@ -423,6 +425,8 @@ async fn compile_command(
     generic_error("There should only be one reference to ModuleGraph")
   })?;
 
+  graph.valid().unwrap();
```
Comment (lucacasonato) [inline cli/main.rs:428]: This should not be a panic…

Comment (bartlomieju) [reply cli/main.rs:428]: Yikes, good catch, you are right
