### PR TITLE
fix(cli/dts): add NotSupported error type

### LINKED ISSUE #10701: `Deno.errors.NotSupported` isn't in types
`Deno.errors.NotSupported` is defined here:
https://github.com/denoland/deno/blob/ef5e5f5e460b40b2c5f7cbcf0a1d11488fc7277f/runtime/js/01_errors.js#L131-L136
However, it isn't included the `.d.ts` files. I'm not sure what it's actually used for, but it seems like it should probably be included in the type definitions if it exists.

### PR DESCRIPTION
**Pull request by kt3k**
closes #10701 (again)

### CODE REVIEW

File: cli/tests/unit/error_test.ts [hunk 1]
```diff
@@ -0,0 +1,24 @@
...
+
+Deno.test("Errors work", () => {
+  assert(new Deno.errors.NotFound("msg") instanceof Error);
+  assert(new Deno.errors.PermissionDenied("msg") instanceof Error);
+  assert(new Deno.errors.ConnectionRefused("msg") instanceof Error);
+  assert(new Deno.errors.ConnectionReset("msg") instanceof Error);
+  assert(new Deno.errors.ConnectionAborted("msg") instanceof Error);
+  assert(new Deno.errors.NotConnected("msg") instanceof Error);
+  assert(new Deno.errors.AddrInUse("msg") instanceof Error);
+  assert(new Deno.errors.AddrNotAvailable("msg") instanceof Error);
```
Comment (bartlomieju) [inline cli/tests/unit/error_test.ts:12]: 👍

**Review by bartlomieju — APPROVED** [review]
