### PR TITLE
fix(cli): support data urls in preload by not splitting on comma.

### LINKED ISSUE #30543: preload flag errors on data url
Version: Deno 2.4.5

```
$ deno run --v8-flags=--single-threaded  --preload 'data:,console.log(1)' 'data:,console.log(2)'
error: Unable to decode data url.
    0: data url is missing comma delimiting attributes and body
```

This happens because of the `.use_value_delimiter(true)` on the `preload_arg()` introduced in #29626 which splits the data url in two at the comma.

Removing that line fixes the error however `preload_flags_test()` explicitly tests for supporting multiple files this way.

```
let flags = flags_from_vec(svec![
      "deno",
      "run",
      "--preload",
      "p1.js,./p2.js",
      "main.ts"
    ])
```

### PR DESCRIPTION
**Pull request by lrowe**
Specify multple files separately, `--preload p1.js --preload p2.js` instead of `--preload p1.js,p2.js`. Closes #30543.

### CODE REVIEW

File: cli/args/flags.rs [hunk 1]
```diff
@@ -12845,22 +12844,17 @@ Usage: deno repl [OPTIONS] [-- [ARGS]...]\n"
       }
     );
 
-    let flags = flags_from_vec(svec![
-      "deno",
-      "run",
-      "--preload",
-      "p1.js,./p2.js",
```
Comment (dsherret) [inline cli/args/flags.rs:12852]: Does it still work with multiple preload flags? Ex. `--preload p1.js --preload ./p2.js`?

Comment (lrowe) [reply cli/args/flags.rs:12852]: Yes, and there is an existing test for that directly underneath this one.

**Review by bartlomieju — APPROVED** [review]
