### PR TITLE
fix(ext/node): improve shelljs compat with managed npm execution

### LINKED ISSUE #22732: `npm:create-docusaurus` ReferenceError: require is not defined
```
$ deno run -A npm:create-docusaurus@latest my-website classic
[INFO] Creating new Docusaurus project...
[INFO] Installing dependencies with npm...
⚠️  The `--unstable` flag is deprecated and will be removed in Deno 2.0. Use granular `--unstable-*` flags instead.
Learn more at: https://docs.deno.com/runtime/manual/tools/unstable_flags
error: Uncaught (in promise) ReferenceError: require is not defined
if (require.main !== module) {
^
    at file:///home/divy/.cache/deno/npm/registry.npmjs.org/shelljs/0.8.5/src/exec-child.js:1:1
[ERROR] Dependency installation failed.
[INFO] The site directory has already been created, and you can retry by typing:

  `cd my-website`
  `npm install`
```

### LINKED ISSUE #24589: Docusaurus compatibility
Version: Deno 1.45.2

The first:

```console
❯ deno run -A npm:create-docusaurus@latest my-website classic --typescript
[INFO] Creating new Docusaurus project...
[INFO] Installing dependencies with npm...
error: Uncaught (in promise) ReferenceError: require is not defined
if (require.main !== module) {
^
    at file:///home/felipecrs/.cache/deno/npm/registry.npmjs.org/shelljs/0.8.5/src/exec-child.js:1:1
[ERROR] Dependency installation failed.
[INFO] The site directory has already been created, and you can retry by typing:

  `cd my-website`
  `npm install`
```

- Refs https://github.com/denoland/deno/issues/22732

But it's likely this one requires changes on Docusaurus level to support `--package-manager=deno`.

It can be bypassed with `--skip-install`, and then the command works.

```console
$ cd my-website
$ DENO_FUTURE=1 deno install --allow-scripts
```

Then:

```console  
$ deno task start
? [WARNING] Something is already running on port 3000. Probably:
  `/home/felipecrs/.deno/bin/deno run -A npm:@docusaurus/core@3.4.0/docusaurus start` (pid 1573) in "/tmp/tmp.cL5qkqnI8O/my-website"

Would you like to run the app on another port instead? › (Y/n)
```

This is a compatibility issue, because I never ran `deno task start` before. Even tried to reboot my machine and the issue persists.

But then, accepting a different port:

```
[SUCCESS] Docusaurus website is running at: http://localhost:60833/

● Client █████████████████████████ building (46%) 2/3 entries 741/816 dependencies 166/277 modules 86 active
 mdx-loader › docs/tutorial-extras/translate-your-site.md

[WARNING] The image at "/tmp/tmp.cL5qkqnI8O/my-website/blog/2021-08-26-welcome/docusaurus-plushie-banner.jpeg" can't be read correctly. Please ensure it's a valid image.
handle.stat is not a function
[WARNING] The image at "/tmp/tmp.cL5qkqnI8O/my-website/blog/2021-08-26-welcome/docusaurus-plushie-banner.jpeg" can't be read correctly. Please ensure it's a valid image.
handle.stat is not a function
[WARNING] The image at "/tmp/tmp.cL5qkqnI8O/my-website/docs/tutorial-extras/img/localeDropdown.png" can't be read correctly. Please ensure it's a valid image.
handle.stat is not a function
[WARNING] The image at "/tmp/tmp.cL5qkqnI8O/my-website/docs/tutorial-extras/img/docsVersionDropdown.png" can't be read correctly. Please ensure i
✖ Client
  Compiled with some errors in 7.87s

Error: Digest method not supported: md4
    at String.replace (<anonymous>)

--------------------------

Error: Digest method not supported: md4
    at String.replace (<anonymous>)

--------------------------

Error: Digest method not supported: md4
    at String.replace (<anonymous>)
client (webpack 5.93.0) compiled with 3 errors
```

Looks like one of these were already reported:

- Refs https://github.com/denoland/deno/issues/23301

But `Digest method not supported: md4` is new, I believe.

### PR DESCRIPTION
**Pull request by kt3k**
This PR improves the Node.js compatibility in managed npm resolution mode.

Currently when an npm script executes the script next to it (`child.js`), the package.json next to it is discovered as config file for it. As a result, Deno uses `$DENO_DIR/npm/registry.npmjs.org/<package>/<version>/node_modules` as root of npm modules. As a result, the script (`child.js`) is considered Deno script, not a npm script. That leads to the error `ReferenceError: require is not defined`.

This PR fixes it by disabling the discovery of `node_modules` when the main specifier is inside of `DENO_DIR`.

closes #22732
closes #24589

### CODE REVIEW

File: cli/factory.rs [hunk 1]
```diff
@@ -367,6 +367,19 @@ impl CliFactory {
...
+            .and_then(|node_modules| if let Ok(deno_dir) = self.deno_dir() {
+              if node_modules.starts_with(&deno_dir.root) {
+                // If the node_modules path is inside the deno_dir, we don't want to use it.
+                None
+              } else {
+                Some(node_modules.clone())
+              }
+            } else {
+              Some(node_modules.clone())
+            });
```
Comment (dsherret) [inline cli/factory.rs:381]: As discussed in person: instead of doing this here, let's move this up into the `resolve_node_modules_folder` function in cli/args/mod.rs (https://github.com/denoland/deno/blob/d1b2a9822d499def513c5b178927c4e05c39caff/cli/args/mod.rs#L1746)

This requires having access to the deno dir at this point though. I think we could:

1. Move the `DenoDirProvider` struct out of cli/factory.rs and instead create it within `CliOptions::new` and store it on `CliOptions`.
2. Expose `DenoDirProvider` on `CliOptions`.
3. Pass `DenoDirProvider` into the `resolve_node_modules_folder` function and then use it in that function.
4. Get and canonicalize the deno dir path inside `resolve_node_modules_folder` in order to compare it against the canonicalized node_modules dir path.

**Comment by kt3k** [comment]
> 1. Move the `DenoDirProvider` struct out of cli/factory.rs and instead create it within `CliOptions::new` and store it on `CliOptions`.
> 2. Expose `DenoDirProvider` on `CliOptions`.
> 3. Pass `DenoDirProvider` into the `resolve_node_modules_folder` function and then use it in that function.
> 4. Get and canonicalize the deno dir path inside `resolve_node_modules_folder` in order to compare it against the canonicalized node_modules dir path.

Addressed the above points.

Confirmed `deno run -A npm:create-docusaurus` now works with managed npm resolution.

```shellsession
$ ./target/debug/deno run -A npm:create-docusaurus
✔ What should we name this site? … website
✔ Select a template below... › classic (recommended)
✔ Which language do you want to use? › JavaScript
[INFO] Creating new Docusaurus project...
✔ Select a package manager... › npm
[INFO] Installing dependencies with npm...
npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported

added 1212 packages, and audited 1213 packages in 1m

298 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
[SUCCESS] Created website.
```

File: cli/args/mod.rs [hunk 2]
```diff
@@ -810,11 +812,14 @@ impl CliOptions {
 
     let maybe_lockfile = maybe_lockfile.filter(|_| !force_global_cache);
     let root_folder = start_dir.workspace.root_folder_configs();
+    let deno_dir_provider =
+      Arc::new(DenoDirProvider::new(flags.cache_path.clone()));
```
Comment (kt3k) [inline cli/args/mod.rs:816]: `deno_dir_provider` is not `Deferred` anymore. The `Deferred` defined in `cli/factory.rs` uses `once_cell::unsync::OnceCell` and not thread-safe, that is inconvenient for `CliOptions`. Should I create `once_cell::sync::OnceCell`-version of `Deferred` and wrap this `deno_dir_provider`? (That feels a bit overkill to me for now)

Comment (dsherret) [reply cli/args/mod.rs:816]: Nope. This is good. Thanks!

File: cli/args/mod.rs [hunk 3]
```diff
@@ -1776,7 +1784,18 @@ fn resolve_node_modules_folder(
   } else if let Some(state) = &*NPM_PROCESS_STATE {
     return Ok(state.local_node_modules_path.as_ref().map(PathBuf::from));
   } else if let Some(package_json_path) = maybe_package_json.map(|c| &c.path) {
-    // always auto-discover the local_node_modules_folder when a package.json exists
+    if let Ok(deno_dir) = deno_dir_provider.get_or_create() {
+      // `deno_dir.root` can be symlink in macOS
+      if let Ok(root) = canonicalize_path_maybe_not_exists(&deno_dir.root) {
```
Comment (dsherret) [inline cli/args/mod.rs:1789]: I wonder if we should surface these errors when they happen? I guess they'll be surfaced later anyway.

**Review by dsherret — APPROVED** [review]
Great. LGTM!
