### PR TITLE
fix(npm): panic resolving some dependencies with dist tags

### LINKED ISSUE #17275: Panicked when attempting to run storybook@next
With the news of Storybook 7 beta release, I thought I'd see if Deno could handle running it. TBH I wasn't expecting it to work, but I seem to have hit a bug in Deno in the process:

```
$ RUST_BACKTRACE=1 deno run --reload npm:storybook@next

============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: macos x86_64
Version: 1.29.1
Args: ["deno", "run", "--reload", "npm:storybook@next"]

thread 'main' panicked at 'programming error: cannot use matches with a tag: next', cli/npm/semver/mod.rs:199:37
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: <deno::npm::semver::NpmVersionReq as deno::npm::resolution::NpmVersionMatcher>::matches
   3: deno::npm::resolution::graph::GraphDependencyResolver<TNpmRegistryApi>::analyze_dependency
   4: deno::npm::resolution::NpmResolution::add_package_reqs_to_snapshot::{{closure}}
   5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   6: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   7: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   8: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   9: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  10: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  11: deno::tools::run::run_script::{{closure}}
  12: deno::run_subcommand::{{closure}}
  13: deno::main::{{closure}}
  14: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  15: deno_runtime::tokio_util::run_local
  16: deno::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

I get the same even if I use an explicit version rather than `next`:

```
$ RUST_BACKTRACE=1 deno run --reload npm:storybook@7.0.0-beta.19
```

### PR DESCRIPTION
**Pull request by dsherret**
This would only occur if a dist tag for a package was resolved more than once.

Closes #17275

### CODE REVIEW

File: cli/npm/resolution/graph.rs [hunk 1]
```diff
@@ -552,18 +551,15 @@ impl<'a, TNpmRegistryApi: NpmRegistryApi>
...
-    let version_and_info = self.resolve_best_package_version_and_info(
-      name,
-      version_matcher,
-      package_info,
-    )?;
+    let version_and_info = self
+      .resolve_best_package_version_and_info(version_matcher, package_info)?;
     let id = NpmPackageId {
-      name: name.to_string(),
+      name: package_info.name.to_string(),
```
Comment (dsherret) [inline cli/npm/resolution/graph.rs:562]: I think this was also incorrect. The package id name should be the resolved name and not the key in the npm package dependency entry.

**Review by bartlomieju — APPROVED** [review]
LGTM, no comments
