### PR TITLE
fix(runtime/readFile*): close resources on error during read

### LINKED ISSUE #10043: Resource leak after calling Deno.readFileSync on directory
After calling Deno.readFileSync on a directory, a file handle stays open after the "Is a directory" error is thrown.

For example, take this test:

```ts
import { assertThrows } from "https://deno.land/std@0.92.0/testing/asserts.ts";

Deno.test("readFileSync on dir", async () => {
  assertThrows(() => (
    Deno.readFileSync('/home/paulo/misc/temp_dir')
  ), Error, "Is a directory");
});
```

After running it, an AssertionError is raised, because the handle is still open:

```
AssertionError: Test case is leaking resources.
Before: {
  "0": "stdin",
  "1": "stdout",
  "2": "stderr"
}
After: {
  "0": "stdin",
  "1": "stdout",
  "2": "stderr",
  "3": "fsFile"
}

Make sure to close all open resource handles returned from Deno APIs before
finishing test case.
    at assert (deno:runtime/js/06_util.js:33:13)
    at resourceSanitizer (deno:runtime/js/40_testing.js:84:7)
    at async Object.exitSanitizer [as fn] (deno:runtime/js/40_testing.js:100:9)
    at async TestRunner.[Symbol.asyncIterator] (deno:runtime/js/40_testing.js:272:13)
    at async Object.runTests (deno:runtime/js/40_testing.js:347:22)
    at async file:///home/paulo/misc/test_readfilesync/$deno$test.ts:3:1
```

Why does this happen?

### PR DESCRIPTION
**Pull request by satyarohith**
Closes #10043

### CODE REVIEW

File: runtime/js/40_read_file.js [hunk 1]
```diff
@@ -7,32 +7,52 @@
 
   function readFileSync(path) {
     const file = openSync(path);
-    const contents = readAllSync(file);
-    file.close();
-    return contents;
+    try {
+      const contents = readAllSync(file);
+      file.close();
```
Comment (lucacasonato) [inline runtime/js/40_read_file.js:12]: Do the `file.close` in a `finally` block.

**Review by bartlomieju — APPROVED** [review]
LGTM, thanks
