### PR TITLE
chore(tests): fix flaky fetchPostBodyTypedArray

### LINKED ISSUE #12101: fetchPostBodyTypedArray is flaky
```
error: Test failed
failures:

fetchPostBodyTypedArray
AssertionError: Values are not equal:


    [Diff] Actual / Expected


+   POST /blah HTTP/1.1
+   hello: World
+   foo: Bar
+   accept: */*
+   user-agent: Deno/1.14.0
+   accept-encoding: gzip, br
+   host: 127.0.0.1:4503
+   content-length: 11
+   
+   helloworld
-   


    at assertEquals (file:///Users/runner/work/deno/deno/test_util/std/testing/asserts.ts:271:9)
    at fetchPostBodyTypedArray (file:///Users/runner/work/deno/deno/cli/tests/unit/fetch_test.ts:743:5)
    at async asyncOpSanitizer (deno:runtime/js/40_testing.js:35:9)
    at async resourceSanitizer (deno:runtime/js/40_testing.js:72:7)
    at async exitSanitizer (deno:runtime/js/40_testing.js:99:9)
    at async applyPermissions (deno:runtime/js/40_testing.js:124:9)
    at async runTest (deno:runtime/js/40_testing.js:215:7)
    at async Object.runTests (deno:runtime/js/40_testing.js:299:22)

failures:

	fetchPostBodyTypedArray
```

Ref #1219

### PR DESCRIPTION
**Pull request by dsherret**
Closes #12101.

### CODE REVIEW

File: cli/tests/unit/fetch_test.ts [hunk 1]
```diff
@@ -634,8 +615,8 @@ function bufferServer(addr: string): Buffer {
     await Promise.all([p1, p2]);
     conn.close();
     listener.close();
+    return buf;
   });
-  return buf;
```
Comment (dsherret) [inline cli/tests/unit/fetch_test.ts:638]: I'm a little confused... is there a reason why this wasn't done before and the code was this way?

I think previously the `conn.write` could complete before the `buf.readFrom` causing the tests to read from the buffer and it being empty.

Comment (bartlomieju) [reply cli/tests/unit/fetch_test.ts:638]: I believe it was just a mistake in code and your version if the proper one

**Review by bartlomieju — APPROVED** [review]
