### PR TITLE
fix: update glob implementation to match with latest node

### LINKED ISSUE #31625: node:fs glob() fails with error; works correctly on nodejs
Version: Deno 2.6.0

`foo.ts`
```typescript
import * as fs from 'node:fs/promises';

for await(const item of fs.glob('**/foo', {cwd: '/'})) {
    console.dir(item);
}
```

```shell
$ deno -A ./foo.ts 
error: Uncaught (in promise) TypeError: Cannot read properties of null (reading 'length')
for await(const item of fs.glob('**/foo', {cwd: '/'})) {
                ^
    at Glob.#iterateSubpatterns (ext:deno_node/_fs/_fs_glob.ts:580:33)
    at eventLoopTick (ext:core/01_core.js:179:7)
    at async Glob.glob (ext:deno_node/_fs/_fs_glob.ts:494:9)
$ node ./foo.ts
// works correctly; logs glob matches
```

### PR DESCRIPTION
**Pull request by crowlKats**
Fixes #31625

### CODE REVIEW

File: ext/node/polyfills/_fs/_fs_glob.ts [hunk 1]
```diff
@@ -205,7 +205,7 @@ class Cache {
     const promise = PromisePrototypeThen(
       readdir(path, { __proto__: null, withFileTypes: true }),
       null,
-      () => null,
+      () => [],
```
Comment (crowlKats) [inline ext/node/polyfills/_fs/_fs_glob.ts:208]: for reference, this line is the actual fix for the linked issue

**Review by bartlomieju — APPROVED** [review]
