### PR TITLE
fix: URL constructor throws confusing error on invalid scheme

### LINKED ISSUE #5056: URL constructor throws confusing error on invalid scheme
Currently, URL constructor throws confusing error when the scheme part is invalid. See repros in REPL.

# Current behaviour

deno --version 0.42

```
> new URL("invalid_scheme://foo")
error: Uncaught TypeError: Cannot destructure property 'port' of '(intermediate value)(intermediate value)(intermediate value)' as it is undefined.
    at new URLImpl ($deno$/web/url.ts:373:13)
    at <unknown>:1:1
    at evaluate ($deno$/repl.ts:64:34)
    at Object.replLoop ($deno$/repl.ts:153:13)
```

# Expected behaviour

```
> new URL("invalid_scheme://foo")
error: Uncaught TypeError: Invalid URL.
    at new URLImpl ($deno$/web/url.ts:392:13)
    at <unknown>:1:1
    at evaluate ($deno$/repl.ts:64:34)
    at Object.replLoop ($deno$/repl.ts:153:13)
```

# Other platforms

node --version v12.16.1

```
> new URL("invalid_scheme://foo")
Uncaught TypeError [ERR_INVALID_URL]: Invalid URL: invalid_scheme://foo
    at onParseError (internal/url.js:257:9)
    at new URL (internal/url.js:333:5)
    at repl:1:1
    at Script.runInThisContext (vm.js:120:20)
    at REPLServer.defaultEval (repl.js:430:29)
    at bound (domain.js:426:14)
    at REPLServer.runBound [as eval] (domain.js:439:12)
    at REPLServer.onLine (repl.js:758:10)
    at REPLServer.emit (events.js:323:22)
    at REPLServer.EventEmitter.emit (domain.js:482:12) {
  input: 'invalid_scheme://foo',
  code: 'ERR_INVALID_URL'
}
```

google-chrome

image

### PR DESCRIPTION
**Pull request by lenkan**
Fixes #5056

### CODE REVIEW

File: cli/js/web/url.ts [hunk 1]
```diff
@@ -389,7 +389,7 @@ export class URLImpl implements URL {
         hash: urlParts.hash,
       });
     } else {
-      throw new TypeError("URL requires a base URL.");
+      throw new TypeError("Invalid URL.");
```
Comment (lenkan) [inline cli/js/web/url.ts:392]: Not sure about changing this one, but I thought this was more inline with other implementations.
