### PR TITLE
fix(check): support "moduleResolution": "bundler" in compiler options

### LINKED ISSUE #25359: Next.js components from `"next"` package are not importing types properly
I was excited to try out deno on Next.JS after hearing about it on the syntax podcast. It runs well but unfortunately I'm getting a couple of type errors when importing the next core components like `next/link` and `next/image`.

This only happens in the editor with the LSP so it might not be the right place to post it so let me know.

For good measure in the project that I found it in I tried copy and pasting the compiler options into `deno.json`. It had no effect.

> JSX element type 'Link' does not have any construct or call signatures.deno-ts(2604)
> 'Link' cannot be used as a JSX component.
  Its type 'typeof import("file:///Users/richardvanbergen/code/deno-nextjs-bug-example/node_modules/.deno/next@14.2.7/node_modules/next/link")' is not a valid JSX element type.deno-ts(2786)

> JSX element type 'Image' does not have any construct or call signatures.deno-ts(2604)
'Image' cannot be used as a JSX component.
>  Its type 'typeof import("file:///Users/richardvanbergen/code/deno-nextjs-bug-example/node_modules/.deno/next@14.2.7/node_modules/next/image")' is not a valid JSX element type.deno-ts(2786)

Reproduction Steps:

1. Download the repo from the link below
2. Enable Deno from the menu command bar `Deno: Enable`
3. Ensure Deno Future is checked in the user settings
4. Just for good measure, add `DENO_FUTURE=1` explicitly in the settings.
5. Navigate to `src/app/page.tsx`.
6. Behold! Errors!

Version: Deno 1.46.2
Reproduction repo: [https://github.com/richardvanbergen/deno-nextjs-bug-example](https://github.com/richardvanbergen/deno-nextjs-bug-example)

Side note: I can deal with it but is there a way to enable wildcard import aliases?
Side side note: There's also an error importing the styles I personally don't care about that but if it's easy to answer then it might be worth documenting it.

### LINKED ISSUE #28599: SvelteKit and generated types
Version: Deno 2.2.5

Hello,

When installing Svelte from the CLI (`npx sv create`) and then updating the code to add a `+page.ts` to fetch data, the `import type { PageLoad } from "./$types";` returns this error:

```
Unable to load a local module: file:///Users/naelshiab/Desktop/svelte/src/routes/$types
Please check the file path.deno(no-local)
Resolved Dependency

Types: file​:///Users/naelshiab/Desktop/svelte/src/routes/$types
```

These types are generated, but it looks like Deno is not able to find them.

A screenshot below shows you the problem. The only thing I did was to add a data file in `static` and create a `+pages.ts` to fetch it.

Image

Thank you! 🙏

### LINKED ISSUE #29673: Support `"moduleResolution": "bundler"` for type checking and bundling
As title. It would only use this for type checking and bundling. Otherwise it defaults to regular NodeNext resolution.

### PR DESCRIPTION
**Pull request by nayeemrmn**
- Continuing #30048
- Closes #29673
- Closes #28599
- Closes #25359

### CODE REVIEW

File: libs/resolver/workspace.rs [hunk 1]
```diff
@@ -378,27 +379,44 @@ impl SloppyImportsResolutionReason {
 
 #[derive(Debug)]
 struct SloppyImportsResolver<TSys: FsMetadata> {
+  compiler_options_resolver: RwLock<CompilerOptionsResolverRc>,
```
Comment (dsherret) [inline libs/resolver/workspace.rs]: Is there a way we could put this in something like a `CompilerOptionsResolverCell` and have that passed in as a ctor parameter then share that with the factory? That way we can always ensure the two are always in sync and then we don't need an explicit `set_compiler_options_resolver` method here.

File: libs/resolver/workspace.rs [hunk 2]
```diff
@@ -942,8 +970,12 @@ impl<TSys: FsMetadata + FsRead> WorkspaceResolver<TSys> {
       })
       .collect::<BTreeMap<_, _>>();
     let fs = CachedMetadataFs::new(sys, fs_cache_options);
-    let sloppy_imports_resolver =
-      new_rc(SloppyImportsResolver::new(fs, sloppy_imports_options));
+    let compiler_options_resolver = CompilerOptionsResolverCell::default();
```
Comment (dsherret) [inline libs/resolver/workspace.rs]: Nitpick: maybe `CompilerOptionsResolverCellRc` for clarity that it's in an arc/rc
