### PR TITLE
fix(ext/node): Match punycode module behavior to node

### LINKED ISSUE #19214: `个��.hk` throws error at Object.toASCII (ext:deno_node/punycode.ts:5:16)
Following https://github.com/denoland/deno/issues/19113

Usage example still fails but now with a new error:

```
ERROR CheerioCrawler: Request failed and reached maximum retries. Error: Errors { invalid_mapping, disallowed_character }
    at Object.toASCII (ext:deno_node/punycode.ts:5:16)
    at file:///home/username/.cache/deno/npm/registry.npmjs.org/psl/1.9.0/index.js:47:34
    at Array.reduce (<anonymous>)
    at Object.internals.findRule (file:///home/username/.cache/deno/npm/registry.npmjs.org/psl/1.9.0/index.js:41:26)
    at Object.exports.parse (file:///home/username/.cache/deno/npm/registry.npmjs.org/psl/1.9.0/index.js:201:24)
    at Object.exports.get (file:///home/username/.cache/deno/npm/registry.npmjs.org/psl/1.9.0/index.js:261:18)
    at Object.getPublicSuffix (file:///home/username/.cache/deno/npm/registry.npmjs.org/tough-cookie/4.1.2/lib/pubsuffix-psl.js:70:14)
    at permuteDomain (file:///home/username/.cache/deno/npm/registry.npmjs.org/tough-cookie/4.1.2/lib/permuteDomain.js:38:28)
    at MemoryCookieStore.findCookies (file:///home/username/.cache/deno/npm/registry.npmjs.org/tough-cookie/4.1.2/lib/memstore.js:99:21)
    at MemoryCookieStore.findCookies (file:///home/username/.cache/deno/npm/registry.npmjs.org/universalify/0.2.0/index.js:5:67)
```

Code where it fails: https://github.com/lupomontero/psl/blob/main/index.js#L44

I've tracked it down to the `个��.hk` string that is passed.

Surprisingly, following works:

```ts
import * as mod from "npm:punycode";
console.log(mod.default.toASCII('个��.hk'));
```

Deno version is built from source from this commit: https://github.com/denoland/deno/commit/40bda07ff5751cbb2665a2d134f64826fe3790a8

### PR DESCRIPTION
**Pull request by nathanwhit**
Fixes #19214.

We were using the `idna` crate to implement our polyfill for `punycode.toASCII` and `punycode.toUnicode`. The `idna` crate is correct, and adheres to the IDNA2003/2008 spec, but it turns out `node`'s implementations don't really follow any spec! Instead, node splits the domain by `'.'` and punycode encodes/decodes each part. This means that node's implementations will happily work on codepoints that are disallowed by the IDNA specs, causing the error in #19214.

While fixing this, I went ahead and matched the node behavior on all of the punycode functions and enabled node's punycode test in our `node_compat` suite.

### CODE REVIEW

File: ext/node/polyfills/punycode.ts [hunk 1]
```diff
@@ -7,22 +7,33 @@ import {
...
+    fn,
+    "The `punycode` module is deprecated. Please use a userland " +
+      "alternative instead.",
+    "DEP0040",
+  );
+}
+
 function toASCII(domain) {
-  return op_node_idna_domain_to_ascii(domain);
+  return punyDeprecated(op_node_idna_domain_to_ascii)(domain);
```
Comment (nathanwhit) [inline ext/node/polyfills/punycode.ts:24]: Wrapping each function feels kinda gross, open to suggestions

Comment (bartlomieju) [reply ext/node/polyfills/punycode.ts:25]: That seems reasonable 👍

**Review by bartlomieju — APPROVED** [review]
LGTM, nice fix!
