### PR TITLE
fix(check): remove instability in loading lib files

### LINKED ISSUE #28201: `deno check` occasionally fails on `fetch` signature with no http client
Version: Deno 2.2.0

This is a regression in 2.2.0, where `deno check` checks against the `fetch` in `lib.deno.shared_globals.d.ts` instead of `lib.deno.fetch.d.ts`. I suspect a broken cache causing this because it does not always happen.

The most minimal repro case I could produce:

```ts
// bug.ts
import { stub } from "jsr:@std/testing@1.0.9/mock";
const stubbed = stub(globalThis, "fetch");
await stubbed.original.call(globalThis, "https://www.example.com", {});
```

```sh
> deno check -r bug.ts
Check file:///Users/tugrul/Code/bug-deno-fetch-check-signature/bug.ts
TS2345 [ERROR]: Argument of type '{}' is not assignable to parameter of type 'RequestInit & { client: HttpClient; }'.
  Property 'client' is missing in type '{}' but required in type '{ client: HttpClient; }'.
await stubbed.original.call(globalThis, "https://www.example.com", {});
                                                                   ~~
    at file:///Users/tugrul/Code/bug-deno-fetch-check-signature/bug.ts:4:68

    'client' is declared here.
      init?: RequestInit & { client: Deno.HttpClient },
                             ~~~~~~
        at asset:///lib.deno.shared_globals.d.ts:754:26

error: Type checking failed.
```

I was able to find the culprit commit as well (#28056).

```
2.2.0,                                     # fail
33bccf9090e8764790be84e56fe0988600ffe31a,  # fail: perf(check): use v8 code cache for extension sources in deno check (#28089)
a2afae46b616e9ca087ce09539a56c2fc159f49d,  # fail
23540c2825ddf838444279a394909d0888bd3dcb,  # fail: refactor: remove tsc snapshot (#28056)
07410d19cf30d102f7aa1874c4f716934d0d0137,  # pass
b9183c737ffe727b24c141bb0ffb13df39ed126b,  # pass
a5a1cce50d7c48a373ac2381b309e253601a2321,  # pass: feat(ext/cache): support lscache (#27628)
2.1.10                                     # pass
```

You can find the repro code, and bisecting results [here](https://github.com/tugrulates/deno-bug-28201/actions/runs/13436815644).

### PR DESCRIPTION
**Pull request by dsherret**
Also reduces memory usage.

Closes #28201

### CODE REVIEW

File: cli/lsp/tsc.rs [hunk 1]
```diff
@@ -5074,10 +5074,10 @@ deno_core::extension!(deno_tsc,
...
     use deno_core::ExtensionFileSource;
-    ext.esm_files.to_mut().push(ExtensionFileSource::new_computed("ext:deno_tsc/99_main_compiler.js", crate::tsc::MAIN_COMPILER_SOURCE.get().into()));
-    ext.esm_files.to_mut().push(ExtensionFileSource::new_computed("ext:deno_tsc/97_ts_host.js", crate::tsc::TS_HOST_SOURCE.get().into()));
-    ext.esm_files.to_mut().push(ExtensionFileSource::new_computed("ext:deno_tsc/98_lsp.js", crate::tsc::LSP_SOURCE.get().into()));
-    ext.js_files.to_mut().push(ExtensionFileSource::new_computed("ext:deno_cli_tsc/00_typescript.js", crate::tsc::TYPESCRIPT_SOURCE.get().into()));
+    ext.esm_files.to_mut().push(ExtensionFileSource::new_computed("ext:deno_tsc/99_main_compiler.js", crate::tsc::MAIN_COMPILER_SOURCE.as_str().into()));
+    ext.esm_files.to_mut().push(ExtensionFileSource::new_computed("ext:deno_tsc/97_ts_host.js", crate::tsc::TS_HOST_SOURCE.as_str().into()));
+    ext.esm_files.to_mut().push(ExtensionFileSource::new_computed("ext:deno_tsc/98_lsp.js", crate::tsc::LSP_SOURCE.as_str().into()));
+    ext.js_files.to_mut().push(ExtensionFileSource::new_computed("ext:deno_cli_tsc/00_typescript.js", crate::tsc::TYPESCRIPT_SOURCE.as_str().into()));
```
Comment (dsherret) [inline cli/lsp/tsc.rs:5080]: I think there's cloning that shouldn't be done because we have a static string here.

File: cli/tsc/mod.rs [hunk 2]
```diff
@@ -156,88 +142,30 @@ pub enum StaticAssetSource {
...
-  }
 }
 
 /// Contains static assets that are not preloaded in the compiler snapshot.
 ///
 /// We lazily load these because putting them in the compiler snapshot will
 /// increase memory usage when not used (last time checked by about 0.5MB).
 pub static LAZILY_LOADED_STATIC_ASSETS: Lazy<
-  HashMap<&'static str, StaticAssetSource>,
+  IndexMap<&'static str, StaticAssetSource>,
```
Comment (dsherret) [inline cli/tsc/mod.rs:166]: Main bug fix is here.

**Review by nathanwhit — APPROVED** [review]
Nice, LGTM!

**Review by bartlomieju — APPROVED** [review]
LGTM too
