### PR TITLE
errors: add fsEvent notify::Error casts

### LINKED ISSUE #4485: Panick on fsEvents where path doesn't exist
Given the following code:
```
const iter = Deno.fsEvents("non-existant.file");
```
The code aborts with the following error:
```
thread 'main' panicked at 'Can't downcast ErrBox(Error { kind: Io(Os { code: 2, kind: NotFound, message: "No such file or directory" }), paths: [] }) to OpError', cli/op_error.rs:389:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: failed to initiate panic, error 5
Aborted
```
This is on:
```
deno 0.37.1
v8 8.2.308
typescript 3.8.3
```

### PR DESCRIPTION
**Pull request by kevinkassimo**
Closes #4485

Add cast code. Add a basic error test.

### CODE REVIEW

File: cli/js/tests/fs_events_test.ts [hunk 1]
```diff
@@ -14,6 +14,26 @@ unitTest({ perms: { read: false } }, function fsEventsPermissions() {
...
+  let thrown = false;
+  try {
+    Deno.fsEvents("non-existant.file");
+  } catch (err) {
+    console.error(err);
+    if (Deno.build.os === "win") {
+      assert(
+        err.message.includes(
+          "Input watch path is neither a file nor a directory"
+        )
```
Comment (ry) [inline cli/js/tests/fs_events_test.ts]: odd
