### PR TITLE
fix(ext/kv): throw on the Kv constructor

### LINKED ISSUE #18963: Usability Kv class
Consider making the constructor of `Deno.Kv` private or throw.  For those coming to the API, a user needs to leverage `Deno.openKv()` instead of `new Deno.Kv()` and there is no use case where constructing an instance makes any sense.

If you do a `new Deno.Kv()` the user will get a cryptic error when trying to access values:

```
error: Uncaught BadResource: Bad resource ID
for await (let item of list) {
               ^
    at KvListIterator.<anonymous> (ext:deno_kv/01_db.ts:107:42)
    at KvListIterator.next (ext:deno_kv/01_db.ts:383:48)
```

### PR DESCRIPTION
**Pull request by lucacasonato**
Closes #18963

### CODE REVIEW

**Review by ry — APPROVED** [review]

File: ext/kv/01_db.ts [hunk 1]
```diff
@@ -43,10 +43,17 @@ type RawValue = {
...
 };
 
+const kvSymbol = Symbol("KvRid");
+
 class Kv {
   #rid: number;
 
-  constructor(rid: number) {
+  constructor(rid: number = undefined, symbol: symbol = undefined) {
+    if (kvSymbol === symbol) {
```
Comment (bartlomieju) [inline ext/kv/01_db.ts:52]:
```suggestion
    if (kvSymbol !== symbol) {
```
