### PR TITLE
fix(runtime): return number from `op_ppid` instead of bigint

### LINKED ISSUE #22166: `Deno.ppid` returns bigint, although type declarations says it's number
## Summary

`Deno.ppid` is supposed to have type of `number` (according to https://deno.land/api@v1.40.2?s=Deno.ppid), but what we get actually is `bigint`.

## What happens now

Version: Deno 1.40.2

```console
$ deno eval "console.log(typeof Deno.ppid, Deno.ppid)"
bigint 89489n

$ deno --version
deno 1.40.2 (release, aarch64-apple-darwin)
v8 12.1.285.6
typescript 5.3.3
```

## Expected result

`typeof Deno.ppid === "number"`

## Additional note

- `Deno.pid` (not ppid) is of type `number` as expected.
- `Deno.ppid` is of type `number` if we run it in Deno Deploy.

### PR DESCRIPTION
**Pull request by magurotuna**
Fixes #22166

### CODE REVIEW

File: runtime/ops/runtime.rs [hunk 1]
```diff
@@ -32,8 +32,8 @@ fn op_main_module(state: &mut OpState) -> Result<String, AnyError> {
 /// This is an op instead of being done at initialization time because
 /// it's expensive to retrieve the ppid on Windows.
 #[op2(fast)]
-#[bigint]
```
Comment (mmastrac) [inline runtime/ops/runtime.rs:35]: You can use `#[number]` here to force it to return an integer-like number up to `MAX_SAFE_INTEGER`

**Review by mmastrac — APPROVED** [review]
LGTM!
