### PR TITLE
fix(runtime/windows): fix calculation of console size

### LINKED ISSUE #23872: 🐛(WinOS) `Deno.consoleSize()` incorrectly returns console buffer size
for *all versions* of `deno` since at least 1.21.0

`Deno.consoleSize()` is incorrectly returning the console *buffer size* instead of the console *window size*. This can be seen when using the usual console window (not 'Windows Terminal').

Screenshot 2024-05-17 135307

I hadn't noticed this issue earlier because I primarily use 'Windows Terminal' which maintains its own scrollback buffer and allocates a console screen buffer which is the *same size* as the console view window. Additionally, most allocated consoles only reserve extra lines for the screen buffer, not extra columns. And most uses only care about the column width of the screen. As a result, `Deno.consoleSize()` has been accidentally correct for the majority of users and cases, likely since inception (#6520).

The error is in *runtime/ops/tty/rs*:

https://github.com/denoland/deno/blob/d64921c1906ee1ac39230c16abe9ff8c546bd645/runtime/ops/tty.rs#L273-L276

It's an easy fix. I'll post a PR for the fix in a few minutes.

### PR DESCRIPTION
**Pull request by rivy**
Fixes #23872.

### CODE REVIEW

**Comment by rivy** [comment]
I haven't implemented an underflow check for the subtractions, but I can if requested.

**Comment by rivy** [comment]
I read the docs a bit closer and decided that over/under-flow protection was warranted given the vagueness.
Return will be either correct, or, if bad values are received, `{ columns: 0, rows: 0 }`.

File: runtime/ops/tty.rs [hunk 1]
```diff
@@ -270,10 +270,20 @@ fn console_size_from_fd(
...
-    Ok(ConsoleSize {
-      cols: bufinfo.dwSize.X as u32,
-      rows: bufinfo.dwSize.Y as u32,
-    })
+
+    // calculate the size of the visible window
+    // * use over/under-flow protections b/c MSDN docs only imply that srWindow components are all non-negative
+    // * ref: <https://docs.microsoft.com/en-us/windows/console/console-screen-buffer-info-str> @@ <https://archive.is/sfjnm>
+    let cols = std::cmp::max(
+      bufinfo.srWindow.Right as i32 - bufinfo.srWindow.Left as i32 + 1,
```
Comment (littledivy) [inline runtime/ops/tty.rs:278]: We can copy libuv here. width can be `dwSize.X`

https://github.com/libuv/libuv/blob/d2d92b74a8327daf9652a9732454937f3529bd30/src/win/tty.c#L175-L176

Comment (rivy) [reply runtime/ops/tty.rs:278]: I don't see any explanation in `libuv` for using the screen buffer width instead of the calculation from the console window view, so I'm not sure why they are using that assignment instead of doing the simple calculation.

I haven't seen any examples, but I don't know of any reason that the screen buffer width and the console window view width would always have to be equal. So, using `dwSize.X` seems to be falling into a future error similar to the height calculation that this PR fixes.

**Review by littledivy — APPROVED** [review]

**Comment by bartlomieju** [comment]
@littledivy can you, please, shepherd this PR to landing?

**Comment by dsherret** [comment]
@rivy can you rebase this PR onto main? Also, please allow maintainers the ability to push to your branches in the future. I went through and fixed this PR myself and then wasn't able to push.

**Comment by rivy** [comment]
> @rivy can you rebase this PR onto main? Also, please allow maintainers the ability to push to your branches in the future. I went through and fixed this PR myself and then wasn't able to push.

Happy to rebase.

I didn't specifically disallow maintainer edits; I just opened a quick PR.
But I also don't now see the "Allow edits from maintainers" checkbox to enable access.
I'm not sure why it's not there... some permission issue? on my fork? Any idea?

**Comment by rivy** [comment]
@dsherret 

> Also, please allow maintainers the ability to push to your branches in the future. I went through and fixed this PR myself and then wasn't able to push.

I did some quick research, and the permission problem might be related to my fork being "organization owned". I segregate forks which I don't "own" but commit to into a "rivy-fix" organization. There's some discussion about this as a problem in the community discussions (see <https://github.com/orgs/community/discussions/5634>).
