### PR TITLE
fix(task): output encoding issues on windows

### LINKED ISSUE #16792: Emojis on Windows not displayed correctly in deno task `echo`
I'm having some issues on Windows (powershell). Let's see the following tasks:

```json
{
  "tasks": {
    "eval": "deno eval \"console.log('🔥');\"",
    "echo": "deno echo \"🔥\"",
    "run-pipeline": "echo \"console.log('🔥');\" | deno run -",
    "run-pipeline-2": "echo import \"./fire.ts\" | deno run -",
    "run": "deno run ./fire.ts",
  }
}
```

some of them run this script:

```ts
// fire.ts
console.log("🔥");
```

```sh
deno task eval
>🔥
deno task echo
>ƒöÑ
deno task run-pipeline
>ƒöÑ
deno task run-pipeline-2
>ƒöÑ
deno task run
>🔥
```

It seems that the `echo` implementation in deno has issues with emojis because all task containing a echo don't display the emojis.

### PR DESCRIPTION
**Pull request by dsherret**
Closes #16792

### CODE REVIEW

File: cli/tests/integration/task_tests.rs [hunk 1]
```diff
@@ -50,6 +50,14 @@ itest!(task_non_existent {
   exit_code: 1,
 });
 
+#[test]
+fn task_emoji() {
+  // this bug only appears when using a pty/tty
+  let args = "task --config task/deno.json echo_emoji";
+  use test_util::PtyData::*;
+  test_util::test_pty2(args, vec![Output("Task echo_emoji echo 🔥\r\n🔥")]);
```
Comment (dsherret) [inline cli/tests/integration/task_tests.rs:58]: Confirmed this fails in deno_task_shell 0.7.2

**Review by bartlomieju — APPROVED** [review]
LGTM
