### PR TITLE
fix(workspace): do not resolve to self for npm pkg depending on matching req

### LINKED ISSUE #24584: Package depending on itself as a package should not resolve to self
I think this is a bug with the npm workspace change.

```
git clone https://github.com/Microsoft/TypeScript
cd TypeScript
export DENO_FUTURE=1
deno install
deno task build
```

It will fail because node_modules/typescript is a symlink to the parent directory, but npm seems to resolve this to a remote dependency. I think maybe it should only resolve to self in a workspace, but not in a single package I guess. Marking this as needs investigation.

Version: Deno 1.45.2

### PR DESCRIPTION
**Pull request by dsherret**
Closes #24584

### CODE REVIEW

File: cli/args/package_json.rs [hunk 1]
```diff
@@ -7,18 +7,27 @@ use deno_config::package_json::PackageJsonDepValue;
...
 use deno_semver::package::PackageReq;
 
+#[derive(Debug)]
+pub struct InstallNpmRemotePkg {
+  pub alias: String,
+  // todo(24419): use this when setting up the node_modules dir
+  #[allow(dead_code)]
+  pub base_dir: PathBuf,
+  pub req: PackageReq,
+}
```
Comment (dsherret) [inline cli/args/package_json.rs:17]: This change was in preparation for https://github.com/denoland/deno/issues/24419

**Review by nathanwhit — APPROVED** [review]
LGTM!
