### PR TITLE
Catch errors on file_server response.send. Fixes #5624

### LINKED ISSUE #5624: file_server not handling BrokenPipe
is this worth to fix? and is there another full featured file_server in the community out of std?

easy to reproduce this when serving a large file to browser, and click stop loading

```console
[2020-05-19 12:00:25] "GET /output.json HTTP/1.1" 200
error: Uncaught BrokenPipe: Broken pipe (os error 32)
    at unwrapResponse ($deno$/ops/dispatch_minimal.ts:63:11)
    at Object.sendAsyncMinimal ($deno$/ops/dispatch_minimal.ts:106:10)
    at async Object.write ($deno$/ops/io.ts:65:18)
    at async BufWriter.flush (https://deno.land/std/io/bufio.ts:475:25)
    at async BufWriter.write (https://deno.land/std/io/bufio.ts:514:9)
    at async Object.copy ($deno$/io.ts:70:21)
    at async writeResponse (https://deno.land/std/http/_io.ts:265:15)
    at async ServerRequest.respond (https://deno.land/std/http/server.ts:97:7)
```

### PR DESCRIPTION
**Pull request by jimvandervoort**
This PR simply logs errors thrown from `response.send` to the console:

```
2020-06-13 21:13:28] "GET /large.txt HTTP/1.1" 200
Broken pipe (os error 32)
```

I'm not sure if this is actually useful info for users (at least not in the case of #5624). I quickly looked at python's `http.server`, Go's. `FileServer`, nginx and http-party/http-server, and none of them seem to log any info when the client closes connection early.

Is it worth considering changing the `server.ts` api to better communicate when the client closes the connection? (instead of throwing an os error on write). In node, `http.ClientRequest` sends a `close` event when the client disconnects, using `response.write` after that is actually allowed and does not throw an error (last part is also not ideal imho).

### CODE REVIEW

File: std/http/file_server.ts [hunk 1]
```diff
@@ -353,7 +353,11 @@ function main(): void {
           setCORS(response);
         }
         serverLog(req, response!);
-        req.respond(response!);
+        try {
+          await req.respond(response!);
```
Comment (ry) [inline std/http/file_server.ts:357]: There shouldn't be an await here. We want to asynchronously respond to requests so others can be handled.

Comment (jimvandervoort) [reply std/http/file_server.ts:357]: This handler function is not awaited for in `server.ts` `listenAndServe`: https://github.com/denoland/deno/blob/master/std/http/server.ts#L279

So I suppose async requests still works. I'm just using await because otherwise the handler function will end before the error is thrown (and will thus not be caught).

Is that correct? Otherwise I'll change it to use `catch()` on the respond promise.
