### PR TITLE
fix(lsp): prevent crash analyzing module

### LINKED ISSUE #17640: lsp crashing with a simple import
**Describe the bug**

**To Reproduce**

Trying to import the supabase package from unpkg or esm.sh, it makes in both cases crash the lsp server.

```ts
import { createClient } from 'https://unpkg.com/@supabase/supabase-js@2';

console.log(createClient);
```

Here is the error output:
```
Starting Deno language server...
  version: 1.30.1 (release, x86_64-unknown-linux-gnu)
  executable: /home/Olyno/.deno/bin/deno
Connected to "Visual Studio Code" 1.75.0
Enabling import suggestions for: https://x.nest.land
Download https://x.nest.land/.well-known/deno-import-intellisense.json
Download https://intellisense.nest.land/deno-import-intellisense.json
Enabling import suggestions for: https://crux.land
Enabling import suggestions for: https://deno.land
Server ready.

============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: linux x86_64
Version: 1.30.1
Args: ["/home/Olyno/.deno/bin/deno", "lsp"]

thread 'main' panicked at 'internal error: entered unreachable code', cli/lsp/documents.rs:1455:7
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[Error - 1:10:24 AM] The Deno Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
```

I'm wondering if it's not an issue with organization level imports, because i don't have this issue with the ``http`` module from the ``std`` module.

**Expected behavior**

It shouldn't make it crash.

**Screenshots**

/

**Versions**

vscode: 1.75.0 deno: 1.30.1 extension: v3.17.0

### PR DESCRIPTION
**Pull request by dsherret**
Closes #17640

### CODE REVIEW

File: cli/lsp/documents.rs [hunk 1]
```diff
@@ -1440,40 +1439,14 @@ fn analyze_module(
...
-        Some(&analyzer),
-      )
-    }
+    Ok(parsed_source) => Ok(deno_graph::parse_module_from_ast(
+      specifier,
+      deno_graph::ModuleKind::Esm,
+      maybe_headers,
+      parsed_source,
+      maybe_resolver,
+    )),
```
Comment (dsherret) [inline cli/lsp/documents.rs:1449]: I didn't bother adding a test for the scenario because this will now never fail and I don't believe having a regression test for the previous scenario is worth it.

**Review by bartlomieju — APPROVED** [review]
LGTM

**Comment by ErkanSensei** [comment]
Hello, any way I can use this fix ASAP? I have the same issue as the original thread

**Comment by bartlomieju** [comment]
> Hello, any way I can use this fix ASAP? I have the same issue as the original thread

If you are on other os/arch that macOS M1 (M2, etc) you can use canary version of Deno. Run `deno upgrade --canary` to use it.

**Comment by ErkanSensei** [comment]
I am on M1 :)
I guess I have to wait?

**Comment by bartlomieju** [comment]
> I am on M1 :) I guess I have to wait?

Yes, we don't provide canary release for M1. This fix should be available in 1.30.3 that will be released next week.

**Comment by dsherret** [comment]
@ErkanSensei you might want to consider downgrading (`deno upgrade --version 1.30.0`)

**Comment by ErkanSensei** [comment]
@dsherret Yup, that did the trick for now! Thanks, I appreciate the followup
