### PR TITLE
fix(std/node): resolve files in symlinked directories

### LINKED ISSUE #3867: PNPM and createRequire not working
I tried to resolve this bug on the glitter channel, and was told it worked fine on other systems that are not using PNPM:

> sounds like an edge case with hard links where only one is being followed. npm doesn't use hard links like pnpm as far as I know. Probably worth filing an issue.

So just make a directory with these two files in, have https://github.com/pnpm/pnpm installed and type `pnpm install` then `deno -A rules.ts`

rules.ts
```
import { createRequire } from 'https://deno.land/std@v0.31.0/node/module.ts';
const denoRequire = createRequire(import.meta.url);

const test2 = denoRequire(
  './node_modules/@typescript-eslint/eslint-plugin/dist/configs/eslint-recommended.js'
);
console.log(JSON.stringify(test2));

const test1 = denoRequire(
  './node_modules/eslint-config-airbnb-typescript/base.js'
);
console.log(JSON.stringify(test1));
```
package.json
```
{
  "name": "deno-test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@typescript-eslint/eslint-plugin": "^2.18.0",
    "@typescript-eslint/parser": "^2.18.0",
    "eslint": "^6.8.0",
    "eslint-config-airbnb-typescript": "^6.3.1",
    "eslint-plugin-import": "^2.20.1",
    "typescript": "^3.7.5"
  }
}
```
Error:
```
deno -A rules.ts 
Compile file:///home/david/Downloads/denobug/rules.ts
{"default":{"overrides":[{"files":["*.ts","*.tsx"],"rules":{"getter-return":"off","no-dupe-args":"off","no-dupe-keys":"off","no-unreachable":"off","valid-typeof":"off","no-const-a
ssign":"off","no-new-symbol":"off","no-this-before-super":"off","no-undef":"off","no-dupe-class-members":"off","no-redeclare":"off"}}]}}
error: Uncaught Error: Cannot find module 'eslint-config-airbnb-base'
Require stack:
- /home/david/Downloads/denobug/node_modules/eslint-config-airbnb-typescript/base.js
- /home/david/Downloads/denobug/rules.ts
► module.ts:255:19

255       const err = new Error(message);
                      ^

    at _resolveFilename (module.ts:255:19)
    at resolve (module.ts:1105:19)
    at <unknown>:2:61
    at _compile (module.ts:151:36)
    at Module._extensions..js (module.ts:1051:10)
    at load (module.ts:130:34)
    at _load (module.ts:392:14)
    at require (module.ts:116:21)
    at require (module.ts:1101:16)
    at rules.ts:9:15
```
my system:
```
linux: centos8

deno 0.31.0
v8 8.1.108
typescript 3.7.2
```

### PR DESCRIPTION
**Pull request by Liamolucko**
Fixes #3867

### CODE REVIEW

File: std/node/module_test.ts [hunk 1]
```diff
@@ -69,3 +69,15 @@ Deno.test("requireStack", function () {
     assertStringIncludes(e.stack, "/tests/cjs/cjs_throw.js");
   }
 });
+
+Deno.test("requireFileInSymlinkDir", async () => {
+  // I don't think symlinks would hold up too well through Git, so create it at runtime
```
Comment (bartlomieju) [inline std/node/module_test.ts:74]: We have symlinks in the repo (`cli/tests/symlink_to_subdir`), I think it's preferable solution to creating at runtime

**Review by bartlomieju — CHANGES_REQUESTED** [review]

**Review by bartlomieju — APPROVED** [review]
LGTM, thanks @Liamolucko
