### PR TITLE
fix(vendor): error on dynamic imports that fail to load instead of panicking

### LINKED ISSUE #15215: Deno panics when vendoring `"https://esm.sh/rollup@2.75.7?pin=v87"`
I have a file `test.js`:
```js
import {rollup} from "https://esm.sh/rollup@2.75.7?pin=v87";
console.log("done");
```

and if I run `deno vendor test.js` deno panics with the following stack trace:
```
Platform: macos x86_64
Version: 1.23.4+635eed9
Args: ["deno", "vendor", "test.js"]

thread 'main' panicked at 'Could not find local path for https://esm.sh/v87/fsevents@2.3.2/deno/fsevents.js', cli/tools/vendor/mappings.rs:138:11
stack backtrace:
   0:        0x104f25599 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h6ab6a4b798848da1
   1:        0x104571e7b - core::fmt::write::h3cfeb2e4a41b5943
   2:        0x104ef6478 - std::io::Write::write_fmt::h207c490a0e714424
   3:        0x104f2a46d - std::panicking::default_hook::{{closure}}::h2dad0ca14a5f6fb3
   4:        0x104f2a16a - std::panicking::default_hook::he28ca1b524a71648
   5:        0x1045022d7 - deno::setup_panic_hook::{{closure}}::he8024f67c013d490
   6:        0x104f2af90 - std::panicking::rust_panic_with_hook::hc50fd680dab3e13f
   7:        0x104f2adf4 - std::panicking::begin_panic_handler::{{closure}}::h73da24fc37eba97b
   8:        0x104f2ad69 - std::sys_common::backtrace::__rust_end_short_backtrace::hff104f8fa804dc90
   9:        0x104f2ad25 - _rust_begin_unwind
  10:        0x10622f4d3 - core::panicking::panic_fmt::hf5e95a7953f70bca
  11:        0x10443df12 - deno::tools::vendor::mappings::Mappings::local_path::h5919da71c72a4b61
  12:        0x10443fa49 - deno::tools::vendor::mappings::Mappings::local_uri::ha6a12c2d9c3c472e
  13:        0x10443ec29 - deno::tools::vendor::mappings::Mappings::relative_specifier_text::h740e17e051f349c8
  14:        0x10443e56b - deno::tools::vendor::import_map::visit_maybe_resolved::hae6ba9302eb48b01
  15:        0x10443a8b0 - deno::tools::vendor::build::build::hedba2e9c83a428e4
  16:        0x104435f82 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hb0e699d5f44bfb4d
  17:        0x1041d335e - deno::main::{{closure}}::ha10932b0dab64839
  18:        0x1041c6c75 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h75517a8166f7f072
  19:        0x1041c40af - deno_runtime::tokio_util::run_local::h725d4437ffae34cd
  20:        0x1041c350d - deno::main::hb9f7125e60480e76
  21:        0x1041c2b4e - std::sys_common::backtrace::__rust_begin_short_backtrace::had83fdd2d04aa992
  22:        0x1041c2ef9 - _main
```

I've also found that deno very frequently prints `Download https://esm.sh/v87/fsevents@2.3.2/deno/fsevents.js` even though that should definitely have been cached by now. Sometimes it doesn't panic but it keeps hanging on `Download https://esm.sh/v87/fsevents@2.3.2/deno/fsevents.js`.

I wouldn't be surprised if this is exclusive to my machine, maybe my cache is simply corrupt.

### PR DESCRIPTION
**Pull request by dsherret**
Closes #15215

### CODE REVIEW

File: cli/tools/vendor/build.rs [hunk 1]
```diff
@@ -1003,6 +1011,26 @@ mod test {
     );
   }
 
+  #[tokio::test]
+  async fn vendor_file_fails_loading_dynamic_import() {
+    let mut builder = VendorTestBuilder::with_default_setup();
+    let err = builder
+      .with_loader(|loader| {
+        loader.add("/mod.ts", "import 'https://localhost/mod.ts';");
+        loader.add("https://localhost/mod.ts", "await import('./test.ts');");
```
Comment (dsherret) [inline cli/tools/vendor/build.rs:1020]: Interestingly this only occurs for dynamic imports.

File: cli/tools/vendor/build.rs [hunk 2]
```diff
@@ -68,6 +68,14 @@ pub fn build(
   graph.lock()?;
   graph.valid()?;
```
Comment (dsherret) [inline cli/tools/vendor/build.rs:69]: Removing this in https://github.com/denoland/deno/pull/15390/files#diff-25670ef0ccc50ba364743d0195b7ed54396876142b482fa36b99926bc1d6b46bL69 because it would error on some bare specifiers in type declarations, which wouldn't occur with `deno run` even when doing `--check=remote`.

**Review by kitsonk — APPROVED** [review]
LGTM
