### PR TITLE
fix(#5449): REPL does not exit properly when close() is called

### LINKED ISSUE #5449: Unwanted behaviour close() in REPL
When we do `close()`, it exits the REPL but somehow after then I am unable to type
in the terminal, though if I type and press enter it executes the commands but I
can't see the characters.

```
[sanket143@lisa test_plugin]$ deno
Deno 1.0.0
exit using ctrl+d or close()
> close()
undefined
> [sanket143@lisa test_plugin]$ Cargo.toml  src  tests
[sanket143@lisa test_plugin]$ ^C
[sanket143@lisa test_plugin]$ 
```

### PR DESCRIPTION
**Pull request by uki00a**
Closes #5449.

---

**Before this fix:**

1. User types `close()` in REPL.
2. `globalThis.close()` is called and it queues up a call to `Deno.exit()` as follows:
https://github.com/denoland/deno/blob/a08a4abac116eda498f8ad2df13b3816ec36c9ad/cli/js/runtime_main.ts#L38-L54
3. REPL shows `undefined` which is the result of evaluation of `globalThis.close()` ([https://github.com/denoland/deno/blob/master/cli/js/repl.ts#L48](repl.ts#L48)).
4. REPL shows the prompt and  wait for user to type something ([repl.ts#L116](https://github.com/denoland/deno/blob/master/cli/js/repl.ts#L116)).
5. Before user types something in REPL, the process is terminated by a queued call to `Deno.exit()`.

**After this fix:**

1. User types `close()` in REPL.
2. `globalThis.close()` is called, which immediately terminates REPL and the process.
    - This function is overwritten [at line 111 in repl.ts](https://github.com/denoland/deno/pull/5451/files#diff-73adb4a3036d57af9ca33dde0122d6acR110-R116).

### CODE REVIEW

File: cli/js/repl.ts [hunk 1]
```diff
@@ -106,6 +107,13 @@ export async function replLoop(): Promise<void> {
     },
   });
 
+  // Configure globalThis.close to terminate REPL properly when `close()` is called.
+  Object.defineProperty(
+    globalThis,
+    "close",
+    writable(() => quitRepl(0))
+  );
```
Comment (ry) [inline cli/js/repl.ts:115]: I also noticed this problem - it's annoying - so thanks for looking into it. But I'm not sure I agree with you fix. It works, of course, but I wonder if there isn't a better solution. I don't like that `close()` in the REPL is now a different function than it is in scripts.

Comment (uki00a) [reply cli/js/repl.ts:115]: @ry Ok, I agree with you.

How about the following changes?

- Stop overwriting `globalThis.close()`.
- Add a function that checks if `close()` is called (`isCloseCalled()`).
- Quit the REPL if `isCloseCalled()` returns `true` before entering the next loop .

```diff
diff --git a/cli/js/repl.ts b/cli/js/repl.ts
index d969a1e3..b6b83a02 100644
--- a/cli/js/repl.ts
+++ b/cli/js/repl.ts
@@ -33,6 +33,12 @@ function isRecoverableError(e: Error): boolean {
   return recoverableErrorMessages.includes(e.message);
 }

+// Returns `true` if `close()` is called in REPL.
+function isCloseCalled(): boolean {
+  // @ts-ignore
+  return globalThis.closed;
+}
+
 // eslint-disable-next-line @typescript-eslint/no-explicit-any
 type Value = any;

@@ -46,7 +52,9 @@ function evaluate(code: string): boolean {
   const [result, errInfo] = core.evalContext(code);
   if (!errInfo) {
     lastEvalResult = result;
-    replLog(result);
+    if (!isCloseCalled()) {
+      replLog(result);
+    }
   } else if (errInfo.isCompileError && isRecoverableError(errInfo.thrown)) {
     // Recoverable compiler error
     return false; // don't consume code.
@@ -107,17 +115,14 @@ export async function replLoop(): Promise<void> {
     },
   });

-  // Configure globalThis.close to terminate REPL properly when `close()` is called.
-  Object.defineProperty(
-    globalThis,
-    "close",
-    writable(() => quitRepl(0))
-  );
-
   replLog(`Deno ${version.deno}`);
   replLog("exit using ctrl+d or close()");

   while (true) {
+    if (isCloseCalled()) {
+      quitRepl(0);
+    }
+
     let code = "";
     // Top level read
     try {

```

Comment (uki00a) [reply cli/js/repl.ts:115]: Note: `globalThis.closed` is defined in [runtime_main.ts](https://github.com/denoland/deno/blob/89fe81168e75a375a67e9d391b367d2a9749153c/cli/js/runtime_main.ts#L64).
