### PR TITLE
fix(ext/node): Add sqlite allow unknown named params option

### LINKED ISSUE #31196: `node:sqlite`: StatementSync's `setAllowUnknownNamedParameters(boolean)` method isn't implemented
Version: Deno 2.5.6

* API doc: https://nodejs.org/api/sqlite.html#statementsetallowunknownnamedparametersenabled
* Node.js PR: https://github.com/nodejs/node/pull/57552

With the help of that method, code like the following can work without throwing an error:

```js
import { DatabaseSync } from "node:sqlite"

const person = {name: "Joe", age: 28, height: 185}

const db = new DatabaseSync(":memory:")
db.exec("CREATE TABLE attendees (name TEXT, age INTEGER)")

const stmt = db.prepare("SELECT COUNT(*) FROM attendees WHERE name = :name AND age = :age")
//stmt.setAllowUnknownNamedParameters(true)

stmt.get(person)

/*
Uncaught Error: Unknown named parameter 'height'
    at <anonymous>:11:6
    at eventLoopTick (ext:core/01_core.js:179:7)
*/
```

### PR DESCRIPTION
**Pull request by isAdrisal**
Adds [statement.setAllowUnknownNamedParameters(enabled)](https://nodejs.org/api/sqlite.html#statementsetallowunknownnamedparametersenabled) to node:sqlite.

Closes #31196

This is my first commit to deno and I'm very new to rust so apologies in advance for any dumb mistakes!

I've mostly copied the implementation of `setAllowBareNamedParams` so hopefully it's mostly correct.

### CODE REVIEW

File: ext/node/ops/sqlite/statement.rs [hunk 1]
```diff
@@ -487,6 +488,10 @@ impl StatementSync {
             }
 
             if r == 0 {
+              if self.allow_unknown_named_params.get() {
```
Comment (isAdrisal) [inline ext/node/ops/sqlite/statement.rs:491]: Is this ok being accessed each time inside the loop or should it be allocated first?

**Comment by isAdrisal** [comment]
@bartlomieju I think this is ready to review if you have some time :)

File: ext/node/ops/sqlite/statement.rs (hunk 1 above)
Comment (littledivy) [reply ext/node/ops/sqlite/statement.rs:491]: yes, this should be fine
