### PR TITLE
fix(cli): use millisecond precision for Deno.futime and Deno.utime

### LINKED ISSUE #2411: [bug] Deno.utime
As explained in https://github.com/denoland/deno_std/issues/421
Deno.utime seems buggy on MacOs.

> Loss of precision when changing timestamps using Deno.utime

cc @axetroy

example:
```
test [fs] copy synchronously with preserve timestamps ... ‌FAILED‌
Error: 

    ‌[Diff]‌ ‌Left‌ &#x2F; ‌Right‌


-   1558364063‌
+   1558364062‌

    at assertEquals (/Users/vsts/agent/2.150.3/work/1/s/testing/pretty.ts:66:11)
    at assertEquals (/Users/vsts/agent/2.150.3/work/1/s/testing/asserts.ts:64:5)
    at /Users/vsts/agent/2.150.3/work/1/s/fs/copy_test.ts:185:5
    at fn (/Users/vsts/agent/2.150.3/work/1/s/fs/copy_test.ts:32:13)
    at runTestsSerial (/Users/vsts/agent/2.150.3/work/1/s/testing/mod.ts:112:19)
    at async runTests (/Users/vsts/agent/2.150.3/work/1/s/testing/mod.ts:147:9)
    at async main (/Users/vsts/agent/2.150.3/work/1/s/testing/main.ts:5:5)
```

### LINKED ISSUE #5065: utimeSync truncates millisecond timestamps to nearest second
Deno `statSync` returns millisecond resolution but `utimeSync` truncates to seconds resolution.

Platform:

```
$ uname -a
Linux gnome-1804 4.15.0-99-generic #100-Ubuntu SMP Wed Apr 22 20:32:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

$ deno --version
deno 0.42.0
v8 8.2.308
typescript 3.8.3
```

In lieu of the REPL (https://github.com/denoland/deno/issues/5063) I ran the following code:

```
const encoder = new TextEncoder();
const data = encoder.encode("foobar");

Deno.writeFileSync("test.txt", data);
console.log(`mtime: ${Deno.statSync("test.txt").mtime!.getTime()}`);
const newTime = 1588561654321;
console.log(`updating mtime to ${newTime}`);
Deno.utimeSync("test.txt", new Date(newTime), new Date(newTime));
console.log(`mtime: ${Deno.statSync("test.txt").mtime!.getTime()}`);
```

Output (the updated mtime is truncated to the nearest second):

```
mtime: 1588564365265
updating mtime to 1588561654321
mtime: 1588561654000
```

The Node.js `utimesSync` API does not exhibit this behaviour and sets millisecond timestamp resolution:

```
$ node --version
v13.14.0

$ node
Welcome to Node.js v13.14.0.
Type ".help" for more information.
> fs.writeFileSync('test.txt', 'foobar');
undefined
> fs.statSync('test.txt').mtime.getTime();
1588561704180
> fs.utimesSync('test.txt', new Date(1588561576064), new Date(1588561576064));
undefined
> fs.statSync('test.txt').mtime.getTime();
1588561576064
> 
```

### PR DESCRIPTION
**Pull request by caspervonb**
This uses millisecond precision in Deno.futime and Deno.utime when sourcing a timestamp from a Date object.

Fixes #2411
Fixes #5065

### CODE REVIEW

File: cli/tests/unit/utime_test.ts [hunk 1]
```diff
@@ -1,18 +1,11 @@
...
 import {
   unitTest,
-  assert,
+  assertEquals,
   assertThrows,
   assertThrowsAsync,
 } from "./test_util.ts";
 
-// Allow 10 second difference.
-// Note this might not be enough for FAT (but we are not testing on such fs).
```
Comment (caspervonb) [inline cli/tests/unit/utime_test.ts:10]: Nothing (symlinks etc) work on a FAT filesystem so shouldn't be concerned about that.

File: cli/rt/30_fs.js [hunk 2]
```diff
@@ -264,8 +264,25 @@
     await sendAsync("op_link_async", { oldpath, newpath });
   }
 
-  function toSecondsFromEpoch(v) {
-    return v instanceof Date ? Math.trunc(v.valueOf() / 1000) : v;
+  function toUnixTimeFromEpoch(value) {
+    if (value instanceof Date) {
+      const time = value.valueOf();
+      const seconds = Math.trunc(time / 1e3);
+      const nanoseconds = Math.trunc(time - (seconds * 1e3)) * 1e6;
```
Comment (caspervonb) [inline cli/rt/30_fs.js:271]: On second thought, need to truncate here? seconds is already truncated.

**Comment by uki00a** [comment]
This PR also fixes #5065.

**Comment by uki00a** [comment]
@caspervonb "[[fs] copy with preserve timestamps](https://github.com/denoland/deno/blob/644190eed862c2224630dd68404a5fd6e2e30440/std/fs/copy_test.ts#L147)" test has been ignored due to the issue ##5065.
Could you re-enable it in this PR?

**Comment by caspervonb** [comment]
> The following test has been ignored due to the issue #5065:

Done, and passing.
Thanks for the heads up @uki00a.

PTAL @ry.

File: std/fs/copy_test.ts [hunk 3]
```diff
@@ -32,13 +32,6 @@ function testCopy(
   });
 }
 
-function testCopyIgnore(
-  name: string,
-  cb: (tempDir: string) => Promise<void>,
-): void {
-  testCopy(name, cb, true);
-}
-
```
Comment (ry) [inline std/fs/copy_test.ts:41]: 👍
