### PR TITLE
fix(ext/ffi): Fix UnsafeCallback ref'ing making Deno enter a live-loop

### LINKED ISSUE #15136: Event loop middlewares returning true cause a live loop
If a `deno_runtime` user wants to use the event loop middleware feature to keep Deno from exiting while waiting for eg. a message to come from a spawned thread, they must return `true` from the event loop middleware.

This will cause the Deno runtime to wake up the isolate to check for new tasks, which causes the event loop middlewares to be immediately re-polled. As a result, any event loop middleware returning `true` will essentially put Deno into a live loop with the process taking as much CPU processing power as it can get.

Additionally, this is somewhat at odds with the presumably intended use case of event loop middleware: If a middleware causes JS to be run on the isolate and that JS creates microtasks, then one might expect that the middleware should then return true (or some more explicit enum value) to signal that the isolate should be woken up and microtasks performed. What instead happens is that Deno's automatic microtasks policy will run any created microtasks as soon as the JS function run by the middleware returns, effectively making them just synchronous calls.

As such, event loop middleware are currently not a good solution to keeping Deno alive while some external task is being performed. One solution might be to enable event loop middleware to return a delay value, which would sleep the Deno process for the delay (of course presuming no one else returns a smaller delay, or returns an eager polling command) and re-poll event loop middlewares after the delay (possibly waking up the isolate as well).

Another solution might be to give ops easier access to a clonable Waker that could be used to manually wake up the isolate when or after performing external tasks. This would be more in line with the JS Promise / callback system, whereas the previous would be more like a ticking interval.

Whether or not either of these solutions is implemented, the microtasks policy also causes some confusion to these. A Waker waking up the isolate just for the purpose of creating a Promise that, once resolved on the next tick, will perform heavier calculations would unexpectedly find itself blocked by the heavier calculations as those would be performed synchronously when the Promise creating JS code returned. Similarly, an event loop middleware causing JS to be run on the isolate would find that any microtasks created by that JS would already be run as part of the call into the isolate, and explicitly telling Deno to execute microtasks eagerly after the middleware returned would be unnecessary.

### PR DESCRIPTION
**Pull request by aapoalas**
Fixes #15136

Currently `UnsafeCallback` class' `ref()` and `unref()` methods rely on the `event_loop_middleware` implementation in core. If even a single `UnsafeCallback` is ref'ed, then the FFI event loop middleware will always return `true` to signify that there may still be more work for the event loop to do.

The middleware handling in core does not wait a moment to check again, but will instead synchronously directly re-poll the event loop and middlewares for more work. This becomes a live-loop.

This PR introduces a `Future` implementation for the `CallbackInfo` struct that acts as the intermediary data storage between an `UnsafeCallback` and the `libffi` C callback. Ref'ing a callback now means calling an async op that binds to the `CallbackInfo` Future and only resolves once the callback is unref'ed. The `libffi` C callback will call the waker of this Future when it fires to make sure that the main thread wakes up to receive the callback.

### CODE REVIEW

File: ext/ffi/00_ffi.js [hunk 1]
```diff
@@ -261,22 +262,27 @@
...
+        this.#refpromise = undefined;
       }
     }
 
     close() {
-      if (this.#refcount) {
+      if (this.#refcount > 0) {
         this.#refcount = 0;
-        ops.op_ffi_unsafe_callback_ref(false);
+        core.opSync("op_ffi_unsafe_callback_unref", this.#rid);
```
Comment (littledivy) [inline ext/ffi/00_ffi.js:284]: `ops.op_ffi_unsafe_callback_unref(this.#rid);`

File: ext/ffi/lib.rs [hunk 2]
```diff
@@ -1397,6 +1397,12 @@ struct CallbackInfo {
   pub callback: NonNull<v8::Function>,
   pub context: NonNull<v8::Context>,
   pub isolate: *mut v8::Isolate,
+  pub state: Arc<Mutex<SharedState>>,
+}
+
+struct SharedState {
+  refed: bool,
+  waker: Option<Waker>,
 }
```
Comment (littledivy) [inline ext/ffi/lib.rs:1406]: Why do we need a Mutex? Waker is Send + Sync. `refed` can be part of CallbackInfo

Comment (aapoalas) [reply ext/ffi/lib.rs:1406]: > Why do we need a Mutex? Waker is Send + Sync. `refed` can be part of CallbackInfo

I have no idea :D This is quite directly copied over from here: https://rust-lang.github.io/async-book/02_execution/03_wakeups.html

Comment (aapoalas) [reply ext/ffi/lib.rs:1406]: I tried removing the whole `SharedState` and moving both `refed` and `waker` to the `CallbackInfo` struct but moving even just the `refed` bool caused tests to hang. Moving `waker` along with it did not fix the situation.

**Comment by aapoalas** [comment]
I needed to make unref'ing the callback asynchronous. Additionally, closing a ref'ed callback resource is internally-asynchronous.

The reason for this is that the Future that controls the ref'ing is dependent on the resources continued existence, and the resource cannot be dropped while a ref is still active. If it gets dropped, a panic will occur.

As a result, any tests that rely on a ref'ed callback disappearing from the resource table synchronously after a `close()` call will fail. The proper way to "synchronously" close a callback resource is to first `unref()` it, and only call `close()` on it once the `unref()` method resolves with `true`.

File: ext/ffi/lib.rs [hunk 3]
```diff
@@ -1834,17 +1852,52 @@ where
...
+    // The future for the CallbackInfo never resolves: It can only be canceled.
+    Poll::Pending
   }
 }
 
+#[op]
+fn op_ffi_unsafe_callback_ref(
+  state: &mut deno_core::OpState,
+  rid: ResourceId,
+) -> Result<impl Future<Output = Result<(), AnyError>>, AnyError> {
```
Comment (aapoalas) [inline ext/ffi/lib.rs:1872]: There's something odd going on with this op's hybridity: Even if the resource is already closed and the getting by rid from the resource table fails, it will still get rejected in a promise instead of being thrown synchronously. @littledivy Do you have any clue what might be wrong with this?

File: ext/ffi/lib.rs (hunk 2 above)
Comment (aapoalas) [reply ext/ffi/lib.rs]: After making the resolving of the CallbackInfo Future happen only through cancel I was now able to remove the `Arc<Mutex<T>>` part and just park the waker inside of `CallbackInfo`. Foreign threads will call `waker.wake_by_ref()` to avoid unnecessary (?) clones.

Locally tests still pass so this seems fine. Maybe.

File: ext/ffi/lib.rs (hunk 3 above)
Comment (aapoalas) [reply ext/ffi/lib.rs:1826]: I misremembered: The op macro purposefully (perhaps unnecessarily) handles even the synchronous result through the promise.

File: ext/ffi/lib.rs [hunk 4]
```diff
@@ -1790,17 +1806,52 @@ where
...
+  let callback_resource =
+    state.resource_table.get::<UnsafeCallbackResource>(rid)?;
+  let info_ptr = callback_resource.info;
+  // SAFETY: CallbackInfo pointer stays valid as long as the resource is still alive.
+  let info: &'static mut CallbackInfo = unsafe { info_ptr.as_mut().unwrap() };
```
Comment (littledivy) [inline ext/ffi/lib.rs:1831]: Can we move this decl inside the future? It wouldn't have to be `'static` that way.

File: ext/ffi/lib.rs [hunk 5]
```diff
@@ -1790,17 +1806,52 @@ where
...
+}
+
+#[op(fast)]
+fn op_ffi_unsafe_callback_unref(
+  state: &mut deno_core::OpState,
+  rid: u32,
+) -> Result<(), AnyError> {
+  let callback_resource =
+    state.resource_table.get::<UnsafeCallbackResource>(rid)?;
+  // SAFETY: CallbackInfo pointer stays valid as long as the resource is still alive.
```
Comment (littledivy) [inline ext/ffi/lib.rs:1850]: Not unsafe so remove `// SAFETY`

**Review by littledivy — APPROVED** [review]
LGTM! Thanks
