### PR TITLE
fix(ext/os): silently ignore invalid utf-8 characters in os vars

### LINKED ISSUE #29475: thread 'main' panicked - Deno doesn't like emojis in path, maybe?
I have emojis in my paths, and it looks like Deno isn't fond of that?

```
$ bin/build

============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: macos aarch64
Version: 2.1.9
Args: ["deno", "run", "-A", "bin/build"]

thread 'main' panicked at std/src/env.rs:163:83:
called `Result::unwrap()` on an `Err` value: "$HOME/project/\xF0\x83\xBF\xA7\x83\x80 foo/\xF0\x83\xBF\x83\xB3\x83\xA8 bar/baz/bin/build"
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

The bin/build script:

```
#!/usr/bin/env -S deno run -A

import * as esbuild from "npm:esbuild@0.25.5";
import { denoPlugins } from "jsr:@duesabati/esbuild-deno-plugin@^0.0.1";

const result = await esbuild.build({
    plugins: [...denoPlugins()],
    entryPoints: ["https://deno.land/std@0.185.0/bytes/mod.ts"],
    outfile: "./dist/bytes.esm.js",
    bundle: true,
    format: "esm",
});

console.log(result.outputFiles);

esbuild.stop();
```

### PR DESCRIPTION
**Pull request by efekrskl**
Fixes #29475 

Where would be the best place to add tests for this?

### CODE REVIEW

File: ext/os/lib.rs [hunk 1]
```diff
@@ -183,7 +183,17 @@ fn op_env(
...
+  Ok(
+    env::vars_os()
+      .filter_map(|(key_os, value_os)| {
+        key_os
+          .into_string()
+          .ok()
+          .and_then(|key| value_os.into_string().ok().map(|value| (key, value)))
+      })
+      .collect(),
+  )
```
Comment (dsherret) [inline ext/os/lib.rs:196]: Do you know what Node does?

Comment (efekrskl) [reply ext/os/lib.rs:196]: As far as I see, node also silently ignores such env vars. When I run something like 

```sh
env $(printf "BAD\xF0\x83\xBF\xA7\x83\x80_VAR=/some/path") node script.ts
```

```ts
// script.ts

for (const [key, value] of Object.entries(process.env)) {
    console.log(JSON.stringify(key), '=', value);
}
```

Runs fine and outputs envs without the malformed one, the same input crashes deno. I'm not familiar with node codebase though, so I'm not sure how exactly they handle it.

Comment (anonhostpi) [reply ext/os/lib.rs:196]: Its probably not a good security practice to accept malformed env vars anyway.

Even in cases where the var was encoded with a different encoding (like Latin-1), its probably best to deprecate and discourage that kind of behavior.

**Review by dsherret — APPROVED** [review]
LGTM. I'm not sure how to easily do a test for this and it's rare to occur, so this seems fine to just merge.
