### PR TITLE
fix(check): ensure diagnostics caused by changes in other files get invalidated between runs

### LINKED ISSUE #18516: `deno check` cache causes wrong results
Summary
----------

The cache used by `deno check` can lead to incorrect results reported.  Running `deno check app.ts` a second time will just return the previous result, even though the types of local modules that `app.ts` depends on have been corrected.

Reproduction
---------------

Given the files:

```ts
// File: app.ts
import { greet } from "./_greet.ts"

greet("world")
```

and:

```ts
// File: _greet.ts
export function greet(name: number) {
    console.log(`Hello, ${name}!`)
}
```

`deno check` gives the expected error:

```
Check file:///C:/Users/Cody/code/deno/check-cache-bug/app.ts
error: TS2345 [ERROR]: Argument of type 'string' is not assignable to parameter of type 'number'.
greet("world")
      ~~~~~~~
    at file:///C:/Users/Cody/code/deno/check-cache-bug/app.ts:4:7
```

If we fix `_greet.ts` to take a `name: string`, `deno check` should now pass, but we still get the same error. 

You can work around this by running `deno check --reload app.ts`, but there are two big problems with this:

First: For large projects, this can result in re-downloading quite a large dependency tree with every run of `deno check --reload`.

But more importantly, you have to first *know* that you're getting the wrong results to know to go look for `--reload`.  If you run into the caching problem from the other direction (i.e.: you cached a "pass", which should now be failing), `deno check` is giving you a dangerous result. You think your build is good and you push it out, only to run into runtime errors that TypeScript should've saved you from.

Possible fixes?
---------------

Maybe when `deno check` caches its results, it can save the graph of local dependencies checked. Then, the next `deno check` will *only* use the cache if *none* of those local dependencies have changed.

### PR DESCRIPTION
**Pull request by dsherret**
Regression caused by the performance improvement in #18329. Figuring this out was hard. It's luckily still fast after this change.

Closes #18516

### CODE REVIEW

File: test_util/src/builders.rs [hunk 1]
```diff
@@ -46,17 +46,15 @@ impl TestContextBuilder {
...
 
   pub fn for_npm() -> Self {
-    let mut builder = Self::new();
-    builder.use_http_server().add_npm_env_vars();
-    builder
+    Self::new().use_http_server().add_npm_env_vars()
   }
 
-  pub fn use_http_server(&mut self) -> &mut Self {
+  pub fn use_http_server(mut self) -> Self {
```
Comment (dsherret) [inline test_util/src/builders.rs:52]: This is better. The other way was slightly annoying.

**Review by bartlomieju — APPROVED** [review]
LGTM, nice fix, I'm sure it was painful to debug it
