### PR TITLE
fix(Deno.serve): accessing .url on cloned request throws

### LINKED ISSUE #19818: Accessing .url on cloned request throws in new Deno.serve API
Minimal example:

```ts
Deno.serve((req) => new Response(req.clone().url));
```

Request:
```
curl http://localhost:8000
```

Trace:
```
TypeError: Cannot read properties of undefined (reading '0')
    at Object.url (ext:deno_fetch/23_request.js:182:32)
    at Request.get url (ext:deno_fetch/23_request.js:446:33)
    at file:///Users/qwtel/GitHub/tmp/index.ts:1:38
    at ext:deno_http/00_serve.js:530:28
    at ext:deno_http/00_serve.js:730:29
    at eventLoopTick (ext:core/01_core.js:183:11)
```

Screenshots:
Screenshot 2023-07-13 at 15 50 14

Version:
```
deno 1.35.1 (release, aarch64-apple-darwin)
v8 11.6.189.7
typescript 5.1.6
```

### PR DESCRIPTION
**Pull request by fbaltor**
This PR fixes #19818. The problem was that [the new `InnerRequest` class](https://github.com/denoland/deno/blob/aa95a3a6e04a7b0d1a06f4e149793a6970bda3aa/ext/http/00_serve.js#L125) do not initialize the fields `urlList` and `urlListProcessed` that [are used during a request clone](https://github.com/denoland/deno/blob/21c2c01ebed902c70763bb9319c3ec48c4cb5284/ext/fetch/23_request.js#L177-L178). The solution aims to be straightforward by simply initializing the missing properties during the clone process. I also implemented a ["cache"](https://github.com/denoland/deno/blob/83e8ac8fecf7e16942ece3945bb192009233bf10/ext/http/00_serve.js#L239-L241) to the `url` getter of the new `InnerRequest`, avoiding the [cost](https://github.com/fbaltor/deno/blob/aa95a3a6e04a7b0d1a06f4e149793a6970bda3aa/ext/http/00_serve.js#L243-L244) of calling `op_http_get_request_method_and_url`.

But I note that a better solution should unify the implementation of the `InnerRequest`. Currently there are at least two flavors spawned across the files `00_serve.js`, `23_request.js`, `26_fetch.js` and `01_http.js`.

### CODE REVIEW

File: ext/fetch/23_request.js [hunk 1]
```diff
@@ -174,8 +174,8 @@ function cloneInnerRequest(request, skipBody = false) {
     body,
     redirectMode: request.redirectMode,
     redirectCount: request.redirectCount,
-    urlList: request.urlList,
-    urlListProcessed: request.urlListProcessed,
+    urlList: [request.url],
```
Comment (mmastrac) [inline ext/fetch/23_request.js:177]: Should this also be request.url()?

**Review by mmastrac — CHANGES_REQUESTED** [review]
Thanks for the work on this! In general this is looking very good, but as we are changing the inner request in `23_request.js` I would like to see a bit more coverage of `.clone` in `request_test.ts` so we can be confident that it doesn't break the other paths to this code.

Could you create a few additional tests in there around requests with URLs and/or add some extra cloning tests to the tests that exist in that file?

File: ext/fetch/23_request.js (hunk 1 above)
Comment (fbaltor) [reply ext/fetch/23_request.js:177]: I used type hints to conclude this, but to be honest I'm still grasping the meaning of the `urlList` and `urlListProcessed` by reading its use in other files. Do you understand their meaning? If not, do you know someone that implemented them and could help me?

**Comment by fbaltor** [comment]
> Could you create a few additional tests in there around requests with URLs and/or add some extra cloning tests to the tests that exist in that file?

Sure thing!

File: ext/fetch/23_request.js (hunk 1 above)
Comment (mmastrac) [reply ext/fetch/23_request.js:177]: You're right actually, it's a list of closures. It should probably be `urlList: [() => request.url()]` to ensure that the `this` pointer is always bound correctly.

(ref)

```
/**
 * @param {(() => string)[]} urlList
 * @param {string[]} urlListProcessed
 */
function processUrlList(urlList, urlListProcessed) {
  for (let i = 0; i < urlList.length; i++) {
    if (urlListProcessed[i] === undefined) {
      urlListProcessed[i] = urlList[i]();
    }
  }
  return urlListProcessed;
}
```

File: cli/tests/unit/serve_test.ts [hunk 2]
```diff
@@ -2826,6 +2828,102 @@ Deno.test(
...
+      headers: { connection: "close" },
+      method: "POST",
+      body: '{"bar":true}'
+    });
+
+    ac.abort();
+    await resp.body?.cancel();
+    await server.finished;
+  },
+);
```
Comment (fbaltor) [inline cli/tests/unit/serve_test.ts:2925]: I'm having some trouble with this test. When I forcefully make it fail in the `customErrorCb` it does not throw and keep passing for some reason. It's very strange to me since the almost identical test above it does throw in the same situation.

**Comment by fbaltor** [comment]
The obvious test cases I thought of was asserting the following behavior ([as described by the spec](https://fetch.spec.whatwg.org/#dom-request-clone)):

> The clone() method steps are:
> 
> 1. If [this](https://webidl.spec.whatwg.org/#this) is [unusable](https://fetch.spec.whatwg.org/#body-unusable), then [throw](https://webidl.spec.whatwg.org/#dfn-throw) a [TypeError](https://webidl.spec.whatwg.org/#exceptiondef-typeerror).
> 
> 2. Let clonedRequest be the result of [cloning](https://fetch.spec.whatwg.org/#concept-request-clone) [this](https://webidl.spec.whatwg.org/#this)’s [request](https://fetch.spec.whatwg.org/#concept-request-request).
> 
> 3. [Assert](https://infra.spec.whatwg.org/#assert): [this](https://webidl.spec.whatwg.org/#this)’s [signal](https://fetch.spec.whatwg.org/#request-signal) is non-null.
> 
> 4. Let clonedSignal be the result of [creating a dependent abort signal](https://dom.spec.whatwg.org/#create-a-dependent-abort-signal) from « [this](https://webidl.spec.whatwg.org/#this)’s [signal](https://fetch.spec.whatwg.org/#request-signal) », using [AbortSignal](https://dom.spec.whatwg.org/#abortsignal) and [this](https://webidl.spec.whatwg.org/#this)’s [relevant realm](https://html.spec.whatwg.org/multipage/webappapis.html#concept-relevant-realm).
> 
> 5. Let clonedRequestObject be the result of [creating](https://fetch.spec.whatwg.org/#request-create) a [Request](https://fetch.spec.whatwg.org/#request) object, given clonedRequest, [this](https://webidl.spec.whatwg.org/#this)’s [headers](https://fetch.spec.whatwg.org/#request-headers)’s [guard](https://fetch.spec.whatwg.org/#concept-headers-guard), clonedSignal and [this](https://webidl.spec.whatwg.org/#this)’s [relevant realm](https://html.spec.whatwg.org/multipage/webappapis.html#concept-relevant-realm).
> 
> 6. Return clonedRequestObject.
> 

Does this make sense or you had other tests in mind, @mmastrac?

File: cli/tests/unit/serve_test.ts [hunk 3]
```diff
@@ -2826,6 +2828,102 @@ Deno.test(
...
+        ac.abort();
+        return new Response("Internal server error", { status: 500 });
+      };
+    }    
+
+    const server = Deno.serve({
+      handler: async (req) => {
+        await req.text();
+
+        req.clone();
```
Comment (mmastrac) [inline cli/tests/unit/serve_test.ts:2856]: I would suggest adding try/catch around these blocks, and asserting if it succeeds like so:

```
try {
  req.clone();
  fail("This should not have succeeded");
} catch (e) {
  assert(...)
}
```

File: cli/tests/unit/serve_test.ts (hunk 2 above)
Comment (mmastrac) [reply cli/tests/unit/serve_test.ts:2925]: It's possible that there's a bug here elsewhere in the code. If this test doesn't work as expected with the try/catch as seen above, let's add `ignore: true` and put a comment above it. We can create a follow-up issue to fix whatever that is.

File: cli/tests/unit/serve_test.ts [hunk 4]
```diff
@@ -2799,6 +2799,8 @@ Deno.test(
         const cloned = req.clone();
         assertEquals(req.headers, cloned.headers);
 
+        assertEquals(cloned.url, req.url);
```
Comment (mmastrac) [inline cli/tests/unit/serve_test.ts:2802]: Perfect!

**Review by mmastrac — APPROVED** [review]
Looks good to me. Thanks for the follow-up work!
