### PR TITLE
Prevent segfault when eval throws an error

### LINKED ISSUE #1410: deno segfaults on basic eval errors
Running a script containing just
```
eval("a")
```
causes segfault.

Here is the v8 stack trace:

```
#
# Fatal error in ../../third_party/v8/src/api-inl.h, line 123
# Debug check failed: allow_empty_handle || that != nullptr.
#
#
#
#FailureMessage Object: 0x7ffeeb20a060
==== C stack trace ===============================

    0   deno                                0x000000010589f393 v8::base::debug::StackTrace::StackTrace() + 19
    1   deno                                0x0000000105d90919 v8::platform::(anonymous namespace)::PrintStackTrace() + 41
    2   deno                                0x0000000105896025 V8_Fatal(char const*, int, char const*, ...) + 325
    3   deno                                0x0000000105895b55 v8::base::(anonymous namespace)::DefaultDcheckHandler(char const*, int, char const*) + 21
    4   deno                                0x0000000105668068 v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>) + 712
    5   deno                                0x0000000104a9a689 deno::EncodeExceptionAsJSON(v8::Local<v8::Context>, v8::Local<v8::Value>) + 1465
    6   deno                                0x0000000104a9ba40 deno::ExecuteV8StringSource(v8::Local<v8::Context>, char const*, v8::Local<v8::String>) + 336
    7   deno                                0x0000000104a9970f deno::Execute(v8::Local<v8::Context>, char const*, char const*) + 111
    8   deno                                0x0000000104a995ed deno_execute + 141
    9   deno                                0x00000001067b47e6 deno_bin::isolate::Isolate::execute2::h6583480f31299d2b + 422
    10  deno                                0x00000001067b462a deno_bin::isolate::Isolate::execute::ha53c6adc9cae7255 + 74
    11  deno                                0x00000001067dadd8 _ZN8deno_bin4main28_$u7b$$u7b$closure$u7d$$u7d$17h52d19fd56931dbefE + 40
    12  deno                                0x00000001067d7c09 _ZN8deno_bin10tokio_util4init28_$u7b$$u7b$closure$u7d$$u7d$17h4709c209a0d37cc2E + 25
    13  deno                                0x0000000106600a93 _ZN14tokio_executor6global12with_default28_$u7b$$u7b$closure$u7d$$u7d$17h5587b48aa4a33921E + 243
    14  deno                                0x000000010665970f _ZN46_$LT$std..thread..local..LocalKey$LT$T$GT$$GT$8try_with17he6ee412d025381daE + 479
    15  deno                                0x0000000106654f60 _ZN46_$LT$std..thread..local..LocalKey$LT$T$GT$$GT$4with17h295d43a9dd6879f0E + 48
    16  deno                                0x000000010660098f tokio_executor::global::with_default::h146c15736a108059 + 63
    17  deno                                0x00000001067d7b6a deno_bin::tokio_util::init::heaacdf3d2a982845 + 202
    18  deno                                0x00000001067dac28 deno_bin::main::hc88d7c6fd92b086c + 840
    19  deno                                0x0000000106647922 _ZN3std2rt10lang_start28_$u7b$$u7b$closure$u7d$$u7d$17h557d1c32670b69c8E + 18
    20  deno                                0x0000000104a31b18 std::panicking::try::do_call::hcfe6ac53944e0624.llvm.17449721543890783428 + 24
    21  deno                                0x0000000104a42f7f __rust_maybe_catch_panic + 31
    22  deno                                0x0000000104a1a4ed std::rt::lang_start_internal::hb972e1f76be57958 + 237
    23  deno                                0x0000000106647902 std::rt::lang_start::h97309960939da35b + 66
    24  deno                                0x00000001067e2892 main + 34
    25  libdyld.dylib                       0x00007fff6677b115 start + 1
    26  ???                                 0x0000000000000002 0x0 + 2
Illegal instruction: 4
```

Looks like there is some false assumption happening in `deno::EncodeExceptionAsJSON`

### PR DESCRIPTION
**Pull request by kevinkassimo**
Closes #1410

See comments on the code.

### CODE REVIEW

File: libdeno/binding.cc [hunk 1]
```diff
@@ -105,10 +105,13 @@ std::string EncodeExceptionAsJSON(v8::Local<v8::Context> context,
...
-                ->Set(context, v8_str("scriptName"),
-                      frame->GetScriptNameOrSourceURL())
-                .FromJust());
+      // scriptName can be empty in special conditions e.g. eval
+      auto scriptName = frame->GetScriptNameOrSourceURL();
+      if (scriptName.IsEmpty()) {
+        scriptName = v8_str("<unknown>");
+      }
+      CHECK(
+          frame_obj->Set(context, v8_str("scriptName"), scriptName).FromJust());
```
Comment (ry) [inline libdeno/binding.cc]: Can you please add something like this to libdeno_test.cc
```c
TEST(LibDenoTest, EncodeErrorBug) {
  Deno* d = deno_new(deno_config{0, empty, nullptr});
  EXPECT_FALSE(deno_execute(d, d, "a.js", "eval('a')"));
  EXPECT_STREQ(deno_last_exception(d),
               "{\"message\":\"Error: boo\","
               "\"frames\":[{\"line\":3,\"column\":7,"
               "\"functionName\":\"\",\"scriptName\":\"a.js\","
               "\"isEval\":false,"
               "\"isConstructor\":false,\"isWasm\":false}]}");
  deno_delete(d);
}
```

Comment (kevinkassimo) [reply libdeno/binding.cc]: Was working on an output diff test, but I guess a libdeno test sounds more reasonable...

Comment (kevinkassimo) [reply libdeno/binding.cc]: All checks finally turn green.
