### PR TITLE
fix: exclude internal JS files from coverage

### LINKED ISSUE #20447: `deno test --coverage` includes internal deno code
Noticed that the coverage output files include coverage for our internal `ext:*` modules which seems wrong.

## Steps to reproduce

1. Create a test file `foo_test.ts` with the contents:
  ```ts
  const add = (a: number, b: number) => a + b;

  Deno.test(function addTest() {
    if (add(2, 3) !== 5) {
      throw new Error("fail");
    }
  });
  ```
2. Run `deno test --coverage=cov` -> Generates way more cov files than expected

### PR DESCRIPTION
**Pull request by marvinhagemeister**
This PR changes the `deno test --coverage=...` behavior so that internal deno JS files are excluded.

Fixes #20447

### CODE REVIEW

File: cli/tools/coverage/mod.rs [hunk 1]
```diff
@@ -127,6 +127,11 @@ impl CoverageCollector {
 
     let script_coverages = self.take_precise_coverage().await?.result;
     for script_coverage in script_coverages {
+      // Filter out internal JS files from being included in coverage reports
+      if script_coverage.url.starts_with("ext:") || script_coverage.url.starts_with("[ext:") {
```
Comment (bartlomieju) [inline cli/tools/coverage/mod.rs:131]: `node:` should also be excluded

Comment (marvinhagemeister) [reply cli/tools/coverage/mod.rs:131]: Seems like this is already happening because internally `node:*` is resolved to `ext:deno_node/*`.

**Review by bartlomieju — APPROVED** [review]
Nice fix 👍
