### PR TITLE
fix(repl): don't terminate on unhandled error events

### LINKED ISSUE #15528: `reportError()` segfaults in the repl
**reproduction**: run `reportError()` with any argument in repl

**expected behavior**: argument gets printed and repl exits

**what actually happens**: process exits with SIGSEGV

### PR DESCRIPTION
**Pull request by nayeemrmn**
Fixes #15528. Note that for now, all errors in the REPL which aren't plainly `throw`n are not output to the console. This can already be seen with unhandled promise rejections.

### CODE REVIEW

File: core/ops_builtin_v8.rs [hunk 1]
```diff
@@ -712,13 +712,25 @@ fn op_destructure_error(
   JsError::from_v8_exception(scope, error.v8_value)
 }
 
+/// Effectively throw an uncatchable error. This will terminate runtime
+/// execution before any more JS code can run, except in the REPL where it
+/// should just output the error to the console.
 #[op(v8)]
-fn op_terminate(scope: &mut v8::HandleScope, exception: serde_v8::Value) {
+fn op_dispatch_exception(
```
Comment (nayeemrmn) [inline core/ops_builtin_v8.rs:719]: I renamed this because it no longer terminates in every case. Now it just represents unhandled error events.

File: core/01_core.js [hunk 2]
```diff
@@ -314,7 +314,6 @@
       error,
     ) => ops.op_abort_wasm_streaming(rid, error),
     destructureError: (error) => ops.op_destructure_error(error),
-    terminate: (exception) => ops.op_terminate(exception),
```
Comment (nayeemrmn) [inline core/01_core.js:317]: Since this was being renamed to `op_dispatch_exception`, I took the chance to just remove it and use the op directly

File: core/runtime.rs [hunk 3]
```diff
@@ -184,19 +181,18 @@ pub(crate) struct JsRuntimeState {
...
   pub(crate) shared_array_buffer_store: Option<SharedArrayBufferStore>,
   pub(crate) compiled_wasm_module_store: Option<CompiledWasmModuleStore>,
-  /// The error that was passed to an explicit `Deno.core.terminate` call.
+  /// The error that was passed to an `op_dispatch_exception` call.
   /// It will be retrieved by `exception_to_err_result` and used as an error
   /// instead of any other exceptions.
-  pub(crate) explicit_terminate_exception: Option<v8::Global<v8::Value>>,
+  // TODO(nayeemrmn): This should be a queue, mirroring `pending_promise_exceptions`.
+  // The REPL doesn't terminate on the first one and should keep track of many.
+  pub(crate) dispatched_exception: Option<v8::Global<v8::Value>>,
```
Comment (bartlomieju) [inline core/runtime.rs:189]: Could you make it a queue in this PR?

File: core/runtime.rs [hunk 4]
```diff
@@ -184,19 +181,18 @@ pub(crate) struct JsRuntimeState {
...
+  inspector: Option<Rc<RefCell<JsRuntimeInspector>>>,
```
Comment (bartlomieju) [inline core/runtime.rs:190]: Please add a comment here that Isolate must outlive Inspector

File: core/runtime.rs [hunk 5]
```diff
@@ -1152,6 +1144,10 @@ where
 }
 
 impl JsRuntimeState {
+  pub fn inspector(&self) -> Rc<RefCell<JsRuntimeInspector>> {
```
Comment (bartlomieju) [inline core/runtime.rs:1147]: Does it need to be public?

File: core/runtime.rs (hunk 4 above)
Comment (nayeemrmn) [reply core/runtime.rs:190]: I think that's not a problem any more since it's stored in runtime state which can't outlive the isolate. The reason it's coincidentally an `Option` is so it can be dropped when snapshotting, same as `global_realm: Option<JsRealm>`.

Comment (bartlomieju) [reply core/runtime.rs:190]: Okay, that makes sense. Can you address the exception queue in this PR?

File: core/runtime.rs (hunk 3 above)
Comment (nayeemrmn) [reply core/runtime.rs]: Done. I hesitated because I figured the polling should be moved to somewhere proper first rather than giving `exception_to_err_result()` a side-effect, but I guess `Option` has the same problem..

**Review by bartlomieju — APPROVED** [review]
LGTM, thank you Nayeem
