### PR TITLE
fix: trim space around DENO_AUTH_TOKENS

### LINKED ISSUE #25043: DENO_AUTH_TOKEN does not work, when it contains an extra \n at the end
Version: Deno 1.45.5

1. Create an otherwise valid bearer token, and set it as an env var, but with an extra newline at the end
   ```
   export DENO_AUTH_TOKENS=$'github_pat_xxxxxxxxxxxxxxxxxxx@raw.githubusercontent.com\n'
   ```
1. Do a `deno cache --reload https://raw.githubusercontent.com/pihentagy/some-private-repo/main/main.ts`
1. Watch it fail with a misleading error:
   ```
   error: Module not found "https://raw.githubusercontent.com/pihentagy/some-private-repo/main/main.ts".
   ```
   
Ran into that issue when setting the env var via gitlab variable btw.

### PR DESCRIPTION
**Pull request by lucacasonato**
Fixes #25043

### CODE REVIEW

File: cli/auth_tokens.rs [hunk 1]
```diff
@@ -211,6 +211,23 @@ mod tests {
     );
   }
 
+  #[test]
+  fn test_auth_tokens_space() {
+    let auth_tokens = AuthTokens::new(Some(
+      " abc123@deno.land;def456@example.com\t".to_string(),
```
Comment (marvinhagemeister) [inline cli/auth_tokens.rs:217]: Let's add a test with `\n` at the end like in the original issue report.

**Review by marvinhagemeister — APPROVED** [review]
