### PR TITLE
fix(upgrade): Added error message when using canary option with M1

### LINKED ISSUE #16221: Can not install canary on aarch64 macOS
Version: macOS Monterey 12.6

```
ME ~ % deno upgrade --canary
Looking up latest version
Found latest version a622c5df27e908bff152ce7374c47dabfdba0bba
Checking https://dl.deno.land/canary/a622c5df27e908bff152ce7374c47dabfdba0bba/deno-aarch64-apple-darwin.zip
Download could not be found, aborting
```

### PR DESCRIPTION
**Pull request by ydoi**
fix #16221 

before
```
Looking up latest version
Found latest version 8c9e6c5565c1c00437d083de76cdd944e44b1d99
Checking https://dl.deno.land/canary/8c9e6c5565c1c00437d083de76cdd944e44b1d99/deno-aarch64-apple-darwin.zip
Download could not be found, aborting
```

after
```
Looking up latest canary version
Found latest version 8c9e6c5565c1c00437d083de76cdd944e44b1d99
error: Canary builds are not available for M1
```

### CODE REVIEW

File: cli/tools/upgrade.rs [hunk 1]
```diff
@@ -21,6 +21,9 @@ use std::path::PathBuf;
 use std::process::Command;
 use std::time::Duration;
 
+if env!("TARGET") == "aarch64-apple-darwin" {
+  bail!("Canary builds are not available for M1");
+}
```
Comment (dsherret) [inline cli/tools/upgrade.rs:26]: This should be moved into the `upgrade` function below as this won't compile.

**Review by dsherret — CHANGES_REQUESTED** [review]

File: cli/tools/upgrade.rs (hunk 1 above)
Comment (ydoi) [reply cli/tools/upgrade.rs]: Thanks for your comment.
Moved to upgrade function.

**Review by bartlomieju — APPROVED** [review]
LGTM, thanks
