### PR TITLE
fix(ext/node): lossy UTF-8 read node_modules files

### LINKED ISSUE #24027: fails to import a module because of invalid utf8 sequence from npm packages
Original issue https://github.com/denoland/deno/issues/23911

The original issue was not fixed by the pr https://github.com/denoland/deno_graph/pull/483

```js
import {} from "npm:js-clipper@1.0.1";
```

the minimal reproduction was fixed, I'm suspecting that when importing from npm packages there is another decode path at play that still doesn't handle utf8

### PR DESCRIPTION
**Pull request by lucacasonato**
Previously various reads of files in `node_modules` would error on invalid UTF-8. These were cases involving:

- reading package.json from Rust
- reading package.json from JS
- reading CommonJS files from JS
- reading CommonJS files from Rust (for ESM translation)
- reading ESM files from Rust

There are tests for all these cases now.

Fixes #24027

Needs https://github.com/denoland/deno_core/pull/773 to land first.

### CODE REVIEW

File: cli/resolver.rs [hunk 1]
```diff
@@ -320,7 +320,12 @@ impl NpmModuleLoader {
 
     let code = if self.cjs_resolutions.contains(specifier) {
       // translate cjs to esm if it's cjs and inject node globals
-      let code = String::from_utf8(code)?;
+      let code = match String::from_utf8_lossy(&code) {
+        Cow::Owned(code) => code,
+        // SAFETY: `String::from_utf8_lossy` guarantees that the result is valid
+        // UTF-8 if `Cow::Borrowed` is returned.
+        Cow::Borrowed(_) => unsafe { String::from_utf8_unchecked(code) },
+      };
```
Comment (dsherret) [inline cli/resolver.rs:328]: It's surprising there isn't a version of this on `String`.

**Review by dsherret — APPROVED** [review]
Nice. LGTM

File: cli/resolver.rs (hunk 1 above)
Comment (lucacasonato) [reply cli/resolver.rs:328]: Yeah... I have to reimplement this helper frequently 🥲

Maybe I should make a PR to the standard library.
