### PR TITLE
fix(unstable): move sloppy-import warnings to lint rule

### LINKED ISSUE #22844: Move sloppy import warnings to lint rule
Like the title says: Passing `--unstable-sloppy-imports` should disable sloppy import warnings. My console is getting spammed with these when running a node project with Deno.

Version: Deno 1.41.1

### PR DESCRIPTION
**Pull request by dsherret**
Adds a new `no-sloppy-imports` lint rule and cleans up the lint code.

Closes #22844
Closes https://github.com/denoland/deno_lint/issues/1293

### CODE REVIEW

File: cli/tools/lint/linter.rs [hunk 1]
```diff
@@ -0,0 +1,242 @@
...
+        crate::cache::CACHE_PERM,
+      )
+      .context("Failed writing fix to file.")?;
+    }
+
+    Ok((source, diagnostics))
+  }
+}
+
+fn apply_lint_fixes_and_relint(
```
Comment (dsherret) [inline cli/tools/lint/linter.rs:182]: Moved from cli/tools/mod.rs

File: cli/tools/lint/linter.rs [hunk 2]
```diff
@@ -0,0 +1,242 @@
...
+  }
+
+  fn lint_file_and_fix(
+    &self,
+    specifier: &ModuleSpecifier,
+    media_type: MediaType,
+    source_code: String,
+    file_path: &Path,
+  ) -> Result<(ParsedSource, Vec<LintDiagnostic>), deno_core::anyhow::Error> {
+    // initial lint
```
Comment (dsherret) [inline cli/tools/lint/linter.rs:122]: Contents moved from cli/tools/lint/mod.rs

File: cli/tools/lint/linter.rs [hunk 3]
```diff
@@ -0,0 +1,242 @@
...
+      .linter
+      .lint_with_ast(parsed_source, self.deno_lint_config.clone())
+  }
+
+  pub fn lint_file(
+    &self,
+    file_path: &Path,
+    source_code: String,
+  ) -> Result<(ParsedSource, Vec<LintDiagnostic>), AnyError> {
+    let specifier = specifier_from_file_path(file_path)?;
```
Comment (dsherret) [inline cli/tools/lint/linter.rs:97]: Contents moved from cli/tools/lint/mod.rs

File: cli/tools/lint/linter.rs [hunk 4]
```diff
@@ -0,0 +1,242 @@
...
+      }),
+      deno_lint_config: options.deno_lint_config,
+    }
+  }
+
+  pub fn has_package_rules(&self) -> bool {
+    !self.package_rules.is_empty()
+  }
+
+  pub fn lint_package(
```
Comment (dsherret) [inline cli/tools/lint/linter.rs:71]: This is also incrementally working towards having these lint rules show up in the lsp.

File: cli/resolver.rs [hunk 5]
```diff
@@ -1012,11 +932,13 @@ impl SloppyImportsResolver {
 
     fn media_types_to_paths(
       path_no_ext: &str,
+      original_media_type: MediaType,
       probe_media_type_types: Vec<MediaType>,
       reason: SloppyImportsResolutionReason,
     ) -> Vec<(PathBuf, SloppyImportsResolutionReason)> {
       probe_media_type_types
         .into_iter()
+        .filter(|media_type| *media_type != original_media_type)
```
Comment (dsherret) [inline cli/resolver.rs:941]: Fixes a bug with sloppy imports.

File: cli/tools/lint/rules/mod.rs [hunk 6]
```diff
@@ -0,0 +1,296 @@
...
+pub struct LintRuleProvider {
+  sloppy_imports_resolver: Option<Arc<SloppyImportsResolver>>,
+  workspace_resolver: Option<Arc<WorkspaceResolver>>,
+}
+
+impl LintRuleProvider {
+  pub fn new(
+    sloppy_imports_resolver: Option<Arc<SloppyImportsResolver>>,
+    workspace_resolver: Option<Arc<WorkspaceResolver>>,
+  ) -> Self {
```
Comment (bartlomieju) [inline cli/tools/lint/rules/mod.rs:155]: Consider doing options object instead

File: cli/tools/lint/mod.rs [hunk 7]
```diff
@@ -271,18 +272,27 @@ impl WorkspaceLinter {
...
+          &state,
+          &paths,
+        ))
+      });
+
+    let linter = Arc::new(CliLinter::new(CliLinterOptions {
+      configured_rules: lint_rules,
+      fix: lint_options.fix,
+      deno_lint_config: lint_config,
+    }));
```
Comment (bartlomieju) [inline cli/tools/lint/mod.rs:292]: It's most likely a problem for another time, but we're gonna have a lot of "fun" with this abstraction if we start supporting plugins. Again, a problem for another time.

File: cli/tools/lint/rules/no_sloppy_imports.md [hunk 8]
```diff
@@ -0,0 +1,20 @@
...
+
+Non-explicit specifiers are ambiguous and require probing for the correct file
+path on every run, which has a performance overhead.
+
+Note: This lint rule is only active when using `--unstable-sloppy-imports`.
+
+### Invalid:
+
+```typescript
+import { add } from "./math/add";
```
Comment (bartlomieju) [inline cli/tools/lint/rules/no_sloppy_imports.md:11]: Cool that this will be showed in doc help output, but it won't be shown on https://lint.deno.land/. Any ideas how we could do that?

Comment (bartlomieju) [reply cli/tools/lint/rules/no_sloppy_imports.md:11]: Actually I think we don't have markdown help text output for specific rules anymore in the `deno` binary...

**Review by bartlomieju — COMMENTED** [review]
A few comments, but overall looks good to me 👍

File: cli/tools/lint/rules/mod.rs (hunk 6 above)
Comment (dsherret) [reply cli/tools/lint/rules/mod.rs:155]: The "rule" I've been following is an options object for configuration settings and then just regular parameters for "service structs". That also makes it easier to implement `Default` for the options object (though in this case that wouldn't be a problem because both parameters happen to be optional). I don't think introducting explanatory options is that helpful in this scenario.

File: cli/tools/lint/mod.rs (hunk 7 above)
Comment (dsherret) [reply cli/tools/lint/mod.rs:292]: I don't think this makes that any harder. Maybe easier.

File: cli/tools/lint/rules/no_sloppy_imports.md (hunk 8 above)
Comment (dsherret) [reply cli/tools/lint/rules/no_sloppy_imports.md:11]: I think we need to move lint.deno.land out of the deno_lint repo and have it automatically update on publish of the CLI. I opened https://github.com/denoland/deno_lint/issues/1300

**Review by nayeemrmn — APPROVED** [review]
LGTM

**Review by marvinhagemeister — APPROVED** [review]
Nice, really looking forward to this!
