### PR TITLE
fix(ext/fetch): clone second branch chunks in Body.clone()

### LINKED ISSUE #10994: Use structuredClone for teed ReadableStreams in Response.clone
See https://staging.wpt.fyi/results/fetch/api/response/response-clone.any.html?label=master&product=deno&product=servo&product=chrome

### PR DESCRIPTION
**Pull request by marcosc90**
This PR makes `Body.clone()` spec compliant: https://fetch.spec.whatwg.org/#concept-body-clone

> 1, Let « out1, out2 » be the result of [teeing](https://streams.spec.whatwg.org/#readablestream-tee) body’s [stream](https://fetch.spec.whatwg.org/#concept-body-stream).
> ...
> To tee a [ReadableStream](https://streams.spec.whatwg.org/#readablestream) stream, return ? [ReadableStreamTee](https://streams.spec.whatwg.org/#readable-stream-tee)(stream, true).

---
Closes #10994

### CODE REVIEW

File: ext/web/06_streams.js [hunk 1]
```diff
@@ -9,6 +9,7 @@
 const core = globalThis.Deno.core;
 const ops = core.ops;
 import * as webidl from "ext:deno_webidl/00_webidl.js";
+import { structuredClone } from "ext:deno_web/02_structured_clone.js";
```
Comment (marcosc90) [inline ext/web/06_streams.js:12]: Are we using `02_structured_clone` or `13_message_port` one?

https://github.com/denoland/deno/blob/72d9f0609094adee954b271db12ca4c834f6b860/ext/web/13_message_port.js#L332

**Review by bartlomieju — COMMENTED** [review]
@crowlKats please take a look as you're more knowledgable about this part of the codebase

File: ext/web/06_streams.js (hunk 1 above)
Comment (crowlKats) [reply ext/web/06_streams.js:12]: its fine to use 02

**Review by crowlKats — APPROVED** [review]
LGTM!
