### PR TITLE
fix(#10815): lsp only responds to formatting for md, json, jsonc

### LINKED ISSUE #10815: lsp: Hover info and completions in markdown files
Since 1.10.3 and VSC extension 3.5.0, I am getting hover info, completions, semantic highlighting and some other stuff from the deno TS service in markdown files.

### PR DESCRIPTION
**Pull request by kitsonk**
Fixes #10815

This refactors how we determine if we respond to diagnostics, using what is provided by the language server client and doesn't respond for "diagnostic" related APIs for markdown JSON, JSONC.

ping @satyarohith

### CODE REVIEW

File: cli/file_fetcher.rs [hunk 1]
```diff
@@ -178,33 +178,7 @@ pub fn map_content_type(
...
-      "application/json" | "text/json" => MediaType::Json,
-      "application/wasm" => MediaType::Wasm,
-      // Handle plain and possibly webassembly
-      "text/plain" | "application/octet-stream" => MediaType::from(specifier),
-      _ => {
-        debug!("unknown content type: {}", content_type);
-        MediaType::Unknown
-      }
-    };
+    let media_type = MediaType::from_content_type(specifier, content_type);
```
Comment (kitsonk) [inline cli/file_fetcher.rs:181]: `MediaType` didn't actually properly handle data URLs, and this logic was buried in file fetcher and should actually be part of `MediaType`.

File: cli/file_fetcher.rs [hunk 2]
```diff
@@ -216,55 +190,6 @@ pub fn map_content_type(
   }
 }
 
-/// Used to augment media types by using the path part of a module specifier to
-/// resolve to a more accurate media type.
-fn map_js_like_extension(
```
Comment (kitsonk) [inline cli/file_fetcher.rs:221]: Again, this logic, specific to `MediaType` was moved to `cli/media_type.rs`.

**Review by lucacasonato — APPROVED** [review]
LGTM!
