### PR TITLE
cli: handle deno -v and deno --version

### LINKED ISSUE #2652: Expose version also as --version
On Deno

```
deno: 0.12.0
v8: 7.7.200
typescript: 3.5.1
```

Running `deno version` works but `deno --version` doesn't.

It is quite a common pattern for unix commands to provide `--help` (that works in Deno) and `--version` (that currenty doesn't works in Deno).

I think that `deno --version` not working as one would expect could lead to a worse user experience.

### PR DESCRIPTION
**Pull request by bartlomieju**
Closes #2652

### CODE REVIEW

File: cli/flags.rs [hunk 1]
```diff
@@ -140,6 +140,17 @@ To evaluate code from the command line:
...
   deno help run")
+    .arg(
+      Arg::with_name("version")
+        .short("v")
+        .long("version")
+        .help("Print the version")
+        .long_help("Print current version of Deno.
+
+Includes versions of Deno, V8 JavaScript Engine, and the TypeScript
+compiler.",
```
Comment (ry) [inline cli/flags.rs]: The long_help doesn’t seem very useful. Can it be removed?

File: cli/flags.rs [hunk 2]
```diff
@@ -853,6 +856,28 @@ mod tests {
...
+      flags,
+      DenoFlags {
+        version: true,
+        ..DenoFlags::default()
+      }
+    );
+    assert_eq!(subcommand, DenoSubcommand::Version);
+    assert_eq!(argv, svec!["deno"]);
+
+    let (flags, subcommand, argv) = flags_from_vec(svec!["deno", "-v"]);
```
Comment (ry) [inline cli/flags.rs]: 👍

**Comment by bartlomieju** [comment]
@ry updated
