### PR TITLE
fix(core): allow esm extensions not included in snapshot

### LINKED ISSUE #18979: `deno_runtime`'s `WorkerOptions::extensions` breaks with esm extensions
```rust
deno_core::extension!(hello_runtime, esm = ["hello_runtime_bootstrap.js"]);

let mut worker = MainWorker::bootstrap_from_options(
  main_module.clone(),
  PermissionsContainer::allow_all(),
  WorkerOptions {
    module_loader: Rc::new(FsModuleLoader),
    extensions: vec![hello_runtime::init_ops_and_esm()],
    ..Default::default()
  },
);
```
fails on bootstrap when trying to load `ext:path/hello_runtime_bootstrap.js`. This occurs when `JsRuntime` is given a startup snapshot and an extension with esm which isn't included in that snapshot.

### PR DESCRIPTION
**Pull request by nayeemrmn**
Fixes #18979.

This changes the predicate for allowing `ext:` specifier resolution from `snapshot_loaded_and_not_snapshotting` to `ext_resolution_allowed` which is only set to true during the extension module loading phase. Module loaders as used in core
are now declared as `ExtModuleLoader` rather than `dyn ModuleLoader`.

### CODE REVIEW

File: core/runtime.rs [hunk 1]
```diff
@@ -622,6 +594,8 @@ impl JsRuntime {
     js_runtime.init_extension_ops().unwrap();
     let realm = js_runtime.global_realm();
     js_runtime.init_extension_js(&realm).unwrap();
+    *loaded_extensions.borrow_mut() = true;
+    js_runtime.module_map.as_ref().unwrap().borrow_mut().loader = loader;
```
Comment (nayeemrmn) [inline core/runtime.rs:598]: After extensions are initialised, this unsets `ExtModuleLoader` in favour of the user's loader. I think we should have a concrete `CoreModuleLoader` which always wraps the user's loader. Then we can declare it concretely instead of stacking two `dyn ModuleLoader`. That way we can remove `resolve_helper()` and not have to pass around `loaded_extensions`.

File: bench_util/js_runtime.rs [hunk 2]
```diff
@@ -10,9 +10,7 @@ use crate::profiling::is_profiling;
 pub fn create_js_runtime(setup: impl FnOnce() -> Vec<Extension>) -> JsRuntime {
   JsRuntime::new(RuntimeOptions {
     extensions: setup(),
-    module_loader: Some(
-      std::rc::Rc::new(deno_core::ExtModuleLoader::default()),
-    ),
+    module_loader: Some(std::rc::Rc::new(deno_core::NoopModuleLoader)),
```
Comment (bartlomieju) [inline bench_util/js_runtime.rs:13]: This is the default so maybe it could be removed altogether?

File: cli/tests/testdata/run/extension_dynamic_import.ts.out [hunk 3]
```diff
@@ -1,4 +1,4 @@
-error: Uncaught TypeError: Cannot load extension module from external code
+error: Uncaught (in promise) TypeError: Cannot load extension module from external code
```
Comment (bartlomieju) [inline cli/tests/testdata/run/extension_dynamic_import.ts.out:1]: Sweet, this is more correct 👍

File: core/modules.rs [hunk 4]
```diff
@@ -3042,48 +2988,28 @@ if (import.meta.url != 'file:///main_with_code.js') throw Error();
...
-    assert_eq!(
-      resolve_helper(
-        true,
-        Rc::new(loader),
-        "ext:core.js",
-        "file://bar",
-        ResolutionKind::Import,
-      )
-      .err()
-      .map(|e| e.to_string()),
```
Comment (bartlomieju) [inline core/modules.rs:3086]: Can you move these two checks to a separate test case?

File: core/runtime.rs [hunk 5]
```diff
@@ -722,7 +692,13 @@ impl JsRuntime {
       JsRealm::new(v8::Global::new(scope, context))
     };
 
+    if let Some(m) = self.module_map.as_ref() {
+      m.borrow().loader.allow_ext_resolution();
+    }
```
Comment (bartlomieju) [inline core/runtime.rs:697]: I believe these should be `.unwrap()` here - if module_map is not present during realm creation it's an internal bug.

File: core/runtime.rs [hunk 6]
```diff
@@ -863,23 +839,15 @@ impl JsRuntime {
   /// Initializes ops of provided Extensions
   fn init_extension_ops(&mut self) -> Result<(), Error> {
     let op_state = self.op_state();
-    // Take extensions to avoid double-borrow
-    {
-      let mut extensions: Vec<Extension> = std::mem::take(&mut self.extensions);
```
Comment (bartlomieju) [inline core/runtime.rs:868]: Huh, nice that you cleaned it up

**Review by bartlomieju — COMMENTED** [review]
This is a great cleanup, you simplified this subsystem a lot. I got a few minor concerns

**Review by bartlomieju — APPROVED** [review]
LGTM, thank you @nayeemrmn. Great work!
