### PR TITLE
fix(node): improve error message requiring non-npm es module

### LINKED ISSUE #16913: `ERR_REQUIRE_ESM` error code is missing errors resulting from `require`ing esm files
Babel tests this here:

https://github.com/babel/babel/blob/859daa3c185d18901106d8e6c39898ba1ce8e8f4/packages/babel-core/src/config/files/module-types.ts#LL39C25-L39C40

The error type mapping is not working correctly between Rust and JS here:

```
Error 'could not find npm package for 'file:///Users/lucacasonato/projects/local/babeltest/babel.config.js'' contains boxed error of unknown type:
  "could not find npm package for 'file:///Users/lucacasonato/projects/local/babeltest/babel.config.js'"
Error: could not find npm package for 'file:///Users/lucacasonato/projects/local/babeltest/babel.config.js'
    at Object.Module._extensions..js (deno:ext/node/02_require.js:745:28)
    at Module.load (deno:ext/node/02_require.js:643:34)
    at Function.Module._load (deno:ext/node/02_require.js:500:14)
    at Module.require (deno:ext/node/02_require.js:665:21)
    at require (deno:ext/node/02_require.js:799:18)
    at startHiding - secret - don't use this - v1 (file:///Users/lucacasonato/Library/Caches/deno/npm/registry.npmjs.org/@babel/core/7.20.5/lib/errors/rewrite-stack-trace.js:55:12)
    at loadCjsDefault (file:///Users/lucacasonato/Library/Caches/deno/npm/registry.npmjs.org/@babel/core/7.20.5/lib/config/files/module-types.js:77:69)
    at loadCjsOrMjsDefault (file:///Users/lucacasonato/Library/Caches/deno/npm/registry.npmjs.org/@babel/core/7.20.5/lib/config/files/module-types.js:55:16)
    at loadCjsOrMjsDefault.next (<anonymous>)
    at readConfigJS (file:///Users/lucacasonato/Library/Caches/deno/npm/registry.npmjs.org/@babel/core/7.20.5/lib/config/files/configuration.js:86:47)
```

The first message is logged because the error type in Rust has no JS mapping - this is probably also why the code is missing.

### LINKED ISSUE #19842: More helpful error message when requiring a module that fails to parse with require?
When `require` fails to parse a module, perhaps it should say what file it failed to parse?

For example:

```
// main.ts
import { createRequire } from "node:module";

const require = createRequire(import.meta.url);

console.log(require("./other.ts"));

// other.ts
import "./somethingElse.ts"
```

It will error with just:

```
error: Uncaught SyntaxError: Cannot use import statement outside a module
    at Object.evalContext (ext:core/01_core.js:842:14)
    at wrapSafe (node:module:696:27)
    at Module._compile (node:module:706:29)
    at Object.Module._extensions..js (node:module:738:12)
    at Module.load (node:module:653:34)
    at Function.Module._load (node:module:535:16)
    at Module.require (node:module:672:23)
    at require (node:module:772:20)
    at ...etc.../main.ts:1:7
```

It would be useful if it said that it failed to parse other.ts and provide that path.

### PR DESCRIPTION
**Pull request by dsherret**
Closes #19842
Closes #16913

### CODE REVIEW

File: ext/node/polyfills/01_require.js [hunk 1]
```diff
@@ -994,25 +1002,28 @@ Module._extensions[".js"] = function (module, filename) {
...
 
   if (parent) {
     message += ` from ${parent}`;
   }
 
   message +=
     ` not supported. Instead change the require to a dynamic import() which is available in all CommonJS modules.`;
-  return message;
+  const err = new Error(message);
+  err.code = "ERR_REQUIRE_ESM";
```
Comment (dsherret) [inline ext/node/polyfills/01_require.js:1025]: Fixes https://github.com/denoland/deno/issues/16913 properly this time.

That said, in the future we should go through and rewrite all these errors to be more similar to what Node does.

**Review by bartlomieju — APPROVED** [review]
LGTM
