### PR TITLE
fix(publish): vite import.meta.hot not type checking

### LINKED ISSUE #32126: `deno publish` fails with type error, `deno check` is ok
See https://github.com/denoland/fresh/actions/runs/21907315275/job/63250964994

## Steps to reproduce

1. Clone https://github.com/denoland/fresh
2. Run `git checkout 2.2.1`
3. Run `deno publish --dry-run` -> Error

Output:

```sh
TS2339 [ERROR]: Property 'hot' does not exist on type 'ImportMeta'.
if (import.meta.hot) {
                ~~~
    at file:///Users/marvinh/dev/denoland/fresh/packages/plugin-vite/src/client.ts:14:17

TS2339 [ERROR]: Property 'hot' does not exist on type 'ImportMeta'.
  import.meta.hot.on("fresh:reload", () => {
              ~~~
    at file:///Users/marvinh/dev/denoland/fresh/packages/plugin-vite/src/client.ts:15:15

TS2339 [ERROR]: Property 'hot' does not exist on type 'ImportMeta'.
  import.meta.hot.on("vite:beforeUpdate", (module: UpdatePayload) => {
              ~~~
    at file:///Users/marvinh/dev/denoland/fresh/packages/plugin-vite/src/client.ts:19:15

Found 3 errors.

error: Type checking failed.

  info: The program failed type-checking, but it still might work correctly.
  hint: Re-run with --no-check to skip type-checking.
```

But running `deno check` passes. Only `deno publish` breaks. Seems like something is different during type checking there.

Version: Deno 2.6.9

### PR DESCRIPTION
**Pull request by marvinhagemeister**
Ambient types from `compilerOptions.types` need to be available during
`deno publish` type checking.

## Problem

`create_publish_graph()` passes `imports: Vec::new()`, excluding all
tsconfig imports. The `to_graph_imports()` method on
`CompilerOptionsResolver` includes both:

1. `tsconfig.json` `files` entries (should be excluded from publish)
2. `compilerOptions.types` entries (should be included for type checking)

By excluding everything, ambient types from `compilerOptions.types` are
unavailable during publish's type checking, causing errors for code that
depends on type augmentations (e.g. Vite's `import.meta.hot`).

## Solution

- Add `to_compiler_options_types_imports()` on `CompilerOptionsResolver`
  that returns only `compilerOptions.types` entries, excluding tsconfig
  `files` entries. Refactor `to_graph_imports()` to reuse it internally.
- In `create_publish_graph`, clone the publish graph and extend it with
  the types imports for type checking, keeping the publish graph itself
  clean (types `.d.ts` files are not included in published output).
- Add both a positive test (publish succeeds with types) and a negative
  test (publish type-checking fails without types, confirming the fix is
  load-bearing).

Closes #32126

### CODE REVIEW

File: libs/resolver/deno_json.rs [hunk 1]
```diff
@@ -1537,6 +1537,31 @@ impl CompilerOptionsResolver {
     }
   }
 
+  #[cfg(feature = "graph")]
+  pub fn to_compiler_options_types_imports(
```
Comment (dsherret) [inline libs/resolver/deno_json.rs:1590]: Is this necessary? There already exists an to_graph_imports function right below.

File: cli/graph_util.rs [hunk 2]
```diff
@@ -513,8 +513,10 @@ impl ModuleGraphCreator {
         is_dynamic: false,
         graph_kind: deno_graph::GraphKind::All,
         roots,
-        // do not include the tsconfig imports for `deno publish`
-        imports: Vec::new(),
+        // include compilerOptions.types but not tsconfig files for publish
+        imports: self
+          .module_graph_builder
+          .resolve_compiler_options_types_imports(deno_graph::GraphKind::All),
```
Comment (dsherret) [inline cli/graph_util.rs]: What do the other subcommands do? Can we copy that?

File: libs/resolver/deno_json.rs (hunk 1 above)
Comment (marvinhagemeister) [reply libs/resolver/deno_json.rs:1590]: Good find, yeah that seems to work too.

**Comment by kajukitli** [comment]
looks good to me. preserving `compilerOptions.types` for publish type-checking while still excluding tsconfig `files` is the right split, and this fixes the `import.meta.hot` case without broadening publish inputs in the wrong way.

**Comment by bartlomieju** [comment]
This isn't quite right -- the PR doesn't actually split `compilerOptions.types` from tsconfig `files`. `maybe_resolve_ts_config_imports` calls `to_graph_imports()` which returns **both** (see `libs/resolver/deno_json.rs:1593-1607`). It works in practice because `deno.json` configs don't typically have tsconfig `files` entries, but the separation described here isn't implemented.

**Comment by bartlomieju** [comment]
Addressed feedback in fb776d2c9:

1. **Deduplication**: Refactored `to_graph_imports()` to call `to_compiler_options_types_imports()` internally instead of duplicating the types-handling loop.
2. **Else branch clone**: Acknowledged, no change needed -- the non-types path is unchanged.
3. **npm-style types entries**: Not a new concern since `to_graph_imports()` already had the same pattern. The graph resolver handles npm specifiers.
4. **Negative test**: Added `types_missing` test case that verifies publish type-checking fails with `TS2339: Property 'hot' does not exist on type 'ImportMeta'` when `compilerOptions.types` is absent. Confirms the fix is load-bearing.
5. **Double `Check` in output**: Expected behavior -- first check is type-checking, second is slow types analysis. Not adding a comment to the `.out` file since the pattern is used across many publish tests.
