### PR TITLE
fix(cli/console): quote object string keys that are invalid identifiers

### LINKED ISSUE #7548: Inspect should quote non-simple object keys
This is a follow-on from https://github.com/denoland/deno/issues/7532 where I noticed Deno is not doing what I expected for object keys.

In node we get this:

```console
> ({ "foo\b": 1, "bar": 2 })
{ 'foo\b': 1, bar: 2 }
```

While in deno (latest commit, https://github.com/denoland/deno/commit/e4188f7dfb95ad16750874dd2cdd4a80b48b1ecc) we get this:

```console
> ({ "foo\b": 1, "bar": 2 })
{ foo\b: 1, bar: 2 }
```

I think we essentially need to detect when object keys would be valid unquoted keys in a JS object literal, and otherwise quote them.

cc @caspervonb

### PR DESCRIPTION
**Pull request by caspervonb**
Fixes #7548

### CODE REVIEW

File: cli/rt/02_console.js [hunk 1]
```diff
@@ -469,6 +469,15 @@
       );
   }
 
+  // Surround a string with quotes when it is required (e.g the string not a valid identifier).
+  function maybeQuoteString(string) {
+    if (/^[a-zA-Z_][a-zA-Z_0-9]*$/.test(string)) {
```
Comment (caspervonb) [inline cli/rt/02_console.js:474]: Technically we could be more permissive than this but this matches what Node does as far as I can tell.

**Review by ry — APPROVED** [review]
LGTM - thanks
