### PR TITLE
fix(cli) implicit conversion from path to url

### LINKED ISSUE #6401: regression: path containing `:` in first segment breaks filesystem APIs
Deno 1.0.5
```
$ deno eval "Deno.lstatSync('abc:def')"
error: Uncaught NotFound: No such file or directory (os error 2)
    at unwrapResponse ($deno$/ops/dispatch_json.ts:43:11)
    at Object.sendSync ($deno$/ops/dispatch_json.ts:72:10)
    at Object.lstatSync ($deno$/ops/fs/stat.ts:77:15)
    at file:///mnt/f9/tests/__$deno$eval.ts:1:6
```

Deno 1.1.0
```
$ deno eval "Deno.lstatSync('abc:def')"
error: Uncaught TypeError: Must be a path string or file URL.
    at Object.pathFromURL ($deno$/util.ts:120:13)
    at Object.lstatSync ($deno$/ops/fs/stat.ts:79:10)
    at file:///mnt/f9/tests/__$deno$eval.ts:1:6
```

This most likely introduced by #5990

### PR DESCRIPTION
**Pull request by caspervonb**
This removes any implicit conversion from file-paths to URLs.

Fixes #6401

### CODE REVIEW

File: cli/js/util.ts [hunk 1]
```diff
@@ -110,14 +110,9 @@ function pathFromURLPosix(url: URL): string {
 }
 
 export function pathFromURL(pathOrUrl: string | URL): string {
```
Comment (actual-size) [inline cli/js/util.ts:112]: I think this method attempting to parse strings as URLs makes sense, given the name of the function. (plus, even though this is not part of the public API, returning any string unchanged is sorta weird)

The fix should be in all the methods that use pathFromURL unconditionally, I'll add another comment to where I'm referring

Comment (actual-size) [reply cli/js/util.ts:112]: @caspervonb I don't know exactly what that reaction means, it could just be disagreement, but in case I didn't explain myself well:

As of this PR, `openSync` (and all fs methods that can take a file URL) takes either a string, which is always a path, or a URL. If it is a URL then `pathFromUrl` will work as expected. If it is a string then it is still passed into `pathFromURL` which does nothing except return it back out.

What my comment was aiming at is that I think that the fs methods should only call `pathFromURL` when passed a URL, since we know passing a string into it won't do anything.

Comment (caspervonb) [reply cli/js/util.ts:112]: > I think this method attempting to parse strings as URLs makes sense

It's path from URL; if its already a path then no just return, no?

> What my comment was aiming at is that I think that the fs methods should only call pathFromURL when passed a URL, since we know passing a string into it won't do anything.

Yeah I just went for removing the offending code rather than starting on a refactoring trip introducing more code.

Comment (actual-size) [reply cli/js/util.ts:112]: Yeah fair enough on that. I was mostly just concerned that if you just look at the fs methods it looks like we're still parsing everything into paths. I guess it still makes sense this way 👍

**Comment by caspervonb** [comment]
Closing in favor of https://github.com/denoland/deno/pull/6478

**Comment by bartlomieju** [comment]
This PR is fine, we should just fix the bug instead of reverting this useful feature.

**Comment by bartlomieju** [comment]
I familiarised myself better with this piece of code and I don't really understand why any processing or validation (`pathFromURL`, `pathFromURLPosix` and `pathFromURLWin32`) is done in JS instead of Rust... 

This issue could be handled by sending either `path` or `path_url` (taken from `url.href`) to Rust and parsing using `url::Url`. @ry WDYT?

**Comment by caspervonb** [comment]
> Please add some more tests for Deno.open that use both string and URL argument. I'd be best if you could incorporate failing cases from #6401

Testing that legal file paths don't get interpreted as urls when we no longer interpret strings as urls seems moot? Added an itest, pretty sure this will fail on windows tho as its testing unix behaviour.

**Comment by caspervonb** [comment]
Adding the test fixtures blows up the CI on Windows where it cannot even checkout the repository so reverted
