### PR TITLE
fix(cli): add hygiene pass to transpile pipeline

### LINKED ISSUE #8412: Deno.transpileOnly(...) produces faulty code on decorator chain
`test-with-decorators.ts`
```javascript
function A() {
  console.log("@A evaluated");
  return function (
    target: any,
    propertyKey: string,
    descriptor: PropertyDescriptor,
  ) {
    console.log("@A called");
    const fn = descriptor.value;
    descriptor.value = function() {
      console.log("fn() called from @A");
      fn();  
    };
  };
}

function B() {
  console.log("@B evaluated");
  return function (
    target: any,
    propertyKey: string,
    descriptor: PropertyDescriptor,
  ) {
    console.log("@B called");
    const fn = descriptor.value;
    descriptor.value = function() {
      console.log("fn() called from @B");
      fn();  
    };
  };
}

class C {
  @A()
  @B()
  static test() {
    console.log("C.test() called");
  }
}

C.test();
```
See the error as decorator `A()` isn't getting called (`denopack` uses `Deno.transpileOnly()` by default):
```sh
denopack -i test-with-decorators.ts -o bundle.js
denopack completed in 405ms
deno run bundle.js   
@A evaluated
@B evaluated
@B called
@B called
fn() called from @B
fn() called from @B
C.test() called
```
Expected behavior with `deno run` which uses `Deno.compile()`:
```sh
deno run test-with-decorators.ts
@A evaluated
@B evaluated
@B called
@A called
fn() called from @A
fn() called from @B
C.test() called
```
This is the code `Deno.transpileOnly()` emits:
```javascript
function _applyDecoratedDescriptor(target, property, decorators, descriptor, context) {
    var desc = {
    };
    Object.keys(descriptor).forEach(function(key) {
        desc[key] = descriptor[key];
    });
    desc.enumerable = !!desc.enumerable;
    desc.configurable = !!desc.configurable;
    if ("value" in desc || desc.initializer) {
        desc.writable = true;
    }
    desc = decorators.slice().reverse().reduce(function(desc, decorator) {
        return decorator(target, property, desc) || desc;
    }, desc);
    if (context && desc.initializer !== void 0) {
        desc.value = desc.initializer ? desc.initializer.call(context) : void 0;
        desc.initializer = undefined;
    }
    if (desc.initializer === void 0) {
        Object.defineProperty(target, property, desc);
        desc = null;
    }
    return desc;
}
var _class, _dec, _dec;
function A() {
    console.log("@A evaluated");
    return function(target, propertyKey, descriptor) {
        console.log("@A called");
        const fn = descriptor.value;
        descriptor.value = function() {
            console.log("fn() called from @A");
            fn();
        };
    };
}
function B() {
    console.log("@B evaluated");
    return function(target, propertyKey, descriptor) {
        console.log("@B called");
        const fn = descriptor.value;
        descriptor.value = function() {
            console.log("fn() called from @B");
            fn();
        };
    };
}
let C = ((_class = class C {
    static test() {
        console.log("C.test() called");
    }
}) || _class, _dec = A(), _dec = B(), _applyDecoratedDescriptor(_class, "test", [_dec, _dec], Object.getOwnPropertyDescriptor(_class, "test"), _class), _class);
C.test();
```
Obviously `_dec` will always take the last value (last decorator in chain) in the assignment above.

### PR DESCRIPTION
**Pull request by jveres**
Closes #8412

### CODE REVIEW

File: cli/ast.rs [hunk 1]
```diff
@@ -309,7 +310,7 @@ impl ParsedModule {
 
     let program = swc_common::GLOBALS.set(&Globals::new(), || {
       helpers::HELPERS.set(&helpers::Helpers::new(false), || {
-        program.fold_with(&mut passes)
+        program.fold_with(&mut passes).fold_with(&mut hygiene())
```
Comment (bartlomieju) [inline cli/ast.rs:313]: Move `hygiene` to `passes` chain

**Review by bartlomieju — COMMENTED** [review]
Thanks for the PR @jveres, can you add a test case from issue demonstrating what's being fixed?

**Review by bartlomieju — APPROVED** [review]
LGTM, thanks @jveres
