### PR TITLE
fix: Format non-error exceptions

### LINKED ISSUE #14596: `Deno.test` does not render POJO errors nicely
```js
Deno.test("foo", async () => {
  throw { foo: "bar" };
})
```

prints as the error message:

```
./test.ts > foo
#<Object>
```

`#<Object>` is not a helpful serialization of the thrown value.

### PR DESCRIPTION
**Pull request by nayeemrmn**
Fixes #14596.

### CODE REVIEW

File: core/error.rs [hunk 1]
```diff
@@ -191,6 +191,20 @@ impl JsError {
...
+    let state = state_rc.borrow();
+    if let Some(format_exception_cb) = &state.js_format_exception_cb {
+      let format_exception_cb = format_exception_cb.open(scope);
+      let this = v8::undefined(scope).into();
+      let formatted = format_exception_cb.call(scope, this, &[exception]);
+      if let Some(formatted) = formatted {
+        if formatted.is_string() {
+          exception_message = Some(formatted.to_rust_string_lossy(scope));
+        }
+      }
```
Comment (bartlomieju) [inline core/error.rs:205]: What will be the formatting if the callback is not set?

Comment (nayeemrmn) [reply core/error.rs:205]: It will hit the `exception_message.unwrap_or_else()`s below to give the current behaviour
