### PR TITLE
fix(kv) increase number of allowed mutations in atomic

### LINKED ISSUE #19741: KV: increase atomic operations size
Also limit the total size of the atomic payload (key + value bytes)

### PR DESCRIPTION
**Pull request by igorzi**
fixes #19741

Impose a limit on the total atomic payload size

### CODE REVIEW

File: ext/kv/lib.rs [hunk 1]
```diff
@@ -35,7 +35,8 @@ const MAX_VALUE_SIZE_BYTES: usize = 65536;
 const MAX_READ_RANGES: usize = 10;
 const MAX_READ_ENTRIES: usize = 1000;
 const MAX_CHECKS: usize = 10;
-const MAX_MUTATIONS: usize = 10;
+const MAX_MUTATIONS: usize = 1000;
+const MAX_TOTAL_MUTATION_SIZE_BYTES: usize = 2097152;
```
Comment (losfair) [inline ext/kv/lib.rs:39]: Probably keep this limit at 800 KiB for now

**Review by losfair — APPROVED** [review]
LGTM
