### PR TITLE
fix(cli): deno doc panics on invalid url

### LINKED ISSUE #11529: cli: `deno doc` panics on invalid url
```
➜  ~ deno doc https://raw.githubusercontent.com%2Fdyedgreen%2Fdeno-sqlite%2Frework_api%2Fmod.ts\#PreparedQuery
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidUrl(InvalidDomainCharacter)', cli/tools/doc.rs:101:62
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### PR DESCRIPTION
**Pull request by F3n67u**
fix #11529

### CODE REVIEW

File: cli/tools/doc.rs [hunk 1]
```diff
@@ -98,7 +98,14 @@ pub async fn print_docs(
...
   } else {
-    let module_specifier = resolve_url_or_path(&source_file).unwrap();
+    let module_specifier = resolve_url_or_path(&source_file);
+    let module_specifier = match module_specifier {
+      Ok(s) => s,
+      Err(e) => {
+        eprintln!("{}", e);
+        std::process::exit(1);
+      }
+    };
```
Comment (bartlomieju) [inline cli/tools/doc.rs:108]: This error should be returned to the caller instead of calling `process::exit` - use: `resolve_url_or_path(&source_file)?` instead

**Review by bartlomieju — COMMENTED** [review]
Thanks for the PR @F3n67u, please add a test exercising the fixed failure

File: cli/tools/doc.rs (hunk 1 above)
Comment (F3n67u) [reply cli/tools/doc.rs]: fixed

**Review by ry — APPROVED** [review]
LGTM - thanks!
