### PR TITLE
Remove asni term dependency

### LINKED ISSUE #4112: Windows terminal colors broken after removal of ansi_term
We need to call `set_virtual_terminal_processing` 

see https://github.com/denoland/deno/pull/4106#pullrequestreview-363475270

### PR DESCRIPTION
**Pull request by jsouto18**
This Pull Request fixes the following bugs found from migrating to `termcolor`:

- Color was not being reset after a colored text was printed.
- Windows 10 was missing ANSI/VT100 enabling. (Needs to be tested on a Windows 10 machine!).

Closes #4112

### CODE REVIEW

File: cli/lib.rs [hunk 1]
```diff
@@ -389,7 +389,7 @@ async fn test_command(
 
 pub fn main() {
   #[cfg(windows)]
-  ansi_term::enable_ansi_support().ok(); // For Windows 10
+  colors::enable_ansi(); // For Windows 10
```
Comment (ry) [inline cli/lib.rs]: 👍
