### PR TITLE
fix(check): respect "compilerOptions.skipLibCheck" for graph errors

### LINKED ISSUE #30986: Allow `deno check` to ignore graph errors in dts files with `skipLibCheck`
I've been unable to integrate Deno with a framework that auto-generates code into a local "vendor" directory (e.g., [sst](https://sst.dev/)), where its generated types are referenced via a triple slash directive.

In my specific use case, I'm trying to use [sst](https://sst.dev). After running `sst init` (per SST's [docs](https://sst.dev/docs/start/aws/deno/)), a directory named `.sst/` is created, which contains auto-generated code, including a `package.json` and dependencies installed to `.sst/platform/node_modules`. Finally, `sst init` creates a file named `sst.config.ts` in the root of the project, which contains a triple-slash directive to pull in SST's type definitions located in `.sst/platform/config.d.ts`.

```typescript
/* sst.config.ts */
/// <reference path="./.sst/platform/config.d.ts" />

export default $config({
  app(input) {
    // stuff goes here...
  },
});
```

Deno picks up on the types referenced via the triple-slash directive, but `deno check` follows the reference path and type-checks the code in `.sst/`. For example:
```bash
❯ deno check --config ./deno.json sst.config.ts
Check file:///path/to/deno-aws/sst.config.ts
TS2307 [ERROR]: Cannot find module 'file:///path/to/deno-aws/.sst/types.generated'.
    at file:///path/to/deno-aws/.sst/platform/config.d.ts:2:8

...

TS2307 [ERROR]: Cannot find module 'file:///path/to/deno-aws/.sst/platform/src/components/component'. Maybe add a '.ts' extension or run with --sloppy-imports
    at file:///path/to/deno-aws/.sst/platform/src/global.d.ts:336:42

Found x errors.

error: Type checking failed.
```

**Whether or not the type errors are legitimate is besides the point — `deno check` shouldn't type check these files to begin with.** Currently, in this scenario, there doesn't seem to be a mechanism to provide type hints through the LSP while simultaneously excluding the types when running `deno check`.

---

Configuration options in `deno.json` I've tried:

1. ` "exclude": [".sst"]`
3. `"compilerOptions": { "types": [".sst/platform/config.d.ts"] }`
4. using `links`/`patch`
5. The above in combination with `"compilerOptions": { "skipLibCheck": true }`

---

To create a minimal reproduction, you can run these commands:
```bash
deno init sst-deno
cd sst-deno
deno add npm:sst
deno sst init --yes
deno check sst.config.ts
```

I initially asked for help in Discord and was directed to file an issue ([discussion here](https://questions.deno.com/m/1415419846765580318)).

I tested using the latest version of Deno (2.5.4).

### PR DESCRIPTION
**Pull request by nayeemrmn**
- Fixes #30986

### CODE REVIEW

File: cli/lsp/diagnostics.rs [hunk 1]
```diff
@@ -1076,6 +1076,16 @@ fn diagnose_dependency(
     return; // ignore, surface typescript errors instead
   }
 
+  if referrer_module.media_type.is_declaration() {
+    let compiler_options_data = snapshot
+      .compiler_options_resolver
+      .for_key(&referrer_module.compiler_options_key)
+      .expect("Key should be in sync with resolver.");
```
Comment (dsherret) [inline cli/lsp/diagnostics.rs]: Maybe warn instead just in case? Doesn't seem worth taking down the whole process for.
