### PR TITLE
fix(op_crates/fetch): Stringify and parse Request URLs

### LINKED ISSUE #7837: new Request(undefined).url should return "undefined"
See https://github.com/denoland/deno/issues/7836

This is what Chrome, FF, and Safari do, and it is intended behaviour:

- The constructor takes a union type https://fetch.spec.whatwg.org/#requestinfo
- Here's how to process a union type https://heycam.github.io/webidl/#es-union
- Which falls through to step 12
- Which sends us to https://heycam.github.io/webidl/#es-USVString
- Which sends us to https://heycam.github.io/webidl/#es-DOMString
- Which sends us to https://tc39.es/ecma262/#sec-tostring
- Which returns the string "undefined"
- So we process the request constructor with the string input, which takes us to step 6 https://fetch.spec.whatwg.org/#dom-request

### PR DESCRIPTION
**Pull request by nayeemrmn**
Fixes #7837.

### CODE REVIEW

File: op_crates/fetch/26_fetch.js [hunk 1]
```diff
@@ -985,8 +985,9 @@
         this.headers = new Headers(input.headers);
         this.credentials = input.credentials;
         this._stream = input._stream;
-      } else if (typeof input === "string") {
-        this.url = input;
+      } else {
+        // TODO(nayeemrmn): Base from `--location` when implemented and set.
+        this.url = new URL(String(input)).href;
```
Comment (nayeemrmn) [inline op_crates/fetch/26_fetch.js:990]: Relative URLs, including the original repro `new Request(undefined).url`, are now correctly blocked by #7369.

**Review by james-and — APPROVED** [review]

**Review by kitsonk — APPROVED** [review]
LGTM
