### PR TITLE
fix(check): ignore errors on ambient modules

### LINKED ISSUE #28455: vite should type-check out of the box
```
# deno run -A npm:create-vite@latest
# cd vite-project/
# ls
index.html  package.json  public  src  tsconfig.json
# deno check
[works!]
```

Similarly the LSP should work out of the box.

Currently runs into errors like this:

```
# deno check .
error: Failed resolving types. Could not resolve "vite/client", but found it in a package.json. Deno expects the node_modules/ directory to be up to date. Did you forget to run `deno install`?
```

### PR DESCRIPTION
**Pull request by kt3k**
Continued from #27633

This PR makes `deno check` ignore `Cannot find module` diagnostic if the missing module specifier matches one of ambient module pattern. (For example if there's `declare module "*.svg" { ... }` declaration in one of d.ts files, importing of `<any>.svg` doesn't cause type error with this change. This is necessary for passing the type checking of default vite template.)

LSP already implements this in #27855

closes #28455

### CODE REVIEW

File: cli/graph_util.rs [hunk 1]
```diff
@@ -968,6 +1009,10 @@ impl ModuleGraphBuilder {
         check_js: CheckJsOption::Custom(self.tsconfig_resolver.as_ref()),
         exit_integrity_errors: true,
         allow_unknown_media_types,
+        ignore_graph_errors: matches!(
```
Comment (nathanwhit) [inline cli/graph_util.rs:1012]: We probably also need to do this for deno test and other subcommands that do typechecking

**Review by nathanwhit — APPROVED** [review]
Nice, LGTM!

Only comment is that we probably need to apply this to other subcommands, depending on whether we're going to do typechecking.

File: cli/graph_util.rs (hunk 1 above)
Comment (nathanwhit) [reply cli/graph_util.rs:1012]: Oh good point, yeah that makes sense to me!
