### PR TITLE
fix(std): existsFile test

### LINKED ISSUE #4804: std/ tests existsFile and existsFileSync are flaky
https://github.com/denoland/deno/runs/597668423
https://github.com/denoland/deno/runs/595070636

### PR DESCRIPTION
**Pull request by bartlomieju**
Closes #4804

### CODE REVIEW

File: std/node/_fs/_fs_exists_test.ts [hunk 1]
```diff
@@ -6,10 +6,12 @@ import { exists, existsSync } from "./_fs_exists.ts";
 const { test } = Deno;
 
 test(async function existsFile() {
-  const availableFile = await new Promise(async (resolve) => {
```
Comment (bartlomieju) [inline std/node/_fs/_fs_exists_test.ts:9]: This problem should have been caught by eslint - https://eslint.org/docs/rules/no-async-promise-executor
