### PR TITLE
fix(upgrade): don't display release information for canary

### LINKED ISSUE #17515: `deno upgrade --canary` will panic after upgrade
It may be caused by the change of #17073.

```shell
> deno upgrade --canary
Looking up latest canary version
Found latest version 2027d98a8e9e530277ab301841872cdea7e2d590
Downloading https://dl.deno.land/canary/2027d98a8e9e530277ab301841872cdea7e2d590/deno-x86_64-pc-windows-msvc.zip
Deno is upgrading to version 2027d98a8e9e530277ab301841872cdea7e2d590
Upgraded successfully
Release notes: https://github.com/denoland/deno/releases/tag/v2027d98a8e9e530277ab301841872cdea7e2d590

============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: windows x86_64
Version: 1.29.4+654e177
Args: ["C:\\Users\\ayame\\.deno\\bin\\deno.exe", "upgrade", "--canary"]

thread 'main' panicked at 'index out of bounds: the len is 1 but the index is 1', cli\tools\upgrade.rs:166:3
stack backtrace:
   0:     0x7ff6a655ae16 - napi_release_threadsafe_function
   1:     0x7ff6a560c38b - napi_release_threadsafe_function
   2:     0x7ff6a653538a - napi_release_threadsafe_function
   3:     0x7ff6a655f19b - napi_release_threadsafe_function
   4:     0x7ff6a655ed91 - napi_release_threadsafe_function
   5:     0x7ff6a655e99b - napi_release_threadsafe_function
   6:     0x7ff6a5510f0c - napi_fatal_error
   7:     0x7ff6a655f9e8 - napi_release_threadsafe_function
   8:     0x7ff6a655f755 - napi_release_threadsafe_function
   9:     0x7ff6a655f69f - napi_release_threadsafe_function
  10:     0x7ff6a655f674 - napi_release_threadsafe_function
  11:     0x7ff6a780d0d5 - CrashForExceptionInNonABICompliantCodeRange
  12:     0x7ff6a780d157 - CrashForExceptionInNonABICompliantCodeRange
  13:     0x7ff6a628b1d8 - napi_release_threadsafe_function
  14:     0x7ff6a54c6b01 - napi_fatal_error
  15:     0x7ff6a54f7421 - napi_fatal_error
  16:     0x7ff6a5515753 - napi_fatal_error
  17:     0x7ff6a52b7065 - napi_cancel_async_work
  18:     0x7ff6a50754c8 - <unknown>
  19:     0x7ff6a5511b01 - napi_fatal_error
  20:     0x7ff6a50bce6d - <unknown>
  21:     0x7ff6a558ae84 - napi_release_threadsafe_function
  22:     0x7ff6a77bfbec - CrashForExceptionInNonABICompliantCodeRange
  23:     0x7ffd412655a0 - BaseThreadInitThunk
  24:     0x7ffd4240485b - RtlUserThreadStart
```

Note: The upgrade works fine. There seems to be a problem printing the message after that.

### PR DESCRIPTION
**Pull request by crowlKats**
Fixes #17515

### CODE REVIEW

**Review by aapoalas — APPROVED** [review]

**Review by bartlomieju — APPROVED** [review]
LGTM

File: cli/tools/upgrade.rs [hunk 1]
```diff
@@ -449,16 +453,18 @@ pub async fn upgrade(
...
+        "{}{}",
+        "Release notes: https://github.com/denoland/deno/releases/tag/v",
+        &install_version,
+      );
+      log::info!(
+        "{}{}",
+        "Blog post: https://deno.com/blog/v",
+        get_minor_version(&install_version)
+      );
+    }
```
Comment (dsherret) [inline cli/tools/upgrade.rs:467]: Same code three times. Maybe we should extract this out.

Comment (crowlKats) [reply cli/tools/upgrade.rs:467]: I was thinking as well (there actually is 2 more places), but they dont all use log::info, which is why i held off with that

Comment (dsherret) [reply cli/tools/upgrade.rs:467]: It looks like we can just use log::info everywhere (side note: IMO it would be nice to do the `!has_same_minor_version` check to conditionally show the blog post url everywhere too)

Comment (crowlKats) [reply cli/tools/upgrade.rs:467]: ok, done

File: cli/tools/upgrade.rs [hunk 2]
```diff
@@ -312,16 +310,6 @@ pub async fn upgrade(
...
-        log::info!(
-          "{}{}",
-          "Release notes: https://github.com/denoland/deno/releases/tag/v",
-          crate::version::deno(),
-        );
-        log::info!(
-          "{}{}",
-          "Blog post: https://deno.com/blog/v",
-          get_minor_version(&crate::version::deno())
-        );
```
Comment (dsherret) [inline cli/tools/upgrade.rs:324]: +1 for removing this. Too much noise.

**Review by dsherret — APPROVED** [review]
LGTM. I'm not sure why the CI is failing though. That looks like a segfault

**Comment by bartlomieju** [comment]
Blocked by https://github.com/denoland/deno/pull/17523
