### PR TITLE
fix(install): don't try to re-symlink binaries in node_modules if the symlink is correct

### LINKED ISSUE #30424: VitePress fails to build
Version: Deno 2.4.4 (but reproducing since June 18 2025)

> We had v2.x specified with setup-deno, so it always got the latest v2.x, and suddenly builds started to fail.
>
> The last successful build we had was on June 5. And it was broken by June 18.
>
> The full error can be seen here: https://github.com/grammyjs/website/actions/runs/15738672373/job/44358118850

More: https://discord.com/channels/684898665143206084/684898665151594506/1406063191460413672

### PR DESCRIPTION
**Pull request by nathanwhit**
Fix #30424.

I think this should avoid the errors. It will add some overhead when they aren't set up yet, but binaries are pretty small in number so I doubt it will matter.

In the case where it's already set up (which is probably common), it should avoid some work and prevent using binaries that are already in use

### CODE REVIEW

File: libs/npm_installer/bin_entries.rs [hunk 1]
```diff
@@ -487,6 +495,16 @@ fn symlink_bin_entry<'a>(
...
 
+  let original_relative = relative_path(bin_node_modules_dir_path, &original)
+    .map(Cow::Owned)
+    .unwrap_or_else(|| Cow::Borrowed(&original));
+
+  if let Ok(original_link) = sys.fs_read_link(&link)
+    && *original_link == *original_relative
+  {
+    return Ok(EntrySetupOutcome::Success);
+  }
```
Comment (dsherret) [inline libs/npm_installer/bin_entries.rs:506]: Maybe this should only happen on error? I've found reading symlinks to be really slow compared to just setting up the symlinks.

Comment (nathanwhit) [reply libs/npm_installer/bin_entries.rs:506]: Really? On my machine a successful `symlink` is about 50x slower than a readlink. And a failed `symlink` because the link is already there is about 15x slower than a readlink

Comment (nathanwhit) [reply libs/npm_installer/bin_entries.rs:506]: Oh hmm on linux, it does look like readlink is a bit slower than just trying to symlink. But on macos it's quite the opposite

Comment (dsherret) [reply libs/npm_installer/bin_entries.rs:506]: Interesting. IIRC reading is slower than writing on Windows as well. I guess it doesn't matter too much because there won't be a lot of these, as you mentioned.
