### PR TITLE
[WIP] Better flag parsing

### LINKED ISSUE #1198: Pass unrecognized command line arguments
At the moment using command line arguments that are not recognized by Deno results in error:
```
deno https://deno.land/x/examples/gist.ts --title test somefile.txt
Unrecognized option: 'title'
```

We'd like to be able to pass additional arguments especially once #1197 lands. I think it's connected with recent introduction of `optparse` in #1080.

cc: @ry @kevinkassimo

### PR DESCRIPTION
**Pull request by bartlomieju**
Based on @ry's patch: https://gist.github.com/ry/158e4d3ca54a57f4926bd0a39fd5a844

Fixes #1198 

This is a bit of brute force approach because we're parsing arguments one-by-one using `getopts.parse` and storing unrecognized arguments to be later passed to `deno.args`. Any ideas how to that do better are welcome.

There is still work to do, because at the moment V8 swallows arguments passed after `--`.

### CODE REVIEW

**Comment by hayd** [comment]
There are benefits to caring about the ordering e.g.
```sh
$ deno gist.ts --title X --allow-net
# vs
$ deno --allow-net gist.ts --title X
```
For example you can complain about typos e.g. `--allow-nt` rather than silently failing. Node and Python both care, deno should too.

**Comment by ry** [comment]
@hayd that’s a good point (that should be discussed in the code comment)

My argument against it: V8 has all these flags which are silently extracted from argv.. it works. By being less strict we allow the user code to take on that responsibility.

File: src/flags.rs [hunk 1]
```diff
@@ -36,11 +37,75 @@ Environment variables:
...
+  }
+  Ok(rest)
+}
+
 #[cfg_attr(feature = "cargo-clippy", allow(stutter))]
 pub fn set_flags(
   args: Vec<String>,
 ) -> Result<(DenoFlags, Vec<String>, String), String> {
+  // TODO: all flags passed after "--" are swallowed by v8_set_flags
+  // eg. deno --allow-net ./test.ts -- --title foobar
```
Comment (ry) [inline src/flags.rs]: Good catch! I wasn't aware of this.

File: src/flags.rs [hunk 2]
```diff
@@ -36,11 +37,75 @@ Environment variables:
   )
 }
 
-// Parses flags for deno. This does not do v8_set_flags() - call that separately.
+// Checks provided arguments for known options and sets appropriate Deno flags for them.
+// Unknown options are returned for further use.
+fn set_recognized_flags(
```
Comment (ry) [inline src/flags.rs]: Please add to the comment the two caveats of this approach: 
1. This assumes that privileged flags do not accept parameters `deno --foo bar`. This assumption is currently valid. But if it were to change in the future, this parsing technique would need to be modified. I _think_ we want to keep the privileged flags minimal - so having this restriction is maybe a good thing.
2. Misspelled flags will be forwarded to user code - e.g. `--allow-ne` would not cause an error. I also think this is ok because missing any of the privileged flags is not destructive. Userland flag parsing would catch these errors.

**Comment by hayd** [comment]
I really dislike this change. If you want to pass args to v8 or deno, pass them before the filename. That's the standard. Anything else is going to be surprising.

>  V8 has all these flags which are silently extracted from argv.. it works.

Perhaps the solution is to work out a way to be more explicit here. Require all args *before the script* to be consumed either by deno or v8. That way we can reject typos in v8 args too. That way there's nothing to do in userland!

It seems clear there's a cost. What's the benefit of this ambiguity?

**Comment by ry** [comment]
Your dislike is because you don't get errors when args are misspelled? Or are there other reasons?

I do a lot of command-line editing, and I dislike having to carefully place arguments. It's very nice to do "up up -D enter" and get debug output. I also think this behavior is easy to explain - whereas telling people where to place arguments is more complex.

**Comment by hayd** [comment]
I prefer errors be loud and not happen at runtime, so I think catching typos is valuable. If deno adds a arg, or there is a v8 arg you don't know about/added, it's going to be confusing that it's not available in deno.args (and that it's modified v8 somehow).

---

up ctrl+a alt+f -D

is a few more keystrokes BUT I'd argue generally a user is more likely to debug their own code rather than deno's core. I wonder if you're optimizing development rather than majority use case (which is, of course, fine at the moment).

An alternative is to alias deno and ddeno resp. to `out/debug/deno` and `out/debug/deno -D`. That way you can do:

up ctrl+a d

which is the same number keystrokes 😄

**Comment by ry** [comment]
I mean, -D is just an example, it could as well be "up up --allow-net enter" or "up up -r enter"

**Comment by hayd** [comment]
I still don't buy this argument, but I wonder if a way to move forward here is to pass --version and --help along if a script is passed.

i.e. `deno --version` prints version but `deno --version main.ts` passes the version flag to main.ts.

cc @lucascaro
