### PR TITLE
fix(coverage): `deno test --coverage` fails when importing modules from `data:` urls

### LINKED ISSUE #29479: deno test --coverage errors if `data:` modules were imported
Version: Deno deno 2.3.3 (stable, release, x86_64-unknown-linux-gnu)

```
vscode ➜ /workspaces/metrics (x2025) $ deno test --coverage test.ts 
Check file:///workspaces/metrics/test.ts
running 1 test from ./test.ts
test ... ok (0ms)

ok | 1 passed | 0 failed (11ms)

Error generating coverage report: Failed to fetch "data:application/typescript,export default null" from cache. Before generating coverage report, run `deno test --coverage` to ensure consistent state.
```

The last message shouldn't be printed (and probably the coverage for `data:` schemes should be skipped too)

Minimal repro
```ts
import { expect } from "jsr:@std/expect@1"

async function test() {
  const {default:value} = await import("data:application/typescript,export default null")
  return value
}

Deno.test("test", async () => {
  await expect(test()).resolves.toBeNull()
})
```

### PR DESCRIPTION
**Pull request by lowlighter**
Close #29479

### CODE REVIEW

File: cli/tools/test/mod.rs [hunk 1]
```diff
@@ -1701,7 +1701,7 @@ pub async fn run_tests(
       flags,
       vec![coverage.clone()],
       vec![],
-      vec![],
+      vec!["^file:".to_string()],
```
Comment (kt3k) [inline cli/tools/test/mod.rs]: This argument is mainly for handling exclude pattern given by the user. Can you instead modify `filter_coverages` function to exclude those files?

**Review by kt3k — COMMENTED** [review]
Thanks for looking into this!

The test case looks good to me. Left one comment.

File: cli/tools/test/mod.rs (hunk 1 above)
Comment (lowlighter) [reply cli/tools/test/mod.rs]: What would be the best approach for this ?

Do I add something like `!is_data` or should I directly append the `^data:` regex in the `is_excluded` vector ?
https://github.com/denoland/deno/blob/5bd9a337c1da8c7cad22c7760c02f80314021eea/cli/tools/coverage/mod.rs#L589-L592

**Review by kt3k — APPROVED** [review]
Thanks for the fix! LGTM
