### PR TITLE
core: let embedders plug in their own V8 platform

### LINKED ISSUE #9912: embedding: JsRuntime::new() fails if V8 is initialized
If a deno_core embedder calls:
```rust
v8::V8::initialize_platform(v8::new_default_platform().unwrap());
```
Then subsequently calling `deno_core::JsRuntime::new(...)` results in this error:
<details>

```
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `PlatformInitialized`,
 right: `Uninitialized`', /home/bnoordhuis/.cargo/registry/src/github.com-1ecc6299db9ec823/rusty_v8-0.21.0/src/V8.rs:183:3
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at ./rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/panicking.rs:92:14
   2: rusty_v8::V8::initialize_platform
             at ./home/bnoordhuis/.cargo/registry/src/github.com-1ecc6299db9ec823/rusty_v8-0.21.0/src/V8.rs:183:3
   3: deno_core::runtime::v8_init
             at ./home/bnoordhuis/.cargo/registry/src/github.com-1ecc6299db9ec823/deno_core-0.81.0/runtime.rs:148:3
   4: deno_core::runtime::JsRuntime::new::{{closure}}
             at ./home/bnoordhuis/.cargo/registry/src/github.com-1ecc6299db9ec823/deno_core-0.81.0/runtime.rs:209:16
   5: std::sync::once::Once::call_once::{{closure}}
             at ./home/bnoordhuis/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sync/once.rs:261:41
   6: std::sync::once::Once::call_inner
             at ./rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/sync/once.rs:420:21
   7: std::sync::once::Once::call_once
             at ./home/bnoordhuis/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sync/once.rs:261:9
   8: deno_core::runtime::JsRuntime::new
             at ./home/bnoordhuis/.cargo/registry/src/github.com-1ecc6299db9ec823/deno_core-0.81.0/runtime.rs:201:5
```

</details>

Because of these two lines - rusty_v8 doesn't like it when you call `initialize_platform()` twice:

https://github.com/denoland/deno/blob/b11249647fa14e482881fd22446dbd8b0cbac27c/core/runtime.rs#L148-L149

I'm not sure what to do about it but it makes coexistence of deno_core and plain rusty_v8 code difficult.

I could tweak rusty_v8 to allow multiple calls but then deno_core would override the embedder's platform. It shouldn't.

### PR DESCRIPTION
**Pull request by bnoordhuis**
Fixes #9912.

### CODE REVIEW

**Review by ry — COMMENTED** [review]
Would it be difficult to have a small unit test example demonstrating this API? Would be nice to have. If too difficult, I'm ok with not doing it.

File: core/runtime.rs [hunk 1]
```diff
@@ -2381,4 +2387,14 @@ main();
     // Test that the script specifier is a URL: `deno:<repo-relative path>`.
     assert!(error_string.contains("deno:core/core.js"));
   }
+
+  #[test]
+  fn test_v8_platform() {
+    let options = RuntimeOptions {
+      v8_platform: Some(v8::new_default_platform()),
```
Comment (ry) [inline core/runtime.rs:2394]: 👍

**Review by ry — APPROVED** [review]
LGTM
