### PR TITLE
fix(lsp): properly resolve jsxImportSource for caching

### LINKED ISSUE #25678: Bug(lsp): jsx runtime not found if defined in `package.json`
When both a `package.json` and a `deno.json` are present the JSX import source isn't resolved properly in the LSP. It seems to only check for dependencies in `deno.json` for `jsxImportSource`.

## Steps to reproduce

1. Run `npm init -y`
2. Run `npm i preact`
3. Create a `deno.json` with these contents:
  ```json
  {
    "compilerOptions": {
      "jsx": "react-jsx",
      "jsxImportSource": "preact"
    }
  }
  ```

Output:

```sh
Refreshing configuration tree...
  Resolved Deno configuration file: "file:///Users/marvinh/dev/test/deno-jsx-package/deno.json"
  Resolved package.json: "file:///Users/marvinh/dev/test/deno-jsx-package/package.json"
  Enabled 'bring your own node_modules'.
Error caching: Relative import path "preact/jsx-runtime" not prefixed with / or ./ or ../
    at data:application/typescript;base64,aW1wb3J0ICdwcmVhY3QvanN4LXJ1bnRpbWUnOw==:1:8
```

Screenshot 2024-09-17 at 10 59 57

Version: Deno 2.0.0-rc.2+aaf2bf4

### PR DESCRIPTION
**Pull request by nayeemrmn**
Fixes #25678.

### CODE REVIEW

File: tests/integration/lsp_tests.rs [hunk 1]
```diff
@@ -11663,7 +11663,6 @@ export function B() {
   client.shutdown();
 }
 
-#[ignore = "https://github.com/denoland/deno/issues/21770"]
 #[test]
 fn lsp_jsx_import_source_config_file_automatic_cache() {
```
Comment (nayeemrmn) [inline tests/integration/lsp_tests.rs:11667]: Gonna try reenabling this. It was flaky (#21770), but we've made the LSP init sequence more stable so it might be fixed. And it's the only way to test this.

**Review by lucacasonato — APPROVED** [review]

**Review by marvinhagemeister — APPROVED** [review]
