### PR TITLE
fix(ext/node): emit `online` event after worker thread is initialized

### LINKED ISSUE #23281: Bug: `parcel` freezes on start
Running `parcel` freezes the terminal and I can't even use `ctrl+c` to abort it.

## Steps to reproduce

1. Create `index.html` with these contents:
```html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <title>My First Parcel App</title>
  </head>
  <body>
    <h1>Hello, World!</h1>
  </body>
</html>
```
5. Run `DENO_FUTURE=1 deno run -A npm:parcel src/index.html`

Version: Deno 1.42.1 (git 2670c1d58 2024-04-08)
OS: mac

### PR DESCRIPTION
**Pull request by nathanwhit**
Fixes #23281. Part of #20613.

We were emitting the `online` event in the constructor, so the caller could never receive it (since there was no time for them to add a listener). Instead, emit the event where it's intended – after the worker is initialized.

---

After this parcel no longer freezes, but still will fail due to other bugs (which will be fixed in other PRs)

### CODE REVIEW

File: ext/node/polyfills/worker_threads.ts [hunk 1]
```diff
@@ -243,7 +253,17 @@ class NodeWorker extends EventEmitter {
         this.emit("messageerror", err);
         return;
       }
-      this.emit("message", message);
+      if (
+        // only emit "online" event once, and since the message
+        // has to come before user messages, we are safe to assume
+        // it came from us
```
Comment (bartlomieju) [inline ext/node/polyfills/worker_threads.ts:259]: Is it guaranteed that this will arrive before user messages? In the past we had trouble with raciness between user and internal messages

**Review by bartlomieju — APPROVED** [review]

File: ext/node/polyfills/worker_threads.ts (hunk 1 above)
Comment (nathanwhit) [reply ext/node/polyfills/worker_threads.ts:259]: Hmm I mean this gets called as part of bootstrap. Is it possible for user code to execute before bootstrap?

Comment (bartlomieju) [reply ext/node/polyfills/worker_threads.ts:259]: It shouldn't. Let's try it out first. Maybe I'm overthinking.
