### PR TITLE
fix(cli): Handling of relative importmaps while using watch

### LINKED ISSUE #7831: Using watch with importmap requires an absolute path
# Steps to reproduce
If you run `deno` and use the options `--watch` in combination with `--importmap` like this:
```bash
cd /denoapp
deno run --unstable \
--watch \
--importmap import_map.json \
src/app.ts
```
then you will get an error if `--importmap` is not an absolute path.

# Workaround
```bash
cd /denoapp
deno run --unstable \
--watch \
--importmap /denoapp/import_map.json \
src/app.ts
```

# Environment used
**Deno Version: 1.4.3**
To be precise I used this [docker image](https://github.com/hayd/deno-docker/releases/tag/1.4.3)
Error did not occur with Version 1.4.1
Did not test with Deno Version 1.4.4 cause upgrading inside the docker container did not work as expected but the code that created the error did not change.

# Error message
If you do not supply an absolute path to `--importmap` then you get this error.
```stacktrace
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ()', cli/main.rs:512:10
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1076
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1537
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:217
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:526
  11: rust_begin_unwind
             at src/libstd/panicking.rs:437
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  13: core::option::expect_none_failed
             at src/libcore/option.rs:1269
  14: core::result::Result<T,E>::unwrap
  15: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  16: tokio::runtime::Runtime::block_on
  17: deno::main
  18: std::rt::lang_start_internal::{{closure}}::{{closure}}
             at src/libstd/rt.rs:52
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

# Code

The error was raised by the following code
```rust
  //cli/main.rs:512:10
  if let Some(import_map) = global_state.flags.import_map_path.clone() {
    paths_to_watch.push(
      Url::parse(&format!("file://{}", &import_map))?
        .to_file_path()
        .unwrap(),
    );
  }
```

### PR DESCRIPTION
**Pull request by Absebo**
Resolves  #7831

### CODE REVIEW

File: cli/tests/integration_tests.rs [hunk 1]
```diff
@@ -1127,6 +1127,66 @@ fn run_watch() {
...
+      .expect("unable to create relative temporary file")
+      .to_owned();
+    assert!(relative_path.is_relative());
+    relative_path
+  }
+  let temp_directory =
+    TempDir::new_in(util::root_path()).expect("tempdir fail");
+  let file_to_watch = create_relative_tmp_file(
+    &temp_directory,
+    "file_to_watch.js",
```
Comment (bartlomieju) [inline cli/tests/integration_tests.rs:1200]: Nice test

**Review by bartlomieju — APPROVED** [review]
LGTM
