### PR TITLE
Fix(cli): don't panic when no `HOME` env var is set

### LINKED ISSUE #6566: Deno v1.1.2 panics when no `HOME` env var is set
This is new behavior as of v1.1.2:

```
$ deno --version
deno 1.1.2
v8 8.5.216
typescript 3.9.2

$ unset HOME

$ deno
thread 'main' panicked at 'Could not get home directory.', cli/deno_dir.rs:18:20
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I think Deno should fall back to checking the result of `getpwuid()` (Rust-equivalent, Windows-equivalent), which I believe is what Node.js does (node doesn't require `$HOME` to be set and `os.homedir()` still works properly).

I am using a [workaround](https://github.com/TooTallNate/vercel-deno/blob/1252210069563c128fc3a248b56ed3feae9d9255/src/bootstrap#L7) that fixes the issue for now.

### PR DESCRIPTION
**Pull request by Spoonbender**
Fix #6566
1. Only resolve the cache dir if no $DENO_DIR is set
2. Only resolve the home dir if no cache dir was found
3. If the $HOME environment variable is not set, try to fetch the home directory from the system user database (passwd)

### CODE REVIEW

File: cli/tests/integration_tests.rs [hunk 1]
```diff
@@ -3197,3 +3197,52 @@ fn should_not_panic_on_no_stderr() {
...
+    .env_remove("DENO_DIR")
+    .stdout(std::process::Stdio::piped())
+    .spawn()
+    .unwrap()
+    .wait_with_output()
+    .unwrap();
+  assert!(output.status.success());
+}
+
+#[cfg(not(windows))]
```
Comment (ry) [inline cli/tests/integration_tests.rs:3233]: Why not windows?

Comment (Spoonbender) [reply cli/tests/integration_tests.rs:3232]: Right! fixed
