### PR TITLE
fix(bundle): fix handling of multiple entrypoints

### LINKED ISSUE #29648: bundle only handles first entrypoint

### PR DESCRIPTION
**Pull request by nathanwhit**
Fixes #29648.

### CODE REVIEW

File: tests/specs/bundle/multiple_entries/src/bar/main.ts [hunk 1]
```diff
@@ -0,0 +1,2 @@
+import { helper } from "./helper.ts";
+console.log(`hello from ${helper()}`);
```
Comment (marvinhagemeister) [inline tests/specs/bundle/multiple_entries/src/bar/main.ts:2]: CI fails because of different casing `Hello` vs `hello`

**Review by marvinhagemeister — APPROVED** [review]
