### PR TITLE
fix(publish): make include and exclude work

### LINKED ISSUE #22482: Consider deprecating `exclude` and `include` in deno.json in favor of a unified `files` key
Right now it is not immediately clear whether `include` or `exclude` has higher priority when determining what files we include, and which ones we do not include when matching. It seems that `include` effectively defaults to `["**"]`, while `exclude` defaults to `[]`.

This means that a reasonable person doing this would suddenly get the weird behaviour of matching no files?!

```diff
{
  "exclude": ["target/"],
+ "include": ["target/release/js/"]
}
```

Instead you should add `"include": ["**", "target/release/js/"]` - this however also does not work, because our implementation is buggy.

This is weird. This is not how `.gitignore` works. This is not how `.prettierignore` works. This is not how `.npmignore` or `.dockerignore` work. It's just plain weird. It's also not how `package.json`'s `files` works.

I think we should solve this. There are three constraints at hand:

- should be inside of `deno.json`, no external file
- it should be easy to ignore all files and include only some files
- it should be easy to include all files, except for some

I suggest we solve this using an array of positive and negative globs, evaluated top down. We call this key `files` in the config file, and allow it everywhere we allow `exclude` and `include`. When this key is specified, `exclude` and `include` MUST NOT be specified in the config file (they will be deprecated).

As for timelines, I suggest we introduce this feature in an upcoming release, and deprecate (but not remove `exclude` and `include` in 2.0 (too much usage in the wild).

Here are some examples of modeling various scenarios with this feature:

#### Include only `deno/` folder in config file
```json
{
  "files": [
    "!**",
    "deno/",
  ]
}
```

#### Include all files except `dist/` folder
```json
{
  "files": [
    "!dist/",
  ]
}
```

#### Include all files except the `dist/` folder, but do include `dist/js/` 
```json
{
  "files": [
    "!dist/",
    "dist/js/",
  ]
}
```

### LINKED ISSUE #22648: JSR: `deno publish` does not respect `config.jsonc`'s `#/publish/include`/`#/publish/exclude` fields
Version: Deno 1.41.0

I'm trying to exclude all files in my codebase (except `config.jsonc` and `mod.ts`) when publishing to JSR via `deno publish`.

Instructions on how to use the glob pattern in the config's `#/publish/include`/`#/publish/exclude` fields: https://jsr.io/docs/publishing-packages#ignoring-files

### Input
```jsonc
{
    "name": "@<scope>/<package>",
    "version": "0.0.1",
    "exports": {
        ".": "./ui/static/script/mod.ts"
    },
    "publish": {
        "exclude": [
          "**"
        ],
        "include": [
            "ui/static/script/mod.ts"
        ]
    },
}
```
### Output
`deno publish --dry-run`
```
Checking for slow types in the public API...
Simulating publish of @<scope>/<package>@0.0.1 with files:
Warning Aborting due to --dry-run
```
Notice how there are `zero` files picked up.

### Input
```jsonc
{
    "name": "@<scope>/<package>",
    "version": "0.0.1",
    "exports": {
        ".": "./ui/static/script/mod.ts"
    },
    "exclude": [
        ".github",
        ".idea",
        ".vscode",
        "bin",
        "docs",
        "target",
        "<code>",
        "ui/html",
        "ui/static/file",
        "ui/static/image",
        "ui/static/scss",
        "<code>",
        ".clippy.toml",
        "Cargo*",
        "Dockerfile",
        "Makefile"
    ]
}
```
### Output
`deno publish --dry-run`
```
Checking for slow types in the public API...
Simulating publish of @<scope>/<package>@0.0.1 with files:
   file:///Users/<me>/Documents/code/<repo>/.dockerignore (58B)
   file:///Users/<me>/Documents/code/<repo>/.gitignore (68B)
   file:///Users/<me>/Documents/code/<repo>/LICENSE (1.07KB)
   file:///Users/<me>/Documents/code/<repo>/README.md (1.08KB)
   file:///Users/<me>/Documents/code/<repo>/deno.jsonc (892B)
   file:///Users/<me>/Documents/code/<repo>/ui/static/script/mod.ts (897B)
Warning Aborting due to --dry-run
```
I've finally excluded a majority of the files I want to exclude from the final published package. But now I have to manually maintain this list of excludes which is error-prone (aka failure by default).

## Also: `.gitignore` is not respected

I'm also very surprised that my `.gitignore`/`.dockerignore` files are not respected. Rust's `cargo` ignores paths that are ignored by the repo's VCS.

> Cargo will automatically ignore files ignored by your version control system when packaging, but if you want to specify an extra set of files to ignore you can use the [exclude key](https://doc.rust-lang.org/cargo/reference/manifest.html#the-exclude-and-include-fields) in the manifest:

Source: https://doc.rust-lang.org/cargo/reference/publishing.html#packaging-a-crate

### LINKED ISSUE #22656: Cannot opt out of .gitignore when publishing
It seems I cannot opt out of the gitignore when publishing. My current solution is to delete the `.gitignore` file before running `deno publish`

Version: Deno 1.41.1

### PR DESCRIPTION
**Pull request by dsherret**
1. Stops `deno publish` using some custom include/exclude behaviour from other sub commands
2. Takes ancestor directories into account when resolving gitignore
3. Backards compatible change that adds ability to unexclude an exclude by using a negated glob at a more specific level for all sub commands (see https://github.com/denoland/deno_config/pull/44).
    
**Include only `deno/` folder**

This respects the ignored files in the gitignore:

```json
{
  "publish": [
    "include": ["deno/"]
  ]
}
```

**Include all files except `dist/` folder**

This respects the ignored files in the gitignore:

```json
{
  "publish": [
    "exclude": ["dist/"]
  ]
}
```

**Include a file/directory that's excluded at the top level**

```jsonc
{
  "publish": [
    "exclude": [
      "!dist" // unexclude for publish
    ]
  ],
  "exclude": [
    "dist"
  ]
}
```

**Include a file/directory that's excluded in a gitignore**

```
// gitignore
dist
```

```jsonc
{
  "publish": [
    "exclude": [
      "!dist" // unexclude for publish
    ]
  ]
}
```

**Include all files except the `dist/` folder, but do include `dist/js/`**

```jsonc
{
  "publish": [
    "exclude": [
      "dist/",
      "!dist/js/", // items further down in the array win over items above
    ]
  ]
}
```

Closes #22648
Closes #22656
Closes #22482
Closes https://github.com/jsr-io/jsr/issues/194

### CODE REVIEW

**Comment by dsherret** [comment]
I'm working on updating deno-docs with this information.

File: cli/lsp/config.rs [hunk 1]
```diff
@@ -1095,7 +1095,15 @@ impl Config {
         continue;
       };
       let settings = self.workspace_settings_for_specifier(workspace_uri);
-      if settings.enable.unwrap_or_else(|| self.has_config_file()) {
```
Comment (dsherret) [inline cli/lsp/config.rs:1098]: @nayeemrmn this previous condition seemed slightly wrong and caused some trouble in the tests. Is the new condition ok?

Comment (nayeemrmn) [reply cli/lsp/config.rs:1098]: Ah good find, but if `enable_paths` is specified then it should completely override `enable`.

```rust
if settings.enable_paths.as_ref().map(|p| !p.is_empty()).unwrap_or_else(|| previous_condition) { ... }
```

File: cli/tools/bench/mod.rs [hunk 2]
```diff
@@ -394,25 +394,16 @@ async fn bench_specifiers(
 }
 
 /// Checks if the path has a basename and extension Deno supports for benches.
-fn is_supported_bench_path(path: &Path, patterns: &FilePatterns) -> bool {
-  if !is_script_ext(path) {
+fn is_supported_bench_path(entry: WalkEntry) -> bool {
```
Comment (bartlomieju) [inline cli/tools/bench/mod.rs:397]: It's a bit scary that we have to update every single subcommand to the new mechanism :D

File: cli/tools/registry/tar.rs [hunk 3]
```diff
@@ -45,75 +44,60 @@ pub fn create_gzipped_tarball(
...
-  for pattern in file_patterns.as_ref().iter().flat_map(|p| p.include.iter()) {
-    for path_or_pat in pattern.inner() {
-      match path_or_pat {
-        PathOrPattern::Path(p) => ob.add(p.to_str().unwrap())?,
-        PathOrPattern::Pattern(p) => ob.add(p.as_str())?,
-        PathOrPattern::RemoteUrl(_) => continue,
-      };
+  let iter_paths = FileCollector::new(|e| {
+    if !e.file_type.is_file() {
+      if let Ok(specifier) = ModuleSpecifier::from_file_path(e.path) {
```
Comment (bartlomieju) [inline cli/tools/registry/tar.rs:54]: I'm confused here - if the file type is not a file then why try to do `ModuleSpecifier::from_file_path`? Can it be a symlink?

File: cli/util/fs.rs [hunk 4]
```diff
@@ -300,14 +348,17 @@ impl<TFilter: Fn(&Path, &FilePatterns) -> bool> FileCollector<TFilter> {
...
-          || !is_dir
-            && !file_patterns
-              .include
-              .as_ref()
-              .map(|i| i.matches_path(&c))
-              .unwrap_or(true)
-        {
+        let maybe_gitignore =
+          maybe_git_ignores.as_mut().and_then(|git_ignores| {
+            let dir_path = if is_dir { &c } else { c.parent()? };
```
Comment (bartlomieju) [inline cli/util/fs.rs:353]: Add context to `c.parent()`?

File: cli/util/fs.rs [hunk 5]
```diff
@@ -300,14 +348,17 @@ impl<TFilter: Fn(&Path, &FilePatterns) -> bool> FileCollector<TFilter> {
...
+            git_ignores.get_resolved_git_ignore(dir_path)
+          });
+        if !is_pattern_matched(
```
Comment (bartlomieju) [inline cli/util/fs.rs:356]: This whole for loop + loop is super hard to grasp. Consider rewriting to use `if` + `continue`, but not a blocker to land

File: ext/fs/in_memory_fs.rs
Comment (bartlomieju) [inline ext/fs/in_memory_fs.rs:1]: Is this whole module added just to support testing gitignore functionality? 😬 If so consider making it only available in `cfg(test)`

File: ext/fs/in_memory_fs.rs [hunk 6]
```diff
@@ -0,0 +1,424 @@
+// Copyright 2018-2024 the Deno authors. All rights reserved. MIT license.
+
+#![allow(clippy::disallowed_types)]
```
Comment (bartlomieju) [inline ext/fs/in_memory_fs.rs:3]: Are there many of them? Maybe leave a comment about this directive usage.

File: cli/tools/bench/mod.rs (hunk 2 above)
Comment (dsherret) [reply cli/tools/bench/mod.rs:397]: They're all basically doing the same thing. It's mostly a refactor from arguments to a single argument and then consolidating the duplicate custom bench & test code to the same function then handling negated globs/paths in the consolidation.

File: cli/util/fs.rs (hunk 4 above)
Comment (dsherret) [reply cli/util/fs.rs:353]: Do you mean anyhow context? Can't for this because it's an option and this should never happen because `c.parent()` would only be undefined for the root directory, in which case it would match on `is_dir`. I just did `?` to not unwrap.

Comment (bartlomieju) [reply cli/util/fs.rs:353]: Yeah I meant anyhow context. Disregard if it's an option.

File: ext/fs/in_memory_fs.rs
Comment (dsherret) [reply ext/fs/in_memory_fs.rs:1]: Can't make it #[cfg(test)] because then it can't be used outside this crate. I think this will just be optimized away when compiling?

File: cli/util/fs.rs (hunk 5 above)
Comment (dsherret) [reply cli/util/fs.rs:356]: I'm going to leave the code as-is for now because doing that is a riskier refactor.

File: ext/fs/in_memory_fs.rs (hunk 6 above)
Comment (dsherret) [reply ext/fs/in_memory_fs.rs:3]: I'm going to add a comment on this. It's just to use `Arc`, which is fine for this module.

File: ext/fs/in_memory_fs.rs
Comment (bartlomieju) [reply ext/fs/in_memory_fs.rs:1]: Hm... Since the trait it implements is public maybe move it to the gitignore module?

Comment (dsherret) [reply ext/fs/in_memory_fs.rs:1]: I think it would be useful in the future for non-CLI crates and Deploy for testing purposes.

**Comment by ghostdevv** [comment]
The behaviour of `include` ignoring the `.gitignore` feels very unintuitive to me but perhaps I am missing something? To me the include option here feels more specific than the gitignore and should be able to overwrite it - or I should have to do the `!` syntax in the `include` not the `exclude`

**Comment by dsherret** [comment]
@ghostdevv there are so many scenarios with what files should be matched or not. For example, someone might specify the `./src` folder and expect gitignored files/directories within that folder to not be matched. Someone else might expect them to be matched. Perhaps someone does `./**/*.json` in their include, but they have one `.gitignored` json file they didn't want included, but someone else in a similar situation did. So the behaviour implemented in this PR is to not include anything that's gitignored for people that want that behaviour, but also providing an explicit opt-out mechanism for people who want to include something that's gitignored.

That said, and as you allude to, directories or files (non-globs) in the `include` array should override non-glob `.gitignore` entries that match the full path or an ancestor directory. I thought it would be complicated to implement because of directories, but I thought of an easy way to implement it. Opened https://github.com/denoland/deno/pull/22790

**Comment by dsherret** [comment]
@magic-akari ok, so the reason it occurs in that scenario is because the `.gitignore` has `*` and so it ignores the parent directory. It looks like that's a bug and `*` in a gitignore should not ignore the parent directory. Real life scenarios that don't use `*` in a .gitignore should work.

**Comment by ghostdevv** [comment]
@dsherret that makes a lot of sense thanks! It's for sure a complicated problem and this is probably the nicest solution
