### PR TITLE
Fix dynamic import base path problem for REPL and eval

### LINKED ISSUE #2756: Dynamic import broken under REPL and deno eval
Assume `mod.ts` exists and with content `export const mod = 1;`

REPL:
```
$ deno
> import('./mod.ts').then(console.log)
Promise {}
> error: Uncaught TypeError: invalid base URL for relative import: relative URL without a base
```

`deno eval`:
```
$ deno eval "import('./mod.ts').then(console.log)"
error: Uncaught TypeError: invalid base URL for relative import: relative URL without a base
```

### PR DESCRIPTION
**Pull request by kevinkassimo**
Closes #2756 

Separated into 2 parts, since `<anonymous>` is not known to core crate (while `<unknown>` is known), and that `<>` would be escaped for URL paths and looks ugly, thus replaced with `__anonymous__`.

We do not have a robust way to test REPL directly atm. Instead test on `Deno.core.evalContext` which is used by REPL.

### CODE REVIEW

File: core/module_specifier.rs [hunk 1]
```diff
@@ -46,6 +46,10 @@ impl fmt::Display for ModuleResolutionError {
 pub struct ModuleSpecifier(Url);
 
 impl ModuleSpecifier {
+  fn is_dummy_specifier(specifier: &str) -> bool {
+    specifier == "<unknown>"
```
Comment (piscisaureus) [inline core/module_specifier.rs]: I think this is good as a short term fix.

Longer term, we should make ModuleSpecifier an enum , something like `enum ModuleSpecifier { Url(Url), Repl(PathBuf) }`, and stop converting between String/Url/ModuleSpecifier all the time, and change the resolve_import signature to 
`pub fn resolve_import(
    specifier: &str,
    base: ModuleSpecifier
  ) -> Result<ModuleSpecifier, ModuleResolutionError>`.
