### PR TITLE
chore(tests): maybe fix flaky flock tests

### LINKED ISSUE #12094: flock tests are flaky
Based on how the test is written, probably flockFileSync is flaky too.

```
error: Test failed
failures:

flockFileAsync
AssertionError: shared does not block shared
    at assertEquals (file:///D:/a/deno/deno/test_util/std/testing/asserts.ts:271:9)
    at flockFileAsync (file:///D:/a/deno/deno/cli/tests/unit/flock_test.ts:96:5)
    at async asyncOpSanitizer (deno:runtime/js/40_testing.js:35:9)
    at async resourceSanitizer (deno:runtime/js/40_testing.js:72:7)
    at async exitSanitizer (deno:runtime/js/40_testing.js:99:9)
    at async applyPermissions (deno:runtime/js/40_testing.js:124:9)
    at async runTest (deno:runtime/js/40_testing.js:215:7)
    at async Object.runTests (deno:runtime/js/40_testing.js:299:22)

failures:

	flockFileAsync
```

### PR DESCRIPTION
**Pull request by dsherret**
Removes any timing from these tests. Instead just checks that the file can be read or written based on the type of lock.

Closes #12094

### CODE REVIEW

File: cli/tests/unit/flock_test.ts [hunk 1]
```diff
@@ -17,125 +17,115 @@ unitTest(
...
-  assertEquals(
-    await checkFirstBlocksSecond({
-      firstExclusive: true,
-      secondExclusive: true,
+    });
+    try {
+      await fileLock.waitEnterLock();
+      assertEquals(
+        checkFileCanRead(filePath),
+        false,
```
Comment (dsherret) [inline cli/tests/unit/flock_test.ts:35]: Looks like I didn't actually fix this because it doesn't work this way on Linux.

File: cli/tests/unit/flock_test.ts [hunk 2]
```diff
@@ -17,125 +17,134 @@ unitTest(
...
+      exclusive ? "exclusive cannot read" : "non-exclusive can read",
+    );
+    assertEquals(
+      checkFileCanWrite(filePath),
+      false,
+      "cannot write",
+    );
+  } else {
+    const process = await Deno.run({
+      cmd: ["lsof", "-p", pid.toString()],
```
Comment (dsherret) [inline cli/tests/unit/flock_test.ts:83]: Not available on GH actions. Sigh...

**Review by bartlomieju — APPROVED** [review]
LGTM, let's try
