### PR TITLE
fix: adapt to new jupyter runtime API and include session IDs

### LINKED ISSUE #24737: Session Ids returned in Jupyter Kernel responses are incorrect
Version: Deno x.x.x (latest version)

Steps to repro
* Install Jupyter Lab
* Install deno and the deno kernel for Jupyter
* Install the Kernel spy (to view kernel messages https://github.com/jupyterlab-contrib/jupyterlab-kernelspy)
* Create a new Notebook and open Kernel Spy
* Run some cells
* All kernel responses are expected to have the same session Id in the header.
However with deno, all of the responses contain different Session Ids.

This causes a few issues with Jupyter lab as well, fortunately it does work, but throws a few errors (that are ignored).
Here's where the session id is captured [this._kernelSession = reply.header.session;](https://github.com/jupyterlab/jupyterlab/blob/78cd6b60e5eb43b1278d825290ac81fd378faed6/packages/services/src/kernel/default.ts#L610)
& here's where the session id is validated and error thrown
https://github.com/jupyterlab/jupyterlab/blob/78cd6b60e5eb43b1278d825290ac81fd378faed6/packages/services/src/kernel/default.ts#L1145-L1153

Documentation on session id can be found here  https://jupyter-client.readthedocs.io/en/latest/messaging.html#message-header

<details>
  <summary>Here's a screenshot of Python kernel returning the same session id `a9afb6dc-2cd09f98a3940f3f1ba6b705` being returned by the kernel in all responses.
</summary>
  
Image

</details>

<details>
  <summary>In contrast the deno kernel always returns new/unique session ids. (supposed to use 2040024b-c6eb-4616-a930-a6343db2b4f5)
</summary>
  

Image

</details>

@rgbkrk /cc

FYI, this used to work in some older version of deno, unfortunately I didn't check the version of Deno i had installed before updating to the latest version.

### PR DESCRIPTION
**Pull request by rgbkrk**
Closes #24737, #24437.

image

### CODE REVIEW

File: tests/integration/jupyter_tests.rs [hunk 1]
```diff
@@ -493,7 +493,7 @@ async fn jupyter_heartbeat_echoes() -> Result<()> {
   let (_ctx, client, _process) = setup().await;
   client.send_heartbeat(b"ping").await?;
   let msg = client.recv_heartbeat().await?;
-  assert_eq!(msg, Bytes::from_static(b"ping"));
```
Comment (bartlomieju) [inline tests/integration/jupyter_tests.rs:496]: Ah, nice catch!

**Review by bartlomieju — APPROVED** [review]
LGTM, good fix 👍
