### PR TITLE
fix(lsp): cannot read config option in windows

### LINKED ISSUE #10747: Updating tsconfig has errored: Failed to load configuration file
### Reproducible steps

1. Prepare the following environment.
```
> systeminfo
OS Name:                   Microsoft Windows 10 Pro N
OS Version:                10.0.19042 N/A Build 19042
> code --version
1.56.2
054a9295330880ed74ceaedda236253b4f39a335
x64
> deno --version
deno 1.10.2 (release, x86_64-pc-windows-msvc)
v8 9.1.269.27
typescript 4.2.2
> # vscode_deno: v3.4.0
```
2. Execute the following commands.
```
git clone https://github.com/jeiea/deno_report.git
cd deno_report
code .
```
3. Open a.ts

### Expected behavior

There should be no error.

### Actual behavior

image

### Additional context

The following is 'Deno Language Server' panel output.
```
Starting Deno language server...
  version: 1.10.2 (release, x86_64-pc-windows-msvc)
Connected to "Visual Studio Code" 1.56.2
{"type":"mark","name":"update_tsconfig"},
Updating TypeScript configuration from: "./deno.tsconfig.json"
Updating tsconfig has errored: Failed to load configuration file
{"type":"mark","name":"request","count":1,"args":{"id":2,"method":"getSupportedCodeFixes"}},
{"type":"measure","name":"request","count":1,"duration":1},
{"type":"measure","name":"initialize","count":1,"duration":76},
language server initialized
{"type":"mark","name":"update_import_map"},
{"type":"measure","name":"update_import_map","count":1,"duration":0},
{"type":"mark","name":"update_registries"},
{"type":"measure","name":"update_registries","count":1,"duration":0},
Server ready.
```

I know denoland/vscode_deno#413 is similar to this but I'm using deno 1.10.2.

### PR DESCRIPTION
**Pull request by jeiea**
Currently lsp can't read correct --config option in windows. It is a regression because 1.7 didn't have this problem.

Close #10747.

### CODE REVIEW

File: cli/tests/integration_tests_lsp.rs [hunk 1]
```diff
@@ -31,7 +33,10 @@ fn init(init_path: &str) -> LspClient {
   client
 }
 
-fn did_open<V>(client: &mut LspClient, params: V)
+fn did_open<V>(
+  client: &mut LspClient,
+  params: V,
+) -> Vec<PublishDiagnosticsParams>
```
Comment (kitsonk) [inline cli/tests/integration_tests_lsp.rs:39]:
```suggestion
) -> Vec<lsp::PublishDiagnosticsParams>
```

And remove the use clause for it above.

File: cli/tests/integration_tests_lsp.rs [hunk 2]
```diff
@@ -66,6 +75,50 @@ fn lsp_startup_shutdown() {
   shutdown(&mut client);
 }
 
+#[test]
+fn lsp_init_tsconfig() {
+  let temp_dir = TempDir::new().expect("could not create temp dir");
+  let mut params: InitializeParams =
```
Comment (kitsonk) [inline cli/tests/integration_tests_lsp.rs:81]:
```suggestion
  let mut params: lsp::InitializeParams =
```

And remove the use above for `InitializeParams`.

File: cli/tests/integration_tests_lsp.rs [hunk 3]
```diff
@@ -66,6 +75,50 @@ fn lsp_startup_shutdown() {
...
+    serde_json::from_value(load_fixture("initialize_params.json")).unwrap();
+  let tsconfig =
+    serde_json::to_vec_pretty(&load_fixture("lib.tsconfig.json")).unwrap();
+  fs::write(temp_dir.path().join("lib.tsconfig.json"), tsconfig).unwrap();
+
+  params.root_uri = Some(Url::from_file_path(temp_dir.path()).unwrap());
+  if let Some(Value::Object(mut map)) = params.initialization_options {
+    map.insert(
+      "config".to_owned(),
+      Value::String("./lib.tsconfig.json".to_owned()),
```
Comment (kitsonk) [inline cli/tests/integration_tests_lsp.rs:91]:
```suggestion
      json!("./lib.tsconfig.json"),
```

File: cli/tests/integration_tests_lsp.rs [hunk 4]
```diff
@@ -66,6 +75,50 @@ fn lsp_startup_shutdown() {
...
+  let mut params: InitializeParams =
+    serde_json::from_value(load_fixture("initialize_params.json")).unwrap();
+  let tsconfig =
+    serde_json::to_vec_pretty(&load_fixture("lib.tsconfig.json")).unwrap();
+  fs::write(temp_dir.path().join("lib.tsconfig.json"), tsconfig).unwrap();
+
+  params.root_uri = Some(Url::from_file_path(temp_dir.path()).unwrap());
+  if let Some(Value::Object(mut map)) = params.initialization_options {
+    map.insert(
+      "config".to_owned(),
```
Comment (kitsonk) [inline cli/tests/integration_tests_lsp.rs:90]:
```suggestion
      "config".to_string(),
```

File: cli/tests/integration_tests_lsp.rs [hunk 5]
```diff
@@ -66,6 +75,50 @@ fn lsp_startup_shutdown() {
...
+        "uri": "file:///a/file.ts",
+        "languageId": "typescript",
+        "version": 1,
+        "text": "location.pathname;\n"
+      }
+    }),
+  );
+
+  let issues = diagnostics.into_iter().flat_map(|x| x.diagnostics);
+  assert_eq!(issues.count(), 0);
```
Comment (kitsonk) [inline cli/tests/integration_tests_lsp.rs:117]:
```suggestion
  let diagnostics = diagnostics.into_iter().flat_map(|x| x.diagnostics);
  assert_eq!(diagnostics.count(), 0);
```

**Review by kitsonk — COMMENTED** [review]
Thank you for the contribution. A couple comments on the tests.

**Comment by jeiea** [comment]
@kitsonk Could you relaunch ci checks?

**Review by kitsonk — APPROVED** [review]
LGTM, thanks for contributing.
