### PR TITLE
fix(cli/fmt): show filepath for InvalidData error

### LINKED ISSUE #17253: cli/fmt: include file path in error message
```
➜  example tree .
.
├── binary.json
├── good.json
└── main.ts

0 directories, 3 files
➜  example deno fmt
error: invalid data
```

The `binary.json` has a JSON extension but isn't JSON underneath. When we run `deno fmt` in the folder, we get the following error which is not very helpful. `Invalid data` is helpful but it would more helpful to know the file responsible for the error.

### PR DESCRIPTION
**Pull request by crowlKats**
Closes #17253

### CODE REVIEW

File: cli/tools/fmt.rs [hunk 1]
```diff
@@ -575,7 +575,8 @@ fn read_file_contents(file_path: &Path) -> Result<FileContents, AnyError> {
   let file_bytes = fs::read(file_path)
     .with_context(|| format!("Error reading {}", file_path.display()))?;
   let charset = text_encoding::detect_charset(&file_bytes);
-  let file_text = text_encoding::convert_to_utf8(&file_bytes, charset)?;
+  let file_text = text_encoding::convert_to_utf8(&file_bytes, charset)
+    .context(file_path.display().to_string())?;
```
Comment (bartlomieju) [inline cli/tools/fmt.rs:579]:
```suggestion
    .with_context(|| format!("{} is not a valid UTF-8 file", file_path.display()))?;
```

File: cli/tests/testdata/fmt/invalid_data.out [hunk 2]
```diff
@@ -0,0 +1,4 @@
+error: [WILDCARD] is not a valid UTF-8 file
+
+Caused by:
+    invalid data
```
Comment (bartlomieju) [inline cli/tests/testdata/fmt/invalid_data.out:4]: Looking at this error... I think we should do `map_err()` instead of `with_context()`. "caused by: invalid data" provides no value to the user here

**Review by bartlomieju — CHANGES_REQUESTED** [review]
LGTM

**Review by bartlomieju — APPROVED** [review]
