### PR TITLE
fix(cache): do not attempt to emit non-emitable files

### LINKED ISSUE #15558: `deno cache` fails with JSON imports
**test.ts**

```ts
import asd from "./test.json" assert { type: "json" };
```

**test.json**

```json
{
  "foo": {
    "bar": 1
  }
}
```

```
$ deno --version
deno 1.24.3+ecf3b51 (canary, x86_64-unknown-linux-gnu)
v8 10.5.218.2
typescript 4.7.4
$ deno cache test.ts
error: Expected ';', '}' or <eof> at file:///mnt/artemis/Projects/github.com/denoland/fresh/test.json:2:8
```

It seems to treat the file as JS instead of as JSON.

### PR DESCRIPTION
**Pull request by dsherret**
Closes #15558

### CODE REVIEW

File: cli/tests/integration/cache_tests.rs [hunk 1]
```diff
@@ -92,3 +92,8 @@ itest!(check_local_by_default2 {
   output: "cache/check_local_by_default2.out",
   http_server: true,
 });
+
+itest!(json_import {
+  args: "cache --quiet cache/json_import/main.ts",
+  output: "cache/json_import/main.out",
```
Comment (dsherret) [inline cli/tests/integration/cache_tests.rs:98]: Oh, I just realized this is empty. Wonder what I can do to avoid an empty file.

Comment (dsherret) [reply cli/tests/integration/cache_tests.rs]: I updated the test util to allow not providing anything.

Comment (nayeemrmn) [reply cli/tests/integration/cache_tests.rs]: > Wonder what I can do to avoid an empty file.

`output_str: Some("")` but good addition anyway
