### PR TITLE
fix(repl): remove check flags

### LINKED ISSUE #26042: `deno repl --check` doesn't check types
`--check` option of `repl` subcommand says:

```
--check[=<CHECK_TYPE>]        Enable type-checking. This subcommand does not type-check by default
```

But it actually doesn't check types.

```
$ deno repl --check
Deno 2.0.0-rc.10+ac73b10
exit using ctrl+d, ctrl+c, or close()
> let a: string = 1;
undefined
> a
1
```

Should we remove `--check` option from `deno repl` command?

### PR DESCRIPTION
**Pull request by kt3k**
This PR removes the handling of `--check` and `--no-check` flags from `deno repl` subcommand.

Currently these flags don't have effects, and the help output for these options are incorrect and confusing.

closes #26042

### CODE REVIEW

File: cli/args/flags.rs [hunk 1]
```diff
@@ -2767,8 +2767,13 @@ It is especially useful for quick prototyping and checking snippets of code.
 
 TypeScript is supported, however it is not type-checked, only transpiled."
   ), UnstableArgsConfig::ResolutionAndRuntime)
-    .defer(|cmd| runtime_args(cmd, true, true)
-      .arg(check_arg(false))
+    .defer(|cmd| {
+      let cmd = compile_args_without_check_args(cmd);
```
Comment (satyarohith) [inline cli/args/flags.rs:2771]: Instead of expanding calls from runtime_args to here, what do you think about adding an option to runtime_args() and runtime_args_parse() that excludes the `check/no-check` flags?

Comment (kt3k) [reply cli/args/flags.rs:2771]: Introducing a new flag for only supporting single case would be less readable in my opinion.

Also currently `runtime_args` only adds `no-check` (`check` is not added). If we introduce the flag for it, I feel what that flag does will be confusing.

**Review by satyarohith — APPROVED** [review]
LGTM

**Review by bartlomieju — APPROVED** [review]
