### PR TITLE
fix(ext/node): return relative path from fs.watch with recursive option

### LINKED ISSUE #33419: `fs.watch` with `recursive: true`: inconsistent filename (basename vs relative path)
Version: Deno 2.7.12

Hi,

I would like to report a behavior in Deno that can be reproduced using the below PoC:

1. watcher.mjs
```javascript
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const srcDir = path.join(__dirname, "src");

if (!fs.existsSync(srcDir)) {
  fs.mkdirSync(srcDir, { recursive: true });
}

console.log("Watching:", srcDir);

fs.watch(srcDir, { recursive: true }, (event, file) => {
  console.log("EVENT:", event, "FILE:", file);
});

// Keep process alive long enough to perform manual steps
setTimeout(() => {
  console.log("Exiting watcher after timeout");
  process.exit(0);
}, 600000);
```
2. trigger.mjs
```javascript
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const srcDir = path.join(__dirname, "src");

// Step 1: ensure base src dir exists
if (!fs.existsSync(srcDir)) {
  fs.mkdirSync(srcDir, { recursive: true });
}

// Step 2: create a file directly in src (should be logged)
const file1 = path.join(srcDir, "file1.txt");
fs.writeFileSync(file1, "root file\n");

// Step 3: create a new subdirectory (should be logged)
const subDir = path.join(srcDir, "subdir1");
if (!fs.existsSync(subDir)) {
  fs.mkdirSync(subDir, { recursive: true });
}

// Small delay before creating file inside new subdir
setTimeout(() => {
  // Step 4: create a file inside the new subdirectory
  // Expected (per Node semantics): this should also be logged when recursive: true
  const nestedFile = path.join(subDir, "nested.txt");
  fs.writeFileSync(nestedFile, "nested file\n");
  console.log("Created nested file:", nestedFile);
}, 1000);
```
4. Run command: `deno run -A watcher.mjs & sleep 2 && deno run -A trigger.mjs`

### Expected output
Filename is consistent for subdir1/nested.txt for change event
```
root@KContainer:~/15939# node watcher.mjs & sleep 2 && node trigger.mjs
[2] 1013
Watching: /home/c01kele/15939/src
EVENT: change FILE: file1.txt
EVENT: change FILE: file1.txt
EVENT: change FILE: file1.txt
EVENT: change FILE: file1.txt
EVENT: change FILE: subdir1/nested.txt
EVENT: change FILE: subdir1/nested.txt
EVENT: change FILE: subdir1/nested.txt
EVENT: change FILE: subdir1/nested.txt
Created nested file: /home/c01kele/15939/src/subdir1/nested.txt
```

### Actual output
When using `fs.watch()` with `{ recursive: true }`, the filename argument is inconsistent for nested files. For change events for the same file, the callback sometimes receives:
1. nested.txt
2. subdir1/nested.txt
This makes it unreliable to reconstruct the full path of the changed file.
```
root@KContainer:~/15939# deno run -A watcher.mjs & sleep 2 && deno run -A trigger.mjs
[3] 1028
Watching: /home/c01kele/15939/src
EVENT: change FILE: file1.txt
EVENT: change FILE: file1.txt
EVENT: change FILE: file1.txt
EVENT: change FILE: file1.txt
EVENT: change FILE: file1.txt
EVENT: change FILE: file1.txt
EVENT: change FILE: file1.txt
Created nested file: /home/c01kele/15939/src/subdir1/nested.txt
EVENT: change FILE: nested.txt
EVENT: change FILE: nested.txt
EVENT: change FILE: subdir1/nested.txt
EVENT: change FILE: nested.txt
EVENT: change FILE: subdir1/nested.txt
EVENT: change FILE: subdir1/nested.txt
EVENT: change FILE: subdir1/nested.txt
```

### PR DESCRIPTION
**Pull request by bartlomieju**
## Summary

Closes #33419

`fs.watch()` with `{ recursive: true }` was always passing `basename()` of the changed file path to the callback. Node.js returns the **relative path** from the watched directory for recursive watches (e.g. `"subdir/file.txt"` instead of just `"file.txt"`).

Fix: use `path.relative(watchedDir, changedPath)` for recursive watches and `basename()` for non-recursive, matching Node.js behavior. Applied to both the callback-style `fs.watch()` and the async iterable `fs.promises.watch()`.

## Test plan

Before:
```
EVENT: change FILE: nested.txt      // wrong - just basename
EVENT: change FILE: subdir1/nested.txt
```

After:
```
EVENT: change FILE: subdir1/nested.txt   // consistent relative path
EVENT: change FILE: subdir1/nested.txt
```

### CODE REVIEW

File: tests/unit_node/fs_test.ts [hunk 1]
```diff
@@ -1884,3 +1885,44 @@ Deno.test(
     }
   },
 );
+
+Deno.test({
+  name: "[node/fs] watch recursive returns relative path for nested files",
+  ignore: Deno.build.os === "windows",
```
Comment (fibibot) [inline tests/unit_node/fs_test.ts:1891]: Add `|| Deno.build.os === "darwin"` here, or convert to `unsupported: { darwin: ..., windows: ... }` — macOS recursive watches use FSEvents which only fires directory-granularity events, so `val.paths[0]` is the parent dir and `relative()` returns `"sub"`, not `"sub/test.txt"`.

File: tests/unit_node/fs_test.ts [hunk 2]
```diff
@@ -1884,3 +1885,44 @@ Deno.test(
...
+
+      // Small delay to let the watcher start
+      await new Promise((r) => setTimeout(r, 100));
+      writeFileSync(join(subdir, "test.txt"), "hello");
+
+      await promise;
+      watcher.close();
+
+      const hasRelative = filenames.some((f) =>
+        f === join("sub", "test.txt") || f === "sub/test.txt"
```
Comment (fibibot) [inline tests/unit_node/fs_test.ts]: If you want this test to also exercise the macOS path, replace the equality check with `f.startsWith("sub")` or `f === "sub" || f === "sub/test.txt"`. Today macOS receives only `"sub"` (which is the correct relative path of the directory event the OS gave us), so the assertion fails CI.

**Review by fibibot — CHANGES_REQUESTED** [review]
The fix in `fs.ts` is right — `relative(resolvedWatchPath, val.paths[0])` for recursive watches is what Node does, and applying it to both `watch()` and `watchPromise()` keeps the two surfaces consistent. The `realpathSync(watchPath)` step is also necessary because `Deno.watchFs` returns symlink-resolved paths.

The blocker is the new unit test on macOS: `[node/fs] watch recursive returns relative path for nested files` fails with `Expected relative path like "sub/test.txt", got: sub`. That's not a bug in the polyfill — macOS FSEvents (which `Deno.watchFs`'s recursive mode is built on) only delivers directory-granularity events, so `val.paths[0]` is `/tmp/…/sub` and the new `relative()` call correctly produces `"sub"`. Node behaves the same way on macOS for the same reason.

Easiest fix is to either (a) add `Deno.build.os === "darwin"` to the existing `ignore`, (b) loosen the assertion to `f.startsWith("sub")` so the directory-level event still passes, or (c) swap the test to a non-recursive watch on `subdir` directly, where Linux/macOS both produce `test.txt`.

**Review by fibibot — APPROVED** [review]
LGTM. The follow-up commit `2c92efeb` ("fix(test): loosen fs.watch recursive assertion for macOS FSEvents") addresses the prior CHANGES_REQUESTED exactly:

- Assertion changed from strict `f === "sub/test.txt"` to `f.startsWith("sub")` so macOS's directory-granularity FSEvents (`"sub"`) and Linux/Windows's file-granularity events (`"sub/test.txt"`) both pass.
- Added a comment justifying the looser check, anchored to the FSEvents behaviour.

The substantive fix in `fs.ts` (`relative(resolvedWatchPath, val.paths[0])` for recursive watches in both `watch()` and `watchPromise()`, with `realpathSync` to handle the `/var → /private/var` case) is unchanged from the prior pass. The follow-up merge commit (`50283297`) is just resolving the trivial fs_test.ts conflict against main. CI is rerunning with 0 failures so far.
