### PR TITLE
fix(ext/node): Support returning tokens and option defaults in `node:util.parseArgs`

### LINKED ISSUE #22454: node compat: parseArgs doesn't support `default` option
Version: Deno 1.40.5

<del>

```ts
import { parseArgs } from "node:util";

const parsedArgs = parseArgs({
  options: { hello: { type: "string" } },
  allowPositionals: true,
});

console.log(parsedArgs);
```

`node a.js --args hello a`
```
{ values: [Object: null prototype] { hello: 'a' }, positionals: [] }
```

`deno run a.js --args hello a`

```
error: Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'execArgv')
const parsedArgs = parseArgs({
                   ^
    at getMainArgs (ext:deno_node/internal/util/parse_args/parse_args.js:53:28)
    at parseArgs (ext:deno_node/internal/util/parse_args/parse_args.js:162:48)
    at file:///home/mrcool/dev/lab/c/a.js:3:20
```

</del>

the above is already tracked by  https://github.com/denoland/deno/issues/22363

But the behavior is still not the same

```ts
import { parseArgs } from "node:util";

const parsedArgs = parseArgs({
  args: [],
  options: {
    handler: {
      type: "string",
      default: "hello",
    },
  },
});

console.log(parsedArgs.values.handler);
```

Running with not arguments

deno -> undefined
nodejs -> hello

### LINKED ISSUE #23179: parseArgs from node:util doesn't support tokens
Version: Deno 1.41.1

https://nodejs.org/api/util.html#parseargs-tokens

Specifically the error is popping up in Observable Framework here https://github.com/observablehq/framework/blob/f85e0d81abcdfd9d1e193d2e18b4c67eb6ae74a4/src/bin/observable.ts#L25-L59

To reproduce:
```
# npm init @observablehq
# cd hello-framework
# deno task dev
Task dev observable preview
error: Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'find')
    at file:///Users/ry/src/hello-framework/node_modules/.deno/@observablehq+framework@1.2.0/node_modules/@observablehq/framework/dist/bin/observable.js:36:20
```

### PR DESCRIPTION
**Pull request by nathanwhit**
Fixes #23179.
Fixes #22454.

Enables passing `{tokens: true}` to `parseArgs` and setting default values for options.

With this PR, the observable framework works with deno out of the box (no unstable flags needed).

The existing code was basically copied straight from node, so this PR mostly just updates that (out of date) vendored code. Also fixes some issues with error exports (before this PR, in certain error cases we were attempting to construct error classes that weren't actually in scope).

The last change (in the second commit) adds a small hack so that we actually exercise the `test-parse-args.js` node_compat test, previously it was reported as passing though it should have failed. That test now passes.

### CODE REVIEW

File: ext/node/polyfills/internal/util/parse_args/parse_args.js [hunk 1]
```diff
@@ -160,71 +148,56 @@ function storeOption(longOption, optionValue, options, values) {
...
+ * @param {string} longOption - long option name e.g. 'foo'
+ * @param {string
+ *         | boolean
+ *         | string[]
+ *         | boolean[]} optionValue - default value from option config
+ * @param {object} values - option values returned in `values` by parseArgs
+ */
+function storeDefaultOption(longOption, optionValue, values) {
+  if (longOption === "__proto__") {
+    return; // No. Just no.
```
Comment (bartlomieju) [inline ext/node/polyfills/internal/util/parse_args/parse_args.js:162]: 🙃

**Review by bartlomieju — APPROVED** [review]
LGTM!
