### PR TITLE
fix(check): regression where config "types" entries caused type checking errors

### LINKED ISSUE #18117: Type checking fails because of .d.ts being included twice
Since `1.31.2` it seems like files in `types/` are included twice when including using `compilerOptions.types` in `deno.json`. First they're checked with `.d.ts` ending, then with `.d.ts.d.ts` ending (which wierdly enough works, even though the files does not exist). Then type checker complains that everything in the files are already declared.

### Minimal steps to reproduce

Content of **deno.json**
```json
{
    "compilerOptions": {
        "types": [
            "./types/wat.d.ts"
        ]
    }
}
```

Content of **types/wat.d.ts**
```
declare class wat {
    static wat(): void;
}
```

Content of **main.ts**
```
console.log("Hello world!");
```

**Outcome**

Running `deno check main.ts`

```
TS2300 [ERROR]: Duplicate identifier 'wat'.
declare class wat {
              ~~~
    at /typestest/types/wat.d.ts.d.ts:1:15    

    'wat' was also declared here.
    declare class wat {
                  ~~~
        at /typestest/types/wat.d.ts:1:15
```

### Findings

Including types using the pattern `// @deno-types="../types/wat.d.ts"` instead of `deno.json: compilerOptions.types.wat` makes the problem go away.

Possibly related to PR #18026 

Everything is ok in previous version `1.31.1`

### Additional info

**Platform:** Windows 10 / Powershell / VS Code / Deno 1.31.2

### LINKED ISSUE #18121: Type checking does an excessive amount of fs::exists calls that don't apply to Deno when a config file exists
On startup, type checking does about 12,000 `fs::exists` calls looking for `node_modules/<lib...>` paths (ex. `file:///V:/deno/cli/tests/node_modules/@typescript/lib-esnext/index.jsx`).

We should investigate how to disable this.

Edit: It's about 12,000 nested one directory deep from the file system root with a config file, and fast without a config file because then it doesn't have a cwd for some reason.

### PR DESCRIPTION
**Pull request by dsherret**
Closes #18117
Closes #18121 (this is just over 10ms faster in a directory one up from the root folder)

cc @nayeemrmn

### CODE REVIEW

File: cli/tests/integration/run_tests.rs [hunk 1]
```diff
@@ -826,15 +826,15 @@ itest!(config {
 
 itest!(config_types {
   args:
-    "run --reload --quiet --config run/config_types/tsconfig.json run/config_types/main.ts",
+    "run --reload --quiet --config --check=all run/config_types/tsconfig.json run/config_types/main.ts",
```
Comment (dsherret) [inline cli/tests/integration/run_tests.rs:829]: This regression was not caught because these tests weren't type checking due to the change to not type check by default.

File: cli/args/config_file.rs [hunk 2]
```diff
@@ -185,10 +185,16 @@ fn parse_compiler_options(
...
   for (key, value) in compiler_options.iter() {
     let key = key.as_str();
-    if IGNORED_COMPILER_OPTIONS.contains(&key) {
-      items.push(key.to_string());
-    } else {
-      filtered.insert(key.to_string(), value.to_owned());
+    // We don't pass "types" entries to typescript via the compiler
+    // options and instead provide those to tsc as "roots". This is
+    // because our "types" behavior is at odds with how TypeScript's
+    // "types" works.
```
Comment (dsherret) [inline cli/args/config_file.rs:191]: I think Nayeem is right in this comment: https://github.com/denoland/deno/pull/10999/files#r652967963

File: cli/build.rs [hunk 3]
```diff
@@ -177,16 +177,6 @@ mod ts {
...
 
-    #[op]
-    fn op_cwd() -> String {
-      "cache:///".into()
-    }
-
-    #[op]
-    fn op_exists() -> bool {
-      false
-    }
```
Comment (dsherret) [inline cli/build.rs:188]: Reverts the changes made in #10999 which was the source of #18121

File: cli/tools/check.rs [hunk 4]
```diff
@@ -230,6 +230,41 @@ fn get_tsc_roots(
   graph: &ModuleGraph,
   check_js: bool,
 ) -> Vec<(ModuleSpecifier, MediaType)> {
+  fn try_get_check_entry(
+    module: &deno_graph::Module,
+    check_js: bool,
+  ) -> Option<(ModuleSpecifier, MediaType)> {
```
Comment (nayeemrmn) [inline cli/tools/check.rs:236]: nit: `maybe_get_check_entry`?

**Review by bartlomieju — APPROVED** [review]
LGTM, great catch David. Looking forward to the benchmark results from this change
