### PR TITLE
fix(ext/kv): send queue wake messages accross different kv instances

### LINKED ISSUE #20454: KV queues don't work if different KV instances are used for enqueue and queueListen
repro:
```
const kv = await Deno.openKv();
kv.listenQueue(async (msg) => {
  console.log("Delivered", msg);
});
console.log("Listening for messages...");

const kv2 = await Deno.openKv();
Deno.serve((_req) => {
  kv2.enqueue("foo");
  return new Response("Hello, World!");
});
```

the following works:
```
const kv = await Deno.openKv();
kv.listenQueue(async (msg) => {
  console.log("Delivered", msg);
});
console.log("Listening for messages...");

Deno.serve((_req) => {
  kv.enqueue("foo");
  return new Response("Hello, World!");
});
```

### PR DESCRIPTION
**Pull request by igorzi**
fixes #20454

Current KV queues implementation assumes that `enqueue` and `listenQueue` are called on the same instance of `Deno.Kv`. It's possible that the same Deno process opens multiple KV instances pointing to the same fs path, and in that case `listenQueue` should still get notified of messages enqueued through a different KV instance.

### CODE REVIEW

File: ext/kv/sqlite.rs [hunk 1]
```diff
@@ -212,30 +215,34 @@ impl<P: SqliteDbHandlerPermissions> DatabaseHandler for SqliteDbHandler<P> {
...
+                let flags =
+                  OpenFlags::default().difference(OpenFlags::SQLITE_OPEN_URI);
+                (
+                  rusqlite::Connection::open_with_flags(path, flags)?,
+                  Some(PathBuf::from(path)),
+                )
+              }
+              (None, Some(path)) => {
+                std::fs::create_dir_all(path)?;
+                let path = path.join("kv.sqlite3");
```
Comment (losfair) [inline ext/kv/sqlite.rs:238]: The path needs to be resolved (relative to absolute, symlink resolution) before used as the key

**Review by losfair — COMMENTED** [review]
This still doesn't handle the case where a message is enqueued in one process but the listener is in another process?

I think a better solution would be to periodically (with a very low frequency) wake up the queue listener even if there are no locally-enqueued messages.

**Comment by igorzi** [comment]
> This still doesn't handle the case where a message is enqueued in one process but the listener is in another process?
> 
> I think a better solution would be to periodically (with a very low frequency) wake up the queue listener even if there are no locally-enqueued messages.

Correct, this doesn't take care of cross-process enqueue/dequeue. I propose to handle that in a separate PR, either through a periodic wake-up, or using some cross-process channel (e.g. fs).

File: ext/kv/sqlite.rs (hunk 1 above)
Comment (igorzi) [reply ext/kv/sqlite.rs:238]: This path is already absolute. Why is the resolution needed?

Comment (losfair) [reply ext/kv/sqlite.rs:238]: Sorry, this comment should be on the `(Some(path), _)` case - resolution is needed for that case because `path` is a user-provided string.

Comment (igorzi) [reply ext/kv/sqlite.rs:238]: Ah, thanks!

**Review by losfair — APPROVED** [review]
LGTM
