### PR TITLE
fix(ext/node): prevent derefencing symlinks on `fs.rm`

### LINKED ISSUE #31840: `fs.rm` behavior is different from Node.js
Version: Deno 2.6.4 Node 25.3.0
OS: Linux

Reproduce:

```js
// main.js
import fs from 'node:fs/promises';

await fs.rm('bar');
```

- `mkdir foo`
- `ln -s foo bar`
- `node main.js` -> No errors
- `ln -s foo bar`
- `deno --allow-all main.js` -> Uncaught (in promise) SystemError: Path is a directory: rm returned EISDIR (is a directory) bar

### PR DESCRIPTION
**Pull request by Tango992**
Closes #31840 and also addresses `prefer-primordials` rule

### CODE REVIEW

File: ext/node/ops/winerror.rs [hunk 1]
```diff
@@ -115,6 +114,7 @@ pub fn op_node_sys_to_uv_error(err: i32) -> String {
     WSAENOTSOCK => "ENOTSOCK",
     ERROR_NOT_SUPPORTED => "ENOTSUP",
     ERROR_BROKEN_PIPE => "EOF",
+    ERROR_ACCESS_DENIED => "EPERM",
```
Comment (Tango992) [inline ext/node/ops/winerror.rs:117]: ref: https://github.com/nodejs/node/blob/70f6b58ac655234435a99d72b857dd7b316d34bf/deps/uv/src/win/error.c#L158

File: tests/node_compat/config.json [hunk 2]
```diff
@@ -535,6 +535,10 @@
     "parallel/test-fs-ready-event-stream.js": {},
     "parallel/test-fs-realpath-buffer-encoding.js": {},
     "parallel/test-fs-rename-type-check.js": {},
+    "parallel/test-fs-rm.js": {
+      "darwin": false,
+      "windows": false
+    },
```
Comment (Tango992) [inline tests/node_compat/config.json:541]: macos and windows fail on these cases: https://github.com/nodejs/node/blob/v24.12.0/test/parallel/test-fs-rm.js#L513-L562. since it's not related with the issue, I think it's better to solve it on a separate PR
