### PR TITLE
fix: 'Promise was collected' error in REPL/jupyter

### LINKED ISSUE #20528: [repl][jupyter-kernel] {"code":-32000,"message":"Promise was collected"}
Sometimes instead of the result I would expect, this error comes up:

```
{"code":-32000,"message":"Promise was collected"}
```

It goes out as the current exception rather than the output for a cell. The cell seems to run fine still regardless.

image

This happens both in the REPL and in Jupyter.

### PR DESCRIPTION
**Pull request by bartlomieju**
Fixes #20528

### CODE REVIEW

File: cli/tools/repl/session.rs [hunk 1]
```diff
@@ -291,7 +297,17 @@ impl ReplSession {
...
-      .with_event_loop(self.session.post_message(method, params).boxed_local())
+      .js_runtime
+      .with_event_loop(
+        self.session.post_message(method, params).boxed_local(),
+        PollEventLoopOptions {
+          wait_for_inspector: false,
+          // NOTE(bartlomieju): this is an important bit; we don't want to pump V8
+          // message loop here, so that GC won't run. Otherwise, the resulting
+          // object might be GC'ed before we have a chance to inspect it.
+          pump_v8_message_loop: false,
```
Comment (bartlomieju) [inline cli/tools/repl/session.rs:308]: This is the fix :)

**Review by mmastrac — APPROVED** [review]
LGTM assuming test passes!

File: cli/tools/repl/session.rs (hunk 1 above)
Comment (rgbkrk) [reply cli/tools/repl/session.rs:308]: Wow. Thanks for noting it so heavily here.
