### PR TITLE
fix(runtime): fix Deno.hostname on windows

### LINKED ISSUE #16527: Deno.hostname() returns empty string on some situation on windows
On windows the following script prints an empty string (with canary):
```ts
console.log(Deno.hostname());
```

But the following script prints the correct hostname:

```ts
await fetch("https://example.com");
console.log(Deno.hostname());
```

There seems existing some precondition for `GetHostNameW` to working correctly ref: https://github.com/retep998/winapi-rs/issues/296

### PR DESCRIPTION
**Pull request by kt3k**
This PR tries to fix `Deno.hostname()` issue on windows. This change starts winsocket before calling `GetHostNameW` as suggested in https://github.com/retep998/winapi-rs/issues/296

closes #16527

### CODE REVIEW

File: runtime/ops/os/sys_info.rs [hunk 1]
```diff
@@ -131,15 +131,26 @@ pub fn hostname() -> String {
...
     let mut name: Vec<u16> = vec![0u16; namelen];
-    let err =
-      // SAFETY: length of wide string is 256 chars or less. 
+    let err = unsafe {
+      let mut data = mem::zeroed();
+      // Start winsock to make `GetHostNameW` work correctly
+      // https://github.com/retep998/winapi-rs/issues/296
+      let wsa_startup_result = WSAStartup(MAKEWORD(2, 2), &mut data);
+      if wsa_startup_result != 0 {
+        panic!("Failed to start winsocket");
```
Comment (dsherret) [inline runtime/ops/os/sys_info.rs:148]: Maybe we should return `String::from("")` in this case?

File: runtime/ops/os/sys_info.rs [hunk 2]
```diff
@@ -131,15 +131,26 @@ pub fn hostname() -> String {
...
+      }
```
Comment (littledivy) [inline runtime/ops/os/sys_info.rs:149]: This should be in a once_cell

**Review by littledivy — APPROVED** [review]

File: runtime/ops/os/sys_info.rs (hunk 1 above)
Comment (kt3k) [reply runtime/ops/os/sys_info.rs:153]: I agree. I'll try that in a later PR
