### PR TITLE
fix(ext/node): do not apply socket-init-workaround to ipc socket

### LINKED ISSUE #16899: NPM: Playwright does not work
Hi,

I'm trying to use [Playwright](https://github.com/microsoft/playwright) via the new NPM compatibility layer, but it fails with:

`Uncaught TypeError: browserType.launch: Cannot read properties of undefined (reading 'on')`

The following snippet can be used to reproduce the error:

```typescript
import { chromium } from 'npm:playwright';

async function main() {
  const browser = await chromium.launch({
    headless: false,
  });
  const page = await browser.newPage();
  await page.goto('http://example.com');
  await browser.close();
};

if (import.meta.main) {
  main()
}
```

After running the above via `deno run --unstable --allow-all main.ts`, the following message is displayed:

```
error: Uncaught Error: browserType.launch: Executable doesn't exist at /home/user/.cache/ms-playwright/chromium-1033/chrome-linux/chrome
╔═════════════════════════════════════════════════════════════════════════╗
║ Looks like Playwright Test or Playwright was just installed or updated. ║
║ Please run the following command to download new browsers:              ║
║                                                                         ║
║     npx playwright install                                              ║
║                                                                         ║
║ <3 Playwright Team                                                      ║
╚═════════════════════════════════════════════════════════════════════════╝
```

Executing `deno run --unstable --allow-all npm:playwright install` downloads the required binaries.

Executing `deno run --unstable --allow-all main.ts` again, leads to the above-mentioned error:

```
error: Uncaught TypeError: browserType.launch: Cannot read properties of undefined (reading 'on')
=========================== logs ===========================
<launching> /home/user/.cache/ms-playwright/chromium-1033/chrome-linux/chrome --disable-field-trial-config --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-back-forward-cache --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-component-update --no-default-browser-check --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,DialMediaRouteProvider,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater,AvoidUnnecessaryBeforeUnloadCheckSync,Translate --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --no-sandbox --user-data-dir=/tmp/playwright_chromiumdev_profile-4e2wKK --remote-debugging-pipe --no-startup-window
<launched> pid=835204
============================================================
```

`Playwright`/`Deno` was already discussed in https://github.com/denoland/deno/issues/16298, but I thought it makes sense to open an issue that focuses only on `Playwright`. There was also some discussion in the `Playwright` repo: https://github.com/microsoft/playwright/issues/3146

### LINKED ISSUE #27623: playwright tests have stopped working in deno v2.1.5
Version: Deno 2.1.5

The playwright tests have stopped working for me in my deno template: [https://github.com/dsm23/dsm23-deno-vite-spa-template](https://github.com/dsm23/dsm23-deno-vite-spa-template). Specifically, the `webServer` functionality in the playwright config.

When running locally and running the dev task in a separate window, the tests pass. It seems like playwright is no longer waiting for the command, `webServer.command` to finish and very quickly says that there is an error connecting to the port, in this case, 5173.

When downgrading to Deno v2.1.4, these tests pass locally and in the pipeline whether playwright is reusing an existing server or not

I am running on a Mac. The GitHub actions pipeline is ubuntu-latest.

### LINKED ISSUE #27658: playwright regression in 2.1.5 (BadResource: Bad resource ID)
This dockerfile builds successfully.

```Dockerfile
FROM denoland/deno:bin-2.1.4 AS deno
FROM debian:12-slim
COPY --from=deno /deno /usr/local/bin/deno
RUN deno run -A "npm:playwright@1.49.1" install chromium-headless-shell --with-deps
```

This dockerfile does not.

```Dockerfile
FROM denoland/deno:bin-2.1.5 AS deno
FROM debian:12-slim
COPY --from=deno /deno /usr/local/bin/deno
RUN deno run -A "npm:playwright@1.49.1" install chromium-headless-shell --with-deps
```

The only difference is the deno version from `2.1.4` to `2.1.5`.
Playwright fails to download the browsers and fails like this.

```txt
Downloading Chromium Headless Shell 131.0.6778.33 (playwright build v1148) from https://playwright.azureedge.net/builds/chromium/1148/chromium-headless-shell-linux.zip
BadResource: Bad resource ID
    at node:http:306:27
    at HttpsClientRequest._writeHeader (node:http:398:7)
    at HttpsClientRequest._flushHeaders (node:_http_outgoing:382:12)
    at onConnect (node:http:444:16)
    at node:http:451:11
    at processTicksAndRejections (ext:deno_node/_next_tick.ts:28:11)
    at runNextTicks (ext:deno_node/_next_tick.ts:76:3)
    at eventLoopTick (ext:core/01_core.js:182:21) {
  name: "BadResource"
}
```

Possibly similar to https://github.com/denoland/deno/issues/27629 but only because the error message looks similar & the regression appears to fit the timeline but I'm just a humble deno user, I'm no expert.

FWIW another issue related to 2.1.5 & playwright https://github.com/denoland/deno/issues/27623

### PR DESCRIPTION
**Pull request by kt3k**
This PR resolves 2 issues of Socket class of node compat (both are related to playwright)

Currently `browser.launch()` of playwright is not working. `browser.launch` opens PipeTransport (which is based on Pipe/IPC socket) with the browser process. But that pipe doesn't start reading the data because of the workaround #27662 (which pauses the socket at the beginning if it's from playwright-core). This PR fixes this issue by checking whether the given handle is `ipc` handle or not.

Another issue is that sock-init-workaround for TLS connection stopped working at #27707 because of the changes of TLS socket initialization steps. This change fixes the issue by correctly returning the function in workaround path.

The added case `specs::npm::playwright_compat` checks both fixes with actual playwright and playwright-core packages.

`browser.launch` issues
closes #16899
closes #27623 

`https.request` issue
closes #27658

- [x] write test case

### CODE REVIEW

File: tests/specs/npm/playwright_compat/main.ts [hunk 1]
```diff
@@ -0,0 +1,4 @@
+import { chromium } from "npm:playwright";
+await chromium.launch();
+console.log("chromium launched");
```
Comment (bartlomieju) [inline tests/specs/npm/playwright_compat/main.ts:3]: Does this actually work on CI?

Comment (kt3k) [reply tests/specs/npm/playwright_compat/main.ts:3]: I suppose so. The first step in this spec test `run -A npm:playwright install chromium` should be downloading the chromium for this platform.

Comment (satyarohith) [reply tests/specs/npm/playwright_compat/main.ts:3]: If it's not cached already, it's worth looking into caching the chromium artifact.

Comment (kt3k) [reply tests/specs/npm/playwright_compat/main.ts:3]: Added browser binary cache at key `playwright-${{ runner.os }}-${{ runner.arch }}`

Looks it's been saved successfully

Screenshot 2025-01-27 at 17 25 25

https://github.com/denoland/deno/actions/runs/12984044432/job/36206262673

Comment (bartlomieju) [reply tests/specs/npm/playwright_compat/main.ts:3]: Thanks for confirming

**Review by bartlomieju — APPROVED** [review]
LGTM!

**Comment by nshiab** [comment]
Do you know when this will be part of an official release? Thank you!

**Comment by bartlomieju** [comment]
In 2.2 next week. You can upgrade to canary in the meantime (`deno upgrade --canary`)

**Comment by nshiab** [comment]
Amazing! Thanks!
