### PR TITLE
fix(node): support advanced serialization in IPC

### LINKED ISSUE #31354: Deno 2.5.6 panics with Vitest 4.0.10
Deno 2.5.6 panics with Vitest 4.0.10.  You can find an example attached; just run "deno install && deno run test".  This issue started appearing with Vitest 4.0.10.  Vitest 4.0.9 still works fine.

[deno-panic-with-vitest.tar.gz](https://github.com/user-attachments/files/23638703/deno-panic-with-vitest.tar.gz)

### PR DESCRIPTION
**Pull request by nathanwhit**
Fixes #31354.

### CODE REVIEW

File: cli/args/mod.rs [hunk 1]
```diff
@@ -1469,7 +1482,7 @@ pub fn config_to_deno_graph_workspace_member(
 
 pub fn get_default_v8_flags() -> Vec<String> {
   vec![
-    "--stack-size=1024".to_string(),
+    "--stack-size=2048".to_string(),
```
[the remark this answers is not in the document]
Comment (nathanwhit) [reply cli/args/mod.rs]: Note: revert this

File: cli/args/mod.rs [hunk 2]
```diff
@@ -586,16 +587,28 @@ impl CliOptions {
...
     let maybe_node_channel_fd = std::env::var("NODE_CHANNEL_FD").ok();
+    let maybe_node_channel_serialization =
+      std::env::var("NODE_CHANNEL_SERIALIZATION_MODE")
+        .ok()
+        .and_then(|s| {
+          s.parse::<ChildIpcSerialization>()
+            .inspect_err(|e| {
+              log::warn!("Invalid node IPC serialization type: {}", e)
+            })
+            .ok()
```
Comment (bartlomieju) [inline cli/args/mod.rs]: Why is it just a warning an not a hard error that terminates the process?

Comment (nathanwhit) [reply cli/args/mod.rs]: fair enough

File: ext/node/ops/ipc.rs [hunk 3]
```diff
@@ -226,6 +273,509 @@ mod impl_ {
...
+    } else if view.is_float64_array() {
+      Some(8)
+    } else if view.is_data_view() {
+      Some(9)
+    } else if view.is_big_int64_array() {
+      Some(11)
+    } else if view.is_big_uint64_array() {
+      Some(12)
+    }
+    // else if view.is_float16_array() {
```
Comment (bartlomieju) [inline ext/node/ops/ipc.rs]: Can you open an issue in rusty_v8?

File: ext/node/ops/ipc.rs [hunk 4]
```diff
@@ -226,6 +273,509 @@ mod impl_ {
...
+    let constants = AdvancedIpcConstants {
+      buffer_constructor: v8::Global::new(scope, buffer_constructor),
+      constructor_key: v8::Global::new(
+        scope,
+        v8::String::new_from_utf8(
+          scope,
+          b"constructor",
+          v8::NewStringType::Internalized,
+        )
+        .unwrap(),
```
Comment (bartlomieju) [inline ext/node/ops/ipc.rs]: Wouldn't `v8_static_strings` or `OneByteConst` be better here?

File: ext/node/ops/ipc.rs [hunk 5]
```diff
@@ -226,6 +273,509 @@ mod impl_ {
...
+    scope: &mut v8::PinScope<'a, '_>,
+    state: Rc<RefCell<OpState>>,
+    #[smi] rid: ResourceId,
+    value: v8::Local<'a, v8::Value>,
+    // using an array as an "out parameter".
+    // index 0 is a boolean indicating whether the queue is under the limit.
+    //
+    // ideally we would just return `Result<(impl Future, bool), ..>`, but that's not
+    // supported by `op2` currently.
+    queue_ok: v8::Local<'a, v8::Array>,
```
Comment (bartlomieju) [inline ext/node/ops/ipc.rs:448]: Clever and thanks for the comment 👍

File: ext/node/ops/ipc.rs [hunk 6]
```diff
@@ -226,6 +273,509 @@ mod impl_ {
...
+  ) -> Result<impl Future<Output = Result<(), io::Error>> + use<>, IpcError> {
+    let constants = state.borrow().borrow::<AdvancedIpcConstants>().clone();
```
Comment (bartlomieju) [inline ext/node/ops/ipc.rs:450]: If we're cloning this a bunch I suggest to wrap `v8::Global` in `Rc` - it will be a lot cheaper to clone them

File: ext/node/ops/ipc.rs (hunk 4 above)
Comment (nathanwhit) [reply ext/node/ops/ipc.rs]: Those are slower for property accesses, since they go through the slow lookup routine in V8. In general if you're going to do a lot of lookups internalized strings are faster

File: ext/node/ops/ipc.rs [hunk 7]
```diff
@@ -226,6 +273,509 @@ mod impl_ {
...
+                .into()
+            }
+            11 => v8::BigInt64Array::new(
+              scope,
+              array_buffer,
+              0,
+              byte_length as usize / 8,
+            )
+            .unwrap()
+            .into(),
```
Comment (bartlomieju) [inline ext/node/ops/ipc.rs]: Are we really sure we want to `unwrap()` everywhere in this `match`?

File: ext/node/ops/ipc.rs (hunk 3 above)
Comment (nathanwhit) [reply ext/node/ops/ipc.rs]: The binding is already merged (I added it) but waiting on a deno_core update

File: ext/node/ops/ipc.rs [hunk 8]
```diff
@@ -226,6 +273,509 @@ mod impl_ {
...
+    obj.set(
+      scope,
+      v8::String::new_from_utf8(scope, b"cmd", v8::NewStringType::Internalized)
+        .unwrap()
+        .into(),
+      v8::String::new_from_utf8(
+        scope,
+        b"NODE_CLOSE",
+        v8::NewStringType::Internalized,
+      )
```
Comment (bartlomieju) [inline ext/node/ops/ipc.rs:730]: Ditto about `v8_static_string`/`OneByteConst`

File: ext/process/ipc.rs [hunk 9]
```diff
@@ -156,8 +156,10 @@ impl IpcJsonStreamResource {
     self: Rc<Self>,
     msg: &[u8],
   ) -> Result<(), io::Error> {
+    log::debug!("json ipc write: {msg:?}");
```
Comment (bartlomieju) [inline ext/process/ipc.rs]: Do you want to keep these two logs?

File: ext/node/ops/ipc.rs (hunk 4 above)
Comment (nathanwhit) [reply ext/node/ops/ipc.rs]: Likewise if you're doing string comparisons / equality. For internalized strings it becomes an integer comparison vs a full string comparison for external strings

File: tests/node_compat/config.toml [hunk 10]
```diff
@@ -135,6 +135,9 @@
 "parallel/test-buffer-zero-fill-cli.js" = {}
 "parallel/test-buffer-zero-fill-reset.js" = {}
 "parallel/test-buffer-zero-fill.js" = {}
+"parallel/test-child-process-advanced-serialization.js" = {}
+"parallel/test-child-process-advanced-serialization-largebuffer.js" = {}
+"parallel/test-child-process-advanced-serialization-splitted-length-field.js" = {}
```
Comment (bartlomieju) [inline tests/node_compat/config.toml:141]: That's pretty great

File: ext/node/ops/ipc.rs (hunk 4 above)
Comment (bartlomieju) [reply ext/node/ops/ipc.rs]: We might want to take a look at `deno_core` then 😬

File: ext/node/ops/ipc.rs [hunk 11]
```diff
@@ -226,6 +273,510 @@ mod impl_ {
...
+        .or_cancel(cancel)
+        .await;
+      // adjust count even on error
+      stream
+        .queued_bytes
+        .fetch_sub(serialized.len(), std::sync::atomic::Ordering::Relaxed);
+      result??;
+      Ok(())
+    })
+  }
```
[the remark this answers is not in the document]
Comment (nathanwhit) [reply ext/node/ops/ipc.rs:480]: This is incorrect. The pattern `Ok` in `let Ok(v) = false.to_v8(scope);` is an _irrefutable_ pattern, because false.to_v8 returns a `Result<_, std::convert::Infallible>` and `Infallible` is an uninhabitable type, which means that the `Err` variant can never be constructed!
