### PR TITLE
fix(cli/installer): percent decode name

### LINKED ISSUE #6408: `deno install xxx.ts` will replace blank spaces in folder names with "%20" which won't run on Windows 10
It can be fixed by replacing "%20" by " " (blank space) in `C:\Users[user].deno\bin\xxx.cmd`. After that it's finally possible to run `xxx` from anywhere.

deno 1.1.1
v8 8.5.104
typescript 3.9.2

### PR DESCRIPTION
**Pull request by crowlKats**
Fixes #6408.
This is what the url crate partially does behind the scenes.

### CODE REVIEW

File: cli/tools/installer.rs [hunk 1]
```diff
@@ -152,12 +152,19 @@ pub async fn infer_name_from_url(url: &Url) -> Option<String> {
...
+    PathBuf::from(std::ffi::OsStr::from_bytes(
+      &percent_decode.collect::<Vec<u8>>(),
+    ))
   };
-  if stem == "main" || stem == "mod" || stem == "index" || stem == "cli" {
+  #[cfg(windows)]
+  let path = PathBuf::from(percent_decode.decode_utf8_lossy().as_ref());
+
+  let mut stem = path.file_stem()?.to_string_lossy().to_string();
+  if matches!(stem.as_str(), "main" | "mod" | "index" | "cli") {
```
Comment (littledivy) [inline cli/tools/installer.rs:167]:
```suggestion
  let mut stem = path.file_stem()?.to_string_lossy();
  if matches!(stem.as_ref(), "main" | "mod" | "index" | "cli") {
```

File: cli/tools/installer.rs [hunk 2]
```diff
@@ -152,12 +152,19 @@ pub async fn infer_name_from_url(url: &Url) -> Option<String> {
...
-  let mut stem = match path.file_stem() {
-    Some(stem) => stem.to_string_lossy().to_string(),
-    None => return None,
+  let percent_decode = percent_encoding::percent_decode(url.path().as_bytes());
+  #[cfg(unix)]
+  let path = {
+    use std::os::unix::prelude::OsStrExt;
+    PathBuf::from(std::ffi::OsStr::from_bytes(
+      &percent_decode.collect::<Vec<u8>>(),
+    ))
```
Comment (littledivy) [inline cli/tools/installer.rs:161]:
```suggestion
    use std::os::unix::prelude::OsStringExt;
    PathBuf::from(std::ffi::OsString::from_vec(
      percent_decode.collect::<Vec<u8>>(),
    ))
```

> This conversion does not allocate or copy memory.

https://doc.rust-lang.org/std/path/struct.PathBuf.html#impl-From%3COsString%3E-for-PathBuf

**Review by littledivy — APPROVED** [review]
