### PR TITLE
fix(std/node): Stop callbacks being called twice when callback throws error

### LINKED ISSUE #8815: Promise as Callbacks using dangerous pattern
While working on some node/fs feature it was noticed that many of the compatibility modules used Promise based Deno builtins inside Callback based implementations, in a dangerous way.  

"if callback throws you reach the catch and the callback is called again with an error"

The problem was reported in my module by @benjamingr but it spans to many of them.

- _fs_appendFile
- _fs_chmod
- _fs_chown
- _fs_copy
- _fs_dir
- _fs_exists
- _fs_lstat
- _fs_mkdir
- _fs_open
- _fs_readfile
- _fs_realpath
- _fs_rename
- _fs_rmdir
- _fs_stat
- _fs_unlink
- _fs_writeFile

### PR DESCRIPTION
**Pull request by Liamolucko**
Closes #8815.

### CODE REVIEW

**Comment by bartlomieju** [comment]
@Liamolucko thanks for the PR, looks good, no comments on the code. Could you add some test cases showcasing the problem described in #8815 so we're sure there's no regressions in the future?

**Comment by Liamolucko** [comment]
Should something be written down somewhere about this issue? I wouldn't be surprised if more of these bugs pop up as `std/node` is expanded.

**Comment by bartlomieju** [comment]
> Should something be written down somewhere about this issue? I wouldn't be surprised if more of these bugs pop up as `std/node` is expanded.

@Liamolucko yes, a note in `std/node/README.md` would be very helpful 👍

**Comment by guybedford** [comment]
On the topic of callbach handling for Node.js I've also posted https://github.com/denoland/deno/issues/8897 for error remapping. It's a separate issue, but the two problems are still closely related.

File: std/node/_crypto/randomBytes.ts [hunk 1]
```diff
@@ -50,9 +52,12 @@ export default function randomBytes(
       ) {
         throw e;
       } else {
-        cb(e);
+        err = e;
       }
     }
+    setTimeout(() => {
+      cb(err, bytes);
+    }, 0);
```
Comment (bnoordhuis) [inline std/node/_crypto/randomBytes.ts:60]:
```suggestion
    cb(err, bytes);
```
If the setTimeout is there for a reason, can you add an explaining comment? Thanks.

File: std/node/_fs/_fs_close.ts [hunk 2]
```diff
@@ -2,14 +2,15 @@
 import type { CallbackWithError } from "./_fs_common.ts";
 
 export function close(fd: number, callback: CallbackWithError): void {
-  queueMicrotask(() => {
+  setTimeout(() => {
```
Comment (bnoordhuis) [inline std/node/_fs/_fs_close.ts:5]: Can you explain this change?

File: std/node/_fs/_fs_lstat.ts [hunk 3]
```diff
@@ -36,9 +36,10 @@ export function lstat(
 
   if (!callback) throw new Error("No callback function supplied");
 
-  Deno.lstat(path)
-    .then((stat) => callback(undefined, CFISBIS(stat, options.bigint)))
-    .catch((err) => callback(err, err));
+  Deno.lstat(path).then(
+    (stat) => callback(undefined, CFISBIS(stat, options.bigint)),
```
Comment (bnoordhuis) [inline std/node/_fs/_fs_lstat.ts:40]:
```suggestion
    (stat) => callback(null, CFISBIS(stat, options.bigint)),
```
(node always passes null if there is no error)

File: std/node/_fs/_fs_lstat.ts [hunk 4]
```diff
@@ -36,9 +36,10 @@ export function lstat(
...
+    (err) => callback(err, err),
```
Comment (bnoordhuis) [inline std/node/_fs/_fs_lstat.ts:41]:
```suggestion
    (err) => callback(err),
```
(`arguments.length` == 1 when a fs callback fails)

Similar comments apply to `std/node/_fs/_fs_open.ts` and `std/node/_fs/_fs_stat.ts`.

**Review by bnoordhuis — COMMENTED** [review]
Thanks for the pull request, I admire your testing rigor!

General observation:

1. Successful fs ops always invoke the callback like this `cb(null, res)`, never `cb(undefined, res)`. There's still some work left to be done there. I pointed out some instances but not all.

2. Unsuccessful fs ops invoke `cb(err)`, i.e., `arguments.length === 1`.

That said, this PR is already a big improvement on the status quo!

Apropos testing, there's a lot of repetition right now. I'd move the boilerplate into a helper function and then simply pass in the script-to-eval as an argument.

I think it's okay to start deno with `--unstable` unconditionally, no need to special case that.

Thanks again!

File: std/node/_fs/_fs_close.ts (hunk 2 above)
Comment (Liamolucko) [reply std/node/_fs/_fs_close.ts:5]: At the moment `queueMicrotask()` doesn't exit the program when the callback throws an error (#4350), so I replaced it with `setTimeout()`. To be fair that is a Deno issue though, so maybe it should be left alone?

Comment (bnoordhuis) [reply std/node/_fs/_fs_close.ts:5]: Yes, please leave it for now. I'll comment on the other issue, I think I know what needs to be done in order to fix that.

File: std/node/_crypto/randomBytes.ts (hunk 1 above)
Comment (Liamolucko) [reply std/node/_crypto/randomBytes.ts:60]: Since the callback is called synchronously, any errors it throws can be caught with a try/catch around `randomBytes()`. That isn't really related to this issue, but I originally did it because for some reason [a V8 debug check was failing](https://github.com/denoland/deno/runs/1610754385#step:25:4138) when pbkdf2 was synchronous.

**Review by bartlomieju — APPROVED** [review]
LGTM, thank you @Liamolucko especially for updating the README for `std/node` module. I will wait on Ben's review before landing

File: std/node/_fs/_fs_close.ts (hunk 2 above)
Comment (bnoordhuis) [reply std/node/_fs/_fs_close.ts:5]: This is still unresolved but I suppose it doesn't matter much in practice.

**Review by bnoordhuis — APPROVED** [review]
Thanks, LGTM!
