### PR TITLE
fix(op_crates): Don't use `Deno.inspect` in op crates

### LINKED ISSUE #9446: Uncaught (in promise) ReferenceError: Deno is not defined - when deno namespace is set to false in WebWorker
Don`t know how to reproduce this for now, but using a worker without deno namespace set to true is not possible for now, in some situations.

I mean it makes sense in the context that the error message is build with some "Deno stuff" - but this shouldnt be the case, when i dont allowed the deno namespace to be used at all.

Thrown Error: `"Uncaught (in promise) ReferenceError: Deno is not defined\n    return ${obj.constructor.name} ${Deno...",`

Feel free to look into this, for now its just a placeholder - will update this when i have more informations.

### PR DESCRIPTION
**Pull request by nayeemrmn**
Pass `Deno.inspect()` as an arg to the internal custom inspect implementations.

Fixes #9446.

### CODE REVIEW

**Comment by kt3k** [comment]
Providing 2 different implementations for each custom inspector looks too costly to me.

How about taking `Deno.inspect` as an argument of custom inspector and use it in the implementation? That should remove the dependency to the global Deno namespace.

```ts
[Symbol.for("Deno.customInspect")](inspect) {
  return `${this.constructor.name} ${
    inspect({ locked: this.locked })
  }`;
}
```

**Comment by nayeemrmn** [comment]
Good point. I also realised the fallback implementations are defective because they don't quote string properties, which would require even more code to fix.

In #8099 it's suggested to do this as part of the public custom inspect API. I'll only do this for the internal custom inspect because a) it's yet to be argued if user code will need this mechanism and b) it can land now.

**Comment by nayeemrmn** [comment]
I've changed my mind, I think using the Deno namespace in custom inspect under the assumption it's only called in Deno aligns with how we expect users to write browser-compatible modules.

**Comment by nayeemrmn** [comment]
Reopening to fix #9446. This is needed because web workers can disable the Deno namespace. cc @bartlomieju

**Comment by bartlomieju** [comment]
> Reopening to fix #9446. This is needed because web workers can disable the Deno namespace. cc @bartlomieju

LGTM, but could you please add a test showcasing #9446?

File: cli/tests/084_worker_custom_inspect_worker.ts [hunk 1]
```diff
@@ -0,0 +1,2 @@
+console.log(new ReadableStream());
```
Comment (kt3k) [inline cli/tests/084_worker_custom_inspect_worker.ts:1]: 👍

File: cli/tests/integration_tests.rs [hunk 2]
```diff
@@ -2685,6 +2685,11 @@ console.log("finish");
     assert_eq!(out, "");
   }
 
+  itest!(_084_worker_custom_inspect {
+    args: "run 084_worker_custom_inspect.ts",
```
Comment (kt3k) [inline cli/tests/integration_tests.rs:2689]:
```suggestion
    args: "run --allow-read 084_worker_custom_inspect.ts",
```

**Review by kt3k — APPROVED** [review]
LGTM

**Review by bartlomieju — APPROVED** [review]
LGTM
