### PR TITLE
fix(cli/console): always quote and escape inspected strings

### LINKED ISSUE #7545: Inspect should always quote and escape strings
This is similar to #7532 but for plain strings.

We are returning strings back as-is from Deno.inspect which isn't very useful.

```typescript
const value = "\x1b[2J";
console.log(Deno.inspect(value));
```

Expected output
```
"\x1b[2j" // Deno.inspect yields a string with \"\\x1b[2j\"
```

Actual output
```
\x1b[2j
```

This manifests itself in quite a few different ways including but not limited to;
- Doing an asserting error with something that returns a terminal sequence can blow up the terminal.
- Impossible to spot string diffs in testing/asserts.
- Typing in a terminal sequence in the prompt can blow up the terminal as it echoes back without being escaped.

### PR DESCRIPTION
**Pull request by caspervonb**
Fixes #7545

### CODE REVIEW

File: cli/tests/unit/console_test.ts [hunk 1]
```diff
@@ -831,7 +831,7 @@ unitTest(function consoleTestWithStringFormatSpecifier(): void {
 unitTest(function consoleTestWithObjectFormatSpecifier(): void {
   assertEquals(stringify("%o"), "%o");
   assertEquals(stringify("%o", 42), "42");
-  assertEquals(stringify("%o", "foo"), "foo");
+  assertEquals(stringify("%o", "foo"), `"foo"`);
```
Comment (caspervonb) [inline cli/tests/unit/console_test.ts:834]: Do we want to keep %o and %s the same for strings?

**Comment by caspervonb** [comment]
cc @nayeemrmn

File: cli/tests/unit/console_test.ts (hunk 1 above)
Comment (caspervonb) [reply cli/tests/unit/console_test.ts:834]: Node does quote and escape strings with the `%o` format specifier.

File: std/testing/asserts.ts [hunk 2]
```diff
@@ -28,10 +28,8 @@ export function _format(v: unknown): string {
       compact: false,
       iterableLimit: Infinity,
     }))
-    : String(v);
-  if (typeof v == "string") {
-    string = `"${string.replace(/(?=["\\])/g, "\\")}"`;
-  }
+    : `"${String(v).replace(/(?=["\\])/g, "\\")}"`;
```
Comment (solson) [inline std/testing/asserts.ts:31]: What is the intended purpose of this code? It may be the cause of the mismatch with my expectations in https://github.com/denoland/deno/issues/7545#issuecomment-694603355. (That is, an unexpected extra backslash.)

Comment (solson) [reply std/testing/asserts.ts:31]: Well, based on your reply in the issue, I realize the assertions are actually asserting what I expected, so I guess all is well. But I'm still not sure what this line of code is for, out of my own curiosity.

File: cli/tests/unit/console_test.ts [hunk 3]
```diff
@@ -1424,6 +1424,17 @@ unitTest(function consoleTrace(): void {
   });
 });
 
+unitTest(function inspectString(): void {
+  assertEquals(
+    stripColor(Deno.inspect("\0")),
+    `"\\x00"`,
```
Comment (solson) [inline cli/tests/unit/console_test.ts:1430]:
```suggestion
    String.raw`"\x00"`,
```

Maybe this is slightly less confusing? Just a thought.

File: cli/tests/unit/console_test.ts [hunk 4]
```diff
@@ -1424,6 +1424,17 @@ unitTest(function consoleTrace(): void {
...
+  );
+  assertEquals(
+    stripColor(Deno.inspect("\x1b[2J")),
+    `"\\x1b[2J"`,
```
Comment (solson) [inline cli/tests/unit/console_test.ts:1434]:
```suggestion
    String.raw`"\x1b[2J"`,
```

Ditto.

File: std/testing/asserts.ts (hunk 2 above)
Comment (caspervonb) [reply std/testing/asserts.ts:31]: Was already there as the only escape mechanism, does not apply when Deno.inspect is involved tho.
Its either Deno.inspect or string.replace.

File: cli/tests/unit/console_test.ts (hunk 3 above)
Comment (caspervonb) [reply cli/tests/unit/console_test.ts:1430]: Hmm, either way is fine; just went with the style of literals and escape tests in the surrounding tests.

Comment (caspervonb) [reply cli/tests/unit/console_test.ts:1430]: Leaving as-is since the existing escape asserts are in this form.

File: cli/tests/unit/console_test.ts (hunk 4 above)
Comment (caspervonb) [reply cli/tests/unit/console_test.ts:1434]: Ditto.

File: cli/tests/unit/console_test.ts (hunk 3 above)
Comment (solson) [reply cli/tests/unit/console_test.ts:1430]: Makes sense. I think we should either stick to the surrounding style or change them all at once (in a separate PR).

File: cli/tests/unit/console_test.ts (hunk 1 above)
Comment (caspervonb) [reply cli/tests/unit/console_test.ts:834]: Browsers do also quote strings with the %o specifier so this is indeed the correct behavior at-least in regards to quoting. Non printable characters differ across browsers.

**Review by ry — APPROVED** [review]
LGTM
