### PR TITLE
fix(watch): preserve `ProcState::file_fetcher` between restarts

### LINKED ISSUE #15465: bug: `--watch --reload` will reload on every file change
Running `--reload` with `--watch` will reload on every file change, which is probably not desirable.
Example `./file.ts`:
```ts
#!/usr/bin/env -S deno run --allow-net --watch --reload
import { serve } from "https://deno.land/std/http/mod.ts"

serve(() => new Response("hi"), { port: 8080 });
```
Edit the file or just save it and deno will reload all dependencies

### PR DESCRIPTION
**Pull request by nayeemrmn**
Fixes #15465.

### CODE REVIEW

File: cli/proc_state.rs [hunk 1]
```diff
@@ -127,6 +127,29 @@ impl ProcState {
     Ok(ps)
   }
 
+  pub fn reset_for_file_watcher(&self) -> Self {
```
Comment (bartlomieju) [inline cli/proc_state.rs:130]: Please add a comment here

File: cli/main.rs [hunk 2]
```diff
@@ -731,17 +730,14 @@ async fn run_with_watch(flags: Flags, script: String) -> Result<i32, AnyError> {
...
   let main_module = resolve_url_or_path(&script)?;
   let (sender, receiver) = tokio::sync::mpsc::unbounded_channel();
+  let ps =
+    ProcState::build_for_file_watcher((*flags).clone(), sender.clone()).await?;
 
-  let operation = |(sender, main_module): (
-    tokio::sync::mpsc::UnboundedSender<Vec<PathBuf>>,
-    ModuleSpecifier,
-  )| {
+  let operation = |main_module: ModuleSpecifier| {
```
Comment (bartlomieju) [inline cli/main.rs:736]: Why is sender gone here?

**Review by bartlomieju — COMMENTED** [review]
@nayeemrmn please rebase

File: cli/main.rs (hunk 2 above)
Comment (nayeemrmn) [reply cli/main.rs:736]: It's not used in the closure anymore because `ps` is constructed above

**Review by bartlomieju — COMMENTED** [review]
@nayeemrmn this looks good to me, but could we test it somehow?

**Review by bartlomieju — APPROVED** [review]
LGTM, thanks for looking into this!

**Comment by nayeemrmn** [comment]
Looks like the test from this PR is hanging frequently on either debug or release linux, can't reproduce locally. I'll try actually changing the watched file content on the second write...

**Comment by nayeemrmn** [comment]
Yeah I don't know what's happening with this test. It hangs on one different job each time, but when I put an explicit panic at the end of the function it gets hit. @bartlomieju Anything you can see that's wrong with the test?

File: cli/tests/integration/watcher_tests.rs [hunk 3]
```diff
@@ -1129,3 +1129,41 @@ fn run_watch_dynamic_imports() {
...
+    .stderr(std::process::Stdio::piped())
+    .spawn()
+    .unwrap();
+  let (mut stdout_lines, mut stderr_lines) = child_lines(&mut child);
+
+  wait_contains("finished", &mut stderr_lines);
+  let first_output = stdout_lines.next().unwrap();
+
+  write(&file_to_watch, format!("{}\n", file_content)).unwrap();
+  // The remote dynamic module should not have been reloaded again.
```
[the remark this answers is not in the document]
Comment (nayeemrmn) [reply cli/tests/integration/watcher_tests.rs:1162]: It's a static import of a remote module with dynamic content (system time)

**Comment by bartlomieju** [comment]
> Yeah I don't know what's happening with this test. It hangs on one different job each time, but when I put an explicit panic at the end of the function it gets hit. @bartlomieju Anything you can see that's wrong with the test?

Sorry for a slow response. I looked at the tests and can't really spot anything off :(

**Comment by nayeemrmn** [comment]
@bartlomieju Finally figured out the problem: https://github.com/denoland/deno/pull/15466/commits/8d58477191ded54bbc0badb5b0536d02be8623b5, debugging with timestamps shows that the file modification in the test can happen between these lines and I guess the watcher misses the event because of that. Files should be watched before printing the finished message

**Comment by bartlomieju** [comment]
@nayeemrmn nice, I will try to review the PR tonight

File: cli/proc_state.rs [hunk 4]
```diff
@@ -147,6 +147,38 @@ impl ProcState {
     Ok(ps)
   }
 
+  /// Return a cloned `self` with all runtime state reset to its default. This
+  /// should be used on file watcher restarts.
+  pub fn reset_for_file_watcher(&self) -> Self {
```
Comment (bartlomieju) [inline cli/proc_state.rs:152]: Couldn't this method update `ProcState` in place instead?

File: cli/proc_state.rs [hunk 5]
```diff
@@ -304,7 +335,7 @@ impl ProcState {
       .map(|s| (s, ModuleKind::Esm))
       .collect::<Vec<_>>();
 
-    if !reload_on_watch && !has_root_npm_specifier {
+    if !has_root_npm_specifier {
```
Comment (bartlomieju) [inline cli/proc_state.rs:338]: I'm not sure if this branch is needed anymore, IIRC I only had problems with it because of `reload_on_watch`

Comment (nayeemrmn) [reply cli/proc_state.rs:338]: The alternative would be making this an unconditional block. I believe we want to skip this short circuiting logic if there are npm roots since `GraphData::check()` doesn't account for those (this could be cleaned up in a separate PR)

**Comment by bartlomieju** [comment]
Thanks for fixing the PR Nayeem; I will review it after the holiday break.

**Review by dsherret — APPROVED** [review]
Nice. LGTM!

File: cli/tools/test.rs [hunk 6]
```diff
@@ -1355,12 +1354,14 @@ pub async fn run_tests_with_watch(
   let no_check = ps.options.type_check_mode() == TypeCheckMode::None;
   let test_options = &test_options;
 
+  let ps = RefCell::new(ps);
```
Comment (bartlomieju) [inline cli/tools/test.rs:1357]: Now that I'm seeing it I'm a bit worried this might cause unexpected bugs - since `ProcState` is internally an `Arc` a lot of APIs could have cloned it and hold onto a copy of that `Arc`. Even if we create a new `Arc` in `reset_for_file_watcher` some code might hold onto the old copy. Does that make sense? Are am I overanalyzing it and essentially anything that can hold onto `ProcState` gets torn down between restarts?

Comment (nayeemrmn) [reply cli/tools/test.rs:1357]: Well `ProcState`'s fields are either (1) immutable config, (2) mutable data that gets defaulted on reset, or (3) interior mutable fields with their own `Arc`s which are preserving-ly cloned on reset. If there _were_ an old lingering `ProcState` inner, the issue would be if (2) and (3) started conflicting since (3) is being affected by a future run. That can be avoided by being strict about what fields are (3), if there's an bug it should just mean that more fields need to be defaulted on reset.. I think

Comment (bartlomieju) [reply cli/tools/test.rs:1357]: Okay, makes sense. Thanks for investigating

**Review by bartlomieju — APPROVED** [review]
LGTM too
