### PR TITLE
fix(npm): remove export binding to match node

### LINKED ISSUE #15790: npm classes lose their prototypes
When running the following file `foo.js`:
```js
import {ESLint} from "npm:eslint@8.23.0";

console.log(ESLint.outputFixes);
```
with `deno run --unstable -A foo.js`

it logs `undefined` instead of the static method.
It seems like `FunctionPrototypeBind` is causing the prototype to get lost. `ESLint.prototype` is also turned into `undefined`:
https://github.com/denoland/deno/blob/5f251b283b3532849862c7fdf4b91f0f9ed68829/ext/node/02_require.js#L867-L874

### PR DESCRIPTION
**Pull request by dsherret**
Closes #15790

### CODE REVIEW

File: cli/tests/testdata/npm/cjs_this_in_exports/main.js [hunk 1]
```diff
@@ -0,0 +1,7 @@
+import defaultImport, { getValue } from "npm:@denotest/cjs-this-in-exports";
+
+console.log(defaultImport.getValue());
+
+// This will throw because it's lost its context.
+// (same thing occurs with Node's cjs -> esm translation)
+getValue();
```
Comment (dsherret) [inline cli/tests/testdata/npm/cjs_this_in_exports/main.js:7]: Example in Node:

```
> cat other.cjs
module.exports = {
  test() {
    return this.other();
  },
  other() {
    return 5;
  }
};

> cat file.mjs
import defaultImport from "./other.cjs";
import * as namespaceImport from "./other.cjs";
import { test } from "./other.cjs";

console.log(defaultImport.test());
console.log(test());
console.log(namespaceImport.test()); // this also throws

> node file.mjs
5
V:\scratch-npm\other.cjs:3
    return this.other();
                ^

TypeError: this.other is not a function
    at Module.test (V:\scratch-npm\other.cjs:3:17)
    at file:///V:/scratch-npm/file.mjs:6:12
    at ModuleJob.run (node:internal/modules/esm/module_job:198:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:385:24)
    at async loadESM (node:internal/process/esm_loader:88:5)
    at async handleMainPromise (node:internal/modules/run_main:61:12)
```

**Review by littledivy — APPROVED** [review]
LGTM
