### PR TITLE
fix(cli/rt/console): fix inspection of Function

### LINKED ISSUE #7633: console.log dies on null prototype function
So, I was honestly acting dumb, and ended up with essentially just this:
```ts
const f = <T>(x: T): T => x;

Reflect.setPrototypeOf( f, null );

console.log( f );

console.log(( f( NaN ) );
```

Attempting to log the function causes an error.

> Uncaught TypeError: Cannot read property 'constructor' of null...

### PR DESCRIPTION
**Pull request by kt3k**
This PR fixes the inspection of functions. The current implementation gets the name of the type of the function from `f.__proto__.constructor.name`, and it throws when the prototype is set to null as described in #7633. This PR checks the prototype before accessing its constructor name and uses the generic name 'Function' if the prototype is not available.

fixes #7633

### CODE REVIEW

**Review by bartlomieju — APPROVED** [review]
LGTM, thank you @kt3k 

I'll wait for @nayeemrmn approval before landing

**Review by nayeemrmn — APPROVED** [review]
LGTM

File: cli/tests/unit/console_test.ts [hunk 1]
```diff
@@ -347,6 +347,21 @@ unitTest(function consoleTestStringifyCircular(): void {
...
+  assertEquals(stringify(f), "[Function: f]");
+  const af = async function af() {};
+  Reflect.setPrototypeOf(af, null);
+  assertEquals(stringify(af), "[Function: af]");
+  const gf = function gf() {};
+  Reflect.setPrototypeOf(gf, null);
+  assertEquals(stringify(gf), "[Function: gf]");
+  const agf = function agf() {};
+  Reflect.setPrototypeOf(agf, null);
+  assertEquals(stringify(agf), "[Function: agf]");
```
Comment (solson) [inline cli/tests/unit/console_test.ts:362]: I know this is already merged, but was this intended to test generator functions and async generator functions? (`function* gf() {}` and `async function* agf() {}`)

Comment (bartlomieju) [reply cli/tests/unit/console_test.ts:362]: @solson good catch, could you open an issue about it?

Comment (nayeemrmn) [reply cli/tests/unit/console_test.ts:362]: > `function* gf() {}` and `async function* agf() {}`

Are you saying they should have their own output? That's just declaration-side syntactic sugar.

Comment (solson) [reply cli/tests/unit/console_test.ts:362]: No, I'm saying they should be declared that way here in the test, as in `const gf = function* gf() {};` to match `async function af` above, presumably to test this "set prototype to `null`" manipulation on all 4 of `Function`, `AsyncFunction`, `GeneratorFunction`, and `AsyncGeneratorFunction`. Currently, `gf` and `agf` are just testing the same thing as `f`.

Comment (solson) [reply cli/tests/unit/console_test.ts:362]: @bartlomieju https://github.com/denoland/deno/issues/7962
