### PR TITLE
Reland "fix(cli): don't store blob and data urls in the module cache"

### LINKED ISSUE #18260: Imported blob URLs are persisted in the FS module cache
```ts
const prevUrl = localStorage.getItem("url");
if (prevUrl == null) {
  console.log("first run, storing blob url");
  const url = URL.createObjectURL(
    new Blob(["export {}"], { type: "application/javascript" }),
  );
  await import(url); // this shouldn't insert into the fs module cache
  localStorage.setItem("url", url);
} else {
  await import(prevUrl)
    .then(() => console.log("importing old blob url incorrectly works"))
    .catch(() => console.log("importing old blob url correctly failed"));
}
```
```
$ deno run temp.ts
first run, storing blob url
$ deno run temp.ts
importing old blob url incorrectly works
```

### PR DESCRIPTION
**Pull request by nayeemrmn**
Relands #18261 now that https://github.com/lucacasonato/esbuild_deno_loader/pull/54 is landed and used by fresh.
Fixes #18260.

### CODE REVIEW

File: cli/tests/integration/watcher_tests.rs [hunk 1]
```diff
@@ -1122,6 +1122,46 @@ fn test_watch_unload_handler_error_on_drop() {
   check_alive_then_kill(child);
 }
 
+#[test]
+fn run_watch_blob_urls_reset() {
+  let _g = util::http_server();
```
Comment (dsherret) [inline cli/tests/integration/watcher_tests.rs:1127]: Nitpick: If willing, could you update this test to use the new `TestContextBuilder`? I know a bunch of the tests here don't use it, but we're slowly transitioning over.

Comment (dsherret) [reply cli/tests/integration/watcher_tests.rs:1127]: Actually, maybe it's not easy to do the `child_lines` thing with it atm.

File: cli/factory.rs [hunk 2]
```diff
@@ -137,7 +137,7 @@ struct CliFactoryServices {
   maybe_import_map: Deferred<Option<Arc<ImportMap>>>,
   maybe_inspector_server: Deferred<Option<Arc<InspectorServer>>>,
   root_cert_store_provider: Deferred<Arc<dyn RootCertStoreProvider>>,
-  blob_store: Deferred<BlobStore>,
+  blob_store: Deferred<Arc<BlobStore>>,
```
Comment (nayeemrmn) [inline cli/factory.rs:140]: I moved the reference counter outside of `BlobStore` rather than on each of its fields because it makes more sense and resembles the other service fields. Ended up changing a lot of lines though.

**Review by nayeemrmn — COMMENTED** [review]
`CliFactoryServices` is nice with regards to file watcher resets

**Review by dsherret — COMMENTED** [review]
LGTM, but I don't understand the blob store well enough to approve this.

File: cli/file_fetcher.rs [hunk 3]
```diff
@@ -50,10 +49,6 @@ pub const SUPPORTED_SCHEMES: [&str; 5] =
 /// A structure representing a source file.
 #[derive(Debug, Clone, Eq, PartialEq)]
 pub struct File {
-  /// The path to the local version of the source file.  For local files this
-  /// will be the direct path to that file.  For remote files, it will be the
-  /// path to the file in the HTTP cache.
-  pub local: PathBuf,
```
[the remark this answers is not in the document]
Comment (nayeemrmn) [reply cli/file_fetcher.rs:56]: This field wasn't used anywhere IIRC, unless you can see a usage being removed in this diff. No `Serialize` on this struct either.

File: cli/file_fetcher.rs [hunk 4]
```diff
@@ -337,55 +317,26 @@ impl FileFetcher {
...
-    }
-
-    if self.cache_setting == CacheSetting::Only {
-      return Err(custom_error(
-        "NotCached",
-        format!(
-          "Specifier not found in cache: \"{specifier}\", --cached-only is specified."
-        ),
-      ));
-    }
```
[the remark this answers is not in the document]
Comment (nayeemrmn) [reply cli/file_fetcher.rs:353]: It's not in the module cache anymore so `--cached-only` wouldn't apply.

File: cli/file_fetcher.rs [hunk 5]
```diff
@@ -337,55 +317,26 @@ impl FileFetcher {
...
       map_content_type(specifier, Some(&content_type));
     let source = get_source_from_bytes(bytes, maybe_charset)?;
-
-    let local =
-      self
-        .http_cache
-        .get_cache_filename(specifier)
-        .ok_or_else(|| {
-          generic_error("Cannot convert specifier to cached filename.")
-        })?;
```
[the remark this answers is not in the document]
Comment (nayeemrmn) [reply cli/file_fetcher.rs:380]: dead code from `File::local` being removed

File: cli/file_fetcher.rs [hunk 6]
```diff
@@ -308,21 +294,15 @@ impl FileFetcher {
...
     let mut headers = HashMap::new();
     headers.insert("content-type".to_string(), content_type);
+    // TODO(nayeemrmn): Don't use the fs cache for data URLs:
+    // https://github.com/denoland/deno/issues/18260#issuecomment-1494791622.
```
Comment (bartlomieju) [inline cli/file_fetcher.rs:300]: Is there a blocker to addressing this right now?

Comment (nayeemrmn) [reply cli/file_fetcher.rs:300]: https://github.com/lucacasonato/esbuild_deno_loader/pull/54 hasn't been incorporated in fresh yet I don't think.

Comment (bartlomieju) [reply cli/file_fetcher.rs:300]: @nayeemrmn thanks for linking that issue, it should now be used by Fresh, so can we address this TODO before landing?

**Review by dsherret — COMMENTED** [review]
@bartlomieju LSP changes looks good and it looks good to me again, but someone else needs to review as well before landing.

File: cli/tests/integration/lsp_tests.rs [hunk 7]
```diff
@@ -7480,25 +7480,9 @@ fn lsp_data_urls_with_jsx_compiler_option() {
     }
   })).all();
 
-  // there will be a diagnostic about not having cached the data url
-  assert_eq!(diagnostics.len(), 1);
-  assert_eq!(
-    diagnostics[0].code,
-    Some(lsp::NumberOrString::String("no-cache-data".to_string()))
-  );
+  assert_eq!(diagnostics.len(), 0);
```
[the remark this answers is not in the document]
Comment (dsherret) [reply cli/tests/integration/lsp_tests.rs:7483]: Nice!

**Review by bartlomieju — CHANGES_REQUESTED** [review]
LGTM, but I'm marking as "Request changes" so we don't accidently land it now. 

Fresh 1.2 will be released this week, let's give people a couple weeks to upgrade before we land this PR. I think Deno v1.35 later this month will be okay.

**Review by bartlomieju — APPROVED** [review]
LGTM, thank you Nayeem :)
