### PR TITLE
fix(lsp): move sloppy import resolution from loader to resolver

### LINKED ISSUE #23197: Sloppy import resolution is flaky in the lsp
In a project with a deno.json with `"unstable": ["sloppy-imports"]`, using imports like `./AppContext.js` resolving to `./AppContext.ts`, I found that the resolved specifiers sometimes go to the `.js` file instead.

For example, in this video it was working, then I restarted the lsp and suddenly it's going to the `.js` file (actually, before I went to the specifiers file the first time it wasn't working before either).

https://github.com/denoland/deno/assets/1609021/da266d9f-a0d0-4566-bea1-083de67b46f3

Reproduction steps:

1. Check out this PR: https://github.com/dsherret/ts-ast-viewer/pull/143
2. `npm install`
3. Open the LSP

Version: Deno 1.42.1+57572da

### LINKED ISSUE #23745: LSP prefers `.d.ts` over `.js` files with sloppy imports
If you have sloppy imports enabled, and you have both a `.js` and `.d.ts` file, you get an error upon opening the `.js` file. 

For instance:

```ts
// deno.json
{
  "unstable": ["sloppy-imports"]
}

// foo.js
export const bar = 3;

// foo.d.ts
export const bar: number;
```

if you open `foo.js`, you get

```
ERROR TSLS = Error: Could not find source file: 'file:///home/lsp-sloppy-imports/foo.js'.
    at getValidSourceFile (ext:deno_tsc/00_typescript.js:144419:24)
    at Object.getSemanticDiagnostics (ext:deno_tsc/00_typescript.js:144681:32)
    at serverRequest (ext:deno_tsc/99_main_compiler.js:1153:34)
Error during TS request "$getDiagnostics":
  Error: Could not find source file: 'file:///home/lsp-sloppy-imports/foo.js'.
    at getValidSourceFile (ext:deno_tsc/00_typescript.js:144419:24)
    at Object.getSemanticDiagnostics (ext:deno_tsc/00_typescript.js:144681:32)
    at serverRequest (ext:deno_tsc/99_main_compiler.js:1153:34)
Error generating TypeScript diagnostics: The response was not received for the request.
```

This is because the LSP is resolving `foo.js` to `foo.d.ts` even though `foo.js` exists.

### PR DESCRIPTION
**Pull request by nathanwhit**
Fixes #23745
Fixes #23197

Moves sloppy import resolution from the loader to the resolver.

Also adds some test helper functions to make the lsp tests less verbose

### CODE REVIEW

File: cli/lsp/documents.rs
Comment (dsherret) [inline cli/lsp/documents.rs:1]: > Before this PR -> ./foo.js resolves to ./foo.d.ts
> After this PR ->./foo.js resolves to ./foo.js

This will cause typescript to resolve the incorrect file I think? Sloppy imports is informed by the provided `ResolutionMode` that will resolve .d.ts for `ResolutionMode::Types` and `.js` for `ResolutionMode::Execution`. Probably we need to surface that up to a higher level instead of only always doing `ResolutionMode::Types`.

Comment (nathanwhit) [reply cli/lsp/documents.rs:1]: Hmm my thinking was that this matches the behavior without sloppy imports enabled. Without sloppy imports we don't resolve `foo.js` to `foo.d.ts`, since we don't actually do any special resolution for file specifiers. So it seems inconsistent to change that behavior for an import that isn't actually sloppy

Comment (dsherret) [reply cli/lsp/documents.rs:1]: Yeah it's different than Deno's default resolution. For sloppy imports it does TypeScript's Node resolution behaviour where it prefers .d.ts files when resolving the types, but .js files when executing the code.

Comment (dsherret) [reply cli/lsp/documents.rs:1]: This actually might be a bug/design issue elsewhere. This is a fully resolved specifier so it's strange sloppy import resolution is happening here.

Comment (dsherret) [reply cli/lsp/documents.rs:1]: I did a commit that moves the sloppy import resolution from the loader to the resolver. This should fix the issue if you try it out now (and resolve to the .d.ts file).

This also seems to fix https://github.com/denoland/deno/issues/23197 for me.

File: cli/lsp/resolver.rs [hunk 1]
```diff
@@ -181,8 +196,18 @@ impl LspResolver {
     Ok(())
   }
 
-  pub fn as_graph_resolver(&self) -> &dyn Resolver {
-    self.graph_resolver.as_ref()
+  pub fn as_graph_resolver<'a>(
+    &self,
+    // this really only needs a HashSet<ModuleSpecifier>, but it's provided
+    // the entire HashMap to avoid cloning all the time
+    open_docs: &'a HashMap<ModuleSpecifier, Arc<Document>>,
```
Comment (dsherret) [inline cli/lsp/resolver.rs:203]: This is only necessary for sloppy import resolution. It's slightly unfortunate to have to have to pass it around, but I'm not sure a better way because we're mutating the `Documents` while calling this sometimes and sloppy import resolution needs to know about files that may only exist in memory.

File: tests/integration/lsp_tests.rs [hunk 2]
```diff
@@ -12106,7 +12049,7 @@ fn lsp_deno_future_env_byonm() {
 }
 
 #[test]
-fn lsp_sloppy_imports_warn() {
```
Comment (dsherret) [inline tests/integration/lsp_tests.rs:12109]: I removed the warning. It's not worth maintaining because it's a lot of work to add when this is done from the resolver. We can add this back as a lint rule later (see https://github.com/denoland/deno/issues/22844#issuecomment-1989103409)

File: cli/lsp/resolver.rs [hunk 3]
```diff
@@ -307,6 +332,80 @@ impl LspResolver {
...
+  ) -> Result<deno_ast::ModuleSpecifier, deno_graph::source::ResolveError> {
+    let specifier =
+      self
+        .resolver
+        .resolve(specifier_text, referrer_range, mode)?;
+    if self.unstable_sloppy_imports && specifier.scheme() == "file" {
+      Ok(
+        SloppyImportsResolver::resolve_with_stat_sync(
+          &specifier,
+          mode,
```
Comment (dsherret) [inline cli/lsp/resolver.rs:370]: See here how this now properly handles the mode for resolution.

File: cli/lsp/resolver.rs [hunk 4]
```diff
@@ -50,34 +52,39 @@ use std::path::Path;
...
   redirect_resolver: Option<Arc<RedirectResolver>>,
   graph_imports: Arc<IndexMap<ModuleSpecifier, GraphImport>>,
   config: Arc<Config>,
+  unstable_sloppy_imports: bool,
 }
 
-impl Default for LspResolver {
-  fn default() -> Self {
+impl LspResolver {
+  pub fn new(cache: Arc<dyn HttpCache>) -> Self {
```
Comment (nayeemrmn) [inline cli/lsp/resolver.rs:72]: I've been trying to avoid passing cache here, since the first value we pass in during `Inner::new()` isn't correct (doesn't respect workspace settings) and shouldn't be used. Been meaning to do the same for `Documents` as well. Though it would internally default to the same thing via `LspCache::new(None)`. Just a heads up, I can deal with it later.

**Review by nayeemrmn — APPROVED** [review]
LGTM

File: cli/lsp/resolver.rs (hunk 4 above)
Comment (dsherret) [reply cli/lsp/resolver.rs:72]: I was looking at the code more and I think passing `cache` isn't necessary. I'll remove it.

File: cli/lsp/resolver.rs [hunk 5]
```diff
@@ -181,8 +196,18 @@ impl LspResolver {
     Ok(())
   }
 
-  pub fn as_graph_resolver(&self) -> &dyn Resolver {
-    self.graph_resolver.as_ref()
+  pub fn as_graph_resolver<'a, 'b>(
+    &'a self,
+    // this really only needs a HashSet<ModuleSpecifier>, but it's provided
+    // the entire HashMap to avoid cloning all the time
+    open_docs: &'b HashMap<ModuleSpecifier, Arc<Document>>,
```
Comment (dsherret) [inline cli/lsp/resolver.rs:203]: Was thinking about this more this morning and realized that we should just not bother passing the open documents here. In places like vscode, the file will always exist on the file system if it's open (unlike our test server), so we can just consult that for simplicity.

File: cli/lsp/resolver.rs (hunk 4 above)
Comment (dsherret) [reply cli/lsp/resolver.rs]: Reverted in https://github.com/denoland/deno/pull/23751/commits/1d8e394c6c39f4e62a3aeed54556b31428d32434

File: cli/lsp/resolver.rs [hunk 6]
```diff
@@ -307,6 +319,68 @@ impl LspResolver {
...
+          |path| {
+            path.metadata().ok().and_then(|m| {
+              if m.is_file() {
+                Some(SloppyImportsFsEntry::File)
+              } else if m.is_dir() {
+                Some(SloppyImportsFsEntry::Dir)
+              } else {
+                None
+              }
+            })
```
Comment (dsherret) [inline cli/lsp/resolver.rs:362]: One thing we're going to have to do (and this is an existing bug) is recreate the resolved resolutions when a file is deleted or created, but that's a problem for a different day.
