### PR TITLE
fix: update deno_lint and swc

### LINKED ISSUE #20187: feat: Add `no-console` rule to `deno lint`
I'm guilty of accidentally committing `console.log` statements from time to time. We should have a `no-console` rule, similar to eslint: https://eslint.org/docs/latest/rules/no-console

### PR DESCRIPTION
**Pull request by bartlomieju**
Closes #20187

### CODE REVIEW

**Review by dsherret — APPROVED** [review]
LGTM

File: ext/http/websocket_upgrade.rs [hunk 1]
```diff
@@ -188,11 +188,18 @@ mod tests {
...
+          "{:#}",
+          result.err().map(|e| format!("{e:?}")).unwrap_or_default()
+        );
+        let expected = format!("{:#}", e);
+        if !actual.starts_with(&expected) {
+          panic!(
+            "Expected actual to start with expected.\n\nactual:\n{actual}\n\nexpected:\n{expected}"
+          );
+        }
+      }
```
Comment (dsherret) [inline ext/http/websocket_upgrade.rs:202]: Changed because anyhow started outputting more information when RUST_BACKTRACE=full.
