### PR TITLE
fix(#6531): Replacing calls to url.port() with url.port_or_known_default()

### LINKED ISSUE #6531: Network permissions check doesn't account for well-known default ports
Network permissions check for a URL without an explicit port number doesn't account for default ports of well-known schemes (80 for HTTP, 443 for HTTPS), resulting in a false negative in case permissions were indeed granted for that host:port combo explicitly.

### Steps to reproduce

1. Grant permissions to access www.google.com:443 (to ensure only secure access).
2. Try to access an https url without specifying the 443 port, i.e. fetch from https://www.google.com/robots.txt
3. Deno denies access to that address, even though the operation itself is indeed targeting the allowed port on the allowed address.
4. Try to fetch https://www.google.com:443/robots.txt
5. Deno denies access here as well

### Example
Consider the following test:
```ts
const res = await fetch('https://www.google.com/robots.txt');
const data = await res.text();
console.log(data);
```
Calling `deno run --allow-net=www.google.com:443 test.ts` fails on permissions.

Even if we explicitly try to fetch from  https://www.google.com:443/robots.txt we fail on permissions.

### Cause 
The Rust url crate kindly discards the port number if it is the default of the scheme:
```rust
use url::*;

fn main() {
    let uri = url::Url::parse("https://www.google.com:443").unwrap();
    println!("URI = {:?}", uri);  // prints https://www.google.com
    println!("port = {:?}", uri.port()); // prints None
}
```
Prints the URL without the port number, port is None.
To get the port number, we need to use `port_or_known_default()`:
```rust
println!("Seriously, port {:?}", uri.port_or_known_default()); // prints 443
```

### PR DESCRIPTION
**Pull request by jacobgc**
Fixes #6531 

Replaced the two references to url.port() (which returns None if the port is standard to the protocal) with url.port_or_known_default() which returns the port no matter what.

### CODE REVIEW

**Comment by ry** [comment]
Seems reasonable - but it would be very helpful to get a test demonstrating the behavior in #6531 so we don't ever regress.

**Comment by jacobgc** [comment]
> 
> 
> Seems reasonable - but it would be very helpful to get a test demonstrating the behavior in #6531 so we don't ever regress.

I'll look into it

**Comment by jacobgc** [comment]
Added a test that fails on commits lower than e1332bb

File: cli/permissions.rs [hunk 1]
```diff
@@ -692,6 +694,8 @@ mod tests {
       ("https://172.16.0.2:6000", false),
       ("tcp://172.16.0.1:8000", false),
       ("https://172.16.0.1:8000", false),
+      // Testing issue #6531 (Network permissions check doesn't account for well-known default ports) so we dont regress
+      ("https://www.github.com:443/robots.txt", true),
```
Comment (ry) [inline cli/permissions.rs:698]: Nice! Thanks!
