### PR TITLE
fix(cli): info now displays type reference deps

### LINKED ISSUE #11476: `deno info` does not display type dependencies correctly
If you have a dependency in a module graph that contains a triple-slash reference to the types or was served up with an `X-TypeScript-Types` headers, the information about the type dependency is currently missing from the graph.

I'm working on a fix for this, it is just a tracking issue.

### PR DESCRIPTION
**Pull request by kitsonk**
Fixes #11476

### CODE REVIEW

File: cli/info.rs [hunk 1]
```diff
@@ -411,11 +470,16 @@ https://deno.land/x/a.ts (123B)
...
+              {
+                "specifier": "./d.js",
+                "code": "https://deno.land/x/d.js"
+              }
+            ],
+            "size":789,
             "mediaType": "JavaScript",
             "local": "/cache/deps/https/deno.land/x/c.js",
-            "checksum": "9876abcef"
+            "checksum":"9876abcef"
```
Comment (lucacasonato) [inline cli/info.rs:482]: This seems unintentional. Same 2 lines up.

File: schemas/module-graph.json [hunk 2]
```diff
@@ -0,0 +1,125 @@
+{
```
Comment (lucacasonato) [inline schemas/module-graph.json:1]: I dislike that this adds a new top level directory. Can this go into cli/schemas/?

**Review by lucacasonato — APPROVED** [review]
LGTM with some minor comments
