### PR TITLE
fix(install): exclude npm workspace packages from graph roots in `install`

### LINKED ISSUE #28374: `deno install` fails for private npm package (using workspace)
Running `deno install` fails when referencing a npm package from workspace, when the package is not published.

NOTE: running the file `deno run modules/some-other-tool/index.ts` works fine, so it's resolving the package during runtime.

repro:

- [deno-private-npm-repro](https://github.com/ansemb/deno-private-npm-repro)

we have:

```
|
├─ modules/some-other-tool
├─ packages/some-private-tool
└
```

- `modules/some-other-tool/deno.json` contains:
```
{
  "name": "@mynamespace/some-other-tool",
  "exports": "./index.ts",
  "imports": {
    "@mynamespace/some-private-tool": "npm:@mynamespace/some-private-tool"
  }
}
```

Runing `deno install` returns:

```bash
❯ deno install
error: npm package '@mynamespace/some-private-tool' does not exist.

Stack backtrace:
   0: std::backtrace::Backtrace::capture
   1: anyhow::error::<impl core::convert::From<E> for anyhow::Error>::from
   2: deno::tools::pm::cache_deps::cache_top_level_deps::{{closure}}
   3: deno::spawn_subcommand::{{closure}}
   4: <deno_unsync::tokio::task::MaskFutureAsSend<F> as core::future::future::Future>::poll
   5: tokio::runtime::task::raw::poll
   6: deno::main
   7: std::sys::backtrace::__rust_begin_short_backtrace
   8: _main
```

---

deno 2.2.2 (stable, release, aarch64-apple-darwin)
v8 13.4.114.9-rusty
typescript 5.7.3

### PR DESCRIPTION
**Pull request by nathanwhit**
Fixes #28374.

### CODE REVIEW

File: cli/tools/pm/cache_deps.rs [hunk 1]
```diff
@@ -94,7 +100,16 @@ pub async fn cache_top_level_deps(
             });
           }
         }
-        "npm" => roots.push(specifier.clone()),
+        "npm" => {
+          if workspace_npm_package_names.contains(
+            specifier.as_str()[4..]
+              .trim_start_matches('/')
+              .trim_end_matches('/'),
```
Comment (dsherret) [inline cli/tools/pm/cache_deps.rs:107]: I think this won't work if someone specifies a subpath? Probably we should parse to `NpmPackageReqReference` here.

File: cli/tools/pm/cache_deps.rs [hunk 2]
```diff
@@ -94,7 +100,17 @@ pub async fn cache_top_level_deps(
...
           }
         }
-        "npm" => roots.push(specifier.clone()),
+        "npm" => {
+          let Ok(req_ref) =
+            NpmPackageReqReference::from_str(specifier.as_str())
+          else {
+            continue;
+          };
+          if workspace_npm_package_names.contains(&*req_ref.req().name) {
```
Comment (dsherret) [inline cli/tools/pm/cache_deps.rs:109]: I kind of wonder if we should still install when the req doesn't match the version in the package.json, but this is probably fine.

**Review by dsherret — APPROVED** [review]
LGTM!
