### PR TITLE
fix(runtime): Align the DedicatedWorkerGlobalScope event handlers to the spec.

### LINKED ISSUE #11351: A worker global's `onmessage` handler is called with a null event target
### test.js
```js
const worker = new Worker(
  new URL("./worker.js", import.meta.url).href,
  { type: "module" },
);
worker.postMessage({});
```

### worker.js
```js
self.onmessage = (evt) => {
  console.log("event handler attribute: %s", evt.target);
};

self.addEventListener("message", (evt) => {
  console.log("regular event handler: %s", evt.target);
});
```

### Result

```
event handler attribute: null
regular event handler: [object DedicatedWorkerGlobalScope]
```

However, running this code in all browsers gives:
image

-----------------

This bug, together with #11350, is causing some of the WPT test failures in #11338, since some of those WPT tests call `evt.target.postMessage()`.

### PR DESCRIPTION
**Pull request by andreubotella**
Fixes #11351

### CODE REVIEW

File: runtime/js/01_web_util.js [hunk 1]
```diff
@@ -27,17 +27,41 @@
   }
 
   const handlerSymbol = Symbol("eventHandlers");
-  function makeWrappedHandler(handler) {
+  function makeWrappedHandler(handler, isSpecialErrorEventHandler) {
```
Comment (lucacasonato) [inline runtime/js/01_web_util.js:30]: TIL about the special error handler handling. Yucky...

Instead of the `isSpecialErrorEventHandler` flag, could you just switch on `evt instanceof ErrorEvent && evt.type === "error" && target instanceof DedicatedWorkerGlobalScope`?

Comment (andreubotella) [reply runtime/js/01_web_util.js:30]: I didn't want to do that because the `DedicatedWorkerGlobalScope` interface is not available in the main worker, but I could check for it as part of the condition.

Comment (lucacasonato) [reply runtime/js/01_web_util.js:30]: Right... never mind then. Let's keep as is.

Unrelated, but we should go and deduplicate `defineEventHandler` with the one in 02_event.js in extensions/web (available via `window.__bootstrap.event.defineEventHandler`) in a follow-up. I am about 70% through a rewrite of the 02_event.js file though, so I'll do this as part of that rewrite.

File: cli/tests/worker_event_handler_test.js.out [hunk 2]
```diff
@@ -0,0 +1,16 @@
...
+  "",
+  0,
+  0,
+  Error: Some error message
+    at [WILDCARD]/cli/tests/workers/worker_event_handlers.js:9:9
+    at innerInvokeEventListeners (deno:extensions/web/02_event.js:750:9)
+    at invokeEventListeners (deno:extensions/web/02_event.js:789:5)
+    at dispatch (deno:extensions/web/02_event.js:659:11)
+    at dispatchEvent (deno:extensions/web/02_event.js:993:14)
+    at pollForMessages (deno:runtime/js/99_main.js:142:9)
```
Comment (lucacasonato) [inline cli/tests/worker_event_handler_test.js.out:14]:
```suggestion
    at [WILDCARD]
```

Having to change fixtures when line numbers in internal files change is annoying :-)

**Review by lucacasonato — APPROVED** [review]
LGTM, thanks!
