### PR TITLE
fix(ext/ffi): throw errors instead of panic

### LINKED ISSUE #13280: ffi: Panic on incorrect FFI parameters
# Code
```
const user32 = Deno.dlopen("user32.dll", {
    SystemParametersInfoA: {
        parameters: [
            "u32", 
            "u32",
            "pointer", 
            "u32", 
        ], 
        result: "i32" 
    } 
});

const result = user32.symbols.SystemParametersInfoA(0x0014, null, new TextEncoder().encode("D:/flower1.jpg"), 0x01)
```

# Panic
```
============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: windows x86_64
Version: 1.17.1
Args: ["deno", "run", "--unstable", "--allow-all", "natives.ts"]

thread 'main' panicked at 'Expected ffi arg value to be an unsigned integer', ext\ffi\lib.rs:281:6
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

# Mitigation
In this case, you can replace the `null` in `user32.symbols.Syst...` to 0, to match the symbol's parameters and the panic no longer occurs.

### PR DESCRIPTION
**Pull request by DjDeveloperr**
Also improves error message for symbol which could not be found (this has been bugging me when developing FFI related projects...)

closes #13280

### CODE REVIEW

**Review by eliassjogreen — APPROVED** [review]
LGTM, thank you finally!

File: test_ffi/tests/test.js [hunk 1]
```diff
@@ -18,6 +18,19 @@ try {
...
+    non_existent_symbol: {
+      parameters: [],
+      result: "void",
+    },
+  });
+} catch (e) {
+  console.log(
+    `error includes symbol name? ${e.message.includes("non_existent_symbol")}`,
+  );
+}
```
Comment (bartlomieju) [inline test_ffi/tests/test.js:32]: Nit pick, but maybe import `assertThrows` from `test_util/std/`

File: test_ffi/tests/test.js [hunk 2]
```diff
@@ -88,16 +88,12 @@ console.log(Boolean(dylib.symbols.is_null_ptr(ptr)));
 console.log(Boolean(dylib.symbols.is_null_ptr(null)));
 console.log(Boolean(dylib.symbols.is_null_ptr(Deno.UnsafePointer.of(into))));
 console.log(dylib.symbols.add_u32(123, 456));
-try {
+assertThrows(() => {
   dylib.symbols.add_u32(-1, 100);
-} catch (_) {
-  console.log("passing negative integer in u32 argument doesn't panic");
-}
```
Comment (bartlomieju) [inline test_ffi/tests/test.js]: I'd be great to still assert this message

File: test_ffi/tests/test.js [hunk 3]
```diff
@@ -88,16 +88,12 @@ console.log(Boolean(dylib.symbols.is_null_ptr(ptr)));
...
-try {
+});
+assertThrows(() => {
   dylib.symbols.add_u32(null, 100);
-} catch (_) {
-  console.log("passing null in u32 argument doesn't panic");
-}
```
Comment (bartlomieju) [inline test_ffi/tests/test.js]: Ditto

**Review by bartlomieju — COMMENTED** [review]
@DjDeveloperr please add expected messages to `assertThrows` and we can land this PR 👍

File: ext/ffi/lib.rs [hunk 4]
```diff
@@ -450,22 +473,30 @@ fn ffi_call(args: FfiCallArgs, symbol: &Symbol) -> Result<Value, AnyError> {
...
-      if let NativeType::Pointer = native_type {
-        if let Some(idx) = value.as_u64() {
-          if let Some(&Some(buf)) = buffers.get(idx as usize) {
-            return NativeValue::buffer(buf.as_ptr());
-          }
+  {
+    match native_type {
+      NativeType::Pointer => match value.as_u64() {
+        Some(idx) => {
+          let buf = buffers.get(idx as usize).unwrap().unwrap();
```
Comment (littledivy) [inline ext/ffi/lib.rs:486]: These unwraps should be thrown as errors too.

File: ext/ffi/lib.rs [hunk 5]
```diff
@@ -194,44 +206,44 @@ union NativeValue {
...
       },
       NativeType::F32 => Self {
-        f32_value: value_as_f32(value),
+        f32_value: value_as_f32(value)?,
       },
       NativeType::F64 => Self {
-        f64_value: value_as_f64(value),
+        f64_value: value_as_f64(value)?,
       },
       NativeType::Pointer => {
```
Comment (littledivy) [inline ext/ffi/lib.rs:248]: The `.expect` below should be a type_error too

File: test_ffi/tests/integration_tests.rs [hunk 6]
```diff
@@ -29,15 +29,18 @@ fn basic() {
...
   if !output.status.success() {
     println!("stdout {}", stdout);
     println!("stderr {}", stderr);
   }
   println!("{:?}", output.status);
   assert!(output.status.success());
+  if stderr.starts_with("Check ") {
+    // Remove the "Check ..." line from stderr.
+    stderr = &stderr[(stderr.find('\n').unwrap() + 1)..];
+  }
```
Comment (littledivy) [inline test_ffi/tests/integration_tests.rs:42]: Pass `--quiet` to the command maybe?

Comment (DjDeveloperr) [reply test_ffi/tests/integration_tests.rs:42]: TIL that exists, will use that.

File: ext/ffi/lib.rs (hunk 4 above)
Comment (DjDeveloperr) [reply ext/ffi/lib.rs:486]: I thought it'd not be required since these are actually `Option` and always expected to be there according to the JS side which calls it. I'll throw these anyway, but what should be the error message?

Comment (littledivy) [reply ext/ffi/lib.rs]: Actually I agree, these can be only reachable if our internal JS code is buggy. Let's keep them as panics we would want users to report them as bugs.

**Review by littledivy — APPROVED** [review]
LGTM Thanks
