### PR TITLE
fix: Remove unnecessary whitespace in prompt function

### LINKED ISSUE #28828: Request: Make prompt() drop unneccessary whitespace between label and input message
When using a label for the prompt:
```ts
console.log('Please input your statement!');
const statement = prompt('Statement:', 'Example statement');
```

```
Please input your statement!
Statement: Example statement
```

Here Deno adds an extra whitespace between "Statement:" and "Example statement".

When using an empty for the prompt:
```ts
console.log('Please input your statement!');
const statement = prompt('', 'Example statement');
```

```
Please input your statement!
 Example statement 
```

Here Deno also adds an extra whitespace between "" and "Example statement". It would be awesome if Deno did not add a whitespace there if the label is a zero length string.

### PR DESCRIPTION
**Pull request by manishsahanidev**
## Description
Fixes #28828

This PR addresses the issue where unnecessary whitespace is added between the label and input message in the `prompt()` function.

## Changes
- Modified the `prompt()` function to only add a space after the message if the message is non-empty
- This ensures no extra whitespace appears when using an empty label

## Before
- With label: `Statement:  Example statement` (extra space)
- With empty label: ` Example statement` (leading space)

## After
- With label: `Statement: Example statement` (single space)
- With empty label: `Example statement` (no extra space)

## Testing
Manually verified the behavior works correctly for both cases.

### CODE REVIEW

File: runtime/js/41_prompt.js [hunk 1]
```diff
@@ -41,10 +38,9 @@ function prompt(message = "Prompt", defaultValue) {
     return null;
   }
 
-  return op_read_line_prompt(
-    `${message} `,
-    `${defaultValue}`,
-  );
+  const formattedMessage = message === "" ? "" : `${message} `;
+
+  return op_read_line_prompt(formattedMessage, `${defaultValue}`);
```
Comment (dsherret) [inline runtime/js/41_prompt.js:43]:
```suggestion
  const formattedMessage = message.length === 0 ? "" : `${message} `;
  return op_read_line_prompt(formattedMessage, `${defaultValue}`);
```

**Review by dsherret — APPROVED** [review]
LGTM. Thanks!
