### PR TITLE
fix(runtime/js/http): Expose nextRequest() errors in respondWith()

### LINKED ISSUE #10380: [HTTP Native] Process ended because `nextRequest` threw error
Stacktrace:

```
error: Uncaught (in promise) Http: connection closed before message completed
          for await (const requestEvent of httpConn) {
                           ^
    at unwrapOpResult (deno:core/core.js:100:13)
    at async HttpConn.nextRequest (deno:runtime/js/40_http.js:33:23)
    at async Object.next (deno:runtime/js/40_http.js:83:26)
```

deno 1.9.0 (release, x86_64-apple-darwin)
v8 9.1.269.5
typescript 4.2.2

### PR DESCRIPTION
**Pull request by nayeemrmn**
Fixes #10380.

### CODE REVIEW

File: cli/tests/unit/http_test.ts [hunk 1]
```diff
@@ -272,3 +272,48 @@ unitTest(
...
+        async () => {
+          let interval = 0;
+          await respondWith(
+            new Response(
+              new ReadableStream({
+                start(controller) {
+                  interval = setInterval(() => {
+                    const message = `data: ${Date.now()}\n\n`;
+                    controller.enqueue(new TextEncoder().encode(message));
+                  }, 200);
```
Comment (ry) [inline cli/tests/unit/http_test.ts:298]: It's not clear to me whether this setInterval loop is necessary to demonstrate the bug? Can't you just setTimeout and respondWith after?

Comment (nayeemrmn) [reply cli/tests/unit/http_test.ts:298]: This is just a generic streamed response copied from an above test, any endless streamed response will do.

File: runtime/js/40_http.js [hunk 2]
```diff
@@ -172,14 +185,21 @@
...
               throw error;
             }
           }
         } finally {
           // Once all chunks are sent, and the request body is closed, we can
           // close the response body.
-          await Deno.core.opAsync("op_http_response_close", responseBodyRid);
+          try {
+            await Deno.core.opAsync("op_http_response_close", responseBodyRid);
+          } catch { /* pass */ }
```
Comment (aapoalas) [inline runtime/js/40_http.js:202]: The ignored catch could perhaps use a more informative comment on why it can be passed.

Comment (nayeemrmn) [reply runtime/js/40_http.js:202]: It's because it may already be closed. We have this in other places, a comment is there at all because of the linter.

File: runtime/js/40_http.js [hunk 3]
```diff
@@ -144,6 +152,11 @@
           innerResp.headerList,
         ], respBody instanceof Uint8Array ? respBody : null);
       } catch (error) {
+        const connError = connErrors.get(httpConn);
```
Comment (aapoalas) [inline runtime/js/40_http.js:155]: For this and the below line, I am not exactly 100% on this but I think (for normal Map at least) it is more performant to check membership and only get if true.
```javascript
if (error instanceof errors.BadResource && connErrors.has(httpConn)) {
  error = new connError.constructor(connErrors.get(httpConn).message);
}
```

File: runtime/js/40_http.js [hunk 4]
```diff
@@ -35,10 +37,16 @@
           this.#rid,
         );
       } catch (error) {
+        // A connection error seen here would cause disrupted responses to throw
+        // a generic `BadResource` error. Instead store this error and replace
+        // those with it.
+        connErrors.set(this, error);
```
Comment (aapoalas) [inline runtime/js/40_http.js:43]: If you're confident that this is indeed an Error object, then I think you could just save the message part of it since that's the only part that actually gets used down the line.

Comment (nayeemrmn) [reply runtime/js/40_http.js:43]: The `.constructor` as well. Conceptually I'm cloning the error under a new call stack, it's simpler like this.

Comment (aapoalas) [reply runtime/js/40_http.js:43]: Aaah, oh true yeah. I missed the `.constructor` usage. Yeah, saving the error object itself is good.

**Comment by hsjoberg** [comment]
FYI I can confirm that this pull request fixes the crashes I was having regrading the error message in question.

**Comment by ry** [comment]
deferring to @kt3k for final review

File: runtime/js/40_http.js [hunk 5]
```diff
@@ -14,6 +14,8 @@
     return new HttpConn(rid);
   }
 
+  const connErrors = new WeakMap();
```
Comment (kt3k) [inline runtime/js/40_http.js:17]: Do you have any reason to use WeakMap over a simple property like httpConn.error (`Error | undefined`)?

**Review by kt3k — APPROVED** [review]
LGTM with one question.

File: runtime/js/40_http.js (hunk 5 above)
Comment (nayeemrmn) [reply runtime/js/40_http.js:17]: To properly hide it from the public API.

Comment (lucacasonato) [reply runtime/js/40_http.js:17]: Then use a private property or symbol property.

Comment (lucacasonato) [reply runtime/js/40_http.js:17]: We use symbols for essentially all web APIs now. Should be fine.

Comment (nayeemrmn) [reply runtime/js/40_http.js]: Replaced with a symbol.

**Review by kt3k — APPROVED** [review]
@nayeemrmn Thanks for the fix! LGTM
