### PR TITLE
Reorganize $DENO_DIR/deps folder and split by protocol

### LINKED ISSUE #930: Relative import uses HTTP from module loaded over HTTPS
`entry.ts`
```typescript
import message from "./dep";
console.log(message);
```

`dep.ts`
```typescript
export default "success";
```

---

Running `entry.ts` locally works fine:

```shell
$ deno entry
success
```

When attempting to run `entry.ts` over HTTPS, it:

* Loads `entry.ts` fine.
* Attempts to load `dep.ts` over *HTTP* rather than HTTPS.
* Gets a redirect to HTTPS, but does not follow it (see #931).
* Fails to find `dep.ts`.

---

```
$ deno -D -r --recompile https://cdn.rawgit.com/qoh/deno-remote-import-bug/tag/entry
DEBUG RS - starting background reactor
DEBUG RS - msg_from_js Start sync true
DEBUG JS - cwd /home/ns/dev/deno/deno-remote-import-bug
DEBUG JS - args [ "https://cdn.rawgit.com/qoh/deno-remote-import-bug/tag/entry" ]
DEBUG JS - compiler.run { moduleSpecifier: "https://cdn.rawgit.com/qoh/deno-remote-import-bug/tag/entry", containingFile: "/home/ns/dev/deno/deno-remote-import-bug/" }
DEBUG JS - compiler.resolveModule { moduleSpecifier: "https://cdn.rawgit.com/qoh/deno-remote-import-bug/tag/entry", containingFile: "/home/ns/dev/deno/deno-remote-import-bug/" }
DEBUG JS - compiler.resolveFileName { moduleSpecifier: "https://cdn.rawgit.com/qoh/deno-remote-import-bug/tag/entry", containingFile: "/home/ns/dev/deno/deno-remote-import-bug/" }
DEBUG JS - os.ts codeFetch https://cdn.rawgit.com/qoh/deno-remote-import-bug/tag/entry /home/ns/dev/deno/deno-remote-import-bug/
DEBUG RS - code_fetch. module_specifier https://cdn.rawgit.com/qoh/deno-remote-import-bug/tag/entry containing_file /home/ns/dev/deno/deno-remote-import-bug/
DEBUG RS - resolve_module module_specifier https://cdn.rawgit.com/qoh/deno-remote-import-bug/tag/entry containing_file /home/ns/dev/deno/deno-remote-import-bug/
DEBUG RS - module_name: https://cdn.rawgit.com/qoh/deno-remote-import-bug/tag/entry, filename: /home/ns/.deno/deps/cdn.rawgit.com/qoh/deno-remote-import-bug/tag/entry
Downloading https://cdn.rawgit.com/qoh/deno-remote-import-bug/tag/entry
DEBUG RS - resolving host="cdn.rawgit.com", port=443
DEBUG RS - connecting to 151.139.237.11:443
DEBUG RS - loop process - 1 events, 0.000s
DEBUG RS - loop process - 1 events, 0.000s
DEBUG RS - loop process - 1 events, 0.000s
DEBUG RS - loop process - 1 events, 0.000s
DEBUG RS - loop process - 1 events, 0.000s
DEBUG RS - flushed 76 bytes
DEBUG RS - loop process - 1 events, 0.000s
DEBUG RS - read 596 bytes
DEBUG RS - parsed 14 headers
DEBUG RS - incoming body is content-length (104 bytes)
DEBUG RS - incoming body completed
DEBUG RS - pooling idle connection for ("https://cdn.rawgit.com", Http1)
DEBUG RS - dropping I/O source: 0
DEBUG RS - Trying https://cdn.rawgit.com/qoh/deno-remote-import-bug/tag/entry.ts...
Downloading https://cdn.rawgit.com/qoh/deno-remote-import-bug/tag/entry.ts
DEBUG RS - resolving host="cdn.rawgit.com", port=443
DEBUG RS - connecting to 151.139.237.11:443
DEBUG RS - loop process - 1 events, 0.000s
DEBUG RS - loop process - 1 events, 0.000s
DEBUG RS - flushed 79 bytes
DEBUG RS - loop process - 1 events, 0.000s
DEBUG RS - read 535 bytes
DEBUG RS - parsed 14 headers
DEBUG RS - incoming body is chunked encoding
DEBUG RS - incoming chunked header: 0x33 (51 bytes)
DEBUG RS - incoming body completed
DEBUG RS - pooling idle connection for ("https://cdn.rawgit.com", Http1)
DEBUG RS - dropping I/O source: 0
DEBUG RS - set file perm to 438
DEBUG RS - load_cache /home/ns/.deno/gen/6cfe4395a52dff9e4cee4a9cf7b88d56d2d44c19.js
DEBUG RS - msg_from_js CodeFetch sync true
DEBUG JS - resolveModule sourceCode length: 51
DEBUG JS - resolveModule has outputCode: false
DEBUG JS - compiler.setFileName { moduleSpecifier: "https://cdn.rawgit.com/qoh/deno-remote-import-bug/tag/entry", containingFile: "/home/ns/dev/deno/deno-remote-import-bug/" }
DEBUG JS - compiler._resolveDependencies /home/ns/.deno/deps/cdn.rawgit.com/qoh/deno-remote-import-bug/tag/entry.ts
Compiling https://cdn.rawgit.com/qoh/deno-remote-import-bug/tag/entry.ts
DEBUG JS - getCurrentDirectory()
DEBUG JS - getScriptSnapshot() /home/ns/.deno/deps/cdn.rawgit.com/qoh/deno-remote-import-bug/tag/entry.ts
DEBUG JS - getScriptVersion() /home/ns/.deno/deps/cdn.rawgit.com/qoh/deno-remote-import-bug/tag/entry.ts
DEBUG JS - getScriptKind() /home/ns/.deno/deps/cdn.rawgit.com/qoh/deno-remote-import-bug/tag/entry.ts
DEBUG JS - getCompilationSettings()
DEBUG JS - getDefaultLibFileName()
DEBUG JS - compiler.resolveModule { moduleSpecifier: "globals.d.ts", containingFile: "$asset$" }
DEBUG JS - compiler.resolveFileName { moduleSpecifier: "globals.d.ts", containingFile: "$asset$" }
DEBUG JS - resolveModule sourceCode length: 134678
DEBUG JS - resolveModule has outputCode: true
DEBUG JS - compiler.setFileName { moduleSpecifier: "globals.d.ts", containingFile: "$asset$" }
DEBUG JS - resolveModuleNames() { moduleNames: [ "./dep" ], containingFile: "/home/ns/.deno/deps/cdn.rawgit.com/qoh/deno-remote-import-bug/tag/entry.ts" }
DEBUG JS - compiler.resolveModule { moduleSpecifier: "./dep", containingFile: "/home/ns/.deno/deps/cdn.rawgit.com/qoh/deno-remote-import-bug/tag/entry.ts" }
DEBUG JS - compiler.resolveFileName { moduleSpecifier: "./dep", containingFile: "/home/ns/.deno/deps/cdn.rawgit.com/qoh/deno-remote-import-bug/tag/entry.ts" }
DEBUG JS - os.ts codeFetch ./dep /home/ns/.deno/deps/cdn.rawgit.com/qoh/deno-remote-import-bug/tag/entry.ts
DEBUG RS - code_fetch. module_specifier ./dep containing_file /home/ns/.deno/deps/cdn.rawgit.com/qoh/deno-remote-import-bug/tag/entry.ts
DEBUG RS - resolve_module module_specifier ./dep containing_file http://cdn.rawgit.com/qoh/deno-remote-import-bug/tag/entry.ts
DEBUG RS - module_name: http://cdn.rawgit.com/qoh/deno-remote-import-bug/tag/dep, filename: /home/ns/.deno/deps/cdn.rawgit.com/qoh/deno-remote-import-bug/tag/dep
Downloading http://cdn.rawgit.com/qoh/deno-remote-import-bug/tag/dep
DEBUG RS - resolving host="cdn.rawgit.com", port=80
DEBUG RS - connecting to 151.139.237.11:80
DEBUG RS - loop process - 1 events, 0.000s
DEBUG RS - flushed 74 bytes
DEBUG RS - loop process - 1 events, 0.000s
DEBUG RS - read 468 bytes
DEBUG RS - parsed 7 headers
DEBUG RS - incoming body is content-length (178 bytes)
DEBUG RS - incoming body completed
DEBUG RS - pooling idle connection for ("http://cdn.rawgit.com", Http1)
DEBUG RS - Trying http://cdn.rawgit.com/qoh/deno-remote-import-bug/tag/dep.ts...
Downloading http://cdn.rawgit.com/qoh/deno-remote-import-bug/tag/dep.ts
DEBUG RS - dropping I/O source: 0
DEBUG RS - resolving host="cdn.rawgit.com", port=80
DEBUG RS - connecting to 151.139.237.11:80
DEBUG RS - loop process - 1 events, 0.000s
DEBUG RS - flushed 77 bytes
DEBUG RS - loop process - 1 events, 0.000s
DEBUG RS - read 471 bytes
DEBUG RS - parsed 7 headers
DEBUG RS - incoming body is content-length (178 bytes)
DEBUG RS - incoming body completed
DEBUG RS - pooling idle connection for ("http://cdn.rawgit.com", Http1)
DEBUG RS - Trying http://cdn.rawgit.com/qoh/deno-remote-import-bug/tag/dep.js...
Downloading http://cdn.rawgit.com/qoh/deno-remote-import-bug/tag/dep.js
DEBUG RS - dropping I/O source: 0
DEBUG RS - resolving host="cdn.rawgit.com", port=80
DEBUG RS - connecting to 151.139.237.11:80
DEBUG RS - loop process - 1 events, 0.000s
DEBUG RS - flushed 77 bytes
DEBUG RS - loop process - 1 events, 0.000s
DEBUG RS - read 471 bytes
DEBUG RS - parsed 7 headers
DEBUG RS - incoming body is content-length (178 bytes)
DEBUG RS - incoming body completed
DEBUG RS - pooling idle connection for ("http://cdn.rawgit.com", Http1)
DEBUG RS - msg_from_js CodeFetch sync true
DEBUG RS - dropping I/O source: 0
DEBUG RS - op err Cannot resolve module "./dep" from "/home/ns/.deno/deps/cdn.rawgit.com/qoh/deno-remote-import-bug/tag/entry.ts"
DEBUG JS - compiler.getGeneratedContents gen/bundle/main.js
DEBUG JS - compiler.getGeneratedContents main.js.map
NotFound: Cannot resolve module "./dep" from "/home/ns/.deno/deps/cdn.rawgit.com/qoh/deno-remote-import-bug/tag/entry.ts"
    at maybeError (deno/js/errors.ts:25:12)
    at maybeThrowError (deno/js/errors.ts:14:15)
    at sendSync (deno/js/dispatch.ts:70:5)
    at Object.codeFetch (deno/js/os.ts:31:19)
    at DenoCompiler.resolveModule (deno/js/compiler.ts:525:38)
    at DenoCompiler._resolveModuleName (deno/js/compiler.ts:349:33)
    at moduleNames.map.name (deno/js/compiler.ts:657:33)
    at Array.map (<anonymous>)
    at DenoCompiler.resolveModuleNames (deno/js/compiler.ts:649:24)
    at Object.compilerHost.resolveModuleNames (deno/third_party/node_modules/typescript/lib/typescript.js:111684:117)
```

---

```shell
$ deno --version
deno: 0.1.7
v8: 7.0.276.15
```

### PR DESCRIPTION
**Pull request by kevinkassimo**
Supposed to close #930 

Reorganize `$DENO_DIR/deps` folder by creating protocol specific subdirectories.
e.g. 
```ts
import "http://a.com/a.ts"
import "https://b.com/b.ts"
```
should create folder `$DENO_DIR/deps/http/a.com` and `$DENO_DIR/deps/https/b.com`

I feel this might be also a necessary step for Deno to probably support other protocols in the future.

There is currently no test on TS side. To add tests, I hope I could get sample code from https://github.com/denoland/deno/issues/930#issue-367501763 to be hosted somewhere stable.

### CODE REVIEW

File: src/deno_dir.rs [hunk 1]
```diff
@@ -279,10 +299,17 @@ impl DenoDir {
         module_name = p.clone();
         filename = p;
       }
+      "https" => {
+        module_name = j.to_string();
+        filename = deno_fs::normalize_path(
+          get_cache_filename(self.deps_https.as_path(), j).as_ref(),
+        )
+      }
+      // TODO(kevinkassimo): change this to support other protocols than http
```
Comment (hayd) [inline src/deno_dir.rs]: perhaps should do:
```
"http" => ...
_ => unimplemented!();
```

Comment (kevinkassimo) [reply src/deno_dir.rs]: Good idea.

**Comment by kevinkassimo** [comment]
@ry Is this change of design appropriate? I might want to settle this PR sooner, or close it, or explicitly let someone else take care of it (having some urgent academic business need to deal with, and might have to pause my contribution to deno for about 1 month)

**Comment by kevinkassimo** [comment]
@ry I feel http and https might be a special case here that could share the same cache (e.g. I could make `deps/https` a symlink to `deps/http`), but the separation of cache folder might be important considering extensibility for other protocols (`ftp`, `ipfs` or more)

Otherwise, we might have to use other sorts of metadata to store the original protocol used for script retrieval.

**Comment by Macil** [comment]
HTTP and HTTPS could easily serve different files if there's a man-in-the-middle attack. Imagine you're on some crappy free wifi that injects some advertising code into any javascript files downloaded over http, you run one insignificant sandboxed software project using deno that imports `http://foo...`, and then run a different project in deno with a bunch of --allow flags that imports `https://foo...`. If the latter process re-uses the cache of `http://foo...`, then you've just ran malicious code with privileges. Even if you checked the latter project's code fully prior to running it with privileges, you wouldn't be able to spot the issue.

**Comment by hayd** [comment]
There is simplicity in an injective/invertible cache map, being able to know precisely where a cached file was from. The cost of downloading the same file referenced with http and https twice seems worth it.

I had thought the bug this was solving was relative imports inside ts, which requires building the url from the cache location..?

It would be good if this code could be generic over all schemes.
