### PR TITLE
fix: stdout and stderr encoding on Windows

### LINKED ISSUE #6001: windows doesn't print emojis correctly
Hi! This is my first time looking at Deno, and it seems to be very exciting :)

I was playing around with the examples from the tutorial and noticed this inconsistency: (using powershell and windows terminal):

```
> deno run https://deno.land/std/examples/welcome.ts
Welcome to Deno 🦕
> deno run --allow-net https://deno.land/std/examples/curl.ts https://deno.land/std/examples/welcome.ts
console.log("Welcome to Deno ­ƒªò");
```

I found that editing `curl.ts` to add the line 
```ts
import { decode } from "https://deno.land/std/encoding/utf8.ts";
```
and replacing the `Deno.stdout.write` line with
```ts
console.log(decode(body));
```
seems to make the downloaded file print out correctly.

### LINKED ISSUE #14516: The console display is abnormal on Windows when console encoding is not utf-8
implement:
```js
console.log("你好，世界")
```
output:
```
浣犲ソ锛屼笘鐣?
```
Deno:1.21.2
OS:Windows 11

### LINKED ISSUE #14545: regression: `confirm` sometimes doesn't show prompt before receiving input on Windows
In #14435, everything was changed to use the stdio pipes found in the resources table. This seems to have caused a regression where the output of `op_print` doesn't flush the data on Windows even though there's an explicit flush call.

### PR DESCRIPTION
**Pull request by dsherret**
Given:

```ts
const encoder = new TextEncoder();

// stdout
{
  console.log("你好，世界");
  const size = await Deno.stdout.write(encoder.encode("🦕\n"));
  if (size !== 5) {
    throw new Error();
  }
}

// stderr
{
  console.error("你好，世界");
  const size = await Deno.stderr.write(encoder.encode("🦕\n"));
  if (size !== 5) {
    throw new Error();
  }
}
```

Before:

```
õ¢áÕÑ¢´╝îõ©ûþòî
­ƒªò
õ¢áÕÑ¢´╝îõ©ûþòî
­ƒªò
```

After:

```
你好，世界
🦕
你好，世界
🦕
```

Closes #6001
Closes #14516
Closes #14545

### CODE REVIEW

**Comment by dsherret** [comment]
I tried to add a test for this, but whatever I tried passed before and after (I think probably because our test utilitity collects data with a pipe and so it's not a console and doesn't get this special behaviour applied)

File: runtime/ops/io.rs [hunk 1]
```diff
@@ -301,33 +293,119 @@ impl Resource for ChildStderrResource {
...
+#[derive(Clone)]
+enum StdFileResourceInner {
+  // Ideally we would store stdio as an StdFile, but we get some Windows
+  // specific functionality for free by using Rust std's wrappers. So we
+  // take a bit of a complexity hit here in order to not have to duplicate
+  // the functionality in Rust's std/src/sys/windows/stdio.rs
+  Stdin,
+  Stdout,
+  Stderr,
+  File(Arc<Mutex<StdFile>>),
```
Comment (dsherret) [inline runtime/ops/io.rs:305]: Question: why do we store this in a mutex? Can't we just store `Arc<StdFile>` and clone it out when we need it or does this need exclusive access?

File: runtime/ops/io.rs [hunk 2]
```diff
@@ -50,14 +50,6 @@ static STDOUT_HANDLE: Lazy<StdFile> =
...
   Lazy::new(|| unsafe { StdFile::from_raw_fd(2) });
 
-/// Due to portability issues on Windows handle to stdout is created from raw
-/// file descriptor.  The caveat of that approach is fact that when this
-/// handle is dropped underlying file descriptor is closed - that is highly
-/// not desirable in case of stdout.  That's why we store this global handle
-/// that is then cloned when obtaining stdio for process. In turn when
-/// resource table is dropped storing reference to that handle, the handle
-/// itself won't be closed (so Deno.core.print) will still work.
-// TODO(ry) It should be possible to close stdout.
```
Comment (ry) [inline runtime/ops/io.rs:60]: regarding the TODO is it possible to close stdout after this patch?

File: runtime/ops/io.rs (hunk 1 above)
Comment (ry) [reply runtime/ops/io.rs:305]: I don't know off hand. I guess you'd have to remove it and see what happens.

**Review by ry — APPROVED** [review]
LGTM

File: runtime/ops/io.rs (hunk 2 above)
Comment (dsherret) [reply runtime/ops/io.rs:60]: No, not possible still since they're still held globally here (and not stored in a `Mutex<Option<T>>`).

I removed the todo because I didn't think it was worth keeping it in the code since I think doing this will arise from the need to do it.

**Review by piscisaureus — APPROVED** [review]

File: runtime/ops/io.rs (hunk 1 above)
Comment (dsherret) [reply runtime/ops/io.rs:305]: Discussed with Bert and the reason for this is because Read & Write both require `&mut` so storing this in a mutex is faster than duplicating the handle which also could fail.

File: cli/tests/integration/repl_tests.rs [hunk 3]
```diff
@@ -206,6 +206,20 @@ fn pty_assign_global_this() {
...
+  // windows was having issues displaying this
+  util::with_pty(&["repl"], |mut console| {
+    console.write_line("console.log('🦕');");
+    console.write_line("close();");
+
+    let output = console.read_all_output();
+    // one for input, one for output
+    let emoji_count = output.chars().filter(|c| *c == '🦕').count();
+    assert_eq!(emoji_count, 2);
+  });
```
Comment (bartlomieju) [inline cli/tests/integration/repl_tests.rs:220]: Nice 👍
