### PR TITLE
fix(core): don't panic on stdout/stderr write failures

### LINKED ISSUE #10764: cli: panics when the output is piped to a non-existent executable
Steps to reproduce:
```
➜  cat log.ts 
console.log("hello");
➜  deno  run log.ts | 404
zsh: command not found: 404
thread 'main' panicked at 'failed printing to stdout: Broken pipe (os error 32)', library/std/src/io/stdio.rs:940:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: failed to initiate panic, error 5
[1]    52032 abort      deno run log.ts | 
       52033 exit 127   404
```

### PR DESCRIPTION
**Pull request by cmoog**
Closes #10764

### Steps to reproduce
```bash
echo "console.log(123)" > log.ts
touch 404
chmod +x ./404
```

### Old behavior

```bash
$ deno run log.ts | ./404
Failed to execute process './404'. Reason:
exec: Exec format error
The file './404' is marked as an executable but could not be run by the operating system.
thread 'main' panicked at 'failed printing to stdout: Broken pipe (os error 32)', library/std/src/io/stdio.rs:940:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: failed to initiate panic, error 5
fish: Process 843852, “deno” “deno run log.ts | ./404” terminated by signal SIGABRT (Abort)
```

### New Behavior 
```bash
$ ./target/debug/deno run log.ts | ./404
Failed to execute process './404'. Reason:
exec: Exec format error
The file './404' is marked as an executable but could not be run by the operating system.
error: Uncaught BrokenPipe: Broken pipe (os error 32)
console.log(123);
        ^
    at deno:core/core.js:86:46
    at unwrapOpResult (deno:core/core.js:106:13)
    at opSync (deno:core/core.js:120:12)
    at Object.print (deno:core/core.js:132:5)
    at Console.<anonymous> (deno:runtime/js/99_main.js:324:40)
    at console.log (deno:extensions/console/02_console.js:1495:22)
    at file:///home/charlie/Code/deno/log.ts:3:9
```

### CODE REVIEW

**Comment by bartlomieju** [comment]
@cmoog thank you for the PR, could we get some integration test case that exercises this fix?

**Comment by cmoog** [comment]
Pushed an integration test here https://github.com/denoland/deno/pull/11039/commits/bbfeef74c807b9ee29c38b43d1740c5799f9a33f.  Thanks!

**Comment by bartlomieju** [comment]
In some other places we just ignore `BrokenPipe` error without printing anything out: https://github.com/denoland/deno/blob/7b559ee89ef2dd4be6a45af6ae1e3e09c76fec01/cli/main.rs#L246-L258 I wonder if we should do the same here. @ry thoughts?

**Comment by cmoog** [comment]
From what I've gathered, the places that intentionally ignore `BrokenPipe` as shown above are handling nonessential informational output from the `deno` CLI itself, not from user code. If user code attempts to print data and the print fails, the runtime must raise an error in some capacity. 

For reference, Go terminates the program by handling the OS signal directly. (which in my view is a defect... I'd expect the broken pipe error to be returned in the `error` value)

```
$ cat main.go
package main

import "fmt"

func main() {
        _, _ = fmt.Println("123")
}
$ go run main.go | ./404
Failed to execute process './404'. Reason:
exec: Exec format error
The file './404' is marked as an executable but could not be run by the operating system.
signal: broken pipe
```

File: cli/tests/integration_tests.rs [hunk 1]
```diff
@@ -3158,6 +3158,29 @@ console.log("finish");
...
+      .spawn()
+      .unwrap()
+      .wait_with_output()
+      .unwrap();
+
+    assert!(!output.status.success());
+    let stderr = std::str::from_utf8(output.stderr.as_ref()).unwrap().trim();
+    assert!(stderr.contains("Uncaught BrokenPipe"));
+    assert!(!stderr.contains("panic"));
+  }
```
Comment (bartlomieju) [inline cli/tests/integration_tests.rs:3182]: Great test!

**Review by bartlomieju — APPROVED** [review]
Thanks @cmoog this makes sense. Cleanly implemented, no comments. LGTM!
