### PR TITLE
fix(lsp): rewrite imports for 'Move to a new file' action

### LINKED ISSUE #27228: jsr imports become http imports after `Move to a new file`
Version: Deno 2.1.2

## Reproduction

```ts
import { Path } from "jsr:@david/path"

export const f<<o>>oo = new Path("")
// Move to a new file
```

### Expected

```ts
import { Path } from "jsr:@david/path"

export const f<<o>>oo = new Path("")
// Move to a new file
```

### Actual

```ts
import { Path } from "https://jsr.io/@david/path/0.2.0/mod"

export const fooo = new Path("")
```

which gives you

```
Failed resolving types. Importing JSR packages via HTTPS specifiers for type checking is not supported for performance reasons. If you would like types, import via a `jsr:` specifier instead or else use a non-statically analyzable dynamic import.
  Importing: https://jsr.io/@david/path/0.2.0/mod
    at file:///Users/nemo/repo/quotalab-scripts/bin/en.ts:1:22
```

### PR DESCRIPTION
**Pull request by nayeemrmn**
Fixes #27228.

### CODE REVIEW

**Review by dsherret — APPROVED** [review]
LGTM

File: cli/lsp/analysis.rs [hunk 1]
```diff
@@ -15,6 +15,7 @@ use crate::lsp::search::PackageSearchApi;
 use crate::tools::lint::CliLinter;
 use crate::util::path::relative_specifier;
 use deno_config::workspace::MappedResolution;
+use deno_core::resolve_url;
```
Comment (nayeemrmn) [inline cli/lsp/analysis.rs:18]:
```suggestion
```
