### PR TITLE
fix: improve http client builder error message

### LINKED ISSUE #9364: "Unable to build http client error message" when specifying CA Cert using --cert
I'm trying to run deno behind a corporate proxy, but running into a blocker regarding our certificates / proxy setup. I try to run the base command straight out (HTTPS_PROXY:PORT is using my correct proxy, masked for this issue - but the variables are being read appropriately)

```
machine:~ user$ deno run -L debug https://deno.land/std/examples/welcome.ts
DEBUG RS - deno_runtime::js:9 - Deno isolate init with snapshots.
DEBUG RS - deno_core::shared_queue:75 - rust:shared_queue:reset
DEBUG JS - args []
DEBUG RS - deno:969 - main_module https://deno.land/std/examples/welcome.ts
DEBUG RS - deno::file_fetcher:526 - FileFetcher::fetch() - specifier: https://deno.land/std/examples/welcome.ts
DEBUG RS - deno_runtime::permissions:694 - ⚠️️  Granted network access to "deno.land"
DEBUG RS - deno::file_fetcher:446 - FileFetcher::fetch_remote() - specifier: https://deno.land/std/examples/welcome.ts
DEBUG RS - deno_runtime::permissions:694 - ⚠️️  Granted network access to "deno.land"
DEBUG RS - deno::file_fetcher:365 - FileFetcher::fetch_cached - specifier: https://deno.land/std/examples/welcome.ts
Download https://deno.land/std/examples/welcome.ts
DEBUG RS - reqwest::connect:525 - starting new connection: https://deno.land/
DEBUG RS - reqwest::connect:393 - proxy(http://HTTPS_PROXY:PORT) intercepts 'https://deno.land/'
DEBUG RS - rustls::client::hs:89 - No cached session for DNSNameRef("deno.land")
DEBUG RS - rustls::client::hs:211 - Not resuming any session
DEBUG RS - rustls::client::hs:430 - ALPN protocol is None
DEBUG RS - rustls::client::hs:598 - Using ciphersuite TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
DEBUG RS - rustls::client::tls12:209 - ECDHE curve is ECParameters { curve_type: NamedCurve, named_group: secp256r1 }
DEBUG RS - rustls::client::tls12:508 - Server DNS name is DNSName("deno.land")
Sending fatal alert BadCertificate
error: error sending request for url (https://deno.land/std/examples/welcome.ts): error trying to connect: invalid certificate: UnknownIssuer
```

Fair enough, after some digging I found the `--cert` option. Retrying with our cert:

```
machine:~ user$ deno run -L debug --cert ~/certs/cert.pem https://deno.land/std/examples/welcome.ts
error: Unable to build http client
machine:~ user$ 
```

This is confusing to me. The cert is certainly valid for accessing other internal services, but more concerning is that the debugging gets short circuited - **I don't have a lot of visibility as to why the http client failed to build other than that I added this cert to the command**. Is there a way to debug the underlying issue with why deno doesn't like my cert? I would at least expect the BadCertificate error if it was invalid.

```
machine:~ user$ deno --version
deno 1.7.1 (release, x86_64-apple-darwin)
v8 8.9.255.3
typescript 4.1.3
```

### PR DESCRIPTION
**Pull request by bnoordhuis**
Include the lower-level error message in the generic error message.

No test because I can't actually make it fail by passing it bad PEM.
I checked and `reqwest::Certificate::from_pem()` always returns `Ok()`.

Fixes #9364.

### CODE REVIEW

File: op_crates/fetch/lib.rs [hunk 1]
```diff
@@ -433,5 +434,5 @@ fn create_http_client(
   }
   builder
     .build()
-    .map_err(|_| deno_core::error::generic_error("Unable to build http client"))
+    .map_err(|e| generic_error(format!("Unable to build http client: {}", e)))
```
Comment (lucacasonato) [inline op_crates/fetch/lib.rs:437]: Future stuff: we should consider a different error type here before stabilizing.

**Review by lucacasonato — APPROVED** [review]
LGTM

File: op_crates/fetch/lib.rs (hunk 1 above)
Comment (bnoordhuis) [reply op_crates/fetch/lib.rs:437]: Noted!
