### PR TITLE
fix(npm): recursive translation of reexports, remove window global in node code

### LINKED ISSUE #15817: npm: handle the entrypoint as if it's in npm modules when certain ENV var is given
We need to handle the entrypoint as if it's in npm modules (similar to `--compat` mode) when certain ENV var is given in order to support `child_process.fork` in `std/node` https://github.com/denoland/deno_std/issues/2636

```
DENO_NODE_FORK=1 deno run script.js # script.js works like node.js script
```

### PR DESCRIPTION
**Pull request by bartlomieju**
Closes https://github.com/denoland/deno/issues/15691
Closes #15817

### CODE REVIEW

File: cli/node/mod.rs [hunk 1]
```diff
@@ -710,69 +712,117 @@ pub fn translate_cjs_to_esm(
...
+      } else {
+        source.push(format!(
+          "const reexport{} = require.cache[\"{}\"].require(\"{}\");",
+          export_index, referrer_filepath_str, reexport
+        ));
+      }
+
+      let non_default_exports = analysis.exports.iter().filter(|e| {
+        e.as_str() != "default"
+          && e.as_str() != "__esModule"
```
Comment (dsherret) [inline cli/node/mod.rs:811]: Why does this need special handling of `__esModule`?

Comment (bartlomieju) [reply cli/node/mod.rs:811]: Because recursively translated modules can have this property defined as well and that would cause multiple `__esModule` declarations

File: cli/node/mod.rs [hunk 2]
```diff
@@ -710,69 +712,117 @@ pub fn translate_cjs_to_esm(
...
-        e.as_str() != "default" && !root_exports.contains(e.as_str())
-      }) {
+      let analysis = perform_cjs_analysis(
+        reexport_specifier.as_str(),
+        reexport_file.media_type,
+        reexport_file.source.to_string(),
+      )?;
+
+      for reexport in analysis.reexports {
+        reexports_to_handle.push_back((
```
Comment (dsherret) [inline cli/node/mod.rs:790]: It seems this goes over the files like so:

```
1
  3
    5
      8
    6
  4
    7
2
```

I think it should be the following to match the execution order?

```
1
  2
    3
      4
    5
  6
    7
8
```

File: cli/node/mod.rs (hunk 1 above)
Comment (dsherret) [reply cli/node/mod.rs:811]: What happens when other exports have the same name?

Comment (bartlomieju) [reply cli/node/mod.rs:811]: IIRC in Node they get overriden, but we haven't hit this problem in Deno yet

File: cli/node/mod.rs (hunk 2 above)
Comment (bartlomieju) [reply cli/node/mod.rs:790]: Is there a specific reason for it? Checking with how it's implemented in Node it actually goes depth first

Comment (dsherret) [reply cli/node/mod.rs:790]: I believe so it matches the code at runtime?

Comment (bartlomieju) [reply cli/node/mod.rs:790]: I'll look into that

Comment (dsherret) [reply cli/node/mod.rs:790]: Actually, I think the generated code handles all of this. Nevermind.

File: cli/tests/testdata/npm/env_var_re_export/main.js [hunk 3]
```diff
@@ -0,0 +1,3 @@
+import { getEnv } from "npm:@denotest/env-var-re-export";
+
+console.log(getEnv());
```
Comment (dsherret) [inline cli/tests/testdata/npm/env_var_re_export/main.js:3]: Now works the same as node:

```sh
> $env:NODE_ENV="" ; node file.mjs
dev
V:\scratch-npm
> $env:NODE_ENV="production" ; node file.mjs
prod
```

**Review by dsherret — APPROVED** [review]
LGTM
