### PR TITLE
fix: upgrade to swc_ecmascript 0.143

### LINKED ISSUE #14181: Inconsistent formatting for long dictionary ternaries
Deno wants to format the code in the following way, with the first long dictionary value ternary being different then all of the following!

```ts
export default (foo, bar) => {
  return {
    "foo_long_ish": foo.length === 0
      ? foo
      : foo.reduceRight(long_reducer("foo")),
    "bar_long_ish": bar.length === 0 ? bar
    : bar.reduceRight(long_reducer("bar")),
  };
};

```

```
$ deno --version
deno 1.20.4 (release, aarch64-apple-darwin)
v8 10.0.139.6
typescript 4.6.2
```

```
$ uname -a
Darwin Macintosh.local 21.4.0 Darwin Kernel Version 21.4.0: Fri Mar 18 00:47:26 PDT 2022; root:xnu-8020.101.4~15/RELEASE_ARM64_T8101 arm64 arm64 MacBookPro17,1 Darwin
```

### PR DESCRIPTION
**Pull request by dsherret**
- Upgrades to deno_ast 0.14
- Upgrades to the latest dprint plugins which have perf improvements and bug fixes
- This supports parsing source files with missing close braces, which should help improve our editor support.

Closes #14181

### CODE REVIEW

File: cli/tests/testdata/lint/without_config/malformed.js [hunk 1]
```diff
@@ -1,4 +1,4 @@
 // deno-fmt-ignore-file
 
 // intentionally malformed file
-export class A {
```
Comment (dsherret) [inline cli/tests/testdata/lint/without_config/malformed.js:4]: deno_lint works now at analyzing files like this so I changed it to something it will fail analyzing.

File: cli/tests/integration/repl_tests.rs [hunk 2]
```diff
@@ -162,7 +163,7 @@ fn pty_complete_imports() {
 
     let output = console.read_all_output();
     assert!(output.contains("Hello World"));
-    assert!(output.contains("\ntesting output"));
+    assert!(output.contains("testing output\u{1b}"));
```
Comment (dsherret) [inline cli/tests/integration/repl_tests.rs:166]: The other comparison was flaky on Windows, so I switched this.

**Review by bartlomieju — APPROVED** [review]
LGTM
