### PR TITLE
fix(ext/node): add `fs.promises.fstat` and `FileHandle#stat`

### LINKED ISSUE #23301: Node FileHandle#stat() not implemented
Getting a wall of these warnings when running `docusaurus serve`:

```
[WARNING] The image at "/home/divy/gh/littledivy/my-website/blog/2021-08-26-welcome/docusaurus-plushie-banner.jpeg" can't be read correctly. Please ensure it's a valid image.
handle.stat is not a function
```

### PR DESCRIPTION
**Pull request by manzt**
Fixes #23301

Implements `FileHandle.stat`. This PR also adds a promisified `fs.fstat` under 'fs/promises', which is used internally by `FileHandle.stat`.

part of #25554

### CODE REVIEW

File: ext/node/polyfills/internal/fs/handle.ts [hunk 1]
```diff
@@ -152,7 +161,7 @@ function fsCall(fn, handle, ...args) {
     });
   }
 
-  return fn(handle, ...args);
+  return fn(handle.fd, ...args);
```
Comment (manzt) [inline ext/node/polyfills/internal/fs/handle.ts:164]: Added a test for `fh.writeFile` to make sure this change is OK.

Comment (kt3k) [reply ext/node/polyfills/internal/fs/handle.ts:164]: I think we should rather let `fstat` accept `FileHandle`, which improves the compatibility further (See this change for reference https://github.com/denoland/deno/pull/25555 )

This `fsCall` util comes from this part in Node.js ( https://github.com/nodejs/node/blob/ccac4ee19d508abaf38bbabb87288ddeec7fcc21/lib/internal/fs/promises.js#L452-L470 ). I think it would be better to keep the code as aligned to node.js as possible.

Comment (kt3k) [reply ext/node/polyfills/internal/fs/handle.ts:164]: Nevermind. This looks just fine to me

**Review by kt3k — APPROVED** [review]
Sorry for the initial confusing comment. This now looks good to me. Nice work!
