### PR TITLE
fix: replace bad rid panics with errors

### LINKED ISSUE #2249: Replace `panic!`s with graceful errors for userland processing
Currently, we have many code simply panicking and hard crashing on invalid operations or input, e.g.
https://github.com/denoland/deno/blob/200bed9277182e40e4ee4bb08b237f1c2d1ae244/cli/resources.rs#L182-L195

Ideally we should instead wrap these conditions as errors and forward to TS side, such that users could provide code for handling.

However, there are challenges mainly from Tokio fs related problems: async io traits requires `std::io::Error` as error type, yet certain operations (e.g. `BadResource()`) does not exist in std and is hard to translate as one of the `std::io::ErrorKind` enum:
https://github.com/denoland/deno/blob/200bed9277182e40e4ee4bb08b237f1c2d1ae244/cli/resources.rs#L203-L220

One proposal was to merge things like `BadResource` into `NotFound`, yet this somehow violates `ENOENT` definition from the POSIX standard. Ideally we want to emit something similar to `EBADF`, yet such error is not present in `std::io::ErrorKind`.

Another possible (actually very ugly) solution is using `std::io::ErrorKind.Other` to mark special errors and create custom error message format, such that in `From` trait into `DenoError` we could parse the message and translate to our custom error types.

(`std::io::ErrorKind.InvalidInput` might be used to cover some of the other types of error)

### LINKED ISSUE #2406: lift "bad rid" panics in resources.rs into javascript exceptions (was: 'bad rid' panic when dialing localhost)
```typescript
// server.ts
import { serve } from "https://deno.land/std/http/server.ts";

async function main() {
  for await (let req of serve(":80")) {
    console.log(req.proto, req.method, req.url);
    req.respond({});
  }
}

main();
```

```typescript
// test.ts
async function main() {
  let enc = new TextEncoder();
  let conn = await Deno.dial("tcp", ":80");
  conn.write(enc.encode("GET / HTTP/1.0\n"));
  conn.close();
}

main();
```

Ran `server.ts`, then ran `test.ts` in another window:

```
❯ deno run --allow-net test.ts
[1/1] Compiling file:///Users/marktiedemann/dev/deno_test/test.ts
thread '<unnamed>' panicked at 'bad rid', ../../cli/resources.rs:237:15
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
thread 'main' panicked at 'internal error: entered unreachable code', ../../third_party/rust_crates/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.20/src/runtime/threadpool/mod.rs:296:26
thread 'main' panicked at 'unexpected state while aborting task: Complete', ../../third_party/rust_crates/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.14/src/task/mod.rs:216:21
stack backtrace:
   0:        0x10c034ab3 - <std::sys::unix::backtrace::tracing::imp::UnwindError as core::fmt::Display>::fmt::h91279d169ccb5b2c
   1:        0x10c02d6f2 - std::sys_common::alloc::realloc_fallback::h1ea3e7dd66f55875
   2:        0x10c031056 - std::panicking::take_hook::hf5878833b3146ef1
   3:        0x10c030d61 - std::panicking::take_hook::hf5878833b3146ef1
   4:        0x10c0317cf - std::panicking::rust_panic_with_hook::h547ea459e27be908
   5:        0x10c0312fc - std::panicking::begin_panic_fmt::hcacc0f82ca07e29f
   6:        0x10c031250 - std::panicking::begin_panic_fmt::hcacc0f82ca07e29f
   7:        0x10ce47c76 - <tokio_threadpool::task::Task::run::{{closure}}::Guard<'a> as core::ops::drop::Drop>::drop::h3e4ab556eba4c96c
   8:        0x10ce41e59 - tokio_threadpool::pool::state::<impl core::convert::From<tokio_threadpool::pool::state::Lifecycle> for usize>::from::h025a5dce3d6dcb6a
   9:        0x10ce499be - <tokio_threadpool::shutdown::ShutdownTrigger as core::ops::drop::Drop>::drop::hefa5d5ec07d4e8ed
  10:        0x10ce431db - <tokio_threadpool::worker::state::Lifecycle as core::fmt::Debug>::fmt::he88a1c5c815cc32d
  11:        0x10ce3d089 - tokio_threadpool::thread_pool::ThreadPool::shutdown_now::h6b270460ce9a5a1a
  12:        0x10ce1d8bc - tokio::runtime::current_thread::runtime::Runtime::run::hd4ea896f4ae076a4
  13:        0x10ce20160 - <tokio::runtime::threadpool::Runtime as core::ops::drop::Drop>::drop::h06f07afe0cfb18e8
  14:        0x10d0606fb - unicode_normalization::normalize::is_hangul_syllable::h3690a31bd91fba4a
  15:        0x10d135194 - unicode_normalization::normalize::is_hangul_syllable::h3690a31bd91fba4a
  16:        0x10d042b55 - unicode_normalization::normalize::is_hangul_syllable::h3690a31bd91fba4a
  17:        0x10c031167 - std::panicking::update_panic_count::hbf086650ecde3007
  18:        0x10c0414be - __rust_maybe_catch_panic
  19:        0x10c031c4d - std::rt::lang_start_internal::he82d111f45e8971a
  20:        0x10d1359f8 - main
thread panicked while panicking. aborting.
zsh: illegal hardware instruction  deno run --allow-net test.ts
```

When changing the addr to `"localhost:80"`, the panic is gone and a proper error is printed instead:

```
Uncaught ConnectionRefused: Connection refused (os error 61)
    at DenoError (js/errors.ts:22:5)
    at maybeError (js/errors.ts:33:12)
    at handleAsyncMsgFromRust (js/dispatch.ts:41:17)
    at handleAsyncMsgFromRust (shared_queue.js:157:9)
```

### PR DESCRIPTION
**Pull request by bartlomieju**
Closes #2249
Closes #2406

### CODE REVIEW

File: cli/resources.rs [hunk 1]
```diff
@@ -101,6 +101,13 @@ enum Repr {
   Worker(WorkerChannels),
 }
 
+fn not_found(rid: ResourceId) -> Error {
+  Error::new(
+    ErrorKind::NotFound,
+    format!("Resource with rid {:?} not found", rid),
+  )
+}
```
[the remark this answers is not in the document]
Comment (bartlomieju) [reply cli/resources.rs]: Thanks, looks like [`from_raw_os_error`](https://doc.rust-lang.org/std/io/struct.Error.html#method.from_raw_os_error) is the tool for the job, because there's no error kind like that in `std::io::ErrorKind`.

[the remark this answers is not in the document]
Comment (ry) [reply cli/resources.rs]: Use BadResource

https://github.com/denoland/deno/blob/ca000392857b4c79a3609ddbc20073222498998b/cli/msg.rs#L28

https://github.com/denoland/deno/blob/ca000392857b4c79a3609ddbc20073222498998b/cli/deno_error.rs#L49-L51

[the remark this answers is not in the document]
Comment (bartlomieju) [reply cli/resources.rs]: @ry that's not possible... We need this error to be of `std::io::Error` type because `AsyncWrite` trait needs that, see https://github.com/denoland/deno/issues/2249 for longer description

**Comment by bartlomieju** [comment]
@ry @piscisaureus should we discriminate situation when resource was not found and doesn't match required repr?

eg:
```rust
impl AsyncWrite for Resource {
  fn poll_write(&mut self, buf: &[u8]) -> Poll<usize, Error> {
    let mut table = RESOURCE_TABLE.lock().unwrap();
    
    // if resource not found it returns OS error 9 (EBADF)
    let repr = table.get_mut(&self.rid).ok_or_else(resource_not_found)?;

    match repr {
      Repr::FsFile(ref mut f) => f.poll_write(buf),
      Repr::Stdout(ref mut f) => f.poll_write(buf),
      Repr::Stderr(ref mut f) => f.poll_write(buf),
      Repr::TcpStream(ref mut f) => f.poll_write(buf),
      Repr::ChildStdin(ref mut f) => f.poll_write(buf),
      // custom error (ErrorKind === 19), maybe rename to bad_resource_kind?
      r => bad_resource();
    }
  }
}
```

File: tests/044_bad_resource.ts [hunk 2]
```diff
@@ -0,0 +1,7 @@
+async function main(): Promise<void> {
```
Comment (bartlomieju) [inline tests/044_bad_resource.ts]: Test that is failing on master:
```
async function main(): Promise<void> {
  const file = await Deno.open("Cargo.toml", "a");
  file.write(new Uint8Array([0, 1, 2]));
  file.close();
}

main();

```

Unfortunately minimal dispatch still swallows errors and it can't be used right now (because it'll throw generic write error instead of displaying actual error)

**Comment by bartlomieju** [comment]
After some thought I'm not sure that returning `Uncaught Other: Bad file descriptor (os error 9)` is a proper way to handle missing resources. Resources are not "file descriptors" per se, they are abstraction over file descriptors.

How about those:
- missing resource in resource table:
```rust
std::io::Error(
    std::io::ErrorKind::Other, 
    "Bad resource descriptor <rid>"
)
```
- mismatch of resource kind for operation (eg. trying to shutdown a file instead of TcpStream):
```rust
std::io::Error(
    std::io::ErrorKind::Other, 
    "Bad resource kind <rid> (<rid_repr>)"
)
```

File: cli/ops/files.rs [hunk 3]
```diff
@@ -129,17 +124,13 @@ pub fn op_seek(
...
-      let op = resources::seek(resource, args.offset, args.whence as u32)
-        .and_then(move |_| futures::future::ok(json!({})));
-      if args.promise_id.is_none() {
-        let buf = op.wait()?;
-        Ok(JsonOp::Sync(buf))
-      } else {
-        Ok(JsonOp::Async(Box::new(op)))
-      }
-    }
+  let resource = resources::lookup(args.rid as u32)?;
```
Comment (ry) [inline cli/ops/files.rs]: If it's a bad rid, you should get a BadResource error from `lookup()`

File: cli/ops/files.rs [hunk 4]
```diff
@@ -129,17 +124,13 @@ pub fn op_seek(
...
+  let op = resources::seek(resource, args.offset, args.whence as u32)
```
Comment (ry) [inline cli/ops/files.rs]: Therefore it's impossible to call resources::seek with a bad resource.

File: cli/resources.rs [hunk 5]
```diff
@@ -239,18 +249,18 @@ impl Read for Resource {
 impl AsyncRead for Resource {
   fn poll_read(&mut self, buf: &mut [u8]) -> Poll<usize, Error> {
     let mut table = RESOURCE_TABLE.lock().unwrap();
-    let maybe_repr = table.get_mut(&self.rid);
-    match maybe_repr {
-      None => panic!("bad rid"),
```
Comment (ry) [inline cli/resources.rs]: I think the panic is okay here. See above comments about `lookup()`.

File: cli/deno_error.rs [hunk 6]
```diff
@@ -46,10 +46,6 @@ impl fmt::Display for StaticError {
   }
 }
 
-pub fn bad_resource() -> ErrBox {
-  StaticError(ErrorKind::BadResource, "bad resource id").into()
-}
```
Comment (ry) [inline cli/deno_error.rs]: I don't agree this is wrong...

File: cli/ops/files.rs [hunk 7]
```diff
@@ -104,13 +103,9 @@ pub fn op_close(
...
-  match resources::lookup(args.rid as u32) {
-    None => Err(deno_error::bad_resource()),
-    Some(resource) => {
-      resource.close();
-      Ok(JsonOp::Sync(json!({})))
-    }
-  }
+  let resource = resources::lookup(args.rid as u32)?;
+  resource.close();
+  Ok(JsonOp::Sync(json!({})))
```
Comment (ry) [inline cli/ops/files.rs]: 👍 
This seems good.

File: cli/ops/files.rs (hunk 3 above)
Comment (bartlomieju) [reply cli/ops/files.rs]: Alright, but then again inside `poll_read` and `poll_write` if `rid` is not present in resource table we'd return different error type (`std::io::Error` because `AsyncRead/Write` requires it) than during lookup.

File: cli/resources.rs (hunk 5 above)
Comment (bartlomieju) [reply cli/resources.rs]: This panic is exactly the problem we're trying to fix. `poll_read` is called after lookup, but since it's a future it can be called after the resource is removed (see integration test I provided)

File: cli/resources.rs [hunk 8]
```diff
@@ -101,6 +100,17 @@ enum Repr {
   Worker(WorkerChannels),
 }
 
+fn bad_resource(rid: ResourceId) -> Error {
+  Error::new(ErrorKind::Other, format!("Bad resource descriptor {}", rid))
+}
```
Comment (ry) [inline cli/resources.rs]: Use ErrorKind::BadResource

File: tests/044_bad_resource.ts (hunk 2 above)
Comment (ry) [reply tests/044_bad_resource.ts]: Yeah, minimal_dispatch doesn't have error handling... I need to get to that.

File: cli/resources.rs (hunk 5 above)
Comment (ry) [reply cli/resources.rs]: Oh ok - sorry - I hadn't understood that. The problem is that we're implementing AsyncRead and that only returns std::io::Errors... I wonder if we can somehow to this without using AsyncRead, and return DenoError.

**Comment by bartlomieju** [comment]
@ry I implemented `DenoAsyncRead` and `DenoAsyncWrite`, changed the signature of `tokio_write::write` and added `tokio_read::read` as well as reverted back to `deno_error::bad_resources` - the only difference between them and regular tokio implementations is that it uses `ErrBox` instead of `std::io::Error`. 

PTAL and let me know what you think, it's not that much of the code and definitely gives better error handling. If you're good with that we can override traits for accept et al

File: cli/deno_error.rs [hunk 9]
```diff
@@ -46,10 +46,14 @@ impl fmt::Display for StaticError {
   }
 }
 
-pub fn bad_resource() -> ErrBox {
+pub fn bad_resource(_rid: u32) -> ErrBox {
```
Comment (bartlomieju) [inline cli/deno_error.rs]: It'd be cool if we could annotate the error message with actual `rid` but for now I'm getting errors:
```
error[E0716]: temporary value dropped while borrowed
  --> cli/deno_error.rs:54:40
   |
54 |   StaticError(ErrorKind::BadResource, &format!("bad resource kind {:?}", rid.clone())).into()
   |                                       -^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |                                       ||
   |                                       |creates a temporary which is freed while still in use
   |                                       requires that borrow lasts for `'static`
55 | }
   | - temporary value is freed at the end of this statement
```

This can be figured out in separate PR tho

File: cli/deno_error.rs [hunk 10]
```diff
@@ -50,6 +50,10 @@ pub fn bad_resource() -> ErrBox {
   StaticError(ErrorKind::BadResource, "bad resource id").into()
 }
 
+pub fn bad_resource_kind() -> ErrBox {
+  StaticError(ErrorKind::BadResource, "bad resource kind").into()
```
Comment (ry) [inline cli/deno_error.rs]: "bad resource kind" is not a very descriptive message - it took me a few minutes to figure out the difference from "bad resource id". 

I question the value of distinguishing between these two types of errors... What do you think about replacing this with the existing `bad_resource()` error?

Comment (bartlomieju) [reply cli/deno_error.rs]: Yeah it makes sense :+1: I'll replace them

File: cli/resources.rs [hunk 11]
```diff
@@ -236,22 +235,28 @@ impl Read for Resource {
   }
 }
 
-impl AsyncRead for Resource {
-  fn poll_read(&mut self, buf: &mut [u8]) -> Poll<usize, Error> {
+pub trait DenoAsyncRead {
```
Comment (ry) [inline cli/resources.rs]: Could you add a triple slash comment here describing the purpose of DenoAsyncRead (same for DenoAsyncWrite)

Something like this: /// DenoAsyncRead is the same as the AsyncRead trait but uses an ErrBox error instead of std::io:Error

File: cli/tokio_write.rs [hunk 12]
```diff
@@ -29,23 +28,25 @@ enum State<A, T> {
...
+  A: DenoAsyncWrite,
   T: AsRef<[u8]>,
 {
   Write {
     state: State::Pending { a, buf },
   }
 }
 
+/// This is almost the same implementation as in tokio, the only difference is
+/// that error type is `ErrBox` instead of `std::io::Error`.
```
Comment (ry) [inline cli/tokio_write.rs]: 👍

File: cli/deno_error.rs (hunk 9 above)
Comment (ry) [reply cli/deno_error.rs]: It's probably because `StaticError` requires a `&'static str`. I think there are other ways to construct an ErrBox which don't require a `&'static str` error message. But I agree that this can be done later.

**Comment by ry** [comment]
Just a few comments - otherwise looks good

**Comment by bartlomieju** [comment]
Waiting on #2896

**Comment by bartlomieju** [comment]
Rebased on top of `master`
