### PR TITLE
fix(websocket): ignore resource close error

### LINKED ISSUE #9879: ws: BadResource on socket.close()
Since deno version `1.8.0`, invoking `socket.close()` on the client side will cause a `BadResource` error:

> error: Uncaught (in promise) BadResource: Bad resource ID
    at handleError (deno:core/core.js:186:12)
    at jsonOpParseResult (deno:core/core.js:356:9)
    at opSync (deno:core/core.js:259:32)
    at jsonOpSync (deno:core/core.js:372:12)
    at Object.close (deno:core/core.js:383:12)
    at WebSocket.#eventLoop (deno:op_crates/websocket/01_websocket.js:353:18)

It should be easy to reproduce this error but let me know if you need more information please.

### LINKED ISSUE #9958: Deno test WebSocket completing cleanly, but reporting BadResource: Bad resource ID
I am a bit miffed by this error reported by the test runner (notice the async/ops resource sanitizer is not printing (I am the one doing the print). The test completes, reports passed, but a trace at the end.
Any hints, thoughts?
```
running 1 tests
test clean shutdown ...
{ "0": "stdin", "1": "stdout", "2": "stderr", "3": "webSocketStream" }
ok (11ms)

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out (11ms)

error: Uncaught (in promise) BadResource: Bad resource ID
    at handleError (deno:core/core.js:186:12)
    at jsonOpParseResult (deno:core/core.js:356:9)
    at opSync (deno:core/core.js:259:32)
    at jsonOpSync (deno:core/core.js:372:12)
    at Object.close (deno:core/core.js:383:12)
    at WebSocket.#eventLoop (deno:op_crates/websocket/01_websocket.js:353:18)

```

### PR DESCRIPTION
**Pull request by lucacasonato**
It is possible that the WebSocket is already closed when we try to
close it with `WebSocket#close` or in the `error` or `close` events.
Currently this leads to an uncatchable promise rejection. This changes
this so that closing an already closed WebSocket is a noop.

Closes #9879
Closes #9958

### CODE REVIEW

**Review by ry — COMMENTED** [review]
It would be useful to have a test. Will the WPT cover this?

**Comment by lucacasonato** [comment]
Possibly - this is an internal Deno error we are exposing to the user though. No web API should ever through a `Deno.errors` error.

File: op_crates/websocket/01_websocket.js [hunk 1]
```diff
@@ -125,7 +125,12 @@
               const event = new CloseEvent("close");
               event.target = this;
               this.dispatchEvent(event);
-              core.close(this.#rid);
+              try {
+                core.close(this.#rid);
+              } catch (err) {
+                // Ignore error if the socket has already been closed.
+                if (!(err instanceof Deno.errors.BadResource)) throw err;
+              }
```
Comment (bartlomieju) [inline op_crates/websocket/01_websocket.js:133]: Nitpick: make this bit a helper function?

**Review by bartlomieju — APPROVED** [review]

**Comment by bartlomieju** [comment]
This PR should probably be landed onto `1.8.3` branch?

**Comment by lucacasonato** [comment]
I'm going to pull the check into a helper function. Then yeah - let's cherry-pick it for 1.8.3

File: op_crates/websocket/01_websocket.js (hunk 1 above)
Comment (lucacasonato) [reply op_crates/websocket/01_websocket.js]: Done now

**Comment by aricart** [comment]
> It is possible that the WebSocket is already closed when we try to
> close it with `WebSocket#close` or in the `error` or `close` events.
> Currently this leads to an uncatchable promise rejection. This changes
> this so that closing an already closed WebSocket is a noop.

Making it a noop is a good idea, the websocket event gets called after `close()`, which can easily yield double closes.
