### PR TITLE
fix(std/http): properly return port 80 in _parseAddrFromStr

### LINKED ISSUE #6634: regression: serve listens on port 0 instead of port 80 if argument is string
Introduced in #5263

If the `addr` argument supplied to `serve()` is a string, it is passed into the `URL` constructor for parsing. If the port parsed from `addr` matches the default port for the protocol passed to the `URL` constructor (or if the port is omitted altogether), the `URL`'s port is the empty string, which isn't properly handled by `_parseAddrFromStr`. i.e:
```
_parseAddrFromStr('localhost:80');
_parseAddrFromStr('localhost:');
_parseAddrFromStr('localhost');
```
all return
```
{ hostname: "localhost", port: 0 }
```

The fix is simple: set `port` to `80` if `url.port` is the empty string, otherwise `Number(url.port)`

### PR DESCRIPTION
**Pull request by 3bert**
fixes #6634

### CODE REVIEW

File: std/http/server_test.ts [hunk 1]
```diff
@@ -655,7 +655,15 @@ Deno.test({
...
+    assertEquals(server.listener.addr, expected);
     server.close();
   },
 });
+
+Deno.test({
+  name: "server._parseAddrFromStr() port 80",
+  fn: (): void => {
+    const addr = _parseAddrFromStr(":80");
+    assertEquals(addr.port, 80);
```
Comment (ry) [inline std/http/server_test.ts:667]: This test case doesn't seem to cover the changes that were made... the changes seem to suggest it should default to port 80 if no port is provided.

Comment (3bert) [reply std/http/server_test.ts:667]: Well, the issue is that whether the default port for http (80) or no port at all is supplied to `_parseAddrFromStr`, after the host string is passed through the `URL` constructor, the port is set to the empty string. i.e.:
```
_parseAddrFromStr(':80');
_parseAddrFromStr(':');
```
both return
```
{ hostname: "", port: 0 }
```
Should I make the test cover both cases?

Comment (ry) [reply std/http/server_test.ts:667]: I see, it's okay as is.
