### PR TITLE
fix(publish): lazily parse sources

### LINKED ISSUE #22290: `deno publish` doesn't work import-mapped specifiers in private files
While attempting to publish `deno_std` to JSR. I noticed that private files that use import-map JSR specifiers cause `deno publish` to fail. E.g. once the script (`deno run -A ./_tools/convert_to_workspace.ts`) is run, and `deno publish` is run, we get the following error.
```
...
Caused by:
    Failed to publish @std/assert at 0.214.0: failed to build module graph: Relative import path "@std/fmt/colors" not prefixed with / or ./ or ../
```
When we go to the problematic file, `assert/_diff.ts`, and instead use a non-import-mapped specifier (`jsr:/@std/fmt@^0.214.0/colors`), `deno publish` is unblocked. This pattern is repeatable for all private files. I.e. those beginning with an underscore, such as `toml/_parser.ts`.

This is means much manual work is required before we can publish `deno_std` to JSR.

### PR DESCRIPTION
**Pull request by dsherret**
Closes #22290

### CODE REVIEW

File: test_util/src/servers/registry.rs [hunk 1]
```diff
@@ -59,6 +61,16 @@ async fn registry_server_handler(
...
 
+  // serve the registry package files
+  let mut file_path =
+    testdata_path().to_path_buf().join("jsr").join("registry");
+  file_path.push(&req.uri().path()[1..].replace("%2f", "/"));
+  if let Ok(body) = tokio::fs::read(&file_path).await {
+    return Ok(Response::new(UnsyncBoxBody::new(
+      http_body_util::Full::new(Bytes::from(body)),
+    )));
+  }
```
Comment (dsherret) [inline test_util/src/servers/registry.rs:72]: This confused for a few minutes, but we have ended up with two JSR test registries. I'll circle back with another PR that gets all the JSR tests to use this "test registry server".

File: cli/diagnostics.rs [hunk 2]
```diff
@@ -11,25 +11,26 @@ use deno_ast::SourcePos;
...
+
 pub trait SourceTextStore {
   fn get_source_text<'a>(
     &'a self,
     specifier: &ModuleSpecifier,
   ) -> Option<Cow<'a, SourceTextInfo>>;
 }
 
-pub struct SourceTextParsedSourceStore<'a>(pub &'a dyn ParsedSourceStore);
+pub struct SourceTextParsedSourceStore<'a>(pub LazyGraphSourceParser<'a>);
```
Comment (dsherret) [inline cli/diagnostics.rs:26]: Maybe fixes #22288, but I don't have a test for that yet.
