### PR TITLE
fix(dts): add `Uint8Array` base64/hex methods

### LINKED ISSUE #25051: add Uint8Array to/from base64 and hex
The tc39 [Uint8Array to/from base64 and hex](https://github.com/tc39/proposal-arraybuffer-base64) proposal is stage 3.

Support for this would significantly reduce boilerplate code.

Examples:
```js
let arr = new Uint8Array([72, 101, 108, 108, 111, 32, 87, 111, 114, 108, 100]);
console.log(arr.toBase64());
// 'SGVsbG8gV29ybGQ='
console.log(arr.toHex());
// '48656c6c6f20576f726c64'
```

```js
let string = 'SGVsbG8gV29ybGQ=';
console.log(Uint8Array.fromBase64(string));
// Uint8Array([72, 101, 108, 108, 111, 32, 87, 111, 114, 108, 100])

string = '48656c6c6f20576f726c64';
console.log(Uint8Array.fromHex(string));
// Uint8Array([72, 101, 108, 108, 111, 32, 87, 111, 114, 108, 100])
```

[Full spec](https://tc39.es/proposal-arraybuffer-base64/spec/).

### PR DESCRIPTION
**Pull request by 0f-0b**
These are enabled by default in V8 14.0.

Closes #25051.

### CODE REVIEW

File: cli/tsc/mod.rs [hunk 1]
```diff
@@ -290,11 +290,13 @@ pub static LAZILY_LOADED_STATIC_ASSETS: Lazy<
     maybe_compressed_lib!("lib.esnext.d.ts"),
     maybe_compressed_lib!("lib.esnext.decorators.d.ts"),
     maybe_compressed_lib!("lib.esnext.disposable.d.ts"),
+    maybe_compressed_lib!("lib.esnext.error.d.ts"),
     maybe_compressed_lib!("lib.esnext.float16.d.ts"),
     maybe_compressed_lib!("lib.esnext.full.d.ts"),
     maybe_compressed_lib!("lib.esnext.intl.d.ts"),
     maybe_compressed_lib!("lib.esnext.iterator.d.ts"),
     maybe_compressed_lib!("lib.esnext.promise.d.ts"),
+    maybe_compressed_lib!("lib.esnext.sharedmemory.d.ts"),
```
Comment (bartlomieju) [inline cli/tsc/mod.rs:299]: Where is this coming from?

Comment (0f-0b) [reply cli/tsc/mod.rs:299]: This file is from TS 5.9. It provides `Atomics.pause`, so I removed `Atomics.pause` from `lib.deno.unstable.d.ts` and added this file here.

**Comment by bartlomieju** [comment]
Thanks for the PR @0f-0b, I opened https://github.com/mdn/browser-compat-data/pull/27984 for completeness
