### PR TITLE
fix(add/install): default to "latest" tag for npm packages in `deno add npm:pkg`

### LINKED ISSUE #25813: `deno install` can't find package `npm:storybook-solidjs-vite`, unless version is specified
deno 2.0.0-rc.4+0cb00a6

https://www.npmjs.com/package/storybook-solidjs-vite

If a version isn't provided, it doesn't install `latest` like i'd expect it to, but says the module was not found.

```sh
➜ deno i npm:storybook-solidjs-vite
error: npm:storybook-solidjs-vite was not found.

➜ deno i npm:storybook-solidjs-vite@1.0.0-beta.2
Add npm:storybook-solidjs-vite@1.0.0-beta.2

➜ deno i npm:storybook-solidjs-vite@latest      
Add npm:storybook-solidjs-vite@1.0.0-beta.2
```

Screenshot 2024-09-23 at 01 26 00

### PR DESCRIPTION
**Pull request by nathanwhit**
Fixes #25813.

I initially tried doing this in `deno_semver`, where it's a cleaner change, but that caused breakage in deno in places where we don't expect a tag (see https://github.com/denoland/deno/issues/25857).

This does not fix wildcard requirements failing to choose pre-release versions. That's a little more involved and I'll do a separate PR.

### CODE REVIEW

File: cli/tools/registry/pm.rs [hunk 1]
```diff
@@ -654,6 +655,14 @@ struct AddPackageReq {
   value: AddPackageReqValue,
 }
 
+static LATEST_REQ: std::sync::LazyLock<VersionReq> =
+  std::sync::LazyLock::new(|| {
+    VersionReq::from_raw_text_and_inner(
+      "latest".into(),
+      deno_semver::RangeSetOrTag::Tag("latest".into()),
+    )
+  });
```
Comment (dsherret) [inline cli/tools/registry/pm.rs:664]: Do we need this? Maybe just constructing it each time is fine?

**Review by dsherret — APPROVED** [review]
LGTM!
