### PR TITLE
fix: top-level-await module execution

### LINKED ISSUE #7945: Awaiting never-resolved promise makes Deno hang & hot spin.
`deno run` this.

```js
// x.js
await new Promise(() => {});
```

It spins because there is nothing happening any more, and tokio can't block the event loop for us (there's nothing to poll).

Deno should either:
* exit
* throw an exception similar to `UncaughtException`. Maybe `AwaitNeverException` or something?

### PR DESCRIPTION
**Pull request by bartlomieju**
Currently failing, but making this test case pass will ensure our TLA implementation is correct.

Second try for https://github.com/denoland/deno/pull/7672
Reverted in https://github.com/denoland/deno/pull/7911 because of https://github.com/denoland/deno/issues/7909 (which has been addressed in this PR).
Fixes https://github.com/denoland/deno/issues/7907
Fixes https://github.com/denoland/deno/issues/7649
Fixes #7945

### CODE REVIEW

File: core/runtime.rs [hunk 1]
```diff
@@ -916,14 +1044,118 @@ impl JsRuntime {
...
-              Err(err) => self.dyn_import_error(dyn_import_id, err)?,
-            };
+            self.dyn_mod_evaluate(dyn_import_id, module_id)?;
+          }
+        }
+      }
+    }
+  }
+
+  fn evaluate_pending_modules(&mut self) -> Result<(), AnyError> {
```
Comment (ry) [inline core/runtime.rs:1054]: Can you add a triple slash comment here describing what this does? What does "pending" mean in this case?

Comment (bartlomieju) [reply core/runtime.rs]: Done, PTAL

File: core/runtime.rs [hunk 2]
```diff
@@ -83,6 +84,14 @@ pub struct JsRuntime {
   allocations: IsolateAllocations,
 }
 
+type DynImportModEvaluate =
+  (ModuleId, v8::Global<v8::Promise>, v8::Global<v8::Module>);
+type ModEvaluate = (
+  ModuleId,
+  v8::Global<v8::Promise>,
+  mpsc::Sender<Result<(), AnyError>>,
+);
```
Comment (ry) [inline core/runtime.rs:93]: Consider making these structs?

File: core/runtime.rs [hunk 3]
```diff
@@ -91,6 +100,8 @@ pub(crate) struct JsRuntimeState {
   pub(crate) js_recv_cb: Option<v8::Global<v8::Function>>,
   pub(crate) js_macrotask_cb: Option<v8::Global<v8::Function>>,
   pub(crate) pending_promise_exceptions: HashMap<i32, v8::Global<v8::Value>>,
+  pub(crate) pending_dyn_mod_evaluate: HashMap<i32, DynImportModEvaluate>,
+  pub(crate) pending_mod_evaluate: Option<ModEvaluate>,
```
Comment (ry) [inline core/runtime.rs:104]: I realize all of the elements in this struct are `pub(crate)`, but I think the elements you're adding are not accessed outside of `runtime.rs`. Consider making them private.

File: core/runtime.rs [hunk 4]
```diff
@@ -91,6 +100,8 @@ pub(crate) struct JsRuntimeState {
   pub(crate) js_recv_cb: Option<v8::Global<v8::Function>>,
   pub(crate) js_macrotask_cb: Option<v8::Global<v8::Function>>,
   pub(crate) pending_promise_exceptions: HashMap<i32, v8::Global<v8::Value>>,
+  pub(crate) pending_dyn_mod_evaluate: HashMap<i32, DynImportModEvaluate>,
```
Comment (ry) [inline core/runtime.rs:103]: Use `ModuleId` instead of i32?

File: core/runtime.rs [hunk 5]
```diff
@@ -486,13 +504,17 @@ impl JsRuntime {
...
+
+    let has_pending_dyn_imports = !{
+      state.preparing_dyn_imports.is_empty()
+        && state.pending_dyn_mod_evaluate.is_empty()
     };
 
-    if is_idle {
+    let has_pending_module = state.pending_mod_evaluate.is_some();
+
+    if is_idle && !has_pending_dyn_imports && !has_pending_module {
```
Comment (ry) [inline core/runtime.rs:517]: Maybe add ` !has_pending_dyn_imports && !has_pending_module` to the `is_idle` calculation? This bit of code is confusing and I don't understand why it's broken up into multiple statements.

Comment (bartlomieju) [reply core/runtime.rs:517]: Refactored and added comment

**Comment by bartlomieju** [comment]
I think I hit an edge case where trying https://github.com/denoland/deno/issues/7907 on this branch - there's most likely an interval being set up by one of submodules which halts execution of one of dynamic imports. I need to think a bit more how that should be handled.

**Review by ry — APPROVED** [review]
LGTM - I also confirmed it doesn't have a hot loop when idling

**Comment by bartlomieju** [comment]
So I've managed to find one more bug in implementation which is directly related to #7945 

```javascript
// a.mjs
import { foo } from "./timeout_loop.mjs";

export const collection = [];

const mod = await import("./b.mjs");

console.error("foo in main", foo);
console.error("mod", mod);
```

```javascript
// b.mjs
import { foo } from "./timeout_loop.mjs";
import { collection } from "./a.mjs";

console.log("collection in b", collection);
console.log("foo in b", foo);

export const a = "a";
```

```javascript
// timeout_loop.js
export const foo = "foo";

export function delay(ms) {
    return new Promise((res) =>
        setTimeout(() => { res(); }, ms)
    );
}

let i = 0;

async function timeoutLoop() {
    await delay(1000);
    console.log("timeout loop", i);
    i++;
    if (i > 5) {
        return;
    }
    timeoutLoop();
}

timeoutLoop();
```

```
$ target/debug/deno run --allow-read ./a.mjs
timeout loop 0
timeout loop 1
timeout loop 2
timeout loop 3
timeout loop 4
timeout loop 5
... infinite hot loop in deno_core::JsRuntime ...
```

Node exits with code 13
```
$ node ./a.mjs
timeout loop 0
timeout loop 1
timeout loop 2
timeout loop 3
timeout loop 4
timeout loop 5

$ echo $?
13
```

File: core/runtime.rs [hunk 6]
```diff
@@ -502,6 +538,25 @@ impl JsRuntime {
...
+      }
+    }
+
+    if has_pending_dyn_module_evaluation {
+      if has_pending_ops || has_pending_dyn_imports {
+        state.waker.wake();
+      } else {
+        return Poll::Ready(Err(generic_error("Dynamically imported module evaluation is still pending but there are no pending ops.")));
+      }
+    }
```
Comment (bartlomieju) [inline core/runtime.rs:558]: This bit fixes #7945

File: core/runtime.rs [hunk 7]
```diff
@@ -694,7 +749,100 @@ impl JsRuntime {
...
+      let status = module.get_status();
+
+      if let Some(value) = maybe_value {
+        assert!(
+          status == v8::ModuleStatus::Evaluated
+            || status == v8::ModuleStatus::Errored
+        );
+        let promise = v8::Local::<v8::Promise>::try_from(value)
+          .expect("Expected to get promise as module evaluation result");
+        let promise_id = promise.get_identity_hash();
```
Comment (bnoordhuis) [inline core/runtime.rs:810]: This might be problematic. The hash is only a 22 bits random number so, per the Birthday Paradox, there's a 50% chance of a collision after ~2400 turns.

It's a bit (hah!) worse on 32 bits architectures because the hash is one bit smaller, it reaches 50% after ~1700 turns.

**Review by bnoordhuis — APPROVED** [review]

File: core/runtime.rs [hunk 8]
```diff
@@ -474,25 +499,36 @@ impl JsRuntime {
...
+    self.evaluate_pending_module()?;
     {
-      let overflow_response = self.poll_pending_ops(cx);
-      self.async_op_response(overflow_response)?;
-      self.drain_macrotasks()?;
-      self.check_promise_exceptions()?;
+      let context = self.global_context();
+      let scope =
+        &mut v8::HandleScope::with_context(self.v8_isolate(), context);
+      scope.perform_microtask_checkpoint();
```
[the remark this answers is not in the document]
Comment (bartlomieju) [reply core/runtime.rs:513]: Thanks for pointing this out! Actually this checkpoint might not be needed - I added it during debugging and didn't check if it's required. I'll check that before landing.

File: core/runtime.rs (hunk 7 above)
Comment (bartlomieju) [reply core/runtime.rs:810]: Yeah, we already use this method for other purposes and have been for quite some time - what would you suggest to do instead?

Comment (piscisaureus) [reply core/runtime.rs:810]: We do it with modules too - and that should also change.

I'd assign the promise a number and stick it in a HashMap<u64, v8::Global<v8::Promise>>

Comment (bnoordhuis) [reply core/runtime.rs:810]: You probably need to somehow get back the id when you have a bare promise, I suppose?

It could be stored on the promise itself with a `v8::Private` symbol but that requires rusty_v8 to grow bindings for `v8::Object::SetPrivate()` and `v8::Object::GetPrivate()`. I can add those, I had that on my todo list anyway.

<hr>

However, that won't work for modules because they're instances of `v8::Data`, not `v8::Object`. What could work is storing them in a `HashSet` and implement `Eq` and `Hash` ourselves.

`hash()` could use `module.get_identity_hash()` (duplicates are okay) and `eq()` could compare the script id. There's currently no binding for that but it's trivial to add.

Same approach should work for promises, but using `strict_equals()` in `eq()`.

File: core/runtime.rs (hunk 8 above)
[the remark this answers is not in the document]
Comment (bartlomieju) [reply core/runtime.rs:513]: Right, so it's not needed. Removed.

File: core/runtime.rs (hunk 7 above)
Comment (bartlomieju) [reply core/runtime.rs:806]: Thanks for suggestions - I think we could land this PR as is and I'll update whole `deno_core` to this new mechanism in the follow up PR
