### PR TITLE
fix: don't error on version and help flag

### LINKED ISSUE #9048: deno upgrade --canary fails with thread main panicked
Trying to upgrade from v1.6.3 to latest canary:

```sh
Checking https://dl.deno.land/canary/e61e81eb57351782862aa50775ce4348f10b1856/deno-x86_64-unknown-linux-gnu.zip
Download has been found
Deno is upgrading to version e61e81eb57351782862aa50775ce4348f10b1856
Archive:  /tmp/.tmpFypHxG/deno.zip
  inflating: deno
error: 
thread 'main' panicked at 'assertion failed: output.status.success()', cli/tools/upgrade.rs:254:3
stack backtrace:
   0: std::panicking::begin_panic
   1: deno::tools::upgrade::upgrade_command::{{closure}}
   2: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   3: tokio::runtime::Runtime::block_on
   4: deno::main
```

### PR DESCRIPTION
**Pull request by lucacasonato**
Should fix #9048

### CODE REVIEW

File: cli/main.rs [hunk 1]
```diff
@@ -1261,8 +1261,26 @@ pub fn main() {
...
+      message,
+      info,
+    }) if kind == clap::ErrorKind::HelpDisplayed
+      || kind == clap::ErrorKind::VersionDisplayed =>
+    {
+      clap::Error {
+        info,
+        kind,
+        message,
+      }
```
Comment (bnoordhuis) [inline cli/main.rs:1277]: Are you doing this de- and restructuring to get around "value moved" errors? You can pattern match on `Err(ref err)` or `Err(err @ clap::Error { .. })`, depending on what you want to do (but probably the former.)

**Review by bnoordhuis — APPROVED** [review]

File: cli/main.rs (hunk 1 above)
Comment (lucacasonato) [reply cli/main.rs:1277]: Oh, I didn't know that syntax! I'll update it.
