### PR TITLE
fix(test): handle dispatched exceptions from test functions

### LINKED ISSUE #18852: `reportError()` panics in test
```ts
Deno.test("foo", () => {
  reportError(new Error("foo"));
  console.log(1);
});
```
```
running 1 test from ./temp.ts
foo ...
============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: linux x86_64
Version: 1.32.5
Args: ["deno", "test", "temp.ts"]

thread 'tokio-runtime-worker' panicked at 'called `Option::unwrap()` on a `None` value', cli/tools/test.rs:1004:47
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
The test harness doesn't handle dispatched exceptions / terminated execution properly.

### PR DESCRIPTION
**Pull request by nayeemrmn**
Fixes #18852.

### CODE REVIEW

**Review by bartlomieju — APPROVED** [review]
Thanks!

File: core/ops_builtin_v8.rs [hunk 1]
```diff
@@ -722,12 +722,12 @@ fn op_dispatch_exception(
...
-  if state.inspector().try_borrow().is_ok() {
-    scope.terminate_execution();
-  } else {
+  match state.inspector().try_borrow() {
+    Ok(inspector) if !inspector.has_blocking_sessions() => {
+      scope.terminate_execution();
+    }
     // If the inspector is borrowed at this time, assume an inspector is active.
+    _ => {}
   }
```
Comment (nayeemrmn) [inline core/ops_builtin_v8.rs:731]: Above commit https://github.com/denoland/deno/pull/18853/commits/aa63f1bd984327d73f32bc4ba1853e63009ccd3e makes this more sound by making it so that only blocking inspector sessions prevent termination here. And only `deno repl` is a blocking session. @bartlomieju Is this FIXME actually still relevant or no?
