### PR TITLE
fix: worker_message_before_close was flaky

### LINKED ISSUE #11992: worker_message_before_close is flaky
https://github.com/denoland/deno/pull/11990/checks?check_run_id=3579802538
```

failures:

---- integration::run::worker_message_before_close stdout ----
deno_exe path D:\a\deno\deno\target\release\deno.exe
deno_exe args run --quiet --reload --allow-read worker_message_before_close.js
deno_exe testdata path "D:\\a\\deno\\deno\\cli\\tests\\testdata"
output path D:\a\deno\deno\cli\tests\testdata\worker_message_before_close.js.out
OUTPUT
message received in worker 0
message received in worker 1
message received in worker 2
message received in worker 3
response from worker 0 received
response from worker 1 received
response from worker 3 received
response from worker 2 received

OUTPUT
EXPECTED
message received in worker 0
message received in worker 1
message received in worker 2
message received in worker 3
response from worker 0 received
response from worker 1 received
response from worker 2 received
response from worker 3 received

EXPECTED
Error: thread 'integration::run::worker_message_before_close' panicked at 'pattern match failed', test_util\src\lib.rs:1529:7
```

### PR DESCRIPTION
**Pull request by andreubotella**
Closes #11992.

### CODE REVIEW

File: cli/tests/testdata/worker_message_before_close.js [hunk 1]
```diff
@@ -5,11 +5,12 @@ for (let i = 0; i < 4; i++) {
   );
 
   worker.addEventListener("message", (message) => {
-    // Only print responses after all reception logs.
+    // Only print responses in order after all reception logs.
     setTimeout(() => {
       console.log("response from worker %d received", message.data);
-    }, 500);
+    }, 500 * (i + 1));
```
Comment (ry) [inline cli/tests/testdata/worker_message_before_close.js:11]: Rather than this setTimeout, wouldn't it suffice to just increase a counter and log something when all are received? The setTimeout seems unnecessary.

**Review by bartlomieju — APPROVED** [review]
LGTM
