### PR TITLE
Make writeSync, readSync, seekSync, openSync, isatty proper synchronous syscalls

### LINKED ISSUE #4717: Weird issue on 0.40.0 with Deno.readFileSync
I was trying `createRequire` and stepping into a weird issue.

This is only reproducible on deno 0.40.0, not 0.39.0.
I've only tested it on mac, 10.14 and 10.15, both with fresh installation of deno.
@lucacasonato also confirmed that this is reproducible on mac and linux with deno 0.40.0, not 0.39.0.

For demo purpose, I have created 2 branches for this,
`left_pad_fail` for failing and `left_pad_ok` for ok.

```sh
git clone https://github.com/shian15810/denosaur.git
cd denosaur

git checkout left_pad_fail
npm install
deno --allow-read --importmap import_map.json mod.ts # this is failing

git checkout left_pad_ok
deno --allow-read --importmap import_map.json mod.ts # this is ok
```

On branch `left_pad_fail`, deno is stuck at `require('left-pad')` indefinitely. I can only trace it down to this block of code:

https://github.com/denoland/deno/blob/0cf4ac91e6917b76c00d3d4b790e9fefc4dc5323/std/node/module.ts#L653-L658

<details>
  <summary>The debug log before it got stuck:</summary>

```
DEBUG JS - sendSync op_stat 17
⚠️️  Granted read access to "~/denosaur"
op_stat ~/denosaur false
DEBUG JS - sendSync op_stat 17
⚠️️  Granted read access to "~/denosaur/my_mod"
op_stat ~/denosaur/my_mod false
DEBUG JS - sendSync op_stat 17
⚠️️  Granted read access to "~/denosaur/my_mod.js"
op_stat ~/denosaur/my_mod.js false
DEBUG JS - sendSync op_read_link 23
⚠️️  Granted read access to "~/denosaur/my_mod.js"
op_read_link ~/denosaur/my_mod.js
DEBUG JS - sendSync op_open 8
⚠️️  Granted read access to "~/denosaur/package.json"
read rid=3
read rid=3
DEBUG JS - sendSync op_close 62
DEBUG JS - sendSync op_open 8
⚠️️  Granted read access to "~/denosaur/my_mod.js"
read rid=4
read rid=4
DEBUG JS - sendSync op_close 62
DEBUG JS - sendSync op_stat 17
⚠️️  Granted read access to "~/denosaur/node_modules"
op_stat ~/denosaur/node_modules false
DEBUG JS - sendSync op_open 8
⚠️️  Granted read access to "~/denosaur/node_modules/left-pad/package.json"
read rid=5
```
</details>

Adding some `console.log` to this block of code:

```ts
let json: string | undefined;
try {
  console.log('before');
  json = new TextDecoder().decode(
    Deno.readFileSync(path.toNamespacedPath(jsonPath))
  );
  console.log('after');
} catch {
  console.log('catch');
}
```

Only `before` is being printed before it got stuck.

<details>
  <summary>The debug log before it got stuck:</summary>

```
DEBUG JS - sendSync op_stat 17
⚠️️  Granted read access to "~/denosaur"
op_stat ~/denosaur false
DEBUG JS - sendSync op_stat 17
⚠️️  Granted read access to "~/denosaur/my_mod"
op_stat ~/denosaur/my_mod false
DEBUG JS - sendSync op_stat 17
⚠️️  Granted read access to "~/denosaur/my_mod.js"
op_stat ~/denosaur/my_mod.js false
DEBUG JS - sendSync op_read_link 23
⚠️️  Granted read access to "~/denosaur/my_mod.js"
op_read_link ~/denosaur/my_mod.js
before
DEBUG JS - sendSync op_open 8
⚠️️  Granted read access to "~/denosaur/package.json"
read rid=3
read rid=3
DEBUG JS - sendSync op_close 62
after
DEBUG JS - sendSync op_open 8
⚠️️  Granted read access to "~/denosaur/my_mod.js"
read rid=4
read rid=4
DEBUG JS - sendSync op_close 62
DEBUG JS - sendSync op_stat 17
⚠️️  Granted read access to "~/denosaur/node_modules"
op_stat ~/denosaur/node_modules false
before
DEBUG JS - sendSync op_open 8
⚠️️  Granted read access to "~/denosaur/node_modules/left-pad/package.json"
read rid=5
```
</details>

However, on branch `left_pad_ok`, everything is working just fine, with just 4 lines of code difference. You can see the diff here: https://github.com/shian15810/denosaur/compare/left_pad_fail...left_pad_ok

Commenting out these 4 totally unrelated lines, deno didn't get stuck anymore.
It seems like these 4 lines are making `Deno.readFileSync` to fail, but it doesn't make any sense.
If it really did fail, shouldn't it should be handled by the `catch` block?

Is this a bug?

### PR DESCRIPTION
**Pull request by ry**
Fixes #4717 (need to verify / add test)

### CODE REVIEW

File: cli/op_error.rs [hunk 1]
```diff
@@ -103,6 +103,13 @@ impl OpError {
   pub fn invalid_utf8() -> OpError {
     Self::new(ErrorKind::InvalidData, "invalid utf8".to_string())
   }
+
+  pub fn resource_unavailable() -> OpError {
+    Self::new(
+      ErrorKind::InvalidData,
+      "resource is unavailable because it is in by a promise".to_string(),
```
Comment (lucacasonato) [inline cli/op_error.rs:110]:
```suggestion
      "resource is unavailable because it is in use by a promise".to_string(),
```

File: cli/ops/io.rs [hunk 2]
```diff
@@ -27,12 +27,14 @@ use std::os::windows::io::FromRawHandle;
...
-  /// for process. In turn when resource table is dropped storing reference to that handle,
-  /// the handle itself won't be closed (so Deno.core.print) will still work.
+  /// Due to portability issues on Windows handle to stdout is created from raw
+  /// file descriptor.  The caveat of that approach is fact that when this
+  /// handle is dropped underlying file descriptor is closed - that is highly
+  /// not desirable in case of stdout.  That's why we store this global handle
+  /// that is then cloned when obtaining stdio for process. In turn when
+  /// resource table is dropped storing reference to that handle, the handle
+  /// itself won't be closed (so Deno.core.print) will still work.
+  // TODO(ry) It should be possible to close stdout.
```
Comment (bartlomieju) [inline cli/ops/io.rs:37]: Poor phrasing on my part - stdout can be closed using `Deno.close(2)` - what I meant is that dropping a clone of handle won't close stdout.

File: cli/op_error.rs [hunk 3]
```diff
@@ -103,6 +103,19 @@ impl OpError {
   pub fn invalid_utf8() -> OpError {
     Self::new(ErrorKind::InvalidData, "invalid utf8".to_string())
   }
+
+  // TODO(ry) Should this have its own ErrorKind code?
```
Comment (bartlomieju) [inline cli/op_error.rs:107]: Yes, `InvalidData` doesn't make any sense here

File: cli/op_error.rs [hunk 4]
```diff
@@ -103,6 +103,19 @@ impl OpError {
...
+  pub fn resource_unavailable() -> OpError {
+    Self::new(
+      ErrorKind::InvalidData,
+      "resource is unavailable because it is in use by a promise".to_string(),
+    )
+  }
+
+  // TODO(ry) Should this have its own ErrorKind code?
```
Comment (bartlomieju) [inline cli/op_error.rs:115]: type error SGTM

File: cli/ops/io.rs [hunk 5]
```diff
@@ -182,7 +192,8 @@ impl DenoAsyncRead for StreamResource {
   ) -> Poll<Result<usize, OpError>> {
     use StreamResource::*;
     let f: &mut dyn UnpinAsyncRead = match self {
-      FsFile(f, _) => f,
+      FsFile(Some((f, _))) => f,
+      FsFile(None) => todo!(), // not ready
```
Comment (bartlomieju) [inline cli/ops/io.rs:196]: return `resource_unavailable`?

File: core/ops.rs [hunk 6]
```diff
@@ -17,6 +17,9 @@ pub(crate) type PendingOpFuture =
 
 pub type OpResult<E> = Result<Op<E>, E>;
 
+// TODO(ry) Op::Async should be Op::Async(Pin<Box<dyn Future<Output = Buf>>>)
+// The error should be encoded in the Buf. Notice how Sync ops do not return a
+// result. The Sync and Async should be symmetrical!
```
Comment (bartlomieju) [inline core/ops.rs:22]: How errors could be returned from futures in that case?

File: cli/ops/io.rs (hunk 5 above)
Comment (ry) [reply cli/ops/io.rs:196]: yep

File: core/ops.rs (hunk 6 above)
Comment (ry) [reply core/ops.rs:22]: they're encoded in the buffer

File: cli/ops/io.rs (hunk 2 above)
Comment (ry) [reply cli/ops/io.rs:37]: I don't think this static ref to stdout (nor stderr) is necessary, but I don't want to try to remove it in this PR.

File: cli/op_error.rs [hunk 7]
```diff
@@ -103,6 +104,15 @@ impl OpError {
   pub fn invalid_utf8() -> OpError {
     Self::new(ErrorKind::InvalidData, "invalid utf8".to_string())
   }
+
+  pub fn resource_unavailable() -> OpError {
+    // TODO(ry) Is InvalidData the right error code here? BadResource? Should we
```
Comment (piscisaureus) [inline cli/op_error.rs:109]: Comment is now irrelevant.

File: cli/ops/fs.rs [hunk 8]
```diff
@@ -75,22 +76,20 @@ fn op_open(
   let path = resolve_from_cwd(Path::new(&args.path))?;
   let state_ = state.clone();
 
-  let mut open_options = if let Some(mode) = args.mode {
-    #[allow(unused_mut)]
-    let mut std_options = std::fs::OpenOptions::new();
+  #[allow(unused_mut)]
```
Comment (piscisaureus) [inline cli/ops/fs.rs:79]: why?

Comment (ry) [reply cli/ops/fs.rs]: fixed

File: cli/ops/io.rs [hunk 9]
```diff
@@ -304,41 +335,116 @@ impl DenoAsyncWrite for StreamResource {
...
+      .boxed_local(),
+    )
+  }
+}
 
-    Ok(nwritten as i32)
+/// Helper function for doing blocking fs ops on the main thread.
+///
+/// For many types of resources, it does not make sense to do blocking
+/// operations of the main thread - and we should not support it - such as for
```
Comment (piscisaureus) [inline cli/ops/io.rs]: s/of/off/
