### PR TITLE
fix(core): fix top-level-await error handling

### LINKED ISSUE #4445: catch of error from dynamic import does not halt propagation
I am observing that an error thrown by a dynamic import always results in an "uncaught error".  Here is an example:

```ts
// a.ts
try {
  await import('./b.ts')
} catch {
  console.log('catch')
}
```

```ts
// b.ts
throw Error()
```

Expected Output:
```
catch
```

Actual Output:
```
catch
error: Uncaught Error
    at file:///b.ts:1:7
```

### LINKED ISSUE #4908: Dynamic imports are broken
Integration test `error_014_catch_dynamic_import_error` appears to be broken.

It expects that Deno finishes with exit code 1 and following output (from stdout):
```
Caught direct dynamic import error.
TypeError: relative import path "does not exist" not prefixed with / or ./ or ../ Imported from "[WILDCARD]/error_014_catch_dynamic_import_error.js"

Caught indirect direct dynamic import error.
TypeError: relative import path "does not exist either" not prefixed with / or ./ or ../ Imported from "[WILDCARD]/indirect_import_error.js"

Caught error thrown by dynamically imported module.
Error: An error
    at file:///[WILDCARD]tests/subdir/throws.js:5:7
Caught error thrown indirectly by dynamically imported module.
Error: An error
    at file:///[WILDCARD]tests/subdir/throws.js:5:7
```

Actual output (including **stderr**):
```
Caught direct dynamic import error.
TypeError: relative import path "does not exist" not prefixed with / or ./ or ../ Imported from "file:///Users/biwanczuk/dev/deno/cli/tests/error_014_catch_dynamic_import_error.js"

Caught indirect direct dynamic import error.
TypeError: relative import path "does not exist either" not prefixed with / or ./ or ../ Imported from "file:///Users/biwanczuk/dev/deno/cli/tests/subdir/indirect_import_error.js"

Caught error thrown by dynamically imported module.
Error: An error
    at file:///Users/biwanczuk/dev/deno/cli/tests/subdir/throws.js:5:7
Caught error thrown indirectly by dynamically imported module.
Error: An error
    at file:///Users/biwanczuk/dev/deno/cli/tests/subdir/throws.js:5:7
error: Uncaught Error: An error
    at file:///Users/biwanczuk/dev/deno/cli/tests/subdir/throws.js:5:7
```

Notice last two lines with `error: Uncaught Error` - I think that's wrong and it shouldn't be thrown (and return 0 exit code).

Run the same file in Chrome:
```
Caught direct dynamic import error.
TypeError: Failed to resolve module specifier 'does not exist'
    at error_014_catch_dynamic_import_error.js:3
    at error_014_catch_dynamic_import_error.js:31
Caught indirect direct dynamic import error.
TypeError: Failed to resolve module specifier "does not exist either". Relative references must start with either "/", "./", or "../".
Caught error thrown by dynamically imported module.
Error: An error
    at throws.js:5
Caught error thrown indirectly by dynamically imported module.
Error: An error
    at throws.js:5
```

### PR DESCRIPTION
**Pull request by bartlomieju**
Fixes #4908
Fixed #4445

### CODE REVIEW

File: core/es_isolate.rs [hunk 1]
```diff
@@ -233,16 +234,40 @@ impl EsIsolate {
...
       // Update status after evaluating.
       status = module.get_status();
-      if ok {
+
+      if let Some(value) = maybe_value {
         assert!(
           status == v8::ModuleStatus::Evaluated
             || status == v8::ModuleStatus::Errored
         );
+        let obj = value.to_object(scope).unwrap();
```
Comment (piscisaureus) [inline core/es_isolate.rs:261]: Why is this `to_object()` call necessary? 
I think you could just do `let promise = v8::Local::<v8::Promise>::try_from(value).expect(...)`.
