### PR TITLE
fix(net): handle  panic on Windows for Unix socket usage in Deno.serve()

### LINKED ISSUE #21967: "Deno.serve()" panics on Windows when using trying to use Unix socket
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: windows x86_64
Version: 1.39.4
Args: ["deno", "run", "-A", "test.ts"]

thread 'main' panicked at ext\net\lib.rs:135:1:
Unsupported on non-unix platforms
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

the i used=>```
const ac = new AbortController();

const server = Deno.serve({
  path: "path/to/socket",
  handler: (_req) => new Response("Hello, world"),
  signal: ac.signal,
  onListen({ path }) {
    console.log(`Server started at ${path}`);
  },
});
server.finished.then(() => console.log("Server closed"));

console.log("Closing server...");
ac.abort();
```

### PR DESCRIPTION
**Pull request by yazan-abdalrahman**
This PR addresses the issue where Deno.serve() panics on Windows when trying to use a Unix socket.
Fix #21967

### CODE REVIEW

**Comment by yazan-abdalrahman** [comment]
@lucacasonato @bartlomieju,
, could you pls review it?

File: tests/specs/run/non_unix_operating/test.ts [hunk 1]
```diff
@@ -0,0 +1,16 @@
...
+
+const server = Deno.serve({
+  path: "path/to/socket",
+  handler: (_req) => new Response("Hello, world"),
+  signal: ac.signal,
+  onListen({ _path }) {
+    console.log("Server started at ${path}");
+  },
+});
+server.finished.then(() => console.log("Server closed"));
```
Comment (bartlomieju) [inline tests/specs/run/non_unix_operating/test.ts:13]: I think you should be able to add it to `tests/unit/serve_test.ts`, no need to make it into a spec test.

Remember to add `ignore: Deno.build.os !== "windows"` so that it's only run on Windows.

Comment (yazan-abdalrahman) [reply tests/specs/run/non_unix_operating/test.ts]: ok done

File: tests/unit/serve_test.ts [hunk 2]
```diff
@@ -4034,3 +4034,30 @@ Deno.test(
...
+    console.log("Closing server...");
+    ac.abort();
+  } catch (error) {
+    assert(error instanceof Error);
+    assert(
+      error.message.includes(
+        'Operation \`"op_net_listen_unix"\` not supported on non-unix platforms.',
+      ),
+    );
+  }
```
Comment (bartlomieju) [inline tests/unit/serve_test.ts:4062]: Almost correct - you should use `await assertRejects(...)` helper here. Otherwise if the error is not thrown the test still passes.

Comment (yazan-abdalrahman) [reply tests/unit/serve_test.ts]: ok done

**Review by bartlomieju — APPROVED** [review]
LGTM, thanks
