### PR TITLE
fix(config): regression - should not discover npm workspace for nested deno.json not in workspace

### LINKED ISSUE #24554: Regression: Should not discover npm workspace for nested deno.json not part of npm workspace
Deno should not be discovering an npm workspace for a nested deno.json when the nested deno.json is not explicitly part of the workspace (does not have a package.json beside it).

Previously we stopped at the deno.json in this case. This was an oversight when I rewrote the config discovery code.

If someone has multiple deno folders like this, then the workspace only knows about the folder being executed. This leads to churn in the lockfile where it switches between the members (the lockfile keeps track of members).

https://github.com/user-attachments/assets/58df6293-0e82-48ff-b7a6-77baf2d1583b

Version: Deno 1.45.0, 145.1

### PR DESCRIPTION
**Pull request by dsherret**
Closes #24554

### CODE REVIEW

File: cli/args/lockfile.rs [hunk 1]
```diff
@@ -109,23 +107,9 @@ impl CliLockfile {
...
-        }
-        None => match maybe_package_json {
-          Some(package_json) => {
-            package_json.path.parent().unwrap().join("deno.lock")
-          }
-          None => return Ok(None),
-        },
+      None => match workspace.resolve_lockfile_path()? {
+        Some(path) => path,
+        None => return Ok(None),
```
Comment (dsherret) [inline cli/args/lockfile.rs:112]: By the way, @nathanwhit, we should update https://github.com/denoland/deno_config/pull/84/files to get the frozen flag at the same time as resolving the lockfile path from the workspace.

**Review by bartlomieju — APPROVED** [review]
