### PR TITLE
fix(ext/node): isolate parentPort from globalThis in worker_threads

### LINKED ISSUE #17171: npm-compat: z3-solver
```ts
import { init } from "npm:z3-solver";
const { Context } = await init();
const { Solver, Int, And } = new Context("main");

const x = Int.const("x");

const solver = new Solver();
solver.add(And(x.ge(0), x.le(9)));
console.log(await solver.check()); // line that fails
```
error:
```
error: Uncaught RangeError: Maximum call stack size exceeded
    this._events = Object.create(null);
                          ^
    at Function.create (<anonymous>)
    at _Worker.EventEmitter.init (https://deno.land/std@0.170.0/node/_events.mjs:176:27)
    at new EventEmitter (https://deno.land/std@0.170.0/node/_events.mjs:56:21)
    at new _Worker (https://deno.land/std@0.170.0/node/worker_threads.ts:49:5)
    at new _Worker (https://deno.land/std@0.170.0/node/worker_threads.ts:55:36)
    at new _Worker (https://deno.land/std@0.170.0/node/worker_threads.ts:55:36)
    at new _Worker (https://deno.land/std@0.170.0/node/worker_threads.ts:55:36)
    at new _Worker (https://deno.land/std@0.170.0/node/worker_threads.ts:55:36)
    at new _Worker (https://deno.land/std@0.170.0/node/worker_threads.ts:55:36)
    at new _Worker (https://deno.land/std@0.170.0/node/worker_threads.ts:55:36)
```

Also there seem to be a lint issue ? 
image

The node packagae [has z3-solver/browser](https://www.npmjs.com/package/z3-solver) recomends z3-solver/browser for browsers, but I don't know how to use this with deno becasue using
```ts
import { init } from "npm:z3-solver/browser";
```
errors
```
error: Unable to load /home/mrcool/.cache/deno/npm/registry.npmjs.org/z3-solver/4.11.2/browser imported from file:///home/mrcool/dev/deno/lab/qqq.ts

Caused by:
```

### LINKED ISSUE #26739: Deno issue with fflate workers
Version: Deno 2.0.4.

Hi!

Here is the copy of the bug report I sent on fflate issues tracker (https://github.com/101arrowz/fflate/issues/226). 
The maintainer is actually thinking the error I am facing is bound to deno runtime.

Have you any idea on how to solve this?

P.S. Actually it worked on my recent test with 151KB but not working with 1mb. (It doesn't change anything to the issue, since it's bound to the algorithm fflate uses to decide either it should use a worker or not)

---

Hi!

I am trying to use the async version of `zip` function, using `deno` runtime.
Unfortunately, my code returns an error when trying to upload a file higher than 150kb (but works perfectly fine when using files lower in size).

Here are the test files:
[fakefile_150KB.txt](https://github.com/user-attachments/files/17611371/fakefile_150KB.txt)
[fakefile_151KB.txt](https://github.com/user-attachments/files/17611375/fakefile_151KB.txt)

Have you any clue on how to solve this issue?

Thanks.

**How to reproduce**
The code used:
```typescript
import * as fs from "node:fs";
import mime from "mime";
import * as fflate from "fflate";

const filePath = "./bench/fakefile_151KB.txt";
const file = new File([fs.readFileSync(filePath)], filePath, {
  type: mime.getType(filePath) as string,
});
const fileBytes = await file.bytes();

fflate.zip({
  [file.name]: fileBytes,
}, (err, _data) => {
  if (err) console.error(err);
});
```

**The problem**
```console
error: Uncaught (in worker "[worker eval]") SyntaxError: Unexpected end of input
Warning Couldn't format source line: Column 149 is out of bounds (source may have changed at runtime)
    at <anonymous> (data:text/javascript,;u8=Uint8Array;u16=U......u16 "map": index -> :1:149)
[Object: null prototype] {
  message: "Uncaught SyntaxError: Unexpected end of input",
  fileName: 'data:text/javascript,;u8=Uint8Array;u16=Uint16Array;i32=Int32Array;hMap=function (cd, mb, r) {    var s = cd.length;    // index    var i = 0;    // u16 "map": index -> #%20of%20codes%20with%20bit%20length%20=%20index%20%20%20%20var%20l%20=%20new%20u16(mb);%20%20%20%20//%20length%20of%20cd%20must%20be%20288%20(total%20#%20of%20codes)%20%20%20%20for%20(;%20i%20%3C%20s;%20++i)%20{%20%20%20%20%20%20%20%20if%20(cd[i])%20%20%20%20%20%20%20%20%20%20%20%20++l[cd[i]%20-%201];%20%20%20%20}%20%20%20%20//%20u16%20%22map%22:%20index%20-%3E%20minimum%20code%20for%20bit%20length%20=%20index%20%20%20%20var%20le%20=%20new%20u16(mb);%20%20%20%20for%20(i%20=%201;%20i%20%3C%20mb;%20++i)%20{%20%20%20%20%20%20%20%20le[i]%20=%20(le[i%20-%201]%20+%20l[i%20-%201])%20%3C%3C%201;%20%20%20%20}%20%20%20%20var%20co;%20%20%20%20if%20(r)%20{%20%20%20%20%20%20%20%20//%20u16%20%22map%22:%20index%20-%3E%20number%20of%20actual%20bits,%20symbol%20for%20code%20%20%20%20%20%20%20%20co%20=%20new%20u16(1%20%3C%3C%20mb);%20%20%20%20%20%20%20%20//%20bits%20to%20remove%20for%20reverser%20%20%20%20%20%20%20%20var%20rvb%20=%2015%20-%20mb;%20%20%20%20%20%20%20%20for%20(i%20=%200;%20i%20%3C%20s;%20++i)%20{%20%20%20%20%20%20%20%20%20%20%20%20//%20ignore%200%20lengths%20%20%20%20%20%20%20%20%20%20%20%20if%20(cd[i])%20{%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20//%20num%20encoding%20both%20symbol%20and%20bits%20read%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20var%20sv%20=%20(i%20%3C%3C%204)%20|%20cd[i];%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20//%20free%20bits%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20var%20r_1%20=%20mb%20-%20cd[i];%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20//%20start%20value%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20var%20v%20=%20le[cd[i]%20-%201]++%20%3C%3C%20r_1;%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20//%20m%20is%20end%20value%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20for%20(var%20m%20=%20v%20|%20((1%20%3C%3C%20r_1)%20-%201);%20v%20%3C=%20m;%20++v)%20{%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20//%20every%2016%20bit%20value%20starting%20with%20the%20code%20yields%20the%20same%20result%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20co[rev[v]%20%3E%3E%20rvb]%20=%20sv;%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20}%20%20%20%20%20%20%20%20%20%20%20%20}%20%20%20%20%20%20%20%20}%20%20%20%20}%20%20%20%20else%20{%20%20%20%20%20%20%20%20co%20=%20new%20u16(s);%20%20%20%20%20%20%20%20for%20(i%20=%200;%20i%20%3C%20s;%20++i)%20{%20%20%20%20%20%20%20%20%20%20%20%20if%20(cd[i])%20{%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20co[i]%20=%20rev[le[cd[i]%20-%201]++]%20%3E%3E%20(15%20-%20cd[i]);%20%20%20%20%20%20%20%20%20%20%20%20}%20%20%20%20%20%20%20%20}%20%20%20%20}%20%20%20%20return%20co;};wbits=function%20(d,%20p,%20v)%20{%20%20%20%20v%20%3C%3C=%20p%20&%207;%20%20%20%20var%20o%20=%20(p%20/%208)%20|%200;%20%20%20%20d[o]%20|=%20v;%20%20%20%20d[o%20+%201]%20|=%20v%20%3E%3E%208;};wbits16=function%20(d,%20p,%20v)%20{%20%20%20%20v%20%3C%3C=%20p%20&%207;%20%20%20%20var%20o%20=%20(p%20/%208)%20|%200;%20%20%20%20d[o]%20|=%20v;%20%20%20%20d[o%20+%201]%20|=%20v%20%3E%3E%208;%20%20%20%20d[o%20+%202]%20|=%20v%20%3E%3E%2016;};hTree=function%20(d,%20mb)%20{%20%20%20%20//%20Need%20extra%20info%20to%20make%20a%20tree%20%20%20%20var%20t%20=%20[];%20%20%20%20for%20(var%20i%20=%200;%20i%20%3C%20d.length;%20++i)%20{%20%20%20%20%20%20%20%20if%20(d[i])%20%20%20%20%20%20%20%20%20%20%20%20t.push({%20s:%20i,%20f:%20d[i]%20});%20%20%20%20}%20%20%20%20var%20s%20=%20t.length;%20%20%20%20var%20t2%20=%20t.slice();%20%20%20%20if%20(!s)%20%20%20%20%20%20%20%20return%20{%20t:%20et,%20l:%200%20};%20%20%20%20if%20(s%20==%201)%20{%20%20%20%20%20%20%20%20var%20v%20=%20new%20u8(t[0].s%20+%201);%20%20%20%20%20%20%20%20v[t[0].s]%20=%201;%20%20%20%20%20%20%20%20return%20{%20t:%20v,%20l:%201%20};%20%20%20%20}%20%20%20%20t.sort(function%20(a,%20b)%20{%20return%20a.f%20-%20b.f;%20});%20%20%20%20//%20after%20i2%20reaches%20last%20ind,%20will%20be%20stopped%20%20%20%20//%20freq%20must%20be%20greater%20than%20largest%20possible%20number%20of%20symbols%20%20%20%20t.push({%20s:%20-1,%20f:%2025001%20});%20%20%20%20var%20l%20=%20t[0],%20r%20=%20t[1],%20i0%20=%200,%20i1%20=%201,%20i2%20=%202;%20%20%20%20t[0]%20=%20{%20s:%20-1,%20f:%20l.f%20+%20r.f,%20l:%20l,%20r:%20r%20};%20%20%20%20//%20efficient%20algorithm%20from%20UZIP.js%20%20%20%20//%20i0%20is%20lookbehind,%20i2%20is%20lookahead%20-%20after%20processing%20two%20low-freq%20%20%20%20//%20symbols%20that%20combined%20have%20high%20freq,%20will%20start%20processing%20i2%20(high-freq,%20%20%20%20//%20non-composite)%20symbols%20instead%20%20%20%20//%20see%20https://reddit.com/r/photopea/comments/ikekht/uzipjs_questions/%20%20%20%20while%20(i1%20!=%20s%20-%201)%20{%20%20%20%20%20%20%20%20l%20=%20t[t[i0].f%20%3C%20t[i2].f%20?%20i0++%20:%20i2++];%20%20%20%20%20%20%20%20r%20=%20t[i0%20!=%20i1%20&&%20t[i0].f%20%3C%20t[i2].f%20?%20i0++%20:%20i2++];%20%20%20%20%20%20%20%20t[i1++]%20=%20{%20s:%20-1,%20f:%20l.f%20+%20r.f,%20l:%20l,%20r:%20r%20};%20%20%20%20}%20%20%20%20var%20maxSym%20=%20t2[0].s;%20%20%20%20for%20(var%20i%20=%201;%20i%20%3C%20s;%20++i)%20{%20%20%20%20%20%20%20%20if%20(t2[i].s%20%3E%20maxSym)%20%20%20%20%20%20%20%20%20%20%20%20maxSym%20=%20t2[i].s;%20%20%20%20}%20%20%20%20//%20code%20lengths%20%20%20%20var%20tr%20=%20new%20u16(maxSym%20+%201);%20%20%20%20//%20max%20bits%20in%20tree%20%20%20%20var%20mbt%20=%20ln(t[i1%20-%201],%20tr,%200);%20%20%20%20if%20(mbt%20%3E%20mb)%20{%20%20%20%20%20%20%20%20//%20more%20algorithms%20from%20UZIP.js%20%20%20%20%20%20%20%20//%20TODO:%20find%20out%20how%20this%20code%20works%20(debt)%20%20%20%20%20%20%20%20//%20%20ind%20%20%20%20debt%20%20%20%20%20%20%20%20var%20i%20=%200,%20dt%20=%200;%20%20%20%20%20%20%20%20//%20%20%20%20left%20%20%20%20%20%20%20%20%20%20%20%20cost%20%20%20%20%20%20%20%20var%20lft%20=%20mbt%20-%20mb,%20cst%20=%201%20%3C%3C%20lft;%20%20%20%20%20%20%20%20t2.sort(function%20(a,%20b)%20{%20return%20tr[b.s]%20-%20tr[a.s]%20||%20a.f%20-%20b.f;%20});%20%20%20%20%20%20%20%20for%20(;%20i%20%3C%20s;%20++i)%20{%20%20%20%20%20%20%20%20%20%20%20%20var%20i2_1%20=%20t2[i].s;%20%20%20%20%20%20%20%20%20%20%20%20if%20(tr[i2_1]%20%3E%20mb)%20{%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20dt%20+=%20cst%20-%20(1%20%3C%3C%20(mbt%20-%20tr[i2_1]));%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20tr[i2_1]%20=%20mb;%20%20%20%20%20%20%20%20%20%20%20%20}%20%20%20%20%20%20%20%20%20%20%20%20else%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20break;%20%20%20%20%20%20%20%20}%20%20%20%20%20%20%20%20dt%20%3E%3E=%20lft;%20%20%20%20%20%20%20%20while%20(dt%20%3E%200)%20{%20%20%20%20%20%20%20%20%20%20%20%20var%20i2_2%20=%20t2[i].s;%20%20%20%20%20%20%20%20%20%20%20%20if%20(tr[i2_2]%20%3C%20mb)%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20dt%20-=%201%20%3C%3C%20(mb%20-%20tr[i2_2]++%20-%201);%20%20%20%20%20%20%20%20%20%20%20%20else%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20++i;%20%20%20%20%20%20%20%20}%20%20%20%20%20%20%20%20for%20(;%20i%20%3E=%200%20&&%20dt;%20--i)%20{%20%20%20%20%20%20%20%20%20%20%20%20var%20i2_3%20=%20t2[i].s;%20%20%20%20%20%20%20%20%20%20%20%20if%20(tr[i2_3]%20==%20mb)%20{%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20--tr[i2_3];%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20++dt;%20%20%20%20%20%20%20%20%20%20%20%20}%20%20%20%20%20%20%20%20}%20%20%20%20%20%20%20%20mbt%20=%20mb;%20%20%20%20}%20%20%20%20return%20{%20t:%20new%20u8(tr),%20l:%20mbt%20};};ln=function%20(n,%20l,%20d)%20{%20%20%20%20return%20n.s%20==%20-1%20%20%20%20%20%20%20%20?%20Math.max(ln(n.l,%20l,%20d%20+%201),%20ln(n.r,%20l,%20d%20+%201))%20%20%20%20%20%20%20%20:%20(l[n.s]%20=%20d);};lc=function%20(c)%20{%20%20%20%20var%20s%20=%20c.length;%20%20%20%20//%20Note%20that%20the%20semicolon%20was%20intentional%20%20%20%20while%20(s%20&&%20!c[--s])%20%20%20%20%20%20%20%20;%20%20%20%20var%20cl%20=%20new%20u16(++s);%20%20%20%20//%20%20ind%20%20%20%20%20%20num%20%20%20%20%20%20%20%20%20streak%20%20%20%20var%20cli%20=%200,%20cln%20=%20c[0],%20cls%20=%201;%20%20%20%20var%20w%20=%20function%20(v)%20{%20cl[cli++]%20=%20v;%20};%20%20%20%20for%20(var%20i%20=%201;%20i%20%3C=%20s;%20++i)%20{%20%20%20%20%20%20%20%20if%20(c[i]%20==%20cln%20&&%20i%20!=%20s)%20%20%20%20%20%20%20%20%20%20%20%20++cls;%20%20%20%20%20%20%20%20else%20{%20%20%20%20%20%20%20%20%20%20%20%20if%20(!cln%20&&%20cls%20%3E%202)%20{%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20for%20(;%20cls%20%3E%20138;%20cls%20-=%20138)%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20w(32754);%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20if%20(cls%20%3E%202)%20{%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20w(cls%20%3E%2010%20?%20((cls%20-%2011)%20%3C%3C%205)%20|%2028690%20:%20((cls%20-%203)%20%3C%3C%205)%20|%2012305);%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20cls%20=%200;%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20}%20%20%20%20%20%20%20%20%20%20%20%20}%20%20%20%20%20%20%20%20%20%20%20%20else%20if%20(cls%20%3E%203)%20{%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20w(cln),%20--cls;%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20for%20(;%20cls%20%3E%206;%20cls%20-=%206)%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20w(8304);%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20if%20(cls%20%3E%202)%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20w(((cls%20-%203)%20%3C%3C%205)%20|%208208),%20cls%20=%200;%20%20%20%20%20%20%20%20%20%20%20%20}%20%20%20%20%20%20%20%20%20%20%20%20while%20(cls--)%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20w(cln);%20%20%20%20%20%20%20%20%20%20%20%20cls%20=%201;%20%20%20%20%20%20%20%20%20%20%20%20cln%20=%20c[i];%20%20%20%20%20%20%20%20}%20%20%20%20}%20%20%20%20return%20{%20c:%20cl.subarray(0,%20cli),%20n:%20s%20};};clen=function%20(cf,%20cl)%20{%20%20%20%20var%20l%20=%200;%20%20%20%20for%20(var%20i%20=%200;%20i%20%3C%20cl.length;%20++i)%20%20%20%20%20%20%20%20l%20+=%20cf[i]%20*%20cl[i];%20%20%20%20return%20l;};wfblk=function%20(out,%20pos,%20da'... 17699 more characters,
  lineNumber: 1,
  columnNumber: 149
}
```

I am on Linux Pop!_OS, using deno 2.0.4 runtime.
fflate is in version 0.8.2.

### LINKED ISSUE #33380: Overriding `globalThis.postMessage` in Worker causes recursive call stack overflow in Deno Node worker_threads compatibility layer
Version: Deno 2.7.12

Hi,

I would like to report a behavior in Deno that can be reproduced using the below PoC:

1. index.mjs
```javascript
import { Worker } from 'node:worker_threads';

const worker = new Worker('./worker.js');

worker.on('message', console.log); // message never received
```
2. worker.mjs
```javascript
'use strict';

import { parentPort } from 'node:worker_threads';

// verify that these two are different
console.log(parentPort.toString());
console.log(global.toString());

Object.assign(global, {
  postMessage: message => {
    parentPort.postMessage(message);
    console.log('message sent'); // never reached due to stack overflow
  },
});

postMessage('Hello from worker!');
```
4. Run command: `deno run -A index.mjs`

### Expected output
```
root@KContainer:~/10409# node index.js
[object EventTarget]
[object global]
message sent
Hello from worker!
```

### Actual output
```
root@KContainer:~/10409# deno run -A index.js
error: Uncaught (in worker "") Import "worker_threads" not a dependency
  hint: If you want to use a built-in Node module, add a "node:" prefix (ex. "node:worker_threads").
    at file:///home/c01kele/10409/worker.js:4:28
root@KContainer:~/10409# vi worker.js
root@KContainer:~/10409# deno run -A index.js
[object DedicatedWorkerGlobalScope]
[object DedicatedWorkerGlobalScope]
error: Uncaught (in worker "") (in promise) RangeError: Maximum call stack size exceeded
// worker.js
^
    at postMessage (file:///home/c01kele/10409/worker.js:1:1)
    at postMessage (file:///home/c01kele/10409/worker.js:1:1)
    at postMessage 
```

### PR DESCRIPTION
**Pull request by bartlomieju**
- Creates `parentPort` as a separate delegate object instead of aliasing `globalThis`, capturing native `postMessage`/`addEventListener`/`removeEventListener` at init time
- Prevents infinite recursion when Emscripten-based libraries (z3-solver) override `globalThis.postMessage` to call `parentPort.postMessage`
- Prevents double message delivery when both `parentPort.on('message')` and `self.onmessage` are set (as Emscripten does)
- Intercepts `globalThis.onmessage` via getter/setter that suppresses dispatch when Node-style listeners exist
- Mirrors `unref`/`ref` state to `globalThis` so the runtime event loop check still works

Closes #17171
Closes #26739
Closes #33380

### CODE REVIEW

File: ext/node/polyfills/worker_threads.ts [hunk 1]
```diff
@@ -975,16 +1063,15 @@ internals.__initWorkerThreads = (
...
     parentPort.off = parentPort.removeListener = function (
-      this: ParentPort,
       name,
       listener,
     ) {
-      this.removeEventListener(name, listeners.get(listener)!);
+      nativeRemoveEventListener(name, listeners.get(listener)!);
       listeners.delete(listener);
-      return this;
+      if (name === "message") messageListenerCount--;
```
Comment (fibibot) [inline ext/node/polyfills/worker_threads.ts]: Underflow bug: if `listener` was never registered via `parentPort.on/once/addListener`, then `listeners.get(listener)` is `undefined`, `nativeRemoveEventListener(name, undefined)` is a no-op, `listeners.delete(listener)` is a no-op — but `messageListenerCount--` runs anyway and pushes the count negative. Subsequent valid `on()` calls increment from there, so the count is permanently offset and `globalThis.onmessage` fires when it shouldn't (because `messageListenerCount > 0` evaluates false at counts ≤ 0).

Node's `EventEmitter.removeListener` is idempotent for missing listeners — this should be too. Easy fix: gate the decrement on `if (name === "message" && listeners.has(listener)) messageListenerCount--;` (and check `has` before the `delete`).

File: ext/node/polyfills/worker_threads.ts [hunk 2]
```diff
@@ -846,7 +848,93 @@ internals.__initWorkerThreads = (
...
+      globalThis.removeEventListener,
+      globalThis,
+    );
+    parentPort = ObjectCreate(null) as ParentPort;
+    parentPort.postMessage = function (message, transferOrOptions?) {
+      return nativePostMessage(message, transferOrOptions);
+    };
+    parentPort.addEventListener = function (name, listener, options?) {
+      return nativeAddEventListener(name, listener, options);
+    };
```
Comment (fibibot) [inline ext/node/polyfills/worker_threads.ts:908]: `parentPort.addEventListener("message", listener)` is a thin pass-through to `nativeAddEventListener`, so it doesn't bump `messageListenerCount`. That means the double-delivery suppression only works for users who go through the Node-style API:

```js
parentPort.addEventListener("message", L1);
globalThis.onmessage = handler;
// Both L1 and handler still fire — same bug the PR aims to fix.
```

If the intent is "any listener on parentPort suppresses globalThis.onmessage," the addEventListener and removeEventListener delegates need to track the count too (with the same `name === "message"` guard).

File: ext/node/polyfills/worker_threads.ts [hunk 3]
```diff
@@ -846,7 +848,93 @@ internals.__initWorkerThreads = (
...
+      globalThis,
+    );
+    const nativeAddEventListener = FunctionPrototypeBind(
+      globalThis.addEventListener,
+      globalThis,
+    );
+    const nativeRemoveEventListener = FunctionPrototypeBind(
+      globalThis.removeEventListener,
+      globalThis,
+    );
```
Comment (fibibot) [inline ext/node/polyfills/worker_threads.ts:888]: `parentPort` is now `ObjectCreate(null)` cast to `ParentPort`, but `type ParentPort = typeof self & NodeEventTarget` (line 811) still claims it has every property of `globalThis` — `fetch`, `crypto`, `caches`, `setTimeout`, etc. Any of those will type-check on `parentPort.X` but throw `TypeError: parentPort.X is not a function` at runtime. The type should be narrowed to actually reflect what's wired up here (probably just the explicit methods + `onmessage`).

**Review by fibibot — COMMENTED** [review]
The core approach is right — capturing native `postMessage`/`addEventListener` before user code runs avoids the Emscripten/z3-solver recursion, and the `messageListenerCount`-gated forwarder for `globalThis.onmessage` correctly suppresses double delivery in the targeted scenario. The two new spec tests pass cleanly and CI is green.

Three correctness concerns flagged inline that I'd want addressed before approving:

1. **`messageListenerCount` underflow on stray `off()`** — calling `parentPort.off("message", listener)` for a listener that was never registered decrements the count to a negative value, after which `globalThis.onmessage` will fire even when there are real Node-style listeners (since `messageListenerCount > 0` becomes false at counts 0 and below).

2. **`parentPort.addEventListener("message", ...)` bypasses suppression** — only the `on/once/addListener` path increments `messageListenerCount`, so a listener added via the Web API doesn't count toward the suppression. A user who mixes Web-style and Node-style listeners on `parentPort` still gets the same double-delivery the PR is meant to eliminate.

3. **`type ParentPort = typeof self & NodeEventTarget` lies after this change** — the runtime value is `ObjectCreate(null)`, so any property the type inherits from `typeof self` (e.g. `fetch`, `crypto`, `caches`) type-checks but throws at runtime.

(2) and (3) might be acceptable as known limitations if you document them, but (1) is a concrete logic bug.

File: ext/node/polyfills/worker_threads.ts [hunk 4]
```diff
@@ -846,7 +870,93 @@ internals.__initWorkerThreads = (
...
+      return nativePostMessage(message, transferOrOptions);
+    };
+    parentPort.addEventListener = function (name, listener, options?) {
+      nativeAddEventListener(name, listener, options);
+      if (name === "message") messageListenerCount++;
+    };
+    parentPort.removeEventListener = function (name, listener) {
+      nativeRemoveEventListener(name, listener);
+      if (name === "message") messageListenerCount--;
+    };
```
Comment (fibibot) [inline ext/node/polyfills/worker_threads.ts:915]: Non-blocking: `parentPort.removeEventListener("message", L)` decrements `messageListenerCount` unconditionally even when `L` was never registered (or was already removed). Calling it twice for the same listener pushes the count negative and breaks the suppression downstream the same way the off() underflow did. The on/off path solves this with `listeners.has(listener)`, but the Web `addEventListener` API doesn't give you that visibility — typically you'd track the additions in a separate Set on the addEventListener side. Lower-probability than the off() case so I'm not blocking, but worth keeping in mind.

**Review by fibibot — APPROVED** [review]
LGTM after `6a1adc62`. All three prior concerns addressed:

1. **`messageListenerCount` underflow on stray off()** — now gated by `if (listeners.has(listener))`, so `off("message", neverRegistered)` is a clean no-op.
2. **`addEventListener` bypassing the suppression** — both `parentPort.addEventListener` and `removeEventListener` now bump/decrement the count for `"message"`, so mixed Web/Node-style listener usage now correctly suppresses `globalThis.onmessage` when *any* listener is attached.
3. **`type ParentPort = typeof self & NodeEventTarget` lying** — replaced with a proper `interface ParentPort` that declares only the methods the delegate actually has (`postMessage`, `addEventListener`, `removeEventListener`, `onmessage`, `emit`, `removeAllListeners`, `setMaxListeners`, `getMaxListeners`, `eventNames`, `listenerCount`, `unref`, `ref`, plus `[key: symbol]: unknown` for the internal symbol props). `parentPort.fetch` (etc.) now correctly fails to type-check.

One minor note inline about symmetry — the new addEventListener-path tracking has the same kind of underflow as the original off() bug if `removeEventListener` is called twice for the same listener, but that's much less likely than the off() case. Non-blocking.
