### PR TITLE
fix(npm): use original node regex  in npm resolution

### LINKED ISSUE #17403: Node modules resolution fails for a valid exports configuration
## Steps to reproduce

1. Create a file `main.ts` with the following contents:

```ts
import { default as typescript } from 'npm:rollup-plugin-typescript2@0.34.1';

console.log(typeof typescript);
```

2. Run it:

```deno run --allow-read --allow-env test.ts```

## Actual result

```
rpt2: Error loading `tslib` helper library.
error: Uncaught Error: [ERR_INVALID_PACKAGE_TARGET] Invalid "exports" target ./* defined for './*' in the package config /Users/USER_NAME/Library/Caches/deno/npm/registry.npmjs.org/tslib/2.4.1/package.json imported from file:///Users/USER_NAME/Library/Caches/deno/npm/registry.npmjs.org/rollup-plugin-typescript2/0.34.1/dist/rollup-plugin-typescript2.cjs.js
    at resolveExports (deno:ext/node/02_require.js:319:21)
    at Function.Module._findPath (deno:ext/node/02_require.js:358:33)
    at Function.Module._resolveFilename (deno:ext/node/02_require.js:620:29)
    at Function.Module._load (deno:ext/node/02_require.js:469:29)
    at Module.require (deno:ext/node/02_require.js:680:21)
    at require (deno:ext/node/02_require.js:820:18)
    at Object.<anonymous> (file:///Users/USER_NAME/Library/Caches/deno/npm/registry.npmjs.org/rollup-plugin-typescript2/0.34.1/dist/rollup-plugin-typescript2.cjs.js:27922:26)
    at Object.<anonymous> (file:///Users/USER_NAME/Library/Caches/deno/npm/registry.npmjs.org/rollup-plugin-typescript2/0.34.1/dist/rollup-plugin-typescript2.cjs.js:28235:4)
    at Module._compile (deno:ext/node/02_require.js:747:36)
    at Object.Module._extensions..js (deno:ext/node/02_require.js:780:12)
```

## Expected result

```
function
```

### PR DESCRIPTION
**Pull request by wontem**
Closes #17403

### CODE REVIEW

File: ext/node/resolution.rs [hunk 1]
```diff
@@ -339,7 +339,7 @@ fn resolve_package_target_string(
     ));
   }
   let invalid_segment_re =
-    Regex::new(r"(^|\|/)(..?|node_modules)(\|/|$)").expect("bad regex");
+    Regex::new(r"(^|\\|/)(\.\.?|node_modules)?(\\|/|$)").expect("bad regex");
```
Comment (wontem) [inline ext/node/resolution.rs:342]: The corresponding regex in the node codebase:

https://github.com/nodejs/node/blob/f5dc92cff34933fc4a4685765afbba085f081b36/lib/internal/modules/esm/resolve.js#L299

After cleanup I found that not only escaping symbols are missed but also the question mark

**Comment by bartlomieju** [comment]
Cool, thanks for the fix! Any chance you could add some tests that exercise this changed regex? I believe they should be added to `cli/tests/testdata/npm/conditional_exports/main.js` and `cli/tests/testdata/npm/registry/@denotest/conditional-exports/1.0.0/package.json`. You can run the test by doing `cargo test npm::conditional_exports`

**Comment by wontem** [comment]
Sure! Just wanted to ask about tests. Thanks for the quick comment!

File: ext/node/resolution.rs (hunk 1 above)
Comment (wontem) [reply ext/node/resolution.rs]: I reverted the optional regex group change because I found that it was introduced in [this PR (related to double slash deprecation)](https://github.com/nodejs/node/pull/44477), after [the deno impelementation](https://github.com/denoland/deno/pull/15484) so I guess, it's enough to have the deprecated version for now

**Comment by wontem** [comment]
Added a test case and reverted the optional regex group change, see https://github.com/denoland/deno/pull/17404#discussion_r1070138508

**Comment by wontem** [comment]
[The failed test](https://github.com/denoland/deno/actions/runs/3915455340/jobs/6693789379#step:37:1) seems to be unrelated. Can it be flaky?

**Comment by bartlomieju** [comment]
> [The failed test](https://github.com/denoland/deno/actions/runs/3915455340/jobs/6693789379#step:37:1) seems to be unrelated. Can it be flaky?

That's possible, I restarted the CI

**Review by bartlomieju — APPROVED** [review]
LGTM! I confirmed the test fails on `main` but this PR fixes it. Very nice first contribution @wontem, thanks!
