### PR TITLE
fix(node/http): correctly send `Content-length` header instead of `Transfer-Encoding: chunked`

### LINKED ISSUE #20063: `node:http` incorrectly send `Transfer-Encoding: chunked` even if no body is written
Original issue: #20033.

After debugging for a while, I found out that the HTTP `PUT` request was sent with `Transfer-Encoding: chunked` header, although the body is empty.

Which is different from Nodejs behavior:
The header is only added by the first calling [request.write(chunk)](https://nodejs.org/dist/latest-v18.x/docs/api/http.html#requestwritechunk-encoding-callback):
> If no Content-Length is set, data will automatically be encoded in HTTP Chunked transfer encoding, so that server knows when the data ends. The Transfer-Encoding: chunked header is added.

These are the headers Nodejs would send (`PUT` with no body):
```
Headers {
  connection: "close",
  "content-length": "0",
  "content-type": "text/plain",
  host: "127.0.0.1:8001"
}
```
And these are the headers by Deno:
```
Headers {
  accept: "*/*",
  "accept-encoding": "gzip, br",
  "content-type": "text/plain",
  host: "127.0.0.1:8001",
  "transfer-encoding": "chunked",
  "user-agent": "Deno/1.36.0"
}
```

I tried digging into Deno source code to investigate the issue, and found that currently all `POST`, `PATCH` and `PUT` requests will be considered to have body:
- ext/node/polyfills/http.ts
```typescript
    this._req = core.ops.op_node_http_request(
      this.method,
      url,
      headers,
      client.rid,
      this.method === "POST" || this.method === "PATCH" ||
        this.method === "PUT",
    )
```
- ext/node/ops/http.rs (these lines are useless as a result)
```rust
    // POST and PUT requests should always have a 0 length content-length,
    // if there is no body. https://fetch.spec.whatwg.org/#http-network-or-cache-fetch
    if matches!(method, Method::POST | Method::PUT) {
      request = request.header(CONTENT_LENGTH, HeaderValue::from(0));
    }
```

I don't know how to change the code to fix the issue yet. But I think of 2 ways:
- Add `hasBody` and `hasContentTypeHeader` flags then check them in `request.write` function to add `Transfer-Encoding: chunked` (but I don't know whether the `reqwest` crate supports adding header after started).
- Only start sending `reqwest` after the first call to `request.write`.

I'd appreciate any help to implement this.

### PR DESCRIPTION
**Pull request by osddeitf**
Fix #20063.
I also added a customized node_compat test.
The test passed with this fix, but when I tried with v1.36.0, some `AssertionError` were thrown, but they were ignored and the test still passed. Need helps in that regard.

### CODE REVIEW

**Comment by osddeitf** [comment]
I have found a way to fix the test, also fixed the lint issue.

**Comment by bartlomieju** [comment]
@meszarosdezso sorry for a slow response. It seems only `deno fmt` complains at the moment - you can fix that by running `tools/format.js` script

**Comment by osddeitf** [comment]
Thank you @bartlomieju, I didn't read the Contributing guidelines carefully and missed the format and lint steps.

**Comment by osddeitf** [comment]
Can someone please review this?

**Comment by bartlomieju** [comment]
I'll review later tonight.

File: ext/node/polyfills/_http_outgoing.ts [hunk 1]
```diff
@@ -584,6 +576,170 @@ export class OutgoingMessage extends Stream {
...
+        this.statusCode + " response should not use chunked encoding," +
+          " closing connection.",
+      );
+      this.chunkedEncoding = false;
+      this.shouldKeepAlive = false;
+    }
+
+    // TODO(osddeitf): this depends on agent and underlying socket
+    // keep-alive logic
+    // if (this._removedConnection) {
```
Comment (bartlomieju) [inline ext/node/polyfills/_http_outgoing.ts:632]: Why is this commented out? It seems you changed the code to call `this.send()` which appears to already by using connection directly so this part should work as well

Comment (osddeitf) [reply ext/node/polyfills/_http_outgoing.ts:632]: That part is hard to understand, so let me elaborate (sorry if it is too long):
- The current implementation of `ClientRequest` is not using any `Agent`, there are some comments in `ClientRequest` constructor:
    ```typescript
    // initiate connection
    // TODO(crowlKats): finish this
    /*if (this.agent) {
      this.agent.addRequest(this, optsWithoutSignal);
    ```
    In Deno, the `node:http` requests are sent by calling `core.ops.op_node_http_request`, which is in turn make a new `reqwest`, not using any `Agent`.
    It's different from what I see in Nodejs implementation of `node:http` is that the `Agent` is used to manage the underlying socket connection (TCP), and the keepalive logics is to reuse the existing connections when possible.
- The logics I commented out is to add headers `Connection` as `close` or `keep-alive`, which is responsible for keepalive logics.
- The variables `this._last` and `this.shouldKeepAlive` are modified as well. They are used in the following lines in Nodejs implementation, to close the sockets:
    - https://github.com/nodejs/node/blob/v18.x/lib/_http_agent.js#L159-L166
    - https://github.com/nodejs/node/blob/v18.x/lib/_http_server.js#L972-L977
- With the crate `reqwest`, there's no way to access the underlying socket connections, as far as I know (`reqwest` may has its own way to reuse connections). So effectively, we cannot implement keepalive logics in Deno `ClientRequest`, I commented those lines to prevent HTTP header `Connection` being added, to avoid conflict with how the sockets are reused by `reqwest` crate.

Comment (bartlomieju) [reply ext/node/polyfills/_http_outgoing.ts:632]: Thanks, that makes sense to me. I plan to rewrite both `fetch` and `node:http` implementations to not use `reqwest`, but use `hyper` directly. 

@crowlKats can you take a look here? If it's fine for you too we can land it.

Comment (osddeitf) [reply ext/node/polyfills/_http_outgoing.ts:632]: It's been almost a week. How's it going?

**Review by bartlomieju — APPROVED** [review]
LGTM, thanks @osddeitf
