### PR TITLE
fix(ext/node): make next tick queue resilient to `Array.prototype` tampering

### LINKED ISSUE #24358: Deno runtime stuck in endless loop while running `Array.prototype[0]=0;`
Hi,
I would like to report that deno got stuck while running this code:

```javascript
Array.prototype[0]=0;
```
I am using Deno Version: 1.44.4 on Windows OS.

### PR DESCRIPTION
**Pull request by 0f-0b**
Closes #24358.

### CODE REVIEW

File: ext/node/polyfills/internal/fixed_queue.ts [hunk 1]
```diff
@@ -111,11 +111,13 @@ export class FixedQueue {
       // and sets it as the new main queue.
       this.head = this.head.next = new FixedCircularBuffer();
     }
+    // deno-lint-ignore prefer-primordials
     this.head.push(data);
```
Comment (bartlomieju) [inline ext/node/polyfills/internal/fixed_queue.ts:115]: Is this a false positive here? If so can you comment about it?

**Review by bartlomieju — APPROVED** [review]
Thanks!
