### PR TITLE
fix(npm): handle an npm package that has itself as a dependency

### LINKED ISSUE #17420: deno hangs when npm package has itself as a dependency
## Steps to reproduce

**Environment**
```
> deno --version
deno 1.29.3 (release, x86_64-pc-windows-msvc)
v8 10.9.194.5
typescript 4.9.4
> systeminfo
...
Microsoft Windows 11 Pro 10.0.22621 N/A Build 22621
...
```

**Command**
```
git clone https://github.com/jeiea/deno_report.git -b oci
code deno_report
```

## Expected behavior
image

image

## Actual behavior
LSP doesn't work at all.
image
It doesn't run, just hangs.
image

## Additional context
The following is Deno Language Server output when problem occurs.
```
Starting Deno language server...
  version: 1.29.3 (release, x86_64-pc-windows-msvc)
  executable: C:\ProgramData\chocolatey\lib\deno\deno.EXE
Connected to "Visual Studio Code" 1.74.3
{"type":"mark","name":"update_cache"},
{"type":"measure","name":"update_cache","count":1,"duration":0},
{"type":"mark","name":"update_tsconfig"},
{"type":"mark","name":"request","count":1,"args":{"id":2,"method":"configure","compilerOptions":{"allowJs":true,"esModuleInterop":true,"experimentalDecorators":true,"isolatedModules":true,"jsx":"react","lib":["deno.ns","deno.window"],"module":"esnext","moduleDetection":"force","noEmit":true,"resolveJsonModule":true,"strict":true,"target":"esnext","useDefineForClassFields":true,"useUnknownInCatchVariables":false}}},
{"type":"measure","name":"request","count":1,"duration":1},
{"type":"measure","name":"update_tsconfig","count":1,"duration":125},
{"type":"mark","name":"request","count":2,"args":{"id":3,"method":"getSupportedCodeFixes"}},
{"type":"measure","name":"request","count":2,"duration":0},
{"type":"mark","name":"update_import_map"},
{"type":"measure","name":"update_import_map","count":1,"duration":0},
{"type":"mark","name":"update_registries"},
Enabling import suggestions for: https://deno.land
Enabling import suggestions for: https://x.nest.land
Download https://x.nest.land/.well-known/deno-import-intellisense.json
Download https://intellisense.nest.land/deno-import-intellisense.json
Enabling import suggestions for: https://crux.land
{"type":"measure","name":"update_registries","count":1,"duration":1120},
{"type":"mark","name":"request","count":3,"args":{"id":4,"method":"getAssets"}},
{"type":"measure","name":"request","count":3,"duration":1},
{"type":"measure","name":"initialize","count":1,"duration":1253},
Server ready.
{"type":"mark","name":"did_open","count":1,"args":{"textDocument":{"uri":"file:///d%3A/Repos/jeiea/2023/01/deno_report/main.ts","languageId":"typescript","version":1,"text":"import { IdentityClient } from \"npm:oci-identity@2.50.1\";\n// import { IdentityClient } from \"https://esm.sh/oci-identity@2.50.1?dev\";\n\nconsole.log(\"hello\");\nlet a: number = \"a\";\n"}}},
{"type":"measure","name":"did_open","count":1,"duration":0},
```

### PR DESCRIPTION
**Pull request by dsherret**
I'm not sure this properly handles scenarios where an npm package uses an alias that resolves to itself, we can fix that if we find a package that actually depends on that behavior.

```
V:\deno_report [oci ≡]
> ../deno/target/debug/deno run main.ts
✅ Granted env access to "NODE_CLUSTER_SCHED_POLICY".
✅ Granted env access to "NODE_UNIQUE_ID".
hello
```

Closes #17420

### CODE REVIEW

File: cli/npm/resolution/graph.rs [hunk 1]
```diff
@@ -303,6 +303,7 @@ impl Graph {
     parent_id: &NpmPackageId,
   ) {
     let mut child = (*child).lock();
+    assert_ne!(child.id, *parent_id);
```
Comment (dsherret) [inline cli/npm/resolution/graph.rs:306]: Need to do this before it would deadlock on the line below.

**Review by bartlomieju — APPROVED** [review]
LGTM, no comments
