### PR TITLE
fix: Add sys permission kinds for node compat

### LINKED ISSUE #24241: Missing sys permission kinds for node ops
Version: Deno 1.44.2

There seem to be some sys permission checks in the node compatibility layer for kinds that cannot be specified on the CLI with `--allow-sys=xxx`.

"statfs": https://github.com/denoland/deno/blob/4b83ce8acabaf868d47bf764fce18ce5450fd314/ext/node/ops/fs.rs#L112
"getPriority": https://github.com/denoland/deno/blob/4b83ce8acabaf868d47bf764fce18ce5450fd314/ext/node/ops/os/mod.rs#L22
"setPriority": https://github.com/denoland/deno/blob/4b83ce8acabaf868d47bf764fce18ce5450fd314/ext/node/ops/os/mod.rs#L39
"userInfo": https://github.com/denoland/deno/blob/4b83ce8acabaf868d47bf764fce18ce5450fd314/ext/node/ops/os/mod.rs#L53
"geteuid": https://github.com/denoland/deno/blob/4b83ce8acabaf868d47bf764fce18ce5450fd314/ext/node/ops/os/mod.rs#L66

As far as I can tell, the only way to get these permission checks to pass (without prompting the user) is by giving a blanket `allow-sys` flag.

### PR DESCRIPTION
**Pull request by adamgreg**
Fixes #24241

* Support "statfs", "username", "getPriority" and "setPriority" kinds for `--allow-sys`.
* Check individual permissions in `node:os.userInfo()` instead of a single "userInfo" permission.
* Check for "uid" permission in `node:process.geteuid()` instead of "geteuid".
* Add missing "homedir" to `SysPermissionDescriptor.kind` union

### CODE REVIEW

**Comment by adamgreg** [comment]
Hi @bartlomieju I'm not sure why that test fails - it passes locally, and doesn't seem to relate to "sys" permissions. Can you recommend anything I should do please? It's my first time trying to contribute to the Rust codebase.

File: ext/node/ops/os/mod.rs [hunk 1]
```diff
@@ -50,7 +50,10 @@ where
 {
   {
     let permissions = state.borrow_mut::<P>();
-    permissions.check_sys("userInfo", "node:os.userInfo()")?;
+    permissions.check_sys("uid", "node:os.userInfo()")?;
+    permissions.check_sys("gid", "node:os.userInfo()")?;
+    permissions.check_sys("homedir", "node:os.userInfo()")?;
+    permissions.check_sys("username", "node:os.userInfo()")?;
```
Comment (bartlomieju) [inline ext/node/ops/os/mod.rs:56]: Can you give me a hand here and explain why we need to check for all of these permissions when getting the user name?

Comment (adamgreg) [reply ext/node/ops/os/mod.rs]: It only gets called by `node:os.userInfo()`, which returns all that information, but I hadn't noticed it would already check for the other permissions, sorry.

Comment (adamgreg) [reply ext/node/ops/os/mod.rs]: I fixed this, but it may not have been obvious, sorry.

**Review by bartlomieju — APPROVED** [review]
LGTM, thanks
