### PR TITLE
fetch: make response.body async iterable

### LINKED ISSUE #2520: Async iteration for fetch response body
```typescript
let response = await fetch(url);
for await (let chunk of response.body) {
  // ...
}
```

Currently failing with `error TS2504: Type 'Body' must have a '[Symbol.asyncIterator]()' method that returns an async iterator.`

### PR DESCRIPTION
**Pull request by kt3k**
This PR makes response.body of fetch async iterable.

fixes #2520

### CODE REVIEW

File: js/fetch_test.ts [hunk 1]
```diff
@@ -33,6 +33,17 @@ testPerm({ net: true }, async function fetchBlob(): Promise<void> {
...
 
+testPerm({ net: true }, async function fetchAsyncIterator(): Promise<void> {
+  const response = await fetch("http://localhost:4545/package.json");
+  const headers = response.headers;
+  let total = 0;
+  for await (const chunk of response.body) {
+    total += chunk.length;
+  }
+
+  assertEquals(total, Number(headers.get("Content-Length")));
```
Comment (ry) [inline js/fetch_test.ts]: 👍
