### PR TITLE
fix(compile): panic when cross-compiling between windows and unix

### LINKED ISSUE #9194: compile panic on cross compilation (from Linux)
`deno compile` panic if I try to build Windows binary from Linux :
```
$ RUST_BACKTRACE=full deno compile --unstable --lite --target x86_64-pc-windows-msvc --output cat.exe  https://deno.land/std@0.84.0/examples/cat.ts                 
Check https://deno.land/std@0.84.0/examples/cat.ts
Bundle https://deno.land/std@0.84.0/examples/cat.ts
Compile https://deno.land/std@0.84.0/examples/cat.ts
Archive:  /tmp/.tmptRru1m/denort..zip
  inflating: denort.exe              
thread 'main' panicked at 'assertion failed: exe_path.exists()', cli/tools/upgrade.rs:231:3
stack backtrace:
   0:     0x557a1500f2d3 - std::backtrace_rs::backtrace::libunwind::trace::h04d12fdcddff82aa
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/../../backtrace/src/backtrace/libunwind.rs:100:5
   1:     0x557a1500f2d3 - std::backtrace_rs::backtrace::trace_unsynchronized::h1459b974b6fbe5e1
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x557a1500f2d3 - std::sys_common::backtrace::_print_fmt::h9b8396a669123d95
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x557a1500f2d3 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::he009dcaaa75eed60
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x557a14b4bd0c - core::fmt::write::h77b4746b0dea1dd3
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/core/src/fmt/mod.rs:1078:17
   5:     0x557a1500eb71 - std::io::Write::write_fmt::heb7e50902e98831c
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/io/mod.rs:1518:15
   6:     0x557a1500e535 - std::sys_common::backtrace::_print::h2d880c9e69a21be9
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x557a1500e535 - std::sys_common::backtrace::print::h5f02b1bb49f36879
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x557a1500e535 - std::panicking::default_hook::{{closure}}::h658e288a7a809b29
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:208:50
   9:     0x557a1500db15 - std::panicking::default_hook::hb52d73f0da9a4bb8
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:227:9
  10:     0x557a1500db15 - std::panicking::rust_panic_with_hook::hfe7e1c684e3e6462
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:593:17
  11:     0x557a14d71c84 - std::panicking::begin_panic::{{closure}}::hcb184a9ed52d5de5
  12:     0x557a14d71c5e - std::sys_common::backtrace::__rust_end_short_backtrace::haf2505beafd41248
  13:     0x557a14d71d15 - std::panicking::begin_panic::h3ea500739663b54d
  14:     0x557a14adbe52 - deno::tools::upgrade::unpack::hb80d39caf8bb2400
  15:     0x557a14ae5e64 - deno::compile_command::{{closure}}::hfc176927aaf9d749
  16:     0x557a14a2f7b4 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h21fa68fb0634807c
  17:     0x557a14ca64b7 - tokio::runtime::Runtime::block_on::hf66222ab1c11c910
  18:     0x557a14af3019 - deno::main::h9bec61bb270fe059
  19:     0x557a14905ea1 - std::sys_common::backtrace::__rust_begin_short_backtrace::h3112b22ed8321e5c
  20:     0x557a14b00c81 - main
  21:     0x7f51f3b140b3 - __libc_start_main
  22:     0x557a1489ad3a - _start
  23:                0x0 - <unknown>

$ deno --version                                                                                                                                              
deno 1.7.0 (release, x86_64-unknown-linux-gnu)
v8 8.9.255.3
typescript 4.1.3
```

### PR DESCRIPTION
**Pull request by Liamolucko**
The zip unpacker was assuming the extension would be the same as the host platform (using `cfg!(windows)`), which worked fine for `upgrade` but not cross-compilation.

Fixes #9194.

### CODE REVIEW

File: cli/tools/upgrade.rs [hunk 1]
```diff
@@ -177,12 +177,13 @@ async fn download_package(
 pub fn unpack(
   archive_data: Vec<u8>,
   exe_name: &str,
+  windows: bool,
```
Comment (lucacasonato) [inline cli/tools/upgrade.rs:180]: Rename to `is_windows`.

**Review by lucacasonato — COMMENTED** [review]
Just a minor nitpick.

**Review by kt3k — APPROVED** [review]
LGTM

Confirmed this fixes the cross compile of window binary in non windows machine.

**Comment by kt3k** [comment]
By the way probably we should add test case for cross compiling in cli/tests/integration_tests.rs, though it requires the internet access.
