### PR TITLE
fix(lsp): handle invalid config setting better

### LINKED ISSUE #11100: lsp: `deno.config` set to empty string causes strange errors
In VSCode if someone changes the global setting `deno: Config` then deletes the text, VSCode replaces the value in the global `settings.json` with an empty string causing VSCode to see things such as `top-level await` and `console.log` as errors.

image

To my knowledge the only way to fix this is to edit the global `settings.json` by hand and removing the `deno.config` field entirely which is not intuitive at all.

### PR DESCRIPTION
**Pull request by kitsonk**
Fixes #11100

### CODE REVIEW

File: cli/lsp/language_server.rs [hunk 1]
```diff
@@ -324,6 +324,59 @@ impl Inner {
...
+          Url::from_file_path(config_path).map_err(|_| {
+            anyhow!("Bad file path for configuration file: \"{}\"", config_str)
+          })
+        } else {
+          Err(anyhow!(
+            "The path to the configuration file (\"{}\") is not resolvable.",
+            config_str
+          ))
+        }?;
+        info!("  Resolved configuration file: \"{}\"", config_url);
```
Comment (satyarohith) [inline cli/lsp/language_server.rs:354]:
```suggestion
        info!("Resolved configuration file: \"{}\"", config_url);
```

**Review by satyarohith — APPROVED** [review]
LGTM. Also fixes #10808

File: cli/lsp/language_server.rs (hunk 1 above)
Comment (kitsonk) [reply cli/lsp/language_server.rs:354]: The spacing is intentional, as it occurs after the value is read. The spacing was already there, it was just the code refactored to handle errors better.
