### PR TITLE
fix(watcher): watcher doesn't exit when module resolution fails

### LINKED ISSUE #7848: deno run --watch exits when file has invalid syntax
This is possibly intentional, but I would like to illustrate my case regardless:
if I have a file like so:
```ts
// test.ts
function x() {
}
```
when I run `deno run --watch --unstable test.ts`, the file compiles. If I change the file to something with invalid syntax, like so:
```ts
// test.ts
function__ x() {
}
```
then deno outputs the following, but keeps the watcher active:
```
Watcher File change detected! Restarting!
error: Expected ';', '}' or <eof> at file:///home/andrew/test.ts:1:11
Watcher Process terminated! Restarting on file change...
```
however, if I _start_ `deno run --watch --unstable test.ts` on a file with invalid syntax, it writes the error, and then immediately exists:
```
 ✘ andrew  ~  deno run --watch --unstable test.ts
error: Expected ';', '}' or <eof> at file:///home/andrew/test.ts:1:11
```

I believe what should happen here, is that `run --watch` should keep the file watcher active even when the first compilation fails with invalid syntax

### PR DESCRIPTION
**Pull request by magurotuna**
This commit makes the file watcher continue to work even if module
resolution fails at the initial attempt, allowing us to execute `run`
or `bundle` subcommand when a script has invalid syntax. In such
cases, the watcher observes a single file that is specified as an
command line argument.

Fixes #7848

### CODE REVIEW

File: cli/tests/integration_tests.rs [hunk 1]
```diff
@@ -1294,7 +1296,11 @@ fn bundle_watch_fail() {
   std::thread::sleep(std::time::Duration::from_secs(1));
   assert!(stderr_lines.next().unwrap().contains("file_to_watch.js"));
   assert!(stderr_lines.next().unwrap().contains("error:"));
-  assert!(!deno.wait().unwrap().success());
+  assert!(stderr_lines.next().unwrap().contains("Bundle failed!"));
+  // the target file hasn't been created yet
+  assert!(!target_file.is_file());
+  // Make sure the Deno's process is still alive
+  assert!(deno.try_wait().unwrap().is_none());
```
Comment (bartlomieju) [inline cli/tests/integration_tests.rs:1304]: Nice! Could you create a file and check that watcher actually restarts as expected?

Comment (magurotuna) [reply cli/tests/integration_tests.rs]: Sure, done it 👍

**Review by bartlomieju — APPROVED** [review]
I've tested this PR locally, works great, very good fix @magurotuna, LGTM
