### PR TITLE
fix: support mts files for `deno test` & `deno fmt`

### LINKED ISSUE #13268: `deno test` command fails to detect `.mts` test files
The `deno test` command fails to detect test files that have the `.mts` file extension.

For example, with the `foo_test.mts` file present, running:

```
deno test
```

Results in:

```
error: No test modules found
```

The `.mts` file extension needs to be supported for tests so they can properly import `.mjs` ESM containing JSDoc TypeScript types.

### PR DESCRIPTION
**Pull request by crowlKats**
Closes #13268

### CODE REVIEW

**Comment by bartlomieju** [comment]
This looks fine, but it would be great to add `mts` files to `cli/tests/testdata/fmt` and `cli/tests/testdata/test/` to ensure they do picked up automatically.

Following up on the conversation from Discord, I think we should also recognize `cjs` and `cts` files for both `deno fmt` and `deno test` (the latter only in --compat mode). Thoughts?

File: cli/fs_util.rs [hunk 1]
```diff
@@ -130,7 +130,7 @@ pub fn resolve_from_cwd(path: &Path) -> Result<PathBuf, AnyError> {
 /// Checks if the path has extension Deno supports.
 pub fn is_supported_ext(path: &Path) -> bool {
   if let Some(ext) = get_extension(path) {
-    matches!(ext.as_str(), "ts" | "tsx" | "js" | "jsx" | "mjs")
+    matches!(ext.as_str(), "ts" | "tsx" | "js" | "jsx" | "mjs" | "mts")
```
Comment (dsherret) [inline cli/fs_util.rs:133]: I think we might as well add cts and cjs because of node compat mode?

**Review by dsherret — APPROVED** [review]
LGTM

File: cli/fs_util.rs [hunk 2]
```diff
@@ -130,7 +130,10 @@ pub fn resolve_from_cwd(path: &Path) -> Result<PathBuf, AnyError> {
 /// Checks if the path has extension Deno supports.
 pub fn is_supported_ext(path: &Path) -> bool {
```
Comment (dsherret) [inline cli/fs_util.rs:131]: Actually, I just realized this function name and looked at its usages. Perhaps we should remove `cjs` and `cts` from this function. For `is_supported_ext_fmt` I think it makes sense to have `cjs` and `cts`.

Comment (crowlKats) [reply cli/fs_util.rs:131]: Yes, though it would be weird supporting `cjs` & `cts` only in fmt and test, and not lint. just seems like it would be unexpected behaviour for someone that is using a `cjs` or `cts` fiel

Comment (crowlKats) [reply cli/fs_util.rs:131]: With compat mode only, this seems also weird, as to allow a certain filetype depending on compat just seems weird

Comment (dsherret) [reply cli/fs_util.rs:131]: Sorry, my brain is fried at the moment after the swc upgrade. I meant for this and test to not enable it, but yeah I'm not sure what the desired behaviour is. Would be good to confirm with @bartlomieju before merging.

The one issue would be that picking up cjs/cts files would error for deno test if `--compat` mode wasn't enabled, but yeah maybe that's not a big deal and it would just be a reminder to turn on `--compat`.

Comment (bartlomieju) [reply cli/fs_util.rs:131]: I think it's okay to always include `cjs` and `cts`

**Review by bartlomieju — APPROVED** [review]
