### PR TITLE
BREAKING(unstable): Use hosts for net allowlists

### LINKED ISSUE #7587: Deno Permissions API request method unable to grant url "scoped" net permissions
The unstable Deno Permissions APIs `request()` method currently appears unable to grant url "scoped" permissions for the `net` `PermissionDescriptor` whose interface allows for providing an allowlist for urls.

Please see below for code to reproduce:

```ts
console.log(await Deno.permissions.query({ name: "net", url: "http://google.com" }));
console.log(await Deno.permissions.revoke({ name: "net" }));
console.log(await Deno.permissions.request({ name: "net", url: "http://google.com" }));
console.log(await Deno.permissions.query({ name: "net", url: "http://google.com" }));
console.log(await fetch("http://google.com"));
```

When executed with the following command:

```console
$ deno run --unstable --allow-net=google.com ./example.ts

PermissionStatus { state: "granted" }
PermissionStatus { state: "prompt" }
️⚠️  Deno requests network access to "http://google.com". Grant? [g/d (g = grant, d = deny)] g
PermissionStatus { state: "granted" }
PermissionStatus { state: "prompt" }
error: Uncaught PermissionDenied: network access to "http://google.com/", run again with the --allow-net flag
    at Object.jsonOpAsync (core.js:236:13)
    at async fetch (deno:op_crates/fetch/26_fetch.js:1272:29)
    at async example.ts:13:13
```

The expected behaviour is that following the permission request the following query should return a `PermissionStatus` with `state: "granted"` and the `fetch()` should be permitted.

Instead we are seeing the permission is not granted, despite the `granted` state response from the request call and the `fetch()` throws a `PermissionDenied` error.

### PR DESCRIPTION
**Pull request by nayeemrmn**
Allowlist checking already uses hosts but for some reason requests, revokes and the runtime permissions API use URLs.
- BREAKING(`lib.deno.unstable.d.ts`): Change `NetPermissionDescriptor::url` to `NetPermissionDescriptor::host`
- fix(`runtime/permissions`): Don't add whole URLs to the allowlist on request
- fix(`runtime/permissions`): Harden strength semantics (`{ name: "net", host: "127.0.0.1" }` _stronger than_ `{ name: "net", host: "127.0.0.1:8000" }`) for blocklisting
- refactor(`runtime/permissions`): Use tuples for hosts, make the host optional in `Permissions::{query_net, request_net, revoke_net}()`

---

Fixes #7587.

### CODE REVIEW

**Review by kitsonk — APPROVED** [review]
LGTM

**Comment by kitsonk** [comment]
As this is a breaking change to an unstable API, we won't land this until 1.7.0.

**Review by crypt096 — APPROVED** [review]

File: runtime/permissions.rs [hunk 1]
```diff
@@ -545,18 +546,31 @@ impl Permissions {
     )
   }
 
-  pub fn check_net(&self, hostname: &str, port: u16) -> Result<(), AnyError> {
-    self.query_net(hostname, Some(port)).check(
-      &format!("network access to \"{}:{}\"", hostname, port),
+  pub fn check_net<T: AsRef<str>>(
+    &self,
+    host: &(T, Option<u16>),
```
Comment (bartlomieju) [inline runtime/permissions.rs:551]: Maybe `host: (&str, Option<u16>)` or split `host` and `port`? I think @magurotuna had similar problem in his DNS PR

Comment (nayeemrmn) [reply runtime/permissions.rs:551]: `(&str, Option<u16>)` doesn't work because it's really hard to pass a `String` when a `&str` is expected as part of a tuple. Splitting `host` and `port` avoids the issue, but it's inconsistent and not applicable with the other APIs where this is wrapped in an `Option`.

Comment (bartlomieju) [reply runtime/permissions.rs:551]: Thanks for explanation, that sounds reasonable to me, let's keep as is

**Review by bartlomieju — APPROVED** [review]
LGTM
