### PR TITLE
fix(ext/node): fix prismjs compatibiliy in Web Worker

### LINKED ISSUE #25008: self is not defined in NPM packages imported in a Worker
Version: Deno 1.45.5

I have the following code:

```js
// worker.js
import prism from "npm:prismjs@1.29.0";

console.log(prism);
console.log(self);
```

That it's executed inside a worker:

```js
new Worker(new URL('./worker.js', import.meta.url), { type: 'module' });
```

And this produces the following error:

```
error: Uncaught (in worker "") (in promise) ReferenceError: self is not defined
    at Object.<anonymous> (file:///Users/oscarotero/Library/Caches/deno/npm/registry.npmjs.org/prismjs/1.29.0/prism.js:11:48)
```

Looks like the `self` object is not defined inside Prism npm package. It's accessed here:

```js
var _self = (typeof window !== 'undefined')
	? window   // if in browser
	: (
		(typeof WorkerGlobalScope !== 'undefined' && self instanceof WorkerGlobalScope)
			? self // if in worker
			: {}   // if in node js
	);
```

Replacing `self` with `globalThis`, the script works fine:

```js
var _self = (typeof window !== 'undefined')
	? window   // if in browser
	: (
		(typeof WorkerGlobalScope !== 'undefined' && globalThis instanceof WorkerGlobalScope)
			? globalThis // if in worker
			: {}   // if in node js
	);
```

The problem seems to exist only in NPM packages, because the following js file run in a Worker doesn't fail:

```js
console.log(self);
```

### PR DESCRIPTION
**Pull request by kt3k**
PrismJS uses `WorkerGlobalScope` and `self` for detecting browser's Web Worker context:

https://github.com/PrismJS/prism/blob/59e5a3471377057de1f401ba38337aca27b80e03/prism.js#L11

Now the detection logic above is broken when it's imported from Deno's Web Worker context because we only hide `self` (Prism assumes when `WorkerGlobalScope` is available, `self` is also available).

This PR fixes the above by also hiding `WorkerGlobalScope` global in Node compat mode.

closes #25008

### CODE REVIEW

File: ext/node/global.rs [hunk 1]
```diff
@@ -80,7 +81,7 @@ const MANAGED_GLOBALS: [&[u16]; 13] = [
 ];
 
 const SHORTEST_MANAGED_GLOBAL: usize = 4;
-const LONGEST_MANAGED_GLOBAL: usize = 14;
+const LONGEST_MANAGED_GLOBAL: usize = 17;
```
Comment (devsnek) [inline ext/node/global.rs:84]: these could be calculated in a const expr so they can't fall out of date

Comment (kt3k) [reply ext/node/global.rs:84]: Is that easily/reasonably done? Looked into `const fn` feature, but it seems very limited..

Anyway this value is indirectly tested via the test cases

**Review by littledivy — APPROVED** [review]
LGTM
