### PR TITLE
fix permission prompt stuffing

### LINKED ISSUE #9750: Runtime permissions request should fully consume STDIN before asking for user input
A simple way to reproduce:
```typescript
import { sleep } from "https://deno.land/x/sleep/mod.ts";

const buf = new Uint8Array(3);

console.log('Please, enter `long` to start long tests:');
await Deno.stdin.read(buf);
await Deno.permissions.request({ 'name': 'env' });
console.log('\x1bcFooled you! Now I know your $HOME:', Deno.env.get('HOME'))
```

Just entering `long` on the first question would be enough to auto-confirm permissions request. Clearing the screen afterwards is fast enough on my system to hide the fact of requesting permissions from user.

Another vector of attack could be tricking the terminal into producing `g` into STDIN (using some `request` escape codes). Terminal won't produce newlines, but any string starting with `g` is recognized as `grant` by Deno, so even if user enters `d` afterwards, it would be `gd<Enter>`, which is `grant`.

### PR DESCRIPTION
**Pull request by ry**
Fixes  #9750

### CODE REVIEW

File: runtime/permissions.rs [hunk 1]
```diff
@@ -1194,6 +1194,29 @@ fn permission_prompt(message: &str) -> bool {
...
+  fn clear_stdin() {
+    unsafe {
+      let stdin = winapi::um::processenv::GetStdHandle(
+        winapi::um::winbase::STD_INPUT_HANDLE,
+      );
+      let flags =
+        winapi::um::winbase::PURGE_TXCLEAR | winapi::um::winbase::PURGE_RXCLEAR;
+      winapi::um::commapi::PurgeComm(stdin, flags);
+    }
+  }
```
Comment (bartlomieju) [inline runtime/permissions.rs:1214]: I'm wondering if https://docs.microsoft.com/en-us/windows/console/flushconsoleinputbuffer might be a better choice

**Review by bartlomieju — APPROVED** [review]
LGTM
