### PR TITLE
workers: minimal error handling and async module loading

### LINKED ISSUE #2444: Workers crash silently
```js
// file: main.js
let worker = new Worker("./worker.js");
worker.postMessage("hello");
console.log("finished main thread");
```

```js
// file: worker.js
onmessage = (e) => {
  console.log("worker recieved message", e.data);
  new DoesNotExist();
  console.log("end worker");
}
```

```
$ deno run main.js
finished main thread
worker recieved message hello
```

There should be a crash message here, right? Here's what Chrome says:

```
finished main thread
worker recieved message hello
Uncaught ReferenceError: DoesNotExist is not defined
    at onmessage (worker.js:3)
```

### LINKED ISSUE #3020: Uncaught errors in workers should trigger onerror
Related to #2797 (fix in #3019)

Uncaught worker errors should trigger an `ErrorEvent` which can be handled by the `.onerror` handler.  For example this should work under Deno:

```ts
const worker = new Worker("./something.js");
worker.onerror = (evt) => {
  console.log(evt);
  evt.preventDefault();
};
```

If the error event isn't cancelled, it should bubble up to the `window.onerror` (as a normal `Error`).

### PR DESCRIPTION
**Pull request by bartlomieju**
Fixes #2444
Fixes #3020

### CODE REVIEW

**Comment by bartlomieju** [comment]
@ry not fully done, but it's landable now. Runtime snapshot blocks further work for now

File: core/es_isolate.rs [hunk 1]
```diff
@@ -380,6 +380,15 @@ impl EsIsolate {
...
   }
 
+  pub fn clear_exception(&mut self) {
+    let isolate = self.core_isolate.v8_isolate.as_ref().unwrap();
+    let mut locker = v8::Locker::new(isolate);
+    let mut hs = v8::HandleScope::new(&mut locker);
+    let scope = hs.enter();
+    self.core_isolate.last_exception_handle.reset(scope);
+    self.core_isolate.last_exception.take();
+  }
```
Comment (ry) [inline core/es_isolate.rs]: Wouldn't it make more sense for this method to be on core/isolate.rs ?
