### PR TITLE
fix(ext/node): implement `DatabaseSync.function()` and better error details

### LINKED ISSUE #30097: node:sqlite hides error details
Version: Deno 2.4.1

Given:
```js
import * as sql from "node:sqlite"

const db = new sql.DatabaseSync("./node.example.sqlite3", {open: true})
const st = db.prepare("select * from example")
```

```
> deno --version
deno 2.4.1 (stable, release, x86_64-pc-windows-msvc)
v8 13.7.152.6-rusty
typescript 5.8.3
```

```
> deno run -RW error.example.js
error: Uncaught (in promise) Error: failed to prepare statement
const st = db.prepare("select * from example")
              ^
    at file:///C:/Users/codyc/code/sqlite-thing/error.example.js:4:15
```

Meanwhile, in node: v24.4.0
```
file:///C:/Users/codyc/code/sqlite-thing/error.example.js:4
const st = db.prepare("select * from example")
              ^

Error: no such table: example
    at file:///C:/Users/codyc/code/sqlite-thing/error.example.js:4:15
    at ModuleJob.run (node:internal/modules/esm/module_job:370:25)
    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:665:26)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:99:5) {
  code: 'ERR_SQLITE_ERROR',
  errcode: 1,
  errstr: 'SQL logic error'
}
```

There was a PR here that was supposed to add more detail, but maybe there's been a regression? (Or maybe the PR never fixed this issue, because I can reproduce this behavior in 2.2.6, 2.2.13 and 2.3.1 as well.) 

https://github.com/denoland/deno/pull/28431

There was an older issue about not report errors, but was reported there as being unrelated to this one:
https://github.com/denoland/deno/issues/28259

Though this commenter is getting the same error in Deno 2.2.4 as I'm getting in 2.4.1:
https://github.com/denoland/deno/issues/28259#issuecomment-2726674313

### PR DESCRIPTION
**Pull request by Tango992**
Closes #30097

Implementation is based on https://github.com/nodejs/node/blob/v24.2.0/src/node_sqlite.cc

Changes in this PR allows https://github.com/nodejs/node/blob/v24.2.0/test/parallel/test-sqlite-custom-functions.js test to pass.

### CODE REVIEW

File: ext/node/ops/sqlite/database.rs [hunk 1]
```diff
@@ -573,13 +580,204 @@ impl DatabaseSync {
...
+    if !function_value.is_function() {
+      return Err(
+        validators::Error::InvalidArgType(
+          "The \"function\" argument must be a function.",
+        )
+        .into(),
+      );
+    }
+
+    let function: v8::Local<v8::Function> = function_value.try_into().unwrap();
```
Comment (littledivy) [inline ext/node/ops/sqlite/database.rs]: nit: this can be merged into a let-else. `try_into` returns Err if value is not a function.
