### PR TITLE
fix: format wasm stack traces per W3C spec

### LINKED ISSUE #32239: Wasm stack traces are not correctly formatted
Version: Deno 2.6.9

This issues was found while trying to make all the emscripenten tests pass under deno: https://github.com/emscripten-core/emscripten/issues/26234

Running a test that crashes under node looks like this:

```
Error
    at run_js (/usr/local/google/home/sbc/dev/wasm/emscripten/out/test/a.out.js:1:7527)
    at wasm://wasm/f0d79f0e:wasm-function[4]:0x140
    at 1069 (/usr/local/google/home/sbc/dev/wasm/emscripten/out/test/a.out.js:1:7492)
    at runEmAsmFunction (/usr/local/google/home/sbc/dev/wasm/emscripten/out/test/a.out.js:1:6491)
    at _emscripten_asm_const_int (/usr/local/google/home/sbc/dev/wasm/emscripten/out/test/a.out.js:1:6554)
    at wasm://wasm/f0d79f0e:wasm-function[5]:0x150
    at callMain (/usr/local/google/home/sbc/dev/wasm/emscripten/out/test/a.out.js:1:8399)
    at doRun (/usr/local/google/home/sbc/dev/wasm/emscripten/out/test/a.out.js:1:8803)
    at run (/usr/local/google/home/sbc/dev/wasm/emscripten/out/test/a.out.js:1:8957)
    at removeRunDependency (/usr/local/google/home/sbc/dev/wasm/emscripten/out/test/a.out.js:1:5927)
```

But this from deno:

```
Error
    at run_js (file:///usr/local/google/home/sbc/dev/wasm/emscripten/out/test/a.out.js:1:7748)
    at <anonymous> (wasm://wasm/4b6c7e0a:1:321)
    at Object.1069 (file:///usr/local/google/home/sbc/dev/wasm/emscripten/out/test/a.out.js:1:7713)
    at runEmAsmFunction (file:///usr/local/google/home/sbc/dev/wasm/emscripten/out/test/a.out.js:1:6712)
    at _emscripten_asm_const_int (file:///usr/local/google/home/sbc/dev/wasm/emscripten/out/test/a.out.js:1:6775)
    at <anonymous> (wasm://wasm/4b6c7e0a:1:337)
    at callMain (file:///usr/local/google/home/sbc/dev/wasm/emscripten/out/test/a.out.js:1:8620)
    at doRun (file:///usr/local/google/home/sbc/dev/wasm/emscripten/out/test/a.out.js:1:9024)
    at run (file:///usr/local/google/home/sbc/dev/wasm/emscripten/out/test/a.out.js:1:9178)
    at removeRunDependency (file:///usr/local/google/home/sbc/dev/wasm/emscripten/out/test/a.out.js:1:6148)
```

note the `wasm://wasm/4b6c7e0a:1:321` vs `wasm://wasm/f0d79f0e:wasm-function[4]:0x140` in the second line.

In emscripten we rely on the stack strace format for things like ASAN and LSAN, and in particuler we depend on the `wasm-function[N]` part and we expect the offset to be in hex, which is specified in the Wasm spec: https://www.w3.org/TR/wasm-web-api-2/#conventions

### PR DESCRIPTION
**Pull request by bartlomieju**
## Summary

- Update wasm stack trace formatting to use the W3C WebAssembly Web API spec format: `wasm-function[<funcIndex>]:0x<hexOffset>` instead of the generic `line:col` format
- Update existing `wasm_url` test expectation to match
- Add new integration test (`wasm_stack_trace`) covering:
  - Basic unreachable trap with correct `wasm-function[0]:0x<offset>` format
  - Multi-frame wasm call chain verifying correct function indices across frames
  - `Error.prepareStackTrace` callsite `toString()` producing correct wasm format

Fixes #32239
Actually fixed in https://github.com/denoland/deno/pull/32293, this just adds a test.

### CODE REVIEW

File: tests/specs/run/wasm_stack_trace/wasm_stack_trace.js [hunk 1]
```diff
@@ -0,0 +1,45 @@
+// Test 1: Basic unreachable trap - verify wasm stack frame format
+console.log("=== Test 1: unreachable trap ===");
+try {
+  const binary = Deno.readFileSync("./unreachable.wasm");
+  const module = new WebAssembly.Module(binary);
```
Comment (nathanwhit) [inline tests/specs/run/wasm_stack_trace/wasm_stack_trace.js]: These could be just normal wasm imports, but not a huge deal
