### PR TITLE
fix(ext/webgpu): accept `ArrayBuffer` in `GPUQueue.writeBuffer()` as data source

### LINKED ISSUE #33151: `GPUQueue.writeBuffer()` rejects `ArrayBuffer` as data source
`GPUQueue.writeBuffer()` throws a `TypeError: data must be an ArrayBuffer or ArrayBufferView` when the `data` argument is a plain `ArrayBuffer`, even though the WebGPU spec (see https://www.w3.org/TR/webgpu/#dom-gpuqueue-writebuffer) and the error message itself both indicate `ArrayBuffer` should be accepted.

### Repro

```ts
const adapter = await navigator.gpu.requestAdapter();
const device = await adapter.requestDevice();

const buffer = device.createBuffer({
  size: 64,
  usage: GPUBufferUsage.COPY_DST,
});

// works
device.queue.writeBuffer(buffer, 0, new Uint8Array(64));
console.log("Uint8Array: OK");

// fails (but should be valid according to the spec, I think)
device.queue.writeBuffer(buffer, 0, new ArrayBuffer(64));
console.log("ArrayBuffer: OK");
```

Run with:

```sh
deno run --unstable-webgpu repro.ts
```

### Expected behaviour

Both calls succeed. Spec says that `data` can be `AllowSharedBufferSource` which is just `ArrayBuffer | SharedArrayBuffer | ArrayBufferView`. A plain `ArrayBuffer` must therefore be accepted.

### Actual behaviour

The second call throws:

```sh
$ deno run /tmp/repro.ts 
Uint8Array: OK
error: Uncaught (in promise) TypeError: data must be an ArrayBuffer or ArrayBufferView
device.queue.writeBuffer(buffer, 0, new ArrayBuffer(64));
             ^
    at file:///tmp/repro.ts:14:14

```

Funnily enough, the error says I should use `ArrayBuffer` (which I do).

**Deno version:** `deno 2.7.11 (stable, release, x86_64-unknown-linux-gnu)`

### PR DESCRIPTION
**Pull request by KnorpelSenf**
Fixes #33151.

LLM-generated fix, rewritten by hand. Running the repro script from the #33151 shows that it's fixed.

~~I tried adding a test but I can't seem to get webgpu tests to run on my machine. Somehow, they are always skipped, and I can't figure out why right now. Might fix this up, or you do it.~~
I figured it out

### CODE REVIEW

File: ext/webgpu/queue.rs [hunk 1]
```diff
@@ -159,6 +159,16 @@ impl GPUQueue {
...
       (buf, bpe)
+    } else if let Ok(ab) = v8::Local::<v8::ArrayBuffer>::try_from(data_arg) {
+      let byte_len = ab.byte_length();
+      // SAFETY: Pointer is non-null and byte_len is within the backing store.
+      let buf = unsafe {
+        std::slice::from_raw_parts(
+          ab.data().unwrap().as_ptr() as *const u8,
+          byte_len,
+        )
+      };
```
Comment (Hajime-san) [inline ext/webgpu/queue.rs]: split `unsafe` block same as above might be better

Comment (KnorpelSenf) [reply ext/webgpu/queue.rs]: Done
