### PR TITLE
fix(cli): make output of deno info --json deterministic

### LINKED ISSUE #8458: deno info --json deps order is not deterministic
```
/m/f/P/g/d/deno_registry2 ❯❯❯ deno info https://deno.land/std@0.64.0/node/util.ts --json --unstable
{
  "compiled": null,
  "depCount": 4,
  "fileType": "TypeScript",
  "files": {
    "https://deno.land/std@0.64.0/node/_util/_util_callbackify.ts": {
      "deps": [],
      "size": 4287
    },
    "https://deno.land/std@0.64.0/node/_util/_util_promisify.ts": {
      "deps": [],
      "size": 4839
    },
    "https://deno.land/std@0.64.0/node/_util/_util_types.ts": {
      "deps": [],
      "size": 7362
    },
    "https://deno.land/std@0.64.0/node/_utils.ts": {
      "deps": [],
      "size": 3807
    },
    "https://deno.land/std@0.64.0/node/util.ts": {
      "deps": [
        "https://deno.land/std@0.64.0/node/_util/_util_promisify.ts",
        "https://deno.land/std@0.64.0/node/_util/_util_types.ts",
        "https://deno.land/std@0.64.0/node/_util/_util_callbackify.ts",
        "https://deno.land/std@0.64.0/node/_utils.ts"
      ],
      "size": 2298
    }
  },
  "local": "/home/lucacasonato/.cache/deno/deps/https/deno.land/fd5d9188a1b139610da039170f5fb94b0bbb4e07ba48624c6e4b3991a2f3154f",
  "map": null,
  "module": "https://deno.land/std@0.64.0/node/util.ts",
  "totalSize": 22593
}⏎                                            
```
```                                                                                                                                                                                         /m/f/P/g/d/deno_registry2 ❯❯❯ deno info https://deno.land/std@0.64.0/node/util.ts --json --unstable
{
  "compiled": null,
  "depCount": 4,
  "fileType": "TypeScript",
  "files": {
    "https://deno.land/std@0.64.0/node/_util/_util_callbackify.ts": {
      "deps": [],
      "size": 4287
    },
    "https://deno.land/std@0.64.0/node/_util/_util_promisify.ts": {
      "deps": [],
      "size": 4839
    },
    "https://deno.land/std@0.64.0/node/_util/_util_types.ts": {
      "deps": [],
      "size": 7362
    },
    "https://deno.land/std@0.64.0/node/_utils.ts": {
      "deps": [],
      "size": 3807
    },
    "https://deno.land/std@0.64.0/node/util.ts": {
      "deps": [
        "https://deno.land/std@0.64.0/node/_utils.ts",
        "https://deno.land/std@0.64.0/node/_util/_util_callbackify.ts",
        "https://deno.land/std@0.64.0/node/_util/_util_promisify.ts",
        "https://deno.land/std@0.64.0/node/_util/_util_types.ts"
      ],
      "size": 2298
    }
  },
  "local": "/home/lucacasonato/.cache/deno/deps/https/deno.land/fd5d9188a1b139610da039170f5fb94b0bbb4e07ba48624c6e4b3991a2f3154f",
  "map": null,
  "module": "https://deno.land/std@0.64.0/node/util.ts",
  "totalSize": 22593
}⏎                                                                                                                                                                                               
```

### PR DESCRIPTION
**Pull request by wperron**
changed the HashSet used to build the ModuleInfoMap for a BTreeSet to keep the items sorted

Fixes #8458

### CODE REVIEW

File: core/module_specifier.rs [hunk 1]
```diff
@@ -207,6 +208,18 @@ impl PartialEq<String> for ModuleSpecifier {
...
+    self.0.cmp(&other.0)
+  }
+}
+
+impl PartialOrd for ModuleSpecifier {
+  fn partial_cmp(&self, other: &Self) -> Option<Ordering> {
+    Some(self.cmp(other))
+  }
+}
+
```
Comment (magurotuna) [inline core/module_specifier.rs:222]: Seems we could derive `PartialOrd` and `Ord` automatically instead of manually implementing them.

```rust
#[derive(Debug, Clone, Eq, Hash, PartialEq, serde::Serialize, PartialOrd, Ord)]
/// Resolved module specifier
pub struct ModuleSpecifier(Url);
```

I'd prefer this :)

**Review by ry — APPROVED** [review]
LGTM - thanks!
