### PR TITLE
fix: deno info should respect import map

### LINKED ISSUE #19742: `deno info` should respect import map
When running `deno info` it doesn't seem to respect the paths specified in the import map.

- `deno info preact/debug` -> doesn't work
- `deno info https://esm.sh/preact@10.15.1/debug` -> works

## Steps to reproduce

1. Add `deno.json` with the following content:
  ```json
  {
    "imports": {
      "preact": "https://esm.sh/preact@10.15.1",
      "preact/": "https://esm.sh/preact@10.15.1/"
    }
  }
  ```
2. Create a `main.tsx` file with the following content:
  ```jsx
  import { render } from "preact";
  console.log(render);
  ```
3. Run `deno run main.tsx` to force deno to download dependencies
4. Run `deno info preact/debug` -> module not found

### PR DESCRIPTION
**Pull request by vedant-pandey**
Closes #19742

### CODE REVIEW

File: cli/tools/info.rs [hunk 1]
```diff
@@ -36,10 +36,31 @@ use crate::util::checksum;
 pub async fn info(flags: Flags, info_flags: InfoFlags) -> Result<(), AnyError> {
   let factory = CliFactory::from_flags(flags).await?;
   let cli_options = factory.cli_options();
-  if let Some(specifier) = info_flags.file {
+  if let Some(mut specifier) = info_flags.file {
     let module_graph_builder = factory.module_graph_builder().await?;
     let npm_resolver = factory.npm_resolver().await?;
     let maybe_lockfile = factory.maybe_lockfile();
+    let maybe_config_file = factory.cli_options().maybe_config_file();
```
Comment (dsherret) [inline cli/tools/info.rs:43]: See `factory.maybe_import_map()`. On there is a `.resolve(specifier, referrer)` function which can use `cli_options.initial_cwd()` as the referrer similar to line 64.

**Review by dsherret — CHANGES_REQUESTED** [review]
Thanks! It would be good to add a test for this in cli/tests/integration/info_tests.rs

File: cli/tools/info.rs (hunk 1 above)
Comment (vedant-pandey) [reply cli/tools/info.rs]: Thanks @dsherret the resolve function doesn't allow `cli_options.initial_cwd()` because it expects a type of `Url`, although this works with the new changes using `imports_map.base_url()`

**Comment by vedant-pandey** [comment]
Added the test

**Review by bartlomieju — APPROVED** [review]
LGTM, thanks for fixing this @vedant-pandey!
