### PR TITLE
fix(ext/node): `fs.stat` and `fs.statSync` compatibility

### LINKED ISSUE #30570: `npm:fs-extra`: Cannot copy/move 'X' to a subdirectory of itself, 'Y'.
Version: Deno 2.4.5
my repo on windows somehow not work and gets errors like this:
Cannot copy 'C:\Users\STEVE0~1\AppData\Local\Temp\fount_import_1756277197196\fount.json' to a subdirectory of itself, 'C:\Users\steve02081504\workstation\fount\data\users\steve02081504\chars\disco_ball\fount.json'.

see https://github.com/jprichardson/node-fs-extra/issues/1055 for more info, not sure is this an bug of deno or of package.

### PR DESCRIPTION
**Pull request by Tango992**
Closes #30570

Changes in this PR:
- Implement `ino`, `nlink`, and `blocks` properties of `Deno.FileInfo` on Windows. These changes are automatically reflected to the corresponding node stat function. In order to do so, I had to tinker with the [createByteStruct](https://github.com/denoland/deno/blob/a3a904da1450849b51c34a972db4fd9b9a572d29/ext/fs/30_fs.js#L297) function to create another optional int type, apart from `?u64`. It's common for small sized files on Windows (particularly NTFS file system) to have a `Stats.blocks` property of 0, and currently all 0 values with type `?u64` will be coerced into `null` by `createByteStruct`.
- Refactor the `BigIntStats` and `Stats` class, to use the same class with Node.js that are provided from [utils.mjs](https://github.com/denoland/deno/blob/7f8e488c3636e76f15bc1b33693e70b2ebf0593d/ext/node/polyfills/internal/fs/utils.mjs#L577). Also ensures that all properties are not `null` or `undefined`.
- Addresses the `prefer-primordials` lint rule.

### CODE REVIEW

File: ext/node/polyfills/internal/fs/utils.mjs [hunk 1]
```diff
@@ -508,6 +510,70 @@ function dateFromMs(ms) {
   return new Date(Number(ms) + 0.5);
 }
 
+const lazyDateFields = {
```
Comment (Tango992) [inline ext/node/polyfills/internal/fs/utils.mjs:513]: This is copied from the Node.js implementation https://github.com/nodejs/node/blob/96a749b7b3b9dfe982d8d0056122d0d601af6cf7/lib/internal/fs/utils.js#L446

Comment (Tango992) [inline ext/node/polyfills/internal/fs/utils.mjs:513]: This is copied from Node.js implementation https://github.com/nodejs/node/blob/96a749b7b3b9dfe982d8d0056122d0d601af6cf7/lib/internal/fs/utils.js#L446

**Comment by Tango992** [comment]
> Have you tried if any new tests are passing now?

Unfotunately no, but some tests almost pass:
- https://github.com/nodejs/node/blob/v24.2.0/test/parallel/test-fs-stat-date.mjs : Our stat function has `u64` type for file timestamps, thus will fail the test when it checks for negative timestamp value [L84-L88](https://github.com/nodejs/node/blob/591ba692bfe30408e6a67397e7d18bfa1b9c3561/test/parallel/test-fs-stat-date.mjs#L84-L88). Initially I wanted to make the fix on this PR, but I feel like it would be too big.
- https://github.com/nodejs/node/blob/v24.2.0/test/parallel/test-fs-stat.js: Failed on `fstat` invocation with `fd` value of 0 [L50](https://github.com/nodejs/node/blob/591ba692bfe30408e6a67397e7d18bfa1b9c3561/test/parallel/test-fs-stat.js#L50). On node it should be equivalent to stdin.
- https://github.com/nodejs/node/blob/v24.2.0/test/parallel/test-fs-stat-bigint.js: Failed on `fstat` invocation on [L142-L149](https://github.com/nodejs/node/blob/591ba692bfe30408e6a67397e7d18bfa1b9c3561/test/parallel/test-fs-stat-bigint.js#L142-L149) because we currently don't map the `Deno.errors.BadResource` error to the node equivalent.
