### PR TITLE
fix(unstable): Honor granular unstable flags in js runtime

### LINKED ISSUE #21434: Granular unstable feature flags appear ignored
Version: Deno 1.38.3

I added this entry to my `deno.jsonc`:

```json
"unstable": [
  "broadcast-channel",
  "ffi",
  "fs",
  "kv",
  "net",
  "http",
  "worker-options",
  "cron"
],
```

…and stopped passing `--unstable` to the CLI, but now I'm getting errors:

```
error: ReferenceError: BroadcastChannel is not defined
```

The schema only has:

```json
"unstable": {
  "type": "array",
  "description": "List of unstable features to enable.",
  "items": {
    "type": "string"
  }
}
```

The feature name `broadcast-channel` is correct according to the crate's source code, and from what I understand of the `feature_checker` code it should work.

Moreover, passing `--unstable-broadcast-channel` on the command line results in the exact same error.

Granular unstable feature flags appear ignored, either on the command line or in the configuration file.

### PR DESCRIPTION
**Pull request by jcayzac**
This fixes #21434 for `BroadcastChannel` and `WebSocketStream`. `--unstable` still enable both, but granular unstable flags now also work:

* `--unstable-net` now enables `WebSocketStream`.
* `--unstable-broadcast-channel` now enables `BroadcastChannel`.
* Additionally, there are now tests for all granular unstable flags. Since `unsafe-proto` already had tests, so I didn't add any for this one.

It also introduces a map to keep track of granular unstable ids without having to sync multiple places.

- [x] Ensure there are tests that cover the changes.
- [x] Ensure `cargo test` passes.
- [x] Ensure `./tools/format.js` passes without changing files.
- [x] Ensure `./tools/lint.js` passes.

### CODE REVIEW

**Comment by jcayzac** [comment]
cc @crowlKats @bartlomieju

File: runtime/js/99_main.js [hunk 1]
```diff
@@ -495,7 +495,24 @@ function bootstrapMainRuntime(runtimeOptions) {
...
   if (unstableFlag) {
-    ObjectDefineProperties(globalThis, unstableWindowOrWorkerGlobalScope);
+    ObjectDefineProperties(
+      globalThis,
+      Object.values(unstableKeyedFeaturesForWindowOrWorkerGlobalScope)
+        .reduceRight((feature, o) => Object.assign(o, feature), {}),
+    );
+  } else {
+    for (
+      const unstableFeature of Object.keys(
```
Comment (bartlomieju) [inline runtime/js/99_main.js:505]: These will not pass lint checks - you'll need to use "primordials" here - `ObjectValues`, `ObjectAssign` and `ObjectKeys`. I would also suggest to do a for loop instead of `reduceRight`, but not big deal.

Comment (jcayzac) [reply runtime/js/99_main.js]: Changed to use primordials.

**Comment by jcayzac** [comment]
I changed the keys to numbers since that's what in the `unstableFeatures` array. I had incorrectly assumed it was the same string identifiers as used in the crates.

**Comment by jcayzac** [comment]
@bartlomieju @crowlKats what do you think of https://github.com/jcayzac/deno/pull/1/files ? Should I add it to this PR?

**Comment by bartlomieju** [comment]
> @bartlomieju @crowlKats what do you think of https://github.com/jcayzac/deno/pull/1/files ? Should I add it to this PR?

That seems okay, but please put contents of `89_granular_flags.js` into `90_deno_ns.js` directly.

**Comment by bartlomieju** [comment]
Awesome work @jcayzac. Unfortunately we got some merge conflicts - would you be able to resolve them?

Also it would be great to add a regression test for this problem - maybe you could add a test to `cli/tests/integration/run_tests.rs` using `itest!` macro that adds all granular unstable flags, run a JavaScript file that `console.log()` various APIs that should be only available with these flags (eg. `BroadcastChannel`, `WebSocketStream`, `Deno.openKv`).

**Comment by jcayzac** [comment]
> Awesome work @jcayzac. Unfortunately we got some merge conflicts - would you be able to resolve them?

Yes, the features got reordered alphabetically in `main`. I just rebased and pushed everything again, including the other PR from my repo you commented upon earlier.

> Also it would be great to add a regression test for this problem - maybe you could add a test to `cli/tests/integration/run_tests.rs` using `itest!` macro that adds all granular unstable flags, run a JavaScript file that `console.log()` various APIs that should be only available with these flags (eg. `BroadcastChannel`, `WebSocketStream`, `Deno.openKv`).

I might need some help figuring out the best way to test invocations with different runtime options.

Unfortunately I'm still unable to have passing tests even in `main` on either of my two machines (Intel MBP and AMD PC), so I'll have to rely on CI to tell me if they pass there.

**Comment by jcayzac** [comment]
I have added tests for the flags. Please note that:

* `unsafe-proto` already had tests, so I didn't add any for this one.
* I couldn't find any unstable API for `http`, only unstable types and interfaces. I'm not sure how to implement tests around those.

**Comment by jcayzac** [comment]
@bartlomieju I really don't know what I'm doing wrong. Locally on my machine the tests I wrote don't pass and the build panics in the runtime, but I can't get the crash report to give me javascript line numbers that make sense. There seems to be an undefined somewhere, but I can't figure out how to debug the javascript runtime.

**Comment by jcayzac** [comment]
I think I resolved all the issues.

**Comment by littledivy** [comment]
Self note: run startup_time benchbot once CI passes

**Review by crowlKats — APPROVED** [review]
LGTM, thanks!
