### PR TITLE
fix: lazily surface errors in package.json deps parsing

### LINKED ISSUE #17941: Lazily surface package.json dependency entry errors
Right now if we error parsing the package.json’s dependency entries then we surface that error eagerly. We should do it lazily on first package.json dependency bare specifier match in the resolver. This will be less annoying because it won’t get in the way if the user isn’t using the package.json with Deno.

### PR DESCRIPTION
**Pull request by dsherret**
Closes #17941

### CODE REVIEW

File: cli/tests/testdata/package_json/invalid_value/error.ts.out [hunk 1]
```diff
@@ -0,0 +1,6 @@
+error: Parsing version constraints in the application-level package.json is more strict at the moment.
+
+Invalid npm specifier version requirement. Unexpected character.
+  invalid stuff that won't parse
+  ~
+    at file:///[WILDCARD]/error.ts:2:23
```
Comment (bartlomieju) [inline cli/tests/testdata/package_json/invalid_value/error.ts.out:6]: This got me confused - this string is not present in `error.ts:2:23` - it's present in the related package.json. Any chance this could be improved to point to the appropriate `package.json` file?

Comment (dsherret) [reply cli/tests/testdata/package_json/invalid_value/error.ts.out:6]: I'm not sure it's worth the effort mostly because we'll improve this over time to support more version constraints. Also, I don't think it will be so big of a deal for the user to figure out because the user will get a diagnostic at the bare specifier which is referenced in the package.json file. I think this just seems confusing because this test uses the string "invalid stuff that won't parse", but the user will see a version constraint like `1.2 - 1.4` or something like that, which should be more obvious.

**Review by bartlomieju — APPROVED** [review]
LGTM
