### PR TITLE
fix(ext/http): improve error message when underlying resource of request body unavailable

### LINKED ISSUE #27133: Inconsistent Handling of TCP Stream Closure Causes BadResource Error in Deno
Version: deno 2.1.1 (stable, release, x86_64-unknown-linux-gnu)

### `BadResource` Error with Deno's TCP Stream Handling

Deno throws a `BadResource: Bad resource ID` error with an unhelpful stack trace that does not point to the user's code. The error occurs when a TCP connection is closed before the request body is fully read. It depends on request size and the execution context:

- **When server and client run in the same script**: The error occurs consistently when the request size exceeds 512 bytes.
- **When server and client are in separate scripts**: The server can handle larger requests but still eventually throws the same error.

#### Steps to Reproduce

1. Create a Deno server that reads the request body in chunks using `ReadableStream.getReader()`.
2. Send a POST request with a total size exceeding 512 bytes.
3. Close the connection abruptly from the client after sending the request.

#### Code to Reproduce

```typescript
// Server
Deno.serve(async (req) => {
  console.log("Request received");

  const reader = req.body!.getReader();
  const decoder = new TextDecoder();
  let body = "";

  try {
    while (true) {
      console.log("Reading next chunk");
      const { done, value } = await reader.read();
      if (done) break;
      body += decoder.decode(value, { stream: true });
    }
  } catch (e) {
    console.error("Unexpected Error:", e);
    Deno.exit(0);
  }

  throw new Error("This should not be reached");
});

// Client
const REQUEST_SIZE = 513;
const contentLength = REQUEST_SIZE - 59 - REQUEST_SIZE.toString().length;
const body = "a".repeat(contentLength);
const request =
  `POST / HTTP/1.1\r\n` +
  `Host: 127.0.0.1:8000\r\n` +
  `Content-Length: ${contentLength}\r\n` +
  "\r\n" +
  body;

const connection = await Deno.connect({ hostname: "127.0.0.1", port: 8000 });
await connection.write(new TextEncoder().encode(request));
connection.close();
```

#### Observed Error

When the above code is executed (in a single script), the server logs the initial chunks but eventually throws the following error:

```
Unexpected Error: BadResource: Bad resource ID
    at Object.pull (ext:deno_web/06_streams.js:937:38)
    at Module.invokeCallbackFunction (ext:deno_webidl/00_webidl.js:1105:16)
    at ReadableByteStreamController.pullAlgorithm (ext:deno_web/06_streams.js:3558:14)
    at readableByteStreamControllerCallPullIfNeeded (ext:deno_web/06_streams.js:1233:49)
    at ext:deno_web/06_streams.js:1241:11
    at eventLoopTick (ext:core/01_core.js:175:7) {
  name: "BadResource"
}
```
#### Expected Behavior

1. The stack trace should point to the user's code causing the error.
2. The server should handle TCP connection closures consistently, irrespective of the request size.
3. The error message should be more meaningful.

#### Additional Information

I encountered this issue while investigating a related problem with Request.text() in Deno. I have filed a separate issue for that. These two issues may be connected. See #27132

### PR DESCRIPTION
**Pull request by kt3k**
This PR improves the error message when reading request body in `Deno.serve` and the underlying resource is unavailable.

The error message is currently `Bad Resource ID`. This PR change it to `Cannot read request body as underlying resource unavailable`

closes #27133

### CODE REVIEW

File: ext/http/00_serve.ts [hunk 1]
```diff
@@ -370,7 +370,25 @@ class InnerRequest {
...
     this.#streamRid = op_http_read_request_body(this.#external);
-    this.#body = new InnerBody(readableStreamForRid(this.#streamRid, false));
+    this.#body = new InnerBody(
+      readableStreamForRid(
+        this.#streamRid,
+        false,
+        undefined,
+        (controller, error) => {
+          if (ObjectPrototypeIsPrototypeOf(BadResourcePrototype, error)) {
+            // TODO(kt3k): We would like to pass `error` as `cause` when BadResource supports it.
```
Comment (bartlomieju) [inline ext/http/00_serve.ts:380]: Hm, shouldn't this be doable already?

**Review by bartlomieju — APPROVED** [review]

File: ext/http/00_serve.ts (hunk 1 above)
Comment (kt3k) [reply ext/http/00_serve.ts:380]: Doesn't look so as they are implemented like:

```js
  class BadResource extends Error {
    constructor(msg) {
      super(msg);
      this.name = "BadResource";
    }
  }
```
https://github.com/denoland/deno_core/blob/8d7bfea48ebfcaee989f8d72b243fb09302014f9/core/01_core.js#L302-L305

Comment (kt3k) [reply ext/http/00_serve.ts:380]: Created an issue in deno_core https://github.com/denoland/deno_core/issues/1031
