### PR TITLE
chore(tests): fix flaky flock tests

### LINKED ISSUE #12094: flock tests are flaky
Based on how the test is written, probably flockFileSync is flaky too.

```
error: Test failed
failures:

flockFileAsync
AssertionError: shared does not block shared
    at assertEquals (file:///D:/a/deno/deno/test_util/std/testing/asserts.ts:271:9)
    at flockFileAsync (file:///D:/a/deno/deno/cli/tests/unit/flock_test.ts:96:5)
    at async asyncOpSanitizer (deno:runtime/js/40_testing.js:35:9)
    at async resourceSanitizer (deno:runtime/js/40_testing.js:72:7)
    at async exitSanitizer (deno:runtime/js/40_testing.js:99:9)
    at async applyPermissions (deno:runtime/js/40_testing.js:124:9)
    at async runTest (deno:runtime/js/40_testing.js:215:7)
    at async Object.runTests (deno:runtime/js/40_testing.js:299:22)

failures:

	flockFileAsync
```

### PR DESCRIPTION
**Pull request by dsherret**
Closes #12094

### CODE REVIEW

File: cli/tests/unit/flock_test.ts [hunk 1]
```diff
@@ -1,102 +1,152 @@
...
-    const firstBlocksSecond = async (
-      first: boolean,
-      second: boolean,
-    ): Promise<boolean> => {
-      const firstPs = run(first, 1000);
-      await new Promise((res) => setTimeout(res, 250));
-      const start = performance.now();
-      const secondPs = run(second, 0);
-      await secondPs.status();
-      const didBlock = (performance.now() - start) > 500;
```
Comment (dsherret) [inline cli/tests/unit/flock_test.ts:25]: It's not reliable to do stuff like this on the CI. The fix below changes the code to signal and waits when it's at different parts of the code and records the time it enters and exits the locks to check if blocking occurred.

File: cli/tests/unit/flock_test.ts [hunk 2]
```diff
@@ -1,102 +1,152 @@
...
+
+    // wait for exit lock signal
+    await Deno.stdin.read(new Uint8Array(1));
+    const exitTime = new Date().getTime();
+
+    // wait a little bit before releasing the lock so that
+    // the enter time of the next process doesn't occur at the
+    // same time (do double the windows clock resolution)
+    await new Promise((resolve) => setTimeout(resolve, 30));
+    Deno.funlockSync(rid);
```
Comment (dsherret) [inline cli/tests/unit/flock_test.ts:123]: Oops. Will fix.

**Review by bartlomieju — APPROVED** [review]
LGTM
