### PR TITLE
fix(lsp): auto-import from npm package exports with manual node_modules

### LINKED ISSUE #28412: Auto-import quick fixes from `.../$node_modules/...`
Image

### PR DESCRIPTION
**Pull request by nayeemrmn**
Fixes #28412.

### CODE REVIEW

File: cli/lsp/resolver.rs [hunk 1]
```diff
@@ -218,7 +219,53 @@ impl LspScopeResolver {
...
+          let export_keys = dep_package_json
+            .as_ref()
+            .and_then(|p| p.exports.as_ref())
+            .into_iter()
+            .flat_map(|e| e.keys());
+          for export_key in export_keys {
+            let Some(export_suffix) = export_key.strip_prefix("./") else {
+              continue;
+            };
+            let name_and_export = format!("{name}/{export_suffix}");
```
Comment (dsherret) [inline cli/lsp/resolver.rs:239]: What happens if it contains a wildcard?

Comment (nayeemrmn) [reply cli/lsp/resolver.rs:239]: I might have to scan directories to support them, or skip them for now

Comment (dsherret) [reply cli/lsp/resolver.rs:239]: There's some code that does it in https://github.com/denoland/deno/pull/28131/files#diff-9cf4c6f84419e1517fd293cc725422ed4b17ce6c596fd0dc07bc6c1c95a6a671R1859 (I'm hesitant to keep working on that PR further atm, but it would make it work better with typescript).

Comment (nayeemrmn) [reply cli/lsp/resolver.rs]: I added a lookup cache in the node resolver, wildcard cases would fail to resolve here and use that logic instead.

File: resolvers/node/resolution.rs [hunk 2]
```diff
@@ -309,6 +321,20 @@ impl<
...
+        || specifier.starts_with("./")
+        || specifier.starts_with("../")
+        || specifier.starts_with("/")
+      {
+        return None;
+      }
+      let url = url_or_path.clone().into_url().ok()?;
+      package_resolution_lookup_cache.insert(url, specifier.to_string());
+      Some(())
+    })();
```
Comment (dsherret) [inline resolvers/node/resolution.rs:337]: Not too big of a fan of these IIFEs. I find it harder to follow along than if statements or extracting out a method/function.

File: cli/lsp/resolver.rs [hunk 3]
```diff
@@ -655,6 +627,105 @@ pub struct ScopeDepInfo {
...
+        .as_ref()
+        .and_then(|p| p.exports.as_ref())
+        .into_iter()
+        .flat_map(|e| e.keys());
+      for export_key in export_keys {
+        let Some(export_name) = export_key.strip_prefix("./") else {
+          continue;
+        };
+        // Wildcards are not supported here.
+        if export_name.chars().filter(|c| *c == '*').count() == 1 {
```
Comment (dsherret) [inline cli/lsp/resolver.rs:688]: Why .count() == 1?

**Review by dsherret — APPROVED** [review]
LGTM

File: cli/lsp/resolver.rs (hunk 3 above)
Comment (nayeemrmn) [reply cli/lsp/resolver.rs:688]: I played around with exports and it seems like multiple `*` don't count as wildcards in our resolution, e.g. `foo/*/bar/*` doesn't match `foo/x/bar/*`, `foo/*/bar/x` or `foo/x/bar/x`.

File: resolvers/node/resolution.rs (hunk 2 above)
Comment (nayeemrmn) [reply resolvers/node/resolution.rs]: > I find it harder to follow along than if statements or extracting out a method/function.

I agree for reading but they're soooo easy to write 😄 Maybe at least naming the closure is more idiomatic.
