### PR TITLE
fix(check): don't detect tsconfigs with no deno.json/package.json or --no-config

### LINKED ISSUE #29922: tsconfig.json should not be discovered when providing `--no-config`
1. Need to respect `--no-config`
2. Revert to previous behaviour of only checking the fs for tsconfig.json when there's a package.json or deno.json in the workspace.

Version: canary

### PR DESCRIPTION
**Pull request by nayeemrmn**
Fixes #29922.

### CODE REVIEW

File: libs/resolver/deno_json.rs [hunk 1]
```diff
@@ -662,7 +680,9 @@ impl CompilerOptionsResolver {
     let mut ts_config_collector =
       TsConfigCollector::new(sys, node_resolver, &logged_warnings);
     for (dir_url, dir) in workspace_directory_provider.entries() {
-      ts_config_collector.add_root(dir.dir_path().join("tsconfig.json"));
+      if dir.has_deno_or_pkg_json() {
```
Comment (dsherret) [inline libs/resolver/deno_json.rs:683]: One thing I just realized is I think we really just have to do this because `dir.has_deno_or_pkg_json()` will always be false when `config_discover == ConfigDiscoverOption::Disabled`.

**Review by dsherret — APPROVED** [review]
LGTM. Thanks!

File: cli/tools/publish/module_content.rs [hunk 2]
```diff
@@ -415,27 +404,8 @@ mod test {
...
-      NodeResolutionSys::new(sys.clone(), None),
-      NodeResolverOptions::default(),
-    );
-    let compiler_options_resolver = Arc::new(CompilerOptionsResolver::new(
-      &sys,
-      &WorkspaceDirectoryProvider::from_initial_dir(&Arc::new(workspace_dir)),
-      &node_resolver,
-    ));
+    let compiler_options_resolver =
+      Arc::new(CompilerOptionsResolver::default());
```
Comment (dsherret) [inline cli/tools/publish/module_content.rs]: I think this change broke the test.
