### PR TITLE
Ensure global type instances are available.

### LINKED ISSUE #1173: Headers type not available
Adding the following to `js/headers_test.ts` break it
```typescript
test(function headerTypesAvailable() {
  function newHeaders(): Headers {
    return new Headers();
  }
  const headers = newHeaders();
  assert(headers instanceof Headers);
});
```
Results in the following error:
```
> ./out/debug/deno  js/headers_test.ts
Compiling /Users/rld/src/deno/js/headers_test.ts
/Users/rld/src/deno/js/headers_test.ts:176:26 - error TS2304: Cannot find name 'Headers'.

176   function newHeaders(): Headers {
                             ~~~~~~~
```

### PR DESCRIPTION
**Pull request by kitsonk**
Fixes #1173 

It also cleans up a few things related to the `globals.ts` and provides more comments to help guide additions to the file.

### CODE REVIEW

**Comment by kitsonk** [comment]
@ry done

File: js/repl.ts [hunk 1]
```diff
@@ -6,7 +6,9 @@ import * as deno from "./deno";
 import { close } from "./files";
 import * as dispatch from "./dispatch";
 import { exit } from "./os";
-import { window } from "./globals";
+import { globalEval } from "./global_eval";
+
+const window = globalEval("this");
```
Comment (bartlomieju) [inline js/repl.ts]: doing that won't cause window to miss all properties assigned to it in `globals.ts`? I think we would like to use most of them in REPL

Comment (ry) [reply js/repl.ts]: Valid question ... However, I'm going to land this anyway because I need the fix and because this is passing the tests. If this indeed breaks `window` properties, we should add tests that nail that behavior down.

Comment (bartlomieju) [reply js/repl.ts]: It doesn't just rebased it against my REPL branch and everything works as expected.
