### PR TITLE
fix(node): throw ERR_INVALID_ARG_TYPE for invalid fs.readFile path

### LINKED ISSUE #31866: `node:fs` does not throw exception for `readFile`
## Version

deno 2.6.5 (stable, release, x86_64-unknown-linux-gnu)

v8 14.2.231.17-rusty

typescript 5.9.2

## Steps to reproduce

1. Create file `test.js` with the following content:
```js
import { readFile } from 'node:fs';
import { open } from 'node:fs/promises';

const fd = await open('README.md','r');

readFile(fd.name, (err, buf) => {
  console.log(fd.name);
});
```
2. Run the file like `deno -A test.js`.

## Expected Behaviour
Node.js throw a TypeError exception on line 6, where readFile is used
```js
node:fs:381
  binding.open(getValidatedPath(path), flagsNumber, 0o666, req);
               ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received undefined
    at readFile (node:fs:381:16)
    at file:///folder-structure/test.js:6:1 {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

## Actual Behaviour
Deno executes the console.log, and outputs `undefined`

## Additional Information
The file `README.md` is a non empty file in the same folder as the script that I am running.

### PR DESCRIPTION
**Pull request by MaheshThakur9152**
Validate path argument in readFile/readFileSync to match Node.js behavior and add tests for callback/sync/fd.name undefined cases

**Summary**
This patch ensures `fs.readFile` and `fs.readFileSync` validate the `path` argument synchronously and throw a `TypeError` with code `ERR_INVALID_ARG_TYPE` for invalid or missing paths (for example, when passing `fd.name` which is `undefined`). This matches Node.js behavior and prevents silent undefined path usage that previously led to unexpected behavior.

**Related issue**
Fixes #31866

**What I changed**
- _fs_readFile.ts
  - Added import of `ERR_INVALID_ARG_TYPE`.
  - Added synchronous validation for `path` in `readFile` and `readFileSync` to throw when `path` is not a valid type (string, Buffer, URL, number, or FileHandle where applicable).
- _fs_readFile_test.ts
  - Added tests covering:
    - `readFile(undefined, cb)` throws `ERR_INVALID_ARG_TYPE` and does not call the callback.
    - `readFileSync()` throws `ERR_INVALID_ARG_TYPE`.
    - `readFile((fh as any).name, cb)` where `fd.name` is `undefined`, asserting it throws.

**Why**
- Matches Node.js semantics (synchronous validation + ERR_INVALID_ARG_TYPE) so code using Node-style APIs behaves the same on Deno.
- Prevents subtle bugs where `undefined` path would silently be handled leading to incorrect behavior.

**How to test locally**
1. Run the unit tests added/modified:
   - `deno test tests/unit_node/_fs/_fs_readFile_test.ts -A`
2. Run repository checks:
   - npm/deno-based format check.
   - Lint check.

**Notes for reviewers**
- This is a small, focused change limited to input validation and tests — no large refactorings.
- Tests assert both behavior (throwing) and that callbacks are not invoked when the call throws synchronously.
- If maintainers prefer slightly different accepted types for `path` (e.g., Buffer semantics), I can adjust the validation to match their preference.

### CODE REVIEW

File: ext/node/polyfills/_fs/_fs_readFile.ts
Comment (Tango992) [inline ext/node/polyfills/_fs/_fs_readFile.ts:1]: We have a function to validate paths:

```js
import { getValidatedPathToString } from "ext:deno_node/internal/fs/utils.mjs";
```

Since the path could also be a `FileHandle`, you could make a function that checks whether path is an instance of `FileHandle` , or pass it to the `getValidatedPathToString()`. Then let `readFileAsync` and `readFile` to call that function.

File: tests/unit_node/_fs/_fs_readFile_test.ts [hunk 1]
```diff
@@ -204,6 +204,40 @@ Deno.test("fs.readFile creates new file when passed 'w+' flag", async () => {
   Deno.removeSync(tmpDir, { recursive: true });
 });
 
+Deno.test(
+  "fs.readFile throws ERR_INVALID_ARG_TYPE when path is undefined (e.g. fd.name)",
+  async () => {
+    const { open } = await import("node:fs/promises");
```
Comment (Tango992) [inline tests/unit_node/_fs/_fs_readFile_test.ts]: We could move this to top level import instead

File: tests/unit_node/_fs/_fs_readFile_test.ts [hunk 2]
```diff
@@ -204,6 +204,40 @@ Deno.test("fs.readFile creates new file when passed 'w+' flag", async () => {
...
+        readFile(name as unknown as string, () => {});
+      } catch (err) {
+        threw = true;
+        // Ensure it's the node-style error
+        assert(err instanceof Error);
+        // The internal error class sets the code to ERR_INVALID_ARG_TYPE
+        // deno-lint-ignore no-explicit-any
+        assertEquals((err as any).code, "ERR_INVALID_ARG_TYPE");
+      }
+      assert(threw, "readFile did not throw for undefined path");
```
Comment (Tango992) [inline tests/unit_node/_fs/_fs_readFile_test.ts]: I'd say to replace this and use `readFile` from `node:fs/promises` instead. Then you could check the error thrown using `assertRejects()` similar to what you did on the sync version.

Comment (MaheshThakur9152) [reply tests/unit_node/_fs/_fs_readFile_test.ts]: @Tango992 Thanks for the review! I've updated the PR with your suggestions:

1. **Refactored `_fs_readFile.ts`**: Now uses the internal `getValidatedPathToString` helper for validation instead of manual checks.
2. **Updated Tests**: 
   - Moved `open` to top-level imports.
   - Switched the test case to use `node:fs/promises` and `assertRejects` for cleaner error assertion.
   - Verified `ERR_INVALID_ARG_TYPE` is thrown correctly.

Lint and formatting checks passed locally. Ready for another look!
