### PR TITLE
fix(repl): Fix `undefined` result colour in cmd

### LINKED ISSUE #9761: Windows does not highlight undefined in REPL
In deno REPL, only the code becomes the highlight, so it would be nice to apply the result value as well.

deno:
image

### PR DESCRIPTION
**Pull request by dsherret**
**Before**

Command prompt:

image

Windows terminal:

image

**After**

Command prompt:

image

Windows terminal:

image

Highlighting for `undefined` in the Rust and JS code now both use "grey" instead of "dim" and "grey".

Fixes #9761

### CODE REVIEW

File: extensions/console/02_console.js [hunk 1]
```diff
@@ -599,7 +599,7 @@
           }
           const emptyItems = i - index;
           const ending = emptyItems > 1 ? "s" : "";
-          return dim(`<${emptyItems} empty item${ending}>`);
+          return gray(`<${emptyItems} empty item${ending}>`);
```
Comment (dsherret) [inline extensions/console/02_console.js:602]: I think it's better that we just don't use `dim` since it doesn't work in cmd and instead use `gray`, so I've changed this as well. This is the only other occurence of using `dim` in the code.

File: extensions/console/01_colors.js [hunk 2]
```diff
@@ -55,10 +55,6 @@
     return run(str, code(35, 39));
   }
 
-  function dim(str) {
-    return run(str, code(2, 22));
-  }
```
Comment (dsherret) [inline extensions/console/01_colors.js:60]: I think it's better that we just don't use dim since it doesn't work in cmd and instead use gray. I've removed this, but let me know if I should re-add it.

**Review by ry — COMMENTED** [review]
Does it still look ok when terminal is black on white?

**Comment by dsherret** [comment]
> Does it still look ok when terminal is black on white?

Yup (cmd):

image

**Review by ry — APPROVED** [review]
Lgtm
