### PR TITLE
fix(npm): run pre and post tasks if present

### LINKED ISSUE #19157: [npm] Pre and post scripts are not executed
npm docs: https://docs.npmjs.com/cli/v9/using-npm/scripts#pre--post-scripts 

## Steps to reproduce

1. Create a `package.json` file with the following content:
```json
{
  "scripts": {
    "pretest": "echo 'pretest'",
    "posttest": "echo 'posttest'",
    "test": "echo 'test'"
  }
}
```
2. Run `deno task test`.

## Output

`deno task test` output:

```sh
Warning Currently only basic package.json `scripts` are supported. Programs like `rimraf` or `cross-env` will not work correctly. This will be fixed in an upcoming release.
Task test echo 'test'
test
```

`npm run test` output:

```sh

> pretest
> echo 'pretest'

pretest

> test
> echo 'test'

test

> posttest
> echo 'posttest'

posttest
```

### PR DESCRIPTION
**Pull request by marvinhagemeister**
This PR optionally runs pre and posts tasks from `package.json` if available.

Fixes #19157

### CODE REVIEW

**Review by amantank — APPROVED** [review]

**Comment by marvinhagemeister** [comment]
Amended a couple more test cases.

File: cli/tools/task.rs [hunk 1]
```diff
@@ -105,24 +106,85 @@ pub async fn execute_script(
...
-    let env_vars = collect_env_vars();
-    let local = LocalSet::new();
-    let future =
-      deno_task_shell::execute(seq_list, env_vars, &cwd, npx_commands);
-    let exit_code = local.run_until(future).await;
-    Ok(exit_code)
+
+    let mut pre_task_name: String = "pre".to_owned();
+    pre_task_name.push_str(task_name);
+    if let Some(pre_script) = package_json_scripts.get(&pre_task_name) {
```
Comment (bartlomieju) [inline cli/tools/task.rs:112]: If you run `npm run pretest` does it try to run `prepretest`?

File: cli/tools/task.rs [hunk 2]
```diff
@@ -105,24 +106,85 @@ pub async fn execute_script(
...
+        cli_options,
+        &cwd,
+        npm_resolver,
+        node_resolver,
+      )
+      .await?;
+
+      if exit_code > 0 {
+        return Ok(exit_code);
+      }
```
Comment (dsherret) [inline cli/tools/task.rs:157]: These three code blocks are very similar. Perhaps instead we could build up a vector of task_names then iterate through them?

```rs
let task_names = vec![format!("pre{}", task_name"), task_name.clone(), format!("post{}", task_name)];
for task_name in task_names {
  if let Some(script) = package_json_scripts.get(&task_name) {
      // ...
  }
}
```

Comment (bartlomieju) [reply cli/tools/task.rs:157]: Shouldn't we try to run `pre-` and `post-` task only if the requested task actually is defined?

**Comment by marvinhagemeister** [comment]
@bartlomieju the changes in this PR only affect scripts from `package.json` because they're guarded by an earlier check here https://github.com/denoland/deno/pull/19178/files#diff-25b821ac9f791d719c4d772c106c89752c2da633d53159d615e048990ccc9613L68 Happy to add tests that it doesn't affect tasks from `deno.json` nonetheless.

File: cli/tools/task.rs (hunk 1 above)
Comment (marvinhagemeister) [reply cli/tools/task.rs:112]: Yup npm will try to run `prepretest` if it's available.

```json
{
  "scripts": {
    "prepretest": "echo 'prepretest'",
    "pretest": "echo 'pretest'",
    "posttest": "echo 'posttest'",
    "test": "echo 'test'"
  }
}
```

Output:

```sh
$ npm run pretest

> prepretest
> echo 'prepretest'

prepretest

> pretest
> echo 'pretest'

pretest
```

File: cli/tools/task.rs (hunk 2 above)
Comment (dsherret) [reply cli/tools/task.rs:157]: That's what `if let Some(script) = package_json_scripts.get(&task_name) {` is for :)

Comment (marvinhagemeister) [reply cli/tools/task.rs:157]: This is great feedback! I wasn't sure if rust folks prefer to use the `format!` macro for string concatenation or not.

Comment (marvinhagemeister) [reply cli/tools/task.rs:132]: @dsherret Alright, updated the code with your suggestions. They make the code much more concise compared to what I had before. Thanks again for the feedback 👍

**Review by amantank — APPROVED** [review]

**Review by dsherret — APPROVED** [review]
LGTM. Thanks, @marvinhagemeister!
