### PR TITLE
fix(ext/node): crypto `Cipheriv` and `Decipheriv` base64 encoding

### LINKED ISSUE #30722: Incorrect base64 output when encrypting strings using `node:crypto`
Version: Deno 2.4.5

Test Code:

```
import { createCipheriv, createDecipheriv, createHash, randomBytes } from 'node:crypto';
import { Buffer } from 'node:buffer';

function aes256Encrypt(plaintext: string, key: string): string {
  const hash = createHash('sha256').update(key).digest();
  const iv = randomBytes(16); // AES block size is 16 bytes
  const cipher = createCipheriv('aes-256-cbc', hash, iv);

  let encrypted = cipher.update(plaintext, 'utf8', 'base64');
  encrypted += cipher.final('base64');

  return iv.toString('base64') + '.' + encrypted;
}

function aes256Decrypt(encryptedText: string, key: string): string {
  const hash = createHash('sha256').update(key).digest();
  const [ivPart, encryptedPart] = encryptedText.split('.');

  if (!ivPart || !encryptedPart) {
    throw new Error("Invalid encrypted text format");
  }

  const iv = Buffer.from(ivPart, 'base64');
  const decipher = createDecipheriv('aes-256-cbc', hash, iv);

  let decrypted = decipher.update(encryptedPart, 'base64', 'utf8');
  decrypted += decipher.final('utf8');

  return decrypted;
}

const key = 'Kyd4UQNkBXMW7GLJ3IzdvO4l6cTQP9wA';
const ciphertext = aes256Encrypt(
  '{"system":{"uptime":16698013,"timestamp":1757914230428},"load":{"load1":0.33251953125,"load5":0.166015625,"load15":0.11181640625,"cores":2},"memory":{"totalBytes":1981030400,"usedBytes":1264984064},"disk":[],"backup":[{"projectName":"test","databaseFiles":[]}]}',
  key,
);
console.log(ciphertext);
console.log(aes256Decrypt(ciphertext, key));
```

Run with deno:
```
$ deno run src/test.ts
FdGkPm3v2gdwkP+iLUwDDQ==.E1+njwPkEcwjOfvx5s3VwaBLgRno2bDHNrcN5HMyhk07L53yjTF1NzAsMDZxo0Q+RTVP/CZv5I2t22gsrMonacc81yZrbvkhi6pzQryTDGsqDHRAVznDFxMVHQ4DoGwU2UfMDT8Ig0vCGFgrvALJ3/pM8Q+2DnH0zwO2PPXDBF2Kd3y6YqBWhOi5x5tm9SXkN7TuMUHsrLuXv0CKAJjlu+SG+04i5NQceVtZH8lJp2KCIDazgxLx+eb8p4y/ZhPjgS0KY/0EKX/rgWoDouxKQ4aYPDftN0eESb9sIzRNBHwfF0WDPLsZg056ZOPR6tTAtO6c3SpZnTUsmfH8MXj32w==NexdkxlV5GA+DWLF+ULBYA==
error: Uncaught (in promise) TypeError: bad decrypt
  decrypted += decipher.final('utf8');
                        ^
    at Decipheriv.final (ext:deno_node/internal/crypto/cipher.ts:193:5)
    at aes256Decrypt (file:///Volumes/Development/Novsatis/owl/src/test.ts:27:25)
    at file:///Volumes/Development/Novsatis/owl/src/test.ts:38:13
```
look at the end of encrypted string, end with: ==NexdkxlV5GA+DWLF+ULBYA==
It seems  `cipher.update(plaintext, 'utf8', 'base64')` get a string end with `==` then, `decipher.final('utf8')` get a string end with `==` again.

Save code run in node without problem.
```
$ node src/test.js
7MNGlnZg/e52ER8QSlJW8w==.68LTLqM4fnxNbf9lqfQM4vkWZ/YeMH4eqUMqexRnDhBV6+osJeGoNqaqs9hpawghHYSVslpgFYVtmSICwayS0Fqc8MqWnjMpBH2NmbSsZD5C++tMl8Y+SeIv6i1JOM0jvD9ATZVI0ZzIfsLj6Djms+aNJEQi5+buVAOAHQgmZr+eObJIOriXxXdTY/9y1UC7kUV4Xt+N2NoNdvC3zZbRkeQa5xeWhePMiKPFWvLWmTDTbg3Q4k6Bpy2ygtiEHx19yakZwJOLJfPmrfkDUu88+HpW861djrcmw1fEtpeWV07ukHKCrOCfcl7C9x6/X+5NaGw3pSf/4/74KamHJk35jCcVQ3zuZIuOtpeIRv1dWGQ=
{"system":{"uptime":16698013,"timestamp":1757914230428},"load":{"load1":0.33251953125,"load5":0.166015625,"load15":0.11181640625,"cores":2},"memory":{"totalBytes":1981030400,"usedBytes":1264984064},"disk":[],"backup":[{"projectName":"test","databaseFiles":[]}]}
```

### PR DESCRIPTION
**Pull request by Tango992**
Fixes #30722

The root cause comes from the `.update()` and `.final()` methods of `Cipheriv` and `Decipheriv`, which internally calls `.toString()` method of Buffer. Doing so adds padding to make the output length a multiple of 4, which we don't want for this case. This PR replaces that to use `StringDecoder` instead, making it more aligned with the Node.js implementation.

### CODE REVIEW

File: tests/unit_node/crypto/crypto_cipher_gcm_test.ts
Comment (Tango992) [inline tests/unit_node/crypto/crypto_cipher_gcm_test.ts:1]: The changes were needed to match these upon assertion, because now the base64 encoded result doesn't contain paddings.

https://github.com/denoland/deno/blob/6971df68a6cca9b7e71504b1414415d685431122/tests/unit_node/crypto/crypto_cipher_gcm_test.ts#L76-L77

File: ext/node/polyfills/internal/crypto/cipher.ts [hunk 1]
```diff
@@ -481,9 +507,28 @@ export class Decipheriv extends Transform implements Cipher {
...
-      : output.toString(outputEncoding);
+
+    if (outputEncoding !== "buffer") {
+      return this.#decoder!.write(output);
+    }
+
+    return output;
+  }
+
+  #lazyInitDecoder(encoding: string) {
```
Comment (Tango992) [inline ext/node/polyfills/internal/crypto/cipher.ts:518]: Based on https://github.com/nodejs/node/blob/3e79dba4a44316f567da36cfce7df0a7d0811041/lib/internal/crypto/cipher.js#L93-L103
