### PR TITLE
fix(vendor): ignore import map in output directory instead of erroring

### LINKED ISSUE #14899: Cannot update the vendored modules when import map is in output directory
As of Deno v1.23.0, the vendor command modifies the configuration file, to the import-map to `vendor/import_map.json`. Deno will then complain if the user tries to update the vendored modules.

```console
$ deno vendor ./_config.js -f
error: Specifying an import map file (vendor/import_map.json) in the deno vendor output directory is not supported. Please specify no import map or one located outside this directory.
```

This isn't a problem in v1.22.3, since the `deno.json` config file isn't modified.

**Notes**
- Yes, I tested this on both v1.23.0 and v1.22.3
- I have a hunch that this comes from https://github.com/denoland/deno/pull/14836

### PR DESCRIPTION
**Pull request by dsherret**
This ignores an import map specified in the output directory instead of erroring.

Closes #14899

### CODE REVIEW

File: cli/args/mod.rs [hunk 1]
```diff
@@ -122,6 +122,14 @@ impl RootConfig {
     )
   }
 
+  /// Removes the import map from the configuration.
+  pub fn remove_import_map(&mut self) {
```
Comment (bartlomieju) [inline cli/args/mod.rs:126]: Oh? This seems a bit strange to me, we are we modifying configuration from the process?

Comment (dsherret) [reply cli/args/mod.rs:126]: I need to ensure that the import map is not used for anything. An easy way to do that is to modify this configuration to not specify it and then use this mutated configuration that doesn't specify an import map to build everything.

Actually, maybe `RootOptions` might have been a better name than `RootConfig`?

Comment (dsherret) [reply cli/args/mod.rs:126]: I'll change this name to `clear_import_map`

Comment (bartlomieju) [reply cli/args/mod.rs]: > I need to ensure that the import map is not used for anything. An easy way to do that is to modify this configuration to not specify it and then use this mutated configuration that doesn't specify an import map to build everything.

Ok 👍 

> Actually, maybe `RootOptions` might have been a better name than `RootConfig`?

Yes, I think that might be a better name. Maybe `CliOptions` would be better?

Comment (dsherret) [reply cli/args/mod.rs]: > Yes, I think that might be a better name. Maybe CliOptions would be better?

Ok, I like `CliOptions`. I can do another PR after this one that renames it.

Comment (dsherret) [reply cli/args/mod.rs]: By the way, this lazily constructs the results by hiding the flags and config file inside the struct, but perhaps it would be more straightforward if this resolved and inline everything necessary when it's constructed. The one issue is that sometimes people might want to know if something came from a flag or from the config file.

Comment (bartlomieju) [reply cli/args/mod.rs]: > By the way, this lazily constructs the results by hiding the flags and config file inside the struct, but perhaps it would be more straightforward if this resolved and inlined everything necessary when it's constructed. The one issue is that sometimes people might want to know if something came from a flag or from the config file.

I think it should evaluate eagerly. Can you suggest one such situation?

Comment (dsherret) [reply cli/args/mod.rs]: I'll see when I go to work on it. I don't think it's necessary, but this was a decent stepping stone.

Comment (dsherret) [reply cli/args/mod.rs]: So, one nice thing about doing it lazily is that we can surface errors only when necessary and can ignore errors in certain scenarios. For example, only displaying task errors when running a deno task or when using watch we could display an error about a certain part not working, but still continue execution.

Comment (dsherret) [reply cli/args/mod.rs]: It already works lazily. Changing it to not be lazy could open a can of worms of more errors happening.

Comment (dsherret) [reply cli/args/mod.rs]: @bartlomieju I added an "overrides" instead of clearing out the underlying structure. Let me know if this looks better than before.

File: cli/args/mod.rs [hunk 2]
```diff
@@ -44,13 +44,19 @@ use crate::file_fetcher::CacheSetting;
 use crate::lockfile::Lockfile;
 use crate::version;
 
+#[derive(Default)]
+struct CliOptionOverrides {
```
Comment (bartlomieju) [inline cli/args/mod.rs:48]: Seems good 👍 could use a doctring

**Review by bartlomieju — APPROVED** [review]
LGTM
