### PR TITLE
fix(serde_v8): more robust number deserialization

### LINKED ISSUE #14128: op panic when attempting to use an unsafe pointer
meta:
```
deno 1.20.3 (release, x86_64-unknown-linux-gnu)
v8 10.0.139.6
typescript 4.6.2
```
code
```ts
const mem = Deno.makeTempFileSync();

const ankor = new TextEncoder().encode(
  "",
);
const ankorAddr = Deno.UnsafePointer.of(ankor);

Deno.seekSync(mem.rid, ankorAddr, Deno.SeekMode.Start); // to fix the panic replace ankorAddr with Number(ankorAddr)
```
panic:
```
============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: linux x86_64
Version: 1.20.3
Args: ["deno", "run", "-A", "--unstable", "b.js"]

thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/runner/work/deno/deno/serde_v8/de.rs:154:3
stack backtrace:
   0:     0x5606f5d4126c - std::backtrace_rs::backtrace::libunwind::trace::h91c465e73bf6c785
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x5606f5d4126c - std::backtrace_rs::backtrace::trace_unsynchronized::hae9da36f5d58b5f3
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x5606f5d4126c - std::sys_common::backtrace::_print_fmt::h7f499fa126a7effb
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x5606f5d4126c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h3e2b509ce2ce6007
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x5606f5d6f4cc - core::fmt::write::h753c7571fa063ecb
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/fmt/mod.rs:1168:17
   5:     0x5606f5d36a43 - std::io::Write::write_fmt::h2815c0519c99ba09
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/io/mod.rs:1660:15
   6:     0x5606f5d44082 - std::sys_common::backtrace::_print::h64941a6fc8b0ed9b
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x5606f5d44082 - std::sys_common::backtrace::print::hcf25e43e1a9b0766
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x5606f5d44082 - std::panicking::default_hook::{{closure}}::h78d3e6cf97fc623d
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:211:50
   9:     0x5606f5d43c65 - std::panicking::default_hook::hda898f8d3ad1a5ae
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:228:9
  10:     0x5606f5fd825e - deno::setup_panic_hook::{{closure}}::h27904fd79cbabeea
  11:     0x5606f5d447f5 - std::panicking::rust_panic_with_hook::h1a5ea2d6c23051aa
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:610:17
  12:     0x5606f5d444c2 - std::panicking::begin_panic_handler::{{closure}}::h07f549390938b73f
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:500:13
  13:     0x5606f5d41714 - std::sys_common::backtrace::__rust_end_short_backtrace::h5ec3758a92cfb00d
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/sys_common/backtrace.rs:139:18
  14:     0x5606f5d44229 - rust_begin_unwind
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:498:5
  15:     0x5606f5d6ccf1 - core::panicking::panic_fmt::h3a79a6a99affe1d5
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panicking.rs:116:14
  16:     0x5606f5d6cbbd - core::panicking::panic::h97167cd315d19cd4
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panicking.rs:48:5
  17:     0x5606f6332254 - serde_v8::de::from_v8::h1b0b06ab6b687dc3
  18:     0x5606f6476e19 - <extern "C" fn(A0) .> R as v8::support::CFnFrom<F>>::mapping::c_fn::h0f8e1a710646184d
  19:     0x5606f4f88156 - _ZN2v88internal25FunctionCallbackArguments4CallENS0_15CallHandlerInfoE
                               at ./../../../../v8/src/api/api-arguments-inl.h:152:3
  20:     0x5606f4f87b8a - _ZN2v88internal12_GLOBAL__N_119HandleApiCallHelperILb0EEENS0_11MaybeHandleINS0_6ObjectEEEPNS0_7IsolateENS0_6HandleINS0_10HeapObjectEEESA_NS8_INS0_20FunctionTemplateInfoEEENS8_IS4_EENS0_16BuiltinArgumentsE
                               at ./../../../../v8/src/builtins/builtins-api.cc:112:36
  21:     0x5606f4f870cb - _ZN2v88internal21Builtin_HandleApiCallEiPmPNS0_7IsolateE
                               at ./../../../../v8/src/builtins/builtins-api.cc:130:1
  22:     0x5606f5c42e78 - Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_BuiltinExit

```

### PR DESCRIPTION
**Pull request by AaronO**
Fixes #14128

**Note:** we may want to return out-of-range errors, for now I've preserved the saturating behaviour (which wasn't previously consistent ...)

### CODE REVIEW

**Comment by andreubotella** [comment]
For `f32` and `f64`, bigints which are out of the range of `i64` will be first truncated to fit in `i64` and then converted to a float, even if they're a number representable in the float type.

**Review by bartlomieju — APPROVED** [review]
LGTM, nice tests

**Review by lucacasonato — COMMENTED** [review]
Don't you think it'd make more sense to throw than to truncate? Truncating silently seems like it might cause hard to debug issues in the future.

File: serde_v8/de.rs [hunk 1]
```diff
@@ -615,3 +637,22 @@ impl<'de, 'a, 'b, 's> de::VariantAccess<'de>
     de::Deserializer::deserialize_struct(&mut d, "", fields, visitor)
   }
 }
+
+fn bigint_to_f64(b: v8::Local<v8::BigInt>) -> f64 {
```
Comment (lucacasonato) [inline serde_v8/de.rs:641]: This seems questionable. Can a JS number not already represent all values in an `f64`?

Comment (AaronO) [reply serde_v8/de.rs:641]: Yep, JS numbers are effectively doubles/f64s (sometimes SMIs) but this makes sense if we're being "permissive" in the inputs and want to allow deserializing a BigInt to an f64

Comment (lucacasonato) [reply serde_v8/de.rs:641]: I don't think we want to allow this though. It seems that in 99% of cases this will hide a user mistake. People don't use BigInt to store f64s.

Comment (AaronO) [reply serde_v8/de.rs:641]: > I don't think we want to allow this though. It seems that in 99% of cases this will hide a user mistake. People don't use BigInt to store f64s.

I don't disagree, it links back to the broader question if we want serde_v8 to be very strict or permissive, should it coerce implicitly or error instead.

Usually for the op-layer stricter is better

**Comment by AaronO** [comment]
> Don't you think it'd make more sense to throw than to truncate? Truncating silently seems like it might cause hard to debug issues in the future.

We aren't technically truncating but saturating, which was our previous behaviour except it's now consistent/correct and tested.

So this is already a good improvement over the present with no breaking change in intended behaviour. Erroring on OOB numbers would be sane IMO but we should discuss that as part of a broader topic of serde_v8/op-layer strictness.
