### PR TITLE
fix(cli/web): fix atob to throw DOMException

### LINKED ISSUE #8795: atob should throw DOMException
`atob('foobar!!')` returns a `DOMException` in chrome, but it returns a `DataDecodeError` in Deno. This should be aligned to match Chrome behaviour.

### PR DESCRIPTION
**Pull request by gorogoroumaru**
fix #8795 

atob('foobar!!') returns a DOMException in chrome, but it returns a DataDecodeError in Deno.
I fixed atob function to throw DOMException instead of DataDecodeError.

### CODE REVIEW

File: cli/tests/unit/text_encoding_test.ts [hunk 1]
```diff
@@ -50,6 +50,16 @@ unitTest(function atobThrows2(): void {
   assert(threw);
 });
 
+unitTest(function atobThrows3(): void {
+  let threw = false;
+  try {
+    atob("foobar!!");
+  } catch (DOMException) {
```
Comment (kitsonk) [inline cli/tests/unit/text_encoding_test.ts:57]: This unit test needs to:

- Check that the caught error is an instance of DOMException
- Validate that the `toString()` of the caught error starts with the text `DOMException:`

**Review by kitsonk — CHANGES_REQUESTED** [review]

File: cli/tests/unit/text_encoding_test.ts (hunk 1 above)
Comment (gorogoroumaru) [reply cli/tests/unit/text_encoding_test.ts:57]: When I execute the following on chrome, I get this error.
```
try {
    atob("foobar!!");
} catch (e) {
    console.log(e.toString())
}
```
InvalidCharacterError: Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.

What should I do?

Comment (jaeheonji) [reply cli/tests/unit/text_encoding_test.ts:57]: Hi! @gorogoroumaru, @kitsonk 

What about the following approach?

```javascript
let threw = false;
try {
  ...
} catch (e) {
  if (e instanceof DOMException) {
    threw = true;
  }
}
assert(threw);
```

**Review by jaeheonji — CHANGES_REQUESTED** [review]

File: cli/tests/unit/text_encoding_test.ts [hunk 2]
```diff
@@ -50,6 +50,16 @@ unitTest(function atobThrows2(): void {
   assert(threw);
 });
 
+unitTest(function atobThrows3(): void {
+  let threw = true;
+  try {
+    atob("foobar!!");
+  } catch (DOMException) {
```
Comment (jaeheonji) [inline cli/tests/unit/text_encoding_test.ts:57]: Hi, @gorogoroumaru, @kitsonk

What about following approach?

```javascript
let threw = true;
try {
  ...
} catch (e) {
  if (e instanceof DOMException) {
    threw = false;
  }
}
assert(threw);
```

**Review by jaeheonji — CHANGES_REQUESTED** [review]

File: cli/tests/unit/text_encoding_test.ts (hunk 2 above)
Comment (gorogoroumaru) [reply cli/tests/unit/text_encoding_test.ts:57]: Thank you @jaeheonji!
Looks good!
@kitsonk, how about you?

**Comment by rchougule** [comment]
Hi, was just going via open PRs to learn more about deno and thought of asking this...

Shouldn't we be throwing `InvalidCharacterError` according to the spec here: 
image

https://html.spec.whatwg.org/#dom-atob

Or is it like that should be thrown only if the `decoded` data is invalid? Considering the current changes are regarding the `encoded` data being incorrect...

File: op_crates/web/08_text_encoding.js [hunk 3]
```diff
@@ -105,7 +105,7 @@
     if (rem === 1 || /[^+/0-9A-Za-z]/.test(s)) {
       throw new DOMException(
         "The string to be decoded is not correctly encoded",
-        "DataDecodeError",
+        "DOMException",
```
Comment (jaeheonji) [inline op_crates/web/08_text_encoding.js:108]: The `atob()` should display a `DOMException` error when the parameter is not base64 encoded data.
In the current testcase, since `foobar!!` is not base64 encoded data, it is correct for an exception to occur.

But, In [MDN](https://developer.mozilla.org/en-US/docs/Web/API/DOMException) docs, The second property of `DOMException` is the name of the error. 

So, @gorogoroumaru, As mentioned by @rchougule, It seems more reasonable for us to rename the error to `InvalidCharacterError`.

**Comment by gorogoroumaru** [comment]
Thank you @rchougule and @jaeheonji!
I applied your suggested changes.

**Review by kitsonk — APPROVED** [review]
LGTM
