### PR TITLE
fix(npm): improve error message on directory import in npm package

### LINKED ISSUE #19366: Improve directory import error
We currently give a confusing error message:

```
error: Unable to load C:\Users\Alexander\AppData\Local\deno\npm\registry.npmjs.org\lostjs\1.1.14\common imported from file:///D:/Alexander/Documents/vsc-workspace/LostJS.page/test.ts

Caused by:
    Access is denied. (os error 5)
```

We should do something like what node does:

```
Error [ERR_UNSUPPORTED_DIR_IMPORT]: Directory import 'C:\Users\WDAGUtilityAccount\test\node_modules\lostjs\common' is not supported resolving ES modules imported from C:\Users\WDAGUtilityAccount\test\index.mjs
Did you mean to import lostjs/common/index.js?
```

Ref #19365 and some other issues.

### PR DESCRIPTION
**Pull request by ElianCordoba**
Old error:

```
error: Unable to load /Users/eliancordoba/Library/Caches/deno/npm/registry.npmjs.org/lostjs/1.1.14/common imported from file:///Users/eliancordoba/repos/clones/deno/.vscode/tests/bad-error.ts

Caused by:
    Is a directory (os error 21)
```

New error:

```
error: Directory import /Users/eliancordoba/Library/Caches/deno/npm/registry.npmjs.org/lostjs/1.1.14/common is not supported resolving import from file:///Users/eliancordoba/repos/clones/deno/.vscode/tests/bad-error.ts

Caused by:
    Is a directory (os error 21)
```
 
I think we should remove the `file` protocol but I'll leave it up to you

cc @dsherret

Closes #19366

### CODE REVIEW

**Review by aapoalas — DISMISSED** [review]
Looks good to me (especially with the TODO), but a test is failing: `nonexistent_file` test needs its expectations updated.

File: cli/module_loader.rs [hunk 1]
```diff
@@ -748,11 +748,13 @@ impl NpmModuleLoader {
       .read_to_string(&file_path)
       .map_err(AnyError::from)
       .with_context(|| {
-        let mut msg = "Unable to load ".to_string();
+        let mut msg =
+          "Error [ERR_UNSUPPORTED_DIR_IMPORT]: Directory import ".to_string();
```
Comment (dsherret) [inline cli/module_loader.rs:752]: This is being done even if it's not a directory. I'll push a change with some fixes.

**Review by dsherret — APPROVED** [review]
LGTM
