### PR TITLE
fix(std/tesing/asserts): `assertEquals/NotEquals` should take into account the milliseconds part of the Date

### LINKED ISSUE #6643: `assertEquals` ignores the milliseconds part of the Date
## Steps to reproduce

```typescript
import { assertEquals } from "https://deno.land/std@0.60.0/testing/asserts.ts";

const date1 = new Date();
const date2 = new Date(date1);
date2.setMilliseconds(date1.getMilliseconds() + 1);
assertEquals(date1, date2);
```

**Expected behavior**:

The above code should fail.

**Actual behavior**:

The above code doesn't fail.

## Environment
- deno v1.1.3
- std v0.60.0

### PR DESCRIPTION
**Pull request by uki00a**
Closes #6643

- This change causes the failure of [`[fs] copy with preserve timestamps`](https://github.com/denoland/deno/blob/e4e80f20c2f85cfb9ea1ae1a499ac24fd206f99b/std/fs/copy_test.ts#L136) case.
  - It should be re-enabled when #5065 is resolved.

### CODE REVIEW

File: std/fs/copy_test.ts [hunk 1]
```diff
@@ -132,7 +144,8 @@ testCopy(
   }
 );
 
-testCopy(
+// TODO(#6644) This case is ignored because of the issue #5065.
```
Comment (uki00a) [inline std/fs/copy_test.ts:147]: See https://github.com/denoland/deno/issues/5065
