### PR TITLE
Fix import map panics, use import map's location as its base URL

### LINKED ISSUE #2769: Import map panics
Panics when
- One is specified for REPL mode. [cli/state.rs#L198](https://github.com/denoland/deno/blob/9bd473d8ac9228e483bd26028dbe7ba88e971c08/cli/state.rs#L198)
- It doesn't exist or can't be read. (could be merged into and solved with the next case). [cli/import_map.rs#L58](https://github.com/denoland/deno/blob/9bd473d8ac9228e483bd26028dbe7ba88e971c08/cli/import_map.rs#L58)
- Any other `ImportMapError` occurs like parse failure, etc. [cli/state.rs#L200](https://github.com/denoland/deno/blob/9bd473d8ac9228e483bd26028dbe7ba88e971c08/cli/state.rs#L200)

### PR DESCRIPTION
**Pull request by nayeem-rahman**
Fixes #2769

Panics when
- [x] One is specified for REPL mode. [cli/state.rs#L198](https://github.com/denoland/deno/blob/9bd473d8ac9228e483bd26028dbe7ba88e971c08/cli/state.rs#L198)
- [x] It doesn't exist or can't be read. [cli/import_map.rs#L58](https://github.com/denoland/deno/blob/9bd473d8ac9228e483bd26028dbe7ba88e971c08/cli/import_map.rs#L58)
- [x] Any other `ImportMapError` occurs like parse failure, etc. These properly propagate to main.rs but get unwrapped there. [cli/main.rs#L200](https://github.com/denoland/deno/blob/9bd473d8ac9228e483bd26028dbe7ba88e971c08/cli/main.rs#L119)

Also:
- [x] Use import map's location as its base URL.
- [x] Add tests.

### CODE REVIEW

File: cli/state.rs [hunk 1]
```diff
@@ -195,9 +196,14 @@ impl ThreadSafeState {
...
           Some(module_specifier) => module_specifier.clone(),
-          None => unreachable!(),
+          // Dummy child of the CWD.
+          None => ModuleSpecifier::resolve_url_or_path("_").unwrap(),
         };
-        let import_map = ImportMap::load(&base_url.to_string(), file_name)?;
+        let import_map = ImportMap::load(&base_url.to_string(), file_name)
+          .unwrap_or_else(|err| {
+            eprintln!("{}", err.to_string());
+            process::exit(1);
```
Comment (ry) [inline cli/state.rs]: This seems wrong. Why doesn't raising the error work?

Can you add tests?

File: cli/import_map.rs [hunk 2]
```diff
@@ -53,13 +53,15 @@ impl ImportMap {
...
-      ),
-    }
+    fs::read_to_string(&resolved_path)
+      .map_err(|err| {
+        ImportMapError::new(&format!(
+          "Error retrieving import map file at \"{}\": {}",
+          resolved_path.to_str().unwrap(),
+          err.to_string()
+        ))
+      })
```
Comment (ry) [inline cli/import_map.rs]: Looks good

Comment (bartlomieju) [reply cli/import_map.rs]: I think the error type should be changed to eg. `InvalidInput` - it's not an ImportMapError per se, now I think it should only be used when there's resolution error related to import map or it's structure is invalid. It's similar to how `tsconfig.json` is treated.

File: cli/state.rs [hunk 3]
```diff
@@ -195,9 +196,14 @@ impl ThreadSafeState {
       Some(file_name) => {
         let base_url = match &main_module {
           Some(module_specifier) => module_specifier.clone(),
-          None => unreachable!(),
+          // Dummy child of the CWD.
+          None => ModuleSpecifier::resolve_url_or_path("_").unwrap(),
```
Comment (bartlomieju) [inline cli/state.rs]: It's not dummy - `main_module` would then actually be file `_` in cwd, it's not right. It should be just cwd

File: cli/state.rs (hunk 1 above)
Comment (nayeem-rahman) [reply cli/state.rs]: It's being unwrapped in main.rs. You're right, I'll exit there instead.

File: cli/state.rs (hunk 3 above)
Comment (nayeem-rahman) [reply cli/state.rs]: Yes, this is an ugly workaround because `base_url` is taken as a sibling, not as a parent. Either import_map.rs or `Url::join()` needs to be refactored so it takes a parent (the `_` would change to a `.` in that case).

I found that `Url::join()` also works desirably with the CWD with a slash at the end:
```rust
let base_url = match &main_module {
  Some(module_specifier) => module_specifier.to_string(),
  None => {
    format!("file://{}/", env::current_dir().unwrap().to_str().unwrap())
  }
};
let import_map = ImportMap::load(&base_url, file_name)?;
```
Would this have been better?

Comment (bartlomieju) [reply cli/state.rs]: @nayeem-rahman yes, that should work, I'd suggest going with:
```
let base_url = match &main_module {
  Some(module_specifier) => module_specifier.to_string(),
  None => {
    Url::from_file_path(env::current_dir().unwrap()).unwrap()
  }
};
```

Comment (nayeem-rahman) [reply cli/state.rs]: It's not working correctly. Like I said, the import map root is set to the parent of whatever `base_url` you give so it works properly when you give `main_module`. If you want to make the CWD the root, you have to give some child of the CWD (or you can put a slash at the end like I snippeted, but there is no suitable API that produces this naturally).

Comment (nayeem-rahman) [reply cli/state.rs]: You can test it like this:
./a.js:
```js
import("mappedToB").then(console.log).catch(console.error);
```
./b.js:
```js
export const data = 10;
```
./importmap.json:
```json
{
  "imports": {
    "mappedToB": "./b.js"
  }
}
```
Run `cat a.js | target/debug/deno --importmap importmap.json`.
If it works you'll see `{ data: 10 }`, otherwise you'll see an error saying that b.js couldn't  be found and that it was searching in the parent directory.

Comment (bartlomieju) [reply cli/state.rs]: Alright, I'm fine with your solution. My only concern is it will work on Windows properly, but we'll see on CI :)

File: cli/import_map.rs (hunk 2 above)
Comment (nayeem-rahman) [reply cli/import_map.rs]: @bartlomieju I thought that was the case, and even considered returning `Result<Result<Self, ImportMapError>, io::Error>>` :( In the end I decided it would be simplest to just re-imagine the meaning of `ImportMapError`, but I'm not sure. Is there a better way of handling both error types? Or is the nested `Result` alright?

Comment (bartlomieju) [reply cli/import_map.rs]: You can just change the signature of `load` to: `pub fn load(base_url: &str, file_name: &str) -> Result<Self, InvalidInput>` or `pub fn load(base_url: &str, file_name: &str) -> Result<Self, ErrBox>`. Both `ImportMapError` and `InvalidInput` can be downcast to `ErrBox` which encapsulates error handling in `//cli`

Comment (nayeem-rahman) [reply cli/import_map.rs]: @bartlomieju Done. Thanks 👍

File: cli/state.rs (hunk 3 above)
Comment (nayeem-rahman) [reply cli/state.rs]: @bartlomieju Wait a minute. Shouldn't the import map root be the import map's directory? It's currently being set to to the _main module_'s directory (or newly the CWD if there isn't one), but it should be the import map's location in both cases according to the spec. Was this a mistake?

**Comment by ry** [comment]
Can these panics be demonstrated in the unit tests? Can you give an example of a call that panics currently?

File: cli/state.rs (hunk 3 above)
Comment (bartlomieju) [reply cli/state.rs]: @nayeem-rahman I don't think that's true, could you link relevant part of spec?

Comment (nayeem-rahman) [reply cli/state.rs]: @bartlomieju https://github.com/WICG/import-maps#bare-specifiers-for-javascript-modules
> In the case of relative-URL-like addresses, they are resolved relative to the import map's base URL, i.e. the base URL of the page for inline import maps, and the URL of the import map resource for external import maps.

Comment (bartlomieju) [reply cli/state.rs]: Hm that's valid then :+1: not sure how I missed that... Well since we're using URL to specify import map I guess we should treat it as external import map.

**Comment by nayeem-rahman** [comment]
@ry 
```shell
deno --importmap importmap.json
```
where importmap.json exists, and
```shell
deno --importmap importmap.json main.js
```
where importmap.json does not exist, isn't valid JSON or doesn't meet the requirements of an import map. Regarding rust land tests, I'm not familiar with the architecture but I may be able to figure it out today.

File: cli/state.rs (hunk 3 above)
Comment (nayeem-rahman) [reply cli/state.rs]: In light of this, I've moved the base URL resolution inside `ImportMap::load()` and the API is significantly simpler: https://github.com/denoland/deno/pull/2770/commits/b055ac276fa848880f8f39326c2b0e48ce3b0f91

File: tests/error_016_import_map_malformed.test [hunk 4]
```diff
@@ -0,0 +1,4 @@
+args: run --reload --importmap=tests/importmaps/malformed_import_map.json_ tests/importmaps/test.ts
```
Comment (ry) [inline tests/error_016_import_map_malformed.test]: integration tests are relatively close compared to unit tests. Is it possible to test this within cli/importmap.rs ?

Comment (nayeem-rahman) [reply tests/error_016_import_map_malformed.test]: @ry I would only be able to test if `ImportMap::from_json()` and friends return a nice `ImportMapError` instead of panicking, which they already did. The problem was that this `ImportMapError` was being unwrapped in main.rs.

**Comment by nayeem-rahman** [comment]
@ry I was pretty rigorous about checking that the tests would fail before, but I rebased above them so you can verify if you want to.

**Comment by nayeem-rahman** [comment]
@ry Done.

As you suggested I scrapped the integration tests. I've added a unit test each for the first 2 cases, but the third case was fixed by nicely exiting on a `ThreadSafeState::new()` error in main.rs. That one has a broader scope and I'm not sure how to approach it without an integration test, so I'll leave it to someone else.

File: tools/integration_tests.py [hunk 5]
```diff
@@ -87,7 +87,10 @@ def generate(self, test_filename):
             else:
                 # No stdin sent
                 actual_out = subprocess.check_output(
-                    cmd, universal_newlines=True, stderr=stderr)
+                    cmd,
+                    universal_newlines=True,
+                    stdin=open(os.devnull, 'r'),
+                    stderr=stderr)
```
Comment (ry) [inline tools/integration_tests.py]: This change can be left out now

Comment (nayeem-rahman) [reply tools/integration_tests.py]: @ry Done 👍
