### PR TITLE
fix(core,ext): Fix not to be affected by `Promise.prototype.then`

### LINKED ISSUE #16196: Overriding `Promise.prototype.then` affects runtime
~~`SafePromise` is exported by primordials, but functions that return native `Promise` such as `PromisePrototypeThen` are used in the internal code, so it is possible to interrupt any process by overriding `Promise.prototype.then` as follows:~~

```js
const originalThen = Promise.prototype.then;
Promise.prototype.then = function (...args) { console.log("bang!"); return originalThen.call(this, ...args) };
```

~~This probably happens because the `await` operator executes the `"then"` method of the received "thenable" regardless of whether it is a Promise or not. To solve this, I believe we need to make one of the following choices:~~

* ~~Do not use the `await` operator~~
* ~~Provide wrappers for all `Promise` methods by primordials so that they are always wrapped in `SafePromise`~~

----

After reading the spec in detail, it appears that the problem is not caused by the `await` operator, but by calling the `"then"` method directly. I will try to fix the problem and submit a PR.

### PR DESCRIPTION
**Pull request by petamoriken**
fix #16196

### CODE REVIEW

**Comment by petamoriken** [comment]
It seems that if I rewrite `Promise.prototype.then` in repl yet, it will be called. Maybe we need to disallow `await`.

**Comment by petamoriken** [comment]
I ran the following file and had no problem. It seems that the problem is not with `await`, but with `Promise.prototype.then` being called somewhere in the repl.

```js
console.log("start");

const original = Promise.prototype.then;
Promise.prototype.then = function () {
  console.log("bang!");
  return original.apply(this, arguments);
};

await new Promise((resolve) => setTimeout(resolve, 100));

console.log("end");
```

File: core/00_primordials.js [hunk 1]
```diff
@@ -436,6 +442,24 @@
   primordials.PromisePrototypeCatch = (thisPromise, onRejected) =>
     PromisePrototypeThen(thisPromise, undefined, onRejected);
 
+  primordials.SafePromiseAll = (iterable) =>
+    // Wrapping on a new Promise is necessary to not expose the SafePromise
+    // prototype to user-land.
```
Comment (kt3k) [inline core/00_primordials.js:447]: Is it unsafe to expose `SafePromise.prototype` to user-land? I think it can't be modified even if it's exposed because it's frozen. (I might be missing something...

**Comment by kt3k** [comment]
Can you add some integration test cases that modify `Promise.prototype.then` and check the behaviors of APIs which were vulnerable before this change?

File: core/00_primordials.js (hunk 1 above)
Comment (petamoriken) [reply core/00_primordials.js:447]: This implementation is referenced from `SafePromisePrototypeFinally`. I think it is meant to prevent the internal code from being strangely utilized in user-land.
https://github.com/denoland/deno/blob/45ac6e602da9cd016d4a3b093fd4873b90897f9a/core/00_primordials.js#L439-L455

**Comment by petamoriken** [comment]
@kt3k I added tests for `Deno.serve` and `Deno.spawn`.

**Review by kt3k — APPROVED** [review]
LGTM

**Comment by kt3k** [comment]
While `SafePromiseAll` is good for preventing tampering of `Promise.prototype.then`, we need to be careful to use it as it seems having performance penalty compared to `Promise.all`.

I think the usages of `SafePromiseAll` in this PR doesn't affect hot paths of benchmarks we've been tracking in the benchmark page.

But can anyone double check the above just in case?

**Comment by magurotuna** [comment]
Great to see it's landed! Is it also good to have some lint rule to enforce (or at least make developers be aware of) the use of these new `SafePromise` stuff?

**Comment by kt3k** [comment]
> Is it also good to have some lint rule to enforce (or at least make developers be aware of) the use of these new SafePromise stuff?

That makes sense to me. `SafePromiseAll` is added in this PR and I think that can be checked by the linter. I'm not sure if we can do similar check for `PromisePrototypeThen` as it probably requires the type inference of objects..

**Comment by magurotuna** [comment]
> I'm not sure if we can do similar check for PromisePrototypeThen as it probably requires the type inference of objects..

Yeah that's true. My rudimentary idea is that we have the linter check for all `.then(...)` and warn them. Yes, this approach would produce lots of false positives, i.e. the linter would warn the call `.then(...)` even if this `then` method is not for Promise.
In my opinion, however, false positives are much better than false negatives in this case. When false positives occur we can suppress them, saying "hey linter, trust me, this is a false positive." However, when it comes to false negatives, we can never notice that there is problematic code that's prone to pollution from malicious users.

**Comment by magurotuna** [comment]
Opened an issue for deno_lint https://github.com/denoland/deno_lint/issues/1095
