### PR TITLE
fix(npm): improve exports resolution when type checking

### LINKED ISSUE #17012: npm: unable load react-dom/client types from @types/react-dom
Deno LSP is unable to process this:

```tsx
// @deno-types="npm:@types/react-dom/client"
import { createRoot } from 'npm:react-dom/client"
```

Deno version: 1.28.3
VS Code LSP version: 3.14.1

### PR DESCRIPTION
**Pull request by dsherret**
Closes #17012

### CODE REVIEW

**Review by bartlomieju — APPROVED** [review]
LGTM

File: ext/node/errors.rs [hunk 1]
```diff
@@ -61,13 +63,26 @@ pub fn err_invalid_package_target(
 ) -> AnyError {
   let rel_error = !is_import && !target.is_empty() && !target.starts_with("./");
   let mut msg = "[ERR_INVALID_PACKAGE_TARGET]".to_string();
+  let pkg_json_path = PathBuf::from(pkg_path).join("package.json");
```
Comment (jimisaacs) [inline ext/node/errors.rs:66]: @dsherret judging from this line, I'm thinking it should address the `deno test` error I referenced here https://github.com/denoland/deno/issues/16653#issuecomment-1355167325

Comment (dsherret) [reply ext/node/errors.rs:66]: Yup it will. The error you got was what it used to give with `deno check` or `deno test` (since `deno test` does type checking).
