### PR TITLE
fix(outdated): support updating dependencies in external import maps

### LINKED ISSUE #27331: `deno outdated` lies about updating dependencies
Version: Deno 2.1.3

When using an import map instead of listing imports directly in `deno.json`, Deno can correctly list which imports are outdated, but when you do `deno outdated --update --latest`, it says it updated the dependencies and lists them, but hasn't actually changed any files. The import map is left untouched.

### PR DESCRIPTION
**Pull request by nathanwhit**
Fixes #27331.

The support for it was already in `outdated`, but forgot to wire up the updating part

Needs #27337

### CODE REVIEW

File: cli/tools/registry/pm/deps.rs [hunk 1]
```diff
@@ -249,7 +253,7 @@ fn deno_json_import_map(
         Some(path) => {
           let text = std::fs::read_to_string(&path)?;
           let value = serde_json::from_str(&text)?;
```
Comment (dsherret) [inline cli/tools/registry/pm/deps.rs:255]: We should add some context about what this is loading when this fails.

**Review by dsherret — APPROVED** [review]
LGTM
