### PR TITLE
fix(config): regression - handle relative patterns with leading dot slash

### LINKED ISSUE #21916: [Bug test] deno test: error: No test modules found
Version: Deno 1.39.3: https://github.com/poolifier/poolifier-deno/actions/runs/7506348228/job/20437633353 =>  error: No test modules found
Version: Deno 1.39.2: https://github.com/poolifier/poolifier-deno/actions/runs/7506478378/job/20437982957 => no error

100% reproducible in GitHub CI.

### PR DESCRIPTION
**Pull request by dsherret**
This is a hacky quick fix. We need to spend more time cleaning up this code and push more stuff down into deno_config.

Closes #21916

### CODE REVIEW

File: cli/util/glob.rs [hunk 1]
```diff
@@ -248,9 +248,11 @@ impl GlobPattern {
   }
 
   pub fn new(pattern: &str) -> Result<Self, AnyError> {
-    let pattern =
-      glob::Pattern::new(&escape_brackets(pattern).replace('\\', "/"))
-        .with_context(|| format!("Failed to expand glob: \"{}\"", pattern))?;
+    let pattern = escape_brackets(pattern)
+      .replace('\\', "/")
+      .replace("/./", "/");
```
Comment (jerome-benoit) [inline cli/util/glob.rs:253]: Wouldn't it be better to construct each time the absolute path from the relative path instead of building a relative path compliant pattern? 
I do not know what is the exact expected usage of that glob expansion code but that does not look right to do path munging in code dedicated to glob handling.

Comment (dsherret) [reply cli/util/glob.rs:253]: Yeah that's what's done in the real fix in https://github.com/denoland/deno/pull/21925

It requires a much larger refactor to do that though.

**Review by bartlomieju — APPROVED** [review]
