### PR TITLE
fix(repl): don't hang on unpaired braces

### LINKED ISSUE #8150: repl: unpaired braces cause input never consumed
Entering a single ']' would cause repl to forever accepting new lines, due to that `ValidationResult::Invalid` would actually be consumed by the editor itself while continue building the lines. Instead we should mark it as `Valid` and send the bad input for evaluation to get the proper error from V8.

Example:

```
$ deno
> ]
(you can keep entering new line here, and it will never consume input until you Ctrl-C)
```

### PR DESCRIPTION
**Pull request by kevinkassimo**
Fixes #8150

Previously, entering a single ']' would cause repl to forever accepting new lines, due to that `ValidationResult::Invalid` would actually be consumed by the editor itself while continue building the lines. Instead we should mark it as `Valid` and send the bad input for evaluation to get the proper error from V8.

* Before:

```
> ]
(you can keep entering new line here, and it will never consume input
until you Ctrl-C)
```

* After:

```
> ]
Uncaught SyntaxError: Unexpected token ']'
>
```

### CODE REVIEW

File: cli/tests/integration_tests.rs [hunk 1]
```diff
@@ -1516,6 +1516,21 @@ fn repl_test_eval_unterminated() {
   assert!(err.is_empty());
 }
 
+#[test]
```
Comment (caspervonb) [inline cli/tests/integration_tests.rs:1519]: Validator only runs with tty so needs to be tested with pty.

Comment (kevinkassimo) [reply cli/tests/integration_tests.rs:1553]: pty is not suffering from the issue. Added a test anyways.

Comment (caspervonb) [reply cli/tests/integration_tests.rs:1553]: > pty is not suffering from the issue.

Hmm really? It should be, went through the call tree a few days ago in rustyline and the validator trait is not used at all when input is a file (e.g stdin).

Comment (kevinkassimo) [reply cli/tests/integration_tests.rs:1553]: Reason is this part of the code:
https://github.com/kkawakam/rustyline/blob/e9a5ccdc4f24c4a73053e6cf8897c186da5981da/src/lib.rs#L871-L876
For pty case, rustyline calls `readline_direct` which only considers newline and does not run validator, as you mentioned:
https://github.com/kkawakam/rustyline/blob/e9a5ccdc4f24c4a73053e6cf8897c186da5981da/src/lib.rs#L757-L764

**Review by caspervonb — APPROVED** [review]
LGTM, thank you very much @kevinkassimo 😁

**Review by ry — APPROVED** [review]
LGTM - thanks Kevin!

I confirmed that your test creates a hang on master.

**Comment by ry** [comment]
@caspervonb This validator is basically implementing a parser. It's unfortunate that we're only able to test it with super high-level integration tests involving lots of I/O pty, fork etc. Is there some way to *unit* test this little parser? Ideally the fix here would have involved a simple unit test only in cli/repl.rs

**Comment by caspervonb** [comment]
>  Is there some way to unit test this little parser? Ideally the fix here would have involved a simple unit test only in cli/repl.rs

We can just instantiate the helper and test that, even simpler if we extract the validator into a struct since that would require zero mocking.

But I think we should probably just bring in swc and use that to parse this instead, starting to hit a lot of cases where we need to do more thorough parsing so would be better to let a good parser handle it.

See also #8160
