### PR TITLE
fix: don't unwrap in test pipe handling logic

### LINKED ISSUE #14746: Deno Panic
Reporting Deno panic. I cannot isolate a small enough piece of code but reporting in case the backtrace is useful.

```
============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: macos aarch64
Version: 1.22.0
Args: ["deno", "test", "-A", "--fail-fast", "test/list-events.test.ts"]

thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }', cli/tools/test.rs:1631:56
stack backtrace:
   0:        0x102d6c814 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hd6a6e3b094c481b1
   1:        0x102636790 - core::fmt::write::h55deb439a2fa505d
   2:        0x102d57318 - std::io::Write::write_fmt::hdd0ccc220f7ec3f7
   3:        0x102d6338c - std::panicking::default_hook::{{closure}}::haecbbf48cd1ad553
   4:        0x102d6300c - std::panicking::default_hook::hdf33d6d87b6673e5
   5:        0x1024d2f98 - deno::setup_panic_hook::{{closure}}::h0ebb0b0dd9dc4adf
   6:        0x102d63e78 - std::panicking::rust_panic_with_hook::ha19270fc750e5dcf
   7:        0x102d6cb60 - std::panicking::begin_panic_handler::{{closure}}::h520977148193b087
   8:        0x102d6cae0 - std::sys_common::backtrace::__rust_end_short_backtrace::h563c939a775416b3
   9:        0x102d637e4 - _rust_begin_unwind
  10:        0x10263a66c - core::panicking::panic_fmt::h0908dd8514c30916
  11:        0x102642570 - core::result::unwrap_failed::ha509accbcac71268
  12:        0x1024d8e78 - core::result::Result<T,E>::unwrap::h1318faaec3e9a32e
  13:        0x1024a67b0 - deno::tools::test::TestOutputPipe::flush::hac5fe41a5649929e
  14:        0x1024a64d4 - deno::tools::test::TestEventSender::send::hc0a827858c55dfa6
  15:        0x1024e2584 - <extern "C" fn(A0) .> R as v8::support::CFnFrom<F>>::mapping::c_fn::hbfa21c54484da46d
```

### PR DESCRIPTION
**Pull request by crowlKats**
Fixes #14746

### CODE REVIEW

File: cli/tools/test.rs [hunk 1]
```diff
@@ -1600,16 +1600,18 @@ impl TestEventSender {
         | TestEvent::StepResult(_, _, _)
         | TestEvent::UncaughtError(_, _)
     ) {
-      self.flush_stdout_and_stderr();
+      self.flush_stdout_and_stderr()?;
```
Comment (dsherret) [inline cli/tools/test.rs:1603]: Do you know why the panic occurred in the first place? I wonder if converting this to an error will hide an underlying problem. I think probably not a big deal and this is ok? I can't remember this code that well though 😅

Comment (crowlKats) [reply cli/tools/test.rs:1603]: > Do you know why the panic occurred in the first place?

No clue

> I wonder if converting this to an error will hide an underlying problem.

Yea thats one of my concerns as well; but i also think its not a big deal

Comment (bartlomieju) [reply cli/tools/test.rs:1603]: There are several issue reported like this - they are mostly caused by piping output of `deno` commands to another program (like `less` or `grep`). https://github.com/denoland/deno/pull/17152 was an attempt to solve it for all prints in the code base.

Comment (dsherret) [reply cli/tools/test.rs:1603]: I think something is supposed to wait for all this code to finish before tearing down to ensure the pipes have something to send to, but maybe waiting is impractical. It's maybe better to have reports of some test output not displaying (which might now be surfaced somewhere as an error) instead of a panic. I'll approve the PR.

**Review by dsherret — APPROVED** [review]
LGTM, but see comment https://github.com/denoland/deno/pull/17341/files#r1067578874
